### ISSUE TITLE
Package api docs on zipkin-query-service

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1002]
It would be nice to host the openapi docs on the query server, so people using it can discover how to use the api. I suspect there will be steps to take in multiple repos, and decisions to make.

Probably we want to package a jar, so that existing apps can import them. For example add the api docs under, `META-INF/resources/api/v1` to match servlet-style resource mappings.

Ex. if we had this, you could go to http://zipkinquery:9411/api/v1 in the browser, which would look like http://openzipkin.github.io/zipkin-api/#/

We'd want to be careful not to intrude on the efforts to re-host the zipkin javascript UI onto the query server.

**Comment by codefromthecrypt** [comment]
cc @mohsen1 @eirslett @yurishkuro @dsyer @abesto @jcarres-mdsol

**Comment by eirslett** [comment]
That should work well together with the javascript UI. As long as every API call is under /api/v1, then we can return assets for all other endpoints.

**Comment by yurishkuro** [comment]
sounds like a cool feature, although not clear who the intended audience is. I do have one team who wants to read `/dependencies` endpoint for some other SRE service, but not really the query API.

**Comment by mohsen1** [comment]
The swagger-docs project has a configuration capability to load different api specs. Maybe you can take advantage of that and host the UI itself outside of query server.

**Comment by codefromthecrypt** [comment]
fyi /dependencies is in what I'm calling the "query api". basically the
docs are for everything under /api/v1. A request was made to host api
documentation on the api root (vs 404)

**Comment by abesto** [comment]
I'm +1 for the idea, I love self-describing APIs. Not sure about how / what other, existing apps would want to import from this? Would those other apps also serve the same API description? Or is that about distributing the machine-readable API spec?

**Comment by codefromthecrypt** [comment]
I think the packaging step is helpful for derivative work. For example, the
scala impl may expose static static assets differently that spring boot.
For example, spring boot might use "web jars".

In any case, the goal is the same, which is to add documentation to a
complete implementation of the zipkin api. We put effort into getting docs
together and this is a concrete way to put it in front of users.

**Comment by codefromthecrypt** [comment]
#1959
