### ISSUE TITLE
Thrift-less cassandra schema

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1009]
Both @michaelsembwever and @yurishkuro hinted that a thrift-less cassandra schema might be useful. Let's evaluate what such a schema might look like and a transition plan.

**Comment by jorgheymans** [comment]
Is the thrift-less Cassandra scheme not this https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/cassandra (as opposed to the older, thrift-ful one here https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/cassandra-v1) ?

If yes then we're good to close this (and #1008 as well most likely)

**Comment by codefromthecrypt** [comment]
haha yeah @michaelsembwever sorted this ages ago
