### ISSUE TITLE
[1.33.2] Scribe rpc seems to stuck

### ISSUE THREAD

**Issue by lycplus** [openzipkin/zipkin#1015]
After we upgrading from 1.25.3 to 1.33.2, we found every now and then, there are not any trace data. After adding some logging, we found that initially it works as expected, but after 1 minute or so, it stucks at `ScribeClient.Log` (we tried many times, it happened every time). Attached is our main collector code, we collect list of spans from our application, and sends to zipkin collector via a single `Log` call.

[scribe_stuck.txt](https://github.com/openzipkin/zipkin/files/159844/scribe_stuck.txt)
[zipkinCore.txt](https://github.com/openzipkin/zipkin/files/159845/zipkinCore.txt)
[scribe.txt](https://github.com/openzipkin/zipkin/files/159846/scribe.txt)

**Comment by lycplus** [comment]
ScribeClient:

```
    socket, err := thrift.NewTSocket(zipkinAddr)
    if err != nil {
        log.Printf("Failed to create socket: %v\n", err)
        return
    }
    btrans := thrift.NewTFramedTransport(socket)
    proto := thrift.NewTBinaryProtocolTransport(btrans)
    if err = btrans.Open(); err != nil {
        log.Printf("Failed to connect to zipkin: %v\n", err)
        return
    }
    defer btrans.Close()

    scribeClient := scribe.NewScribeClientProtocol(btrans, proto, proto)
```

Every time it stucks, there is a zipkin Collector log which I do not understand:

```
Mar 05, 2016 9:20:25 PM com.twitter.finagle.mux.ServerDispatcher com$twitter$finagle$mux$ServerDispatcher$$process
WARNING: Received duplicate tag 2 from client /127.0.0.1:50796
```

I confirm that `50796` is the port my collector uses to connect to zipkin collector.

**Comment by lycplus** [comment]
Hi, It seems it is a bug in finagle 6.33.0, any plan to update fingale to 6.34.0 ?

**Comment by codefromthecrypt** [comment]
sure.. just need to make sure finatra is compatible with it...
