### ISSUE TITLE
Future Zipkin architecture (post-UI-refactoring)

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin#1019]
The work on refactoring the UI is complete - it's now just a bundle of assets, with client-side rendering, and it talks to Zipkin via the query HTTP API.

Should we go ahead and move zipkin-web into zipkin-query? It's already been discussed, my impression is that most people want to go in that direction. In which case I suggest we change the zipkin-web gradle build; delete all the Scala code, and produce a .zip file (or .tar/tar.gz) with the static assets. Gradle basically becomes a thin wrapper around npm/webpack.
Then, zipkin-query can import that artifact as a dependency, and serve the static assets.
This means zipkin-java can also import the same dependency.

While we're at it - we could also merge zipkin-collector and zipkin-web into one application. Possibly with a configuration option to only enable the "collector" role, the "query" role, or the "all" role. Zipkin is known to be hard to deploy, operations-wise; if we could reduce the number of separate applications to run from 3 to 1, that would be a huge win. Also, from a zipkin developer perspective, I'm sure our code base could look a lot simpler, with fewer submodules.

**Comment by codefromthecrypt** [comment]
I agree with everything you've said. For example zipkin-java calls the
server simply zipkin-server. I will be writing the Kafka listener this
week, which would be an optional module. The same base code can be
configured in clusters which have different roles, as necessary.

Ex it could be deployed to a "web" cluster or a "collection" cluster with
different heap args and options. The configuration story is easier to deal
with when there's a single entry point, and modularization at the component
level keeps the codebase clean.

**Comment by codefromthecrypt** [comment]
Incidentally, I think @yurishiko already bundles query and web in the same
process!

**Comment by codefromthecrypt** [comment]
Here's a rough transition plan idea:
- move zipkin-web's assets and tests to a separate repo (non-gradle). This
  would make it more natural to maintain.
- Once above is in, have the "old zipkin-web" import those assets, so that
  it is drop-in, similarly do the same in zipkin-query (I suppose adding the
  config endpoint?). we cut a release where the experience from a packaging
  POV is the same.
- Next release would be to drop the "zipkin-web" in scala, suggesting folks
  just deploy zipkin-query over their old zipkin-web deployment (should they
  still want 3-tier). This also affects our docker deployments.

**Comment by eirslett** [comment]
@abesto Do you have any input on how we could publish the UI to some remote artifact repo, and then re-fetch it for zipkin-web/zipkin-query/zipkin-java?
Maybe something like using npm to publish to bintray?

**Comment by abesto** [comment]
There are a lot of unknowns in this for me (that I'd be OK exploring). It looks like https://www.npmjs.com/package/bintray can be used to publish programmatically from NPM / Grunt / whatever to Bintray. The question then is what structure the uploaded package should have. I have practically zero experience on that front, so I'll be asking for help on that front.

**Comment by eirslett** [comment]
Let's start with #1024 as a middle ground for now?

**Comment by eirslett** [comment]
Closing in favor of #1044.
