### ISSUE TITLE
investigate memory leak in kafka receiver

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1021]
from @prat0318 

> i suspect there is memory leak in collector. it hogs mem from 1.5G to 4G in 6-7 hrs. and i notice the duration drastically decreased (from days to hours) after the kafka message peek change... earlier we see a slow mem rise (from 1.5G to 4G in days) but now in hours

**Comment by codefromthecrypt** [comment]
So the pivotal change in the recent commit was how to interpret a byte array.

There is state used at the moment, particulalry BinaryThriftStructSerializer reuses a transport which internally contains a buffer. @prat0318 do you have an example of the OOM involved?

**Comment by prat0318** [comment]
Actually i am not sure, if bumping version from `1.32.3` to `1.35.0` is the main reason. This bump was made on Mar 2, but in the graph below (which shows memory being consumed) the slope didn't change much on that date. (Our service restarts when it reaches the limit of 4G, which shows the sudden drop in memory at 4G)

But we did increase the number of spans being ingested drastically from Mar 3 onwards and that bumped up the memory consumption by collector significantly.

![zipkin memory consumption](http://i.imgur.com/uA5Hpws.png)

Also we turned the span volume down on Mar 9 afternoon and that reflects the decrease in slope. So, my hypothesis says memory consumption gets directly propotional to the no. of spans ingested

**Comment by prat0318** [comment]
I haven't yet tried to attach a profiler but if there is nothing apparent which looks like the cause, will try attaching a profiler sometime.

**Comment by codefromthecrypt** [comment]
Thanks for the detailed notes.

I think it makes sense that memory consumption would be directly related to
the amount of spans being processed.

It may be that we use too much memory, but the problem is not releasing
memory (via garbage collection).

**Comment by codefromthecrypt** [comment]
the code is significantly different now. try the docker image openzipkin/zipkin and see how it goes
