### ISSUE TITLE
Exclude ostrich from zipkin-query-service

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin#1036]
Inside the zipkin-query-service shadowJar, we get a /static/ folder with assets from [ostrich](https://github.com/twitter/ostrich). These resources clash with zipkin-ui assets, that are also in /static/. (After #1035 is merged).
We need to find some way to exclude ostrich from our project - is anybody up for that task?

**Comment by codefromthecrypt** [comment]
To kill an ostrich.. This is what you seek?
