### ISSUE TITLE
Feature Request: Allow receiver-kafka to consume JSON encoded spans

### ISSUE THREAD

**Issue by gena01** [openzipkin/zipkin#1037]
It seems that JSON support has been added to the HTTP API, would be nice to publish JSON encoded spans to Kafka and have the receiver consume that (would also simplify coding on the client side and scaling zipkin).

**Comment by eirslett** [comment]
Maybe we could check whether the first character in a message is [ and if that's the case, interpret it as a json list of spans.

**Comment by codefromthecrypt** [comment]
I'm cool with the peek option. We already have to peek anyway. When we move
to a different model, we'd probably want to use a message key instead, and
it might look like a media type.

ex. application/vnd.zipkin2.tracelist+json

**Comment by eirslett** [comment]
@gena01 Pull requests are always welcome :wink:
I'd say if somebody makes a satisfying implementation of this, we should merge it.

**Comment by codefromthecrypt** [comment]
this is a really good idea. one of the problems with kafka is that it is hard to test. with this change, you can literally use the CLI to post a span onto a topic. cc @prat0318 @kristofa
