### ISSUE TITLE
Remove zipkin-web

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin#1044]
This would involve multiple steps:
- [x] Make zipkin-web a dumb proxy
- [x] Remove the zipkin-web submodule from Gradle
- [ ] Remove references to zipkin-web in documentation (architecture)
- [ ] Provide a migration guide for people who run zipkin-query + zipkin-web today
- [ ] Release new version
- [ ] Deprecate/remove the zipkin-web docker image
- [ ] Communicate the change to external open source projects, like the mesos framework

Is anybody up for it?

**Comment by abesto** [comment]
I'd probably leave a couple weeks, maybe a month "deprecation period". Or alternately define the list of projects we want to make sure migrate to `zipkin-web`-less before deleting it fully. Is that taking things too slowly? (This would mean reordering the steps, providing migration documentation first and deprecation notices, then later removing stuff)

**Comment by eirslett** [comment]
Yes, that sounds like a better idea!

**Comment by codefromthecrypt** [comment]
Yeap. We should probably summarize an email to zipkin-user about this
wonderful progress

**Comment by abesto** [comment]
Wish there was a way to send a pull-request to the description of an issue. How about this:

## Deprecation
- [x] Make zipkin-web a dumb proxy
- [ ] Provide a migration guide for people who run zipkin-query + zipkin-web today
- [ ] Make deprecation workflow explicit; when (time or version) will zipkin-web go away fully?
- [ ] Add deprecation notice to 
  - [ ] zipkin.io?
  - [ ] zipkin README
  - [ ] docker-zipkin README
  - [ ] zipkin-web documentation
  - [ ] Startup messages of zipkin-web
- [ ] Announce deprecation to zipkin-user, zipkin-dev, downstream projects (mesos, what else?)

## Removal
- [ ] Remove the zipkin-web submodule from Gradle
- [ ] Remove references to zipkin-web in documentation (architecture)
- [ ] Release new Zipkin artifacts
- [ ] Deprecate the zipkin-web docker image
- [ ] Remove zipkin-web from docker-zipkin, expose zipkin-query on the old port of zipkin-web
- [ ] Announce removal to same parties as for deprecation

**Comment by codefromthecrypt** [comment]
I think we'll want to bump this out as a repo, still, especially as versions are being cut quickly due to UI fixies that have nothing to do with the scala code. If we did, we could even adjust docker to be able to pull the UI into the server separately. This has the advantage of making UI updates decoupled from server code updates. cc @eirslett @abesto

**Comment by eirslett** [comment]
Given that we're (probably) retiring the Scala code anyways, maybe the UI module can live with zipkin-java? (It stays in this repository openzipkin/zipkin, while the java code is moved from openzipkin/zipkin-java to openzipkin/zipkin)

**Comment by codefromthecrypt** [comment]
yeah that could work, too

**Comment by virtuald** [comment]
Curious, is the plan then to completely remove zipkin-web from anything, or would it live on as a separate project, or is there a replacement? The web UI is a fairly useful thing, as a new user I'd hate to have to create my own version of it...

**Comment by virtuald** [comment]
Nvm, just saw the linked issue.

**Comment by codefromthecrypt** [comment]
only things needed are removal from docker (https://github.com/openzipkin/docker-zipkin/issues/98) and then doc updates

**Comment by abesto** [comment]
Is there still work to be done on this? From what I can tell, this is all done.

**Comment by codefromthecrypt** [comment]
yeah I think it is done
