### ISSUE TITLE
[ui] Make "Expand All" the default view for a trace

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#1046]
Transferring one of our internal tickets. Many users have asked for trace to be fully expanded by default, unless it exceeds a certain N of spans. Especially new users often get confused by seeing incomplete traces by default.

**Comment by eirslett** [comment]
Maybe this could be a configuration option, just like default query limit?
The UI refactoring is pretty much done now, so people can send patches.

**Comment by yurishkuro** [comment]
Yes, definitely should be a config option, like `maxSpanCountForExpandAll`

I haven't seen the new config mechanism yet, do we have docs on how one can change config options at deployment?

**Comment by eirslett** [comment]
No, unfortunately we're lagging behind on that part :-/ You'll have to hard-code it into the config.json handler for now. (There is one handler in zipkin-query and one in zipkin-web, of course it's temporary that it's duplicated)

**Comment by codefromthecrypt** [comment]
weird.. I thought we had another issue on this same topic (of expand-all). can't find it .. shrug!

I prefer expand-all, too, but maybe the trace detail was designed for query (where you had selected a specific service). go to trace probably should default to expand all, regardless.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1326
