### ISSUE TITLE
how to set cassandra only store one month or one week data。

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1054]
i want to only store zipkin data one month in cassandra,  how can i set?

i find cassandra doc write:
If the data is inserted with TTL, and that TTL is the same for all inserts, all data in an SSTable will expire at approximately the same time since TTL is relative to the timestamp of the data.

but i don't find how to set ttl from zipkin

thanks

**Comment by codefromthecrypt** [comment]
@dragontree101 starting with zipkin 1.1, ttls are moved to schema defaults. So, you can change the schema to whatever your preferred expiration is.

https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/cassandra/src/main/resources/cassandra-schema-cql3-upgrade-1.txt
