### ISSUE TITLE
zipkin-web 1.37 and zipkin-query 1.38 (Web UI) returns errors in web console

### ISSUE THREAD

**Issue by gena01** [openzipkin/zipkin#1056]
I am unable to use the latest 1.37 docker container for zipkin-web or just tried zipkin-query 1.38 with the Web UI. When I select a service from the dropdown list I am seeing nothing loading and errors in Web Console in both Firefox and Chrome.

Firefox reports: "too much recursion"
Chrome reports: 

``` text
lodash.js:13824Uncaught RangeError: Maximum call stack size exceeded
object.(anonymous function) @ lodash.js:13824
(anonymous function) @ traceSummary.js:15
6totalServiceTime @ traceSummary.js:161
(anonymous function) @ traceSummary.js:161
totalServiceTime @ traceSummary.js:161
(anonymous function) @ traceSummary.js:161
totalServiceTime @ traceSummary.js:161
(anonymous function) @ traceSummary.js:161
totalServiceTime @ traceSummary.js:161
(anonymous function) @ traceSummary.js:161
```

**Comment by eirslett** [comment]
This is the recursive function that fails:

``` javascript
function totalServiceTime(stamps, acc = 0) {
  if (stamps.length === 0) {
    return acc;
  } else {
    const ts = _(stamps).minBy((s) => s.timestamp);
    const [current, next] = _(stamps)
        .partition((t) =>
          t.timestamp >= ts.timestamp
          && t.timestamp + t.duration <= ts.timestamp + ts.duration)
        .value();
    const endTs = Math.max(...current.map((t) => t.timestamp + t.duration));
    return totalServiceTime(next, acc + (endTs - ts.timestamp));
  }
}
```

Unfortunately, it fails on some traces, but so far it has been difficult to reproduce. @adriancole got the same error, but couldn't reproduce later...

If you set a breakpoint there somewhere, do you see whether `current` and/or `next` is changed from function cal to function call? If not, it results in an infinite loop. The interesting thing is to find the type of data that makes the function loop forever!

**Comment by eirslett** [comment]
I suspect this _may_ be caused by one ore more spans that either miss timestamp or duration. Could that be right? You can see the raw JSON data in the chrome debugger by inspecting the network call.

**Comment by codefromthecrypt** [comment]
Yep missing duration was it.

**Comment by codefromthecrypt** [comment]
released in 1.38.1 please give it a shot!

**Comment by gena01** [comment]
Thank you for fixing this. It's loading now and seems a bit faster. I guess there's no duration if both timestamps match?

**Comment by codefromthecrypt** [comment]
No duration if span.duration wasnt set by instrumentation and any of the
following are true:
- there are no annotations
- all annotations have the same timestamp
- there's a bug in the server ;)
