### ISSUE TITLE
Feature Request: Update response headers in zipkin-query (for zipkin-ui assets)

### ISSUE THREAD

**Issue by gena01** [openzipkin/zipkin#1058]
Please add/update response headers to include "Cache-Control" and/or "Expires" headers when serving zipkin-ui? static files. I see them being reloaded on every page/click.

Also seems like /8b55a822e72b8fd5e2ee069236f2d797.png which might be a favicon returns the following response header

``` text
Content-Type:"image/png;charset=utf-8"
```

This is an image, so no need for charset?

**Comment by eirslett** [comment]
They're definitely supposed to be cached.
If you look at ZipkinQueryController, you could try doing something like this (pseudocode):

``` scala
import com.twitter.conversions.time._ // To get the "10.minutes" syntax sugar
// ...
get("/:*") { request: Request =>
    val resp = response.ok.fileOrIndex(
    request.params("*"),
    "index.html"
    )

    resp.cacheControl = 10.minutes
    resp
  }
```

If it works, and you're in the mood for a PR... well... :wink:

About setting charset=utf-8 when the content type is image/png; that seems more like a bug in Finatra, so it should probably be filed as an issue there.

**Comment by gena01** [comment]
Should i open a separate bug on Last-Modified/If-Modified-Since being missing as well?

**Comment by eirslett** [comment]
I would say they belong to the same issue.
In the long term, we should set something like 1 minute timeout on index.html, and 1 year timeout on the assets - given that we add hashes to the asset names. I think we can do that with webpack.

**Comment by codefromthecrypt** [comment]
there's something to consider in the above logic, which is how to detect if we are serving the content of index.html or not. if we are just going on the path name, it is simpler.

```
resp.cacheControl =  if (isIndex) 365.days else 1.minute
```

**Comment by eirslett** [comment]
Let's go for the path name, but the opposite ;) no caching for api, 1 minute caching for index, 10 minutes for config, 1 year for everything else?

**Comment by codefromthecrypt** [comment]
this is also hard to test, as ZipkinQueryServerFeatureTest doesn't have a classpath reference to the resources built by zipkin-ui. Ex. even if you set the following, it 404s

``` scala
  override val server = new EmbeddedHttpServer(
    new ZipkinQueryServer(spanStore, dependencyStore), extraArgs = Seq(
      // Zipkin's web assets are under the path /zipkin-ui
      "-doc.root", "zipkin-ui",
      // We are using fake times, so make sure default lookback doesn't interfere
      "-zipkin.queryService.lookback", lookbackOverride.toString
    )
  )

```

**Comment by codefromthecrypt** [comment]
opened #1062 with a work-in-progress. If anyone feels like adding commits, go for it!

**Comment by codefromthecrypt** [comment]
#1062 is ready to go
