### ISSUE TITLE
Add JSON button to trace detail view

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1060]
The screenshot on zipkin.io includes a blue JSON button which is a link to /api/v1/trace/id. This would be very helpful when folks are trying to debug problems, as manually instructing is not intuitive.

**Comment by eirslett** [comment]
It should be possible to add this in trace.mustache, I think.
Something like `<a href="/api/v1/trace/{{traceId}}">JSON</a>`
