### ISSUE TITLE
zipkin-ui: consider opening a new tab when clicking on a trace

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1061]
When navigating from the find traces view to a trace, you are fine. Navigating back is a problem, as the results might be different.

@gena01 suggested opening a new tab on trace detail so that the find view is stable when the trace clicked isn't the one you wanted

**Comment by yurishkuro** [comment]
Personally, I've always disliked it when websites open tabs without being asked to. It breaks the default behavior of the browser and user expectations. Here's a good summary with many references: http://libux.co/links-should-open-in-the-same-window/

A user can always choose to open a new tab via middle-click or Cmd-click.

**Comment by eirslett** [comment]
I agree with @yurishkuro here. Right-click and open in a new tab.

**Comment by codefromthecrypt** [comment]
Thx for speaking up, folks!
