### ISSUE TITLE
Feature Request: Please add an ability query with StartTs and not just EndTs

### ISSUE THREAD

**Issue by gena01** [openzipkin/zipkin#1063]
So the zipkin UI has a filter for the ending timestamp. Is it possible to add a way to also query by the starting timestamp? One example is if I am looking for new traces I don't want to see traces that are >12 hours old, so I would be able to provide a stop point in history not to pull those old traces.

**Comment by yurishkuro** [comment]
I believe the query REST API accepts a `lookback` parameter, it's just not exposed in the UI.

**Comment by yurishkuro** [comment]
a good UI widget for lookback would be the way Grafana2 does it. I wonder if it's available somewhere in reusable form.

![image](https://cloud.githubusercontent.com/assets/3523016/14037177/3e26d4e4-f217-11e5-9556-be3f59f73fd5.png)

**Comment by codefromthecrypt** [comment]
a quick could be to port the code from the dependencies screen that already does this. This should be very easy as the query parameters are the same (ex endTs and lookback) cc @t-yuki 

<img width="591" alt="screen shot 2016-03-25 at 11 52 02 am" src="https://cloud.githubusercontent.com/assets/64215/14037523/0c660150-f280-11e5-9109-537c20474aac.png">

**Comment by eirslett** [comment]
Wouldn't it be better if they were called startTs and endTs? Anyways, shouldn't be too difficult to implement UI-wise!

**Comment by codefromthecrypt** [comment]
closed via #1067
