### ISSUE TITLE
Install error using the scripts

### ISSUE THREAD

**Issue by fluidjeel** [openzipkin/zipkin#1066]
Im getting the following error on the latest 1.38.1 and 1.38.0 releases while executing ./bin/query

:zipkin-cassandra-core:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':zipkin-cassandra-core:compileJava'.
  > Could not find tools.jar

**Comment by codefromthecrypt** [comment]
JAVA_HOME needs to be set to a JDK ( not a JRE )

**Comment by fluidjeel** [comment]
[root@ixxxx ]# java -version
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by codefromthecrypt** [comment]
what is the value of $JAVA_HOME

**Comment by fluidjeel** [comment]
JAVA_HOME was pointed to /usr/java/latest, i changes it to jdk. Apologies for the trouble
