### ISSUE TITLE
First (index) page is hitting /api/v1/spans?serviceName=undefined 

### ISSUE THREAD

**Issue by gena01** [openzipkin/zipkin#1072]
When first loading the Zipkin UI (tested with zipkin-query 1.39 docker container) it seems that the Javascript is trying to load spans with `undefined` serviceName.

**Comment by codefromthecrypt** [comment]
@eirslett mind helping on this one? I'm not quite sure the best way to early exit on this..

**Comment by eirslett** [comment]
It's not really a big problem. But if somebody wants to fix it, we could first get the list of services, then pick the first service in the list and ask for spans for that service, instead of reading service name from the query string.

**Comment by gena01** [comment]
Actually i thought it was even simpler than that. Maybe I should have rephrased things a little better.

When loading zipkin ui homepage (/ url) it shouldn't be loading any spans since nothing has been selected. This is also where the `undefined` comes from for the serviceName. Is it possible to make this a conditional of sorts just for the homepage case?

**Comment by eirslett** [comment]
Yes, the event that triggers the API call should only be triggered when service name is set in the query string. We use query-string for that already, in other places.
