### ISSUE TITLE
Don't distribute non-shadowed jars of collector-service and query-service

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin#1074]
https://jcenter.bintray.com/io/zipkin/zipkin-query-service/1.39.0/

When people download the wrong jar, the UI assets won't be bundled (neither will any of the jar dependencies)
I think @mansu had this problem, getting the wrong jar? (Or so it seems from the gitter conversation)

If there's no good reason why we're publishing the not-shadowed jars, maybe we could just as well not distribute them in the first place? @abesto is it possible to configure Gradle so it doesn't build the jars, only the shadowed jars? (Or, at least doesn't upload the jars)

**Comment by gena01** [comment]
I had this confused with https://jcenter.bintray.com/io/zipkin/zipkin-query/1.39.0/ today. :(

**Comment by codefromthecrypt** [comment]
there's no use case for non-shadowed -service jars, so yes they can be
removed.

aside: in the java project (zipkin-server), there is a use case, which is
that you can build a smaller or extended zipkin server (ex one that doesn't
include kafka, or that includes 3rd party transports or storage).

**Comment by abesto** [comment]
Gave it a shot in #1076 (two commits because I found a better way, so force pushed)
