### ISSUE TITLE
Could not GET pom when i execute "proxychains ./bin/query"

### ISSUE THREAD

**Issue by zywei** [openzipkin/zipkin#1075]
i use the proxy to install zipkin. i can get the pom by execute "proxychains  wget https://maven.twttr.com/com/twitter/common/metrics/0.0.37/metrics-0.0.37.pom",but when i execute "proxychains ./bin/query",it respone "peer not authenticated"  or "maven.twttr.com/com connect refused". how could i?

**Comment by codefromthecrypt** [comment]
Looks like you'll need to add some things to gradle.properties (or maybe
you can make local.properties file)

https://docs.gradle.org/current/userguide/build_environment.html

**Comment by zywei** [comment]
thanks very much;
