### ISSUE TITLE
move zipkin-sampler to its own repository

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1078]
The adaptive sampler is a storage filter who's goal is to keep collectors from overloading the storage layer. It does this by coordinating a sample rate based on the store rate of each member (against a target which the storage system is capable of).

The adaptive sampler is implemented using zookeeper apis directly, using code that hasn't changed except for maintenance since imported. The code has a lot of classes, and had no notable tests until an attempt at backfilling last year in #891. The dependencies around zookeeper are troubling.

Theoretically, one can install this as a filter on `Seq(Span)`, given some configuration. However, there's no instructions or known use in open source. That said, a version of this is used internally at Twitter.

Options:
- remove it as it isn't used by the community at large
- pull the project out into a separate repository until people use or maintain it
- rewrite it using modern tools, reverse engineering its features and backfilling tests (~month of effort)

**Comment by eirslett** [comment]
+1 for moving it to a separate repository and add a short readme that explains what you just said.

**Comment by mosesn** [comment]
+1 for moving it to a separate repository as long as we can still use it with mainstream zipkin.  I agree that the dependency on ZK is troubling, and we should fix it.  With that said, as far as I can tell it's the key feature that lets zipkin control its write traffic, which is what scaled it at Twitter, so I think it's worth keeping around in a usable capacity.

**Comment by codefromthecrypt** [comment]
Implementation aside, the integration with a span consumer is fairly
simple, a filter.

This would work with both the scala and the java interfaces, and I can put
example code showing this.

**Comment by codefromthecrypt** [comment]
One thing I'd clarify is that even if I can demonstrate get this to
work with another collection filter, this isn't a commitment in any
way to support it. There's no such commitment today by any current
contributor of zipkin, nor any history of it by past committers.

When this goes to its own repository, its fate will be in the hands of
those interested enough to maintain several year old code, or those
who wish to rewrite it.

**Comment by codefromthecrypt** [comment]
Here's the issue that adds basic build infra https://github.com/openzipkin/zipkin-adaptive-sampler/pull/1

**Comment by codefromthecrypt** [comment]
Had an offline chat w/ @eirslett and I think it isn't worth it to move the sampler to a separate repository. Instead, we can add support in zipkin-java and leave this here until zipkin-java can replace the code here. https://github.com/openzipkin/zipkin-java/issues/164

**Comment by codefromthecrypt** [comment]
No-one is using the zookeeper sampler. it has been just a maintenance burden for years. I'd like to move it to openzipkin-attic

@openzipkin/core anyone disagree?

**Comment by eirslett** [comment]
Are you sure Twitter is not using it internally? Maybe they've moved off ZooKeeper?

**Comment by codefromthecrypt** [comment]
they'd only be using it directly if they moved to the java port of the server. In any case it isn't actually connected to the server, so this is why I don't think anyone is using it.

**Comment by jcchavezs** [comment]
+1 to move it to the archive.

**Comment by mosesn** [comment]
@adriancole I'll talk to our zipkin team and get them to chime in.

**Comment by codefromthecrypt** [comment]
Thanks @mosesn if somehow this is in use, it is also ok to make it a non-attic repo (ex contrib), just it pulls zk dependencies takes a while to run tests and has had near zero feedback for the last couple years. Would like to keep the core repo focused

**Comment by mosesn** [comment]
@adriancole let's archive it, if we (Twitter) want to use it we can maintain it.  We're using something similar but not this implementation today.  As a side note, we've updated to 1.28.1.
