### ISSUE TITLE
Scribe receiver does "tryLater" on just about anything

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1081]
One strange thing about the current scribe implementation is that it sends a TryLater on any non-fatal, non-cancellation exception. That seems to imply a poison message (ex bad encoding) could take down scribe, if the caller indeed tries it again later. You could imagine a loop happening with this policy.

It seems more sensible to only issue tryLater on a whitelist of known transient issues, such as IOExceptions.

**Comment by codefromthecrypt** [comment]
ex. we literally have a test to try later on NullPointerException! Would we expect this to not be a NPE later?!

```
    assert(log.get.trim === "Sending TryLater due to NullPointerException(foo was null)")
```

**Comment by codefromthecrypt** [comment]
whitelisting transient could be tricky, as for example `NoHostAvailableException` isn't an IOException, and it is a cassandra-specific class. One way could be to enforce that AsyncSpanConsumer implementations must route an transient scenario to an `IOException`. The problem with this approach is that it is a whack-a-mole and very sensitive to library updates.

Another option is to simply not support tryLater.

**Comment by eirslett** [comment]
I don't think we should support tryLater at all. Spans are lossy data.

**Comment by codefromthecrypt** [comment]
current code doesn't do this
