### ISSUE TITLE
[ui] "Working..." splash stuck on Span view screen

### ISSUE THREAD

**Issue by prat0318** [openzipkin/zipkin#1085]
I see this when running UI from the query service i.e. 1.37+

![screen shot 2016-04-04 at 11 24 30 am](https://cloud.githubusercontent.com/assets/1528697/14258640/1a9e98f6-fa58-11e5-8dd3-81a1802e7643.png)

The console error trace looks like:

```
Uncaught TypeError: Cannot read property 'openChildren' of undefined
(anonymous function) @ trace.js:94
jQuery.extend.each @ jquery.js:365
(anonymous function) @ trace.js:92
jQuery.extend.each @ jquery.js:365
expandSpans @ trace.js:80
filterAdded @ trace.js:74
(anonymous function) @ trace.js:273
```

**Comment by prat0318** [comment]
trace pb

``` json
[
    {
        "traceId": "a83668f5b355bd70",
        "name": "post",
        "id": "0000000000000001",
        "parentId": "0000000000000000",
        "timestamp": ​1459723138170202,
        "duration": ​604053,
        "annotations": [
            {
                "timestamp": ​1459723138170202,
                "value": "sr",
                "endpoint": {
                    "serviceName": "yelp",
                    "ipv4": "10.56.5.4",
                    "port": ​80
                }
            },
            {
                "timestamp": ​1459723138774255,
                "value": "ss",
                "endpoint": {
                    "serviceName": "yelp",
                    "ipv4": "10.56.5.4",
                    "port": ​80
                }
            }
        ],
        "binaryAnnotations": [
            {
                "key": "servlet",
                "value": "connect",
                "endpoint": {
                    "serviceName": "yelp",
                    "ipv4": "10.56.5.4",
                    "port": ​80
                }
            },
            {
                "key": "http.uri",
                "value": "register",
                "endpoint": {
                    "serviceName": "yelp",
                    "ipv4": "10.56.5.4",
                    "port": ​80
                }
            },
            {
                "key": "http.uri.qs",
                "value": "register",
                "endpoint": {
                    "serviceName": "yelp",
                    "ipv4": "10.56.5.4",
                    "port": ​80
                }
            }
        ]
    }
]
```

**Comment by eirslett** [comment]
I suspect that id: 00001 and parentId 00000 could be the problem?
Usually, the top level span has trace id = parent id = span id.
In that case, it's your application instrumentation that has a bug.
That being said, I think the UI should be able to handle cases like this anyways.

**Comment by prat0318** [comment]
It shows up fine with the older UI.

Also, as per [the docs](http://zipkin.io/pages/instrumenting.html), `span_id` can be the same `trace_id` but is not mentioned it must or should. So, i don't think it is a bug.

**Comment by eirslett** [comment]
It could be that the UI is failing because the parent id is set to 0, but there is no span with id 0 in the data set? There may not be any assumptions that trace ids have anything to do with span ids, but I think the UI assumes that every parent ID also exists as a span in the data set. (I have no idea how it worked before...)

What happens if you set span id = 0? So in the root span, id = parent id?

**Comment by codefromthecrypt** [comment]
@prat0318 so I think this is a bug if the above span has no parent (ie is a root span). Ex setting to 0 is invalid, whereas leaving the parentId field unset is

**Comment by yurishkuro** [comment]
In our instrumentation libraries we adopted a convention that parentID==0 means no parent (a more natural "empty" value for int64 than null ptr). The collector adjusts that into null Thrift value when inserting into Cassandra. Might be useful convention to adopt.

**Comment by codefromthecrypt** [comment]
since ids are basically byte arrays packed into a long, we shouldn't do things like interpret them. My concern about conventions like 0 is that a small bug in a custom collector's thrift codec will send the zero across. Basically, do things like that at one's own risk.

**Comment by codefromthecrypt** [comment]
back to this issue.. we do have a bug in the UI, IMHO

a headless trace shouldn't cause problems. Ex. it can be the case that the root span is missing, but everything else is present. The data here is similar in shape to a headless trace (i.e. the root-most span's parent is missing)

**Comment by codefromthecrypt** [comment]
@prat0318 I cleaned up the control characters out of your json and posted it locally. works.. can you try on your end?

``` json
[
  {
    "traceId": "a83668f5b355bd70",
    "name": "post",
    "id": "0000000000000001",
    "parentId": "0000000000000000",
    "timestamp": 1459723138170202,
    "duration": 604053,
    "annotations": [
      {
        "timestamp": 1459723138170202,
        "value": "sr",
        "endpoint": {
          "serviceName": "yelp",
          "ipv4": "10.56.5.4",
          "port": 80
        }
      },
      {
        "timestamp": 1459723138774255,
        "value": "ss",
        "endpoint": {
          "serviceName": "yelp",
          "ipv4": "10.56.5.4",
          "port": 80
        }
      }
    ],
    "binaryAnnotations": [
      {
        "key": "servlet",
        "value": "connect",
        "endpoint": {
          "serviceName": "yelp",
          "ipv4": "10.56.5.4",
          "port": 80
        }
      },
      {
        "key": "http.uri",
        "value": "register",
        "endpoint": {
          "serviceName": "yelp",
          "ipv4": "10.56.5.4",
          "port": 80
        }
      },
      {
        "key": "http.uri.qs",
        "value": "register",
        "endpoint": {
          "serviceName": "yelp",
          "ipv4": "10.56.5.4",
          "port": 80
        }
      }
    ]
  }
]
```

**Comment by codefromthecrypt** [comment]
ok narrowing this down, it couldn't have happened before 1.38 (and be run on the query service), because query didn't host static assets until 1.38

**Comment by codefromthecrypt** [comment]
While I can't get the waiting screen to come up, the error is repeatable given the json I posted in version 1.38.0

``` bash
# in one tab...
$ java -jar ~/Downloads/zipkin-query-service-1.38.0-all.jar -f /query-dev.scala
# in another..
$ curl -X POST -H 'Content-Type: application/json' -s localhost:9411/api/v1/spans -d @/tmp/foo
# in a browser
http://localhost:9411/traces/a83668f5b355bd70
```

**Comment by codefromthecrypt** [comment]
above is also reproducible with latest 1.39.3

**Comment by codefromthecrypt** [comment]
ok the patch is to guard.. now figuring out if I can get this to be testable..

``` javascript
        /* Parent may not be found for a number of reasons. For example, the
        trace id may not be a span id. Also, it is possible to lose the root
        span data (i.e. a headless trace) */
        if (self.spans[pId]) {
          toShow[pId] = true;
          self.spans[pId].openChildren += 1;
        }
```

**Comment by codefromthecrypt** [comment]
took me a long time to figure out how to test this :P If anyone has better ideas, please comment here https://github.com/openzipkin/zipkin/pull/1089
