### ISSUE TITLE
nothing response when i send data to zipkin

### ISSUE THREAD

**Issue by zywei** [openzipkin/zipkin#1086]
i send data by zipkin-java,ex:
            connection.setRequestMethod("POST");
        connection.addRequestProperty("Content-Type", "application/json");
                byte[] json = Codec.JSON.writeSpans(drained);
                connection.getOutputStream().write(json);
but i always read time out ??
        i start the zipkin by the quick start,what else should i do to send data?

**Comment by codefromthecrypt** [comment]
This question seems more about how to POST data vs an issue in zipkin.
Debugging custom http clients would be outside the scope of this project.

For example, the following works.

$ curl -X POST -H'Content-Type: application/json' -s
localhost:9411/api/v1/spans -d @your_file

You might also look at this:
https://github.com/openzipkin/brave/tree/master/brave-spancollector-http

**Comment by zywei** [comment]
not 9410?

**Comment by codefromthecrypt** [comment]
nope 9410 is scribe (thrift rpc protocol) 9411 is http.
