### ISSUE TITLE
Sample decision propagation query

### ISSUE THREAD

**Issue by drpacman** [openzipkin/zipkin#1087]
A bit of background:
My understanding of the sampled approach in Dapper and Zipkin is that a sampling decision is made at the "edge" of the system. It must be propagated to downstreams services in both the positive (we are sampling) and negative (we are not sampling) cases, and must be honoured by the downstream system.
By this I mean the downstream system should not make an independent decision of wether to sample the  request. 

To accomplish this a header (X-B3-Sampled ) is added to downstream client calls. According to http://zipkin.io/pages/instrumenting.html this value should be a 1 or a 0.

However the original Finagle code appears to use "true" and "false" rather then 1 or 0 (see function on line 349 setClientRequestHeaders):

https://www.codatlas.com/github.com/twitter/finagle/develop/finagle-http/src/main/scala/com/twitter/finagle/http/Codec.scala

Which serialises the value from a Scala Option[Boolean]
https://www.codatlas.com/github.com/twitter/finagle/develop/finagle-core/src/main/scala/com/twitter/finagle/tracing/Id.scala

The Brave implementation appears to handle both:
https://github.com/openzipkin/brave/blob/fd3cdb921964a0d7164c29141fe6aac8099ae4cf/brave-http/src/main/java/com/github/kristofa/brave/http/HttpServerRequestAdapter.java

Questions:
Is my understanding of the importance of honouring sampling decisions at the edge in line with others understanding. 
Secondly, which form for X-B3-Sampled is correct - the arch page or the Finagle code? Am I looking in the wrong place?

**Comment by codefromthecrypt** [comment]
Mind re-opening this against the doc repo? There's no code in this repo
related to this question, but it is a nice topic to clarify.

ack that the name of this repo could lead it to be a catch-all for all
things including instrumentation, just saying there's nothing to change
here as a result of this topic.

To answer, I think most instrumentation use 0 or 1 for that header, but we
could clarify it as a choice of true/false or 1/0. We need to check that
other tracers accept that,  though, particularly those in the openzipkin
organization) brave and zipkin-tracer (ruby)). Great example of where
interoperability testing  could help

https://github.com/opentracing/opentracing.github.io/issues

**Comment by drpacman** [comment]
Thanks @adriancole, appreciate the response. I have hopefully now opened this in the correct location. Keep up the great work, it is really appreciated.
