### ISSUE TITLE
can not find trace in ui

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1097]
i input traceid in ui web (curl -I 'http://127.0.0.1:8080/api/v1/trace/21757')， response is 404
how can i input traceid find trace info？

**Comment by eirslett** [comment]
Are you sure the trace is in the database?

**Comment by dragontree101** [comment]
i use 'SELECT \* from traces where trace_id=21757' in cassandra,  i can find 2 rows, so i input 21717 in traces, but not find anything

**Comment by eirslett** [comment]
21717 or 21757?
I'm not sure what the problem could be, you could try starting zipkin-server locally and step-through-debug it, maybe?

**Comment by dragontree101** [comment]
i spell error, is 21757, i use zipkin version is 1.39.4
![image](https://cloud.githubusercontent.com/assets/1763935/14738677/93fb64a2-08b5-11e6-9b52-fade4b166f30.png)  i input traceid to this

**Comment by dragontree101** [comment]
curl -I 'http://127.0.0.1:8080/api/v1/trace/21757' but is 404, url is correct?

**Comment by eirslett** [comment]
Yes, it looks correct.
Which instrumentation library are you using? Brave? Finagle? Pyramid? Usually, the trace IDs are 64-bit hex-encoded numbers, 21757 is a very small number! I don't think it's related though.

**Comment by dragontree101** [comment]
i use Brave, but 21757 is myself input , not brave generate, i read brave is a random long, 21757 maybe also is random long, i read brave code again, thanks very much

**Comment by dragontree101** [comment]
i use String s = IdConversion.convertToString(21757);   result is 54fd, and input 54fd to trace, i can get result, thanks very much

**Comment by eirslett** [comment]
Great!
So the clue is that in the web UI and API, the IDs are hex-encoded.
@adriancole maybe we should document that... (if it's not already?)

**Comment by codefromthecrypt** [comment]
interesting.. id as hex is documented..

https://github.com/openzipkin/zipkin-api/blob/master/zipkin-api.yaml#L141

but.. the website doesn't seem to render that description:

http://zipkin.io/zipkin-api/#/paths/%252Ftrace%252F%257BtraceId%257D

@mohsen1 any ideas why?
