### ISSUE TITLE
zipkin-ui could provide better feedback on slow response

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1099]
When an api query is slow, it could look misallocated in chrome debug. For example, the below slow call to `/services` wasn't caused by /api/v1/services, rather /api/v1/traces which took 200seconds to return

https://files.gitter.im/openzipkin/zipkin/x7p8/blob

Thanks to @yzhang8015 for reporting

**Comment by jorgheymans** [comment]
@adriancole is this still an issue in Lens ? If not feel free to close. 

![image](https://user-images.githubusercontent.com/193792/79007750-1b183380-7b5c-11ea-9ad0-ba624a9c6919.png)

**Comment by codefromthecrypt** [comment]
I would guess it is ok :) If there's some nuanced reason it isn't we can re-open. Thanks @jorgheymans
