### ISSUE TITLE
Make fetch.message.max.bytes configurable

### ISSUE THREAD

**Issue by lycplus** [openzipkin/zipkin#1101]
Recently, we migrate our transport from scribe to kafka, but our zipkin seems not accept any message. Our kafka server have a `message.max.bytes` that are greater than the default 1024*1024 byte, and it is not easily to change it. It seems `KafkaSpanReceiver.receiverProps` is the ConsumerConfig, but we can not pass `fetch.message.max.bytes` via environment variable, which is inconvenient.

**Comment by codefromthecrypt** [comment]
Hi. so the docs actually indicate a megabyte is the max size per message.
Regardless, let me see if there's a way for us to constrain this portably.
If would be nice if we could have one collector parameter for this, as
large messages can become problematic.

http://kafka.apache.org/documentation.html

**Comment by codefromthecrypt** [comment]
which reporter are you using to send the messages? I noticed that htrace compresses the messages like so..

https://github.com/apache/incubator-htrace/blob/master/htrace-zipkin/src/main/java/org/apache/htrace/impl/KafkaTransport.java#L105

**Comment by codefromthecrypt** [comment]
so kafka is tuned for smaller message sizes, and 1MB with compression can hold a fair amount of spans. Can you try compression first? I've opened an issue in zipkin-java to add metrics on message size https://github.com/openzipkin/zipkin-java/issues/165

**Comment by lycplus** [comment]
Our reporter sends message less than 1MB (I have stats to ensure that). But the kafka server's configuration is 200MB (other message needs this)，and the config seems to be global and affects our topic.

**Comment by codefromthecrypt** [comment]
OK if that's the case, then this needs to be a kafka-specific parameter, not conflated with span message size

**Comment by codefromthecrypt** [comment]
ok so maybe `KAFKA_FETCH_MESSAGE_MAX_BYTES` for lack of a better idea..

**Comment by lycplus** [comment]
Yeah.

**Comment by codefromthecrypt** [comment]
ok np

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1109

**Comment by codefromthecrypt** [comment]
settled on `KAFKA_MAX_MESSAGE_SIZE` as it is less awkward and more like the other variables

**Comment by codefromthecrypt** [comment]
going out as 1.39.9
