### ISSUE TITLE
Docker mysql username and password 

### ISSUE THREAD

**Issue by flytosky** [openzipkin/zipkin#1103]
I am trying to access to Docker zipkin MySQL database. I have tried some approaches but failed. Could you provide some ways to access to these data inside the container? And what is the default username and password of MySQL in Docker zipkin container? Thanks!

**Comment by codefromthecrypt** [comment]
mind re-opening the question in the docker repo? it might lead to a doc
update.

https://github.com/openzipkin/docker-zipkin

**Comment by flytosky** [comment]
Done! Thanks!
