### ISSUE TITLE
zipkin-web traces display error

### ISSUE THREAD

**Issue by roson9527** [openzipkin/zipkin#1116]
The traces show is out of order :( (Using Golang)
![image](https://cloud.githubusercontent.com/assets/5964739/15385492/8f0f47f4-1dd4-11e6-8944-80c0851a078c.png)

Theoretically it should be like this (Using C#)~
![image](https://cloud.githubusercontent.com/assets/5964739/15385481/825bad68-1dd4-11e6-9e8b-acc63a701674.png)

json data generated by the same two languages.
![image](https://cloud.githubusercontent.com/assets/5964739/15385580/12f2c96a-1dd5-11e6-804d-e77250bfdfc4.png)

And sometimes, on the first page after clicking Find Traces, Traces time display will be more than 100%
![image](https://cloud.githubusercontent.com/assets/5964739/15380633/c8c3de6c-1daa-11e6-86d3-649cc90f0ea4.png)
If you click it, you can see
![image](https://cloud.githubusercontent.com/assets/5964739/15380711/54a64870-1dab-11e6-8890-5f7182acbef3.png)
I retrieve all its span of trace Id and parentId, is correct.

My system is working modes:
1. Custom span data transmitted from the server is converted to zipkin span of json data
2. Then send json data via HTTP Post method to query server

I do not know zipkin system for json data is sent to the query server must be whether a certain order
Traces of the same order and there may be displayed correctly, there are likely to fail, just like the above two errors :(
- Currently the test environment is to use docker deployment.

**Comment by eirslett** [comment]
Can you please post the JSON data here as text, not as images? It's a bit hard to type it in all over again...

**Comment by codefromthecrypt** [comment]
ps to get the json, use http://your_host/api/v1/trace/_hex_trace_id_here_

http://zipkin.io/zipkin-api/#/paths/%252Ftrace%252F%257BtraceId%257D

**Comment by roson9527** [comment]
Thanks Reply

This is unusual Trace picture.
![image](https://cloud.githubusercontent.com/assets/5964739/15421811/e7e9748e-1ea7-11e6-8fd9-80a6173b546e.png)
@adriancole 

> ps to get the json, use http://your_host/api/v1/trace/_hex_trace_id_here_

============= Acquired through this link is json==================
`[{"traceId":"493e8314428aa606","name":"todo","id":"493e8314428aa606","timestamp":1463732526416075,"duration":5998,"annotations":[{"timestamp":1463732526416075,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526422073,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526416075,"value":"sr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526422073,"value":"ss","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.416075    UnixTime:1463732526416075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.422073    tUnixTime:1463732526422074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]},{"traceId":"493e8314428aa606","name":"func2","id":"419606bc1013db96","parentId":"493e8314428aa606","timestamp":1463732526417074,"duration":4000,"annotations":[{"timestamp":1463732526417074,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526421074,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526417074,"value":"sr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526421074,"value":"ss","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"lc","value":"执行Func2","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"419606bc1013db96","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.417074    UnixTime:1463732526417075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.421074    tUnixTime:1463732526421074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]},{"traceId":"493e8314428aa606","name":"func22","id":"4bc2e66823900abc","parentId":"419606bc1013db96","timestamp":1463732526418074,"duration":2000,"annotations":[{"timestamp":1463732526418074,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526420074,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526418074,"value":"sr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526420074,"value":"ss","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"lc","value":"执行Func22","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"419606bc1013db96","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"4bc2e66823900abc","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.419074    UnixTime:1463732526419074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.421074    tUnixTime:1463732526421074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]},{"traceId":"493e8314428aa606","name":"func21","id":"412a17134fba0d19","parentId":"419606bc1013db96","timestamp":1463732526418074,"duration":1000,"annotations":[{"timestamp":1463732526418074,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526418074,"value":"执行Func21_timerecord","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526419074,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"lc","value":"e2d1bd62-bbe0-4ce0-a8bc-0fc569120b7c","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"GUID","value":"5a801afa-3ae3-48ae-a0ff-c0b3f32e3542","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"419606bc1013db96","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"412a17134fba0d19","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.418074    UnixTime:1463732526418075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.419074    tUnixTime:1463732526419074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]},{"traceId":"493e8314428aa606","name":"func221","id":"4c6c93f2ddf1fbb1","parentId":"4bc2e66823900abc","timestamp":1463732526418574,"duration":1000,"annotations":[{"timestamp":1463732526418574,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526419574,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"lc","value":"执行Func221","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"4bc2e66823900abc","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"4c6c93f2ddf1fbb1","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.420074    UnixTime:1463732526420074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.421074    tUnixTime:1463732526421074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]},{"traceId":"493e8314428aa606","name":"func3","id":"45266bd2e8b1097d","parentId":"493e8314428aa606","timestamp":1463732526418574,"duration":999,"annotations":[{"timestamp":1463732526418574,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526419573,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"lc","value":"执行Func3","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"45266bd2e8b1097d","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.421074    UnixTime:1463732526421074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.422073    tUnixTime:1463732526422074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]},{"traceId":"493e8314428aa606","name":"func1","id":"4ad3dcac1c362d53","parentId":"493e8314428aa606","timestamp":1463732526418574,"duration":999,"annotations":[{"timestamp":1463732526418574,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526419573,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"lc","value":"开始执行Func1","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"lc","value":"结束执行Func1","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"4ad3dcac1c362d53","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.416075    UnixTime:1463732526416075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.417074    tUnixTime:1463732526417075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]}]`

============= Via HTTP POST to queryserver original json:==================
1）
`{"traceId":"493e8314428aa606","name":"Func1","id":"4ad3dcac1c362d53","parentId":"493e8314428aa606","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":1463732526416075},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":1463732526417074}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"开始执行Func1"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"结束执行Func1"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"4ad3dcac1c362d53"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.416075    UnixTime:1463732526416075"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.417074    tUnixTime:1463732526417075"}]}`
2）
`{"traceId":"493e8314428aa606","name":"Func22","id":"4bc2e66823900abc","parentId":"419606bc1013db96","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":1463732526419074},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":1463732526421074}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"执行Func22"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"419606bc1013db96"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"4bc2e66823900abc"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.419074    UnixTime:1463732526419074"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.421074    tUnixTime:1463732526421074"}]}`
3）
`{"traceId":"493e8314428aa606","name":"Func221","id":"4c6c93f2ddf1fbb1","parentId":"4bc2e66823900abc","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":1463732526420074},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":1463732526421074}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"执行Func221"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"4bc2e66823900abc"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"4c6c93f2ddf1fbb1"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.420074    UnixTime:1463732526420074"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.421074    tUnixTime:1463732526421074"}]}`
4）
`{"traceId":"493e8314428aa606","name":"Func21","id":"412a17134fba0d19","parentId":"419606bc1013db96","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":1463732526418074},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":1463732526419074},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"执行Func21_timerecord","timestamp":1463732526418074}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"e2d1bd62-bbe0-4ce0-a8bc-0fc569120b7c"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"GUID","value":"5a801afa-3ae3-48ae-a0ff-c0b3f32e3542"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"419606bc1013db96"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"412a17134fba0d19"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.418074    UnixTime:1463732526418075"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.419074    tUnixTime:1463732526419074"}]}`
5）
`{"traceId":"493e8314428aa606","name":"ToDo","id":"493e8314428aa606","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":1463732526416075},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":1463732526422073}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.416075    UnixTime:1463732526416075"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.422073    tUnixTime:1463732526422074"}]}`
6）
`{"traceId":"493e8314428aa606","name":"Func3","id":"45266bd2e8b1097d","parentId":"493e8314428aa606","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":1463732526421074},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":1463732526422073}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"执行Func3"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"45266bd2e8b1097d"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.421074    UnixTime:1463732526421074"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.422073    tUnixTime:1463732526422074"}]}`
7）
`{"traceId":"493e8314428aa606","name":"Func2","id":"419606bc1013db96","parentId":"493e8314428aa606","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":1463732526417074},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":1463732526421074}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"执行Func2"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"419606bc1013db96"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.417074    UnixTime:1463732526417075"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.421074    tUnixTime:1463732526421074"}]}`

I hope I can get your help, thank you.

**Comment by roson9527** [comment]
Checking the data flow process, we found the results will be different if the root Span of ParentId to "" (empty string) or "00000000000000."
When the root Span parentId value is "0000000000000000", the display may produce strange errors, such as when the display can not find the root Span, but sometimes is normal.
Thank u.

**Comment by eirslett** [comment]
That is correct; if it refers to a parent ID that doesn't exist, the UI logic fails. It recurses through all the spans, and if a parent ID is defined, it tries to find that span. If it's not there, things fail.

**Comment by codefromthecrypt** [comment]
Ps the root span is when the parent is unset. 0 is not a special value (it
is a valid id!).

Please look into your instrumentation and correct it!

**Comment by roson9527** [comment]
5.json is root span data, parent ID is the correct way to set (unset) :)

When I post 1.json data, trace is correct, but if then post 5.json data, found trace changes, the original Func1 had changed the timestamp:(

Hope to get your help, thank you：）
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝only 1.json ＝＝＝＝＝＝＝＝＝＝＝
[{"traceId":"493e8314428aa606","name":"func1","id":"4ad3dcac1c362d53","parentId":"493e8314428aa606","timestamp":**1463732526416075**,"duration":999,"annotations":[{"timestamp":**1463732526416075**,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":**1463732526417074**,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"lc","value":"开始执行Func1","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"lc","value":"结束执行Func1","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"4ad3dcac1c362d53","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.416075 UnixTime:1463732526416075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.417074 tUnixTime:1463732526417075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]}]

＝＝＝＝＝＝＝＝＝＝＝＝＝＝ 1.json + 5.json ＝＝＝＝＝＝＝＝＝＝＝
[{"traceId":"493e8314428aa606","name":"todo","id":"493e8314428aa606","timestamp":_1463732526416075_,"duration":5998,"annotations":[{"timestamp":_1463732526416075_,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526422073,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526416075,"value":"sr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":1463732526422073,"value":"ss","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.416075 UnixTime:1463732526416075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.422073 tUnixTime:1463732526422074","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]},{"traceId":"493e8314428aa606","name":"func1","id":"4ad3dcac1c362d53","parentId":"493e8314428aa606","timestamp":**1463732526418574**,"duration":999,"annotations":[{"timestamp":**1463732526418574**,"value":"cs","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"timestamp":**1463732526419573**,"value":"cr","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}],"binaryAnnotations":[{"key":"lc","value":"开始执行Func1","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"lc","value":"结束执行Func1","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"TraceId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"ParentId","value":"493e8314428aa606","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"CurId","value":"4ad3dcac1c362d53","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"StartTime","value":"2016-05-20 16:22:06.416075 UnixTime:1463732526416075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}},{"key":"EndTime","value":"2016-05-20 16:22:06.417074 tUnixTime:1463732526417075","endpoint":{"serviceName":"test001","ipv4":"127.0.0.1","port":80}}]}]

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝json src ＝＝＝＝＝＝＝＝＝＝＝＝＝
1）
{"traceId":"493e8314428aa606","name":"Func1","id":"4ad3dcac1c362d53","parentId":"493e8314428aa606","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":**1463732526416075**},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":**1463732526417074**}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"开始执行Func1"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"lc","value":"结束执行Func1"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"4ad3dcac1c362d53"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.416075 UnixTime:1463732526416075"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.417074 tUnixTime:1463732526417075"}]}

5）
{"traceId":"493e8314428aa606","name":"ToDo","id":"493e8314428aa606","annotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cs","timestamp":_1463732526416075_},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"value":"cr","timestamp":_1463732526422073_}],"binaryAnnotations":[{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"TraceId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"ParentId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"CurId","value":"493e8314428aa606"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"StartTime","value":"2016-05-20 16:22:06.416075 UnixTime:1463732526416075"},{"endpoint":{"ipv4":"127.0.0.1","port":80,"serviceName":"Test001"},"key":"EndTime","value":"2016-05-20 16:22:06.422073 tUnixTime:1463732526422074"}]}

**Comment by codefromthecrypt** [comment]
When you say generated by these languages, can you be more specific? Do you know which libraries are in use (if open source)? Regardless, one of your questions was about timestamps. Zipkin corrects for clock-skew, if you add the query `?raw` to your api call, you can see the data without any adjustments.

Ex. `http://your_host/api/v1/trace/493e8314428aa606?raw`

Sorry the tips are a bit vague. I'm displaced and can't look too deeply into this for a day or two.

**Comment by roson9527** [comment]
I have found the reason, the problem is the data we generate, it has been corrected
*Performs clock-skew method when the root span only have cr and cs timestamp.

**Comment by codefromthecrypt** [comment]
thx for following up
