### ISSUE TITLE
UI fails to render traces without endpoints

### ISSUE THREAD

**Issue by virtuald** [openzipkin/zipkin#1117]
The [thrift](https://github.com/openzipkin/zipkin/blob/cdc92ec65b88b457b82b5a0d2a8eeb2c7d85380e/zipkin-thrift/src/main/thrift/com/twitter/zipkin/zipkinCore.thrift#L276) schema states that endpoints are optional. However, when rendering, it appears that for some core annotations the endpoint is required _and_ overrides the value (see [this](https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/traceToMustache.js#L132)), otherwise the page fails to render.

**Comment by virtuald** [comment]
Sorry, that was a bad example, I missed the detection for endpoint. However, there's somewhere that it's not checking because it's crashing on me... 

Ah, CORE_ADDRESS: https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/traceToMustache.js#L114

**Comment by virtuald** [comment]
Yep, confirmed that it was a CLIENT_ADDR annotation. It appears that the value doesn't matter for CLIENT_ADDR, as it will always be overridden by the endpoint.

**Comment by codefromthecrypt** [comment]
can you clarify if there's any action desired on this?

**Comment by virtuald** [comment]
There is, but I'll need to revisit to remember what it was...

**Comment by codefromthecrypt** [comment]
I think this was probably fixed by now
