### ISSUE TITLE
how to set zipkin-web's port

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1121]
i am not want to use 8080, how can i to set the port at start the zipkin-web? 
thanks?  
i view the code

```
val webServerPort = flag("zipkin.web.port", new InetSocketAddress(8080), "Listening port for the zipkin web frontend")
```

but have not found how to change the `"zipkin.web.port"` parameter

**Comment by codefromthecrypt** [comment]
Zipkin-Web is deprecated, but listens by default on port 8080 (bin/web)

**Comment by dragontree101** [comment]
i now use zipkin-web-1.40.1-all.jar,  i want to change port from 8080 to other port
i am not want to use the default port (8080), firstly my question is wrong, sorry.
now i could not to change this port now?

**Comment by codefromthecrypt** [comment]
zipkin-web is a dumb proxy and unnecessary.

You don't need to run it because the javascript is now hosted on the query
server which defaults to port 9411. This port can be changed with the
QUERY_PORT variable.

Per various communication, the code here is not going to be maintained, so
I would recommend transitioning to the new server. You will get better
support from me and others, as well better documentation and a better
server.

https://github.com/openzipkin/zipkin-java#quick-start

https://github.com/openzipkin/zipkin-java/tree/master/zipkin-server#environment-variables

**Comment by dragontree101** [comment]
thanks very much
you mean is i only startup collector-service and query-service?  
and i will visit localhost:9411 in web?
i try visit  localhost:9411, that's ok!!
👍

**Comment by codefromthecrypt** [comment]
Yep! Plus, depending on what you are doing you don't even need collector.

**Comment by dragontree101** [comment]
i think zipkin's work flow is app -> data -> kafka <- collector -> cassandra <- query <- web
if i don't start up collector? how zipkin can fetch data from kafka?

**Comment by eirslett** [comment]
The flow is app -> data -> kafka -> [zipkin-all-in-one-application] -> browser/developer (the all-in-one-application, which is zipkin-java, also connects to cassandra)

**Comment by dragontree101** [comment]
thanks, @eirslett   your mean is i only use zipkin-java? 
zipkin-java it contain origin three part?(collector, query and ui)?

i clone zipkin-java code, and checkout 1.0.0 but not found the ui code, ui code does not in this project?

**Comment by eirslett** [comment]
Yes, that is correct. They are all in the same application.
The UI code is actually in the scala git repository, but from that repository it is published as a jar file, and that jar file is imported to zipkin-java.

**Comment by dragontree101** [comment]
ok， i try to deploy zipkin-java!   thanks very much!

**Comment by dragontree101** [comment]
@eirslett   i move to use zipkin-java, but i send message to kafka, but cassandra's db not find my trace, and i found zipkin-java use kafka 0.8.x version, but i use kafka is 0.9.0.1 version
but when i use origin zipkin (collector, query and ui)  is ok.  
i startup zipkin-java `STORAGE_TYPE=cassandra java -jar zipkin-server-1.0.0-exec.jar`

**Comment by dragontree101** [comment]
i change start up command to `STORAGE_TYPE=cassandra KAFKA_ZOOKEEPER=127.0.0.1:2181/ java -jar zipkin-server-1.0.0-exec.jar --logging.level.zipkin=DEBUG` is ok, zk is not default.....
i am sorry

**Comment by codefromthecrypt** [comment]
Glad things are working for you!
