### ISSUE TITLE
Any plan to make trace id and span id UUID?

### ISSUE THREAD

**Issue by chihhsiw** [openzipkin/zipkin#1123]
Hi,
   I'd like to see if there is any plan to make trace id and span id UUID

thanks

William

**Comment by eirslett** [comment]
No, there are no concrete plans. When Zipkin was first designed at Twitter, 64 bits was a well thought-out id length, it's a balance between size and chance of collision.

**Comment by codefromthecrypt** [comment]
just opened this as a constrained proposal to only address the trace id as 128bit https://github.com/openzipkin/zipkin/issues/1262
