### ISSUE TITLE
Why zipkin-dependencies tab show  nothing statistics information and how should  i  do ?

### ISSUE THREAD

**Issue by jahnkey** [openzipkin/zipkin#1129]
Dears,  let me talk about the  issue. 
1.  i  deployed zipkin server via docker and all server(collector、cassandra、query、web-UI) run  normally  ;
2.  By the brave client sent log info to query service(the query default port is： 9411) ;
3.  Then i can find the  tracer information on the zipkin-> web-UI  server 。
4.  issues is：the dependencies tab  have nothing to show .  what should i do and then the dependencies tab will  show the  statistics info , thanks very much.

**Comment by eirslett** [comment]
You must run the zipkin-dependencies-spark job. It's a single jar file that you can execute.

**Comment by rogeralsing** [comment]
How do you do this when running Zipkin using the Docker image?

**Comment by codefromthecrypt** [comment]
This issue was moved to openzipkin/docker-zipkin#112
