### ISSUE TITLE
Can't register spans with zipkin-tracer gem

### ISSUE THREAD

**Issue by ikeisuke** [openzipkin/zipkin#1130]
I use json-api with zipkin-tracer gem.
Zipkin-tracer send a request with null parentId, but zipkin 1.1.4 is not accepted null parentId.
I tried to remove parentId when parentId is null and send a request, so it was successful.

zipkin error meessage:

> Cannot decode spans due to IllegalArgumentException(Expected a string but was NULL at path $[0].parentId reading List<Span> from json:

versions:
- zipkin 1.1.4
- zipkin-tracer 0.18.1 json-api tracer.

**Comment by singram** [comment]
There is a open pull request to resolve this issue here  https://github.com/openzipkin/zipkin-tracer/pull/67

**Comment by codefromthecrypt** [comment]
we can change the parser, too. To be clear, it is sending `"parentId": null` right?

**Comment by codefromthecrypt** [comment]
some relevant notes here https://github.com/openzipkin/zipkin-api/pull/17
