### ISSUE TITLE
How to judge whether a node is no longer invoked?

### ISSUE THREAD

**Issue by wjc133** [openzipkin/zipkin#1131]
If a node is no longer invoked, I found it steel on the dependencies web page. But it should no longer a member of the group. Do you think that's a bug? If yes, how to judge whether a node is no longer invoked?

**Comment by eirslett** [comment]
Remember, the dependencies page is an aggregate of the last hours (or up to last 7 days) of data, so it may take some time before it disappears.

**Comment by wjc133** [comment]
OK, Thx
