### ISSUE TITLE
UI doesn't resolve durations properly

### ISSUE THREAD

**Issue by marcingrzejszczak** [openzipkin/zipkin#1132]
Hi!

For some reason a request repeated to the same endpoint twice for the same trace, makes the UI render the durations improperly.

Check out this section (2 completely different requests, having same traceid, shot to the same endpoint):

```
{
    "traceId": "caa9948bef618715",
    "name": "http:/present/order",
    "id": "c7d6f8f1f0be2d7f",
    "parentId": "c47bbb8a2ea2334a",
    "timestamp": 1465236501361000,
    "duration": 28000,
    "annotations": [],
    "binaryAnnotations": [
      {
        "key": "http.status_code",
        "value": "500",
        "endpoint": {
          "serviceName": "presenting",
          "ipv4": "10.69.252.94",
          "port": 9991
        }
      },
      {
        "key": "lc",
        "value": "unknown",
        "endpoint": {
          "serviceName": "presenting",
          "ipv4": "10.69.252.94",
          "port": 9991
        }
      }
    ]
  },
  {
    "traceId": "caa9948bef618715",
    "name": "http:/present/order",
    "id": "23ca77c6a15733bd",
    "parentId": "1c57dfdea6d8f7e8",
    "timestamp": 1465236636507000,
    "duration": 23000,
    "annotations": [],
    "binaryAnnotations": [
      {
        "key": "http.status_code",
        "value": "500",
        "endpoint": {
          "serviceName": "presenting",
          "ipv4": "10.69.252.94",
          "port": 9991
        }
      },
      {
        "key": "lc",
        "value": "unknown",
        "endpoint": {
          "serviceName": "presenting",
          "ipv4": "10.69.252.94",
          "port": 9991
        }
      }
    ]
  }
```

JSON:
[bad_duration.txt](https://github.com/openzipkin/zipkin/files/301069/bad_duration.txt)

SCREEN:
![bad_duration](https://cloud.githubusercontent.com/assets/3297437/15833097/66d0959a-2c25-11e6-8a87-489a4f162e84.png)

**Comment by eirslett** [comment]
I'm not quite sure I get what the error is... what would the expected output look like?

**Comment by marcingrzejszczak** [comment]
Twice the graph. As you can see the last couple of spans don't have a
duration set. For some spans the duration of negative whereas in the json
it's not.

**Comment by marcingrzejszczak** [comment]
So it should look more or less like this (I've done the edits in Gimp ;) ):

![isues_1132](https://cloud.githubusercontent.com/assets/3297437/15847391/d02f0796-2c85-11e6-9ae2-1857f644cb1e.png)

In the initial picture you can see 16 spans. Actually those are 2 x 8 spans. However the second 8 spans have their durations completely ignored. Actually they have everything ignored in the UI. Also when I click in the span I get some negative times - I'll try to upload the image in a second.

**Comment by marcingrzejszczak** [comment]
And when I click at one of the spans (I've clicked it on another computer so it won't have much to do with the attached JSON) I get such entries:

![isues_1132_span](https://cloud.githubusercontent.com/assets/3297437/15849072/e0058374-2c90-11e6-9475-a995c7685ce4.png)

**Comment by marcingrzejszczak** [comment]
It seems that the issue was with the initial sent span. Let's close it for now
