### ISSUE TITLE
Enable CORS for zipkin-server

### ISSUE THREAD

**Issue by mikewrighton** [openzipkin/zipkin#1135]
Enabling CORS headers (`Access-Control-Allow-Origin: *`) in the Zipkin query API will allow API access from UI applications running on different hosts, which seems very useful. Is there a reason not to enable this by default?

**Comment by eirslett** [comment]
+1
No reason, except nobody has made a PR yet :wink:

**Comment by codefromthecrypt** [comment]
Sounds fine to me..  implementation would be to add `@CrossOrigin` onto `ZipkinQueryApiV1`

@gena01 @marcingrzejszczak @shakuzen unless you know a reason not to, let's make this change
