### ISSUE TITLE
what's the meaning "88%"  of  this sentence: mysql-ycfsolr_inno 88% .

### ISSUE THREAD

**Issue by jahnkey** [openzipkin/zipkin#1137]
_9.000ms 9 spans
mysql-ycfsolr_inno **88%**
mysql-ycfsolr_inno x4 3ms ycf-search x5 3ms_

above content show on zipkin  find a trace page

question：
what's the meaning "88%"  of  this sentence: mysql-ycfsolr_inno 88% .   thanks！

**Comment by codefromthecrypt** [comment]
pretty sure this means that of the services participating in the
trace, mysql-ycfsolr_inno
accounted for 88% of the critical path duration.

to prove it I'd need to look deeper as I've not looked closely at the code
involved

**Comment by jahnkey** [comment]
thanks  very much！
welcome to guangzhou china @adriancole  :-)

**Comment by jorgheymans** [comment]
question answered, thanks.
