### ISSUE TITLE
The page problem

### ISSUE THREAD

**Issue by luoyongjiee** [openzipkin/zipkin#1138]
![zipkin](https://cloud.githubusercontent.com/assets/9767270/16257277/197bff84-388a-11e6-88d3-ec07305eeb80.png)
hello,look at my photo, in my program, zhconverter.convert happens before vproductsolrqueryparser.parse, but what it show in zipkin-ui is the vproductsolrqueryparser.parse  go ahead ！ is it time very closed!  Any good idea to solve it！

**Comment by codefromthecrypt** [comment]
look at the json (click json) associated with this trace.. it might show
the timestamps for these spans are the same?

**Comment by codefromthecrypt** [comment]
closing for now.  to sort this kind of problem means looking at json usually
