### ISSUE TITLE
Is there an official openzipkin C#/.NET implementation?

### ISSUE THREAD

**Issue by hakanson** [openzipkin/zipkin#1139]
Not sure I'm creating this issue in the appropriate repo, but I am looking for a C#/.NET implementation.  I see Java, Go, Ruby and Node.js repos under openzipkin, but nothing I can plug into my ASP.Net Web API 2 based services.

I did find https://github.com/mdsol/Medidata.ZipkinTracerModule which is implemented as OWIN Middleware and looks like a good candidate.  Is there any "official" compatibility test or other way to check compliance?  Can that repo be "taken over" my openzipkin?  Other non-official recommendations?

**Comment by jcarres-mdsol** [comment]
List of instrumentations:
http://zipkin.io/pages/existing_instrumentations.html

https://github.com/mdsol/Medidata.ZipkinTracerModule Should be compatible with current server and other implementations

**Comment by hakanson** [comment]
Thanks. I guess I should have started by looking at the docs instead of the code.
