### ISSUE TITLE
For exception changing the Color to Red

### ISSUE THREAD

**Issue by prateekvjain** [openzipkin/zipkin#1140]
Hi,
Can we have some feature where, if I have a tag added Key as "Exception" or  "error" the color changes to red , to have it highlighted

**Comment by codefromthecrypt** [comment]
we'd need a heuristic for error status (or a new field on Span), as you
mentioned..

@yurishkuro you have an opinion on this?

**Comment by yurishkuro** [comment]
in [OpenTracing](http://opentracing.io/data-semantics/) a span in error is indicated by `span.SetTag("error", true)`. Would be neat if Zipkin UI recognized it out of the box, without translation.

Another option, not yet standardized in OpenTracing, is `span.log_event("error")`, which could be displayed as a red dot on a timeline, rather than coloring the whole span. 

The former is a stronger statement (made by end user) about the state of the span than the latter.

**Comment by codefromthecrypt** [comment]
both sound reasonable

**Comment by codefromthecrypt** [comment]
@virtuald you think you might be able to help make this come to life? Even in zipkin's internal troubleshooting, I could find value in quickly identifying an error span.

**Comment by virtuald** [comment]
Sure, it should be fairly easy to do. I'll look into it later today.

**Comment by virtuald** [comment]
Let's clarify what we would actually do then in zipkin terms:
- If an annotation named `error` is present in a span, then the dot associated with the annotation is colored red. Perhaps the entire span is also colored yellow, or some other color that draws your attention to it?
- If a binary annotation with the keyname `error` is present in a span, then the entire span is colored red

Sound good?

**Comment by codefromthecrypt** [comment]
> Let's clarify what we would actually do then in zipkin terms:
> - If an annotation named error is present in a span, then the dot
>   associated with the annotation is colored red. Perhaps the entire span is
>   also colored yellow, or some other color that draws your attention to it?
> 
> Here's 2p: If there is only one service participating in the span, it is
> unambiguously error, so red. When there's 2 aka RPC (client+server), it
> could be yellow. Also fine with red regardless of how many services
> participate.
> - If a binary annotation with the keyname error is present in a span,
>   then the entire span is colored red
> 
> SG
> 
> Sound good?
> 
> yeap sounds good! I'll raise a PR to add annotations to the constants file
> base on OpenTracing's (simply the word "error")

**Comment by codefromthecrypt** [comment]
Here's documentation for the error https://github.com/openzipkin/zipkin-api/pull/18

**Comment by prateekvjain** [comment]
Thanks everyone for having it closed
