### ISSUE TITLE
Should we add the "json button" to the main search view?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1143]
Sometimes folks report issues about inconsistency of list responses, but delay in responding with json that would help us validate or fix the issue.

For example, #1142 claims limit isn't working right in cassandra eventhough it seems to in mysql. It might well be a problem, but attempting to guess is very inefficient timewise and rarely effective vs json or a test case.

Should we place a JSON button somewhere subtle in the search pane so that troubleshooting doesn't require issue submitters to hand enter api paths?

My assumption is that if we placed a button there, it might reduce the overhead of solving an issue. Typically, I can validate an issue in a minute or two given json. Back and forth without any data often displaces an hour or more. We need to be able to help support users without displacing so much time.

**Comment by eirslett** [comment]
That's fine with me!
