### ISSUE TITLE
Metrics and Logging for AsyncSpanConsumer

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1145]
While investigating #1141, I noticed that while we have good logs and metrics for collectors, we have no logs or metrics for store operations. The impact is that it is very hard to debug subtle issues where collection is successful, but storage doesn't throw an exception, but still fails.

**Comment by jorgheymans** [comment]
`git log --follow -p -- zipkin/src/main/java/zipkin/AsyncSpanConsumer.java` shows that the concept of `AsyncSpanConsumer` was reworked into `StorageComponent` (see https://github.com/openzipkin/zipkin/commit/0635ffbc848e7ed351055205f21918d7e3bcf860 ). 

From the storage components, only the Cassandra storage is lacking metrics, this is better tracked in https://github.com/openzipkin/zipkin/issues/1769.
