### ISSUE TITLE
Tracing data from 1970

### ISSUE THREAD

**Issue by antlsung** [openzipkin/zipkin#1151]
My tracing data is being labeled as coming from January 1970. I assume this is some default date, and I'm wondering why since I've put the correct timestamp on all my annotations/spans using System.currentTimeMillis(). Any ideas? I am using the Java Brave Zipkin implementation

![image](https://cloud.githubusercontent.com/assets/9828758/16391181/fc66bb80-3c73-11e6-8166-81589e0e452e.png)

**Comment by eirslett** [comment]
They are supposed to be micros. Multiply by 1000 ;-)

**Comment by eirslett** [comment]
But if you use Brave, that should happen under the hood...
