### ISSUE TITLE
does zipkin support cassandra 3.0.x or 3.7

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1154]
i have found cassandra lastest version is 3.7 or 3.0.7, dose zipkin support these version?

in readme:
`The CassandraStorage component is tested against Cassandra 2.2+.`

so i don't know does support cassandra 3.7 or 3.0.7
thanks

**Comment by codefromthecrypt** [comment]
we don't run tests on 3.7, but I don't know a reason why it wouldn't work.

**Comment by dragontree101** [comment]
oh,  your mean is zipkin run on 3.7 will is ok,  but you have not test?
i will test zipkin in cassandra 3.7
thanks.

**Comment by codefromthecrypt** [comment]
I mean proceed, and report any issues!

**Comment by dragontree101** [comment]
i have done some simplest test， it seems ok.  thanks!
