### ISSUE TITLE
How many Partition of kafka  should I have?

### ISSUE THREAD

**Issue by luoyongjiee** [openzipkin/zipkin#1159]
Hello,
         If  i storge in cassandra and  collects in kafka,how many partition should I have?

When i storge in cassandra and  collects in kafka that has 8 partitions  and 4 brokers,it could not collect the correct number of spans. 

![zipkinsame](https://cloud.githubusercontent.com/assets/9767270/16544856/03e5da16-4148-11e6-8c7b-6011596f9abf.png)
In the picture ,the request is same,but one receives 9 spans,the others receives 7 spans. In the fact ,it should receive 9 spans;

And when storge in mysql and and  collects in kafka that has 8 partitions  and 4 brokers, it will all receive 9 spans from the same request.  Why ?

**Comment by codefromthecrypt** [comment]
kafka partitioning shouldn't work differently per storage backend. I think
you are running into the limit problem (#1142)

@prat0318 do you have any general advice on partitioning to share (I can
try to include it in docs)

**Comment by prat0318** [comment]
I second @adriancole, changing backend store like cassandra/mysql shouldn't affect the # of returned spans. Try changing limit to 100 or so.

I would say, start with a small number like # of partitions = # of brokers. If you see latency constraints, try the KAFKA_STREAMS option with the value same as # of partitions (collector now tries to read from all partitions parallely). As the number of partitions can't be reduced and it is just a one way road, increase should only be done if latency becomes an issue. Increase in partitions generally leads to overhead in maintainence etc.

**Comment by codefromthecrypt** [comment]
related to #903

**Comment by codefromthecrypt** [comment]
ps there are notes about Yelp's infrastructure (which uses kafka) here https://docs.google.com/document/d/1Px44fjZ37gr05lV7UFo8AfrWZCcJHCuv58290XCbDaw/edit#
