### ISSUE TITLE
Could modules be deployed in separate hosts?

### ISSUE THREAD

**Issue by Ryann-Luo** [openzipkin/zipkin#1168]
Previously, the Collector, Query and Web are separate services and they can be deployed on different hosts. Now from the Readme, the quickest way to run is by java -jar command. I wonder if I can do the same thing in old style since I don't want all the modules are on the same machine. Thanks!~

**Comment by eirslett** [comment]
Yes, you can java -jar 3 instances if you want to, on 3 servers, with one instance each. And then configure the instances to only behave as one of the "roles". (I think it's possible to disable roles)

**Comment by codefromthecrypt** [comment]
Thanks for answering!

**Comment by codefromthecrypt** [comment]
When we released the new server, we clarified this topic on the mailing list, too, which you are free to join, too!  https://groups.google.com/forum/#!topic/zipkin-user/VtyR3GD-0Fo

**Comment by Ryann-Luo** [comment]
@eirslett @adriancole Thanks a lot!~
