### ISSUE TITLE
  Can  zipkin-sever be distributed deployment! 

### ISSUE THREAD

**Issue by luoyongjiee** [openzipkin/zipkin#1171]
Hello
        If I have a lot of spans to consume(kafka+cassandra), one zipkin-sever will take much time to insert into  cassandra!  Too slowly!  Can  zipkin-sever be distributed deployment! 
       Any good ideas!  Thank you!

**Comment by codefromthecrypt** [comment]
yes, this is related to your other question, where the answer implied you can run multiple instances of zipkin #1159

When we released the new server, we clarified this topic on the mailing list, too, which you are free to join https://groups.google.com/forum/#!topic/zipkin-user/VtyR3GD-0Fo

**Comment by dragontree101** [comment]
if i want to run multiple instances of zipkin,  i only need to start zipkin server, and these zipkin server has the same config?

@adriancole if i run multiple instances of zipkin on multiple ip, does these ip both have web ui?  can i start up multiple instances of zipkin-collector and only one zipkin-query and one zipkin-web-ui?

**Comment by codefromthecrypt** [comment]
@dragontree101 there's not much point in creating a separate JVM for the UI, as the UI is just javascript and configuration. Some host the UI on nginx, but we don't support this at the moment.

Configuration aside, there's no state shared between the api/ui components and the collector ones.

This means yes, you can choose to send api/ui traffic to different servers than you send spans to.

**Comment by dragontree101** [comment]
i don't understand your mean, sorry. 

i start zipkin-server by command `java -jar zipkin-server-1.0.0-exec.jar` and i can visit web in localhost:9411, if i start up 3 zipkin-server in different server, i think i can visit web in `zipkin-server-1:9411`, `zipkin-server-2:9411`, `zipkin-server-3:9411`

can i only use one `zipkin-server-1:9411` and close others?

**Comment by codefromthecrypt** [comment]
yep. they don't coordinate or share state between each other. (ps use a
later version like 1.2.1 :) )

think of them like you would a normal stateless api server.
