### ISSUE TITLE
Should we allow Span.duration = 0?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1174]
Should we say durations <1 microsecond should round up to 1 microsecond?

Reason is that sometimes instrumentation accidentally store 0L when they mean null. We could coerce to 0 -> null, if we documented it. This could prevent some mistakes at the cost of special-casing when rounding <1 microsecond spans.

See #1173

**Comment by basvanbeek** [comment]
I think rounding up <1 microsecond durations to 1 microsecond is a good idea for another reason. 

It will make it less ambiguous in the UI if 1μ is shown instead of 0μ to imply there was cost involved in the logic timed within the span.

**Comment by eirslett** [comment]
+1 for rounding up

**Comment by codefromthecrypt** [comment]
first adjustment is to zipkin-api https://github.com/openzipkin/zipkin-api/pull/19
