### ISSUE TITLE
Disable scribe by default

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1192]
We routinely get user questions about TooLongFrameException. This is almost always someone accidentally using the scribe port 9410 as an http port by accident.

I think we should disable scribe by default and eliminate this problem.

Here are some issues logged against this, but it also comes up on gitter
https://github.com/openzipkin/docker-zipkin/issues/106
https://github.com/openzipkin/zipkin/issues/1186

**Comment by codefromthecrypt** [comment]
All major tracing libraries support alternatives to scribe. I think we should disable it by default.

**Comment by tylerhjones** [comment]
👍 , just ran into this issue

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1540
