### ISSUE TITLE
QueryParsingException : nested object is not of nested type 

### ISSUE THREAD

**Issue by phoebetse** [openzipkin/zipkin#1193]
Running some of the tests with ElasticSearch in [SpanStoreTest](https://github.com/openzipkin/zipkin/blob/master/zipkin/src/test/java/zipkin/storage/SpanStoreTest.java) throws a `QueryParsingException[[nested] nested object under path [binaryAnnotations] is not of nested type].`

Seems to be a problem when using QueryRequest.Builder.build(); could potentially be a race condition

**Comment by codefromthecrypt** [comment]
this has been fixed
