### ISSUE TITLE
Duration <= option in UI ?

### ISSUE THREAD

**Issue by mathuo** [openzipkin/zipkin#1205]
Any plans to add a duration less than box to allows searches for x <= duration <= y ?

**Comment by codefromthecrypt** [comment]
no current plans, but an issue is the first start! (api supports it)

UI-wise, microsecond resolution is the only thing that makes using normal
javascript elements tough

**Comment by jorgheymans** [comment]
This has actually been implemented at some point, here is a list of traces in Lens:

![image](https://user-images.githubusercontent.com/193792/97087877-8e335400-162d-11eb-8ff7-134504043c10.png)

So when we then set minDuration to 20ms and maxDuration to 30ms, the only trace returned is 26.914ms which is correct.


![image](https://user-images.githubusercontent.com/193792/97087916-bf138900-162d-11eb-91a0-4b3211a81445.png)
