### ISSUE TITLE
how can i get zipkin version from zipkin-ui?

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1208]
how can i get zipkin version from zipkin-ui?
i update zipkin, but don't know how to get zipkin-ui version from web.

**Comment by shakuzen** [comment]
@dragontree101 Are you running Zipkin server (the self-contained executable jar `zipkin.jar`), or serving the `zipkin-ui` some other way?
Also to clarify your question, you want to know what the current version number of a running Zipkin instance is, or are you looking for something else?

**Comment by dragontree101** [comment]
@shakuzen 
i run newest version, use zipkin.jar  (zipkin-server-1.5.1-exec.jar),  
i just want to get current zipkin version from  web ui,  i have not found any version in web.

**Comment by shakuzen** [comment]
@dragontree101 thank you for the quick response! I understand what you're expecting and I don't think there is any way to get that information currently. We should be able to add it easily enough though. I will submit a pull request for review with a potential solution tomorrow or the next day.

**Comment by dragontree101** [comment]
@shakuzen thanks!
