### ISSUE TITLE
Concerns with sort behavior in the UI

### ISSUE THREAD

**Issue by virtuald** [openzipkin/zipkin#1218]
Let's say I hit 'find traces' for a particular service name, with the other thing set to 'all'. Ok. The top 10 results come back... let's say I get some spans ranging from 4.5s to 1.0s. Cool.

A few seconds later, I go back to the main page, and I hit 'find trace' for the same service name. This time the top result is 40ms, not 4.5s. This seems fishy, and very unexpected.

I played around with it a bit more, and if I increase the limit to something large, then I can see the original spans that came back in my original query. 

What gives? I had assumed that when I have sort selecting 'longest first', that it would return the longest spans in the given time range. However, it seems to be just picking LIMIT entries at random, then sorting those. That seems less than ideal -- **particularly** because duration queries never work on my single-node cluster (always times out).

Zipkin 1.6, cassandra backend.

**Comment by codefromthecrypt** [comment]
Answering one part:

The UI element is only affecting the order of results client-side. It isnt
a server side filter.

**Comment by codefromthecrypt** [comment]
trying to parse through your frustration.. sorry you are frustrated.

zipkin's api is a timeline one. results are always closest to the end time,
filtered by the criteria mentioned. Think of it like twitter itself. I
can't search twitter in reverse order and then by longest tweet.
Bottom-line, this isn't SQL: you can't do server-side sorts in arbitrary
order in all backends.

Anyway you ask for traces without putting a constraint on duration, there
is no constraint. They are ranked by timestamp descending on the server.
You can put a duration constraint, but in the case of cassandra, the
performance of such a query is not yet sorted
https://github.com/openzipkin/zipkin/pull/1204.

I think the biggest problem is the UI element is confusing things.. it
hints at a feature that doesn't exist.  It should be more clearly moved or
worded to indicate that it is for resorting results, not a server-side
ordering task. I may be wrong in this thinking.

  ps. While the api is like twitter, unlike twitter, we don't have advanced
timeline controls https://dev.twitter.com/rest/public/timelines, nor a
thousand engineers. We are primarily limited by able hands and secondarily
by what's supported on mysql vs elasticsearch vs cassandra. IOTW help
wanted!

**Comment by virtuald** [comment]
The frustration is mostly from thinking that it worked one way, and accidentally discovering that it worked another. :)

If the UI display is clearer about what one was actually doing, that would be a good start.

**Comment by Jaware** [comment]
so i have to modify zipkin source codes  to add back end sorting and remove front sorting

**Comment by codefromthecrypt** [comment]
>
> so i have to modify zipkin source codes to add back end sorting and remove
> front sorting
>
if you are able to do that across all backends, please do report back.

**Comment by codefromthecrypt** [comment]
@igorwwwwwwwwwwwwwwwwwwww I think you are also interested in sort behavior. There is some background here.. probably worthwhile to see how other timeseries projects who support cassandra backend do multiple index sorting as cassandra is the more popular backend and mysql doesn't scale (as it is currently designed)

**Comment by Jaware** [comment]
i have modified the es part,i think es is the most efficient and powerful backend,cassandra is a bit hard to use like hbase,you have to add index to to the search field,really bad

**Comment by dhay** [comment]
I'm not the only one who was confused.  Everyone where I work is confused when they learn that the sorting is on the front end.  It's unfortunate that the QueryRequest object doesn't even support the option of sorting on the back end.

**Comment by codefromthecrypt** [comment]
the api doesn't support sorting. would it be less confusing if we removed
the client side sort option? we could make a config parameter to disable it.

**Comment by codefromthecrypt** [comment]
we are switching the order to newest first which matches the server-side ordering #1926

however, we'll still have people surprised that we can't arbitrarily sort in all backends by fields such as duration. That's not something we have any good alternatives to, so we will try to address this in docs in #2488
