### ISSUE TITLE
Allocate release commits to a dummy user like travis

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1220]
_From @adriancole on May 30, 2016 0:6_

I noticed that guava credits travis for release commits. This is probably better than me or james :)

```
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "travis-ci"
```

_Copied from original issue: openzipkin/zipkin-java#254_

**Comment by codefromthecrypt** [comment]
_From @eirslett on May 30, 2016 22:7_

Or maybe openzipkin...

**Comment by jorgheymans** [comment]
if still relevant, dupes #1047
