### ISSUE TITLE
Document retention practice for elasticsearch

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1222]
_From @adriancole on May 26, 2016 15:22_

As mentioned by @yurishkuro in response to a TTL question from @devinsba, the recommended way for ES is to use index aliases, and assign unique index names every N days and drop the old indices. It is much more performant than doing TTL and compactions.

The current implementation has an `IndexNameFormatter` that's something like `${zipkin.storage.elasticsearch.index}-yyyy-MM-dd` for timestamped entries and `${zipkin.storage.elasticsearch.index}-*` for catch-alls.

We should document how this relates to those using TTLs and any practices that would be easy to employ for expiring data.

_Copied from original issue: openzipkin/zipkin-java#249_

**Comment by codefromthecrypt** [comment]
@anuraaga thoughts?

**Comment by codefromthecrypt** [comment]
_From @yurishkuro on May 26, 2016 15:27_

One thing I am not sure about is whether there are actually any tools in ES to auto-expire the named indices that are outside of the retention window. I believe ES does not provide that out of the box and people are implementing adhoc devops solutions for that, which is sad.

**Comment by codefromthecrypt** [comment]
_From @anuraaga on May 27, 2016 3:47_

Elasticsearch has a tool called curator which makes this pretty easy - I guess it's somewhat official. Yeah, it is a cron job somewhere so a bit of complexity but usage is really easy, you can specify a prefix of indices to delete, when they are older than n days. e.g. 

```
curator delete indices --prefix zipkin- --older-than 7 --time-unit days --timestring %Y-%m-%d
```

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html

I was using this initially but we actually use the same elasticsearch for metrics as well, for which we needed a more complex custom cleanup job written in Java, so I ended up just adding the zipkin cleanup to that job as well but when this isn't the case, curator is great.

**Comment by dangets** [comment]
I'm currently prototyping Zipkin with ES backend and one concern is the eviction strategy.

I think it'd be useful to have a configurable default ttl - days, week, etc..  But I think it'd also be pretty neat to be able to mark specific traces to be retained for much longer - so if we're working on investigation the trace and link can stay around for much longer.

I'd be willing to help design / implement this, but would like to get a discussion going.

**Comment by codefromthecrypt** [comment]
> I'd be willing to help design / implement this, but would like to get a
> discussion going.
> 
> sgtm would be interested in other's thoughts, too. ps here's the last
> request for saving a trace: https://github.com/openzipkin/zipkin/issues/1093

**Comment by anuraaga** [comment]
I think having a path that can save to an index named something like '.zipkin-infinite', which is not a daily bucketed index, would be pretty trivial to implement and allow saving traces. I don't think elasticsearch's TTL functionality should be used at all as per the caveats in their documentation

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html

1) It's deprecated with no successor
2) Performance hit is not worth it compared to pruning daily indexes

**Comment by dangets** [comment]
That sounds good to me - or you could always kick it out to an arbitrary date index instead of infinite.  Might need a way to delete specific traces to help cleanup the 'infinite' but this can probably be a separate issue.

**Comment by codefromthecrypt** [comment]
> I think having a path that can save to an index named something like
> '.zipkin-infinite', which is not a daily bucketed index, would be pretty
> trivial to implement and allow saving traces.
> 
> This is a great idea and also super-easy in elasticsearch as we don't need
> to do anything except move documents. It might take some thinking on other
> backends.

**Comment by dangets** [comment]
I'd like to start prototyping some things out for this, but would like to get opinions on best places to put the functionality.

I'd like to add a couple of methods to the interfaces, but I know this would break existing implementations if we can't use Java8 default method implementations.

I was thinking something like `SpanStore.setTraceExpiration(long traceId, Date date)` and `SpanConsumer.setDefaultTraceExpiration(int numDays)`.  Of course it we could change units to allow finer granularity - or use `(int duration, TimeUnit unit)`

EDIT:  It would be up to the implementations on the granularity of eviction that they would support - so e.g. Elasticsearch could use the daily indexes to drop batches.

**Comment by dangets** [comment]
As far as kicking off the eviction process - I was thinking just a background scheduled thread.

**Comment by codefromthecrypt** [comment]
Not currently keen on this being a span store method because eviction is
low priority and can be handled more bluntly in ES (drop the whole daily
index after a point) right?

**Comment by dangets** [comment]
I was trying to consolidate the ideas of individual trace retention along with default trace eviction - though I don't like it on the grounds of backwards-incompatibility.

**Comment by codefromthecrypt** [comment]
> I was trying to consolidate the ideas of individual trace retention along
> with default trace eviction - though I don't like it on the grounds of
> backwards-incompatibility.
> 
> ahh thinking ahead :)

So, in some span stores, there's no eviction at all. Are you anticipating
storage usage being a problem on this feature? Wondering if we can separate
save-a-trace from retention policy of saved traces at least initially.  PS
should probably move this discussion to #1093

**Comment by anuraaga** [comment]
Just want to clarify one point, that strictly speaking dropping daily indexes isn't handled "in ES". ES team maintains the `curator` tool that makes it relatively easy, but still requires installing + running a cron-type job.

I can see an argument for the ease of set-up of zipkin-server including a background job that handles cleaning up daily indexes. It also seems weird for a frontend server, which there may be N replicas of, running cleanup tasks against a single backend - the worst case though would probably be N-1 replicas logging an error and humming along.

So my recommendation would be that it'd be ok to have a background cleanup thread, with clearly documented caveats that it's mainly for simple deployments and in general is preferred to use a cleanup cron external to zipkin-server.

**Comment by dangets** [comment]
Is curator "better" than doing [Delete Index](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html) ?  I can see arguments for having daily cleanup external to zipkin-server, but just curious.

**Comment by dan-tr** [comment]
We are a fairly mature ES shop and already have a cleanup process for our ES clusters. So I would definitely like the option to turn off zipkin-server cleanup (when/if it becomes available) and instead use our existing external cleanup process.

**Comment by anuraaga** [comment]
For a deployment with a single zipkin-server, I think curator and DeleteIndex are essentially equivalent. For a deployment with multiple zipkin-servers (IMO any production deployment should have at least 2 for redundancy), I'd be nervous having multiple machines essentially competing to have their DeleteIndex succeed, where all but one will fail - normal failures tend to make systems fragile.
