### ISSUE TITLE
RxJava?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1227]
_From @adriancole on September 3, 2015 22:2_

I started working on an implementation using Java 8 streams, but continually find myself lacking the ability to do things present in Rx.

https://github.com/ReactiveX/RxJava

RxJava is a <1MB zero dep jar. Anyone have an opinion wrt implementing components to support collection and query with RxJava?

_Copied from original issue: openzipkin/zipkin-java#6_

**Comment by codefromthecrypt** [comment]
_From @spencergibb on September 3, 2015 22:7_

:+1:

**Comment by codefromthecrypt** [comment]
_From @NiteshKant on September 3, 2015 22:7_

:+1:

**Comment by codefromthecrypt** [comment]
_From @rtyler on September 3, 2015 22:12_

:beers:

**Comment by codefromthecrypt** [comment]
_From @danchia on June 1, 2016 5:48_

+1

**Comment by codefromthecrypt** [comment]
_From @eirslett on June 1, 2016 8:16_

zipkin-scala was non-blocking, which perhaps gave it a performance gain. Using RxJava increases code complexity, though (especially for the casual contributor who hasen't used Rx before) so I think we should do an experiment and compare performance tests. We should weigh the extra code complexity against the increase in performance.

**Comment by jorgheymans** [comment]
I guess not then, closing.
