### ISSUE TITLE
Make build work with JDK 9

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1230]
_From @adriancole on May 15, 2016 3:10_

This can capture issues and resolutions to issues building with JDK 9

The below are a subset of issues found with build 9-ea+118 (ie by setting JAVA_HOME and running `./mvnw clean install`)
- [ ] Test failure from centralsync-maven-plugin
  - I think we should move this project to top-level since brave needs it anyway
- [ ] ExceptionInInitializerError from maven-jar-plugin 2.6

_Copied from original issue: openzipkin/zipkin-java#231_

**Comment by codefromthecrypt** [comment]
Good news is that if you only compile and run tests from core, it works. This means there's no api compilation concerns in the core library (ex use of internal classes since removed etc)

Ex. `./mvnw clean test -pl :zipkin`

**Comment by codefromthecrypt** [comment]
_From @shakuzen on May 15, 2016 3:47_

It looks like version 3.0 of the `maven-jar-plugin` will be compatible with JDK 9, but it is not currently released. See [MJAR-205](https://issues.apache.org/jira/browse/MJAR-205)

**Comment by shakuzen** [comment]
Note that the `maven-jar-plugin` is up to version `3.0.2` now which should support JDK 9.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1834 should do it..

**Comment by codefromthecrypt** [comment]
#2162 should do the trick
