### ISSUE TITLE
Consider moving off travis, or putting up a redundant job on CircleCI

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1237]
Travis gives free builds, so we certainly have to thank them for that. That said, if there's competition, we might be better off evaluating it.

For example, the competition might..
- actually update things (vs indefinitely lagging on c\* https://github.com/travis-ci/travis-ci/issues/3952)
- not build tags by default (https://github.com/travis-ci/travis-ci/issues/1532)
- not black-hole builds for 1.5hrs with no status update
- have less severe outages (https://www.traviscistatus.com/incidents/11hp8bhkrkn7)
- ... build faster!

We do use travis features, such as credential encryption. This allows us to do tag-driven deploys. We also use docker. When considering an alternative, we should ensure we have feature parity. That said, travis has been so bad lately, we might want to throw up another build checker just to eliminate false-negatives.

cc the interested.. @abesto @shakuzen @marcingrzejszczak (your_name_here)

-- example black hole from today
![screen shot 2016-08-14 at 10 25 05 pm](https://cloud.githubusercontent.com/assets/64215/17649762/fbe08d78-626e-11e6-9e2a-63e93352d9d5.png)

**Comment by codefromthecrypt** [comment]
I rewrote a cassandra test that was timing out to use mocks and the build went green. I'm assuming that we're bumping limits of our slave, and that becomes more obvious when travis is degraded.

**Comment by abesto** [comment]
The big draw of Circle CI (for me at least) is running tests in parallel. In theory that should allow us to significantly cut down on build times. Don't know about reliability; if nothing else, a redundant system sounds like a reasonable idea (don't forget about the increased maintenance burden though). They also offer a nice packag for OSS projects (see bottom of https://circleci.com/pricing/)

**Comment by codefromthecrypt** [comment]
Had to rewrite another test, mainly as something in the travis image ended up consistently changing a failure case behavior. Note that this isn't something we'd necessarily avoid in circleci.

**Comment by abesto** [comment]
Played around a bit with CircleCI. Set up test dependencies, though there's probably something messed up around MySQL because those tests fail with MySQL-related errors. I've also set up parallel test runs, with support for the time-based auto-balancing of CircleCI. The build https://circleci.com/gh/openzipkin/zipkin/24 took 9:23 (compare to the ~14 minutes of Travis); though maybe the failing tests skew things somewhat. There's nothing around publishing wired in yet, though it should be pretty easy to reuse the existing logic.

All the relevant changes are in https://github.com/openzipkin/zipkin/tree/circle-ci. I'm stuck on the MySQL stuff, as well as the other failures; looking for help. Feel free to commit into the branch, without consulting me.

**Comment by abesto** [comment]
Full build time down to 8:15 after figuring out caching (https://circleci.com/gh/openzipkin/zipkin/37), still failing, still looking for halp on that. (Does the test run abort on the first failing test? If so, then timing is not relevant)

**Comment by codefromthecrypt** [comment]
great news.. taking a look at that test now.. maybe it is time sensitive.

**Comment by codefromthecrypt** [comment]
pushed a commit with my suspicion about the test. If this doesn't
work, there's a lag involved in the runtime that might require some
real surgery.

**Comment by codefromthecrypt** [comment]
ok that's done.. now we just need a mysql tweak...

**Comment by codefromthecrypt** [comment]
fingers crossed

**Comment by codefromthecrypt** [comment]
Last mile: timeout on KafkaCollectorTest

**Comment by jorgheymans** [comment]
IIRC circleci was used for a while, then it went back to Travis and has been for a while now.
