### ISSUE TITLE
Zipkin fails to compile in eclipse

### ISSUE THREAD

**Issue by bedag-moo** [openzipkin/zipkin#1241]
When compiling Zipkin in eclipse, compilation fails with

> zipkin/src/main/java/zipkin/collector/InMemoryCollectorMetrics.java:14
> The declared package "zipkin" does not match the expected package "zipkin.collector"

(eclipse enforces that a source file resides in the directory that corresponds to its package)

**Comment by codefromthecrypt** [comment]
:facepalm: ok will fix
