### ISSUE TITLE
Zipkin server as a CloudFoundry service

### ISSUE THREAD

**Issue by hvandenb** [openzipkin/zipkin#1251]
To simplify the deployment of Zipkin within CloudFoundry/Pivotal has there been some thought on making it a CF service. This way projects like Sleuth can just "bind" to Zipkin. This would be a similar approach as what has been done with Eureka and the Discovery Server of Eureka. Interested in hearing thoughts on this.

**Comment by codefromthecrypt** [comment]
I noticed this, which is a bit out-of-date:
https://github.com/frodenas/zipkin-boshrelease

Also, since zipkin server is a spring boot app, there's probably means to
deploy it in cloud foundry as a normal java app.

iirc @Arghanil might have deployed zipkin in cloud foundry..

**Comment by hvandenb** [comment]
The bosh release looks interesting. I've been able to deploy it as a normal java app without any issue. Using Sleuth with my apps. However, I like the simplicity of being able to doing a cf bind or adding Zipin as a service dependency in the manifest. That way apps don't have to know about all the HTTPS and/or streaming to Zipkin server.

**Comment by eirslett** [comment]
Would it be able to setup a transitive dependency on cassandra as well? Ease of deployment is always a good thing :)

**Comment by codefromthecrypt** [comment]
bosh used to..
https://github.com/frodenas/zipkin-boshrelease/tree/master/packages

definitely would need some cleanup. Also, no idea if bosh-lite makes this
easier now. https://github.com/cloudfoundry/bosh-lite

On Tue, Aug 23, 2016 at 10:38 PM, Eirik Sletteberg <notifications@github.com

**Comment by codefromthecrypt** [comment]
not sure if this helps, but pivotal web services (powered by cloud foundry) has been successfully used in sleuth

https://github.com/spring-cloud/spring-cloud-sleuth/blob/2f93bd955a3399224a3cef5d799064342a28e0e7/docs/src/main/asciidoc/spring-cloud-sleuth.adoc#running-examples

@marcingrzejszczak @dsyer do you have any instructions you can paste links to (or just c&p here?)

**Comment by codefromthecrypt** [comment]
@shakuzen mentioned we could also look at porting from a similar guide, like this one http://blog.hazelcast.com/cloud-foundry/

**Comment by marcingrzejszczak** [comment]
@hvandenb @adriancole there's some work in progress on the topic. Until now it's possible to do it without having a separate tile for that. Check out the brewery which is also deployed to CF and tested there - https://github.com/spring-cloud-samples/brewery

**Comment by hvandenb** [comment]
Like the Hazelcast guide with two options
- deploy normal and define user service
- bosh managed with marketplace

I remember seeing a tool at Springone that simplifies the marketplace / service broker part will have to look back at the conf materials.

**Comment by hvandenb** [comment]
On @eirslett comment I like what Spring Cloud Dataflow has done where they use a DPI (think Java spi) for deployments that makes it agnostic of runtime platform. So you can deploy on cloud foundry, kubernetics, docker etc. in consistent manner.

**Comment by codefromthecrypt** [comment]
kudos shoutout to @mminella and team on that deployment niceness. maybe we could open a repo for something similar for zipkin, if someone's up to task (pun intended)

**Comment by hvandenb** [comment]
There is also a nice project to do the title - marketplace generation http://cf-platform-eng.github.io/isv-portal/ Time to start pulling something together.

**Comment by codefromthecrypt** [comment]
@tushar-dadlani if you know of any place users can go to when asking about CF, please note here!

**Comment by codefromthecrypt** [comment]
For those interested, the next OSS Cloud Foundry release (cf-245) will introduce the first phase of Zipkin support. 

Once this is out, it should probably be communicated more broadly via our [existing implementations list](https://github.com/openzipkin/openzipkin.github.io/blob/master/_data/existing_instrumentations.yml), [zipkin-user](https://groups.google.com/forum/#!forum/zipkin-user) and twitter.

You can stalk https://github.com/cloudfoundry/cf-release/releases for details, but here's a sneak preview from @shalako (who's to thank for driving this feature).

---

Zipkin is an optional feature that operators enable by specifying a configuration property in their BOSH deployment manifest:

```
router.tracing.enable_zipkin:true
```

This is support for developer correlation via logs only. When enabled the CF HTTP router (gorouter) will:
- initiate trace id when trace id and span id are not present in the received request: forward `X-B3-TraceId` with requests to apps and log `x_b3_traceid` in access log
- always initiate a span id: forward `X-B3-SpanId` with requests to apps and log `x_b3_spanid` in access log
- initiate parent span id when trace id and span id are present: forward `X-B3-ParentSpan` with requests to apps and log `x_b3_parentspanid` in access log

**Comment by hvandenb** [comment]
@shalako great work for pushing this I really look forward to seeing this.

**Comment by codefromthecrypt** [comment]
@shalako I noticed that 245 is out, but there's no mention of this feature in the main or router release notes https://github.com/cloudfoundry/cf-release/releases/tag/v245 can you ping us when the release notes are updated? cc @tushar-dadlani

**Comment by shalako** [comment]
Release notes for cf-release v243 noted a bump to routing-release v138
https://github.com/cloudfoundry/cf-release/releases/tag/v243

In release notes for routing-release 138 we note initial support for the
new zipkin config property
https://github.com/cloudfoundry-incubator/routing-release/releases/tag/0.138.0

Release notes for v245 noted a bump to routing-release v140 (so includes
changes in routing-release 139 also)

In release notes for routing-release 139 we note added enhancements to
Zipkin support
https://github.com/cloudfoundry-incubator/routing-release/releases/tag/0.139.0

Shannon Coen
Product Manager, Cloud Foundry
Pivotal, Inc.

**Comment by codefromthecrypt** [comment]
Thanks for the sleuthing, Shannon!

**Comment by codefromthecrypt** [comment]
It's too bad cf release notes don't summarize this, but hey. in the
mean time, zipkin just tweeted to point people where to look
https://twitter.com/zipkinproject/status/786761813698289664

**Comment by codefromthecrypt** [comment]
looks like zipkin is mentioned in recent pivotal cloud foundry notes: https://twitter.com/making/status/800708459041722368

**Comment by alwaysastudent** [comment]
`router.tracing.enable_zipkin:true` is specific to the cf router and is helpful only at the HTTP layer. This would not be helpful to trace any messages which won't go through the cf router   ?

**Comment by poblin-orange** [comment]
@alwaysastudent correct. What type of other messages are you thinking off ?

**Comment by alwaysastudent** [comment]
@poblin-orange - we need to trace container to container calls, messaging calls (amqp, kafka etc)

**Comment by jorgheymans** [comment]
Closing as this mostly concerns activity outside of the Zipkin project itself. It seems to have been implemented at some point as Ser Cole points out here https://github.com/openzipkin/zipkin/issues/1251#issuecomment-253697072 and here https://github.com/openzipkin/zipkin/issues/1251#issuecomment-262125630 . If anything should still be done inside of Zipkin itself to facilitate or improve this feel free to open a new issue.
