### ISSUE TITLE
Make zipkin easier to import into eclipse and intellij

### ISSUE THREAD

**Issue by lijunyong** [openzipkin/zipkin#1256]
I git clone this repository and import my eclipse IDE,but it has many errors,how should I do.

**Comment by codefromthecrypt** [comment]
This issue isn't descriptive enough to take action on. We had a fix recently for @bedag-moo who was using eclipse. If you can be more specific on what zipkin needs to do in order to support eclipse, let us know.

**Comment by lijunyong** [comment]
@adriancole I run ./mvnw -DskipTests --also-make -pl zipkin-server clean install  show exception:
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project zipkin-ui: Failed to run task: 'npm install' failed. (error code -1073741795) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zipkin-ui

and which you use IDE?

**Comment by codefromthecrypt** [comment]
@lijunyong the error you pasted has nothing to do with the IDE. it means you haven't installed npm https://www.npmjs.com/package/npm

I use intellij

**Comment by codefromthecrypt** [comment]
OK, here's the deal on eclipse..

If we import with this, language level isn't set properly and so you have to go through and reset everything to java 8. 

``` bash
$ ./mvnw eclipse:eclipse
```

There's probably other things, too, as eclipse is more strict by default than intellij.

**Comment by lijunyong** [comment]
@adriancole thank you very much

**Comment by codefromthecrypt** [comment]
@lijunyong no prob

**Comment by eirslett** [comment]
You don't need to install node or npm to open the project in Eclipse.

**Comment by lijunyong** [comment]
@eirslett How to do?

**Comment by codefromthecrypt** [comment]
PS recent versions of intellij are now harder to use as they have module-specific compiler settings, but not the ability to override them globally. In a sense, this is similar to the problems in Eclipse.

https://youtrack.jetbrains.com/issue/IDEA-161060

Here's an OS/X workaround for when your IDE makes everything use the main tree source level (which makes the test tree fail to compile)

```
find . -name '*.iml' -print0 | xargs -0 sed -i '' 's/JDK_1_6/JDK_1_8/g'
find . -name '*.iml' -print0 | xargs -0 sed -i '' 's/JDK_1_7/JDK_1_8/g'
sed -i '' 's/target="1.7"/target="1.8"/g' .idea/compiler.xml
sed -i '' 's/target="1.6"/target="1.8"/g' .idea/compiler.xml
```

**Comment by nklmish** [comment]
@adriancole We can also add(zipkin-autoconfigure, zipkin-collector, zipkin-guava, zipkin-storage) and update(only for zipkin module not the parent) `java.version` in pom like this:

`<main.java.version>1.6</main.java.version> -> <main.java.version>1.8</main.java.version>`

 I tried and intellij was happy but not sure whether zipkin will be happy ?

**Comment by codefromthecrypt** [comment]
retrolambda works around the problem in a different way https://github.com/openzipkin/zipkin/pull/1425
