### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by xqliang** [openzipkin/zipkin#1263]
Zipkin-1.8.0 UI page will throw javascript exception when any span missing a `binaryAnnotations` field: `Uncaught TypeError: Cannot read property 'map' of undefined`.

Maybe do some null check [here](https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/traceSummary.js#L10)?

``` javascript
// js/component_ui/traceSummary.js
function endpointsForSpan(span) {
  return _.union(
    span.annotations.map(a => a.endpoint),
    span.binaryAnnotations.map(a => a.endpoint)
  ).
```

**Comment by codefromthecrypt** [comment]
Thanks for finding the bug. Are you up to trying a fix?

**Comment by xqliang** [comment]
Sorry, I'm not very familiar with the UI code :(

**Comment by codefromthecrypt** [comment]
it's ok. I'll ping you with a fix and then you'll know more!

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1264

**Comment by codefromthecrypt** [comment]
1.8.1 on the way. sorry folks. I caused this bug

**Comment by codefromthecrypt** [comment]
ok 1.8.1 is out to docker, now.

**Comment by xqliang** [comment]
Great, it's ok now.
