### ISSUE TITLE
Error executing query: server error (parsererror) in Zipkin 1.8

### ISSUE THREAD

**Issue by jpiechowka** [openzipkin/zipkin#1272]
I got `Error executing query: server error (parsererror)` when trying to find traces. This happens after update from Zipkin 1.7.0 to 1.8.2 today. Spans that I send are somehow problematic for the newer version of Zipkin. I get `202 Accepted` response every time.

JSON:

```
[
  {
    "traceId": "5e1b76cb257aa6fd",
    "name": "app - root span",
    "id": "168ba9a2869c3ae1",
    "timestamp": 1473066067938000,
    "duration": 484655,
    "annotations": [
      {
        "timestamp": 1473066067938000,
        "value": "sr",
        "endpoint": {
          "serviceName": "app",
          "ipv4": "0.0.0.0"
        }
      },
      {
        "timestamp": 1473066068422655,
        "value": "ss",
        "endpoint": {
          "serviceName": "app",
          "ipv4": "0.0.0.0"
        }
      }
    ],
    "binaryAnnotations": []
  },
  {
    "traceId": "5e1b76cb257aa6fd",
    "name": "app test - get",
    "id": "fbbff4adc94c01cb",
    "parentId": "168ba9a2869c3ae1",
    "timestamp": 1473066067939000,
    "duration": 483823,
    "annotations": [],
    "binaryAnnotations": [
      {
        "key": "error",
        "value": "org.sql2o.Sql2oException: Database error: ORA-00942: table or view does not exist\n",
        "endpoint": {
          "serviceName": "app",
          "ipv4": "0.0.0.0"
        }
      },
      {
        "key": "lc",
        "value": "Application",
        "endpoint": {
          "serviceName": "app",
          "ipv4": "0.0.0.0"
        }
      }
    ]
  }
]
```

**Comment by codefromthecrypt** [comment]
thanks.. taking a look!

**Comment by codefromthecrypt** [comment]
are the control characters in your json in the actual json itself?

ex. I don't get an error from zipkin-server, rather one using a json parser.

$ curl -s localhost:9411/api/v1/trace/5e1b76cb257aa6fd|jq .

parse error: Invalid string: control characters from U+0000 through U+001F
must be escaped at line 2, column 1

**Comment by codefromthecrypt** [comment]
yeah seems like it.. when I remove the control characters, the rendering
works fine. maybe we can scrub them at ingest...

**Comment by codefromthecrypt** [comment]
figured it out.. we need to do RFC 7159 escaping on ingest. will get this
sorted shortly

**Comment by jpiechowka** [comment]
@adriancole You were so fast I was not even able to respond :D I will stick with 1.7.0 for now.

**Comment by codefromthecrypt** [comment]
curious.. we aren't actually affecting binaryannotation.value when writing.
I think the library you are
posting with is actually sending unescaped json. eventhough we need to fix
here, probably whatever's generating that will also need a nudge (so that
it doesn't produce values like this)

**Comment by jpiechowka** [comment]
@adriancole @nicmunroe I am using [Wingtips](https://github.com/Nike-Inc/wingtips)

**Comment by codefromthecrypt** [comment]
ok well lucky thing this change will fix both :)

**Comment by codefromthecrypt** [comment]
thanks so much for reporting. I've confirmed the fix by posting json
manually (as well unit tests).

1.8.3 on the way (and I'll also push a version of zipkin-reporter-java once
this is out)

**Comment by jpiechowka** [comment]
Thank you @adriancole! I will test the new version when it is out.

**Comment by codefromthecrypt** [comment]
ok it is out now!

**Comment by jpiechowka** [comment]
@adriancole Downloaded from `https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec` and I still get this error with my JSON. Version 1.8.3

**Comment by codefromthecrypt** [comment]
:( I'll do the same and report back. I'm literally copy/pasting from the issue comments..

**Comment by codefromthecrypt** [comment]
head scratching..

**Comment by codefromthecrypt** [comment]
ok this will teach me to switch between too many types of work. The change to fix every thing _except_ the problem you reported was merged. the fix for binary annotation.value was in a git stash.

https://github.com/openzipkin/zipkin/pull/1275

**Comment by codefromthecrypt** [comment]
1.8.4 on the way. sorry about the confusion I created

**Comment by jpiechowka** [comment]
Hahaha, thanks @adriancole for checking this out again.

**Comment by codefromthecrypt** [comment]
ok tested by downloading from maven and doesn't blow up!

**Comment by codefromthecrypt** [comment]
here's for wingtips https://github.com/Nike-Inc/wingtips/pull/24

**Comment by nicmunroe** [comment]
@jpiechowka Merged, built, and deployed @adriancole's wingtips PR as wingtips version 0.11.1. Thanks guys!

**Comment by codefromthecrypt** [comment]
awesome turnaround, nic

**Comment by jpiechowka** [comment]
Tested the new Zipkin version right now and it works well. Thanks @adriancole

**Comment by codefromthecrypt** [comment]
Whew :) thanks for replying back
