### ISSUE TITLE
use es to store zipkin， ui is zipkin's ui or kibana？

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1274]
now i use cassandra to store zipkin， our ui is default's zipkin's ui.
and if i change es to store zipkin, i also use zipkin's ui is ok ? or i must change ui to kibana? 

if i use cassandra store change to es store, what's different  in zipkin's ui ? 
thanks

**Comment by codefromthecrypt** [comment]
The UI is bound to the zipkin api, not the storage driver, so you can use
any of the storage choices.

**Comment by dragontree101** [comment]
thanks @adriancole  
es or cassandra, what is better ?  now we have use cassandra only to store zipkin's info, and some other log use es, if i change zipkin to es, we only use es, it seems simple and easy.

could you give me some suggest?  which store is much better?  thanks very much

**Comment by codefromthecrypt** [comment]
I'd say use what you are good at.

Elasticsearch has less experience, but there are users on it now. We will
likely need to revisit it soon to make it possible to be REST-only
https://github.com/openzipkin/zipkin/pull/1261

We are in the process of reworking the cassandra model, too (for cassandra
3.9+) https://github.com/openzipkin/zipkin/pull/1252

In the next months, we'll do more dilligence benchmarking both
elasticsearch and cassandra, but we don't expect either to be a bad choice.
