### ISSUE TITLE
Get rid of zipkin3_udts keyspace

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1276]
zipkin3_udts keyspace is needed because the current version of the datastax driver requires that UDT annotated classes have the same namespace as the annotation. The following solutions work:
- get rid of UDT classes and just read the UDT fields directly
- get rid of annotation parsing and write UDT codecs
- raise an issue on the datastax driver to allow configuration overrides when parsing annotations

**Comment by bamb00** [comment]
Hi,
How is the zipkin3_udts keyspace gets created? from java/python code.  I want to automate creating a keyspace in cassandra for zipkin opentracing when the zipkin is deployed.  

Thanks.

**Comment by codefromthecrypt** [comment]
when a zipkin server is started, it will by default create the schema
associated with UDTs on first usage. This is done programmatically in java.

https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/cassandra3/src/main/java/zipkin/storage/cassandra3/DefaultSessionFactory.java#L86

**Comment by bamb00** [comment]
Is there another way I can create a keyspace for zipkin when the the openkin/zipkin pod is deployed?
Thanks for responding.

**Comment by codefromthecrypt** [comment]
not saying you'll love this option, but you can bring up the zipkin server,
hit its health check, then bring it down.

ex. localhost:9411/health

^^ will create the keyspace and the whole thing won't take too long
(seconds)

**Comment by codefromthecrypt** [comment]
cc @openzipkin/cassandra for other opinions on eagerly creating cassandra3 keyspace w/o java

**Comment by jorgheymans** [comment]
@adriancole will the transition to DataStax driver 4.0 change anything here ?

**Comment by codefromthecrypt** [comment]
dunno. will look into it!
