### ISSUE TITLE
UI: Sort order is lost when going back to start screen

### ISSUE THREAD

**Issue by rogeralsing** [openzipkin/zipkin#1279]
If you sort by newest first, and then open up a trace and then go back to the start screen, the sort order is lost, making it somewhat confusing if you are trying to pinpoint a specific trace.

**Comment by jpiechowka** [comment]
@adriancole @rogeralsing That would be a nice improvement to the UI if the sorting method would persist.

**Comment by codefromthecrypt** [comment]
adding help-wanted as I would like this, too, but don't know how to make it happen.

**Comment by eirslett** [comment]
We should add ?sortOrder=something to the URL (replaceHistory) and then have the crossroads router read that param when it delegates to the views. Somebody would have to send a PR for it.

**Comment by joel-airspring** [comment]
I've created a first pass on this feature.  Any feedback on what I did?

I did it in two commits since there were a few plumbing changes needed to make the feature possible.  The two commits can be combined, though, if that is preferable.

**Comment by codefromthecrypt** [comment]
@joel-airspring thx.. for laziness it is easier to review code on a pull request than clicking on commits. Can you raise a PR with those 2?

**Comment by joel-airspring** [comment]
PR #1543
