### ISSUE TITLE
Cassandra storage: service_name_index and service_span_name_index tables are not getting populated.

### ISSUE THREAD

**Issue by sachinpkale** [openzipkin/zipkin#1316]
I am trying out Zipkin on a Clojure project with Cassandra as storage backend. But traces are not being displayed as `service_name_index` and `service_span_name_index` tables are empty. If I use default in-memory database, traces are shown correctly. Facing the same issue on both versions of cassandra 2.7.2 and 3.X. What would be the problem here?

**Comment by sachinpkale** [comment]
I ran Zipkin with `--logging.level.com.datastax.driver.core.QueryLogger=trace` and insert queries for `service_name_index` and `service_span_name_index` did not appear. 
The instrumentation library I am using is old one and does not send `span.timestamp` and `duration`. Could that be the reason?

**Comment by codefromthecrypt** [comment]
we'll need the json for the spans that work in the in-mem, but not in cassandra. can you paste that?

**Comment by codefromthecrypt** [comment]
ps @guilespi @aliceliang @strongh if any of you are interested in continuing work on clj-zipkin, let us know. for example, we've moved some language specific repositories into the openzipkin or so others can help maintain them. would be nice to keep the fire burning.

**Comment by sachinpkale** [comment]
I have thrift serialized data that `clj-zipkin` is sending to scribe.

`#ns525700959.Span{:trace_id 10339031, :name Renderer, :id 9887479, :parent_id 3778525, :annotations (#ns_1186963580.Annotation{:timestamp 1475082174174000, :value end:Renderer, :host #ns1048748842.Endpoint{:ipv4 3232243969, :port 0, :service_name RendererService}, :duration 0} #ns_1186963580.Annotation{:timestamp 1475082174071000, :value start:Renderer, :host #ns1048748842.Endpoint{:ipv4 3232243969, :port 0, :service_name RendererService}, :duration 0}), :binary_annotations [], :debug 0}
`

I tried to get JSON by running Zipkin jar in DEBUG mode but could not collect it. Any way to capture it?

**Comment by sachinpkale** [comment]
@adriancole Got the json by following your comment in Gitter channel.
`
[
  {
    "traceId": "0000000000043ece",
    "id": "00000000005245a2",
    "name": ":get:/",
    "timestamp": 1475082087593000,
    "duration": 919000,
    "annotations": [
      {
        "timestamp": 1475082087593000,
        "value": "start::get:/",
        "endpoint": {
          "serviceName": "testservice"
        }
      },
      {
        "timestamp": 1475082088512000,
        "value": "end::get:/",
        "endpoint": {
          "serviceName": "testservice"
        }
      }
    ],
    "debug": true
  },
  {
    "traceId": "0000000000043ece",
    "id": "0000000000db87ad",
    "name": "renderer",
    "parentId": "00000000005245a2",
    "timestamp": 1475082088097000,
    "duration": 105000,
    "annotations": [
      {
        "timestamp": 1475082088097000,
        "value": "start:Renderer",
        "endpoint": {
          "serviceName": "rendererservice"
        }
      },
      {
        "timestamp": 1475082088202000,
        "value": "end:Renderer",
        "endpoint": {
          "serviceName": "rendererservice"
        }
      }
    ],
    "debug": true
  }
]
`

**Comment by codefromthecrypt** [comment]
ps the ip is very invalid.. that's why it isn't showing up in the json

**Comment by sachinpkale** [comment]
ip32 overflows beyond `127.255.255.255`. I was testing on my machine with intranet IP address `192.168.XXX.XXX`. That's why I changed it to ip64.

**Comment by codefromthecrypt** [comment]
raised this to help get you along
https://github.com/sachinpkale/clj-zipkin/pull/1

**Comment by sachinpkale** [comment]
Thanks for these changes. Much useful. I made few corrections to it and added it to separate branch. Spans are being stored in Cassandra successfully.

**Comment by codefromthecrypt** [comment]
whoo hoo!
