### ISSUE TITLE
noop storage

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1317]
With noop storage, we can help users rate the throughput of the span transport independent of the storage layer. this is important for those trying to size their backends or adjust tuning of things like kafka. unlike mem, this would drop spans on the floor, so could be run continuously without blowing up.

if other names than noop are better.. ex blackhole.. lemme know!

cc @dan-tr

**Comment by codefromthecrypt** [comment]
this storage type should also help people answer the question @dan-tr asked about

> Can anyone offer any guidance on the number and type of servers to use to run Zipkin-Server? We are expecting roughly 10,000 spans per second in our production enviornment?

**Comment by schlosna** [comment]
This might be a separate request, but one item I haven't had a chance to look into would be exposing something along the lines of a span predicate filter that would allow dropping spans based on specific logic -- say drop spans with duration less than 1 millisecond, or in noop case drop everything.

**Comment by codefromthecrypt** [comment]
> This might be a separate request, but one item I haven't had a chance to
> look into would be exposing something along the lines of a span predicate
> filter that would allow dropping spans based on specific logic -- say drop
> spans with duration less than 1 millisecond, or in noop case drop
> everything.
> 
> yeah worth calling out separately, I think. in that issue, we'd have to
> discuss the impact which is partial trace data. this has historically been
> troublesome in collectors and why they consistently drop based on trace id
> vs content of one span in a trace.

on the other hand.. you raise a very interesting point! if we set
collection sample rate to zero, we have effectively noop storage :P

**Comment by codefromthecrypt** [comment]
`COLLECTOR_SAMPLE_RATE=0.0` is essentially noop storage and requires no effort!
