### ISSUE TITLE
Circle build failures after moving to C* 3.9

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1322]
After switching to cassandra 3.9 we are over memory limits, and the CircleCI build has started to fail.

We probably need to set some arguments in circle.yml to try and reduce the memory used by c*. I don't expect our tests to need much memory. There's also a few other processes which might be possible to trim down via JAVA_OPTS or similar.

> Your build has exceeded the memory limit of 4G on 1 container. The results of this build are likely invalid. We have taken a snapshot of the memory usage at the time, which you can find in a build artifact named `memory-usage.txt`. The RSS column in this file shows the amount of memory used by each process, measured in kilobytes.

cc @abesto @michaelsembwever

**Comment by codefromthecrypt** [comment]
ps travis remains slow, but doesn't break on account of memory. I think it has larger VMs

**Comment by abesto** [comment]
Ooooh, OOM, my second best friend! I'll look into this over the weekend.

**Comment by codefromthecrypt** [comment]
:) thanks for your service to a friend

**Comment by michaelsembwever** [comment]
:+1:

**Comment by abesto** [comment]
Green build: https://circleci.com/gh/openzipkin/zipkin/267

Methinks we can close, +1?
