### ISSUE TITLE
Dynamically bound lookback for elasticsearch queries

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1327]
Currently, we have a heck of a long disclaimer in our code to defend against too many indexes being queried. When the lookback hits over 100 index entries (days), we reroute the search to a post request.

``` java
  /**
   * Because the {@link HttpClient} is forced to send the index names in the URL, too many indices
   * (or long names) can quickly exceed the 4096-byte limit commonly imposed on a single HTTP line.
   * This limit is not entirely within the control of Elasticsearch, either, as it may be imposed by
   * arbitrary HTTP-speaking middleware along the request's route. Some more details can be found on
   * this "wontfix" issue: https://github.com/elastic/elasticsearch/issues/7298
   */
  private static final int MAX_INDICES = 100;
```

Apart from dependency links, Zipkin data is usually only retained for orders of days, certainly not hundred days. The reason why this hack was needed is that our unit tests tests by default lookback to epoch. The server looks back to `zipkin.query.lookback` which is 7 days by default, but due to modularity, this property isn't readable by tests.

Except for the test cases, the only way we'd ever need 100 days of data returned is if someone adjusted `zipkin.query.lookback` to an order of magnitude higher than its default (or if someone was using the library directly).

One way or another, we should put a hard-limit on how far back we should look as certainly getting data from 1970 will return null. The storage schema wasn't even written until mid-march of 2016.

My suggestion is the following:
- Hard limit the begin timestamp to no later than when zipkin's elasticsearch was written, March 2016.
- Lookup the indexes dynamically and hard-limit queries to not attempt to read before them

Anyone have feelings about this? @openzipkin/elasticsearch 

```
$ curl -s 'localhost:9200/test_zipkin_http-*/_settings?pretty'
{
  "test_zipkin_http-2016-10-04" : {
    "settings" : {
      "index" : {
        "number_of_shards" : "5",
        "creation_date" : "1475553054979",
        "requests" : {
          "cache" : {
            "enable" : "true"
          }
        },
        "analysis" : {
          "analyzer" : {
            "lowercase" : {
              "filter" : [ "lowercase" ],
              "type" : "custom",
              "tokenizer" : "keyword"
            }
          }
        },
        "number_of_replicas" : "1",
        "uuid" : "_RCZiBM2TUiLbyLge5Yl_Q",
        "version" : {
          "created" : "2040099"
        }
      }
    }
  }
}
```

**Comment by dan-tr** [comment]
@adriancole Is there a reason Zipkin can't use a wildcard in the index name to just query across all zipkin indexes: 
`zipkin-*`

https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

**Comment by codefromthecrypt** [comment]
we do in fallback case, but in general, we only search the indexes that are
relevant to the query. My guess is that the more indexes we search, the
more expensive the query, and that there isn't anything more expensive than
zipkin-*

**Comment by shakuzen** [comment]
> My suggestion is the following:
> - Hard limit the begin timestamp to no later than when zipkin's elasticsearch was written, March 2016.
> - Lookup the indexes dynamically and hard-limit queries to not attempt to read before them

These both sound reasonable to me.

**Comment by codefromthecrypt** [comment]
@dan-tr so this is used to implement timestamp and lookback. Ex. we don't want to ask elasticsearch to scan more indexes than needed. For example, if people don't setup a job to purge old data, a wildcard zipkin-\* would search indexes every document ever sent, even if the api request was for the last few days.

I noticed one way we could compress this is using partial wildcards. For example, instead of literally sending `2016-01-01, 2016-01-02 ..  2016-04-01, 2016-04-02`, we could send  `2016-01-*, 2016-01-*, 2016-03-*, 2016-04-01, 2016-04-02`. In the example given, of spans this year up to april 2nd, it would reduce the date expressions sent from over a hundred to 5. I'll open an issue for this
