### ISSUE TITLE
http://twitter.github.com/zipkin not found

### ISSUE THREAD

**Issue by chengweiv5** [openzipkin/zipkin#1337]
[The Wiki](https://github.com/openzipkin/zipkin/wiki) of this project says the documents can be found at http://twitter.github.com/zipkin

> Documentation
> 
> See http://twitter.github.com/zipkin

But in fact, it's 404 at http://twitter.github.com/zipkin

**Comment by eirslett** [comment]
Thanks for finding that one! It's an old link from back when Twitter hosted the Zipkin project.
This is the updated link: http://zipkin.io/
