### ISSUE TITLE
zipkin deploy document

### ISSUE THREAD

**Issue by gcnote** [openzipkin/zipkin#1348]
How can I find zipkin deploy document in a distributed system ?

I do't know how to deploy zipkin in my distributed system, because I can't find the detail deploy documentation about this , and github pages doesn't have much as well.

**Comment by eirslett** [comment]
You just `java -jar zipkin.jar`, if you have Java installed on the server. Or you can `docker run -d -p 9411:9411 openzipkin/zipkin` if you use Docker. That is all you have to do.

For running Cassandra (or MySQL, or Elasticsearch) there is a lot of documentation other places on the Internet.

Every company has its own way of deploying software to their servers, so it's not generally possible to make more detailed documentation than that.

If you have more detailed questions, you can ask in Zipkin's gitter chat channel, people are usually very helpful there!
