### ISSUE TITLE
Annotations with endpoint port larger than 32767 fails

### ISSUE THREAD

**Issue by nollbit** [openzipkin/zipkin#1350]
Endpoint ports are cast to a short leading to query errors for ports larger than 32767.

This is a bug I guess? Or am I missing something?

```
result.port((short) reader.nextInt());
```

https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/ZipkinAdapters.java#L154

**Comment by codefromthecrypt** [comment]
The Endpoint class (and similar) originally used fields with the same size as the thrift structs. The size of port is i16, yet there's no unsigned 16bit field in java. So, a high port will overflow and be read as signed (negative) unless you do something like this: `int port = endpoint.port & 0xffff`

In hindsight, and with the codecs we have now (especially considering json is often used as thrift), we might just prefer the java type being an int and bounding it to only 16 unsigned bits. However, this would be a significant api break, so not likely worth it by itself.

**Comment by nollbit** [comment]
Thank you.

However; spans reported for an endpoint where the port is larger than what a signed short can hold leads to query errors? There's an exception when the endpoint is unpacked from JSON.

I can't see that being fixed, so I guess this bug should perhaps still be open?

https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/ZipkinAdapters.java#L154 

`port()` asserts port being > 0 https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin/Endpoint.java#L159-L163

which leads to the exception which actually also breaks the UI completely, no error message.

**Comment by codefromthecrypt** [comment]
if there's a bug, we should indeed fix it! I'll look at that one you mentioned

**Comment by codefromthecrypt** [comment]
thanks for the help. I think I got stuck on the word "query error" earlier and didn't realize how clearly you pointed to the code bug https://github.com/openzipkin/zipkin/pull/1358

**Comment by nollbit** [comment]
No worries at all, thanks for the speedy fix!
