### ISSUE TITLE
Document configuration for http logging

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1355]
@mjbryant asked about this and @shakuzen was listening :)

Basically, we should document how to do spring boot access logging for those who want to use log analysis as opposed to metrics to tell who's using the zipkin UI or api

**Comment by shakuzen** [comment]
http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-configure-accesslogs

**Comment by jorgheymans** [comment]
Is log analysis still a thing now ? What about the perf overhead of dumping access logs on a busy zipkin instance, should we recommend doing this at all ? Otherwise we can close this issue, it has not come up since IIRC. @adriancole @shakuzen

**Comment by codefromthecrypt** [comment]
no thumbs up in 4 years seems like a close to me. We can always re-open or point people to prometheus.

**Comment by jorgheymans** [comment]
:musical_score: Another one bites the dust :musical_note:

**Comment by jcchavezs** [comment]
There should be a Freddie Mercury emoji.
