### ISSUE TITLE
Why use mysql storage，app still use a lot of memory，Xmx=1g got OutOfMemoryError

### ISSUE THREAD

**Issue by Dreampie** [openzipkin/zipkin#1365]
```
Exception in thread "ZipkinMySQLStorage-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

https://github.com/spring-cloud/spring-cloud-sleuth/issues/430#event-838109259

**Comment by codefromthecrypt** [comment]
issues like this are somewhat hard for us to help you with. that error says that the process is running garbage collection too much. This doesn't necessarily mean the thread reported is the cause of the garbage. You can also simply increase your heap size as an interim measure.

https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/memleaks002.html

In general, you'd need to investigate what was in the heap when such a thing occurred and use a heap dump or profiling tool to identify what's going on. It may or may not be related to the data retrieved by MySQL.

If you find something that we can take action on, then go ahead and open a case at that point (or ask to re-open this one).
