### ISSUE TITLE
How to configure the UI to connect to zipkin server deployed separately

### ISSUE THREAD

**Issue by altfatterz** [openzipkin/zipkin#1369]
I saw people were using this:

```
java -jar lib/zipkin-web-all.jar -zipkin.web.port=:9412 -zipkin.web.rootUrl=/ zipkin.web.query.dest=localhost:9411
```

But according to this https://github.com/openzipkin/zipkin/issues/1121 the `zipkin-web` is deprecated. 

I am using the `zipkin-autoconfigure-ui` wrapped into a spring boot app running on port 9412

Looking into https://github.com/openzipkin/zipkin/tree/master/zipkin-server#environment-variables I couldn't configure it to connect to separate zipkin server.

What am I missing?

**Comment by codefromthecrypt** [comment]
Hi, zoltan.

zipkin-ui's purpose is to allow someone to "add" the ui to a customized
zipkin-server process. It isn't a replacement for zipkin-web.

We aren't supporting the zipkin web (proxy) use case anymore, though we
have made an example you can look at.

https://github.com/openzipkin/docker-zipkin/tree/master/zipkin-ui

**Comment by altfatterz** [comment]
understand. thanks Adrian
