### ISSUE TITLE
When using AWS Elasticsearch 1.5 storage operations silently fail

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1375]
We only support 2.x, but amazon defaults to start 1.5 clusters. When these are in use, zipkin starts properly, but storage operations simply don't work (ex. no errors but storage ops return nothing). It might be worthwhile to parse elasticsearch versions and fail fast on unsupported cluster versions.

**Comment by jorgheymans** [comment]
Version check is failing fast now: https://github.com/openzipkin/zipkin/blob/28c98c4cbad33db187f6606754359376ebe60406/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/VersionSpecificTemplates.java#L191
