### ISSUE TITLE
Zipkin UI executes html tags contained in span name list

### ISSUE THREAD

**Issue by devinsba** [openzipkin/zipkin#1382]
We have instrumentation on an internet facing app. This obviously results in a few odd requests as people poke around trying to break in.

Apparently we had someone send a request with a http method of `<script>alert(document.domain)</script>`

This got passed to the zipkin UI as is and then the JS executes. Obviously this is a less than ideal span name and we could/should sanitize it on our side, I feel this should also be addressed on the UI side though

**Comment by codefromthecrypt** [comment]
agreed. we already take care to sanitize json
