### ISSUE TITLE
Zipkin/Sleuth not working in PCF

### ISSUE THREAD

**Issue by DivakarGadey** [openzipkin/zipkin#1384]
The Implementation of Sleuth/Zipkin is working for app in local but after deploying to PCF , it is not working .

 Zipkin UI is not showing the our application instead it is showing **application** in the drop down and traces are also coming separately i.e. it is not showing the dependency between client and server .

Even the sleuth loggers are also not coming properly , the trace id is not coming as the same for both webservices.

But in local it is working perfectly with the spring boot server.

**Comment by codefromthecrypt** [comment]
I don't expect the outcome of this issue to end up with a change to this
repo. Usually it is better to start exploratory troubleshooting with an
issue closer to the repo that you are using (or even better start with
https://gitter.im/openzipkin/zipkin). For example, it is unclear what your
deployment consists of.. ex is it an unmodified zipkin-server, or something
else? what's the storage type? what's the version?

if unsure, paste the output of the following

curl -s your_zipkin_host:9411/info|jq .

curl -s your_zipkin_host:9411/health|jq .

Also, the drop-down behavior sounds like different applications are in use
as the zipkin deployment shouldn't impact what the applications report. You
could grab an example trace to get to the bottom of this.

**Comment by codefromthecrypt** [comment]
wondering if there's something about the version you are using? just noticing more formal support of PCF making its way into the codebase https://twitter.com/making/status/800708459041722368

feel free to open again if after bumping latest or otherwise, you are able to give more feedback on this
