### ISSUE TITLE
Zipkin server does not work with MySQL 5.7

### ISSUE THREAD

**Issue by ajacques** [openzipkin/zipkin#1387]
### Technical Details
MySQL Server Version ```5.7.14-8 - Percona Server (GPL), Release '8', Revision '1f84ccd'```
Zipkin Server: ```1.14.3``` 

MySQL SQL Mode: ```ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION``` (Default for Percona distributed by Docker containers)

### Summary
Running Zipkin with ```STORAGE_TYPE=mysql``` causes certain requests to fail with exceptions due to semantically invalid SQL queries. This is caused by SQL_MODE=ONLY_FULL_GROUP_BY.

As per the [MySQL 5.7 release notes](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by), "[...] the default SQL mode includes ONLY_FULL_GROUP_BY. [...]"

#### Exhibit A
```
11/3/2016 10:00:56 PMorg.mariadb.jdbc.internal.util.dao.QueryException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'Zipkin.zipkin_spans.start_ts' which is not in SELECT list; this is incompatible with DISTINCT
11/3/2016 10:00:56 PMQuery is : select distinct `zipkin_spans`.`trace_id` from `zipkin_spans` join `zipkin_annotations` on (`zipkin_spans`.`trace_id` = `zipkin_annotations`.`trace_id` and `zipkin_spans`.`id` = `zipkin_annotations`.`span_id`) where (`zipkin_spans`.`start_ts` between 1478232055406000 and 1478235655406000 and `zipkin_annotations`.`endpoint_service_name` = 'front-end-ui') order by `zipkin_spans`.`start_ts` desc limit 10
11/3/2016 10:00:56 PM	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:939) ~[mariadb-java-client-1.4.6.jar!/:na]
[...]
11/3/2016 10:00:56 PM	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:312) ~[jooq-3.8.4.jar!/:na]
11/3/2016 10:00:56 PM	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:393) ~[jooq-3.8.4.jar!/:na]
11/3/2016 10:00:56 PM	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2748) ~[jooq-3.8.4.jar!/:na]
11/3/2016 10:00:56 PM	at zipkin.storage.mysql.MySQLSpanStore.getTraces(MySQLSpanStore.java:168) ~[zipkin-storage-mysql-1.14.3.jar!/:na]
11/3/2016 10:00:56 PM	at zipkin.storage.mysql.MySQLSpanStore.getTraces(MySQLSpanStore.java:242) ~[zipkin-storage-mysql-1.14.3.jar!/:na]
11/3/2016 10:00:56 PM	at zipkin.server.ZipkinQueryApiV1.getTraces(ZipkinQueryApiV1.java:105) ~[classes/:na]
[...]
```

#### Exhibit B
```
Exception in thread "main" java.sql.SQLSyntaxErrorException: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'Zipkin.a.endpoint_service_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
11/3/2016 10:00:03 PMQuery is : SELECT * FROM (select distinct s.trace_id, s.parent_id, s.id, a.a_key, a.endpoint_service_name from zipkin_spans s left outer join zipkin_annotations a on   (s.trace_id = a.trace_id and s.id = a.span_id and a.a_key in ('ca', 'cs', 'sr', 'sa')) where s.start_ts between 1478217600000000 and 1478303999999999 group by s.trace_id, s.id, a.a_key) as link_spans WHERE 1=0
11/3/2016 10:00:03 PM	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
[...]
11/3/2016 10:00:03 PM	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
11/3/2016 10:00:03 PM	at zipkin.dependencies.mysql.MySQLDependenciesJob.run(MySQLDependenciesJob.java:186)
11/3/2016 10:00:03 PM	at zipkin.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:41)
```

### More Information
This exception is caused by the ORDER BY predicate ordering along a column that's not included in the SELECT part of the query.

This query is bad because Zipkin attempts to order along start_ts, but does not include it in the SELECT:
```
select distinct `zipkin_spans`.`trace_id` from `zipkin_spans` [...] order by `zipkin_spans`.`start_ts`
```

I did not see any other cases of queries that used selectDistinct() and orderBy() on an incorrect SQL column, but I did see another example of this issue in zipkin-dependencies (see Exhibit B.)

### Discussion
In the case of Exhibit A, I looked at the source code to try to understand if I could fix the issue and submit a PR. The order by is a bit strange, which TS does it order by when there's multiple records for a given trace id? MAX/MIN?

One solution would be:
```
select `zipkin_spans`.`trace_id`, MAX(`zipkin_spans`.`start_ts`) [...] group by `zipkin_spans`.`trace_id` order by MAX(`zipkin_spans`.`start_ts`) desc limit 10
```
This should be semantically similar to the previous query while explicitly encoding the ordering intent.

Thoughts?

**Comment by codefromthecrypt** [comment]
The current configuration for 5.7+ is noted in the readme.

# If using MySQL 5.7, you'll need to disable ONLY_FULL_GROUP_BY

$ mysql -uroot -e "SET GLOBAL sql_mode=(SELECT
REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))"

https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/mysql#applying-the-schema

There's also another way, which is to empty out sql mode like this;
https://github.com/fabric8io/kubernetes-zipkin/commit/454f5b1ad86bcaa1e8749fcfa2a716c25e0f21bd

A PR would be welcome to address this without configuration, just make sure
that the tests pass.

ex MYSQL_USER=root ./mvnw clean install -p zipkin-storage/mysql --am

**Comment by ajacques** [comment]
Unfortunately those workarounds aren't really an option for me and I believe a better solution would be resolve the ambiguity in the query to ensure that intent is properly represented in the query.

I took the liberty of creating a pull request based on my current understanding of the problem space. See #1390.
