### ISSUE TITLE
how can i deploy zipkin-server cluster for performance?

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1408]
in my production env, i only deploy one zipkin-server

i think this zipkin-server collect trace from kafka, and send trace es, and show zipkin-web.
if i have lots of services produce trace info to kafka, i think maybe only one zipkin-server to consume the trace info speed less than producer
can i deploy some `zipkin-server`s to raise consumer's performance?

if my kafka's zipkin topic has 9 partition, i start up three zipkin-server, and one zipkin-server consume three partiton, and finally only one zipkin-server to show zipkin's web ui? 

what zipkin-server's param i need to set, and how to deploy the zipkin-server cluster?  

thanks very much!

**Comment by codefromthecrypt** [comment]
duplicate of #1159 please take a look there and comment as needed!
