### ISSUE TITLE
only one es hosts?

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1420]
i config es hosts is ```ES_HOSTS=http://10.215.242.15:9200, http://10.215.242.16:9200, http://10.215.242.17:9200, http://10.215.242.18:9200```
and zipkin'ui say ```ERROR: cannot load span names: Only a single hostname is supported [http://10.215.242.15:9200, http://10.215.242.16:9200, http://10.215.242.17:9200, http://10.215.242.18:9200]```
so i can only set one host?

**Comment by codefromthecrypt** [comment]
Thanks for opening the issue! This is a bit of a known issue. I assume you
cannot create a DNS A record set for those IPs?

**Comment by dragontree101** [comment]
yes we cannot create dns to these ips, so i only choose one ip,  i think maybe this way not very well.

**Comment by codefromthecrypt** [comment]
as long as you are treating the same as if they were in an A record set, we
can accommodate this.

**Comment by dragontree101** [comment]
ok thanks

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1422
