### ISSUE TITLE
How to trace MQ and asyn call  when use zipkin

### ISSUE THREAD

**Issue by lijunyong** [openzipkin/zipkin#1428]

**Comment by codefromthecrypt** [comment]
some are using a messaging span approach discussed here https://github.com/openzipkin/zipkin/issues/1243

**Comment by ghost** [comment]
Looking for this feature eagerly....

Or could someone leave us a hint how to integrate with rabbitmq (RabbitTemplate) ?

**Comment by codefromthecrypt** [comment]
you can try something like we have in kafka, except rabbit has message properties. This means you can inject/extra the trace ID from headers instead of the kafka key.

https://gist.github.com/adriancole/76d94054b77e3be338bd75424ca8ba30

Check with spring-cloud-sleuth (if you are using that) or brave for related functionality (raise an issue if one doesn't exist)

**Comment by ghost** [comment]
Thanks for the hint. 

We're trying to add tracing ability to a traditional project, neither spring-cloud nor 
 spring-boot.

I'll digest the one-way propogration. It makes me feel strange that only few information can be found for the integration of zipkin(brave) and mq.

**Comment by codefromthecrypt** [comment]
>
>  It makes me feel strange that only few information can be found for the
> integration of zipkin(brave) and mq.
>
Not strange, just we don't develop features until they are requested is
all. If you look at the issues there has been no-one requesting rabbit
before you (at least not here). There *have* been a lot of folks asking in
general on zipkin, and that's how the one-way span thing came to be.

Anyway, if you need a hand, feel free to hop on
https://gitter.im/openzipkin/zipkin If others end up interested in this, it
could become a feature.

**Comment by ghost** [comment]
Thanks very much.

**Comment by codefromthecrypt** [comment]
if you can chat then join https://gitter.im/openzipkin/zipkin otherwise,
you can do stackoverflow and I'll look out for it

**Comment by ghost** [comment]
Thanks. So kind of you.

Problem sovled yesterday.
