### ISSUE TITLE
Deprecated trace headers

### ISSUE THREAD

**Issue by sankarbalu** [openzipkin/zipkin#1430]
I have a simple zipkin server with the following pom. This worked well for a while. 

From this week, i am seeing the following warning log message in a loop that is filling up my log files that prevents from starting the server. I am not sure why, because to my knowledge no changes were done to the code or config. 
'2016-12-09 12:06:41.402  WARN [zipkin-server,b48ab054e4dd157c,c75ad2801a23120c,true] [zipkin-server,,,true] 8924 --- [sleuth.sleuth-1] o.s.c.s.z.s.ConvertToZipkinSpanList      : Message tracing cycle detected for: org.springframework.cloud.sleuth.stream.Spans@48848018
2016-12-09 12:06:41.403  WARN [zipkin-server,,,] [zipkin-server,,,] 8924 --- [sleuth.sleuth-1] o.s.c.s.i.m.MessagingSpanExtractor       : Deprecated trace headers detected. Please upgrade Sleuth to 1.1 or start sending headers present in the TraceMessageHeaders class' 

As per the PR (https://github.com/spring-cloud/spring-cloud-sleuth/pull/335/files), 1.0.4 version of sleuth dependencies should work. I verified the versions that come with Brixton.SR4 and it happened to be '1.0.4.RELEASE' for spring-cloud-sleuth-core and spring-cloud-sleuth-stream. I also tried to update the cloud dependencies version to 'Camden.RELEASE', that updated the sleuth dependency versions to ''1.0.9.RELEASE', but the problem persists. 

Any pointers on how to resolve this issue? 

**Original POM:**
      <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.0.RELEASE</version>
        <relativePath/> 
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Brixton.SR4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
  	<dependencies>
     <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
        </dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
    </dependencies>

**Comment by codefromthecrypt** [comment]
This issue was moved to spring-cloud/spring-cloud-sleuth#467
