### ISSUE TITLE
I have a problem about dependency and tree in zipkin UI

### ISSUE THREAD

**Issue by lijunyong** [openzipkin/zipkin#1439]
I have get rest and mq span,then report the span to zipkin,but it's not show dependency in zipkin UI and show tree no serviceName

![image](https://cloud.githubusercontent.com/assets/14291793/21251364/4d7f985c-c388-11e6-9c5b-48bb340d3535.png)

```
[
	{
		"traceId": "633871a0ff544636",
		"id": "633871a0ff544636",
		"name": "get",
		"timestamp": 1481860404941000,
		"duration": 143838,
		"annotations": [
			{
				"timestamp": 1481860404941000,
				"value": "sr",
				"endpoint": {
					"serviceName": "service2",
					"ipv4": "172.16.15.122"
				}
			}, {
				"timestamp": 1481860405084838,
				"value": "ss",
				"endpoint": {
					"serviceName": "service2",
					"ipv4": "172.16.15.122"
				}
			}
		],
		"binaryAnnotations": [
			{
				"key": "http.status_code",
				"value": "200",
				"endpoint": {
					"serviceName": "service2",
					"ipv4": "172.16.15.122"
				}
			}, {
				"key": "http.url",
				"value": "/foo",
				"endpoint": {
					"serviceName": "service2",
					"ipv4": "172.16.15.122"
				}
			}
		]
	}, {
		"traceId": "633871a0ff544636",
		"id": "b204e6cdd4bc2b3a",
		"name": "get",
		"parentId": "633871a0ff544636",
		"timestamp": 1481860405045000,
		"duration": 123456,
		"annotations": [
			{
				"timestamp": 1481860405045000,
				"value": "ms",
				"endpoint": {
					"serviceName": "mq",
					"ipv4": "0.0.0.127"
				}
			}
		],
		"binaryAnnotations": [
			{
				"key": "mq",
				"value": "send message",
				"endpoint": {
					"serviceName": "mq",
					"ipv4": "0.0.0.127"
				}
			}
		]
	}
]
```

**Comment by codefromthecrypt** [comment]
"ms" would have the endpoint of the local process, not the remote broker
(unless you've somehow implemented the broker
The messaging address("ma") will look exactly the same as how we handle the
server address ("sa")

"binaryAnnotations": [
			{
				"key": "ma",
				"value": true,
				"endpoint": {
					"serviceName": "mq",
					"ipv4": "127.0.0.1"
				}
			}
		]


there has been no code for messaging span, yet. so please only
experiment with annotations how they are described in the below pull
request, but don't depend on it or expect any server changes until
they are merged. https://github.com/openzipkin/zipkin-api/pull/24

**Comment by lijunyong** [comment]
@adriancole Thank you,I will change the annotations,but why is black the serviceName in zipkin UI

**Comment by codefromthecrypt** [comment]
the UI interprets certain annotations. best to start with the correct
usage, then if it is a still problem, ping back (don't expect the messaging
ones to turn out right since the UI doesn't know about that yet)

**Comment by lijunyong** [comment]
Thank you,what's the time to support 'ms','ma','mr' in zipkin UI

**Comment by codefromthecrypt** [comment]
>
> Thank you,when support 'ms','ma','mr' in zipkin UI
>
the pull request about those annotations has some discussion on it. We
shouldn't add UI until ppl are cool. Once it is merged, it would be very
easy to add to UI. (like days)

**Comment by lijunyong** [comment]
@adriancole thank you very much, very nice

**Comment by codefromthecrypt** [comment]
if you use the "cs" "sr" practice of one-way spans, the UI should work properly, now. Here's an example https://github.com/openzipkin/brave/tree/master/brave/src/test/java/brave/features/async

I don't expect us to continue with "ms" "mr"
