### ISSUE TITLE
releasing off a branch

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1444]
At some point, we will move to zipkin 2.0. That would imply making a maintenance branch 1.x

I don't know what might break when we do that, but it is probably safe to assume stuff is optimized for releasing from master. Let's make sure that we can release from another branch before we move our version to 2.

**Comment by codefromthecrypt** [comment]
cc @openzipkin/devops-tooling there's no schedule for 2.x, which is good because that means no immediate time pressure for this. That said, it will become needed probably within a month or two.

**Comment by abesto** [comment]
Now that we're well past the 2.x release, do we need / do you expect we'll need multi-track releases?

**Comment by codefromthecrypt** [comment]
I think I've done 2 manual releases off a branch. They will come
infrequently, when we have code we don't routinely maintain. Ex in the core
zipkin repo we are actually still publishing the old code as eventhough the
version is 2, the old libaries are still being maintained (this actually
has caused some issues due to overlapping artifact name, so sometime this
year we should stop that, but still there's work left to port everything to
the v2 api)

summary.. the use case will exist infrequently, and while I'm ok with doing
it manually not sure others would enjoy the lookup old credential, copy
paste or not.

**Comment by jorgheymans** [comment]
If branch releases become a frequent thing (and at least in this issue nobody thinks it will) tooling will emerge.
