### ISSUE TITLE
can't collect and query at the same time

### ISSUE THREAD

**Issue by rush24** [openzipkin/zipkin#1449]
I use the **elasticsearch** to store and **kafka** to collect
while the zipkin is collecting kafka msgs, and it did realy store in the cluster of elasticsearch, and search something is also quickly with elasticsearch's http-query-api, but it can't be query with zipkin UI or API at the same time.
once i stop collecting kafka msgs, zipkin query can work.
i think is it because of the collecting too busy cause zipkin can't handle the query request?
because when i run on my desktop, with all the same config, but just a little data to put in it,and it work normal, that can collect and query at the same time 

**here is my config**:
`
STORAGE_TYPE=elasticsearch,ES_HOSTS="http://host1:9200,http://host2:9200,http://host3:9200,http://host4:9200",KAFKA_STREAMS=6,KAFKA_ZOOKEEPER="host1:port,host2:port,host3,host4:port:port/kafkacluster",KAFKA_TOPIC="halo.msg.trace",KAFKA_MAX_MESSAGE_SIZE="200000000",KAFKA_GROUP_ID="new-zipkin",SELF_TRACING_ENABLED="false"
`

**Comment by codefromthecrypt** [comment]
so the relationship between the two would be the http client (which
accesses the storage layer). there is a connection limit per host

**Comment by rush24** [comment]
so is there anything i could do to solve it ? before changing the storage to ES, we have been using the cassandra, and the speed of putting data is more faster, but had not that problem.

**Comment by codefromthecrypt** [comment]
so right now.. here are the defaults

private int maxRequests = 64; // max requests in flight across all host/ips
private int maxRequestsPerHost = 5;  // max requests in flight per host/ip

We need to adjust this in a way that isn't too much effort. I wonder
what the normal elasticsearch defaults are

**Comment by codefromthecrypt** [comment]
@openzipkin/elasticsearch anybody have a preferred max in-flight? I think elasticsearch itself is 200

**Comment by rush24** [comment]
thank you very much!
so if i understand it, you want to change that two values to solve it?

**Comment by codefromthecrypt** [comment]
so I'm at the moment guessing that this is the issue. We don't have a stat
for this, but it is the only reasonable explanation. One way is we can
expose both. Another way is that we expose the max for all hosts and then
divide. preferences?

**Comment by rush24** [comment]
i can't find that two param, would you please tell me about it. then i can have a test see if that could work

**Comment by codefromthecrypt** [comment]
the parameter doesn't exist, yet. one minute...

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1450 are you able to make a
one-off build? or do you need to download a premade one?

**Comment by rush24** [comment]
premade thanks~

**Comment by codefromthecrypt** [comment]
in about 10-15 minutes there will be a new exec jar here.

http://oss.jfrog.org/oss-snapshot-local/io/zipkin/java/zipkin-server/1.18.1-SNAPSHOT/

Try default (which would now allow full 64 in-flight requests at a time),
and then you can adjust up or down with ES_MAX_REQUESTS

Please report back as soon as you can, in case this isn't the problem.
