### ISSUE TITLE
Simplify documentation for first time users

### ISSUE THREAD

**Issue by franklinhu** [openzipkin/zipkin#145]
- Set Finagle `sampleRate` to 1
- Set collector sample rate to 1
- Make collector sample rate a top level config option

**Comment by johanoskarsson** [comment]
From the mailing list discussion we should also update the readme and configs to describe how to set up a minimally useful Zipkin cluster. Without using Scribe for transport (direct to collector) and without ZooKeeper for ServerSet and sample rate.

**Comment by eirslett** [comment]
This should be fairly well documented by now.
