### ISSUE TITLE
malformed base64 in the zipkin ui

### ISSUE THREAD

**Issue by raam86** [openzipkin/zipkin#1455]
I am using `"htrace-core4" % "4.1.0-incubating"` with  `"htrace-zipkin" % "4.1.0-incubating"` I am getting malformed base64 strings in the frontend, specifically seems like `/` has been converted to `_`. Looking into htrace the spans seems to be sent correctly. Any tips would be appreciated.

**Comment by codefromthecrypt** [comment]
I'm guessing you are using scribe as opposed to kafka? Do you have a scribe
setup or are using that because htrace doesn't yet support http?

**Comment by codefromthecrypt** [comment]
My guess is that this has to do with url encoding. Can you patch htrace to
use encodeBase64URLSafeString instead of encodeBase64String?

**Comment by raam86** [comment]
Thanks for the quick reply, I am using scribe, I will check and see if it helps.

**Comment by raam86** [comment]
After further investigation the problem seems to lie in htrace.
