### ISSUE TITLE
zipkin ui very slow when has a lot of span

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/zipkin#1460]
we are trace is very big, and have a lot of spans, 
so zipkin's ui very slow when i choose span name or into some big trace.

i use zipkin 1.16 and use es store?  

does have any way to speed ui's performance?

**Comment by codefromthecrypt** [comment]
>
> we are trace is very big, and have a lot of spans,
>
define big? spans are typically no more than 1KiB in size (often far less
than that, like hundreds of bytes)

> so zipkin's ui very slow when i choose span name or into some big trace.
>
can you show a profile from Chrome debug tools?

> i use zipkin 1.16 and use es store?
>
ok

> does have any way to speed ui's performance?
>
probably, but we'd need to try and understand what we are optimizing for.

**Comment by dragontree101** [comment]
sorry i am not describe clearly
one of a trace is
![image](https://cloud.githubusercontent.com/assets/1763935/21535618/90af6a92-cdb2-11e6-83ca-e766e5cbfb53.png)

and chrome debug, i found get data from zipkin-server is fast
![image](https://cloud.githubusercontent.com/assets/1763935/21535711/c2a44d96-cdb3-11e6-8a7a-5181859c43b2.png)

and from chrome timeline i found scripting is slow, a lot of time use to execute this script
![image](https://cloud.githubusercontent.com/assets/1763935/21535760/9bb3cb70-cdb4-11e6-8f67-c2c3d6a8261a.png)

i guess exec jquery js is slow, i don't know this could be optimize?

**Comment by codefromthecrypt** [comment]
yeah I think this could be optimized. @cburroughs are you interested in cracking knuckles on some performance work?

**Comment by dragontree101** [comment]
i deploy by myself, not use docker, 
do you mean update zipkin to 1.18 or only update zipkin-ui from http://search.maven.org/#artifactdetails%7Cio.zipkin.ui%7Czipkin-ui%7C0.0.1%7Cjar ?

**Comment by adriancole** [comment]
@dragontree101 yeah you could temporarily change the zipkin-ui jar

**Comment by dragontree101** [comment]
how to change zipkin-ui?  

i change 
```
<dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>zipkin-autoconfigure-ui</artifactId>
      <optional>true</optional>
    </dependency>
```
to
```
<dependency>
    <groupId>io.zipkin.ui</groupId>
    <artifactId>zipkin-ui</artifactId>
    <version>0.0.1</version>
</dependency>
```
in zipkin-server/pom.xml

i use fatjar  and use mvn clean package in zipkin-server.

**Comment by adriancole** [comment]
here's what you want..

```
    <!-- Static content for the web UI -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>zipkin-autoconfigure-ui</artifactId>
      <optional>true</optional>
      <exclusions>
        <exclusion>
          <groupId>${project.groupId}</groupId>
          <artifactId>zipkin-ui</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.zipkin.ui</groupId>
      <artifactId>zipkin-ui</artifactId>
      <version>0.0.1</version>
    </dependency>
```

**Comment by dragontree101** [comment]
ok， i am try this new ui.  thanks

**Comment by dragontree101** [comment]
my zipkin-server is 1.16 and change zipkin-ui in 0.0.1
i use new zipkin-ui, but has error, i need change some ui-config?

i use config is
```
environment=
  KAFKA_ZOOKEEPER="10.215.242.11,10.215.242.12,10.215.242.13:2181/kafka-offline",
  STORAGE_TYPE="elasticsearch",
  SELF_TRACING_ENABLED="true",
  ES_CLUSTER="prod",
  ES_HOSTS="http://10.215.242.15:9200",
  ES_PIPELINE="zipkin",
  KAFKA_STREAMS="4",
  QUERY_PORT="8080"
```

![image](https://cloud.githubusercontent.com/assets/1763935/21539261/22132b2c-cde0-11e6-8217-41b6937a6b4b.png)

**Comment by adriancole** [comment]
@dragontree101 I'm moving the discussion about the new UI into https://github.com/openzipkin/zipkin-ui/issues/25 and cleaning up the comments here. There's still a performance issue in the code we have today, and this issue shoud focus on that.

**Comment by dragontree101** [comment]
because of we have lots of data, service name  and span name all time out,  i remember store data in cassandra, have table only store service_name and span_name, but store in es, service_name and span_name get by es, so time is very long. 

![image](https://cloud.githubusercontent.com/assets/1763935/21561603/a7a8d63c-cea9-11e6-93b0-0ef800b1f7df.png)

**Comment by adriancole** [comment]
can you set SELF_TRACING_ENABLED=true (using elasticsearch-http) and see if
you can get a trace with this failure?

**Comment by dragontree101** [comment]
set `SELF_TRACING_ENABLED=true`  why can get trace?  

i think this failure because of i have huge data, i think self trace can not reduce my query data from server

i query `http://zipkin.xxxxx.net/api/v1/spans?serviceName=product`  can get 1m data from server and use 20s +

**Comment by adriancole** [comment]
self-trace would help tell you which query was slow. it would be better than guessing.. that or look at your server logs to see if you have a corresponding exception.

that said.. from the look of your console error, it looks like the SocketException may just be hiding a local problem.

**Comment by adriancole** [comment]
anyway thanks for the details. at the moment I can tell you that getting the UI to work with the magnitude you have probably will take investment of time. Similarly, there might be some work needed in the ES query. I think I can help with some of this next week, as I need to work on ES anyway.

In the mean time.. can you share a screen shot of your huge trace? I think it would be interesting to see how a trace that big looks in zipkin. It is an order of magnitude larger than what Twitter used to have.

**Comment by dragontree101** [comment]
i found i set SELF_TRACING_ENABLED="true" in environment

![image](https://cloud.githubusercontent.com/assets/1763935/21562108/a01478c0-ceb0-11e6-83fb-b25d98af937d.png)

**Comment by adriancole** [comment]
I'm moving comments about the separate issue about ES performance here https://github.com/openzipkin/zipkin/issues/1462

**Comment by cburroughs** [comment]
Could you give some details about the particular trace that is slow as a point of reference?  How many spans does it have?  Or how many KiB is the json?

**Comment by codefromthecrypt** [comment]
@cburroughs based on the screen shot.. looks like roughly 10k spans at a maximum depth of 7. dunno about the size of the json @dragontree101 ?

**Comment by ghost** [comment]
@adriancole we've also experienced issues where by a trace with over 3,000 spans ended up crashing the chrome instance we were using to view the zipkin UI. The UI was also pretty non perform-ant prior to the crash.

**Comment by codefromthecrypt** [comment]
The "10k span problem" was discussed at the most recent tracing workshop. We are not alone, for example even Google's UI doesn't render with thousands of spans per trace.

Here are some options
* aggregating the spans and putting in timing, possibly on the collection side.
  * basically adding a tag that says spans were dropped
* drop span and replace with annotation
  * have the UI code convert large amounts of spans into annotations before they are rendered
  * note large orders of annotations could also crash the UI so should be tested
* add a control to collapse parts of a trace that are too large
  * leave the span data alone, but collapse spans which have over a certain amount of children
* add a dependency graph per trace
  * when there are a lot of spans, a trace ID scoped dependency graph could be useful

**Comment by Logic-32** [comment]
Have you considered a slightly more optimized rendering technique?  I haven't profiled things myself but the places I'd start poking around are:
1. Mustache templates; are they slow to compile/render at that scale?
2. Lazy render; only add to the DOM what is visible and potentially start with things collapsed after a certain threshold.

Our use case, btw, is that we have a fairly involved data gathering/generation system that sometimes has to do a deep dive through various web services to get all of it's data.  We try to identify repeated requests and consolidate them into bulk requests (in code, not zipkin) to alleviate this issue but we still have it on occasion.

One of our biggest improvements in this area was to break up traces so that the typical "large traces" now link to "child traces" so that you can see at the high level how long things took or navigate off to another trace to see detail for a particular section.

**Comment by yurishkuro** [comment]
Tip: we were able to scale Jaeger UI to 50k spans by using a viewport technique.

**Comment by codefromthecrypt** [comment]
Thanks for the tips, folks. I don't think many have mentioned concrete
ways to improve UI performance. Lucky for us though
@igorwwwwwwwwwwwwwwwwwwww has been active in related performance work
and who knows... might be able to carry this forward.

The most concrete way to improve the UI is available, capable hands.
We don't have fulltime UI staff, so appreciate volunteers who offer
advice or take time to fix things. Thank you.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
In order to reproduce the issue it would be helpful to get a gist with a JSON blob of the trace, that can be POSTed against zipkin.

**Comment by codefromthecrypt** [comment]
@igorwwwwwwwwwwwwwwwwwwww don't have a prebaked utility to make large traces, but this lua script could probably be modified to do so.. https://github.com/openzipkin/zipkin/issues/1226#issuecomment-346745547

**Comment by Logic-32** [comment]
@igorwwwwwwwwwwwwwwwwwwww, I have a trace with 9k spans in it that can probably be used for your purposes (with the aid of #1884).  Is there a "private" way I can send it to you?  Nothing super-confidential in it but enough I don't want it to be public.  Or did @adriancole's lua script fit your need?

Edit: sent the trace :)

**Comment by codefromthecrypt** [comment]
not sure this will change anything but next zipkin release will update jquery lib and we should retry https://github.com/openzipkin/zipkin/pull/1954

**Comment by jorgheymans** [comment]
This issue relates to the classic Zipkin UI. Lens has seen many performance improvements since then. Having testing with 10k span traces myself, i see these loading in just in 7-8 seconds on my laptop. UX wise this can still be improved sure, but it's definitely a major improvement over classic UI.

If you're considering posting similar issues against Lens, please provide us with an anonymized version of your slow loading trace so we can benchmark and profile it.
