### ISSUE TITLE
Elasticsearch http slow on getting span names when there's a lot of data

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1462]
from @dragontree101

because of we have lots of data, service name  and span name all time out,  i remember store data in cassandra, have table only store service_name and span_name, but store in es, service_name and span_name get by es, so time is very long. 

![image](https://cloud.githubusercontent.com/assets/1763935/21561603/a7a8d63c-cea9-11e6-93b0-0ef800b1f7df.png)

and chrome console have

![image](https://cloud.githubusercontent.com/assets/1763935/21561714/5254d35a-ceab-11e6-8fa2-caf5158fc269.png)

i found i set SELF_TRACING_ENABLED="true" in environment

![image](https://cloud.githubusercontent.com/assets/1763935/21562108/a01478c0-ceb0-11e6-83fb-b25d98af937d.png)

and yestoday's es index is 
```
health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   zipkin-2016-12-29               2_uXTThATbyoJ7khnXbo4g   5   1  609199726            0      140gb           70gb
```

**Comment by codefromthecrypt** [comment]
Currently, the query for service names looks at all indexes (it also sorts which is redundant). So, it probably affects more than just today's data.

**Comment by codefromthecrypt** [comment]
@openzipkin/elasticsearch I'm suspicious of using catch-all for service and span names. On one hand we want to make sure data is readable, but on the other hand do you think we need to search all indexes for service and span names? what if we cut-off at a particular date?

**Comment by mansu** [comment]
@adriancole While cutting off after a certain date is a good idea I think a better alternative is to add a mechanism to cache the service and span names in the persistent layer. That way we can run an expensive query periodically and cache accurate data instead of returning incomplete data every time.  The current model of relying on HTTP caching is too expensive when a lot of users use the zipkin UI and is not scalable(for us) in the long run. Loading span and service names is the slowest part in our UI and currently it takes 10-15 seconds before the UI is usable. We are currently sampling 1/3 the expected rate but once we sample at the expected rate, the UI will take even longer to load.

**Comment by codefromthecrypt** [comment]
elasticsearch caching is enabled by default by our schema. Have you looked
into this and perhaps what it would take to better tune the service and
span name cache (or at least see if it is or isn't working)?

https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html

Ideally, we can find a solution that works well at ES level since not
everyone shares libraries to access it.

**Comment by mansu** [comment]
Thanks. Will look into this and let you know.

**Comment by sammypbaird** [comment]
@mansu, we are experiencing the same behavior, taking 30 seconds to load the service names on Zipkin UI. We implemented the suggestion @adriancole  had to only load the last 2 days of indexes (which does improve performance considerably), but we'd prefer a solution similar to yours with caching. Did you get a chance to implement something like this?

**Comment by mansu** [comment]
@sammypbaird I didn't get a chance to look into this yet. Just curious, how much perf improvement did you see when you just scanned 2 days worth of indices?

**Comment by sammypbaird** [comment]
I haven't deployed it on production yet, but on our development cluster (6 servers in a cluster), loading span names went from taking 2 seconds down to 600 ms. I'll tell you once we get the changes out to our production cluster (which has a lot more traffic) what the impact is.

**Comment by codefromthecrypt** [comment]
notes from gitter

@tramchamploo 
> https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-search-speed.html
nested can make queries several times slower and parent-child relations can make queries hundreds of times slower. So if the same questions can be answered without joins by denormalizing documents, significant speedups can be expected.
...
I think that’s suggesting flatting the span structure would be fine.

**Comment by codefromthecrypt** [comment]
@sammypbaird @mansu without more drastic measures such as indexing service names manually or flattening the span's data structure... we could parameterize the "lookback" of service/span names, changing it from forever to one or two days?

**Comment by sammypbaird** [comment]
I think that would be a useful option to set. I would definitely use it (all our services get hit at least once a day, so there's no need to go back further). Thanks!

I have already changed the code locally to insert the service name at the root level, allowing us to write much simpler queries in Kibana and visualizations, and seems to also help speed up the Zipkin queries a bit.

**Comment by codefromthecrypt** [comment]
@sammypbaird incidentally, I was also thinking about a "special field" for indexing service names. Note it would have to be more than one (terms vs a term query to cover client+server spans), but I still think ES would optimize it much better than current nested queries. That said, the follow-up span names query might remain a problem if unbounded.

**Comment by sammypbaird** [comment]
@mansu, I finally got my change to limit the indices it searches to the last two days out to production. Loading the serviceNames went from ~30 seconds down to ~8 seconds. I'm still looking for improvements based off assumptions we can make on our data, but that helped considerably.

We also hope to make some hardware changes to have our elasticsearch cluster writing to SSDs instead of HDDs, which is what we currently have.

**Comment by mansu** [comment]
@sammypbaird This is great to hear. We will push the fix to our prod and report back as well. While this is a great improvement, ~8 seconds is still way above sub-second interactive speeds. Also, please let us know if you can come up with any more improvements.

**Comment by sammypbaird** [comment]
And for context, we are saving about 80 GB of data to elasticsearch a day. I'm not sure what is typical for these type of systems.

**Comment by tramchamploo** [comment]
I still think we should persist service and span names in storage layer. I doubt if there is really much we can do to optimize ES.

**Comment by codefromthecrypt** [comment]
ok, so there's two paths to take.

there's an obvious quick win by limiting the lookback on service names. I think that should be done as it has zero schema implications.

on optimizing other parts, remember that if we optimize for a separate doc etc for service name caching, we end up with a big "if statement" in the codebase, which is tech debt that might last quite a while. For example, the query syntax for old data and new data will be different, and in some cases you may be querying across both.

**Comment by codefromthecrypt** [comment]
@sammypbaird here's one thing I think we can do which should be easy and introduces no new variables.

We already have a variable `QUERY_LOOKBACK`, which controls the default amount of data one searches for. We could reuse this in elasticsearch, for service names, which would default to 24hrs back (usually 2 days because ES indexes are midnight based). So, by default, ES service names would only query 2 days (today and yesterday). Someone can extend that by affecting `QUERY_LOOKBACK` variable.

```
  @Autowired
  @Value("${zipkin.query.lookback:86400000}")
  int defaultLookback = 86400000; // 1 day in millis
```

If you agree, this would be a simple change and not increase tech debt we'd have to revert when addressing the topic more fundamentally.

**Comment by sammypbaird** [comment]
That sounds great. The only reason I chose 2 days for the indices was to not have a small sample early in the morning - 24 hours should address this. I'm not sure however how overloading this variable will impact the current system. What does it currently control and how is it currently used? As long as it doesn't restrict some other part of the system, I'm happy with that idea. I would also want it  to limit the indices for the spanName lookup too (which is also unbounded right now to all indices).

**Comment by codefromthecrypt** [comment]
Currently it is used when someone makes an api call to get traces (but
leave off the lookback parameter). No worries on reusing for span names.

**Comment by tramchamploo** [comment]
I'm trying to implement this, and `defaultLookback` goes a long way through `ZipkinElasticsearchHttpStorageProperties` -> `ZipkinElasticsearchHttpStorageAutoConfiguration` -> `ElasticsearchHttpStorage` -> `ElasticsearchHttpSpanStore`.  
Also in `ZipkinElasticsearchHttpStorageProperties`  there is 
```
  @Autowired
  @Value("${zipkin.query.lookback:86400000}")
  private int defaultLookback = 86400000; // 1 day in millis
```
any idea a better way to implement this?

**Comment by codefromthecrypt** [comment]
My plan would be to add a field to ElasticsearchHttpStorage.Buider of
namesLookback

In the autoconfiguration method, add a Value parameter which binds
zipkin.query.lookback to the parameter namesLookback and pass that to the
builder. In other words dont add it to a properties class. Instead use it
directly in the Bean method


On 10 Mar 2017 12:44, "tramchamploo" <notifications@github.com> wrote:

I'm trying to implement this, and defaultLookback goes a long way through
ZipkinElasticsearchHttpStorageProperties -> ZipkinElasticsearchHttpStorage
AutoConfiguration -> ElasticsearchHttpStorage -> ElasticsearchHttpSpanStore.
Also in ZipkinElasticsearchHttpStorageProperties there is

  @Autowired
  @Value("${zipkin.query.lookback:86400000}")
  private int defaultLookback = 86400000; // 1 day in millis

any idea a better way to implement this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/zipkin/issues/1462#issuecomment-285637183>,
or mute the thread

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1538

**Comment by codefromthecrypt** [comment]
ps not merging https://github.com/openzipkin/zipkin/pull/1538#discussion_r105528463 until someone weighs in on whether we should use QUERY_LOOKBACK, or introduce ES_NAMES_LOOKBACK instead. I'm ok with either, just noticing the work is roughly the same for either

**Comment by tramchamploo** [comment]
Just merge `limit-es-names`, seems the speed does not much improve. 100GB data every day with 12 hosts cluster, 64GB memory per host.

**Comment by codefromthecrypt** [comment]
Can you quantify "much" in terms of improvement and how far back your data
goes?

I think one thing lost is that this isnt a solution for those doing 100%
sampling. Sampling is still required as is watching the amount of data in
traces. This change will not "fix" this part, rather help bound the service
name lookup problem in general for those sampling.

**Comment by tramchamploo** [comment]
I save data for just one day, a service name query takes about more than 5 secs. After limitation I see a about 1s improvement or just nothing. Timeout sometimes happens.

**Comment by codefromthecrypt** [comment]
In your case i am surprised it makes any difference at all! The parameter
used limits the names query to lookback 1 day (which in your case is the
same as the amount of total data you have). I would expect no difference
since the data searched is the same.

you could try to change the lookback to something less than a day.. like an
hour? Just as an experiment.. again something more significant will likely
be needed in your case.

Thanks for reporting back.


On 15 Mar 2017 06:23, "tramchamploo" <notifications@github.com> wrote:

I save data for just one day, a service name query takes about more than 5
secs. After limitation I see a about 1s improvement or just nothing.
Timeout sometimes happens.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/zipkin/issues/1462#issuecomment-286637345>,
or mute the thread

**Comment by codefromthecrypt** [comment]
@sammypbaird are you able to test the outstanding PR? we should do a release for other reasons in the next day or two.

**Comment by sammypbaird** [comment]
@adriancole , I just pulled the code and tested. I verified that changing the query lookback does speed up the loading of serviceNames and spanNames. Thanks!

**Comment by StephenWithPH** [comment]
@sammypbaird and/or @adriancole... have either of you built a Docker image from this branch? I was hoping to do that yesterday, but ran into some problems following along Zipkin & Zipkin-Docker's container build process in order to get something I could test against.

Our live Zipkin is running in Docker (in Kubernetes), so I was hoping to do a side-by-side test atop the production Elasticsearch store so I could report results here.

If you have a Docker image, I'm happy to test. Either way, I'm glad to see that this looks like it will be merged and released soon.

**Comment by codefromthecrypt** [comment]
I'll merge as-is as we can always add an ES specific property later.

@StephenWithPH sorry we don't have a docker process for snapshots at the moment cc @openzipkin/devops-tooling in case someone is bored and wants to help make that happen :P
