### ISSUE TITLE
Unknown service in Zipkin UI when self tracing is enabled

### ISSUE THREAD

**Issue by llinder** [openzipkin/zipkin#1486]
Version 1.19.1 reports "unknown" as the service name when self tracing is enabled.  I haven't dug too deep but rolling back to 1.19.0 fixes the problem.

![image](https://cloud.githubusercontent.com/assets/99359/21943259/0bf1ee84-d996-11e6-8057-70cb4815862a.png)

**Comment by codefromthecrypt** [comment]
thanks, lance. will look into it.

**Comment by codefromthecrypt** [comment]
out in 1.19.2 (and 1 I think)
