### ISSUE TITLE
Storage/Cassandra (or cassandra3) port can't be specified

### ISSUE THREAD

**Issue by welovelain** [openzipkin/zipkin#1505]
I couldn't mention that in https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/resources/zipkin-server-shared.yml

there is no "port" parameter for connecting to cassandra/cassandra3 in "storage" section. By default it goes on 9042, but what if we want to specify another port?

**Comment by codefromthecrypt** [comment]
docs are misleading. the port can be specified like host:9999 (note all
contact points must have a consistent port).

mind raising a PR with a short note about this copied to..
-> the zipkin-shared.yml
-> the two places in zipkin-server/README where CASSANDRA_CONTACT_POINTS
are mentioned (cassandra and cassandra3)
-> the two CassandraStorage.Builder methods
