### ISSUE TITLE
Maven license plugin fails in travis

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1512]
After investigation, it appears that the maven license plugin is failing due to travis having incorrect dates on files.

Ex I added this into the .travis.yml
```
install:
  - date
  - git --version
  - git log -n 1 ./zipkin/src/test/java/zipkin/internal/DependencyLinkerTest.java
```

then the output for a file was this..

```
$ date
Thu Feb  2 04:13:46 UTC 2017
install.2
0.03s$ git --version
git version 2.11.0
install.3
0.02s$ git log -n 1 ./zipkin/src/test/java/zipkin/internal/DependencyLinkerTest.java
commit ffac4ff4eac53b82dea2f66179e3be920bfa6276
Author: Adrian Cole <adriancole@users.noreply.github.com>
Date:   Tue Jan 3 09:28:48 2017 +0800
```

you can see that it says the file was modified on Jan 3 this year..

however, it wasn't.. it was modified last year.

```bash
$ git log -n 1 ./zipkin/src/test/java/zipkin/internal/DependencyLinkerTest.java
commit 21fc32b965e70f0985a164f34ed89ae55e115a11
Author: Adrian Cole <adriancole@users.noreply.github.com>
Date:   Thu Oct 27 09:38:34 2016 +0800
```

There is a current travis issue which might be related https://www.traviscistatus.com/incidents/k79mjcv403c4

In the mean time, I'll try to disable the license plugin temporarily so that we can get a green build (and release code)

**Comment by codefromthecrypt** [comment]
thanks @shakuzen for the help thinking this through. We may want to consider moving off travis at some point, eventhough there's a bottleneck in circleci (max workers per org)

cc @openzipkin/devops-tooling @bsideup

**Comment by codefromthecrypt** [comment]
ps in case not clear, this does not impact our circleci pull request checkers in any way. license check works fine

**Comment by codefromthecrypt** [comment]
0a4ef9566459c06c9c6f705f076461462378693d 6a0d6e7a00ddcd0ff4cb73458adc708838f995c5 and a5a84ede544004d02546a5535f48c589d05ac280 can be reverted once whatever's going on in travis slaves is over

**Comment by bsideup** [comment]
@adriancole Travis is really nice when it comes to Docker testing; I wouldn't recommend to drop it entirely. 

I can't find any reported issue, so Travis team might not be aware of it.

**Comment by codefromthecrypt** [comment]
tweeted earlier, but recently just opened https://github.com/travis-ci/travis-ci/issues/7254 in case no-one else knows about this https://github.com/travis-ci/travis-ci/issues/7254

**Comment by codefromthecrypt** [comment]
I'm worried this might be something strange about git or github. this popped up in circleci just now (but only my pull request, not the one from @devinsba)

https://circleci.com/gh/openzipkin/zipkin/681?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Comment by codefromthecrypt** [comment]
note. this is still popping up on circleci builds from master. This is leading me to believe this isn't travis specific, but perhaps something in common between the circle and travis builds

https://circleci.com/gh/openzipkin/zipkin/703

cc @openzipkin/devops-tooling

**Comment by abesto** [comment]
Oooh, juicy!  Random idea: migrate to http://www.mojohaus.org/license-maven-plugin/?

**Comment by pavolloffay** [comment]
I have posted a possible solution here: https://github.com/travis-ci/travis-ci/issues/7254#issuecomment-387689631. copying here as this issue is the first in google search

**Comment by codefromthecrypt** [comment]
I'd suggest we do both suggestions..

Update to a license plugin not abandoned 3 years ago, as suggested by @abesto 

http://www.mojohaus.org/license-maven-plugin/

Add some stuff into our .travis.yml as suggested by @pavolloffay 
```yaml
git:
  # otherwise license plugin fails due to grafted commits
  # see https://github.com/travis-ci/travis-ci/issues/7254#issuecomment-387689631
  depth: false
```

When this happens, we should scrub all of the disabling things:
```bash
$ ag license.skip
RELEASE.md
90:./mvnw --batch-mode -s ./.settings.xml -Prelease -nsu -DreleaseVersion=$VERSION -Darguments="-DskipTests -Dlicense.skip=true" release:prepare  -DpushChanges=false

zipkin-server/README.md
559:$ ./mvnw -Dlicense.skip=true -DskipTests --also-make -pl zipkin-server clean install

travis/publish.sh
171:  MYSQL_USER=root ./mvnw verify -nsu -Dlicense.skip=true -DskipActuator
181:  ./mvnw --batch-mode -s ./.settings.xml -Prelease -nsu -DskipTests -Dlicense.skip=true deploy
195:  ./mvnw --batch-mode -s ./.settings.xml -Prelease -nsu -DreleaseVersion="$(release_version)" -Darguments="-DskipTests -Dlicense.skip=true" release:prepare
```

Any volunteers?

**Comment by anuraaga** [comment]
Looked at the more modern plugin a while ago and noticed it didn't have integration with git like the current one does here

https://github.com/openzipkin/zipkin/blob/2862853ba2ff4d7370410bb2ee5c88b436fb508c/pom.xml#L610

But want to confirm, do we need integration with it? I guess git updated time or the file's mtime will be same in any realistic case. It's a strange point that removing the integration does have a good chance of making our current plugin work well too... But probably still worth moving to the modern one if it sounds ok.

**Comment by codefromthecrypt** [comment]
I didnt notice the lack of feature parity when suggesting the more
maintained one. this is news to me (possibly I missed a comment)

maybe we try with just the travis changes then?
