### ISSUE TITLE
Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'

### ISSUE THREAD

**Issue by bamb00** [openzipkin/zipkin#1514]
I believe the CASSANDRA_CONTACT_POINTS was pick up for the two nodes in bold below.  Then the exceptions occurs.

TYPE_STORAGE=cassandra3

{"log":"\u0009at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.6.jar!/:8.5.6]\n","stream":"stdout","time":"2017-02-02T23:24:49.656222275Z"}
{"log":"\u0009at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]\n","stream":"stdout","time":"2017-02-02T23:24:49.656225242Z"}
{"log":"\n","stream":"stdout","time":"2017-02-02T23:24:49.656228036Z"}
{"log":"2017-02-02 23:25:09.088  INFO 8 --- [nio-9411-exec-2] com.datastax.driver.core.ClockFactory    : Using native clock to generate timestamps.\n","stream":"stdout","time":"2017-02-02T23:25:09.088947978Z"}
{"log":"2017-02-02 23:25:09.153  INFO 8 --- [nio-9411-exec-2] c.d.d.c.p.DCAwareRoundRobinPolicy        : Using provided data-center name 'DC1' for DCAwareRoundRobinPolicy\n","stream":"stdout","time":"2017-02-02T23:25:09.153756486Z"}
{"log":"2017-02-02 23:25:09.153  INFO 8 --- [nio-9411-exec-2] com.datastax.driver.core.Cluster         : **New Cassandra host /10.32.0.6:9042** added\n","stream":"stdout","time":"2017-02-02T23:25:09.153877727Z"}
{"log":"2017-02-02 23:25:09.153  INFO 8 --- [nio-9411-exec-2] com.datastax.driver.core.Cluster         : **New Cassandra host /10.44.0.0:9042** added\n","stream":"stdout","time":"2017-02-02T23:25:09.153900463Z"}
{"log":"2017-02-02 23:25:09.173  INFO 8 --- [nio-9411-exec-2] zipkin.storage.cassandra3.Schema         : Installing schema /cassandra3-schema.cql\n","stream":"stdout","time":"2017-02-02T23:25:09.173983754Z"}
{"log":"2017-02-02 23:25:11.405  WARN 8 --- [nio-9411-exec-2] zipkin.server.ZipkinHttpCollector        : **Cannot store spans [4b1b98177fe3e1ff.79fc78f356634f6d\u003c:4b1b98177fe3e1ff, 4b1b98177fe3e1ff.4b1b98177fe3e1ff\u003c:4b1b98177fe3e1ff] due to InvalidC
onfigurationInQueryException(Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy')**\n","stream":"stdout","time":"2017-02-02T23:25:11.405902301Z"}
{"log":"\n","stream":"stdout","time":"2017-02-02T23:25:11.40593312Z"}
{"log":"com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'\n","stream":"stdout","time":"2017-02-02T23:25:11.405937886Z"}
{"log":"\u0009at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:37) ~[cassandra-driver-core-3.1.3.jar!/:na]\n","stream":"stdout","time":"2017-02-02T23:25:11.405941742Z"}
{"log":"\u0009at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:27) ~[cassandra-driver-core-3.1.3.jar!/:na]\n","stream":"stdout","time":"2017-02-02T23:25:11.40594501Z"}
{"log":"\u0009at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) ~[cassandra-driver-core-3.1.3.jar!/:na]\n","stream":"stdout","time":"2017-02-02T23:25:11.40594853Z"}
{"log":"\u0009at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245) ~[cassandra-driver-core-3.1.3.jar!/:na]\n","stream":"stdout","time":"2017-02-02T23:25:11.40595193Z"}
{"log":"\u0009at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68) ~[cassandra-driver-core-3.1.3.jar!/:na]\n","stream":"stdout","time":"2017-02-02T23:25:11.405955017Z"}
{"log":"\u0009at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43) ~[cassandra-driver-core-3.1.3.jar!/:na]\n","stream":"stdout","time":"2017-02-02T23:25:11.405958109Z"}
{"log":"\u0009at zipkin.storage.cassandra3.Schema.applyCqlFile(Schema.java:108) ~[zipkin-storage-cassandra3-1.20.0.jar!/:na]\n","stream":"stdout","time":"2017-02-02T23:25:11.405961425Z"}
{"log":"\u0009at zipkin.storage.cassandra3.Schema.ensureExists(Schema.java:96) ~[zipkin-storage-cassandra3-1.20.0.jar!/:na]\n","stream":"stdout","time":"2017-02-02T23:25:11.405964312Z"}

**Comment by codefromthecrypt** [comment]
Sorry you are having trouble.

the "cassandra3
<https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/cassandra3#storage-cassandra3>"
storage type requires minimally version 3.9+ (which includes
TimeWindowCompactionStrategy
<https://issues.apache.org/jira/browse/CASSANDRA-9666>)

Maybe you can verify by using cqlsh against one of your nodes and run "show
version
<http://stackoverflow.com/questions/31502442/check-cql-version-with-cassandra-and-cqlsh>
"

The "cassandra
<https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/cassandra#storage-cassandra>"
storage type still exists and doesn't use that compaction strategy, but
requires minimum cassandra 2.2

You can test zipkin's cassandra3 support against cassandra 3.9 via our
example docker files <https://github.com/openzipkin/docker-zipkin#cassandra>

docker-compose -f docker-compose.yml -f docker-compose-cassandra.yml up

hope this helps

**Comment by codefromthecrypt** [comment]
in the future, please use gitter stackoverflow or zipkin-user google group for troubleshooting. As mentioned in the issue template, issues are for changes to the project
