### ISSUE TITLE
Cleanup modules

### ISSUE THREAD

**Issue by franklinhu** [openzipkin/zipkin#152]
Currently we have a confusing hierarchy of modules for the collector and query services including:
- `zipkin-common`: common classes shared between the two
- `zipkin-thrift`: Thrift structs and interfaces for both services
- `zipkin-scrooge`: module to generate Scala from Thrift via Scrooge
- `zipkin-scribe`: scribe specific classes for collector, including the service
- `zipkin-server`: combination of code for collector and query, including the query service

I think we can clean this up by breaking up the latter two modules and make things more composable.
- `zipkin-cassie`: implementation of `Aggregates`, `Index`, and `Storage` interfaces that use Cassandra as the backing store
- `zipkin-collector-core`: core code for the collector service
- `zipkin-collector-scribe`: scribe specific classes
- `zipkin-collector-service`: module to compose everything together
- `zipkin-query-core`: core code for query service
- `zipkin-query-service`: module to compose everything together

**Comment by mosesn** [comment]
Where will the Aggregates, Index, and Storage interfaces live?  Core?

**Comment by johanoskarsson** [comment]
Overall a good idea. Some feedback:
- I'd change zipkin-cassie to zipkin-cassandra so as not to tie it to the client used.
- We might get away without the -core modules for now, we will get tons of modules with this change.
- Make sure you clearly write up which module does what in the readme (or maybe even a readme per module)

**Comment by franklinhu** [comment]
@mosesn I've already moved them to zipkin-common so they can be shared across all the modules
