### ISSUE TITLE
How to use brave-opentracing API to let Zipkin to display Server Receive and Server Send?

### ISSUE THREAD

**Issue by tomgithub2016** [openzipkin/zipkin#1522]
In my project,I need to use （opentacing-api+brave-opentracing+Zipkin） to tracing.
 I use brave-opentracing API  start(),finish() to create Span and post ,But In Zipkin only to display Client Send and Client Receive datas ,do not display Server Receive and Server Send.

My questions is  How to use brave-opentracing API to let Zipkin to display Server Receive and  Server Send?

Demo,  There are two micro services,ServiceA and ServiceB
ServiceA  remote procedure call ServiceB，via brower to call ServiceA and ServiceA will  remote call serviceB，and ServiceA、ServiceB span finish();
But in zipkin,only to display Client Send and Client Receive,
In this demo, How to display  Server Receive and  Server Send by using brave-opentracing API ?

In ServiceA code
```
@RequestMapping("ServiceA")
	public String serviceA() throws InterruptedException, IOException
	{
		//BraveTracer  
		//root span
 		Span span0 = tracer.buildSpan("ServiceA").start();
		Map<String, String> map = new HashMap<String, String>();
		tracer.inject(span0.context(), Format.Builtin.HTTP_HEADERS, new TextMapInjectAdapter(map));
 		//build HttpHeader
		HttpHeaders header = new HttpHeaders();
		header.setAll(map);
		//remote invoke
 		String rs = restTemplate.postForEntity("http://localhost:9393/ServiceB", new HttpEntity(header), String.class)
				.getBody();
 		//post
 		span0.finish();
 		return "";
	}
```

In ServiceB code

```

	@RequestMapping("ServiceB")
	public String serviceB() throws InterruptedException, IOException
	{
 
		Enumeration<String> e = request.getHeaderNames();
		Map<String, String> spanMap = new HashMap<String, String>();
 
		while (e.hasMoreElements())
		{
			// add the names of the request headers into the spanMap  
			String key = e.nextElement();
			String value = request.getHeader(key);
			spanMap.put(key, value);
 		}
		Span span1 = tracer.buildSpan("ServiceB")
				.asChildOf(tracer.extract(Format.Builtin.HTTP_HEADERS, new TextMapExtractAdapter(spanMap))).start();
		
		
		//demo doSomethings
		Thread.sleep(3000);

		//ServiceB post
 		span1.finish();

		return "test";
	} 
```

**Comment by codefromthecrypt** [comment]
please don't copy/paste post issues to multiple repos. The first one you made was in the right spot

https://github.com/openzipkin/brave-opentracing/issues/18

**Comment by tomgithub2016** [comment]
ok。
