### ISSUE TITLE
Feature Request Elastic Search Authentication

### ISSUE THREAD

**Issue by owenhaynes** [openzipkin/zipkin#1525]
Feature request to allow to use authenticated elastic search clusters. Unable to use Zipkin with Elastic cloud as requires basic auth. 

Have tried using

ES_HOSTS=HTTPS://user:pass@elasticcloud.url

Had a quick browse of the source code and do not see any way to set username and password.

**Comment by codefromthecrypt** [comment]
most typically, user and password are configured separately in our storage apis.

If basic auth is the norm in elasticsearch, please add a link.

cc @openzipkin/elasticsearch in case others are using different schemes (I know AWS is different)

**Comment by owenhaynes** [comment]
Basic authentication is one way they also support transport auth.

https://github.com/elastic/found-shield-example/blob/master/src/main/java/org/elasticsearch/cloud/transport/example/TransportExample.java

Going to hack this into a local copy for the time being, untill I get time
to learn Java again.

As from a quick look I don't know the best way to implement this yet.

**Comment by codefromthecrypt** [comment]
implementation would be like this, except mapped to properties..
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Authenticate.java

pausing on impl just to let others speak up

**Comment by mansu** [comment]
HTTP auth into ES would should work. However, we need to make sure that this approach doesn't interfere with ES hosted on AWS.

**Comment by StephenWithPH** [comment]
We also need this feature. We're considering implementing it... with a PR to follow. Here's the **rough** draft sketch:

- add additional [zipkin.storage.elasticsearch](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-autoconfigure/storage-elasticsearch-http/src/main/java/zipkin/autoconfigure/storage/elasticsearch/http/ZipkinElasticsearchHttpStorageProperties.java#L22) properties for username and password (plaintext throughout)
- propagate these properties to [ElasticsearchHttpStorage](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/ElasticsearchHttpStorage.java#L52)
- via [asyncSpanStore](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/ElasticsearchHttpStorage.java#L203), propagate properties to [ElasticsearchHttpSpanStore](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/ElasticsearchHttpSpanStore.java#L51), and from there to [SearchCallFactory](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/internal/client/SearchCallFactory.java#L31)
- at this time, memoize them using [okhttp3.Credentials](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Authenticate.java#L39)
- update [newCall](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/internal/client/SearchCallFactory.java#L38) to pass (previously memoized) authorization headers on **every request** which should take care of anything originating from ElasticsearchHttpSpanStore.
- via [asyncSpanConsumer](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/ElasticsearchHttpStorage.java#L209), propagate the original properties to [ElasticsearchHttpSpanConsumer](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/ElasticsearchHttpSpanConsumer.java#L31) and memoize them as before
- during every call to [accept](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/ElasticsearchHttpSpanConsumer.java#L42) pass the memoized credentials to [HttpBulkIndexer](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/HttpBulkIndexer.java#L80) where they'll be used as a header on **every request**
- take care of all the similar things for [EnsureIndexTemplate](https://github.com/openzipkin/zipkin/blob/release-1.21.0/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/EnsureIndexTemplate.java)


Comments:
- we're adding authorization headers to every request per https://www.elastic.co/guide/en/x-pack/current/http-clients.html
- for $reasons, our implementation of Zipkin only _reads_ data from Elasticsearch; with all of the above, we're somewhat confident on the reading path; we appreciate more scrutiny on the _writing_ path
- we're not using AWS-hosted Elasticsearch, so we appreciate more scrutiny on this as well
- we're purposefully addressing only elasticsearch-http; we feel this is much better than dealing with embedded or transport nodes. From other discussions in this repo, that feels consistent with the Zipkin roadmap.


Given all of the above, does this path seem reasonable? Before we start work, we'd like to make sure this is something we can ultimately contribute back.

EDIT: add cc @openzipkin/elasticsearch

**Comment by codefromthecrypt** [comment]
I'd prefer a much tighter scope change, in line with how aws works.. Make authentication an http-layer concern, which is already possible via interceptor. Doing this removes all impact from the base code.

This would be like so..

1. Add username and password properties to ZipkinElasticsearchHttpStorageProperties, documented as being for basic authentication per the url.

2. make ZipkinElasticsearchHttpStorageAutoConfiguration.basicAuth which is similar to awsSignatureVersion4 in the aws configuration class. This should be conditional on the 
username and password properties being set. the resulting interceptor should be a normal okhttp authentication one. Make sure it is tested

3. update the yaml and readme with a shortcut env name of the env properties. 

sg?

**Comment by StephenWithPH** [comment]
Sounds great. We're in motion on this. Back soon(ish) for feedback.

**Comment by StephenWithPH** [comment]
@adriancole see #1548 from @NithinMadhavanpillai. Comments?

**Comment by codefromthecrypt** [comment]
yep. made some! mostly there thanks!

**Comment by lmpeiris** [comment]
Just needed to know how to use basic http auth on zipkin docker compose or helm chart. Are these parameters already available; i can't see them any documentation or examples.

**Comment by codefromthecrypt** [comment]
doc was missing in the helm chart https://github.com/openzipkin/zipkin-helm/pull/20

for docker, it is the normal env style. here's an example of setting env https://github.com/openzipkin/zipkin/blob/master/docker/examples/docker-compose-elasticsearch.yml#L32

the variable are `ES_USERNAME` and `ES_PASSWORD` https://github.com/openzipkin/zipkin/tree/master/zipkin-server#elasticsearch-storage
