### ISSUE TITLE
Duration filter does not work for Cassandra storage

### ISSUE THREAD

**Issue by pauldraper** [openzipkin/zipkin#1531]
The min duration filter does not work when using Cassandra storage.

**Comment by codefromthecrypt** [comment]
>
> The min duration filter does not work when using Cassandra storage.
>
The duration filter requires that spans are sent with duration set. Which
library is creating the spans? We have tracked some of them here:
https://github.com/openzipkin/openzipkin.github.io/issues/49

**Comment by pauldraper** [comment]
This works when I use in-memory store.

I tried this with the example data from the documentation (http://zipkin.io/pages/data_model.html) and had the same result with the cassandra store: no matter what the min duration, the trace still appeared.

**Comment by codefromthecrypt** [comment]
Sorry, I should have been more specific and the old readme should have been updated.

if you are using "cassandra" this won't work as the indexing scheme used for duration caused a lot of problems including excess load. "cassandra3" supports duration query

Ex. this from CassandraSpanStoreTest

```java
  @Test
  @Override
  public void getTraces_duration() {
    throw new AssumptionViolatedException("Upgrade to cassandra3 if you want duration queries");
  }
```

**Comment by codefromthecrypt** [comment]
updated readme 9f2004e
