### ISSUE TITLE
[UI] Non common annotations are way too much on the right.

### ISSUE THREAD

**Issue by ys** [openzipkin/zipkin#1541]
I have the following trace https://gist.github.com/ys/f02cf3a291b35b3f52aac8f88c990b08
It has a few custom annotations (`sidekiq.start` and sidekiq.end`)

The interesting part is:
```
"annotations": [
      {
        "timestamp": 1490202030779197,
        "value": "cs"
      },
      {
        "timestamp": 1490202030783701,
        "value": "sr"
      },
      {
        "timestamp": 1490202030783703,
        "value": "sidekiq.start"
      },
      {
        "timestamp": 1490202030975805,
        "value": "sidekiq.end"
      }
```

You can see that the timestamps between `sr` and `sidekiq.start` are super close.
The end is just a few 100ms away.

but the UI displays it wrong.

![image](https://cloud.githubusercontent.com/assets/483012/24211337/f9fc091e-0f2b-11e7-8e93-ff49d15dc280.png)

It lacks the annotations, I discovered I had to scroll a lot to the right.

```
<div class="duration" style="left: 1.7737048999724578%; width: 0.1%">
  8μ : sidekiq
  <div class="annotation core" style="left: 75%; width: 8px" title="Client Send" data-keys="endpoint,value,timestamp,relativeTime,serviceName" data-endpoint=" (client)" data-value="Client Send" data-timestamp="1490202030779197" data-relative-time="3.548ms" data-service-name="client"></div>
  <div class="annotation core" style="left: 56375%; width: 8px" title="Server Receive" data-keys="endpoint,value,timestamp,relativeTime,serviceName" data-endpoint=" (client)" data-value="Server Receive" data-timestamp="1490202030783701" data-relative-time="8.052ms" data-service-name="client"></div>
  <div class="annotation" style="left: 56400%; width: 8px" title="" data-keys="endpoint,value,timestamp,relativeTime,serviceName" data-endpoint="client" data-value="sidekiq.start" data-timestamp="1490202030783703" data-relative-time="8.054ms" data-service-name="client" data-original-title="sidekiq.start"></div>
  <div class="annotation" style="left: 2457675%; width: 8px" title="" data-keys="endpoint,value,timestamp,relativeTime,serviceName" data-endpoint="client" data-value="sidekiq.end" data-timestamp="1490202030975805" data-relative-time="200.156ms" data-service-name="client" data-original-title="sidekiq.end"></div>
</div>
```

This is the inline CSS, you can see that the `left` percentage there is totally off.

Unsure what the fix is but I guess it is in the javascript calculation.

**Comment by adriancole** [comment]
can you retry on latest? the build was a bit mucked up

**Comment by ys** [comment]
I am on `1.21` if that is the latest.

**Comment by adriancole** [comment]
sorry I was just working on zipkin-ui (a different repo) ignore my comment.

**Comment by adriancole** [comment]
killing irrelevant comments which I caused.

**Comment by codefromthecrypt** [comment]
@cburroughs @virtuald either of you bored? :)

**Comment by virtuald** [comment]
@adriancole sorry, got moved to another project, so haven't been using zipkin in a few months. I expect in a few months a different project will start that will need zipkin... we'll see what happens.

**Comment by ys** [comment]
@adriancole I can try to take a look. Am I correct seeing this broken or am I doing something wrong?

**Comment by codefromthecrypt** [comment]
One thing surprising in that span is that the client and server annotations
have the same endpoint.. was that a loopback?

On 24 Mar 2017 18:16, "Yannick Schutz" <notifications@github.com> wrote:

@adriancole <https://github.com/adriancole> I can try to take a look. Am I
correct seeing this broken or am I doing something wrong?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/zipkin/issues/1541#issuecomment-288984047>,
or mute the thread

**Comment by ys** [comment]
It is a sidekiq background job. 
So yeah async tasks on same app.

**Comment by codefromthecrypt** [comment]
If it doesnt make a remote call, maybe best to not add cs sr in that span.
It is possible there is some ui logic that is looking at that. This is just
a guess

**Comment by ys** [comment]
This enqueue the job into redis.
Side question is how would you render that ?
It is async jobs with a queue that is redis.

Different instances

**Comment by codefromthecrypt** [comment]
Existing code (zipkin-js and finagle) render redis as a client span (cs
cr). There wouldnt be a 'sr' until redis itself has zipkin support. cr is
the end of a span.. if theres something later that happens as a callback
from the redis command.. probably a child span?

Ascii art flow of what is going on in real life might help. Usually the
boxes in a flow diagram end up as spans.

**Comment by ys** [comment]
```
+-------------+       +-------------------------+       +-----------------------------------+
| web request |  --> | Enqueuing job in sidekiq |  --> | worker pick the job and process it  |
+-------------+       +-------------------------+       +-----------------------------------+
```

https://gist.github.com/ys/a7190081d466747e1d42376cd65928fa here are the two classes responsible for serializing the trace and deserialize it.

**Comment by codefromthecrypt** [comment]
here's my 2p:

so I think the client enquing the span would be a one-way "cs"
the worker pulling the message extracts trace ids and adds "sr" to the same
span as the client.
a child span of that should be made for the processing of that message

**Comment by codefromthecrypt** [comment]
PS we have messaging spans now.. do you like things like this?
![screen shot 2018-10-22 at 5 32 49 pm](https://user-images.githubusercontent.com/64215/47356213-fde86e80-d6f5-11e8-80a4-f5014768943c.png)

**Comment by jorgheymans** [comment]
zipkin-classic is no longer maintained, i verified that the linked trace displays correctly in Lens.
