### ISSUE TITLE
Span count of same trace is showing differently between Search page and trace details page in UI

### ISSUE THREAD

**Issue by praveenbarli** [openzipkin/zipkin#1544]
Bug is seen on the UI search page . 

Upon debugging I found that the span count is calculated using different logic in search UI. Details page is showing accurate number - span count after merging.. where as search page is relying on total timestamp in a trace.
https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/traceToMustache.js#L179
https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/traceSummary.js#L244

![image](https://cloud.githubusercontent.com/assets/22087406/24283412/d1c643cc-1022-11e7-9fd0-7ceaafb81035.png)
Detials page: 
![image](https://cloud.githubusercontent.com/assets/22087406/24283438/fa91a1ca-1022-11e7-8fdc-7a7c3f11bfdb.png)

**Comment by codefromthecrypt** [comment]
It looks like the 5 spans is relating to the amount of service * spans in the trace (ex if you look at the image, clientapp.com X2 + desktop-prbarl *2 + localhost * 1 = 5

a unit test could probably prove this out https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/test/component_ui/traceSummary.test.js#L329

**Comment by codefromthecrypt** [comment]
As suspected by @prbarl this looks like a dupe of #842

**Comment by praveenbarli** [comment]
@adriancole  I debugged throught the code and I see that span count on search details page is calculated as "Sum of  (Unique services (part of annotation and binary annotation endpoints) in each span ) ". As this is happeing at UI end the Span's are merged ones coming from API. However I didn't understand why it is called Span count. I would describe this count as sum of unique events across spans.

**Comment by codefromthecrypt** [comment]
I'm answering eventhough this logic predated me by quite a while.

the search screen is primarily partitioned by service. a guess is that this was originally Span count (in service) as opposed to Total Spans.

In that case, span count in this screen is implicitly count of spans that passed through the selected service. For example, there's a percentage of time in the same panel which is also "current service" specific.

If it were more clear, it could be a fraction ex. "Span count: 5/10"

The trace detail screen isn't scoped to a specific service by default, and the "Total spans" there should be in fact the total. The "per service" boxes below it should be accurate. For example, if you click on a span which had the service "foo" selected in the search screen, then the Span count on the search screen should match "foo x NNN" on the detail screen.

**Comment by codefromthecrypt** [comment]
The following trace can reproduce the issue.. the search page is reporting service * span (I think) as opposed to total spans as span count

```json
[
  {
    "traceId": "5c53ab5f3f2ac9ff",
    "id": "5c53ab5f3f2ac9ff",
    "name": "get",
    "timestamp": 1491286274031591,
    "duration": 37217,
    "annotations": [
      {
        "timestamp": 1491286274031591,
        "value": "sr",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      },
      {
        "timestamp": 1491286274068808,
        "value": "ss",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      }
    ],
    "binaryAnnotations": [
      {
        "key": "ca",
        "value": true,
        "endpoint": {
          "serviceName": "",
          "ipv4": "192.168.99.1",
          "port": 59656
        }
      },
      {
        "key": "http.status_code",
        "value": "200",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      },
      {
        "key": "http.url",
        "value": "/api/v1/spans",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      }
    ]
  },
  {
    "traceId": "5c53ab5f3f2ac9ff",
    "id": "331fc2da6e9d74cf",
    "name": "get-span-names",
    "parentId": "5c53ab5f3f2ac9ff",
    "timestamp": 1491286274031937,
    "duration": 35797,
    "binaryAnnotations": [
      {
        "key": "lc",
        "value": "AutoValue_ElasticsearchHttpStorage",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      }
    ]
  },
  {
    "traceId": "5c53ab5f3f2ac9ff",
    "id": "fcd1101cae5fc528",
    "name": "aggregation",
    "parentId": "331fc2da6e9d74cf",
    "timestamp": 1491286274037720,
    "duration": 29791,
    "binaryAnnotations": [
      {
        "key": "lc",
        "value": "okhttp",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      }
    ]
  },
  {
    "traceId": "5c53ab5f3f2ac9ff",
    "id": "a69778605c1e1a00",
    "name": "post",
    "parentId": "fcd1101cae5fc528",
    "timestamp": 1491286274043711,
    "duration": 23671,
    "annotations": [
      {
        "timestamp": 1491286274043711,
        "value": "cs",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      },
      {
        "timestamp": 1491286274067382,
        "value": "cr",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      }
    ],
    "binaryAnnotations": [
      {
        "key": "http.url",
        "value": "http://elasticsearch:9200/zipkin-2017-04-03,zipkin-2017-04-04/span/_search?allow_no_indices=true&expand_wildcards=open&ignore_unavailable=true",
        "endpoint": {
          "serviceName": "zipkin-server",
          "ipv4": "172.18.0.4",
          "port": 9411
        }
      },
      {
        "key": "sa",
        "value": true,
        "endpoint": {
          "serviceName": "elasticsearch",
          "ipv4": "172.18.0.2",
          "port": 9200
        }
      }
    ]
  }
]
```

**Comment by codefromthecrypt** [comment]
so you see something like this.. note that the number 5 matches the count summed below it.

<img width="278" alt="screen shot 2017-04-04 at 2 18 47 pm" src="https://cloud.githubusercontent.com/assets/64215/24643621/af5043f6-1941-11e7-8bc9-117c793b3cac.png">

We either need to change the name to something besides "spans" or replace the value with totalSpans

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1550

**Comment by codefromthecrypt** [comment]
this should be fixed now.. try latest (currently 1.23.0)

**Comment by praveenbarli** [comment]
Thanks Adrian! I’ll pull latest.
