### ISSUE TITLE
Can't log a record in console?

### ISSUE THREAD

**Issue by ruinanchen** [openzipkin/zipkin#1551]
Hi, 
Firstly, I should not ask question here, but This has already perplexed me for a long time.
I am debuging zipkin: 
1. I add configure in zikin-server-share.yaml
 zipkin.collector.kafka.KafkaCollector: 'DEBUG'

2.  I define a member of class KafkaCollector:
private static final Logger logger = Logger.getLogger(KafkaCollector.class.getName());

3. I add  a log in class KafkaCollector's member start:
@Override public KafkaCollector start() {
    logger.fine("KafkaCollector  start");//added line
    connector.get();
    streams.get();
    return this;
  }

4. I build & run program:
KAFKA_ZOOKEEPER=localhost:2181 java -jar zipkin-server-1.20.2-SNAPSHOT-exec.jar

I can't find log record in console, but i can find the thread use pstack PID.
Why ???Thank you very much.

**Comment by codefromthecrypt** [comment]
have you tried https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#logging

if you have more problems try https://gitter.im/openzipkin/zipkin or worst case stackoverflow thx!

**Comment by ruinanchen** [comment]
@adriancole Thank you very very much, I solve the problem.
