### ISSUE TITLE
UI does not show latest spans

### ISSUE THREAD

**Issue by strizhov** [openzipkin/zipkin#1567]
Hello,

We have a setup of zipkin jar (v1.22) with MySQL RDS backend. 

After about 20 mins collecting spans from our services, the UI does not show latest spans. 

A simple mysql query `select count(*) from zipkin_spans;` shows that database is being constantly updated with new spans, but UI search does not show them (in fact it shows that the latest span was 20 mins ago). 

We have run tcpdump that confirmed that there are new spans coming on port 9411 from our services.

If we switch back to memory based backend, there is no such issue, however we can't run memory backend due to out-of-memory problem discussed in https://github.com/openzipkin/zipkin/issues/1528

"/health" endpoint shows "UP" in all values.

Let me know if you need any additional details.
Thanks

**Comment by codefromthecrypt** [comment]
troubleshooting is a bit easier on gitter https://gitter.im/openzipkin/zipkin

that said, it is interesting this pattern only exists in mysql so far (you could also try aws elasticsearch, but still we should figure out what's up).

try setting `SELF_TRACING_ENABLED=true` and see if zipkin traces make it even if yours don't? This might help narrow things down

**Comment by codefromthecrypt** [comment]
here's an example query which might help, too https://github.com/openzipkin/zipkin/pull/1568

**Comment by strizhov** [comment]
thanks for response. 

I have tried `SELF_TRACING_ENABLED=true` and received internal traces, but UI stopped reporting any new traces after about 20 mins run.

I also tried sql command from README file (after about 30 min zipkin collector run), but it didn't return anything. 

I am going to try cassandra storage at this point.

**Comment by codefromthecrypt** [comment]
Sorry about timezones making this troubleshooting more difficult. So are
you saying that you saw internal traces but not app ones after 30m or that
you saw no traces? Seems like none if the sql query returned none. You
could check the /metrics endpoint to ensure you are receiving messages.

Yep es or c* are better long term anyway although i would like to
understand what you are bumping into.. guessing theres an error receiving
or writing data which is somehow not in you logs. Seeing metrics will at
least show you spans incoming and if these are plotted with something you
might see a correlation between the incoming messages counted and the count
in storage. If you look at the docker-zipkin repo theres a pull request
regarding metrics and prometheus if you dont have a different tool (or just
calling /metrics isnt enough)

**Comment by feliksik** [comment]
Do make sure your browser is using the right begin and end time; that is, check whether you're not bitten by #1587 .

**Comment by codefromthecrypt** [comment]
closing as a question as there's no clear single change to the codebase this is about. If we need to revisit, please chat on gitter! https://gitter.im/openzipkin/zipkin
