### ISSUE TITLE
pop up UI for span goes out of bound if error message is long

### ISSUE THREAD

**Issue by praveenbarli** [openzipkin/zipkin#1574]
I see a text area with scroll bar should help..

![image](https://cloud.githubusercontent.com/assets/22087406/25370639/f3bd20f4-2940-11e7-91ee-6544d124a0cc.png)

**Comment by codefromthecrypt** [comment]
I think this was also noticed by @felixbarny

**Comment by felixbarny** [comment]
Right. The overflow should be handled just like in the JSON panel.

**Comment by zeagord** [comment]
This must be fixed in the latest versions after #2224
