### ISSUE TITLE
zipkin-ui renovation

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1577]
We recently opened a repo openzipkin/zipkin-ui, but it doesn't have anyone working on it and lacking several important features. We cannot abandon the current UI, not just because people are using it, but also because people are maintaining it!

Recently, @eirslett helped immensely by renovating the build and backend, notably we have unit tests and handlebar routing.

It seems twitter moved from flightjs (what we use for front end and what is deprecated) to react. I opened a tweet to see if there are hints or any other form of help around a transition like this.
https://twitter.com/micheal/status/857278320878116864

Since there were many twitter apps using flightjs, and this was written at twitter, there could possibly be a way to transition in a similar fashion.

**Comment by necolas** [comment]
Hi, as far as Twitter Lite goes, we didn't transition but started from scratch. @rondevera might know of some internal apps that are transitioning from FlightJS to React

**Comment by eirslett** [comment]
I did an experiment a while ago, I ported the current UI to react/redux. Which worked pretty well, except I was only 50 % done (for the sake of the experiment) so I never finished it.
Starting from scratch comes with the risk of never getting finished, like zipkin-ui... also I'm not sure if the Angular 2 + TypeScript stack is as familiar to general developers as React+Redux (or both might be inaccessible, I'm not sure).

**Comment by codefromthecrypt** [comment]
@eirslett wonder if you still have a stash of some of it, or if it is possible to raise a partial migration (Ex the service/span name dropdown to react+dedux). I might be able to follow-the-leader from there (or at least try..)

**Comment by codefromthecrypt** [comment]
@rondevera any tips on migrating from flightjs to react?

**Comment by codefromthecrypt** [comment]
@zeagord I think you've some work towards this

**Comment by eirslett** [comment]
The last renovation effort stalled at 80 % progress, I think one of the mistakes was to do it from scratch, instead of aiming for a gradual rewrite. By doing it gradually, the migration can be prioritized or stalled, and there will still be benefits from the partial migration. (Though more tech debt from having two tech stacks in the same UI)

**Comment by codefromthecrypt** [comment]
there's now a UI Renovation project as folks are able to progress this

**Comment by jorgheymans** [comment]
With Lens being the new default UI now we can consider zipkin-ui renovation complete. Separate issues should be directly logged against Lens.
