### ISSUE TITLE
Counter logs successful send despite failure when SLF4J logger missing

### ISSUE THREAD

**Issue by rstrickland** [openzipkin/zipkin#158]
When there's no SLF4J logger implementation on the classpath, the Zipkin log_span counter logs a successful send when it's actually failing due to a NoClassDefFoundException.  Using a simple console StatsReceiver with no logger implementation, the output is as follows:

Counter HttpServer:connects = 1
Counter HttpServer:received_bytes = 149
Counter HttpServer:requests = 1
Stat HttpServer:handletime_us = 61161.0
Stat HttpServer:request_latency_ms = 4.0
Counter HttpServer:success = 1
Counter zipkin:create_log_entries:error:java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder = 1
Counter HttpServer:sent_bytes = 19
Stat HttpServer:connection_received_bytes = 149.0
Stat HttpServer:connection_sent_bytes = 19.0
Stat HttpServer:connection_duration = 170.0
Stat HttpServer:connection_requests = 1.0
Counter zipkin:log_span:ok = 1

... but the span is not actually sent to Scribe.

**Comment by franklinhu** [comment]
I believe we're in the process of upgrading Finagle to use SLF4J 1.6.x, so this should be fixed in the near future

**Comment by eirslett** [comment]
This probably doesn't apply anymore.
