### ISSUE TITLE
Having issue installing zipkin

### ISSUE THREAD

**Issue by Akhilesh-Anb** [openzipkin/zipkin#1584]
While running the command,
./mvnw -DskipTests --also-make -pl zipkin-server clean install

I'm facing the following error.

> [openplatform@ zipkin]$ ./mvnw -DskipTests --also-make -pl zipkin-server clean install
> Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.0/apache-maven-3.5.0-bin.zip
> 
> Exception in thread "main" java.net.UnknownHostException: repo1.maven.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:589)
>         at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
>         at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
>         at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
>         at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
>         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
>         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
>         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
>         at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:73)
>         at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:60)
>         at org.apache.maven.wrapper.Installer.createDist(Installer.java:64)
>         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
>         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
>

**Comment by codefromthecrypt** [comment]
Looks like you cannot access maven central. Are you behind a proxy? If so,
you can google for how to use proxies with Maven. Also, you do not have to
build from scratch. You can use the docker image or download from bintray.

**Comment by shakuzen** [comment]
@Akhilesh-Anb feel free to come chat with us on [Gitter](https://gitter.im/openzipkin/zipkin) if you still have questions. As Adrian mentioned, you can follow the Quick Start instructions if you just want to run Zipkin Server: https://github.com/openzipkin/zipkin#quick-start
