### ISSUE TITLE
Be lenient when parsing http query field names

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1585]
Notably one of our fields is all lowercase "lookback", but the others are lower-camel. It is a bit eye-squinting to figure out the problem with this query

```bash
curl -s 'localhost:9411/api/v1/traces?annotationquery=event.type%3Dfoo&endts=1493821821000000000&limit=100&lookback=432000000000000&minDuration=&servicename=foo-service&spanname=all'
```

I'm of the opinion that accepting all downcase is worthwhile as it isn't worth annoying new users, nor time to troubleshoot considering the code to accept all downcase would be pretty ok.

**Comment by jorgheymans** [comment]
Unless you still feel strong about this i'ld say we scratch this one off the list. The parameters are what they are and have been for quite a while now, i have looked at the issues list and did not see any support issues complaining about it.

About `lookback` not being camelcase, https://github.com/search?l=Java&q=lookback&type=Code suggests that there is no consensus really and everybody does as they see fit so we're certainly not in the wrong.

**Comment by codefromthecrypt** [comment]
as the only person asking for this, I think it is fine to close based on your comments. thanks @jorgheymans!
