### ISSUE TITLE
UI: default query "End Time" will miss the newest traces

### ISSUE THREAD

**Issue by feliksik** [openzipkin/zipkin#1587]
**Type**: bug/improvement

**Observed behavior**: When zipkin received traces at 13:01:10, and you the UI at 13:01:30, the default query "End time" will be 13:01(:00). So the time is Now() rounded down. Result is that the newest traces are missed. 

**Expected behavior**: Newest traces are shown, too, with the default query settings. 

**Workaround**: Change the query "End time" manually to be 1 minute higher, or wait a minute and refresh. 

**Possible solutions**: 

- round the end time up
- if no-one clicks anything in the UI, we should be able to send no endTs which then the server will choose

**Comment by a-roberts** [comment]
+1, looking for this too, defaults aren't particularly useful if you wanted to do a quick "zero to hero" demonstration - fiddling with defaults would be a necessary first step.

While modifying this (I propose just setting it to include anything from the previous hour as well, like with Prometheus) it would be great to order by newest first as well, and just having a limit of 10 is really quite small...

**Comment by codefromthecrypt** [comment]
With the type of UI skills I have, I can round up :) might be more work, even if not much do do other things it would require a bit more understanding

**Comment by codefromthecrypt** [comment]
just pinged about limit here as different topic https://github.com/openzipkin/zipkin/pull/443

**Comment by codefromthecrypt** [comment]
@schlosna if you want a relatively straightforward one to help with, here 'tis!

**Comment by jorgheymans** [comment]
If i understood the limitation correctly, Lens (the new Zipkin UI) does not have this problem. The default lookback period is 15 minutes and includes spans received in the same minute. This can be observed by starting zipkin with self tracing enabled, `--zipkin.self-tracing.enabled=true`, then refreshing the screen a few times and clicking on the search button without changing any of the default time criteria. The result is that all the traces that were just generated seconds before show up on the screen.

@feliksik @adriancole are you ok with closing this or is there still something else i'm missing here ?

**Comment by jorgheymans** [comment]
Closing, as the default query end time no longer misses newest traces. There are other issues with the component handling custom lookback, but that is / will be tracked in separate issues.
