### ISSUE TITLE
Make it possible to disable the query api for collector-only servers

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin#1591]
We are deploying a zipkin server to a high-security production environment, and wish to disable the query API (ZipkinQueryApiV1) in order to minimise access to details of our system architecture.

**Comment by codefromthecrypt** [comment]
Oops.. yeah we should have a flag for this.

PS This probably applies to any "collector-only" deployment, whether that's a standard build or something like [stackdriver-zipkin](https://github.com/GoogleCloudPlatform/stackdriver-zipkin/tree/master/collector) or [sleuth's stream server](https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/spring-cloud-sleuth-zipkin-stream)

**Comment by shakuzen** [comment]
Should be able to do this easily with `@Profile` or some `Conditional` on the controller. I forget if it is ill-advised to use Spring Boot's `@ConditionalOnProperty` outside of an auto-configuration class...

EDIT: Confirmed using a `Conditional` including `@ConditionalOnProperty` should be fine. See [this Gitter conversation](https://gitter.im/spring-projects/spring-boot?at=5919674800efc2bb3e6b2b3a)
