### ISSUE TITLE
mysql storage /health only work with database name 'zipkin'

### ISSUE THREAD

**Issue by zhanglc** [openzipkin/zipkin#1592]
if no zipkin in schemes ,will throw: new IllegalStateException("Zipkin schema is missing")

MySQLStorage.java : 
```
@Override public CheckResult check() {
    try (Connection conn = datasource.getConnection()) {
      if (!context.get(conn).meta().getSchemas().contains(DEFAULT_CATALOG.ZIPKIN)) {
        throw new IllegalStateException("Zipkin schema is missing");
      }
    } catch (SQLException | RuntimeException e) {
      return CheckResult.failed(e);
    }
    return CheckResult.OK;
  }
```

**Comment by codefromthecrypt** [comment]
oh.. you mean to say if the schema property has been overwritten, this
error is misleading?

**Comment by zhanglc** [comment]
Yup.... the /health will return `{'MYSQL':DOWN}` if there is no 'zipkin' database . the `CheckResult ` metho should checked with user settings.
ie:
start with the line:
`STORAGE_TYPE=mysql MYSQL_HOST=192.168.1.231 MYSQL_TCP_PORT=3306 MYSQL_DB=zipkin_test MYSQL_USER=zipkin_user  nohup java -jar zipkin.jar &`

 the `CheckResult` method should check `zipkin_test ` but not `zipkin`

**Comment by codefromthecrypt** [comment]
good news is that only the health check is messed up :)

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1595
