### ISSUE TITLE
Feature Request: DynamoDB support 

### ISSUE THREAD

**Issue by cemo** [openzipkin/zipkin#1599]
I would like to see DynamoDB support for zipkin. I usually let AWS services to store data and I deal rest of the services. DynamoDB seems a good and cheap alternative for Zipkin. Is it possible to support it as well?

**Comment by cemo** [comment]
@adriancole is this attractive only for me? DynamoDB based on storage means less cost and a better scalability. Am I missing something at here? Or Should I open this issue on zipkin-aws?

**Comment by codefromthecrypt** [comment]
This issue was moved to openzipkin/zipkin-aws#45

**Comment by codefromthecrypt** [comment]
moved to zipkin-aws. generally speaking we don't do something as involved as adding another storage option until there is more than one person interested. There's significant maintenance effort involved in storage layer vs simpler components such as collectors.
