### ISSUE TITLE
qps

### ISSUE THREAD

**Issue by yzfshuijing** [openzipkin/zipkin#1600]
Is there a measure of the qps about the zipkin-server with different storage?

**Comment by jcarres-mdsol** [comment]
That would be tough as it would depend on size of the servers, network, etc.

**Comment by yzfshuijing** [comment]
@jcarres-mdsol 
I means is there any test report about the qps using the httpcollector, so i can conclude the qps in my envirment
after all, the datas reported to the collector may be very large per second
thanks

**Comment by codefromthecrypt** [comment]
Zipkin collects metrics on span count and size (including message they came
in)

https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#metrics

There's a work-in-progress for a dashboard on this
https://github.com/openzipkin/docker-zipkin/pull/135

You can use these tools to measure your throughput, and possibly use them
as feedback loops in a load testing tool.

**Comment by shakuzen** [comment]
You can also reference what load and number of instances some users handle, as documented in sub pages here: https://cwiki.apache.org/confluence/display/ZIPKIN/Sites

As @jcarres-mdsol mentioned, your results will vary depending on sizing and different bottlenecks.

**Comment by jorgheymans** [comment]
Question seems to have been answered, no more feedback from OP.
