### ISSUE TITLE
Default to in-memory storage type when STORAGE_TYPE is empty

### ISSUE THREAD

**Issue by Crevil** [openzipkin/zipkin#1601]
## What kind of issue is this?

 - [x] Feature Request. First, look at existing issues to see if the feature has been requested
       before. If you don't find anything, tell us what problem you’re trying to solve. Often a
       solution already exists! Don’t send pull requests to implement new features without first
       getting our support. Sometimes we leave features out on purpose to keep the project small.

## Request

Default the storage type to in-memory when environment variable `STORAGE_TYPE` is empty.

## Reason
It was unexpected to me that when setting the variable to an empty value would impact the system

Reproduction of the current implementation
```shell
docker run -e "STORAGE_TYPE=" -d -p 9411:9411 openzipkin/zipkin
```

When inspecting the logs it shows the following:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in zipkin.server.ZipkinHttpCollector required a bean of type 'zipkin.storage.StorageComponent' that could not be found.
	- Bean method 'storage' not loaded because @ConditionalOnProperty (zipkin.storage.type=cassandra) found different value in property 'zipkin.storage.type'
	- Bean method 'storage' not loaded because @ConditionalOnProperty (zipkin.storage.type=cassandra3) found different value in property 'zipkin.storage.type'
	- Bean method 'storage' not loaded because @ConditionalOnProperty (zipkin.storage.type=elasticsearch) found different value in property 'zipkin.storage.type'
	- Bean method 'storage' not loaded because @ConditionalOnProperty (zipkin.storage.type=mysql) found different value in property 'zipkin.storage.type'
	- Bean method 'storage' not loaded because @ConditionalOnProperty (zipkin.storage.type=mem) found different value in property 'zipkin.storage.type'


Action:

Consider revisiting the conditions above or defining a bean of type 'zipkin.storage.StorageComponent' in your configuration.
```

**Comment by codefromthecrypt** [comment]
looks like a change here:
https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java#L84

wanna try (also adding a unit test)?

**Comment by Crevil** [comment]
Sure, I'll give it a look some time this week.

**Comment by codefromthecrypt** [comment]
ping! weeks do get away from us, sending one nag just in case the next one doesn't :D

**Comment by Crevil** [comment]
I gave it a look, but I'm to unfamiliar with Java to get my head around this.

**Comment by codefromthecrypt** [comment]
>
> I gave it a look, but I'm to unfamiliar with Java to get my head around
> this.
>
if unfamiliar, advice would be to box a little time to try, and speak up if
you hit a wall and would like help.

**Comment by codefromthecrypt** [comment]
Oh sorry I read you wrong... you already gave it a look. No biggie. ping me
if I don't get this in the next week.

**Comment by Crevil** [comment]
As requested, here is a ping @adriancole :)

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1759 !

**Comment by Crevil** [comment]
That was fast! Good job and thank you for doing this! 😃

**Comment by nickHsiung** [comment]
> looks like a change here: https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java#L84 wanna try (also adding a unit test)?

page not found.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin2/server/internal/ZipkinServerConfiguration.java
