### ISSUE TITLE
Create zipkin plugin LayoutFactory for spring-boot

### ISSUE THREAD

**Issue by devinsba** [openzipkin/zipkin#1602]
Per this issue: https://github.com/openzipkin/zipkin-aws/issues/32 we will no longer be able to use `MODULE` layout for our zipkin plugins in the future. The solution to this is to create a `LayoutFactory` class. This is something we should create so that we make our plugins work the way we want them to.

**Comment by codefromthecrypt** [comment]
ok, so would this be similar to the centralsync maven plugin, ex a decoupled artifact (solving a weird dependency loop of the build on a project it encloses.

**Comment by devinsba** [comment]
Yeah, it would be used most in zipkin-aws and zipkin-azure and any other places that people might be building plugins for layering into the server

**Comment by codefromthecrypt** [comment]
so for repo name.. zipkin-layout-factory? or
zipkin-spring-boot-loader-tools? (based on the implied jar)

cc @shakuzen @llinder

**Comment by shakuzen** [comment]
I like the brevity of zipkin-layout-factory, but that (for better or worse) restricts the repo to a very narrow scope. zipkin-spring-boot-loader-tools on the other hand feels like it could have a couple related concerns in it (though so far I don't know what they would be other than the one mentioned in this issue)
If I had to pick one of the suggested names now, I would go with zipkin-layout-factory. I can’t think of a better one now, either.

**Comment by llinder** [comment]
zipkin-layout-factory sounds fine to me

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin-layout-factory

>

**Comment by shakuzen** [comment]
Closing as this is done thanks to the great work of @zeagord https://github.com/openzipkin/zipkin-layout-factory
