### ISSUE TITLE
hao to create field  to elasticStorage

### ISSUE THREAD

**Issue by qq494679975** [openzipkin/zipkin#1620]
i use zipkin in my spring-cloud-project ,and choose elasticsearech storage。But the default elasticStorage _source like this
{....
"_source": {
    "timestamp_millis": 1497855739973,
    "traceId": "30063886a171f579",
    "id": "15fa4c19599c860e",
    "name": "http: /v1/patient/hello",
    "parentId": "30063886a171f579",
    "timestamp": 1497855739973000,
    "duration": 120,
    "binaryAnnotations": []
}
...
}
what should i do if i want to add my field?
just like
{....
"_source": {
    "timestamp_millis": 1497855739973,
    "traceId": "30063886a171f579",
    "id": "15fa4c19599c860e",
    "name": "http: /v1/patient/hello",
    "parentId": "30063886a171f579",
    "timestamp": 1497855739973000,
    "duration": 120,
    **"is_success":"true"  , // this is my field**
    "binaryAnnotations": []
}
...
}
sorry,my english is very poor

**Comment by codefromthecrypt** [comment]
Custom fields could be added using elasticsearch 5+ pipeline feature
https://www.elastic.co/guide/en/elasticsearch/reference/current/pipeline.html

Sorry I dont have an example but this is what you can try

**Comment by qq494679975** [comment]
well，i use elasticsearch 2.4.4··Is there any other way?

**Comment by codefromthecrypt** [comment]
no there isn't any supported way in 2.4
