### ISSUE TITLE
XSS vulnerabilities

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin#1623]
There exist some XSS vulnerabilities within zipkin and its UI. Either through an injection attack via tags/annotations or by appending injection attack data to the end of the URL, we were able to successfully get the attack to fire when viewing the details of a span. We were only able to get it to happen in the span detail modal window, so it looks as though the data needs sanitising before rendering.

The tag/annotation injection was done using brave, as per the below example:

`    span.annotate("<script>alert(123)</script>");`
`    span.annotate("Annotation 2</td><script>alert(321)</script><td>");`
`    span.annotate("<img src=x onerror=alert(123) />");`
`    span.tag("Tag key 1</td><script>alert('tag key 1')</script><td>", "<script>alert(\"tag value 1\")</script>");`
`    span.tag("Tag key 2</td><!--", "\"quotes are great two\"");`
`    span.tag("<img src=x onerror=alert(123) />", "\"quotes are great two\"");`

Some examples of how this effects the UI is as follows. Please excuse the sanitised screenshots.

Clicking on a span that has been injected by tag/annotation
![1](https://user-images.githubusercontent.com/28124884/27312613-c9e9c5e6-55ac-11e7-9c73-737b6b4e1318.png)
![2](https://user-images.githubusercontent.com/28124884/27312614-c9e9d158-55ac-11e7-973f-f0f81e79f152.png)

How the tag/annotation injected span detail looks:
![3](https://user-images.githubusercontent.com/28124884/27312612-c9c802b2-55ac-11e7-9840-51472a58b0f7.png)

How the tag/annotation injected span script is in the DOM:
![4](https://user-images.githubusercontent.com/28124884/27313124-9cb57bc6-55af-11e7-9225-9795e3ff000f.png)
![5](https://user-images.githubusercontent.com/28124884/27312611-c9c729dc-55ac-11e7-8aae-56b4bbdb8318.png)

Injection attack by URL
![6](https://user-images.githubusercontent.com/28124884/27312608-c9bef12c-55ac-11e7-88c9-53e91bc0457d.png)

Clicking on a span that has had injection attack by URL:
![7](https://user-images.githubusercontent.com/28124884/27312609-c9c04db0-55ac-11e7-8f17-509eb3b9bff8.png)

How injection attack by URL is rendered in DOM:
![8](https://user-images.githubusercontent.com/28124884/27312607-c9bcfb88-55ac-11e7-9ad4-bfa03a3e6e64.png)

**Comment by codefromthecrypt** [comment]
@eirslett @basvanbeek know anyone w/xss mitigation experience?

**Comment by ghost** [comment]
I would imagine you can attack it in two ways. When you receive data, you sanitise it.

and when you render it, you should be able to ask your framework to sanitise the data. What's the UI framework you're using?

**Comment by codefromthecrypt** [comment]
Good points. Responses inline!

I would imagine you can attack it in two ways. When you receive data, you
sanitise it.

This is one use case of zipkin-sparkstreaming, though people making custom
builds of zipkin server can likely intercept the Collector or Storage
component to do the same.

and when you render it, you should be able to ask your framework to
sanitise the data. What's the UI framework you're using

We are using flightjs and crossroads
https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/package.json

There is not yet started renovation idea towards react redux
https://github.com/openzipkin/zipkin/issues/1577#issuecomment-297876694

**Comment by eirslett** [comment]
I'm surprised this is an issue. We use Mustache for templating, which escapes input by default...

**Comment by eirslett** [comment]
Looks like there's a lot of cowboy jQuery in our views, that don't escape input properly.
I'm not sure if it's faster to just port the code to React/Redux, than to look through all the vulnerabilities and fix them...

**Comment by ghost** [comment]
We only found the issue to be on the span detail modal, if that helps narrow it.

**Comment by ghost** [comment]
I must admit I was surprised as well when our security guy found it.

**Comment by eirslett** [comment]
I found it, it's all in this file: https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/spanPanel.js#L35

In some places, we're doing

```javascript
const html = `<tag>${unescapedStuff}</tag>`;
```

and the fix is to do

```javascript
// https://stackoverflow.com/a/12034334
const entityMap = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
  '/': '&#x2F;',
  '`': '&#x60;',
  '=': '&#x3D;'
};

function escapeHtml (string) {
  return String(string).replace(/[&<>"'`=\/]/g, s => entityMap[s]);
}

const html = `<tag>${escapeHtml(unescapedStuff)}</tag>`;
```

I don't have time now to spin up Zipkin with test data and confirm that it works, but that should be the fix.

**Comment by eirslett** [comment]
I made a quickie PR. @sirtyro do you still have a server available with the tampered data? Could you try running my patch and see if it helps?

**Comment by ghost** [comment]
Sure thing, give me about 20min

**Comment by codefromthecrypt** [comment]
fwiw here's a span with the trace data in it, wrapped in an array for easy posting to zipkin.

```bash
curl -s localhost:9411/api/v1/spans -H'Content-Type: application/json' -d '[{
  "traceId": "6add063375594175",
  "id": "6add063375594175",
  "name": "",
  "timestamp": 1498043010965929,
  "duration": 6650,
  "annotations": [
    {
      "timestamp": 1498043010971277,
      "value": "<script>alert(1)</script>",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    },
    {
      "timestamp": 1498043010971480,
      "value": "Annotation 2</td><script>alert(2)</script><td>",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    },
    {
      "timestamp": 1498043010971489,
      "value": "<img src=x onerror=alert(3) />",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    }
  ],
  "binaryAnnotations": [
    {
      "key": "<img src=x onerror=alert(4) />",
      "value": "\"quotes are great two\"",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    },
    {
      "key": "Tag key 1</td><script>alert(tag key 5)</script><td>",
      "value": "<script>alert(\"tag value 1\")</script>",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    },
    {
      "key": "Tag key 2</td><!--",
      "value": "\"quotes are great two\"",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    }
  ]
}]'
```

**Comment by codefromthecrypt** [comment]
I'm looking into this. thanks @eirslett for the headstart!
