### ISSUE TITLE
Zipkin Can not show dependency graph when using ElasticSearch 5 for storage.

### ISSUE THREAD

**Issue by eacdy** [openzipkin/zipkin#1630]
I have two micro services.

* User Service: `microservice-simple-provider-user-trace-zipkin` （localhost:8000）
* Movie Service: `microservice-simple-consumer-movie-trace-zipkin` （localhost:8010）

When I call <http://localhost:8010/user/1> , Movie Service will call<http://localhost:8000/1> using RestTemplate.

I integrate both of the two services with Spring Cloud Sleuth and Zipkin.

When I test like below:

* Start `microservice-trace-zipkin-server-elasticsearch` （localhost:9411, Zipkin Server using **ElasticSearch 5** for storage）
* Start `microservice-simple-provider-user-trace-zipkin`
* Start `microservice-simple-consumer-movie-trace-zipkin` 
* call <http://localhost/user/1>
* open up <http://localhost:9411/dependency>
* I Can see NOTHING!!! The dependency graph will never come out!
<img width="955" alt="2" src="https://user-images.githubusercontent.com/9031050/27569125-6975e7a4-5b28-11e7-9001-6bb28c07ca8b.png">

When I test like below: 

- Start `microservice-trace-zipkin-server` （localhost:9411, Zipkin Server using **memery** for storage）
- Start `microservice-simple-provider-user-trace-zipkin`
- Start `microservice-simple-consumer-movie-trace-zipkin` 
- call <http://localhost/user/1>
- open up <http://localhost:9411/dependency>
- I Can see the graph below:
<img width="1002" alt="1" src="https://user-images.githubusercontent.com/9031050/27569089-2bc5ac96-5b28-11e7-8d35-a6d3819f099f.png">

WHAT'S wrong with my samples? Why Does not the dependency graph show when using ElasticSearch 5 for  storage? Could you help me?

Code is here: <https://github.com/eacdy/test-for-issue-spring-cloud-sleuth> .

**Comment by ImFlog** [comment]
Hello,
To create the dependency graph when not in memory you have to use the [spark job](https://github.com/openzipkin/zipkin-dependencies).
Read the documentation, you should find your way easily.
Hope it helps.

**Comment by codefromthecrypt** [comment]
thanks for answering @ImFlog 

@eacdy ps if you can, next time you run into a problem, use gitter as we could probably have saved you some trouble https://gitter.im/openzipkin/zipkin

**Comment by eacdy** [comment]
@ImFlog @adriancole Thans a lot.
