### ISSUE TITLE
Add unit tests to ensure component names aren't crap in health check

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1646]
Right now, elasticsearch shows as `AutoValue_ElasticsearchHttpStorage` in the health check. This should be the simple name w/o AutoValue_. ZipkinHealthIndicator should scrub `AutoValue_` from the simple class name.

**Comment by jorgheymans** [comment]
This is actually covered by specific tests in [CassandraStorageTest](https://github.com/openzipkin/zipkin/blob/f238246b30ffae0e52b8323e3547a0d97b9aef0c/zipkin-storage/cassandra/src/test/java/zipkin2/storage/cassandra/CassandraStorageTest.java#L39) , [CassandraStorageTest.v1](https://github.com/openzipkin/zipkin/blob/f238246b30ffae0e52b8323e3547a0d97b9aef0c/zipkin-storage/cassandra-v1/src/test/java/zipkin2/storage/cassandra/v1/CassandraStorageTest.java#L28), [ElasticsearchStorageTest](https://github.com/openzipkin/zipkin/blob/10c478ba049696e9ef32e8400a3d7209e3f31c5a/zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/ElasticsearchStorageTest.java#L196), and InMemoryStorageTest was aligned to this in https://github.com/openzipkin/zipkin/pull/3085 which will close this issue once merged.

**Comment by codefromthecrypt** [comment]
oh wow github is smarter than I thought about auto closing!
