### ISSUE TITLE
Cleanup scald.rb

### ISSUE THREAD

**Issue by franklinhu** [openzipkin/zipkin#165]
The way to launch the hadoop jobs is terrifying. We should make this easier/more intuitive
https://github.com/twitter/zipkin/blob/master/zipkin-hadoop/src/scripts/scald.rb

**Comment by franklinhu** [comment]
scald.rb was removed so this is no longer an issue.

**Comment by bmdhacks** [comment]
We should remove more things to resolve issues ;-)
