### ISSUE TITLE
Redirect not so straightforward behind HTTPS

### ISSUE THREAD

**Issue by sczizzo** [openzipkin/zipkin#1653]
So I've got Zipkin deployed behind [Hitch](https://hitch-tls.org/), a really simple TLS proxy. With Hitch, I terminate incoming HTTPS requests bound for Zipkin and forward them in the clear to the backend. With the recent change in openzipkin/zipkin#1627, however, requests bound for the application root (e.g. `https://zipkin.example.com/`) are redirected back to HTTP, not HTTPS:
```
$ curl -vsLSm5 https://zipkin.example.com
* Rebuilt URL to: https://zipkin.example.com/
*   Trying 10.10.10.10...
* Connected to zipkin.example.com (10.10.10.10) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: zipkin.example.com
> GET / HTTP/1.1
> Host: zipkin.example.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 302
< X-Application-Context: zipkin-server:shared:9411
< Location: http://zipkin.example.com/zipkin/
< Content-Language: en
< Content-Length: 0
< Date: Mon, 17 Jul 2017 18:54:50 GMT
<
* Connection #0 to host zipkin.example.com left intact
* Issue another request to this URL: 'http://zipkin.example.com/zipkin/'
* Found bundle for host zipkin.example.com: 0x7f97a34103a0
*   Trying 10.10.10.10...
* Connected to zipkin.example.com (10.10.10.10) port 80 (#1)
> GET /zipkin/ HTTP/1.1
> Host: zipkin.example.com
> User-Agent: curl/7.43.0
> Accept: */*
>
* Operation timed out after 4300 milliseconds with 0 bytes received
* Closing connection 1
curl: (28) Operation timed out after 4300 milliseconds with 0 bytes received
```

Now I could solve this for myself by, say, accepting traffic on port 80 and redirecting it to 443, but that would require introducing a reverse proxy between Hitch and Zipkin, because Hitch doesn't know about the HTTP protocol, only TCP.

An alternative, though, is to have Zipkin allow users to the configure the redirect (say, scheme or URL) or turn off this feature entirely and leave the app mounted at `/` (rather than `/zipkin`)

**Comment by codefromthecrypt** [comment]
Lazy question.. is it possible for hitch do redirect / -> /zipkin?

**Comment by sczizzo** [comment]
No, Hitch doesn't understand HTTP.

**Comment by codefromthecrypt** [comment]
@shakuzen @devinsba do either of you know any spring boot/MVC built-ins to redirect scheme aware?

**Comment by codefromthecrypt** [comment]
ps this might be helpful in figuring out what to do https://github.com/varnish/hitch/wiki/FAQ#varnish-request-coming-from-hitch-or-not

**Comment by shakuzen** [comment]
Looks like this might be related: https://stackoverflow.com/questions/3401113/spring-mvc-redirect-prefix-always-redirects-to-http-how-do-i-make-it-stay
