### ISSUE TITLE
Coding Bug leads no result found.

### ISSUE THREAD

**Issue by dumbdonkey** [openzipkin/zipkin#1661]
Hi,

Sometimes the zipkin will return none after clicking the  search button. which not the same as we expected.

After reading the source code [(CassandraSpanStore.java)](https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraSpanStore.java) . I found maybe it was a bug.

```
    if (request.spanName != null) {
      traceIdToTimestamp = getTraceIdsBySpanName(request.serviceName, request.spanName,
          request.endTs * 1000, request.lookback * 1000, traceIndexFetchSize);
    } else if (request.serviceName != null) {
      traceIdToTimestamp = getTraceIdsByServiceNames(Collections.singletonList(request.serviceName),
          request.endTs * 1000, request.lookback * 1000, traceIndexFetchSize);
    } 

    ListenableFuture<Set<Long>> traceIds;
    if (annotationKeys.isEmpty()) {
      
      traceIds = Futures.transform(traceIdToTimestamp, CassandraUtil.keyset());
    } else {
     
      for (String annotationKey : annotationKeys) {
        futureKeySetsToIntersect.add(getTraceIdsByAnnotation(annotationKey,
            request.endTs * 1000, request.lookback * 1000, traceIndexFetchSize));
      }

      // We achieve the AND goal, by intersecting each of the key sets.
      traceIds = Futures.transform(allAsList(futureKeySetsToIntersect), CassandraUtil.intersectKeySets());
    }
 
```

As the code show, we query by spanName and serviceName firstly,

then we query by annotations when they are not empty.

after that, we intersect both traceIds.

while there is some situations in which this flow won't work.

eg:

Suppose one user query traces by specified anotation and serviceName with limit param 10.

first, we queried by servicesName , suppose we got 1,2,3 

then , we queried by anotations , suppose we got 4,5,6

After intersect both traceIds,we just lost the the correct result 4,5,6.

**Comment by shakuzen** [comment]
@Mobel123 is this still an issue with the latest version? Note we have a new cassandra storage since this issue was opened. https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/cassandra

**Comment by jorgheymans** [comment]
No feedback after 18 months, if you want us to fix it please follow up on the bug report. If this is still an issue against the latest version open a new issue.
