### ISSUE TITLE
Add error count in api/v1/dependencies response

### ISSUE THREAD

**Issue by hfgbarrigas** [openzipkin/zipkin#1662]
It would be helpful to add more metadata to the current api/v1/dependencies response.
Error count should be simple to add as @adriancole mentioned.

**Comment by codefromthecrypt** [comment]
starting on this. realize this isn't probably a great first PR since it touches a lot of things!

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1675
