### ISSUE TITLE
Public Test Server

### ISSUE THREAD

**Issue by yschimke** [openzipkin/zipkin#1666]
Maybe with small rate limits and 5 minute storage. Would be great for initial testing e.g. kickstarter guides.

**Comment by basvanbeek** [comment]
Have you tried one of the methods in the quick start guide?

http://zipkin.io/pages/quickstart

If so, why would a public test server be easier than running from docker or running the self contained executable jar?

A big downside of a public test server would be getting potentially confused by it being in a multi tenant environment.

**Comment by eirslett** [comment]
I suspect it's almost just as easy to use the quickstart guide and run the docker container, either locally or just on an ad-hoc server with docker support in your development environment.
It uses in-memory storage, so no additional setup with databases etc. is required. (But it doesn't scale for production workloads, you'll need a storage solution later on.)

**Comment by codefromthecrypt** [comment]
You can use google stackdriver as a test server, though you would still
need run the proxy collector..

**Comment by codefromthecrypt** [comment]
In general, agree that quickstart is current easiest esp now that in mem
expires data.

It could be possible to add zipkin to the catalog of a cloud service like
amazon to make it ever so slightly easier.

**Comment by yschimke** [comment]
Feel free to close.  I have a zipkin docker setup on 2 home machines, I'm not against doing it. I'm mainly wondering whether it would be useful to have a server where people could explore zipkin.

**Comment by eirslett** [comment]
We should definitely keep it in mind if more people ask for a public test server (rule of 3?) but we would need infrastructure to support it, so it wouldn't be trivial.
