### ISSUE TITLE
Elasticsearch 6+ don't like type

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1676]
So, according to this summary, types are not a great idea moving forward. 

https://github.com/elastic/elasticsearch/issues/15613#issuecomment-303727982

Currently, we use the following types:
* span
* servicespan - optimization due to expensive nested service name query from our v1 span format
* dependencyLink

Seems we need to split out the types now into indexes. First thought is to simply delimit them

Ex.
* zipkin-2017-08-01/span just removes the type (as it is default)
* zipkin-2017-08-01/dependencyLink becomes zipkin-dependencyLink-2017-08-01

this is just an idea. anyone have a smarter one? @openzipkin/elasticsearch

**Comment by anuraaga** [comment]
SGTM

**Comment by ImFlog** [comment]
This seems to be the easiest thing to do.

**Comment by codefromthecrypt** [comment]
polish.. maybe since it is /dependency in the UI and api zipkin-dependencyLink-2017-08-01 -> zipkin-dependency-2017-08-01 (the link part isn't accurate anyway as it is links :) )

**Comment by xeraa** [comment]
The only minor concern is that you're tripling the number of shards; though as long as the retention is short it shouldn't be a real issue.

With a retention of 7 days and the default settings you will end up with `7 days * 3 indices * 5 shards * 2 replicas = 210 shards` and each one of them has a certain overhead of memory, file handles,...

In some scenarios it makes more sense to add a custom `type` field and to apply filters on that (that's also the migration suggestion). But I'm leaning towards 3 indices here as well.

**Comment by codefromthecrypt** [comment]
PS I'm going to make a test elasticsearch 6 image in our docker namespace so we can prove this stuff out (same rationale as our other test images: very few layers which makes things fast)

**Comment by codefromthecrypt** [comment]
I think we need to bust the old index template match

ex our old was `"template": "${__INDEX__}-*"`, which would match zipkin-2017-08-01, but also zipkin-span-2017-08-01. If an old template matches, we'll index improperly.

I think we should break it by using a different delimiter, perhaps a colon (like jaeger do, possibly for similar reasons)

ex `"template": "${__INDEX__}:span-*"`, which would match `zipkin:span-2017-08-01`, but leave the old data alone (because old data in zipkin-2017-08-01 doesn't have a prefix of zipkin:span-)

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1674 implements the new span2 model and also supports ES 6. I'll try to get this to work in such a way that the new model is optional for writes.

**Comment by codefromthecrypt** [comment]
FYI: here's an approach to consider now or later when the storage implementation dramatically differs from a prior version https://github.com/openzipkin/zipkin/issues/1679

**Comment by codefromthecrypt** [comment]
everything is all ready to go in https://github.com/openzipkin/zipkin/pull/1674

**Comment by codefromthecrypt** [comment]
Folks can play with ES 6.x using 1.29.2 which is on the way out.

If you want to use the same indexing with 2.4+, you have to set `ES_EXPERIMENTAL_SPAN2=true` as detailed in #1674. We'll formalize the mechanism for using single-type indexes in ES <6 prior to zipkin 1.30

**Comment by codefromthecrypt** [comment]
ok well ES 6.x can't work in zipkin-dependencies, yet due to elastic/elasticsearch-hadoop#1032

However, spans created with `ES_EXPERIMENTAL_SPAN2=true` on ES 2.4+ -> 5.x can once https://github.com/openzipkin/zipkin-dependencies/pull/83 is released

**Comment by codefromthecrypt** [comment]
ran into a snag with dots.. https://github.com/openzipkin/zipkin/issues/1499#issuecomment-321719394

**Comment by codefromthecrypt** [comment]
Snag with dots resolved by manually indexing queries with a non-storage index field `_q`

Starting with zipkin 1.29.3, all should work fine, notably without version constraints. For example, you no longer need minimum ES 2.4 as earlier versions of 2.0 should work fine

Internally, it just pre-encodes the valid query strings like we do with cassandra, except using equals as a delimiter as opposed to colon. Incidentally, curl queries work still, just with a little inception:

`curl -s localhost:9200/zipkin:span-2017-08-11/_search?q=_q:error=500`

Thanks very very much to @sokac for testing and finding the problem!

**Comment by codefromthecrypt** [comment]
@devinsba @jcarres-mdsol @mansu some of you requested that we take care to make formats compatible and opt-in. I took several person days effort to do that, but I haven't heard from anyone who asked if it works or not.

I'm wondering if one or more of you can test the `ES_EXPERIMENTAL_SPAN2=true` flag so that we can progress this issue?

**Comment by codefromthecrypt** [comment]
another bomb coming in ES 7 https://github.com/openzipkin/zipkin/issues/2219
