### ISSUE TITLE
Long Service Names overflow their column in trace UI

### ISSUE THREAD

**Issue by aaronyoungkash** [openzipkin/zipkin#1693]
As of version 1.27 I've noticed that my extra-long linkerd service names are overflowing into the latency breakdown, making it very hard to read.

![screen shot 2017-08-16 at 3 20 29 pm](https://user-images.githubusercontent.com/23176093/29381634-e924e860-8297-11e7-929c-f1c59321f166.png)

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1637 is at odds with this..
I don't think it expected service names so long, and generally service
names shouldn't have IPs in them as it subverts aggregation..

That said, there could well be long service names even if there
weren't variables in them. I don't know what the best action to take
would be.. should we push the timeline to the right? or truncate the
service names like we did before.. or..

cc @eirslett @fgcui1204 @klingerf @esbie for brainstorming

**Comment by aaronyoungkash** [comment]
My 2c is I'd prefer to have the column expand to fit and shove everything beside it over. Some traces already require horizontal scrolling anyway.

**Comment by klingerf** [comment]
Thanks for reporting this and looping me in! I think making the services column wider but still continuing to truncate super long service names would be a good compromise. It would also be great if truncated services could display a tooltip with the full service name. I don't think we can make guarantees about the max length of service names, unfortunately. There was some discussion about shortening the linkerd service names in linkerd/linkerd#1135, but we concluded that the current service names are the most accurate and should be kept.

**Comment by zeagord** [comment]
Long services names will be truncated and available on mouseover in the latest UI versions. https://github.com/openzipkin/zipkin/pull/2184
