### ISSUE TITLE
limit + sort works improperly

### ISSUE THREAD

**Issue by excavador** [openzipkin/zipkin#1706]
What kind of issue is this?
I am using zipkin with cassandra3 storage (version 1.30.3)

Please take a look to screenshots.
First one is "limit=10", "sort=longest first"
Second one is "limit=100", "sort=longest first"

As you can see, in the first search longest time is 1.2 second, while in second search - 14 seconds.

Seems like "filter" feature works AFTER the "limit", while expected user behavior (at least for me and for any SQL-database user) is opposite - first apply sorting and just after that - limit.

[limit=10](https://dl.dropboxusercontent.com/u/84803444/everybody/zipkin_limit_10.png)
[limit=100](https://dl.dropboxusercontent.com/u/84803444/everybody/zipkin_limit_100.png)

**Comment by codefromthecrypt** [comment]
The UI element is sorting results client side. Are you saying the client
side sort is unreliable? Or that you want all storage backends to sort data
differently before applying filters. The latter is hard due to the amount
of data involved so unlikely to land soon or for all storage options.

**Comment by excavador** [comment]
Actual behavior is useless.
How to find the longest queries for some condition?...
Seems like we need to support limit + sort processing pn storage side

**Comment by codefromthecrypt** [comment]
If you are up to making this work for all storage backends with gigabytes
orders of magnitude more data, feel free to propose a solution to
arbitrarily change order of sort and other conditions.

You can also propose to remove the client side sort.

Finally, if you know which backend you are using there may be a way to
query more arbitrarily.

Meanwhile, thanks for letting us know. All the changes we do are based on
greatest need and hands available. Knowing another person is interested in
something helps steer things.

**Comment by codefromthecrypt** [comment]
closing in favor of a related issue which is still open but has a better explanation imho #1218

**Comment by Jaware** [comment]
client side is really incorrect when the result list size is more than a few hundred,you mean we have to modify the source code ourselves?@adriancole

**Comment by Jaware** [comment]
client side sorting is really incorrect when the result list size is more than a few hundred,you mean we have to modify the source code ourselves?@adriancole

**Comment by codefromthecrypt** [comment]
@Jaware I guess I tried to say earlier that sorting as a server-side function would need to be done consistently for all backends. I'm in favor of removing the client-side sort if it is annoying you. As mentioned earlier, let's keep discussion on the older issue https://github.com/openzipkin/zipkin/issues/1218
