### ISSUE TITLE
zipkin + cassandra3 dependencies does not work

### ISSUE THREAD

**Issue by excavador** [openzipkin/zipkin#1707]
I seted up zipkin (STORAGE_TYPE=cassandra3) + zipkin cassandra docker containers  (version 1.30.3)

"Dependencies" tab show nothing.

If I setup "zipkin" docker without any options, "Dependencies" tab works fine.

**Comment by codefromthecrypt** [comment]
There is an existing issue about this you can look. cassandra3 is
incomplete, though a workaround exists.

**Comment by shakuzen** [comment]
I believe this should be resolved with latest versions now. If not, we can reopen.
