### ISSUE TITLE
How to configure Mysql as storage

### ISSUE THREAD

**Issue by edukondalugorla** [openzipkin/zipkin#1725]
Hi, i am new to zipkin,
Could you explain how to configure  mysql as storage

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#mysql-storage

Feel free to ask more on gitter. I will close this issue as we don't use
issues for q&a

https://gitter.im/openzipkin/zipkin

**Comment by ZJUgreyhaters** [comment]
What is the corresponding command for “STORAGE_TYPE=mysql MYSQL_USER=root java -jar zipkin.jar” under cmd? I succeeded in Ubuntu, but the cmd in Windows has never been successful.

**Comment by codefromthecrypt** [comment]
The key is this uses environment (system) variables. Ex in powershell
they need to be on separate lines

STORAGE_TYPE=mysql
MYSQL_USER=root
java -jar zipkin.jar

In cmd I think you need to use SET command. feel free to ask more on
gitter https://gitter.im/openzipkin/zipkin
