### ISSUE TITLE
traceId&traceIdString

### ISSUE THREAD

**Issue by cbcing** [openzipkin/zipkin#1727]
I get in trouble.

TraceId in web UI(localhost:9411) is traceIdString. example : 5282c4eb28eb478.
But traceId storaged in MySql is traceId. example : -5143342160568881582.

I want them to be consistent, such as traceId storaged in mysql is traceIdAsString rather than trancId. because i want to get a traceId(traceIdString) in mysql to search in web ui.
I saw the README.md in github, but i still dont know how to do.
someone can help me.?
thanks.

**Comment by codefromthecrypt** [comment]
Hi! So it is true we store the ids as numbers in mysql (though we store as string in elasticsearch) https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/mysql#exploring-zipkin-data

If you paste the below, it will make a string for you. You can also change the query of course. 

SELECT lower(concat(CASE trace_id_high
                        WHEN '0' THEN ''
                        ELSE hex(trace_id_high)
                    END,hex(trace_id))) AS trace_id,
       lower(hex(parent_id)) as parent_id,
       lower(hex(id)) as span_id,
       name,
       from_unixtime(start_ts/1000000) as timestamp
FROM zipkin_spans
where (start_ts/1000000) > UNIX_TIMESTAMP(now()) - 5 * 60;

**Comment by cbcing** [comment]
thank you, ^_^  @adriancole 👍

**Comment by codefromthecrypt** [comment]
no problemo! https://gitter.im/openzipkin/zipkin if you have more questions
