### ISSUE TITLE
UI should skip self-referencing trace

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1744]
the following trace will break the UI (white screen)

```
Uncaught RangeError: Maximum call stack size exceeded
    at u (traceToMustache.js:34)
    at traceToMustache.js:37
    at Array.map (<anonymous>)
    at u (traceToMustache.js:37)
    at traceToMustache.js:37
    at Array.map (<anonymous>)
    at u (traceToMustache.js:37)
    at traceToMustache.js:37
    at Array.map (<anonymous>)
    at u (traceToMustache.js:37)
```

```
curl -s localhost:9411/api/v2/spans -H 'Content-Type: application/json' -d '[
  {
    "traceId": "ade3bd64985e5693",
    "parentId": "ade3bd64985e5693",
    "id": "ade3bd64985e5693",
    "name": "offer",
    "timestamp": 1506066778476000,
    "duration": 5,
    "localEndpoint": {
      "serviceName": "offerservice",
      "ipv4": "10.139.144.225",
      "port": 8080
    },
    "annotations": [
      {
        "timestamp": 1506066778476000,
        "value": "kafka produce"
      }
    ],
    "tags": {
      "lc": "unknown"
    }
  },
  {
    "traceId": "ade3bd64985e5693",
    "parentId": "ade3bd64985e5693",
    "id": "ade3bd64985e5693",
    "name": "offer",
    "timestamp": 1506066778568000,
    "duration": 78,
    "localEndpoint": {
      "serviceName": "deliverystatus",
      "ipv4": "10.138.144.243",
      "port": 8080
    },
    "annotations": [
      {
        "timestamp": 1506066778568000,
        "value": "kafka consume"
      }
    ],
    "tags": {
      "lc": "unknown"
    }
  },
  {
    "traceId": "ade3bd64985e5693",
    "parentId": "ade3bd64985e5693",
    "id": "ade3bd64985e5693",
    "name": "offer",
    "timestamp": 1506066778624000,
    "duration": 76,
    "localEndpoint": {
      "serviceName": "offerhistory",
      "ipv4": "10.139.144.194",
      "port": 8080
    },
    "annotations": [
      {
        "timestamp": 1506066778624000,
        "value": "kafka consume"
      }
    ],
    "tags": {
      "lc": "unknown"
    }
  },
  {
    "traceId": "ade3bd64985e5693",
    "parentId": "ade3bd64985e5693",
    "id": "ade3bd64985e5693",
    "name": "offer",
    "timestamp": 1506066778569000,
    "duration": 337,
    "localEndpoint": {
      "serviceName": "event-manipulation",
      "ipv4": "10.139.144.224",
      "port": 8080
    },
    "annotations": [
      {
        "timestamp": 1506066778569000,
        "value": "Kafka consume"
      }
    ],
    "tags": {
      "lc": "unknown"
    }
  }
]'
```

**Comment by Stmated** [comment]
Quite an old entry, but is something being done about this?
My automatic Spring Boot traces add id, traceId and parentId as the same id and crashes on JavaScript-side when rendered.

**Comment by codefromthecrypt** [comment]
are you in a position where you cant upgrade whatever is doing that? seems
a rather serious bug which would make the trace useless even if it didnt
crash.

what is tracing your boot app?

**Comment by Stmated** [comment]
spring-cloud-sleuth-zipkin 2.0.0.RC1 which uses zipkin 2.6.1 -- feels relatively new to me? Though I am posting it using v1 and not v2, which I could upgrade but thought that was just the version of transport and not the content?

**Comment by codefromthecrypt** [comment]
I think you are probably sending spans to the wrong endpoint perhaps? check
that first as 2.0 writes v2 format by default and expects to go to the
/api/v2 endpoint

**Comment by Stmated** [comment]
Changing to v2 did not seem to change much. What I get in the log is:
`
2018-06-18 10:59:27.308 DEBUG 14409 --- [AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@308127b8}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : Created POST request for "http://localhost:47713/api/v2/spans"
`

`
2018-06-18 10:59:27.312 DEBUG 14409 --- [AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@308127b8}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : Setting request Accept header to [text/plain, application/json, application/*+json, */*]
`

`
2018-06-18 10:59:27.325 DEBUG 14409 --- [AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@308127b8}] o.s.c.s.z.s.ZipkinRestTemplateWrapper    : Writing [[B@64fd2c7a] as "application/json" using [org.springframework.http.converter.ByteArrayHttpMessageConverter@504db19b]
`

I do not really know how I can see that the format really is 2.0 when sent. Start it locally and listen to the traffic I guess? I'll get to that and come back later, if you don't have any other ideas?

Anyway, when I go to /api/v2/traces I see that the id, parentId and traceId are all the same.

**Comment by codefromthecrypt** [comment]
maybe you can paste the trace json (cleaning any private info) as it might
help identify what library is actually setting those things to all the same
ID? Let's carry-on here https://gitter.im/spring-cloud/spring-cloud-sleuth
and please also mention when you are on gitter if there are any
customizations we should know about.

**Comment by Stmated** [comment]
Okay, I got to debugging inside the Spring code and this is an example of what was sent:

`{"traceId":"cbe1e42bef9d80e5","id":"cbe1e42bef9d80e5","kind":"SERVER","name":"get","timestamp":1529313348187412,"duration":11847,"localEndpoint":{"serviceName":"keyservice-server","ipv4":"10.66.24.134"},"remoteEndpoint":{"ipv6":"::1","port":62797},"tags":{"error":"405","http.method":"GET","http.path":"/register","http.status_code":"405"},"debug":true,"shared":true}`

There is no parentId given here.

Something which might be the cause here is that I am running a custom Zipkin server (2.9.4), on-top of Spring Boot. I know that's not supported by the community, but did not manage to find a way how to register it with Eureka otherwise.

**Comment by codefromthecrypt** [comment]
let's use gitter as this issue isn't a good place for chat

**Comment by codefromthecrypt** [comment]
PS the lack of parent ID is fine, and shouldn't cause a circular reference. It would if the parent ID was there and was also the same as the span ID. If you have questions about the data model (which isn't sleuth related) you can hop on the normal zipkin channel here https://gitter.im/openzipkin/zipkin

**Comment by adriancole** [comment]
PS the lack of parent ID is fine, and shouldn't cause a circular reference. It would if the parent ID was there and was also the same as the span ID. If you have questions about the data model (which isn't sleuth related) you can hop on the normal zipkin channel here https://gitter.im/openzipkin/zipkin

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2109 should end up killing this in the next release
