### ISSUE TITLE
zipkin mysql request timeout

### ISSUE THREAD

**Issue by eshujiushiwo** [openzipkin/zipkin#1746]
Hey guys

i`ve met a problem when i trying get data from the zipkin-ui.

`Cannot store spans [34ddfb7bbb28d076.67dc18dedd736d2b<:67dc18dedd736d2b] due to RuntimeException(java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30003ms.) 
`
The logs are below：

[zipkin.log](https://github.com/openzipkin/zipkin/files/1331397/zipkin.log)

**Comment by codefromthecrypt** [comment]
You have hit max connections. You might want to monitor zipkin metrics and
possibly increase the connection count above 10
https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md if
this is a volume problem you might habe a separate instance for query vs
collector (same code)

Hard to tell what the connections are doing. Some normal practice such as
thread dumps could tell. Check to see if messages are being dropped or
threads are hung. Restart is likely needed.

**Comment by eshujiushiwo** [comment]
@adriancole 
That`s very kind of you.
Thanks a lot, i`ve set MYSQL_MAX_CONNECTIONS to 30.
But still shows that problem .

Should i change the storage to cassandra?

**Comment by codefromthecrypt** [comment]
maybe hop onto https://gitter.im/openzipkin/zipkin ?

there are different storage options like cassandra and elasticsearch, and
choices depend on what you are comfortable running. You can try different
ones but you also might need to look at your ingest rate and if you need to
adjust sampling etc.

**Comment by jorgheymans** [comment]
question answered, mysql is not for high volume sites.
