### ISSUE TITLE
RabbitMQ integration test fails on Travis

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1748]
We currently have a rabbitmq service added to travis config because the test-containers config fails with connect errors.

**Comment by jorgheymans** [comment]
@adriancole @shakuzen anything needs doing here still or are we ok with the rabbitmq service in travis config ?

**Comment by jorgheymans** [comment]
Roger, time to close this one.

![roger-rabbit](https://user-images.githubusercontent.com/193792/82499508-0e3f1600-9af2-11ea-8616-be8538d4839d.jpg)

**Comment by shakuzen** [comment]
Sorry for the lack of reply. We'd have to see if the latest versions of things (testcontainers, rabbitmq, travis) have magically fixed the problem or if more investigation is needed. It's not high priority though since we can use the travis service in the meantime.

**Comment by jorgheymans** [comment]
Ok so it's in the same category as this then, https://github.com/openzipkin/zipkin/issues/2781 . Probably still worth a look then, reopening.
