### ISSUE TITLE
how yo use zipkin with elasticsearch?

### ISSUE THREAD

**Issue by winrunwang** [openzipkin/zipkin#1750]
hello,everyone 
    i know how to use zipkin with mysql..but elasticsearch ,i don't know ,can everyone help me?

**Comment by codefromthecrypt** [comment]
can you join https://gitter.im/openzipkin/zipkin ?

in short, you replace STORAGE_TYPE=mysql for STORAGE_TYPE=elasticsearch

https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#elasticsearch-storage

**Comment by kahootali** [comment]
@adriancole I am using Elastic search cluster on Azure, how can I configure to send my traces from Zipkin there? And I want to persist the data

**Comment by jcchavezs** [comment]
@adriancole shall we close this?
