### ISSUE TITLE
Feature Request: Allow longer zipkin span names

### ISSUE THREAD

**Issue by pennstatephil** [openzipkin/zipkin#1751]
Currently, "name" in the database is limited to 255 characters. We have some REALLY long URLs (I know it's not ideal) and this causes a SQL exception:

`[ZipkinMySQLStorage-1] zipkin.server.ZipkinHttpCollector        : Cannot store spans [bc4e3b8f7025cbde.aff2ed227e2cea87<:bc4e3b8f7025cbde, bc4e3b8f7025cbde.aff2ed227e2cea87<:bc4e3b8f7025cbde, 4bad878142e4c587.069ffdef649e62c4<:c603f78125156b83, 4bad878142e4c587.c603f78125156b83<:4bad878142e4c587] due to DataAccessException(SQL [null]; Data truncation: Data too long for column 'name' at row 1)`

Trying to increase the field ourselves causes a key length error:

`17:07:35	alter table zipkin.zipkin_spans modify column name varchar(400)	Error Code: 1071. Specified key was too long; max key length is 767 bytes	0.00033 sec`

Is there any way to get a longer name supported? If not, is there a recommended practice we can follow to work around the issue?

**Comment by codefromthecrypt** [comment]
URLs tend to be a bad choice for span names as they end up with variable
names in them (which explodes the cardinality). Do you have very long span
names that don't have variables encoded? In general, we default to method
name, or where supported the associated RPC name (ex method name)

**Comment by codefromthecrypt** [comment]
meant "RPC name (ex function name)"

**Comment by pennstatephil** [comment]
On further inspection, this is an issue with the way Spring Cloud Sleuth picks span names:

TraceFilter.java line 136:
`String name = HTTP_COMPONENT + ":" + uri;`

When "uri" is really long, we start seeing these issues. I can migrate this issue over to that project... Or, is there an easy way to override the span name?

edited to add: looks like it's been reported here: https://github.com/spring-cloud/spring-cloud-sleuth/issues/500

**Comment by codefromthecrypt** [comment]
This issue was moved to spring-cloud/spring-cloud-sleuth#723

**Comment by codefromthecrypt** [comment]
sleuth has means to change the naming convention, you can peek at docs or hop on gitter to ask about it https://gitter.im/spring-cloud/spring-cloud-sleuth
