### ISSUE TITLE
Bug : Zipkin and Consul properties are mixed, cause errors

### ISSUE THREAD

**Issue by Gandalf1** [openzipkin/zipkin#1761]
BUG:
When using Zipkin and Consul the service name uses the Consul registered name and if the `zipkin.service.name` is set, it causes Consul errors

`[o.s.c.c.d.ConsulDiscoveryClient] : Unable to locate service in consul agent: my-service-91828f2f88f18c3fadf193bfa3ad6d1f`

This is problematic because Zipkin is much more useful finding traces if a service, even if many of the same service are deployed in a cluster (i.e. Docker/Rancher), would register it's simple sping.application.name, rather than the randomized one.

To replicate:
On a service that uses Consul, Sleuth, and Zipkin set the zipkin.service.name, you will see the errors after the service has started.

**Comment by jorgheymans** [comment]
This one slipped through the maze it seems, did you ever find a resolution to this ?

**Comment by Gandalf1** [comment]
That was almost 3 years ago - have since moved on from that project.  No
idea if this was ever fixed.

**Comment by jorgheymans** [comment]
Ok thanks for the quick feedback ! 

I'll close this issue, both zipkin and sleuth have evolved quite a bit since then and nobody seemed to have struggled with the same problem.

**Comment by codefromthecrypt** [comment]
fyi If you need zipkin to self-register in consul, please open an issue.
