### ISSUE TITLE
zipkin APM agent monitor TIBCO BW

### ISSUE THREAD

**Issue by prashantnitt07** [openzipkin/zipkin#1767]
hi,
can be deploy zipkin TIBCO BW . please check and reply ,

We have four type to JAVA based ..

Tomcat
Weblogic
Jboss
TIBCO BW
please reply all 4 java type supported

------------------------------------
what is step for installation of ZIPKIN on linux machine .
please send me step or guide document

**Comment by codefromthecrypt** [comment]
dupe of https://github.com/openzipkin/openzipkin.github.io/issues/62

**Comment by raymrg** [comment]
Hi,

Did you manage to integrate BW to ZipKin? I am investigating a similar solution and your input would be appreciated.

Thanks

**Comment by codefromthecrypt** [comment]
servlet, spring boot and dropwizard based applications all have
instrumentation available. We don't have instrumentation at the container
layer, such as tomcat or any other thing at the moment. What this means is
tracing is configured at the app layer (ex servlet filter). Definitely
tomcat is fine and I've heard of folks using WebLogic. It is almost
certainly the case folks are using JBoss with brave. I don't know about
Tibco BW. https://github.com/openzipkin/brave-webmvc-example
