### ISSUE TITLE
There should be an optional lower time bound for fetching traces

### ISSUE THREAD

**Issue by mosesn** [openzipkin/zipkin#177]

**Comment by rtyler** [comment]
@mosesn if this is still important to you, would you mind elaborating on what you mean? What would the ideal acceptance criteria be?

**Comment by mosesn** [comment]
If I want to be able to look at traces which are between 5PM and 7PM today, because there was an incident and I want to investigate it, I can't do that.  If there are 10K traces, and it just gives me 100 uniformly distributed from the past five days, probably very few of them will be in that 2 hour timespan.

**Comment by eirslett** [comment]
I think this is already implemented.
