### ISSUE TITLE
Minor compatibilty issue with ScyllaDB

### ISSUE THREAD

**Issue by hexchain** [openzipkin/zipkin#1770]
I've been running Zipkin with ScyllaDB (a high-performance Cassandra 2.x implementation) for some time. Currently, there are some minor issue:

1. `CassandraSpanStore` gets initialized for every API request, and Scylla complains about preparing the same statement multiple times.
2. Scylla claims to support protocol v4 but does not support some queries (according to https://github.com/scylladb/scylla/issues/2473, used in [this line](https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraSpanStore.java#L160)). And because of 1, all API requests fail due to the unsupported PreparedStatement and the UI is unusable. Since nowhere in the UI allows querying multiple service names, I simply disabled that statement so that UI worked again.

**Comment by emmanuel** [comment]
@hexchain I am interested in using ScyllaDB as a backend for Zipkin, but I haven't started working on it yet. 

Have you published your fork with the disabled statement anywhere? Was the scope of the change literally just commenting out the [`session.prepare` call](https://github.com/openzipkin/zipkin/blob/eeeeb3c02b0e0c578eb36c08d80cf2bf400067fc/zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraSpanStore.java#L160-L168)?

**Comment by emmanuel** [comment]
Looking at this a little more, it seems more like you needed to switch from the `IN` clause to a strict equality query, here on the `service_name` key: https://github.com/openzipkin/zipkin/blob/eeeeb3c02b0e0c578eb36c08d80cf2bf400067fc/zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraSpanStore.java#L163

Is that more like it?

**Comment by hexchain** [comment]
@emmanuel It was a very dirty fix: just replace the `else` block with `selectTraceIdsByServiceNames = null;`.

**Comment by codefromthecrypt** [comment]
hi, can you check the new storage implementation vs ScyllaDB? probably will make more sense to focus on that. The storage type is "cassandra3" and its code is under zipkin-storage/zipkin2_cassandra

**Comment by eirslett** [comment]
If we're going to support ScyllaDB I suggest we should run integration tests against it. Somebody would need to set up Travis with ScyllaDB.

**Comment by hexchain** [comment]
@adriancole Scylla only claims to be a Cassandra 2 implementation. Is there any known protocol difference between Cassandra 2 and 3?

Plus, do I have to upgrade all client to make them generate v2 spans?

**Comment by codefromthecrypt** [comment]
>
> @adriancole <https://github.com/adriancole> Scylla only claims to be a
> Cassandra 2 implementation. Is there any known protocol difference between
> Cassandra 2 and 3?
>
It is a combination of v4 protocol and SASI indexing. Is there a layering
solution for SASI with Scylla?


> Plus, do I have to upgrade all client to make them generate v2 spans?
>
Nope. All recent versions of zipkin will convert depending on the
underlying backend (Ex v1 -> v2 or v2 -> v1) no client change is needed,
though upgrading to a client that supports v2 model is good long term.

**Comment by hexchain** [comment]
> It is a combination of v4 protocol and SASI indexing. Is there a layering
> solution for SASI with Scylla?

Not that I know of. According to http://www.scylladb.com/2017/07/27/materialized-views-preview-scylla-2-0/ and https://github.com/scylladb/scylla/issues/2203, Scylla does not support SASI.

> Nope. All recent versions of zipkin will convert depending on the
> underlying backend (Ex v1 -> v2 or v2 -> v1) no client change is needed,
> though upgrading to a client that supports v2 model is good long term.

Good to know!

**Comment by codefromthecrypt** [comment]
>
> Not that I know of. According to http://www.scylladb.com/2017/
> 07/27/materialized-views-preview-scylla-2-0/ and scylladb/scylla#2203
> <https://github.com/scylladb/scylla/issues/2203>, Scylla does not support
> SASI.
>
>

opened https://github.com/openzipkin/zipkin/issues/1805

**Comment by codefromthecrypt** [comment]
any updates here?

**Comment by jorgheymans** [comment]
@hexchain @emmanuel final call, are any of you still using scylladb as storage backend for zipkin ?

**Comment by hexchain** [comment]
I no longer work with Zipkin or ScyllaDB, sorry.

**Comment by mkorolyov** [comment]
Latest version(type=cassandra3) is not working with ScyllaDB either. The problem remains the same - incompatibility with missing SASI. Btw Cassandra decided to decommission SASI. it is already in the experimental features list and will be totally removed from Cassandra 6.0.
