### ISSUE TITLE
how to bind ip address when starting server with "java -jar zipkin.jar"

### ISSUE THREAD

**Issue by layao** [openzipkin/zipkin#1772]
my machine has two ip address, how can i bind ip address when start zipkin server?

**Comment by codefromthecrypt** [comment]
the server is spring boot. I believe you can use env SERVER_ADDRESS or any
other way spring boot accepts config
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-multi-profile-yaml

**Comment by layao** [comment]
I have solved this problem. Thanks a lot!
