### ISSUE TITLE
Make collapse button work by default

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1774]
Currently, the UI defaults to expand all, which implicitly selects all services like so..

<img width="986" alt="screen shot 2017-11-01 at 4 01 14 pm" src="https://user-images.githubusercontent.com/64215/32260743-ee6949ca-bf1d-11e7-87d7-1cd3a3415c2f.png">

When this is in place, you cannot collapse a the calls under root (clicking on the + just blinks red in the top-left corner).

Conversely, if you click Collapse All, then expand root, you can now collapse the child

<img width="994" alt="screen shot 2017-11-01 at 4 02 47 pm" src="https://user-images.githubusercontent.com/64215/32260779-29ce1b26-bf1e-11e7-9ee6-331bb688d7ea.png">

If you look closely, the difference is that in the Collapse All, both services are not highlighted. Looking at the trace.js, hide is muted when the service is in the filtered list

```javascript
function hideSpan(span) {
  if (span.inFilters > 0 || span.openChildren > 0 || span.openParents > 0) return;
  span.hide();
}
``` 

Probably, the default should be similar to clicking Collapse All, click + as intuitively, someone would like to be able to hide parts of the tree. This is especially important in large traces. Thanks to @sigerber for reporting this!

**Comment by victorlin-houzz** [comment]
Love to see the change asap.

**Comment by codefromthecrypt** [comment]
can someone paste a reasonably complex trace? simply removing the `span.inFilters > 0` makes the box work again, but it would be ideal to have a trace with several services and multiple levels of nesting to ensure this works cc @igorwwwwwwwwwwwwwwwwwwww

**Comment by codefromthecrypt** [comment]
we have a large trace now.. in the zipkin-ui/testdata area

**Comment by jorgheymans** [comment]
Was resolved, in any case zipkin-classic is no longer maintained.
