### ISSUE TITLE
Display span name on the list of traces

### ISSUE THREAD

**Issue by lhsm** [openzipkin/zipkin#1775]
Hi.
It would be useful to display first span name of the trace on the list of traces.
Thanks

**Comment by shakuzen** [comment]
I also think this would be useful. What does everyone else think?

**Comment by jorgheymans** [comment]
Lens has you covered :+1: 

![image](https://user-images.githubusercontent.com/193792/79001797-73950400-7b4f-11ea-98ec-0070a85435b3.png)
