### ISSUE TITLE
Cannot read property 'timestamp' of undefined

### ISSUE THREAD

**Issue by lhsm** [openzipkin/zipkin#1776]
Hi.
Zipkin UI starts with error 
`error_handler.js?934c:54 EXCEPTION: Cannot read property 'timestamp' of undefined
ErrorHandler.handleError @ error_handler.js?934c:54
error_handler.js?934c:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js?934c:59
error_handler.js?934c:60 TypeError: Cannot read property 'timestamp' of undefined
    at eval (webpack-internal:///165:117:70)
    at Array.sort (native)
    at Array.sort (webpack-internal:///875:21:15)
    at Trace.sortTrace (webpack-internal:///165:117:23)
    at eval (webpack-internal:///165:120:23)
    at Array.forEach (<anonymous>)
    at Trace.sortTrace (webpack-internal:///165:119:27)
    at eval (webpack-internal:///165:120:23)
    at Array.forEach (<anonymous>)
    at Trace.sortTrace (webpack-internal:///165:119:27)
    at Trace.getSortedSpans (webpack-internal:///165:80:14)
    at new Trace (webpack-internal:///165:55:32)
    at eval (webpack-internal:///165:157:65)
    at Array.map (<anonymous>)`
If i understand correctly expected structure of traces (response of `api/v1/traces`) is `..{"traceId": "trace", ..., "**annotations**"} ..` - annotations is mandatory.
But in my case trace looks like `[
    [
        {
            "traceId": "fca49abacae88255",
            "id": "fca49abacae88255",
            "name": "",
            "timestamp": 1509704101447000,
            "duration": 55875,
            "annotations": [
                {
                    "timestamp": 1509704101502875,
                    "value": "ss",
                    "endpoint": {
                        "serviceName": "",
                        "ipv4": "",
                        "port": 8080
                    }
                }
            ]
        },
        {
            "traceId": "fca49abacae88255",
            "id": "8382a3fc6365f507",
            "name": "",
            "parentId": "fca49abacae88255",
            "timestamp": 1509704101455000,
            "duration": 22310,
            "binaryAnnotations": [
                {
                    "key": "OUTPUT_MESSAGE",
                    "value": "",
                    "endpoint": {
                        "serviceName": "",
                        "ipv4": "",
                        "port": 8080
                    }
                },
                {
                    "key": "lc",
                    "value": "unknown",
                    "endpoint": {
                        "serviceName": "",
                        "ipv4": "",
                        "port": 8080
                    }
                }
            ]
        }
    ]
]
`
"Traditional" ui works fine with that trace

**Comment by codefromthecrypt** [comment]
Sounds familiar to me.. are you running latest?

**Comment by asyd** [comment]
Same issue here with the latest version of `openzipkin/zipkin-ui` docker image

**Comment by codefromthecrypt** [comment]
This could be a bug, when all labels are empty or unknown. Is it
intentional that you have a trace with no service or span name?

**Comment by codefromthecrypt** [comment]
oh you are referring to https://github.com/openzipkin/zipkin-ui

someone can fix the bug, but the project is likely to be canceled because no one has been maintaining it.. see also https://github.com/openzipkin/zipkin/issues/1577 and https://github.com/openzipkin/docker-zipkin/issues/160

At any rate, this issue should be moved to https://github.com/openzipkin/zipkin-ui

**Comment by lhsm** [comment]
Sorry, i mixed up the target project. Create one https://github.com/openzipkin/zipkin-ui/issues/42 just in case
Thanks
