### ISSUE TITLE
Setting environment name via environment variable

### ISSUE THREAD

**Issue by simondean** [openzipkin/zipkin#1783]
It’s great how much Zipkin config can be set via environment variables. At the moment it’s not possible to set the environment name shown in the Zipkin UI. 

https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/resources/zipkin-server-shared.yml#L130

Would it be possible to add an end bar for setting the environment name/label?

**Comment by codefromthecrypt** [comment]
you mean ZIPKIN_UI_ENVIRONMENT=foo doesn't work?

**Comment by codefromthecrypt** [comment]
lemme know if the suggestion didn't work
