### ISSUE TITLE
Cannot decode spans

### ISSUE THREAD

**Issue by liugj** [openzipkin/zipkin#1787]
wget -O zipkin.jar 'https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec'
java -jar zipkin.jar

request
``
curl  -H "Expect:" -H "Content-Type:application/json"  -d '[{"traceId":"203e61853bd419ee","name":"php_curl","version":"php-4","id":"1.1","timestamp":1510299948487949,"duration":5336,"annotations":[{"value":"cs","timestamp":1510299948487949,"endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}},{"value":"cr","timestamp":1510299948493285,"endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}}],"binaryAnnotations":[{"key":"http.url","value":"http:\/\/localhost:12345\/","endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}},{"key":"error","value":"Failed to connect to localhost port 12345: Connection refused","endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}}]},{"traceId":"203e61853bd419ee","name":"cli","version":"php-4","id":"1","timestamp":1510299948487872,"duration":5476,"annotations":[{"value":"sr","timestamp":1510299948487872,"endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}},{"value":"ss","timestamp":1510299948493348,"endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}}],"binaryAnnotations":[{"key":"path","value":"-","endpoint":{"serviceName":"php_test","ipv4":"10.0.2.15"}}]}]' http://127.0.0.1:9411/api/v1/spans
 
``
response
```
Cannot decode spans
```

**Comment by liugj** [comment]
I find the answer 'id' and `parentId` length must be equal 16

**Comment by codefromthecrypt** [comment]
cool. Just following up, if you enable server log debug you can see this error

Ex.
```
java -jar zipkin.jar  --logging.level.zipkin=DEBUG --logging.level.zipkin2=DEBUG
```

produces
```
2017-11-12 19:27:49.527 DEBUG 37505 --- [nio-9411-exec-1] zipkin.server.ZipkinHttpCollector        : Cannot decode spans due to IllegalArgumentException(1.1 should be a 1 to 32 character lower-hex string with no prefix reading List<Span> from json)

java.lang.IllegalArgumentException: 1.1 should be a 1 to 32 character lower-hex string with no prefix reading List<Span> from json
```

**Comment by liugj** [comment]
yes ,thank you very much!
