### ISSUE TITLE
zipkin's v2 REST API doesn't work well with elasticsearch-storage

### ISSUE THREAD

**Issue by owenliang** [openzipkin/zipkin#1790]
I post spans to zipkin following the API listed here: [Zipkin’s v2 api](http://zipkin.io/zipkin-api/#/), there is a  span stored in Elasticsearch looks like this:

```
      {
        "_index" : "zipkin:span-2017-11-12",
        "_type" : "span",
        "_id" : "AV-vfw65QXyBEEiRZzUY",
        "_score" : 1.0,
        "_source" : {
          "traceId" : "00055dc5884e341d",
          "localEndpoint" : {
            "serviceName" : "b.service.com",
            "ipv4" : "192.168.1.200",
            "port" : 80
          },
          "debug" : true,
          "kind" : "SERVER",
          "name" : "/method_of_b",
          "annotations" : [
            {
              "timestamp" : 1510477860320575,
              "value" : "sr"
            },
            {
              "timestamp" : 1510477860523920,
              "value" : "ss"
            }
          ],
          "id" : "00055dc5884e353b",
          "parentId" : "00055dc5884e3535"
        }
      }
```

But the zipkin web UI doesn't list the service named "b.service.com", so I use tcpdump to capture the request from zipkin to es.

The request shows an agg query group by annotations.endPoint.serviceName, but the span in es has only localEndPoint.serviceName but not annotations.endPoint.serviceName.

Is this a bug or v2 API not compatible with elasticsearch storage?How to solve it, 3Q.

**Comment by codefromthecrypt** [comment]
guessing this is because span.timestamp isn't set ("sr", "ss" aren't used
in v2 format. timestamp/duration are)

**Comment by owenliang** [comment]
@adriancole Thanks man, It works. 

[V2 API](http://zipkin.io/zipkin-api/#/default/post_spans)

> Zipkin v1 core annotations such as “cs” and “sr” have been replaced with
> Span.Kind, which interprets timestamp and duration.
