### ISSUE TITLE
can't get dependencies

### ISSUE THREAD

**Issue by yzfshuijing** [openzipkin/zipkin#1791]
I'v used the same code to report info to zipkin server,  if I used kafka+es, I found that I could not get the dependencies, but if I changed the storage to in memory it could work
is that the es can't support getDependencies?

**Comment by yzfshuijing** [comment]
@adriancole

**Comment by MrGlaucus** [comment]
see this [zipkin-dependencies](https://github.com/openzipkin/zipkin-dependencies)

**Comment by yzfshuijing** [comment]
@MrGlaucus thanks
if I want to getDependencies ，I should execute STORAGE_TYPE=elasticsearch ES_HOSTS=host1:9201 java -jar zipkin-dependencies.jar
is there a way to make zikin-server and zikpin-dependencies work together ？not to execute the command everytime？

**Comment by MrGlaucus** [comment]
im working on this now. But you only need to run this jar once on your server, it's a scheduled job.

**Comment by MrGlaucus** [comment]
@yzfshuijing im working on this now. At present, you can make a it a scheduled job in zipkin-server.

**Comment by yzfshuijing** [comment]
ok，thank you so much @MrGlaucus

**Comment by codefromthecrypt** [comment]
PS this can be done for a small amount of data in the server. The problem
(and reason why there is a spark job) is because a large amount of data
usually implies crashing the server to try and load a days worth.
