### ISSUE TITLE
zipkin-ui does not support non-shared spans

### ISSUE THREAD

**Issue by devinsba** [openzipkin/zipkin#1799]
Feature Request

With the advent of the X-Ray compatible modes for zipkin/brave comes the fact that X-Ray spans (segments) are not shared by client and server so the UI ends up losing the hierarchy information. It still orders correctly because of timestamps. I would be great to support this model of spans in the native zipkin UI

**Comment by codefromthecrypt** [comment]
>
> With the advent of the X-Ray compatible modes for zipkin/brave comes the
> fact that X-Ray spans (segments) are not shared by client and server so the
> UI ends up losing the hierarchy information. It still orders correctly
> because of timestamps. I would be great to support this model of spans in
> the native zipkin UI
>
I suspect this is related as well (notably the parent isn't propagated)
https://github.com/openzipkin/zipkin/pull/1745

**Comment by codefromthecrypt** [comment]
possibly a dupe of #963?

**Comment by codefromthecrypt** [comment]
In the current api, I think maybe cheapest win is fusing single-host spans together. Basically move the server span into its client and adjust ids. However, I think possibly there's something more to ask you about.

You suggest the hierarchy is wrong.. which is a different problem then seeing things in the same detail screen. Can you give an example of this? It would seem a broken hierarchy would also be a problem in X-Ray..

**Comment by codefromthecrypt** [comment]
please take a look at https://github.com/openzipkin/zipkin/pull/2302 and let me know if this is still desirable!

**Comment by codefromthecrypt** [comment]
the logic has been completely written and so has the UI, so it might be easier to notice any new problem vs think through what's changed

**Comment by codefromthecrypt** [comment]
one note relevant here is that lens allows multiple spans to be expanded which compensates somewhat for usability concerns on client and server spans that don't share an ID. I'm not sure it is worse than other tools like jaeger or stackdriver in this regard or not.
