### ISSUE TITLE
Disable "Find Traces" on Zipkin UI and allow navigation to trace only through traceID

### ISSUE THREAD

**Issue by codingzombie** [openzipkin/zipkin#1800]
I'm looking to disable search (a.k.a clicking on Find Traces) on zipkin UI. I want users to only be able to navigate to trace page with traceID. Is this possible? I'm not sure how to block homepage, but let access to https://zipkin.<..>/traces/<..>. Is there a config?

**Comment by codefromthecrypt** [comment]
There's no such setting at the moment. We only have an option to disable the UI completely.

If we did have an option like this, it would apply to all users as we have no means to identify one. Note that they could still access the api directly, as the api is ultimately what presents the search capability.

We could gracefully handle when the api returns unauthorized.. For example, the UI begins with a query against the api services endpoint. If this returns unauthorized, we could possibly guess that someone has disabled exploration, then only present the get trace by ID screen.

Before we go there, though, probably maybe elaborate on your end goal and how you plan to enforce it?

cc @jonathan-lo @sirtyro

**Comment by codingzombie** [comment]
Thank you!

I want to disable search because our backend Cassandra is unable to handle
the load. But one useful feature is going to tracepage directly with
traceid which developers have it handy. Blocking search page for all users
is okay in my case.

**Comment by codefromthecrypt** [comment]
>
> I want to disable search because our backend Cassandra is unable to handle
> the load. But one useful feature is going to tracepage directly with
> traceid which developers have it handy. Blocking search page for all users
> is okay in my case.

do you know the source of the load? Is it a particular query? Which
cassandra implementation are you using?
maybe we can help?

**Comment by bplotnick** [comment]
Is this solved by https://github.com/openzipkin/zipkin#disabling-search now?

**Comment by codefromthecrypt** [comment]
yep!
