### ISSUE TITLE
Migrate UI to use v2 API endpoints

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/zipkin#1802]
v2 API endpoints are now available for the v2 span format, but the UI still uses the v1 API endpoints, and consequently the v1 span format. It would be good if the UI were v2 native like other components are now.

**Comment by apei830** [comment]
I just looked into the source code, I found that ZipkinQueryApiV2 won't be loaded, and I tried the url in browser http://localhost:9411/zipkin/api/v2/services, got 404 error, so I guess that the v2 UI is not ready yet. :)

**Comment by shakuzen** [comment]
@apei830 I ran into the same thing, but the V2 API is in fact in place and intentionally not available under `/zipkin` because that is for the UI. Recent Gitter chat log:

> Tommy Ludwig @shakuzen 18:09
> I noticed the v2 query endpoints are from the root while v1 are from /zipkin. Concretely, this works:
> http://localhost:9411/zipkin/api/v1/trace/c204854ddf6e4a72
> this gets a 404:
> http://localhost:9411/zipkin/api/v2/trace/c204854ddf6e4a72
> this works:
> http://localhost:9411/api/v2/trace/c204854ddf6e4a72
> 
> Adrian Cole @adriancole 18:10
> anything about api being under /zipkin is basically accident of UI mounting

**Comment by apei830** [comment]
Hi shakuzen,

Please refer to the source code of ZipkinUiAutoConfiguration
https://github.com/openzipkin/zipkin/blob/master/zipkin-autoconfigure/ui/src/main/java/zipkin/autoconfigure/ui/ZipkinUiAutoConfiguration.java

  /** The UI looks for the api relative to where it is mounted, under /zipkin */
  @RequestMapping(value = "/zipkin/api/v1/**", method = GET)
  public ModelAndView forwardApi(HttpServletRequest request) {
    String path = (String) request.getAttribute(PATH_WITHIN_HANDLER_MAPPING_ATTRIBUTE);
    return new ModelAndView("forward:" + path.replaceFirst("/zipkin", ""));
  }

it seems that all request under /zipkin/api/vi/** will be forward to the path /api/vi/**

**Comment by apei830** [comment]
@shakuzen 
;)

**Comment by codefromthecrypt** [comment]
hehe you are both right :)

the /zipkin path is only for the UI, and yes it isn't ready for v2 yet
because of this issue. I'd love it to be v2 ready, so pull requests welcome.

I was mentioning to tommy bc I thought the context was about routine api
use. IOTW, routine api users shouldn't depend on the /zipkin path as some
deployments disable the UI and would then disable this mapping

**Comment by codefromthecrypt** [comment]
#1818 forwards the api root

**Comment by codefromthecrypt** [comment]
added #2217 to actually use v2 data internally now that we are consuming it
