### ISSUE TITLE
Investigate making SASI optional

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1805]
In the "cassandra3" storage type (zipkin2_cassandra directory), SASI is used for resolving annotationQuery. SASI moves write amplification internal to cassandra, and substantially decreases write performance. Moreover, some environments do not yet support this (See #1770 for ScyllaDB). We don't want a scenario where people perpetually use the old cassandra storage type as it doubles our maintenance burden.

One thought is to make it possible to use the "cassandra3" type without SASI. In simplest scenario, this could imply no support for annotationQuery when that's the case. This might allow for partial support of ScyllaDB until it has a SASI option.

cc @openzipkin/cassandra

**Comment by michaelsembwever** [comment]
One idea is here is that one could simply and elegantly execute in `cqlsh` the following:
```
DROP INDEX zipkin2.traces_annotation_query_idx ; 
DROP INDEX zipkin2.traces_l_service_idx ;
```
and annotation searches in the UI would silently fail (simply returning no result or a simple explanation that such searches have been disabled).

Dropping these indexes can improve write throughput ten or twenty fold. So it's not just about supporting ScyllaDB but also providing an expert mode for those that really want to push how many spans per second they are collecting (eg hundreds of thousands per second ++).

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1876 will fix this (still needs a bit of work to make the schema install not add the indexes vs just not use them)
