### ISSUE TITLE
zipkin use elasticsearch storage

### ISSUE THREAD

**Issue by xiaoxinba** [openzipkin/zipkin#1813]
my elasticsearch have zipkin:span* index data, but when i start zipkin-ui and zipkin-server ,i can not get data in zipkin-ui?
start zipkin:  
   java -DKAFKA_ZOOKEEPER=xxx -DSTORAGE_TYPE=elasticsearch -DES_HOSTS=xxx -jar ./zipkin-server/target/zipkin-server-*exec.jar
  proxy=http://localhost:9411/zipkin/ ./npm.sh run dev

why? please help!!

**Comment by codefromthecrypt** [comment]
please join gitter for help https://gitter.im/openzipkin/zipkin

troubleshooting isn't easy with github issue
