### ISSUE TITLE
Invalid MD5 checksums, GPG signatures on -exec artifacts

### ISSUE THREAD

**Issue by abesto** [openzipkin/zipkin#1819]
All `zipkin-server-$VERSION-exec.jar` artifacts on BinTray have an invalid MD5 sum and GPG signature. Other jars (checked only the `zipkin-server-$VERION.jar` files) seem to be fine.

Script to reproduce by checking for all versions, MD5 sum only (manually checked a few GPG signatures):

```sh
#!/bin/bash

set -euo pipefail
set -x

fetch() {
  version="$1"; shift
  suffix="$1"; shift
  url="https://dl.bintray.com/openzipkin/maven/io/zipkin/java/zipkin-server/$version/zipkin-server-$version$suffix.jar"
  filename="zipkin-server-$version$suffix.jar"
  curl -o "$filename" "$url"
  echo "$(curl -s "$url.md5")  $filename" >> checksums
}

: > checksums
versions="$(curl -s https://bintray.com/api/v1/packages/openzipkin/maven/zipkin | jq '.versions | join("\n")' -r)"
for version in $versions; do
  fetch $version ''
  fetch $version -exec
done

md5sum --check checksums
```

Output from my run: https://gist.github.com/abesto/3e18dd2eee8586729508a5f3b0cd5bb0

The last few lines, representative of the rest:

```
zipkin-server-0.4.4.jar: OK
zipkin-server-0.4.4-exec.jar: FAILED
zipkin-server-0.4.3.jar: OK
zipkin-server-0.4.3-exec.jar: FAILED
md5sum: WARNING: 16 lines are improperly formatted
md5sum: WARNING: 136 computed checksums did NOT match
```

**Comment by codefromthecrypt** [comment]
Thanks for noticing.

**Comment by codefromthecrypt** [comment]
± |master ?:4 ✗| → md5 ~/Downloads/zipkin-server-2.4.0-exec.jar
MD5 (/Users/acole/Downloads/zipkin-server-2.4.0-exec.jar) = 7870d5571638f4c5940ac1153e647e8f

 2017-11-27 19:13:06 ⌚  acole in ~/oss/docker-zipkin
± |master ?:4 ✗| → cat ~/Downloads/zipkin-server-2.4.0-exec.jar.md5 
7870d5571638f4c5940ac1153e647e8f

all good
