### ISSUE TITLE
elasticsearch connect error

### ISSUE THREAD

**Issue by Jaware** [openzipkin/zipkin#1820]
zipkin 1.31.3,ES 5.6
my zipkin config ES_HOSTS is: 10.11.31.189:9200,10.11.33.219:9200
when query ,the error below occured:
Error executing query: java.net.ConnectException: Failed to connect to /10.11.33.219:62951
my cnfig is wrong?

**Comment by codefromthecrypt** [comment]
doesn't make sense to me unless somehow there is a redirect.

PS there have been a number of unrelated but important changes to ES
storage between 1.31 and now. you should look at upgrading.

**Comment by Jaware** [comment]
wrong on  mac,linux ok
