### ISSUE TITLE
same artifactId for different modules can't distribute in the same dir

### ISSUE THREAD

**Issue by asereda-gs** [openzipkin/zipkin#1830]
Hello,

The following modules have identical `artifactId` (named `zipkin.jar`) but with different classes : 
1. `io.zipkin.java:zipkin` ([pom.xml](https://github.com/openzipkin/zipkin/blob/master/zipkin/pom.xml))
2. `io.zipkin.zipkin2:zipkin` ([pom.xml](https://github.com/openzipkin/zipkin/blob/master/zipkin2/pom.xml))

I can't manually exclude one of those since [Span](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/Span.java) class depends on both Endpoints:
1) [Span.remoteEndoint(zipkin.Endpoint)](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/Span.java#L91) - now deprecated (declared in `io.zipkin.java:zipkin`)
2) [Span.remoteEndpoint(zipkin2.Endpoint)](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/Span.java#L101) (declared in `io.zipkin.zipkin2:zipkin`)

This might create issues for deployments which include all dependencies in the same directory (eg. servlet container `WEB-INF/lib`).

Is it a known issue ? Am I using this library incorrectly ? 

Thanks,
Andrei.

**Comment by asereda-gs** [comment]
It seems I have to exclude `io.zipkin.zipkin2:zipkin`. 
`io.zipkin.java:zipkin` already contains classes from `zipkin2` package.

**Comment by codefromthecrypt** [comment]
the name of jars as downloaded is something tools can often manage. I think
the question is about brave. you can exclude io.zipkin.java:zipkin
dependency. Only use the zipkin2 types.
https://github.com/openzipkin/brave/tree/master/brave/src/it/nozipkin1

**Comment by shakuzen** [comment]
We no longer publish the `io.zipkin.java:zipkin` artifact, so this should not be an issue with recent versions.
