### ISSUE TITLE
download link in readme is busted

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1836]
```markdown
Fetch the latest released
 [executable jar for Zipkin server](https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec)
```

due to #1804 and specifically https://issues.sonatype.org/browse/MVNCENTRAL-2870 which covers the root problem (those watching from home)

not sure what to do about it..

**Comment by eirslett** [comment]
We could upload the jar to github and link there instead...

**Comment by codefromthecrypt** [comment]
fixed differently
