### ISSUE TITLE
Timing issues with different systems involved

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1839]
_From @DanielMSchmidt on December 11, 2017 14:40_

Hi there,

First of all big thanks for maintaining this project! We are adding zipkin to our application and experience a problem with the time sync between our frontend running in a browser and our backend systems running on AWS or in a kubernetes cluster. We got spans that look like this:

<img width="1440" alt="screen shot 2017-12-11 at 15 35 53" src="https://user-images.githubusercontent.com/1337046/33836421-a7878d10-de89-11e7-85b7-fdbc4f489981.png">

I ensured that the span is only finished when the request comes back from the server and the times indicate that it should be fine, except for a some second offset between both systems. Is there some way I can "sync" both zipkin clients with each other to rely on the same timing? Is this not a common issue?

_Copied from original issue: openzipkin/zipkin-js#173_

**Comment by codefromthecrypt** [comment]
_From @DanielMSchmidt on December 11, 2017 14:41_

/cc @levito & @garthenweb

**Comment by codefromthecrypt** [comment]
looks related to this?
https://github.com/openzipkin/zipkin/issues/1492#issuecomment-350920084

**Comment by codefromthecrypt** [comment]
_From @mpetazzoni on December 12, 2017 3:42_

> looks related to this? openzipkin/zipkin#1492 (comment)

I think you meant https://github.com/openzipkin/zipkin/issues/1492#issuecomment-350910202 (my comment just above it), but yes it looks very similar. The hosts participating in the trace have slightly offset clocks. I'm not sure the dependency-linking discussed in https://github.com/openzipkin/zipkin/issues/1480 would help there, unless I'm misunderstanding something.

**Comment by jorgheymans** [comment]
Closing, as the linked issue #1492 contains the useful discussion. It would have been helpful to include an anonymized version of the trace so that it's very easy to check if your case has been corrected since then.
