### ISSUE TITLE
Consider replacing adrian with a tiny shell script

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1859]
I've been looking at [atomist](https://app.atomist.com/login) which seems to have means to do distributed maintenance, such as version bumping etc, based on typescript functions.

It would be nice to be able to test and/or roll-out a change to the myriad of applications that use zipkin's libraries, in and outside our org, without necessarily depending on my caffeination levels.

There might be other tools, but seems atomist might help here?

cc @openzipkin/core @openzipkin/devops-tooling 

(ps I don't mind maintenance work, it is good for the ecosystem that we push updates, just wondering if we can make it require less labor)

**Comment by codefromthecrypt** [comment]
PS rod mentioned this for content https://vimeo.com/247562710

beyond selfish aims of maintaining things, seems atomist could also be a way to help instrument libraries. I didn't think of this angle.

**Comment by johnsonr** [comment]
Happy to see how we could help. Distributed library updates are definitely doable; we've examples in both Maven and `package.json`.

- Are we talking about updating `npm` stuff, Java stuff, other? Any sample PRs we could look at to see what we're talking about?
- Which orgs?

**Comment by codefromthecrypt** [comment]
sure. here are some examples. some have inherent workflow so not sure if appropriate or not

### automatically update to latest finagle version
* Finagle updates once a month, but the day might change. Update and immediately cut a release
  * nag issue placeholder https://github.com/openzipkin/zipkin-finagle/issues/38
  * version bump before release tag https://github.com/openzipkin/zipkin-finagle/commit/221a74bc7f7e8f5f045e09afcddd65df571f1824

### update spring-cloud-sleuth
* once a "notable" release is done to our core library, put it in spring-cloud-sleuth. deployment decoupled as out of our org, usually 2 branches to do
  * https://github.com/spring-cloud/spring-cloud-sleuth/commit/92e434e26129bef00215cd20253a58b32c8ee12d

### update extension to our docker image
* update extension library with latest zipkin, on green build make a release-0.8.5 tag to kick automation
  * thing to do to update versions: https://github.com/openzipkin/zipkin-aws/commit/107d9df6cadcd68c20547e4bba9b3543522c1f62
* once that's done, it is synced to bintray, so we can update and cut a docker image via 0.8.5 tag
  * thing to do to update versions: https://github.com/openzipkin/docker-zipkin-aws/commit/91198770444766a848e7a8900de1702ab1b658e3

**Comment by johnsonr** [comment]
All these look doable. 

- I assume cutting a release means a tag and updating release notes?
- Not sure I fully understand the POM changes here, but certainly editing the POM is a core capability
- Editing docker files is also relatively easy

**Comment by codefromthecrypt** [comment]
Another angle is we have a number of example projects to show how to configure zipkin. While some are starting anew, many are copy-pasting things out of these into existing apps. Some sort of means to inject zipkin could be great for support.

https://github.com/openzipkin/brave-webmvc-example
https://github.com/openzipkin/zipkin-php-example
https://github.com/openzipkin/brave-webmvc-example
(there are many others)

**Comment by jorgheymans** [comment]
Not sure how much of a manual chore doing releases still is (apart from writing the release notes and kicking bintray / travis around), if so maybe [github actions](https://github.com/marketplace?type=actions) could be leveraged. But ultimately it's @adriancole to call this, as he's doing most releases.

**Comment by jorgheymans** [comment]
A single `release.sh` script ain't going to happen, github actions are being leveraged more and more. Instead of this, specific issues can be opened for different parts of the release automation. Sorry Adrian, you're not scriptable !
