### ISSUE TITLE
Zipkin server isn't showing reported tags

### ISSUE THREAD

**Issue by yschimke** [openzipkin/zipkin#1873]
As reported in gitter

Adding println debugging in RequestBodyMessageEncoder.java:61

Evaluate and log "new String(next)"

```
{"traceId":"481f6a309b11363c","parentId":"481f6a309b11363c","id":"565e82365fbe26f9","name":"connection","timestamp":1515319672528066,"duration":677881,"localEndpoint":{"serviceName":"oksocial","ipv4":"192.168.1.26"},"tags":{"cipher":"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","peer":"CN=httpbin.org","protocol":"http/1.1","route":"httpbin.org/23.21.74.117:443","tls":"TLS_1_2"}}
{"traceId":"481f6a309b11363c","id":"481f6a309b11363c","kind":"CLIENT","name":"http","timestamp":1515319671773843,"duration":1443207,"localEndpoint":{"serviceName":"oksocial","ipv4":"192.168.1.26"},"tags":{"http.host":"httpbin.org","http.method":"GET","http.path":"/get"}}
```

However trace JSON is

[
  {
    "traceId": "481f6a309b11363c",
    "id": "481f6a309b11363c",
    "name": "http",
    "timestamp": 1515319671773843,
    "duration": 1443207
  },
  {
    "traceId": "481f6a309b11363c",
    "id": "565e82365fbe26f9",
    "name": "connection",
    "parentId": "481f6a309b11363c",
    "timestamp": 1515319672528066,
    "duration": 677881
  }
]

**Comment by yschimke** [comment]
reproduction

```
$ cat ~/.zipkinrc
SENDER=http://localhost:9411/api/v1/spans
DISPLAY=http://localhost:9411/zipkin/traces/{traceid}
```

```
brew install yschimke/tap/oksocial
oksocial --zipkin https://httpbin.org/get
```

**Comment by codefromthecrypt** [comment]
is the sender v2? if so, the sender url should be v2 not v1

**Comment by yschimke** [comment]
Thanks, just found that also

    uri.scheme == "http" || uri.scheme == "https" -> AsyncReporter.builder(OkHttpSender.create(uri.toString())).build(SpanBytesEncoder.JSON_V2)

and updated to v2 in the SENDER

**Comment by codefromthecrypt** [comment]
sorry I should have thought about this when you asked on gitter earlier.
take care
