### ISSUE TITLE
Rewrite storage code where i can start?

### ISSUE THREAD

**Issue by pickmonster** [openzipkin/zipkin#1883]
My project need trace request/responce. So I use zipkin. But I have a difficult question for me. Zipkin storage is not I wanna. So I want to rewrite zipkin storage code. But I don`t know how to start. 
Thank u all help.

**Comment by codefromthecrypt** [comment]
so you are not able to use the in-memory, mysql, elasticsearch or the
pending influxdb? which storage backend are you looking for?

**Comment by pickmonster** [comment]
@adriancole mysql, First I need to analyze the address and parameters based on a different URL. And then record the number of calls to different interfaces based on different addresses.Finally accumulate these quantities into the database.
So I should start with the storage path in the Zipkin project, then go to the MySQL path of zipkin-storage project to process all processes?

**Comment by codefromthecrypt** [comment]
It seems like you could do this work as post-processing like via a flink or
spark job? This could result in less code. For example, use one of the
normal zipkin backends, then hang a job off the storage to do
post-processing into the categories you mention.

**Comment by pickmonster** [comment]
@adriancole It`s mean I needn`t use zipkin-storage-mysql. I just write one class which is implement StorageAdapters.SpanConsumer, then storage my object bean to database. All codes put in normal zipkin project. Is it right?

**Comment by codefromthecrypt** [comment]
you can look at this for how to change zipkin into something that exports
traces to another backend. You don't need to modify anything but you do
need to implement a StorageComponent
https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/48

**Comment by pickmonster** [comment]
@adriancole OK, Thanks very much!!!

**Comment by jorgheymans** [comment]
Question was answered satisfactorily it seems, closing !
