### ISSUE TITLE
Make elastic storage template more customizable

### ISSUE THREAD

**Issue by ouaibsky** [openzipkin/zipkin#1885]
Hi

Right now the index template definition is hardcoded into a java class (VersionSpecificTemplates)
On top of not being a best practice, it makes very difficult to override it.
**And we need to override** it in order to be able to index some custom tag available into span

Maybe good to
* Extract the index definition into a resource file.
* Add an option to load the file from another place (props, ...)
* Maybe good time to add a type of versioning into the template (name or whatever else).

Christophe

**Comment by codefromthecrypt** [comment]
It would be nice to do this, but the amount of version and
configuration-specific options makes it difficult, imply a templating
system and/or involve significant copy/paste (like 6 or more copies).
That's unless I'm missing something...

Is it possible for you to create another index template under a different
path? I thought that they were composable..

**Comment by ouaibsky** [comment]
Hi
Thx for the suggestion.
I was not aware of this elastic feature: getting many templates matching same index with order apply.
Sounds good with elastic 2.4, but I spent many to get something working fine. looks like you have to make sure there is no same mapping property in the both.

Anyway at the end it works like a charm. Thx for insight.
Cheers
Christophe
