### ISSUE TITLE
Will unfinished span caused by some-deadlock be recognized?

### ISSUE THREAD

**Issue by ext2xhb** [openzipkin/zipkin#1889]
we are using zipkin to inspect the database-sql-execute in lots of services. some-time, the sql-execution will dead-locked unpredictable. this dead-lock will leave some span un-finished.  It seems these un-finished span will not be report to database.

So if we using zipkin, how to easily recognize such sql-dead-lock problems  in lots of services?

**Comment by codefromthecrypt** [comment]
Which library are you using? if brave, incomplete spans are flushed
with the annotation "brave.flush" if they stick around until GC

**Comment by jorgheymans** [comment]
No more feedback received since reporting, or perhaps it was solved through gitter chat. (also question was answered)
