### ISSUE TITLE
Hide the "Find a Trace" screen when searchEnabled=false

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1893]
In support of https://github.com/openzipkin/zipkin/pull/1876, we should hide the "find a trace" and also maybe change the default content to empty or otherwise when the config.json has searchEnabled=false

**Comment by Logic-32** [comment]
Me and `git` really don't git along (pun intended).  My apologies for the noisy previous commits.  Hopefully a correct one will follow shortly.  Do you want a pull request for it when it does?

**Comment by codefromthecrypt** [comment]
please do! thanks for your continued help
