### ISSUE TITLE
Display bubbles for core annotations nested in a span

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1895]
Currently, we don't display bubbles for "core annotations" like "sr" "ss". Presumably the reason is to not duplicate signals by putting a bubble on either side of the span.

However, in client+server spans, this doesn't make so much sense. It is meaningful to show the time the server receive and send happened in a shared span. (similarly anything enclosed in a client span, such as "ws" "wr").

By special casing, and only muting "bookend annotations" which correspond with start/stop, we can avoid motivating people to duplicate annotations just to make the UI show the server timestamps.

**Comment by Logic-32** [comment]
Question: how will this work with the UI gets updated to fully support V2, which technically doesn't have SR/SS annotations?  Currently, V2 spans get converted back to V1 format, so it works.  But will they still do that going forward?

**Comment by codefromthecrypt** [comment]
Overlay of two spans with same ID could use bubbles too and name events
same as before (at least initially)

**Comment by codefromthecrypt** [comment]
in lens, color shading is used to show client+server timing of a span. we aren't investing any more time in the classic UI
