### ISSUE TITLE
RabbitMQ collector configuration should support a URI

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/zipkin#1901]
Some cloud service offerings for RabbitMQ may only expose a connection URI. There is no easy way to use this with Zipkin Server now to connect to the RabbitMQ service. The application would have to parse the provided URI into its parts and set those.

The complication here is that multiple addresses cannot be used in the RabbitMQ [URI spec](https://www.rabbitmq.com/uri-spec.html). Originally one of the goals of the exposed configuration was to support RabbitMQ clusters that do not have a TCP load balancer or VIP in front of their nodes.

Some of this is explained in #1827.

Without changes to the RabbitMQ URI spec or Java client, I think our best option is to expose a `RABBIT_URI` configuration property. Behavior of the other configuration properties when this is set would have to be defined (i.e., when URI is set, ignore individual properties for any parts of the URI).

/cc @marcingrzejszczak

**Comment by codefromthecrypt** [comment]
agree. we can add support for this and document like you said, ignoring the other properties.

wanna have a go?

**Comment by marcingrzejszczak** [comment]
please do, please do :D

**Comment by shakuzen** [comment]
> wanna have a go?

I'm happy to make a pull request for this. I just have to find the time. Maybe this weekend!
