### ISSUE TITLE
What the time does zipkin use？

### ISSUE THREAD

**Issue by CyberDick** [openzipkin/zipkin#1904]
When I used crontab to execute the dependencies.jar, I can't get the dependency tree. I check out many times of my own crontab scheduler, and it is right. 
Finally, I find that would be some problems with time. I come from China, maybe zipkin use GMT time. I want to know if there is method to choose time zone.
Thx!

**Comment by fan807017570** [comment]
I have the same problem with you,and I come from china.Do you have solve thi problem?

**Comment by codefromthecrypt** [comment]
zipkin data is always UTC time. no timezones are stored. In fact, timestamps are epoch microseconds https://zipkin.io/zipkin-api/#/default/post_spans
