### ISSUE TITLE
Self tracing broken in update?

### ISSUE THREAD

**Issue by Tony-Zheng-Zocdoc** [openzipkin/zipkin#1912]
I upgraded from 2.3.1 to 2.4.6 and had this error on startup. I was running
`SELF_TRACING_ENABLED=true SELF_TRACING_SAMPLE_RATE=0.10 java -jar zipkin.jar`
zipkin startsup with no problems when I removed the self tracing variables.

> Application startup failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zipkinServerConfiguration.BraveTracedStorageComponentEnhancer': Unsatisfied dependency expressed through field 'brave'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'brave' defined in class path resource [zipkin/server/brave/BraveConfiguration.class]: Unsatisfied dependency expressed through method 'brave' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'braveTracer' defined in class path resource [zipkin/server/brave/BraveConfiguration.class]: Unsatisfied dependency expressed through method 'braveTracer' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reporter' defined in class path resource [zipkin/server/brave/BraveConfiguration.class]: Unsatisfied dependency expressed through method 'reporter' parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zipkinServerConfiguration': Unsatisfied dependency expressed through field 'httpCollector'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zipkinHttpCollector' defined in URL [jar:file:/home/zipkin/zipkin.jar!/BOOT-INF/classes!/zipkin/server/ZipkinHttpCollector.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'metrics': Requested bean is currently in creation: Is there an unresolvable circular reference?

**Comment by codefromthecrypt** [comment]
thanks for reporting.. will look into it. In the mean time, please disable
self tracing

**Comment by codefromthecrypt** [comment]
2.4.7 will fix this. it is going out now
