### ISSUE TITLE
mouseover flickering for kafka spans

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#1923]
Hard to describe this, see the gifs.  Basically I have a trace containing kafka spans, when hovering over the kafka span (the little circle) it is difficult to get the label to appear in a stable way. The gifs i captured don't really do justice to the flickering i am seeing, sometimes it's near impossible to get it to appear. Chrome (64.0.3282.119) seems to suffer more from it than firefox (ESR 52.6.0), this is on windows7. 

This might be related to having a lot of data (about 400 spans in the trace), or maybe the mouseover box on the circle character is too small to be reliable.

Chrome:
![kafka-tracing-zipkin-chrome](https://user-images.githubusercontent.com/193792/36485537-c957231c-171c-11e8-89ac-802a351829b9.gif)

Firefox:
![kafka-tracing-zipkin-firefox](https://user-images.githubusercontent.com/193792/36485317-33d0c2ee-171c-11e8-9056-9fe8d6ac2584.gif)

**Comment by codefromthecrypt** [comment]
I think the original solution to this was the zoom box.. (click and drag outline over the bunched up things) is there another way you can think of

**Comment by codefromthecrypt** [comment]
we won't fix this in classic, but we'll keep watch in #2509 for lens
