### ISSUE TITLE
Configuring Elasticsearch index name

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#1925]
The properties ES_INDEX and ES_DATE_SEPARATOR allows configuring the prefix and the separator used in the index name. However it is not enough to control the date pattern used.

This is a feature request to have a property, like 'ES_INDEX_DATE_PATTERN=yyyyMMdd' to control the suffix used for the index name. If this ask makes querying logic complex, an interim solution can be to allow specifying an empty string for the property 'ES_DATE_SEPARATOR' will be sufficient. For example, 'ES_DATE_SEPARATOR=none' to create a date pattern yyyyMMdd.

**Comment by codefromthecrypt** [comment]
@shakuzen wdyt about  'ES_DATE_SEPARATOR=none' ? is there a better way to indicate empty in boot that isn't easily conflated with unset?

**Comment by codefromthecrypt** [comment]
empty works, it was something else

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/1941
