### ISSUE TITLE
Loopback dropdown menu not working properly [UI Bug]

### ISSUE THREAD

**Issue by saddam-eng-tech** [openzipkin/zipkin#1927]
In Lookback dropdown menu, when we select "Custom" option, then 2 input boxes come.
So, when you click on "Find Trace", these input boxes disappear, which shouldn't.
Because if a user wants to change the date of custom loopback then he have to again select "Custom" from the dropdown menu in order to show those 2 input boxes, even if the "Custom" option is already selected.

![issue 1](https://user-images.githubusercontent.com/12938848/36625277-6db100b8-1957-11e8-9fb9-72e064385ee6.png)

@igorwwwwwwwwwwwwwwwwwwww Can you please help resolve this issue?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@saddampojee should be fixed in https://github.com/openzipkin/zipkin/pull/1929.
