### ISSUE TITLE
What if we suggested span.kind = SERVER when the other side is a message processor?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1931]
We have two classifications of remote spans: RPC and messaging. These have kinds in CLIENT, SERVER and PRODUCER, CONSUMER respectively.

A client server span is typically one where the client span overlaps or contains the server span.

Ex. two way
```
[    client    ] 
    \         /
     [ server ]
```

or a one-way client:
```
[ client ] 
    \
     [ server ]
```

The consumer span is defined as one where you re-inject a span id on the message for later processing.

Ex.
```
[ producer ] 
            \ 
             [consumer]
                        \ 
                         ...     ... [processor or maybe never one!]
```

This is needed in kafka consumers, but ends up laborious or weird in message processing code which conflates receiving a message with processing it.

Let's take code like this for example, which is a message listener:

```java
    @RabbitListener(queues = "test-queue")
    public void receive(Message message) {
      // do amazing work
    }
```

To satisfy the PRODUCER -> CONSUMER flow, you'd make a CONSUMER span and close it immediately (representing the message consume that came before the processor was invoked). Then, you'd make a child span for that processing function.

Ex. the "receive" method above includes a 1us consumer span immediately followed by a processor span
```
[ producer ] 
            \ 
             [consumer][processor]
```

What's happening above is basically the same as a one-way client - server span. It seems like we could save some effort by indicating folks can use the "server" pattern to describe a messaging scenario where consuming a message is conflated with immediately processing it.

Ex.
```
[ producer ] 
            \ 
             [ server ]
```

What do you think? cc @openzipkin/core and specifically @jcarres-mdsol @jonathan-lo and @marcingrzejszczak

see https://github.com/openzipkin/brave/pull/603

**Comment by jonathan-lo** [comment]
Our messaging traces were pre consumer / producer span types, so we them as one-way client interactions.

The proposal above makes sense to me, but not sure if it's a little disconcerting having a producer span without a corresponding consumer one.

**Comment by codefromthecrypt** [comment]
regardless, we can document the more literal interpretation for now (which is that a message processor missing consumer instrumentation should probably make a faux consumer span so that there's parity)

**Comment by codefromthecrypt** [comment]
closing this for now. we can revisit it if we feel like it with this context kept
