### ISSUE TITLE
how can I run openzipkin with elasticsearch? example guide doesn't work.

### ISSUE THREAD

**Issue by Jacob-Aiden-Son** [openzipkin/zipkin#1939]
I run my zipkin server with openzipkin zipkin-server#elasticsearch

here is my command

```
STORAGE_TYPE=elasticsearch
ES_HOSTS=http://host1:9200,http://host2:9200 
java -jar zipkin.jar
```

ES's version is 5.2.2

this ES is already using with other server.

so I think, this ES doesn't have any problem.

zipkin is running and logging is successful.

but I can't find any data of zipkin in ES.

so It isn't persistent.

Is there any additional option to run openzipkin.jar with ES?

**Comment by jcchavezs** [comment]
You can probably get a faster answer from the chat:
https://gitter.im/openzipkin/zipkin

>
> --
*José Carlos Chávez*
Spain: (+34) 672921339
Perú: (+51) 708-5422 Anexo 918

https://github.com/jcchavezs

**Comment by codefromthecrypt** [comment]
we also mentioned recently that for data to appear, applications need to be
sending traces

https://github.com/openzipkin/zipkin#quick-start

you can tell also by hitting the /metrics endpoint and look at stats named
collector
