### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by caniszczyk** [openzipkin/zipkin#194]
I discussed with @franklinhu on creating a Sonatype OSS account:
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

This would allow us to publish artifacts directly to Maven Central and be good open source citizens.

**Comment by mosesn** [comment]
Why is it better to be on Sonatype OSS than maven.twttr?

**Comment by caniszczyk** [comment]
Because it automatically syncs to Maven Central.

I'm slowly weaning Twitter off of maven.twttr.com for most things and having artifacts published to Maven Central instead.

**Comment by mosesn** [comment]
Neat, good to know.

**Comment by franklinhu** [comment]
Filed the ticket: https://issues.sonatype.org/browse/OSSRH-4607
@caniszczyk can you sanity check that?

**Comment by caniszczyk** [comment]
Looks fine, would be great to have this change coincide moving to Maven :)

To sync to maven central, we need spruce up our POM most likely with extra metadata:
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-6.CentralSyncRequirement

**Comment by mauhiz** [comment]
So, has anything been published yet?

**Comment by jpinner** [comment]
@caniszczyk seems like the last release was end of Aug, 2013 -- any chance of cutting a new release and publishing it to sonatype?

**Comment by smparkes** [comment]
@jpinner Yes. We're working on scheduling it now.

**Comment by jpinner** [comment]
any updates?

**Comment by codefromthecrypt** [comment]
I think the idea is that openzipkin will drive artifact publication @rtyler can invite you to the org as well!

**Comment by codefromthecrypt** [comment]
The https://github.com/openzipkin org includes a zipkin-core team which has jpinner in it now too. The plan is to publish artifacts to https://bintray.com/openzipkin/maven after merging some in-flight sbt-bintray  work Lookout built.

**Comment by codefromthecrypt** [comment]
Just to touch this again.

Inside Twitter, maven central is the preferred repo, and our pants 3rdparty will only look at that and https://maven.twttr.com/

I can manually push to the latter until central sync is supported. That would be ideally something that's already published to bintray. Once something is published somewhere, I can move twitter onto openzipkin, which would be very sweet.

**Comment by codefromthecrypt** [comment]
@rtyler @eirslett @michaelsembwever @kristofa @jamescway (think this is openzipkin founding parents)...

So, are you thinking com.github.openzipkin:zipkin-whatev?

Once we decide on group id, I can start the sonatype ticket.

**Comment by codefromthecrypt** [comment]
Twitter donated zipkin.io to us. @aasta has access to the godaddy stuff. I suspect we could use this for group id, etc? cc @eirslett @rtyler

**Comment by eirslett** [comment]
Fantastic, thanks a lot! :-)
io.zipkin it is!

**Comment by rtyler** [comment]
@adriancole sounds good to me, can you get twitter to just point zipkin.io at GitHub's nameservers for CNAME purposes?

**Comment by codefromthecrypt** [comment]
@rtyler I just added you to have manage products ability on godaddy, so
lemme know if that didn't work.

**Comment by codefromthecrypt** [comment]
https://issues.sonatype.org/browse/OSSRH-16669

I'd like a backup.. @eirslett @michaelsembwever @abesto @kristofa @aasta .. can one or more of you register on https://issues.sonatype.org and add a comment ^^ with your username?

**Comment by codefromthecrypt** [comment]
soo.. we did this, and it didn't even take 3 years!

https://repo1.maven.org/maven2/io/zipkin/zipkin-common/1.2.1/
