### ISSUE TITLE
Change the UI trace view page to show the traceId and update the popup window to always show trace, span and parent id

### ISSUE THREAD

**Issue by wdittmer** [openzipkin/zipkin#1947]
When I click on a trace in the main Zipkin UI and I want to know the traceId, I have to click on the trace, then click on a service or span, then click on more info to see the traceId. Though, yes I can get the traceId from the URL (as pointed out by @adriancole ), I might be a good idea to update it as follows:
1. After clicking on a trace from the main UI, show a TraceId: xxxxxxx at the top which can be easily cut & pasted. E.g. a good place might be near (before/after/above) Duration: xxxx ms. See screenshot.
2. In the pop up window: remove the 'more info button' and always show the traceId, spanId and parentId

![zipkin-example-trace-id](https://user-images.githubusercontent.com/16978067/37474218-1dedb0ee-2870-11e8-9b1b-19ae6a9851f9.png)

**Comment by codefromthecrypt** [comment]
@drolando was also recently confused by the "more info" button. Sounds like we have a choice between deleting it or renaming it to something less confusion like "show ids"

**Comment by codefromthecrypt** [comment]
I think the reason why we hid it was that the span detail page was a bit cluttered

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2290 is a stab at improving

**Comment by codefromthecrypt** [comment]
please ask us to reopen this if what happens in #2507 misses the mark
