### ISSUE TITLE
 service/application name is appearing in local zipkin server, but not in other hosted servers

### ISSUE THREAD

**Issue by sangramkb** [openzipkin/zipkin#1956]
I have done the zipkin set up using spring cloud sleuth for one of the spring boot app. Everything is working perfectly in the local system. 

But when I push my changes to a hosted server, the service name is not appearing in the dropdown on zipkin server.
Any inputs please ?

**Comment by codefromthecrypt** [comment]
please use gitter for troubleshooting. issues are for changes to the core libraries or the server https://gitter.im/spring-cloud/spring-cloud-sleuth
