### ISSUE TITLE
instructions for developing against zipkin-ui don't work

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#1957]
apologies for this lame issue, but i'm a lame UI coder to say the least :-P

after following the instructions here https://github.com/openzipkin/zipkin/tree/master/zipkin-ui#whats-the-easiest-way-to-develop-against-this-locally i am getting this (from the zipkin-ui dir)

```
$ ./npm.sh run dev
ERROR: npm not found at ./target/node/npm, did you run mvn install?
$ find . -type f -name npm
./node_modules/npm/bin/npm
./target/node/node_modules/npm/bin/npm
```
It seems that the location of npm in the npm.sh script does not exist after a build.
When i then change it to ./target/node/node_modules/npm/bin/ npm executes but i get this:

```
module.js:545
    throw err;
    ^

Error: Cannot find module '/Users/jorgheymans/Developer/zipkin/zipkin-ui/target/node/node_modules/npm/bin/node_modules/npm/bin/npm-cli.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**Comment by ryanrupp** [comment]
The version of NPM installed via maven used to not be nested within node, after some changes a while back it is, so the wrapper script needed to be updated, see linked PR.

**Comment by jorgheymans** [comment]
@ryanrupp tx !
