### ISSUE TITLE
Separate user/password for read and write to elasticsearch

### ISSUE THREAD

**Issue by wangjishan** [openzipkin/zipkin#1964]
my  elasticsearch  account is Reading and writing separation,
  I   hope  ： when config the  elasticsearch    ,I can config two account (write and  read)

 - [ ] Feature Request. First, look at existing issues to see if the feature has been requested
       before. If you don't find anything, tell us what problem you’re trying to solve. Often a
       solution already exists! Don’t send pull requests to implement new features without first
       getting our support. Sometimes we leave features out on purpose to keep the project small.

**Comment by codefromthecrypt** [comment]
Usually when people have different roles for read and write, they are
deploying multiple servers.

If you deploy at least two servers, then you can do this today by
configuring different credentials

I'm currently hesitant to have a keychain for multiple access levels in the
same server. We aren't doing this for any storage backend at the moment.

**Comment by codefromthecrypt** [comment]
if you can't run multiple instances, but can support your own custom server, you could make your own okhttp interceptor that uses a different basic authentication based on POST vs GET.

As the multiple server approach is often needed anyway for at least redundancy, closing this out. If we get others routinely asking for the same thing, we can re-open it.
