### ISSUE TITLE
[Bug] Can't open pop window

### ISSUE THREAD

**Issue by WiFeng** [openzipkin/zipkin#1972]
It can't open pop window when I click the service bar.  If I reopen an private browser , it will be good in little time.
![image](https://user-images.githubusercontent.com/2247568/37959050-b88aedc4-31e4-11e8-9e20-9c6456b73cbc.png)

**Comment by zeagord** [comment]
I don't think it is a Zipkin issue. Please try again.

**Comment by shakuzen** [comment]
@WiFeng Is this still an issue with the latest version of Zipkin? What browser are you using? If you can provide details so we can reproduce this, we will reopen this and look into it.

**Comment by WiFeng** [comment]
Now we use elasticsearch to store the data, the issue doesn't appears again. I guess it is memory recycle leads to old data be removed.
