### ISSUE TITLE
Switch from actuate PublicMetrics to micrometer

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1977]
Currently, we have people depending on hierarchical metric names generated here: https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/internal/ActuateCollectorMetrics.java

We need to move to micrometer as we can't update to spring boot 2 until this is done. Anyway, it is a nice library. Hopefully with some advice, or a similar PR we can make short work of this.

cc @jkschneider

**Comment by codefromthecrypt** [comment]
@zeagord @shakuzen either of you game for this one?

**Comment by zeagord** [comment]
Of Course. If you can help outline what needs to be done. Most of the metrics that we need JVM, Http_Requests are available out of the box. I think we need to implement custom meters for spans, bytes collected, etc.

**Comment by shakuzen** [comment]
This work is done now by #2014 and the follow-up pull requests.
