### ISSUE TITLE
Index chars limit used in ES SpanConsumer is inconsistent in docs and code

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#1979]
The limit checked is 255 in the [code](https://github.com/openzipkin/zipkin/blob/fdd5c4b6344012554756daafd3841c896d1a1ec7/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/ElasticsearchSpanConsumer.java#L122) and 256 in the [docs](https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/elasticsearch).

**Comment by codefromthecrypt** [comment]
closed by #1980
