### ISSUE TITLE
[Question] why there is set index.mapper.dynamic:false in the storage-es?

### ISSUE THREAD

**Issue by eva233man** [openzipkin/zipkin#1983]
In the class VersionSpecificTemplates, there is set index.mapper.dynamic = false.
[https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/VersionSpecificTemplates.java](url)
Sometimes I need to be on kibana fuzzy query something use some fields.

**Comment by codefromthecrypt** [comment]
this is to reduce the indexing cost, as the primary consumer of this index
is zipkin api which doesn't have fuzzy search
