### ISSUE TITLE
how to configure the language of another country in application.yml?

### ISSUE THREAD

**Issue by halower** [openzipkin/zipkin#1988]
hi， I see that zipkin has supported i18n. If it is used in the springcloud project, does it only need to configure one item? What is this lang configuration property? thank you !

**Comment by codefromthecrypt** [comment]
This i18n in question is javascript and runs in the browser. There is
currently no property to control language choices. Ir one existed, the
browser would read the property from config.json

**Comment by halower** [comment]
it also means that i need to run zipkin ui independently use i18n to change the local language?

**Comment by codefromthecrypt** [comment]
the language is detected from your browser. We have had contributions for a
couple languages. Are you looking for a different language? or is it that
your language isn't detected properly from your browser.

https://github.com/jquery-i18n-properties/jquery-i18n-properties

**Comment by halower** [comment]
thank you very much for your reply, I set in my Google browser is chinese, but the Zipkin UI is still not detected, display english

**Comment by codefromthecrypt** [comment]
you are using latest zipkin right?
https://github.com/openzipkin/zipkin#quick-start

**Comment by halower** [comment]
great, the interface is localized

**Comment by Alexhendar** [comment]
what version you use ,@halower ,i try zipkin-server-2.11.6-exec.jar  and zipkin-server-2.11.7-exec.jar  but still display in english
