### ISSUE TITLE
zipkin broken ui thru gateway

### ISSUE THREAD

**Issue by riteshcodesgit** [openzipkin/zipkin#1993]
hi @adriancole @stepanv @abesto 

issue discussed at #1732  still exits in latest 2.7.1 
on hitting localhost:9411 it auto redirects to /zipkin
and while accessing thru zuul-gateway 

`https://localhost:443/zipkin`
it can not resolve all the components  at 
`https://localhost:443/zipkin/(resource names)**`
which should actually be 
`https://localhost:443/zipkin/zipkin/(resource names)**`

although i have done some manaul labour to append the host name

for few resource in my filter but still doesnot work completely 
`
if(!StringUtils.substringAfterLast(previousUri, "zipkin/").isEmpty()){
		   try {
			ctx.setRouteHost(new URL(host+"/zipkin"));
		} catch (MalformedURLException e) 
			e.printStackTrace();
		}
		   
	   }
`

please suggest any fix its been long since most of the issues related to this are closed but issue still persists

**Comment by codefromthecrypt** [comment]
Please create a zuul example on github as I suspect many are unfamiliar
with it. Include your workaround. Thanks!

**Comment by riteshcodesgit** [comment]
@adriancole  @stepanv @abesto 

zuul properties for accessing  gateway

`zuul.routes.zipkin.path=/zipkin/**
zuul.routs.zipkin.url=http://localhost:9411/`

iam adding /zipkin in host name for all the requests having context /zipkin thru following filter

`     @Override
	`       public Object run() {
		RequestContext ctx = RequestContext.getCurrentContext();
		HttpServletRequest request = ctx.getRequest();
		Object serviceId=ctx.get("serviceId");
	    String previousUri = request.getRequestURI();
	    Object host = ctx.getRouteHost();`
	 
   if(!StringUtils.substringAfterLast(previousUri, "zipkin/").isEmpty()){
		   try {
			ctx.setRouteHost(new URL(host+"/zipkin"));
		} catch (MalformedURLException e) {

			e.printStackTrace();
		}
		   
	   }
	    
	   host = ctx.getRouteHost();
	    
	      return null;
	}
`

the filter works fine for fetching some of the ui resource not all
attached images of resources thru gateway with above filter

[gateway](https://drive.google.com/file/d/13ouvCwZY6SrxFFek6VxCyMctvM8K6cyd/view?usp=sharing)

[direct](https://drive.google.com/file/d/1uM4wJtW0kxu4s0oZcUTpsOvqZSuytE--/view?usp=sharing)

[without filter](https://drive.google.com/file/d/1zHGeG-8zExehOpD4eO0aWHRfGc_ZdAHz/view?usp=sharing)
can u please explain y some of the resources are being accessed successfully while others are not despite 
adding  /zipkin to context or it would be better if u suggest any cleaner solution for reverse proxy

**Comment by jorgheymans** [comment]
As of v2.20 of Zipkin, Lens now explicitly supports reverse proxy configurations (https://github.com/openzipkin/zipkin/pull/2987), documentation can be found [here](https://github.com/openzipkin/zipkin/tree/master/zipkin-lens#running-behind-a-reverse-proxy)

**Comment by jcchavezs** [comment]
@momentum123 would you please confirm this works for you too?
