### ISSUE TITLE
ERROR: Cannot load trace df2507877540c96f: server error (Not Found)

### ISSUE THREAD

**Issue by WiFeng** [openzipkin/zipkin#1995]
![image](https://user-images.githubusercontent.com/2247568/38793139-88357ee8-4182-11e8-8983-3224ee249c14.png)

**Comment by codefromthecrypt** [comment]
is that trace in storage?

**Comment by WiFeng** [comment]
@adriancole I'am not config the storage, I guess it should be memory storage model.

**Comment by codefromthecrypt** [comment]
if you cannot access the trace via /api/v2/trace/your_trace_id then the server didn't receive it. Either the trace wasn't sampled or it dropped along the way. You can look at metrics to see if things are healthy https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#collector

**Comment by codefromthecrypt** [comment]
feel free to troubleshoot via gitter https://gitter.im/openzipkin/zipkin

issues are better for changes to the code
