### ISSUE TITLE
zipkin-server can't support spring cloud 2.x(spring boot 2.x)

### ISSUE THREAD

**Issue by didicenter** [openzipkin/zipkin#2012]
when i use spring cloud 2.x and spring boot 2.x , i want to use zipkin-server annotation, but it cannot work.
I find that 
org.springframework.boot.context.embedded.undertow 
is move to  org.springframework.boot.web.embedded.undertow.

**Comment by codefromthecrypt** [comment]
custom servers are unsupported per https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/EnableZipkinServer.java

however, we will be moving to spring boot version 2.0 soon anyway. Please watch pull requests for status on this, as it is work in progress.
