### ISSUE TITLE
elasticsearch storage . zipkin dependencies no data!!!

### ISSUE THREAD

**Issue by 65725738** [openzipkin/zipkin#2016]
elasticsearch storage . zipkin dependencies no data!!! traces is fine.  and   mysql storage all is fine. why?
( http://localhost:8001/zipkin/api/v1/dependencies?endTs=2524621629058&lookback=86399998  no data )
(http://localhost:8001/zipkin/api/v1/traces?annotationQuery=&limit=10&lookback=3600000&minDuration=&sortOrder=duration-desc   is fine)

zipkin server 

	       <dependency>
			<groupId>io.zipkin.java</groupId>
			<artifactId>zipkin-autoconfigure-storage-elasticsearch-http</artifactId>
			<version>2.6.1</version>
		</dependency>
		
		<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>5.2.2</version>
        </dependency>
        
        
        <dependency>
	      <groupId>org.elasticsearch</groupId>
	      <artifactId>elasticsearch</artifactId>
	      <version>5.2.2</version>
	    </dependency>

           	<dependency>
	        <groupId>io.zipkin.java</groupId>
	        <artifactId>zipkin-server</artifactId>
	    </dependency>
		
		<dependency>
		    <groupId>io.zipkin.java</groupId>
		    <artifactId>zipkin-autoconfigure-ui</artifactId>
		</dependency>
	
	    <dependency>
		  <groupId>io.zipkin.java</groupId>
		  <artifactId>zipkin-autoconfigure-collector-kafka</artifactId>
		  <version>2.6.1</version>
		</dependency>
		
spring cloud 

         <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

**Comment by 65725738** [comment]
es data:


{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 95,
    "max_score": 1,
    "hits": [
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLuJMHyfRRHS9yEt",
        "_score": 1,
        "_source": {
          "traceId": "05e5a2968f194a2a",
          "duration": 6000,
          "localEndpoint": {
            "serviceName": "iot-gate",
            "ipv4": "192.168.0.44",
            "port": 8765
          },
          "timestamp_millis": 1524619470002,
          "kind": "CLIENT",
          "name": "http:/client/myclient.do",
          "id": "34ea496e336ace1a",
          "parentId": "05e5a2968f194a2a",
          "timestamp": 1524619470002000,
          "tags": {
            "http.host": "wangbin-PC",
            "http.method": "GET",
            "http.path": "/client/myClient.do",
            "http.url": "http://wangbin-PC:8766/client/myClient.do?serviceId=iot-gate&secret=123456",
            "spring.instance_id": "wangbin-PC:iot-gate:8765"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLntMHyfRRHS9yDI",
        "_score": 1,
        "_source": {
          "traceId": "0ae106a1b48e9a4d",
          "duration": 9534,
          "localEndpoint": {
            "serviceName": "iot-gate",
            "ipv4": "192.168.0.44",
            "port": 8765
          },
          "timestamp_millis": 1524619710002,
          "name": "refresh-allowed-client",
          "id": "0ae106a1b48e9a4d",
          "timestamp": 1524619710002000,
          "tags": {
            "class": "ServiceAuthUtil$$EnhancerBySpringCGLIB$$9c94d298",
            "lc": "scheduled",
            "method": "refreshAllowedClient"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLnzMHyfRRHS9yDP",
        "_score": 1,
        "_source": {
          "traceId": "a63fe1bd0ba894ae",
          "duration": 19332,
          "localEndpoint": {
            "serviceName": "iot-gate",
            "ipv4": "192.168.0.44",
            "port": 8765
          },
          "timestamp_millis": 1524620010002,
          "name": "refresh-allowed-client",
          "id": "a63fe1bd0ba894ae",
          "timestamp": 1524620010002000,
          "tags": {
            "class": "ServiceAuthUtil$$EnhancerBySpringCGLIB$$9c94d298",
            "lc": "scheduled",
            "method": "refreshAllowedClient"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLn2MHyfRRHS9yDT",
        "_score": 1,
        "_source": {
          "traceId": "b05c4866005fe237",
          "duration": 2653,
          "shared": true,
          "localEndpoint": {
            "serviceName": "iot-auth",
            "ipv4": "192.168.0.44",
            "port": 8766
          },
          "timestamp_millis": 1524619590005,
          "kind": "SERVER",
          "name": "http:/client/myclient.do",
          "id": "17c7981080e31148",
          "parentId": "b05c4866005fe237",
          "timestamp": 1524619590005000,
          "tags": {
            "mvc.controller.class": "ClientController",
            "mvc.controller.method": "getAllowedClient",
            "spring.instance_id": "wangbin-PC:iot-auth:8766"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLn4MHyfRRHS9yDX",
        "_score": 1,
        "_source": {
          "traceId": "cd33f9058f2f585b",
          "duration": 7000,
          "localEndpoint": {
            "serviceName": "iot-iotserver",
            "ipv4": "192.168.0.44",
            "port": 8767
          },
          "timestamp_millis": 1524620250003,
          "kind": "CLIENT",
          "name": "http:/client/myclient.do",
          "id": "eff98aaae2fa6280",
          "parentId": "cd33f9058f2f585b",
          "timestamp": 1524620250003000,
          "tags": {
            "http.host": "wangbin-PC",
            "http.method": "GET",
            "http.path": "/client/myClient.do",
            "http.url": "http://wangbin-PC:8766/client/myClient.do?serviceId=iot-iotserver&secret=123456",
            "spring.instance_id": "wangbin-PC:iot-iotserver:8767"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLn4MHyfRRHS9yDY",
        "_score": 1,
        "_source": {
          "traceId": "cd33f9058f2f585b",
          "duration": 10477,
          "localEndpoint": {
            "serviceName": "iot-iotserver",
            "ipv4": "192.168.0.44",
            "port": 8767
          },
          "timestamp_millis": 1524620250002,
          "name": "refresh-allowed-client",
          "id": "cd33f9058f2f585b",
          "timestamp": 1524620250002000,
          "tags": {
            "class": "ServiceAuthUtil$$EnhancerBySpringCGLIB$$eb7a1d5f",
            "lc": "scheduled",
            "method": "refreshAllowedClient"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLn4MHyfRRHS9yDb",
        "_score": 1,
        "_source": {
          "traceId": "26b1a45d43533558",
          "duration": 6000,
          "localEndpoint": {
            "serviceName": "iot-iotserver",
            "ipv4": "192.168.0.44",
            "port": 8767
          },
          "timestamp_millis": 1524619830002,
          "kind": "CLIENT",
          "name": "http:/client/myclient.do",
          "id": "7ecb19f7a9752bba",
          "parentId": "26b1a45d43533558",
          "timestamp": 1524619830002000,
          "tags": {
            "http.host": "wangbin-PC",
            "http.method": "GET",
            "http.path": "/client/myClient.do",
            "http.url": "http://wangbin-PC:8766/client/myClient.do?serviceId=iot-iotserver&secret=123456",
            "spring.instance_id": "wangbin-PC:iot-iotserver:8767"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLn5MHyfRRHS9yDe",
        "_score": 1,
        "_source": {
          "traceId": "88999e1c5c53860d",
          "duration": 9391,
          "localEndpoint": {
            "serviceName": "iot-gate",
            "ipv4": "192.168.0.44",
            "port": 8765
          },
          "timestamp_millis": 1524620040001,
          "name": "refresh-allowed-client",
          "id": "88999e1c5c53860d",
          "timestamp": 1524620040001000,
          "tags": {
            "class": "ServiceAuthUtil$$EnhancerBySpringCGLIB$$9c94d298",
            "lc": "scheduled",
            "method": "refreshAllowedClient"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLn5MHyfRRHS9yDf",
        "_score": 1,
        "_source": {
          "traceId": "061d522c4e624835",
          "duration": 2725,
          "shared": true,
          "localEndpoint": {
            "serviceName": "iot-auth",
            "ipv4": "192.168.0.44",
            "port": 8766
          },
          "timestamp_millis": 1524619560004,
          "kind": "SERVER",
          "name": "http:/client/myclient.do",
          "id": "e0acb5b243bb3369",
          "parentId": "061d522c4e624835",
          "timestamp": 1524619560004000,
          "tags": {
            "mvc.controller.class": "ClientController",
            "mvc.controller.method": "getAllowedClient",
            "spring.instance_id": "wangbin-PC:iot-auth:8766"
          }
        }
      },
      {
        "_index": "zipkin:span-2018-04-25",
        "_type": "span",
        "_id": "AWL6eLn5MHyfRRHS9yDi",
        "_score": 1,
        "_source": {
          "traceId": "d19d64e2abfb41de",
          "duration": 10528,
          "localEndpoint": {
            "serviceName": "iot-gate",
            "ipv4": "192.168.0.44",
            "port": 8765
          },
          "timestamp_millis": 1524619650001,
          "name": "refresh-allowed-client",
          "id": "d19d64e2abfb41de",
          "timestamp": 1524619650001000,
          "tags": {
            "class": "ServiceAuthUtil$$EnhancerBySpringCGLIB$$9c94d298",
            "lc": "scheduled",
            "method": "refreshAllowedClient"
          }
        }
      }
    ]
  }
}

**Comment by codefromthecrypt** [comment]
you need to run https://github.com/openzipkin/zipkin-dependencies when
using elasticsearch or Cassandra

**Comment by 65725738** [comment]
ok another question 。
trace：

95.000ms 3 spans
**all 0%**
iot-auth x3 95ms
04-25-2018T14:22:52.566+0800
25.000ms 3 spans
all 0%
iot-auth x3 NaNms
04-25-2018T14:22:52.541+0800
16.000ms 3 spans 

ALL 0%  what is meaning？

**Comment by codefromthecrypt** [comment]
please join gitter for questions. issues alert a lot of people and are only
for changes to code

https://gitter.im/openzipkin/zipkin

**Comment by 65725738** [comment]
I can't open the page -----https://gitter.im/openzipkin/zipkin


help me  .  ALL 0% what is meaning？

please!!!

**Comment by codefromthecrypt** [comment]
be patient

**Comment by liyuanjun** [comment]
Hello, if I don't run zipkin-dependency.jar, can I use POM dependency to start zipkin-server only to achieve the same result?

**Comment by codefromthecrypt** [comment]
no.. currently there's no way to do this. the dependency job is offline. We
can consider changing this as so many people ask (to an approach like mysql
which does on-demand if the dependencies job never ran)

**Comment by liyuanjun** [comment]
yes. After all, there is a dependency button on UI, but it can not display data. It will make some people feel very strange. Thank you for your answer.

**Comment by hlpdlpu** [comment]
good
