### ISSUE TITLE
Presumptive text in the Zipkin UI help popup

### ISSUE THREAD

**Issue by jakerobb** [openzipkin/zipkin#2018]
From https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/static/traces.properties:

    modal.p4 = Span names are generally RPC method names or Rails endpoints. This allows you to look up traces that accessed a particular part of the service.

Our instrumented services are Java HTTP/REST services. Span names are _never_ RPC method names nor Rails endpoints. Zipkin should not be so presumptive about this.

:)

**Comment by codefromthecrypt** [comment]
that's probably the older text in the project :P

It is true though that RPC names are usually span names (ex grpc) and we prefer route names (endpoints recently clarified using the http.route) tag. last place is "get" "post" etc.

**Comment by jorgheymans** [comment]
Lens (the new UI) is less presumptive, and zipkin-classic is no longer maintained so we can close this.
