### ISSUE TITLE
UI no longer has datepickers when using a "Custom" lookback

### ISSUE THREAD

**Issue by jakerobb** [openzipkin/zipkin#2019]
With the introduction of the "lookback" dropdown, I no longer see datepickers, nor any sort of formatting help/advice for the from/to date/time fields.

![image](https://user-images.githubusercontent.com/8182938/39258774-ce774790-4882-11e8-90a9-a7d3b36c7138.png)

The datepickers were helpful! Please bring them back. A "placeholder" attribute on the date and time textboxes indicating format would also be very much appreciated. It would be even better if the boxes could be prepopulated with the values from the most recent search or Lookback selection. :)

**Comment by jakerobb** [comment]
Also, the date/time fields don't repopulate after performing a search with a custom lookback.

**Comment by shakuzen** [comment]
@igorwwwwwwwwwwwwwwwwwwww Can you take a look at this if you have time?
