### ISSUE TITLE
Don't show "all 0%" in the UI

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2020]
The "all" selection in the service name drop-down shouldn't affect the service percentage results.

![image](https://user-images.githubusercontent.com/64215/39290715-25950f68-4963-11e8-835a-ba2e3f536710.png)

Thanks @65725738 for reporting

**Comment by zeagord** [comment]
This is fixed by #2198

**Comment by shakuzen** [comment]
Thanks @zeagord!
