### ISSUE TITLE
when I build zipkin.2.7.1 server, found the ERROR at the UI: cannot load service names: No message available

### ISSUE THREAD

**Issue by nolan4954** [openzipkin/zipkin#2022]
And I find the network request at the chrome:
message:"No message available"
path:"/zipkin/api/v1/services"
status:404

**Comment by codefromthecrypt** [comment]
are you running a custom build?

**Comment by ankeway** [comment]
Running with Spring Boot 2.0.1.RELEASE, Build Zipkin Server,  zipkin/api/v1/services response 404 not found

**Comment by zeagord** [comment]
Custom builds are not supported. Use the released jar or docker version.

**Comment by chuguoren** [comment]
Why not support custom builds?
I want to register zipkin to eureka server, and also get configuration from spring config server.

**Comment by nolan4954** [comment]
I had resolved it. Just downgrade springboot2.0 to 1.5.x.
To refrence
https://stackoverflow.com/questions/50027127/zipkin-ui-displaying-error-message-error-cannot-load-service-names-no-message
Well, it is great to upgrade faster the version of springboot dependenced by zipkin-server.jar  :) @adriancole

**Comment by zeagord** [comment]
@chuguoren Well. Firstly, There is nothing stopping you from using custom builds. You can still use it at your own risk. For most of the users, the released versions are sufficient enough for running it production. If you're learning/exploring Zipkin, I would recommend using the released version and if you feel any limitations you can request that feature to be included in the core library or explore the option of running a custom build. 
@nolan4954 - FYI - The latest verision of Zipkin 2.8.4 is using Springboot 2.0.1 under the hood.

**Comment by shakuzen** [comment]
> Why not support custom builds?

@chuguoren it's possible we can support more features in the prebuilt Zipkin Server, but we need to gauge user interest and adoption/support for each. Supporting any possible custom build requires an unbounded amount of support resources, while we have limited resources (volunteers and paid staff) to help. As @zeagord explained, using a custom build is still an option, as long as you are willing to support yourself in doing so.

> I want to register zipkin to eureka server

see #1870 for the feature request to support service discovery. You can comment there explaining your situation.

> and also get configuration from spring config server.

I don't think we've had a request for this, so you can be the first to make a ticket for it if you're interested in it and want to see if others are as well.

**Comment by nolan4954** [comment]
@zeagord 
I tried to upgrade zipkin-server to 2.8.1 , springboot to 2.0.x
But `@EnableZipkinServer ` cannot be imported. 
And there will be 404 error with zipkin ui home page if doesn't use @EnableZipkinServer
So, It's better to use 2.7.1 v and springboot 1.5.x ?

**Comment by ankeway** [comment]
zipkin Use the released jar or docker version is enough for running it production, Don't need downgrade springboot to 1.5.x,  Custom build zipkinserver with spring Boot is unnecessary, Starting from the Edgware release, the Zipkin Stream server is deprecated. In the Finchley release, it got removed.
@EnableZipkinServer and @EnableZipkinStreamServer is deprecated,
Web
java -jar zipkin-server-2.8.3-exec.jar
Rabbitmq
java -jar zipkin-server-2.8.3-exec.jar --RABBIT_ADDRESSES=localhost:5672 --RABBIT_USER=user --RABBIT_PASSWORD=password --RABBIT_VIRTUAL_HOST=host
kafak
java -jar zipkin-server-2.8.3-exec.jar --KAFKA_ZOOKEEPER=localhost:2181

**Comment by nolan4954** [comment]
ok,Thank All~
I have start zipkin-server with zipkin-server.jar only, that's great.
