### ISSUE TITLE
The issue about Kafka 0.10+ Collector Auto-configure Module???

### ISSUE THREAD

**Issue by liusl12** [openzipkin/zipkin#2029]
[root@blninst06 zipkin]# KAFKA_BOOTSTRAP_SERVERS=10.122.23.134:9092 \
>     java \
>     -Dloader.path='kafka10.jar,kafka10.jar!/lib' \
>     -Dspring.profiles.active=kafka \
>     -cp zipkin.jar \
>     org.springframework.boot.loader.PropertiesLauncher
Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher

**Comment by codefromthecrypt** [comment]
Note: we just upgraded to Spring Boot 2.0.1 I've verified that kafka
still works using our docker setup with version 2.8.1

You can look at how it works just in case:

https://github.com/openzipkin/docker-zipkin/blob/master/zipkin/Dockerfile#L35

**Comment by codefromthecrypt** [comment]
I just manually tested too https://github.com/openzipkin/zipkin/tree/master/zipkin-autoconfigure/collector-kafka10#quick-start

feel free to get support here if you need it https://gitter.im/openzipkin/zipkin
