### ISSUE TITLE
Upgrading to Springboot 2 adds double slash in the url

### ISSUE THREAD

**Issue by zeagord** [openzipkin/zipkin#2037]
After upgrading to Springboot 2 the UI URLs after `/zipkin//` for the requests.

**Comment by shakuzen** [comment]
Note that the URLs still work this way, but it is distracting and a difference we should probably fix if easy to do.

**Comment by codefromthecrypt** [comment]
agreed should sort it. we should make the existing properties work like
they did before as they are added for things like bastion hosts. in other
words if feasible change via code not property value
