### ISSUE TITLE
Potential loss of data on JVM termination

### ISSUE THREAD

**Issue by wjase** [openzipkin/zipkin#2042]
Saw a warning from one of our Spring Artefacts on shutdown:

    04 Apr 2018 12:36:34,299] WARN  [requestId=] [loader.WebappClassLoaderBase]: The web 
    application [XXX] appears to have started a thread named [AsyncReporter(XXX)] but has failed to 
    stop it. This is very likely to create a memory leak. Stack trace of thread:\n 
    sun.misc.Unsafe.park(Native Method) 
    java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215) java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
    zipkin.reporter.ByteBoundedQueue.drainTo(ByteBoundedQueue.java:83)
    zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:227)
    zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:166)
    zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source) 
    java.lang.Thread.run(Thread.java:745)

I think this is the Daemon thread created in `zipkin.reporter.AsyncReporter.build(Encoder<S> encoder)`

> Normal thread and daemon threads differ in what happens when they exit. When the JVM halts any remaining 
> daemon threads are abandoned:
> finally blocks are not executed,
> stacks are not unwound - the JVM just exits.
> Due to this reason daemon threads should be used sparingly and it is dangerous to use them for tasks  that might perform any sort of I/O

The daemon flushing thread could potentially just exit without completion (or executing the finally block), losing trace data.
Perhaps the thread should have a shutdown hook and not be set as a daemon thread?

**Comment by codefromthecrypt** [comment]
This issue was moved to openzipkin/zipkin-reporter-java#109
