### ISSUE TITLE
Proposal: Rename the io.zipkin.java:zipkin dependency to io.zipkin.java:zipkin-java

### ISSUE THREAD

**Issue by henrik242** [openzipkin/zipkin#2044]
Both `io.zipkin.java:zipkin:2.6.0` and `io.zipkin2.zipkin:zipkin:2.6.0` provides a jar named `zipkin-2.6.0.jar`.  This has been a problem for us when deploying to an exploded war folder for Tomcat and/or Cargo, since one overwrites the other.  The workaround for us has been to remove or rename one of the jars.

By renaming the `io.zipkin.java:zipkin` artifact to `io.zipkin.java:zipkin-java`, the problem could be avoided.

**Comment by codefromthecrypt** [comment]
why are you importing both artifacts?

**Comment by codefromthecrypt** [comment]
see also #2045 #2046 as there are elaborate explanations. (interesting pile-on of issues in such a short time!)

While understood, we won't be changing the group of a deprecated artifact. Rather, we will make it unnecessary. It  already is unnecessary for current versions of Brave, for example.

Feel free to comment here why you are importing both, or let us know on https://gitter.im/openzipkin/zipkin Perhaps there's a way to make this issue unnecessary for you.

**Comment by codefromthecrypt** [comment]
see https://github.com/openzipkin/zipkin/issues/2047

**Comment by henrik242** [comment]
> Why are you importing both artifacts?

@adriancole: I don’t.  io.zipkin.java:zipkin adds this dependency itself:

https://github.com/openzipkin/zipkin/blob/328904f476208bc2454626f818798c72e3290bc4/zipkin/pom.xml#L38
