### ISSUE TITLE
build zipkin-sever with kafka, the kafka cluster is not work, but only 9092 port worked.

### ISSUE THREAD

**Issue by nolan4954** [openzipkin/zipkin#2049]
You see, I had built a kafka cluster at a single machine. The broker list is 10.88.0.81:9092,10.88.0.81:9093,10.88.0.81:9094, And I can sure this kafka cluster is health.
But, When start zipkin with kafka, only 10.88.0.81:9092 is used. So when I killed the kafka broker 9092 process, the zipkin couldn't receive message with topic zipkin and the log also report always: 
```
Group coordinator 10.88.0.81:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery
```
And find it from the start server log:
```
[Consumer clientId=consumer-1, groupId=zipkin] Discovered group coordinator 10.88.0.81:9092 (id: 2147483647 rack: null)
```
Finally my start server command:
```
KAFKA_BOOTSTRAP_SERVERS=10.88.0.81:9093,10.88.0.81:9092,10.88.0.81:9094 \
    java \
    -Dloader.path='kafka10.jar,kafka10.jar!/lib' \
    -Dspring.profiles.active=kafka \
    -cp zipkin-server-2.8.3-exec.jar \
    org.springframework.boot.loader.PropertiesLauncher
```

**Comment by codefromthecrypt** [comment]
try version 2.9.4 with default (java -jar) as kafka 0.10+ is now default.

ex. KAFKA_BOOTSTRAP_SERVERS=10.88.0.81:9093,10.88.0.81:9092,10.88.0.81:9094 java -jar zipkin.jar

If the problem is the same, please mention so!

**Comment by jorgheymans** [comment]
Question seems answered, and no more feedback received since. If you still have issues with broker connectivity please open a separate issue.
