### ISSUE TITLE
zipkin ui can not get service names from /api/v1/services

### ISSUE THREAD

**Issue by larrying** [openzipkin/zipkin#2050]
The number of service names is 320, and zipkin UI can not get service names from /api/v1/services, but can get service names from /api/v2/services. When i reduced the number of service names, it can be loaded from /api/v1/services.

zipkin version: 2.7.1

can you give me some help ?

**Comment by zeagord** [comment]
Can you try this with the latest Zipkin and check?

**Comment by shakuzen** [comment]
Since #1802, the UI now uses the v2 API endpoints. Therefore, I think it's no longer an issue for you, but if it is, please try with the latest version and come chat with us on Gitter: https://gitter.im/openzipkin/zipkin
