### ISSUE TITLE
how to discard certain service in zipkin?

### ISSUE THREAD

**Issue by Yisaer** [openzipkin/zipkin#2051]
I use zipkin by `openzipkin/zipkin` docker image in `istio` environment and it traces many `istio-mixer` report requests which I dont want zipkin to trace and store.  What should i do to set zipkin discard a certain service request?

**Comment by jcchavezs** [comment]
I think this is more an itsio feature question rather than zipkin. Zipkin
displays what you send to the backend.

**Comment by codefromthecrypt** [comment]
yep. I think this should be elaborated in istio as a part of sampling policy. for example, most tools that originate traces have a means to describe what paths should be traced or not.
