### ISSUE TITLE
Build zipkin multi-arch docker image 

### ISSUE THREAD

**Issue by alicefr** [openzipkin/zipkin#2057]
Hi,
I have a question and I hope you could help me.

I wanted to build `openzipkin/zipkin` docker image for another platform rather than x86. However, the `cantara/alpine-zulu-jdk8` has not multi-arch image support. So, I was wondering if it would be possible to change the parent image of `openzipkin/jre-full` with the official docker image `openjdk:8-jdk-alpine`. The openjdk image has already multi-arch support.

I also opened the same issue in https://github.com/openzipkin/docker-jre-full/issues/7

Thanks for the help!

**Comment by shakuzen** [comment]
Fixed in openzipkin/docker-jre-full#7 and docker images since zipkin 2.7.4
