### ISSUE TITLE
Zipkin UI span names have incorrect CSS `left` value

### ISSUE THREAD

**Issue by echoAlexey** [openzipkin/zipkin#2058]
Zipkin UI don't show span names in correct place. CSS `left` value has "minus" value, which causes them to be out of the screen. 

![selection_001](https://user-images.githubusercontent.com/3122131/40357122-d6c12f82-5dc3-11e8-8faf-ee46950e8bc4.png)

![selection_002](https://user-images.githubusercontent.com/3122131/40357124-d7bbe210-5dc3-11e8-9ba1-f0331c449ff2.png)

Using: `openzipkin/zipkin:latest`. Image ID: `a62fb9056a9a`

**Comment by zeagord** [comment]
Could be related to this https://github.com/openzipkin/zipkin/issues/1906

**Comment by echoAlexey** [comment]
Hi, sorry, issue was caused by server time being not in sync.
