### ISSUE TITLE
cassandra3-storage tables creation gives a warning during index creation

### ISSUE THREAD

**Issue by hyginous29** [openzipkin/zipkin#2059]
Hi Adrian,

We are trying to create cassandra tables for zipkin using below project - 
https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/zipkin2_cassandra

**It seems , it needs some index to be created but SASI indexes is not supported by Datastax.**

https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/useSASIIndex.html

"Secondary indexes, SSTable Attached Secondary Indexes (SASI), have improved the performance of secondary indexes but should be used with caution.

Attention: SASI indexes in DSE are experimental. DataStax does not support SASI indexes for production."

**Is it possible to use create tables without index ? I mean will it work without indexes**

**Comment by codefromthecrypt** [comment]
:) in general please don't ask questions directly to a person even if that person will answer you, they might go on holiday etc.

Yes, you can disable the SASI indexing (via SEARCH_ENABLED=false). However I can't say if it works in DSE or not. We don't test with DSE cc @openzipkin/cassandra 

feel free to ask more on gitter https://gitter.im/openzipkin/zipkin

**Comment by hyginous29** [comment]
:) ... Thanks man
