### ISSUE TITLE
is zipkin tracer client available for below frameworks/technology stack ?

### ISSUE THREAD

**Issue by hyginous29** [openzipkin/zipkin#2063]
is zipkin tracer client available for below frameworks/technology stack ?

- iOS swift/ Android (Mobile apps) 
- Oracle database/ ibm db2
- Couchbase, redis

thanks.

**Comment by codefromthecrypt** [comment]
* iOS - really don't know
* Android - brave is used in android https://github.com/openzipkin/brave
* Oracle/IBM DB2 - depends on what language, if java Brave P6SPY might work
* Couchbase/ Redis - also depends on the language. If java I know some have custom brave things. perhaps @kojilin @anuraaga might know

https://zipkin.io/pages/existing_instrumentations has an incomplete list.
https://docs.google.com/document/d/13qEcxIjijbdiaVgOAH1OarrctyHEg88kMSIhd16DFK4/edit has unofficial information (and a bit out of date as well)

please join https://gitter.im/openzipkin/zipkin for questions next time ok? thanks!

**Comment by hyginous29** [comment]
Joined , thanks.
