### ISSUE TITLE
zipkin-ui do not show the times

### ISSUE THREAD

**Issue by lanyyyy** [openzipkin/zipkin#2067]
If service A send 10 requests to service B, there will be 10 tracing items...
But on the zipkin-ui, there is only one:
![image](https://user-images.githubusercontent.com/4739622/40725545-4c58b416-6456-11e8-96f7-e0aec5f18d57.png)
I want to see like this:
![image](https://user-images.githubusercontent.com/4739622/40725601-69c55cd4-6456-11e8-9984-c3d91693d1a3.png)

**Comment by codefromthecrypt** [comment]
>
> If service A send 10 requests to service B, there will be 10 tracing
> items...
>
if 100% sampling yes.. should be equal in the dependency link callCount

**Comment by lanyyyy** [comment]
1.  Is there a method to set the sampling config of service A/B???

2.  Does the zipkin-server need to set   the sampling config???

**Comment by codefromthecrypt** [comment]
please join gitter for help

https://gitter.im/openzipkin/zipkin

**Comment by lanyyyy** [comment]
ok。。。       :)
