### ISSUE TITLE
zipkin 2.8.4: when uses storage elasticsearch, can not query dependencies

### ISSUE THREAD

**Issue by ldcsaa** [openzipkin/zipkin#2074]
When I use **storage mysql** to store zipkin span infos, I can query dependencies, the '/api/v2/dependencies' API can return the invoking dependencies infos, and 'http://localhost:9411/zipkin/dependency' Web UI can 
query and display it.
But when I use **storage elasticsearch** to store zipkin span infos, I can NOT query dependencies, the '/api/v2/dependencies' API return an empty json array, and 'http://localhost:9411/zipkin/dependency' Web UI can NOT query dependencies.

What's wrong with me, or any bug with zipkin ?

The following code is my startup shell script:
```
#!/bin/sh
PRGDIR=$(dirname $0)
SVR_NAME="zipkin-server"
LOG_FILE="$PRGDIR/zipkin.log"
JAVA_OPTIONS="-server -Xmn128m -Xmx128m -Xms512m"
SPRING_BOOT_OPTIONS="--management.endpoints.enabled-by-default=true"
ZIPKIN_COLLECTOR_OPTIONS=
# mysql storage (can query dependencies)
#ZIPKIN_STORAGE_OPTIONS="--zipkin.storage.type=mysql --zipkin.storage.mysql.host=myhost --zipkin.storage.mysql.port=3306 --zipkin.storage.mysql.username=dev --zipkin.storage.mysql.password=123456 --zipkin.storage.mysql.db=my_zipkin_db"
# elasticsearch storage (can NOT query dependencies)
ZIPKIN_STORAGE_OPTIONS="--zipkin.storage.StorageComponent=elasticsearch --zipkin.storage.type=elasticsearch --zipkin.storage.elasticsearch.hosts=http://192.168.3.11:9200,http://192.168.3.12:9200,http://192.168.3.13:9200 --zipkin.storage.elasticsearch.index=zipkin --zipkin.storage.elasticsearch.index-shards=5 --zipkin.storage.elasticsearch.index-replicas=1 --zipkin.storage.elasticsearch.max-requests=64 --zipkin.storage.elasticsearch.timeout=10000"

printf "starting %s ...\n" "$SVR_NAME"
printf "log file -> %s\n" "$LOG_FILE"

nohup java -jar $PRGDIR/zipkin-server-2.8.4-exec.jar $JAVA_OPTIONS $SPRING_BOOT_OPTIONS $ZIPKIN_COLLECTOR_OPTIONS $ZIPKIN_STORAGE_OPTIONS > $LOG_FILE 2>&1 &
```

**Comment by codefromthecrypt** [comment]
you need to run https://github.com/openzipkin/zipkin-dependencies to
aggregate dependencies.

in our docker image, we have a built-in schedule. You can do something
similar

https://github.com/openzipkin/docker-zipkin-dependencies/tree/master/periodic

**Comment by ldcsaa** [comment]
Thanks very much, I have make it work now ~
