### ISSUE TITLE
java.lang.NoClassDefFoundError: zipkin/internal/Span2Converter    zipkin-autoconfigure-storage-elasticsearch-http  1.29.3

### ISSUE THREAD

**Issue by hi794510874** [openzipkin/zipkin#2090]
![default](https://user-images.githubusercontent.com/7234043/41214088-e0e54ce2-6d7b-11e8-8374-ed1f3b2d585b.png)

**Comment by codefromthecrypt** [comment]
internal classes aren't to be used directly.

If you have a classpath problem with an internal class, probably there's a
version mismatch somewhere. the artifact that would have had that class
would be io.zipkin.java:zipkin

Meanwhile, custom builds aren't supported. However if you are curious
troubleshooting questions should be here not on github issues
https://gitter.im/openzipkin/zipkin
