### ISSUE TITLE
Elasticsearch does not show the correctly number of spans

### ISSUE THREAD

**Issue by lanyyyy** [openzipkin/zipkin#2093]
####  I am doing a pressure test:
In 30 seconds, I send 3000 requests to my services, then the services generate 3000 traceIds...  Each tracesIds has 7 spans, for example:
![image](https://user-images.githubusercontent.com/4739622/41282108-d6cf03a2-6e65-11e8-9eb2-91de56939939.png)
The total spans ： 3000 * 7 = 21000 spans
and
The data flow is:   services ---> zipkin-server ---> Elasticsearch

#### The zipkin-ui only got 2957 ( why not is 3000????)
![image](https://user-images.githubusercontent.com/4739622/41282314-5f34c542-6e66-11e8-8767-0a8bc108fdaf.png)

#### I check the zipkin-ui “/metrics” interface and elasticsearch， nothing wrong：
![image](https://user-images.githubusercontent.com/4739622/41282486-c1b7af40-6e66-11e8-834f-66cf0ef5c253.png)

Why？？？

**Comment by lanyyyy** [comment]
I saw an earlier issue describe this:
https://github.com/openzipkin/zipkin/issues/1841
I will try it firstly

modifing the ES_MAX_REQUESTS do not wors...  :（

**Comment by codefromthecrypt** [comment]
was there any follow-up on this? we can re-open if so. let us know on gitter https://gitter.im/openzipkin/zipkin
