### ISSUE TITLE
Zipkin Server is not able to collect from Kafka

### ISSUE THREAD

**Issue by Anand0583** [openzipkin/zipkin#2097]
I have created a Spring Boot Application and included the Zipkin-Server and also included the collector-kafka of zipkin and enabled the elasticsearch for storage. But for some reason the service is not reading the messages from Kafka and it is reading the messages.

Please attached the Spring Boot Application.  Searched alot in the internet but not able to find out why the service is not reading the messages and persisting into Elastic Search and displaying the same in the UI.

[ZipkinStreamServer.zip](https://github.com/openzipkin/zipkin/files/2113845/ZipkinStreamServer.zip)

Any help is much appreciated.

**Comment by codefromthecrypt** [comment]
there are many things wrong in your project. Firstly, custom zipkin servers are neither necessary to use Kafka, nor supported. This implies that the zipkin server is not a part of your application.

Please use the following example to get started in the right direction https://github.com/openzipkin/sleuth-webmvc-example/pull/8
