### ISSUE TITLE
Make kafka health check meaningful

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2098]
Right now, the kafka health check returns ok eventhough it is not. Let's improve that.

**Comment by jeqo** [comment]
We could solve this by adding an `AdminClient` on the `KafkaColletor`, and query Cluster description on health-check to validate if connection with Kafka is OK, instead of checking Consumer metrics.
WDYT?

**Comment by codefromthecrypt** [comment]
sounds good. any downside? is the admin client sometimes not available
(due to auth or something?)

**Comment by jeqo** [comment]
It will reuse Consumer's properties, so it will fail as Consumer does if no broker available (and try to reconnect and so on).
We can use a very basic query like `describeCluster` to validate that connection is working properly.
If it make sense, I can create a PR to evaluate this solution.

**Comment by codefromthecrypt** [comment]
ok thanks. please raise a PR and bonus points if you can ping a Kafka
committer to validate the health check approach ;)

**Comment by jeqo** [comment]
Great! I have created #2168 and I have ask for validation on Confluent's Slack and Kafka devs mailing list to confirm in the meantime.
