### ISSUE TITLE
Zipkin support for redis as a collector

### ISSUE THREAD

**Issue by rfyiamcool** [openzipkin/zipkin#2099]
We are using Redis in our project and we don't want to go for any other queue, so it will be good if Zipkin provides support for Redis as a collector.

enjoy it & thank you.

**Comment by codefromthecrypt** [comment]
thanks for the interest. It will take a certain amount of more interest for
this to become a default option. Depending on your experience level, you
might be able to create something like this on your own, such as we have
for SQS.
https://github.com/openzipkin/zipkin-aws/tree/master/autoconfigure/collector-sqs

If you want to try, https://gitter.im/openzipkin/zipkin we can talk

**Comment by rfyiamcool** [comment]
yes, thank u.
