### ISSUE TITLE
Spring Boot 2.0.x and Spring Cloud 2.0.x support

### ISSUE THREAD

**Issue by AndyWilks79** [openzipkin/zipkin#2100]
Does Zipkin support Spring Boot 2.0.x and Spring Cloud 2.0.x, specifically Spring Cloud Gateway ?

Our existing configuration which runs on Spring Boot 1.5.9  no longer works under 2.0.1

**Comment by codefromthecrypt** [comment]
i am not sure what you are eluding to, but I will try to answer.

custom servers are unsupported. if you are trying to do a custom zipkin server, I would expect some maintenance moving to 2.0

if you are talking about applications, you might have the wrong support channel as code that instruments spring boot is not here rather in the spring-cloud-sleuth project

**Comment by jorgheymans** [comment]
Question answered, thanks !
