### ISSUE TITLE
Migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by abesto** [openzipkin/zipkin#2102]
CircleCI 1.0 will be sunset August 31. Instead of opening 13 separate issues, I thought this might be an OK place to track the work. List generated with https://github.com/CircleCI-Public/find-circle-yml/.

### Core repositories
 - [x] Done: https://github.com/openzipkin/brave/pull/725
 - [x] Done: https://github.com/openzipkin/zipkin-api/pull/52
 - [X] Done: https://github.com/openzipkin/sleuth-webmvc-example/pull/14
 - [x] Done: https://github.com/openzipkin/b3-propagation/pull/23
 - [x] Done: https://github.com/openzipkin/zipkin-go/pull/67
 - [x] Done: https://github.com/openzipkin/zipkin-aws/pull/95
 - [x] Done: https://github.com/openzipkin/zipkin-gcp/pull/85
 - [x] Done: https://github.com/openzipkin/brave-karaf/pull/6
 - [x] Done: https://github.com/openzipkin/zipkin-azure/pull/49
 - [x] Done: https://github.com/openzipkin/brave-cassandra/pull/9

### Attic

 - https://github.com/openzipkin-attic/zipkin-ui/blob/master/circle.yml (archived)
 - https://github.com/openzipkin-attic/zipkin-sparkstreaming/blob/master/circle.yml (archived)

### Contrib

- [X] Scrapped CircleCI: https://github.com/openzipkin-contrib/zipkin-go-opentracing/pull/109

**Comment by codefromthecrypt** [comment]
thanks for opening this!

**Comment by abesto** [comment]
It uhh... seems like we're done? I'll be optimistic and close this.
