### ISSUE TITLE
Running Zipkin as a standalone war

### ISSUE THREAD

**Issue by dgt-amexio** [openzipkin/zipkin#2103]
Hi team,

I'm currently struggling in having zipkin run as a standalone war (on a Tomcat Server). Whatever configuration I'm attempting to set in the application.properties or boostrap.properties regarding servletPath & uiPath, the application seems unreachable when running on a tomcat container (whereas it works perfectly from the Java command line)
[see attachment below to get my test project, as is]

What am I doing wrong ?
Kind regards

[test.zipkin.zip](https://github.com/openzipkin/zipkin/files/2132420/test.zipkin.zip)

**Comment by codefromthecrypt** [comment]
sorry but what you are trying to do is unsupported.

**Comment by dgt-amexio** [comment]
Thx for your answer. Do you have any plan to get this supported in future release. I cannot figure out why such an application could not run into a J2EE container.
Regards

**Comment by codefromthecrypt** [comment]
think of this like mysql.. do you expect mysql to run in a j2ee container?
How about cassandra or kafka? Why must zipkin run in a j2ee container?

**Comment by codefromthecrypt** [comment]
anyway technically there are a few issues with J2EE. the collectors often
spawn threads which wouldnt be managed. the http POST endpoint is
implemented directly with undertow so it doesnt use servlet. at least these
things are technical hurdles if you want to create and support a J2EE
variant.

Meanwhile be careful as MySQL is also not a target production environment.
The schema is not designed for larger scale data so your configuration may
hit another problem later. Cassandra and Elasticsearch are the more capable
ones.

Finally sometimes people mistakenly think they need or should cohost zipkin
server with their application. If that is why you are looking for J2EE
might be worth looking at our brave examples which show that trace data
recording is decoupled from the zipkin server.

https://github.com/openzipkin/brave-webmvc-example

**Comment by dgt-amexio** [comment]
Thx for your feedback, the point is clear to me now.
