### ISSUE TITLE
Documentation Improvement : What dependency do you need to include to start using the Zipkin library?

### ISSUE THREAD

**Issue by h-karaki** [openzipkin/zipkin#2113]
To get Zipkin up and running locally, without downloading a completed JAR, how does one do that? What are the dependencies needed to get Zipkin Server and UI working? If I go to Spring Initilizr, and download a spring boot project, and want to build this project by including a dependency in the build.gradle and a @EnableZipkinServer annotation in my main class, how would I know to do that from this documentation? Given Zipkin is often used in a PCF environment as well, maybe consider also including the PCF-variation of this dependency?

**Comment by codefromthecrypt** [comment]
what you are asking for is unsupported, which is why we don't document it. If you look at the javadoc on the deprecated `@EnableZipkinServer` annotation, it mentions custom servers are not supported.

What is supported is documented here https://github.com/openzipkin/zipkin#quick-start

**Comment by h-karaki** [comment]
Including Zipkin Server in a spring boot project is unsupported?

**Comment by h-karaki** [comment]
I'm just saying, its not immediately clear how to start developing a Zipkin server.

**Comment by codefromthecrypt** [comment]
developing a custom server is not supported by the community. you can at
your own risk but please don't raise issues if you try against our advice.

Here's the reference I mentioned to you which mentions this:

https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/EnableZipkinServer.java#L25

**Comment by h-karaki** [comment]
Thank you for the clarification. I appreciate it.

**Comment by codefromthecrypt** [comment]
no prob. If there are features you'd like to see.. please raise issues or
add to existing ones about them.

**Comment by missrezie** [comment]
hello, I have a question, would you please contact me at missrezie13@yahoo.com. thank you

**Comment by codefromthecrypt** [comment]
@missrezie you can join https://gitter.im/openzipkin/zipkin to ask a question
