### ISSUE TITLE
sbt default repository is blocked in China, any other building solutions?

### ISSUE THREAD

**Issue by PinkyJie** [openzipkin/zipkin#212]
Sbt's default repository  http://repo.typesafe.com/typesafe/ivy-releases/  is blocked by GFW in China. When I try to execute the command 'sbt', it keeps downloading the jars needed.

So, is there any other repository that sbt can use? Or, any other building solutions?

**Comment by franklinhu** [comment]
Can you reach [Maven Central](http://search.maven.org/)?
I have a branch that ports Zipkin over to using Maven. Would that help? It's not fully functioning yet, so it'd take a bit more time to get it ready for release.

**Comment by PinkyJie** [comment]
Finally, I got a solution using proxy...
