### ISSUE TITLE
How does Undertow project use zipkin?

### ISSUE THREAD

**Issue by JaryZhen** [openzipkin/zipkin#2124]
Im new user zipkin. As a playframework project can use [Play-zipkin-tracing](https://github.com/bizreach/play-zipkin-tracing). How does Undertow project use zipkin? And how to trace between play project to undertow project,I know by undertow side need process request Header something. Can you give me some details?

**Comment by codefromthecrypt** [comment]
looks like this. we trace undertow internally in zipkin as zipkin uses
undertow
https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/internal/brave/TracingHttpHandlerConfiguration.java

**Comment by JaryZhen** [comment]
I have see the doc EnableZipkinServer which is Deprecated . Are there any example about  tracing between play project and  undertow project

**Comment by codefromthecrypt** [comment]
no one has asked for this type of integration example. you can look at
play-zipkin-tracing in github. not sure if it needs any changes for
undertown.

**Comment by jorgheymans** [comment]
question answered, please use https://gitter.im/openzipkin/zipkin for follow questions.
