### ISSUE TITLE
Track number of active requests

### ISSUE THREAD

**Issue by Logic-32** [openzipkin/zipkin#2125]
I can happily report that #1760 has caused our Zipkin instance to be much more stable.  But, to help further tune a server and prevent issues like #2023 it would be nice if a Prometheus metric for "number of active requests" could be added.  That way we could identify peak load times and tune the number of max-requests appropriately.

Essentially, log `HttpCall.semaphore.availablePermits()`.  Normally not a good method to call because of unreliable/synchronization issues but should be safe for the sake of metrics.

Note: this solves a different problem than `counter_zipkin_collector_messages_http` would answer because that `semaphore` gets used for requests that read from storage in addition to those that write whereas the collector increments only for those that write.

If you want to turn this into a case for separating read from write limits I'd be ok with that also :)

**Comment by jorgheymans** [comment]
@anuraaga does Armeria expose this metric already ?

**Comment by anuraaga** [comment]
Yup - confirmed we have `elasticsearch_active_requests` in prometheus now
