### ISSUE TITLE
 zipkin-server-2.7.5 v2 data model can be read

### ISSUE THREAD

**Issue by wuyoushan** [openzipkin/zipkin#2126]
java -jar zipkin-server-2.7.5-exec.jar

The v1 data model can be read. And in the zipkin ui display, can not read the v2 data model.

Download from http://search.maven.org/#artifactdetails%7Cio.zipkin.java%7Czipkin-server%7C2.7.5%7Cjar

can you give me some help ?

**Comment by shakuzen** [comment]
@wuyoushan Please use the latest released version of the server. You can find the quick start instructions here: https://github.com/openzipkin/zipkin/#quick-start

If you have further questions, please ask us on Gitter (https://gitter.im/openzipkin/zipkin) because we prefer to use GitHub issues for feature requests, bug reports, and enhancement requests.

**Comment by wuyoushan** [comment]
Thank you, I did what you said, but still do not support the v2 data model. My operating system windows7 64bit

**Comment by wuyoushan** [comment]
Thank you @shakuzen My data model is missing []

**Comment by codefromthecrypt** [comment]
>
> Thank you @shakuzen <https://github.com/shakuzen> My data model is
> missing []
>
is there a problem where we aren't leniently reading something? Or are you
ok now?

**Comment by wuyoushan** [comment]
1. Windows7 system,jdk1.8
2. java -jar zipkin-server-2.7.5-exec.jar
3 kafka-1.0.1
I don't know why not add [], can not read the v2 data model
https://github.com/wuyoushan/zipkin-kafka-test/blob/master/src/main/java/cqut/wys/biz/KafkaReporterSpanV2.java

 @Override
    public void report(Span span) {
        System.out.println("span to String = " + span.toString());
        //not add [], can not read the v2 data model
        String mess = "["+span.toString()+"]";
        kafkaProducer.send(zipkinTopic, mess.getBytes());
    }

**Comment by codefromthecrypt** [comment]
you can try using our normal kafka reporter, or putting your code in our test to make the effects easier to see 

https://github.com/openzipkin/zipkin-reporter-java/blob/master/kafka11/src/test/java/zipkin2/reporter/kafka11/KafkaSenderTest.java#L61

Meanwhile this issues list is for changes to the server, not troubleshooting. Please use gitter for more help https://gitter.im/openzipkin/zipkin
