### ISSUE TITLE
How can I quickly try out a zipkin demo?

### ISSUE THREAD

**Issue by PinkyJie** [openzipkin/zipkin#213]
I just wanna try out a zipkin demo to check whether it is suitable for my own project. I follow the [Install page](http://twitter.github.com/zipkin/install.html) , and I have already built the zipkin project successfully by using the command `bin/sbt update package-dist`, it shows no errors and all tests are passed. So, what's the next, I can not find a `dist` directory to execute `scp dist/zipkin*.zip [server]`. 

I just wanna see a demo to demonstrate the functionality of zipkin. How can I try out the `Zipkin UI`(maybe the `zipkin-web` directory, I am not sure) to see the rails app?

Maybe the [Install Page](http://twitter.github.com/zipkin/install.html) is out of date?

**Comment by franklinhu** [comment]
Do the log messages say anything about finishing successfully? SBT should dump out where it sticks the zips.

Alternatively, you should be able to run any of the services locally with the scripts in the `bin` directory if you'd just like to try it out.
- `bin/collector`
- `bin/query`
- `bin/web`

**Comment by PinkyJie** [comment]
I found an instruction file `centos6-quickstart.txt` in the 'doc' directory, with the help of this file I finally launched the project. 

New Question!!! It seems that zipkin can not find the services. I open the `localhost:8080` and see the zipkin UI, the `Service` droplist has no items. I open the localhost `localhost:9900` and `localhost:9901`, I can see the hello text.

I think it is the problem of zookeeper, it can not find the servers, right? When I launch the `bin/collector` and `bin/query`, I find some WARNs and ERRORs.

```
WAR [20121231-15:19:57.754] zookeeper: server set empty!
```

```
INF [20121231-16:14:32.895] cassie: Mapping cluster...
FAT [20121231-16:14:32.903] cassie: error mapping ring
FAT [20121231-16:14:32.903] cassie: com.twitter.finagle.FailedFastException
FAT [20121231-16:14:32.903] cassie:     at com.twitter.finagle.NoStacktrace(Unknown Source)
```

**Comment by franklinhu** [comment]
Do you have a Cassandra instance running?

**Comment by PinkyJie** [comment]
Yes, I follow the install page step by step. 
I wanna know that, do I need to rewrite the page `localhost:9900` and `localhost:9901` to provide the source services for monitor?

**Comment by xbeta** [comment]
I have the same issue

**Comment by bmdhacks** [comment]
I'm closing this since we released the SQL support which eliminates all external dependencies.

**Comment by jamescway** [comment]
I had this error `error mapping ring`
I had a network aware instance of cassanda, with replication settings that were different than my laptop.  Changed it with the statment below.

```
cqlsh> describe schema;
CREATE KEYSPACE "Zipkin" WITH replication = {'class': 'NetworkTopologyStrategy', 'datacenter1': '1'}  AND durable_writes = true;

cqlsh> ALTER KEYSPACE "Zipkin" WITH REPLICATION =
  { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
```
