### ISSUE TITLE
Allow user to use any span name

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2141]
Since we use the url path as span name for HTTP requests, we usually have more span names for a service than the 1000 that zipkin reads from the storage.

The issue is that even if I know what's exactly the span name (i.e. `post /login`) the zipkin ui won't let me search for that unless it shows in its list. I usually have to search for a random span name and then manually change the url which is very annoying.

It'd be great if we could remove the requirement of the span name being in the pre-computed list and let the users search on whatever they want

**Comment by drolando** [comment]
Lol there's a PR to allow this in chosen which is open since 2011 and never got merged: https://github.com/harvesthq/chosen/pull/166

**Comment by drolando** [comment]
The main suggestion seems to be to use select2 :/

**Comment by codefromthecrypt** [comment]
This needs to be tread very carefully, as it doesn't just impact us but
also anything downstream or anything aggregation in nature that works off
assumptions that span is low or relatively fixed cardinality. Internally,
this affects how search works, and relaxing this also limits our ability to
improve aggregations.

**Comment by codefromthecrypt** [comment]
example issue which is knock-on effect: https://github.com/openzipkin/zipkin/issues/2139
also the work we are trying to do to relate metrics name to span name would be thwarted as metrics dimensions are similarly fixed cardinality

**Comment by drolando** [comment]
Yeah, the best approach is probably for us to implement https://github.com/Yelp/pyramid_zipkin/issues/93.

That might solve it for most services (as long as they don't have > 1k endpoints)

**Comment by codefromthecrypt** [comment]
thanks for opening the issue though. context around this topic changes
every so often
