### ISSUE TITLE
JSON download button still uses v1 HTTP endpoint

### ISSUE THREAD

**Issue by 595979101** [openzipkin/zipkin#2143]
http://172.16.5.30:9411/zipkin/api/v1/trace/65248810e1002a98

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Jul 20 14:53:14 CST 2018
There was an unexpected error (type=Not Found, status=404).
Not Found

**Comment by 595979101** [comment]
version is zipkin-release-2.10.2

**Comment by shakuzen** [comment]
As part of the [2.10 release](https://github.com/openzipkin/zipkin/releases/tag/2.10.1), we dropped the v1 read HTTP endpoints. If you use the v2 endpoint (as the UI itself does now), it should work. I'm curious: what is the use case for accessing the HTTP endpoint directly?

**Comment by 595979101** [comment]
![image](https://user-images.githubusercontent.com/38642570/42997443-4b96d9ca-8c49-11e8-9ef9-7502d768525f.png)

The download address of zipkin-server.jar is https://repo1.maven.org/maven2/io/zipkin/java/zipkin-server/2.10.2/zipkin-server-2.10.2-exec.jar

**Comment by shakuzen** [comment]
@595979101 Thank you for the additional information. This looks like a bug, then. We should update the UI to use the v2 endpoint.

**Comment by shakuzen** [comment]
@595979101 the fix for this is released now as version 2.10.3.

**Comment by 595979101** [comment]
Ok, thank you. You fixed this bug too fast
