### ISSUE TITLE
the root span's  duration is not equal with  ss-sr

### ISSUE THREAD

**Issue by huhu-sky** [openzipkin/zipkin#2146]
I found that the root span's  duration time is not equal with  (ss-sr) time ,and the first root span just have tow annotation under the propery annotations, so  i think duration should be equal with (ss -sr)
-- 
``` java
{
    "status":"success",
    "code":200,
    "data":{
        "traceId":"04820a393727e7d5",
        "id":"04820a393727e7d5",
        "name":"http:/b2c",
        "timestamp":1532339436420000,
        "annotations":[
            {
                "endpoint":{
                    "ipv4":"10.1.166.177",
                    "port":11001,
                    "serviceName":"tracing-demo-a"
                },
                "timestamp":1532339436420000,
                "value":"sr"
            },
            {
                "endpoint":{
                    "ipv4":"10.1.166.177",
                    "port":11001,
                    "serviceName":"tracing-demo-a"
                },
                "timestamp":1532339436540000,
                "value":"ss"
            }
        ],
        "binaryAnnotations":Array[3],
        "duration":122037,
        "children":Array[1],
        "spanCount":2,
        "services":Object{...},
        "success":true,
        "serverName":"tracing-demo-a"
    }
}
```
the duration is 122.037ms, but the (ss-sr) is 120ms
--
can you explain this for me ,thanks.

**Comment by basvanbeek** [comment]
which instrumentation was used to create this span?

**Comment by huhu-sky** [comment]
@basvanbeek  i use spring-cloud and sleuth integrated with zipkin

**Comment by codefromthecrypt** [comment]
best advice is this. use latest zipkin server which is 2.10.3 This has different javascript than before, especially data conversion.

Then, try your issue again.. if you capture the javascript objects like you have now, also capture the json (ex via the JSON button). Then we can see what we need to do or not.

Thanks!

**Comment by shakuzen** [comment]
@WywTed have you tried with the latest versions? if it is still happening, can you provide the JSON (remove any sensitive data) for us to troubleshoot?

**Comment by huhu-sky** [comment]
sorry for no answering .  I'll  try the latest version and if it still exists, i'll comment later. Thanks you all.
