### ISSUE TITLE
Make debug logging work with zipkin-server

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2149]
I may be wrong, but there may be a packaging/config problem preventing JUL logs (like from the collector) from showing up even when DEBUG is available. This could possibly be a regression if verified.

Ex. the following bad request should show up in console output when the server has `--logging.level.zipkin2=DEBUG`

```
$ curl -X POST localhost:9411/api/v2/spans -H'Content-Type: 
application/json' -d '[ "mary", "had", "a", "little", "lamb"]'
Cannot decode spans
```

seems https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html#howto-configure-log4j-for-logging says to use the log manager, but I don't think that works by default using java -jar

```bash
$ java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -jar zipkin.jar --logging.level.zipkin2=TRACE
Could not load Logmanager "org.apache.logging.log4j.jul.LogManager"
java.lang.ClassNotFoundException: org.apache.logging.log4j.jul.LogManager
```

**Comment by zeagord** [comment]
Looks like this fixed in the spring-boot 2.0.3.RELEASE. I just validated it.

https://github.com/spring-projects/spring-boot/issues/12659

https://github.com/spring-projects/spring-boot/commit/1a0dfa06abdf5ca81b7396c8d882c914c11e7235

**Comment by codefromthecrypt** [comment]
ok latest indeed work, but only if you add the `-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager` to the args...

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2150 makes explicit args not required
