### ISSUE TITLE
ASF Proposal

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2152]
This issue is about moving Zipkin (at least the server and name) into the ASF. It is a result of significant deliberation by the [core team](https://github.com/orgs/openzipkin/teams/core/members).

Background is [in another issue](https://github.com/openzipkin/openzipkin.github.io/issues/51), but a lot of this context has changed since. To be clear, this issue is not another open debate about the merits of CNCF or ASF or Eclipse. Our core team is represented by a dozen people who share no employer. They hold the most history and responsibility in shepherding our works. While not everyone are +1 on ASF, there is a quorum and a general understanding by +0s that this is a mature move. @openzipkin/core members are absolutely free to change their mind, but please do so promptly :)

While it probably goes without saying, we are not soliciting votes from other foundations or zipkin competitors. Please don't interfere.

For the record, here are the motivations of this:
* The majority of OpenZipkin identify closer with a community-focus vs a marketing or commercially focused organization. ASF tends to be the answer here, even if not always.
* A significant amount of our friends are in ASF, not limited to Cassandra, SkyWalking and HTrace. Apache is on the whole quite a "Zipkin friendly" place, and as such less likely to strike tensions than some other choices.
* Some are concerned of a perception of Zipkin being conflated with Adrian. ASF has a clear notion of project management which is easy for anyone who doesn't know OpenZipkin intimately to understand.
* We have had folks offer staff in the past conditional on foundation membership, and also interest in other things like Summer of Code. Formalizing our project helps reduce hurdles like this.
* Some contributors would like to attend events, but can't for financial reasons. ApacheCon has a process for helping sponsor folks to attend events.
* ASF is "china friendly" in so far as a lot of people know about it and know how it works. Projects are built largely without dependencies on things not attainable without breaking the firewall. We want to be accessible for more of our chinese developers and users. These benefits are of course not exclusive to China.
* Finally, we have no means to slow or even evaluate brand abuse apart from complaining into the wind. Abuse of our brand stresses people out even more that we have no resources to counter it. We don't want people stressing with no place to go with that.

We also understand moving isn't free. For example, the formality of release will lead to us having to improve our nightly release process on the server. The 72hr vote on releases will lead to something around monthly release cadence apart from emergencies. Some tools might need to be revamped. Releasers might need to be more aware of things like signatures than they are now. There are several committers dedicated enough to walk this path. Also, we have @michaelsembwever who has offered to champion this after little rest from championing our friends at SkyWalking.

Logistically, this issue will track things including creating the proposal, and possibly tagged for incidentals along the way. Looking very forward to joining the foundation that brought us many exciting technology over many years.

**Comment by wu-sheng** [comment]
+1 for sure.

I am so excited and glad to see a friendly and wide use project to join Apache community. Even I am not a member of `openzipkin/core`. I want to say, I want to offer my help as an initial committer and PPMC member during your Apache incubating or further ways in Apache. 

At least, I can help on License and release processes. After SkyWalking graduated, I think I even can do more.

**Comment by codefromthecrypt** [comment]
@wu-sheng honestly you have acted like a part of Zipkin for a long time. We'd love your help.

**Comment by wu-sheng** [comment]
> @wu-sheng honestly you have acted like a part of Zipkin for a long time. We'd love your help.

@adriancole When you begin to write the proposal, let me know.  WIKI of this repo? Or somewhere else?

**Comment by codefromthecrypt** [comment]
https://etherpad.net/p/zipkin-asf-proposal until someone breaks it.. once we finish drafting.. the proposal, we can post it on the apache wiki (iirc that's where they go) and revise further if needed

**Comment by wu-sheng** [comment]
Good to know.

**Comment by devinsba** [comment]
I'm a solid +1 here, are we planning to include brave in this as well?

**Comment by jcchavezs** [comment]
+1 from my side. I would like us to consider also moving the libraries (at
least the ones in the `openzipkin` namespace.

**Comment by basvanbeek** [comment]
if we put the libraries in the openzipkin namespace in here too, I'd suggest doing a triage of the ones in there now. Maybe not all of them benefit at this time and might need to be demoted to contrib.

**Comment by zeagord** [comment]
+1 from me. I think this is a progressive step.

**Comment by codefromthecrypt** [comment]
we can put brave in there.. it simplifies some of the discussions around
some of the satellite repos such as zipkin-aws.

Do you have any opinion on this?

**Comment by wu-sheng** [comment]
> if we put the libraries in the openzipkin namespace in here too, I'd suggest doing a triage of the ones in there now. Maybe not all of them benefit at this time and might need to be demoted to contrib.

OpenZipkin org could take responsibilities of hosting the related repos, which are willing to donate those to Apache in the future.

**Comment by michaelsembwever** [comment]
+1 (and will be humbled to help on the journey)

**Comment by codefromthecrypt** [comment]
sorry took so long wrote most of the proposal https://etherpad.net/p/zipkin-asf-proposal as a straw man based on jclouds which I am most familiar with. Feel free to make edits if you are a part of the project. you can make notes with your initials if you have a question etc.


reminder using etherpad as it isn't blocked in china.. we can move to normal apache wiki when someone helps with that.

**Comment by ShaneCurcuru** [comment]
[Left two important notes/questions in the proposal -SC].  Overall it looks really good; you've covered all the high points and it seems like the community would be a good fit.

Once ready, someone will need to put the proposal in the incubator wiki; you may need to email general@incubator.a.o "[WIKI] Permissions to add page for proposal" with your wiki username.

Reminder: chat rooms are fine, but always bring final discussion and decision of project changes back to the mailing lists (at Apache).

Also - Apache infra is investigating a new _supported_ chat tool - likely Slack or Rocket.Chat.  Projects can run their own chat instances on other tools (and do their own maintenance work); infra will support rooms and integrations on the main chat tool that is finally chosen (we currently support hipchat, which is going away :sob: )

**Comment by wu-sheng** [comment]
Zipkin proposal page has been added. https://wiki.apache.org/incubator/ZipkinProposal When we are ready, I can move the proposal to Apache WIKI. If I remember right, that WIKI has a different format, sadly, have to do several manual works.

**Comment by abesto** [comment]
Read the proposal, looks pretty solid to me (added a link to the server javadocs, just for completeness' sake). Exciting!

**Comment by wu-sheng** [comment]
> Note: The ASF requires full trademark rights to the project brand before it can graduate. The community would need to figure out during incubation (you have time to do this) if the Apache project would take on a new name or not.  The issue is that you couldn't have a podling releasing 'Zipkin' software while others in the ecosystem are also releasing other parts of 'Zipkin' software. I can help answer some questions, or otherwise the privately-archived trademarks@ mailing list can help figure out what that means

This may cause some side effect to `brave` project, I think?  Zipkin server and zipkin brave are both under `io.zipkin`, right?

**Comment by wu-sheng** [comment]
The proposal has been moved from etherpad.net to Apache WIKI. Anyone has Apache WIKI edit access right could change, or ping me to change.

Here is the address: https://wiki.apache.org/incubator/ZipkinProposal

**Comment by michaelsembwever** [comment]
Under the "Source and Intellectual Property Submission Plan" section I would add a sentence along the lines of:

All source code is copyrighted to 'The OpenZipkin Authors', to which the existing [core](https://github.com/orgs/openzipkin/teams/core) community has the rights to re-assign to the ASF.

**Comment by wu-sheng** [comment]
> Under the "Source and Intellectual Property Submission Plan" section I would add a sentence along the lines of:
All source code is copyrighted to 'The OpenZipkin Authors', to which the existing core community has the rights to re-assign to the ASF.

@michaelsembwever Done. Since GitHub org team member can't be seen from outside, @adriancole known that too, I add this sentence:

`All source code is copyrighted to 'The OpenZipkin Authors', to which the existing core community(members list in Initial Committers) has the rights to re-assign to the ASF.`

**Comment by ShaneCurcuru** [comment]
Replies to above questions:

- The ASF requires full trademark rights to whatever project name and primary software product releases that a podling makes.  (These rights have to be transferred before you can graduate - so there's time to figure out the details, but it is a hard requirement)

So - it depends.  If you want to have "Apache Zipkin" that releases zipkin-client-x.y.zip, then the ZIPKIN name has to be solely given to the ASF; no other projects could release software using the ZIPKIN name.
I'm not sure exactly how Brave works/is branded, but a group outside could continue to release brave-server-x.y.zip if they wanted, and call it "BRAVE" or "BRAVE, powered by Apache Zipkin" or things like that.  They could not call the product being released ZIPKIN BRAVE or anything like that.

Note also that you can choose to change to a new name during incubation if the community wants to (although it doesn't sound like you'd want to).

- The ASF does not want your copyright assignments.  What the ASF does require is IP Clearance of the code drop being donated (verifying that all the IP is licensed such that the ASF can license it without restriction under Apache-2.0), and a signed ICLA license agreement from anyone who wants to be a committer on the new podling at the Incubator.

If that doesn't make sense, don't worry: the point is the ASF only needs the right license for the work, not an actual assignment of the underlying copyright.  Apache committers keep copyright on the code they write; it's just that the ICLA to the ASF ensures the ASF has enough rights to always outbound license any submissions to the world under our license.

**Comment by codefromthecrypt** [comment]
Thanks, @michaelsembwever 

So I presume we will leave the OpenZipkin org for things not in ASF zipkin or not yet. For example, zipkin-ruby, php etc.

Also, there seems to be a soft consensus that zipkin-reporter, brave and zipkin-dependencies (the spark job) would move to ASF initially as that keeps the core java stuff in the same place.

**Comment by codefromthecrypt** [comment]
fire in the hole!!

https://lists.apache.org/thread.html/54798a5059db1d5716ed9910a15c92945509a25ec3b7ccb6b1215c53@%3Cgeneral.incubator.apache.org%3E

**Comment by codefromthecrypt** [comment]
apologies for forgetting to paste, but the formal vote is underway http://mail-archives.apache.org/mod_mbox/incubator-general/201808.mbox/%3C1535339658.3334760.1487003256.1BC04858@webmail.messagingengine.com%3E

**Comment by codefromthecrypt** [comment]
we reverted to OpenZipkin org
