### ISSUE TITLE
Kafka offset commit failures

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2173]
I see a lot of these warnings in the logs:
```bash
2018-08-21 02:33:47.357  WARN 15 --- [pool-2-thread-1] o.a.k.c.c.i.ConsumerCoordinator: 
[Consumer clientId=consumer-10, groupId=zipkin_collector] Synchronous auto-commit of
offsets  {zipkin.traces-1=OffsetAndMetadata{offset=54995069, metadata=''}} failed:
Commit cannot be completed since the group has already rebalanced and assigned the 
partitions to another member.
This means that the time between subsequent calls to poll() was longer than the configured 
max.poll.interval.ms, which typically implies that the poll loop is spending too much time 
message processing. You can address this either by increasing the session timeout or by 
reducing the maximum size of batches returned in poll() with max.poll.records.
```
They seem to trigger a consumer rebalance which slows down everything and make offset distance grow.

I want to try setting those options to see whether they help, but I can't figure out how I pass them to the kafka consumer zipkin uses. Should I use `-Dzipkin.collector.kafka.overrides.auto.max.poll.records=20`? I can't tell if it's being applied or not

**Comment by codefromthecrypt** [comment]
two ways.. look at server logs for "o.a.k.c.c.ConsumerConfig" which
prints out the config used
you can also look at the config values accepted by Spring (which
should influence ^^)

curl -s localhost:9411/actuator/configprops|jq
'.contexts.application.beans."zipkin.collector.kafka-zipkin2.autoconfigure.collector.kafka.ZipkinKafkaCollectorProperties"'

{

  "prefix": "zipkin.collector.kafka",

  "properties": {

    "topic": "zipkin",

    "overrides": {},

    "bootstrapServers": "kafka-zookeeper:9092",

    "groupId": "zipkin",

    "streams": 1

  }

}

**Comment by drolando** [comment]
Thanks, looking at those properties I was able to figure out that I simply needed to specify the `-D zipkin.collector.kafka.overrides` values before the `-jar zipkin-server.jar` otherwise they're ignored.

**Comment by codefromthecrypt** [comment]
ah right. this is subtle.. if after the jar you can use -- syntax ex
--zipkin.collector.kafka.overrides which is a subtely of "system
properties" vs arguments. you can see example of many ways to do
something with the SPRING_APPLICATION_JSON example here
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
