### ISSUE TITLE
i18n failed

### ISSUE THREAD

**Issue by jaydensun** [openzipkin/zipkin#2175]
when i visit index html, error occur below.
it might be because `data-i18n="traces.lookback">` (templates/index.mustache)have not been defined in i18n files.

```
jquery.i18n.properties.js:271 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.$.i18n.prop (jquery.i18n.properties.js:271)
    at HTMLSpanElement.<anonymous> (i18n.js:22)
    at Function.each (jquery.js:354)
    at De.fn.init.each (jquery.js:189)
    at Object.callback (i18n.js:18)
    at callbackIfComplete (jquery.i18n.properties.js:306)
    at loadAndParseFiles (jquery.i18n.properties.js:322)
    at jquery.i18n.properties.js:319
    at Object.success (jquery.i18n.properties.js:349)
    at l (jquery.js:3268)
```

**Comment by codefromthecrypt** [comment]
happened again today:

jquery.js:9600 GET http://***:31399/zipkin/trace_zh.properties 404 (Not Found)
Uncaught TypeError: Cannot read property 'length' of undefined jquery.i18n.properties.js:271 

from @GuangmingLuo

**Comment by codefromthecrypt** [comment]
https://github.com/jquery-i18n-properties/jquery-i18n-properties/issues/103

**Comment by JoveYu** [comment]
same problem, anyone help?

**Comment by codefromthecrypt** [comment]
@JoveYu is same for you? on 'trace_zh.properties'?

**Comment by codefromthecrypt** [comment]
I will try to workaround the problem in the build but making a copy of XXX_zh_CN.properties as XXX_zh.properties

**Comment by codefromthecrypt** [comment]
attempted fix waiting on feedback https://github.com/openzipkin/zipkin/pull/2238

**Comment by codefromthecrypt** [comment]
#2239 should fix this

**Comment by jorgheymans** [comment]
zipkin-classic (https://github.com/openzipkin-attic/zipkin-classic) is no longer maintained, Lens (the new UI) has its own I18N system added in #2487.
