### ISSUE TITLE
Provide methods to  call zipkin APIs

### ISSUE THREAD

**Issue by GuangmingLuo** [openzipkin/zipkin#2181]
Feature:
Provide (static) methods to make calls to [zipkin APIs](https://zipkin.io/zipkin-api/#/)

Explain:
Zipkin expose those APIs to user, and the documentation is written in Swagger. A yaml file is also available for api/v2. In order to make calls to those APIs, users may need use raml or swagger to generate client-side code to make those calls to zipkin server. It's a lot of work and many classes including client implementations and models will be generated.
It would save a lot of work if zipkin itself provide interfaces to make those calls.
 
Example
public static List<Span> getTraceById (String traceId, @Optional String version);
(version could be v1 or v2, due to the version of zipkin that the user uses)

The zipkin server url is defined by user by overriding the following default value:
spring.zipkin.base-url=http://localhost:9411/

**Comment by shakuzen** [comment]
A similar request has been made before (I can search for it later when not on mobile). Could you explain your use case first, though? Why do you want to access the Zipkin HTTP API programmatically? We are under the assumption that in most cases, only the UI and reporters interact with the HTTP API directly.

**Comment by codefromthecrypt** [comment]
see also https://github.com/openzipkin/zipkin-api-example

**Comment by GuangmingLuo** [comment]
@shakuzen  Hi, the use cases could be: user may want to get/post a span; user want to get the trace by traceId. Since the Zipkin APIs are exposed to public, and we can even override the reporter and Tracefilter to add extra tags and so on,  it's is possible that users will make use of those APIs for their own Log & tracing solution. I would be very appreciate if this functionalities can be provided and they will be very helpful.

**Comment by GuangmingLuo** [comment]
@adriancole Hi, many thanks that you show me an example. But pity is that it make uses of swagger for code generation, which I have explained before is very heavy for user. Besides, "localhost:9411" is hard-coded in the example and it's in go. It would be better if a common java library is provided and make use of the user input of spring.zipkin.base-url, and expose those APIs as methods for call.

**Comment by codefromthecrypt** [comment]
so the use case you mention isn't typical, so it is hard to say how much
value there is in publishing this. For example, we don't create features
without 3 folks asking and creating a new library before that happens would
be too early as well, especially under the assumption it would be backed
into a sleuth app :P

I would recommend that you try to use something like feign which if you are
only getting a trace by ID will be easy to do on your own. You make sure
the decoder uses SpanBytesDecoder.decodeList. Can you try this please?

>

**Comment by codefromthecrypt** [comment]
you can also look at some older code here, as well which while written against the v1 api (io.zipkin.java:zipkin code in package zipkin), can be a hint for v2 api (io.zipkin.zipkin2:zipkin code in package zipkin2)

https://github.com/openzipkin/zipkin/commit/8f99f3cf44cbcdc678b9ae845d501ba2fc2422a4#diff-428d6e11ec1d9804af04afc7ecc13c91L33

**Comment by GuangmingLuo** [comment]
@shakuzen You are right, Feign or directly using RestTemplate are the alternatives. I know how to do it. The problem is which is the best solution or the most effective way. User will still need model Span or Trace as entity in this case.

Maybe we can wait for few days if there are other users want the same feature before we close it.
I still believe its would be valuable to have such features. Zipkin GUI is not enough as an output for the whole distributed tracing solution.

**Comment by codefromthecrypt** [comment]
I wonder if somehow we are overthinking this..

There is a library with a decoder, why do you need to do any entity mapping?

List<zipkin2.Span> decoded =
SpanBytesDecoder.JSON_V2.decodeList(your_byte_from_http_response);

There's no concept of Trace in zipkin it is a list of spans.. if only
getting by id using the above makes the code far less text than the
conversation so far.

**Comment by codefromthecrypt** [comment]
here's a working example, where the only dependencies are io.github.openfeign:feign-core and io.zipkin.zipkin2:zipkin

Hopefully this can buy you time as we don't typically enter work like creating a new library etc within days anyway.

```java

  interface Zipkin {

    @RequestLine("GET /api/v2/trace/{traceId}")
    List<Span> getTrace(@Param("traceId") String traceId);

    static Zipkin connect() {
      Decoder decoder = new Decoder.Default() {
        @Override
        public Object decode(Response response, Type type) throws IOException {
          if (response.request().url().contains("/api/v2/trace/")) {
            byte[] bytes = (byte[]) super.decode(response, byte[].class);
            if (bytes == null) return null;
            return SpanBytesDecoder.JSON_V2.decodeList(bytes);
          }
          return super.decode(response, type);
        }
      };

      return Feign.builder()
          .decoder(decoder)
          .logger(new Logger.ErrorLogger())
          .logLevel(Logger.Level.BASIC)
          .target(Zipkin.class, "http://localhost:9411");
    }
  }

  public static void main(String... args) {
    Zipkin zipkin = Zipkin.connect();

    System.out.println(zipkin.getTrace("96e7c98dd2d01b3c"));
  }
```

**Comment by GuangmingLuo** [comment]
@adriancole  You are right, Trace is a list of Span with the same traceId. 
Great to know that there is already a library zipkin2.Span for span and there is a decoder.
In this case, Feign could  be the most effective solution.

Many thanks for the working example.

**Comment by codefromthecrypt** [comment]
no problem. my goal is to make people not blocked.. we are doing a lot
of stuff, like JMS so hard to address everything completely as it
arrives. https://github.com/openzipkin/brave/pull/764

feel free to join https://gitter.im/openzipkin/zipkin to chat more if you like
