### ISSUE TITLE
Unable to store tracing data in  cassandra server 

### ISSUE THREAD

**Issue by Anupma97** [openzipkin/zipkin#2186]
Hello,

I want to store tracing data in my own(custom) Cassandra server. I have manually created below tables in Cassandra.
Tables->
span
dependency
trace_by_service_span
span_by_service

I want that tracing data will store in these tables.  I do not want to allow zipkin server to create table with schema /cassandra3-schema.cql. For this I have set " zipkin.storage.cassandra3.ensure-schema=false " property in application.properties. But as soon as I click on "Find Traces"
button on zipkin UI it starts running cassandra3-schema.cql for table creation. I am new to this. May you please guide me if there is some property available to handle the situation.

Please find code below:
ZipkinServerApplication.java

@SpringBootApplication
@EnableZipkinServer
public class ZipkinServerApplication {

    public static void main(String[] args) {
        SpringApplication.run(ZipkinServerApplication.class, args);
    }
}

Pom.xml dependecies -
<dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.java</groupId>
            <artifactId>zipkin-server</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.java</groupId>
            <artifactId>zipkin-autoconfigure-ui</artifactId>
            <scope>runtime</scope>
        </dependency>
	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>io.zipkin.java</groupId>
			<artifactId>zipkin-autoconfigure-storage-cassandra3</artifactId>
			<version>1.17.1</version>
			<exclusions>
				<exclusion>
					<artifactId>cassandra-driver-core</artifactId>
					<groupId>com.datastax.cassandra</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.datastax.cassandra</groupId>
			<artifactId>cassandra-driver-core</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.datastax.cassandra</groupId>
			<artifactId>cassandra-driver-mapping</artifactId>
			<version>3.1.0</version>
		</dependency>

application.properties -

zipkin.storage.type=cassandra3
zipkin.storage.cassandra3.ensure-schema=false
zipkin.storage.cassandra3.contact-points=contact pt value
zipkin.storage.cassandra3.keyspace=keyspacename
zipkin.storage.cassandra3.username=username
zipkin.storage.cassandra3.password=pwd

**Comment by devinsba** [comment]
So indeed you are building a custom zipkin server. `@EnableZipkinServer` is deprecated and not supported as I said in the chat room. Please check our quickstart documentation for running a supported server configuration: https://github.com/openzipkin/zipkin#quick-start

**Comment by Anupma97** [comment]
Thanks a lot for your quick response . Appreciated !!!
