### ISSUE TITLE
Restful request with @PathVariable cause too many spans

### ISSUE THREAD

**Issue by GavinLin168** [openzipkin/zipkin#2188]
Hi , one of my service requestMapping like below , everytime a new id come in , zipkin will take it as a new span . Finally , when I select span in Zipkin UI , the response was very slow. Any suggestion for this ? Thanks.

       @RequestMapping(value = "/test/{id}" ,method = RequestMethod.GET)
	public String testPathVariable(@PathVariable String id){
		return id;
	}

**Comment by GuangmingLuo** [comment]
Hi, 
I guess you don't quite understand the concept of Span.

["Span: The basic unit of work. For example, sending an RPC is a new span, as is sending a response to an RPC."  ](https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.0.12.RELEASE/)

BR
