### ISSUE TITLE
[Feature request] More flexible MySQL datasource configuration

### ISSUE THREAD

**Issue by aukevanleeuwen** [openzipkin/zipkin#2190]
Currently the MySQL data storage is configured roughly here: https://github.com/openzipkin/zipkin/blob/d47e80433cdf97a78e92712f313ae607e6f61dec/zipkin-autoconfigure/storage-mysql/src/main/java/zipkin2/autoconfigure/storage/mysql/ZipkinMySQLStorageProperties.java#L89-L102

This doesn't give a whole lot of flexibility in the datasource setup. In my case I have a Galera cluster for which I can specify a JDBC url like this: `jdbc:mariadb:failover://host1:3306,host2:3306,host3:3306/database?prop1=true` This allows for failover in case one of the nodes is down.

Even if you use 'plain' MySQL there is still a host of failover configuration options: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-config-failover.html.

Can we perhaps add an optional property to `ZipkinMySQLStorageProperties` to specify the JDBC url directly and if it doesn't exist use the current implementation as a fallback?

Given a property `jdbcUrl`, kind of like this?

```java
    StringBuilder url = new StringBuilder();
    if (getJdbcUrl() != null) {
      url.append(getJdbcUrl());
    } else {
      url.append("jdbc:mysql://");
      url.append(getHost()).append(":").append(getPort());
      url.append("/").append(getDb());
      url.append("?autoReconnect=true");
      url.append("&useSSL=").append(isUseSsl());
      url.append("&useUnicode=yes&characterEncoding=UTF-8");
    }
```

**Comment by codefromthecrypt** [comment]
bear in mind this configuration is noted as not for production. even if we
add an env option for a full url you may still run into performance
problems due to the schema design which is intended for learning not prod.

**Comment by aukevanleeuwen** [comment]
Hmm I didn't really read** it like that. It sounded like if we really put a lot (but what is a lot ??) of data into it, the querying of certain traces and or dependencies would be slow. That is okay for now I think. 

I would like to know if *putting* the data in, so storing the spans, would be going slower as well, thus possibly hampering the clients that are sending the data? (Brave, Sleuth)

Any ball park figure on what 'a lot of data' is?

** https://github.com/openzipkin/zipkin/tree/master/zipkin-storage talks about 'discouraged' for newer systems
** https://github.com/openzipkin/zipkin talks about "The following components are no longer encouraged, but exist to help aid transition to supported ones. "

**Comment by codefromthecrypt** [comment]
I would classify this as use at your own risk as it is double-discouraged,
one for performance and the other for the schema. This means once you are
in production and you hit load problems you'll have to do a migration off
this to elasticsearch or cassandra. If that's ok with you we can look about
adding the url option.
