### ISSUE TITLE
After the test is completed, not all traces are displayed in ui

### ISSUE THREAD

**Issue by gagarinvy** [openzipkin/zipkin#2192]
I use zipkin4net and docker-zipkin to track traces in my application. I have a unit test. Inside a unit test a client is created from which I send a request to the first server, then I send the request from the first server to the second, then from the second service I send a request to the third service, and then I return the response to the client. All this I do with the help of commands ClientSend - ServerReciev-ServerSend-ClientReciev. If the request is one, then all is well. If I send asynchronously 100 requests, then some of the traces are lost. But if I debug the test in debug mode, or when I end the test, I set a delay, then all the traces are displayed. It seems that all the traces simply do not have time to send to the collector. Can you help me?

**Comment by codefromthecrypt** [comment]
troubleshooting is best done on gitter as it usually requires back and
forth. if we do it here people get alerted too much

gitter.im/openzipkin/zipkin
