### ISSUE TITLE
Question: how to customize index formatter timezone of elasticsearch storage

### ISSUE THREAD

**Issue by addozhang** [openzipkin/zipkin#2194]
By default, it is using UTC. New index created at 8:00 am for asia/shanghai zone. 

We hope it created at midnight. So how to customize timezone? 

Thanks.

**Comment by codefromthecrypt** [comment]
I think most people set their timezone on servers to UTC often the
operating system, but also possible at JVM launch I think. we don't plan to
support misalignment with UTC as it is quite common server setup and
everything in the code assumes this.

**Comment by codefromthecrypt** [comment]
closing for now, basically the areas are around the following:

Index creation and span name lookup is based on zipkin2.elasticsearch.internal.IndexNameFormatter. There may be other places, but this is likely where it is. In worst case you can make a copy of this file and change the timezone.. then place it in the front of your classpath.

If we get demand to have this as a normal option we'd need to have integration tests etc to show that it works, but above might work for you right now..
