### ISSUE TITLE
HTTP timeout not handled

### ISSUE THREAD

**Issue by gtzinos** [openzipkin/zipkin#2196]
Hello,

Can I handle HTTP requests which send no response ?

Example:

`   var appzip = require("appmetrics-zipkin")({
      host: "localhost",
      port: 9411,
      serviceName: "frontend",
      sampleRate: 1.0
    });

    var express = require("express");
    var app = express();

    app.get("/timeout", (req, res) => {

    });

    var server = app.listen(9000, () => {

    });

    server.setTimeout(5000);
`

I call /timeout and after 5seconds the server will stop it (timeout) but the Zipkin will not handle this issue.

**Comment by codefromthecrypt** [comment]
sorry I think you opened this against the wrong repository https://github.com/CloudNativeJS/appmetrics-zipkin
