### ISSUE TITLE
Zipkin UI doesn't fail gracefully when no endpoints are found in a Span

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#2197]
View the attached saved traces using Zipkin UI. The UI fails with the error `ERROR: Cannot parse file: TypeError: Cannot read property 'ipv4' of undefined` for the file `missing-endpoint-trace.json` and loads fine when the localEndpoint and remoteEndpoint values are added.

[good-trace.json.txt](https://github.com/openzipkin/zipkin/files/2418213/good-trace.json.txt)
[missing-endpoint-trace.json.txt](https://github.com/openzipkin/zipkin/files/2418215/missing-endpoint-trace.json.txt)

The failure is from skew.js:188

function ipsMatch(a, b) {
  if (a.ipv6 && b.ipv6 && a.ipv6 === b.ipv6) {
    return true;
  }
  **if (!a.ipv4 && !b.ipv4) return false;**
  return a.ipv4 === b.ipv4;
}

**Comment by codefromthecrypt** [comment]
Thanks.. good info tested with trace viewer
