### ISSUE TITLE
 Does not limit the length of the id to a string type

### ISSUE THREAD

**Issue by glmapper** [openzipkin/zipkin#2199]
In the zipkin model, the id value of the span can be set by the String type, but the length can be limited to no more than 16 bits.
```
public Span.Builder id(String id) {
    if (id == null) {
        throw new NullPointerException("id == null");
    } else {
    	int length = id.length();
        if (length == 0) {
            throw new IllegalArgumentException("id is empty");
        } else if (length > 16) {
            throw new IllegalArgumentException("id.length > 16");
        } else {
            Span.validateHex(id);
            this.id = length < 16 ? Span.padLeft(id, 16) : id;
            return this;
        }
    }
}
```
Now we use 0, 0.1, 0.1.1, 0.1.1.1, ..., to describe the spanId. If the link is long, it may exceed 16 bits. Therefore, it is recommended not to set the maximum length or increase the maximum length. .

**Comment by codefromthecrypt** [comment]
we dont support arbitrary string span IDs. a span ID is 64bit encoded as
lower hex

**Comment by jorgheymans** [comment]
Question answered, thanks !
