### ISSUE TITLE
My own brave span connect with springboot tracing?

### ISSUE THREAD

**Issue by imperio-wxm** [openzipkin/zipkin#2200]
Tracing my own brave span like this:

```java
Sender sender = OkHttpSender.create("http://127.0.0.1:9411/api/v2/spans");
AsyncReporter<Span> spanReporter = AsyncReporter.create(sender);
Tracing tracing = Tracing.newBuilder()
		.localServiceName("stand-alone-service")
		.spanReporter(spanReporter)
		.sampler(Sampler.ALWAYS_SAMPLE)
		.propagationFactory(ExtraFieldPropagation.newFactory(B3Propagation.FACTORY, "user-name"))
		.currentTraceContext(ThreadContextCurrentTraceContext.create())
		.supportsJoin(true)
		.build();
HttpTracing httpTracing = HttpTracing.create(tracing);
brave.Span span = tracing.tracer().newTrace().name("stand-alone-service");
span.start();
span.tag("test", "stand-alone-service");
span.annotate("Method In");

okHttpTest(httpTracing); // call springboot with okHttpClient

span.annotate("Method Out");
span.finish();
tracing.close();
spanReporter.close();
sender.close();

private static void okHttpTest(HttpTracing httpTracing) {
	String url = "http://localhost:8082";
	OkHttpClient okHttpClient = new OkHttpClient.Builder().addNetworkInterceptor(TracingInterceptor.create(httpTracing)).build();
	Request.Builder builder = new Request.Builder();
	Request request = builder.url(url).build();
	Call call = okHttpClient.newCall(request);
	try {
		Response response = call.execute();
		System.out.println(response.body().string());
	} catch (IOException e) {
		e.printStackTrace();
	}
}
```

![image](https://user-images.githubusercontent.com/8111349/46194901-4f8b1c80-c335-11e8-8076-5ca65638f7d0.png)

`http://localhost:8082` in `okHttpTest` is a url for springboot, and this project has two traces like this:

![image](https://user-images.githubusercontent.com/8111349/46196046-91699200-c338-11e8-8d4c-1d1fa6fc55a7.png)

Now,I want to connect my own span tracing with springboot tracing like this:

> normal jar (stand-alone-service) ——> springboot2(zipkin-service2)——>springboot1(zipkin-service1)

However `stand-alone-service` can not tracing in springboot's call chain.
How can I make it works?

**Comment by codefromthecrypt** [comment]
the root client span is stand-alone-service.. if you click on the first
span you should see it in the details. the name chosen on the left is based
on servers. if you go to the dependency graph you should see
stand-alone-service.

https://gitter.im/openzipkin/zipkin for more!

**Comment by imperio-wxm** [comment]
@adriancole 

Thanks.

However there is no relation between `stand-alone-service` and `zipkin-service2、zipkin-service1` on stand-alone-service‘s graph.

I want to connect them, but on graph is not.

**Comment by codefromthecrypt** [comment]
probably we need to see the json for the trace. can you click the JSON
button and paste it?

**Comment by imperio-wxm** [comment]
@adriancole 

JSON like this:
```java
[
  {
    "traceId": "1f3be10b8e4d57f9",
    "id": "1f3be10b8e4d57f9",
    "name": "stand-alone-service",
    "timestamp": 1538218281013256,
    "duration": 6125044,
    "localEndpoint": {
      "serviceName": "stand-alone-service",
      "ipv4": ""
    },
    "annotations": [
      {
        "timestamp": 1538218281013272,
        "value": "Method In"
      },
      {
        "timestamp": 1538218287138296,
        "value": "Method Out"
      }
    ],
    "tags": {
      "test": "stand-alone-service"
    }
  }
]
```

There is no `zipkin-service2、zipkin-service1` info, just have `stand-alone-service` local info.

**Comment by codefromthecrypt** [comment]
please use brave-webmvc-example or similar. this looks like you are making
a client call but not using span.kind CLIENT. best to use built in
instrumentation

**Comment by imperio-wxm** [comment]
@adriancole 

If my app not use spring frame,even not web app, just a normal java app.
And this app use okHttp to request spring restful API, it can not tracing in Zipkin?

**Comment by codefromthecrypt** [comment]
issues are a place to discuss changes to code, not general question and
answer.

based on the trace you posted I dont see a bug in zipkin which is the repo
you are discussing on right now. I think you are not instrumenting properly
and should look at brave project and its various readme. I think it would
help both of us if you start with a working example even if you dont use
spring.

Regardless, use existing instrumentation there before creating your own.
for example we have tests which mean we know the scenarios where something
works or not. For example, there is okhttp instrumentation in brave and it
had a README and also is tested.

If you need more discussion please go to https://gitter.im/openzipkin/zipkin
as again issues are for changes not troubleshooting
