### ISSUE TITLE
collect span info  with kafka

### ISSUE THREAD

**Issue by flyer1212** [openzipkin/zipkin#2201]
after i use kafka, the consumer can't get any span?

 - [ ] Question. I want zipkin to send span to kafka, than i will user kafka's consumer to consumer info, but after i do that,   i don't get any infomation,  can you help me?

 - [ ]  My zipkin:  
        - name: zipkin
        image: docker.io/openzipkin/zipkin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9411
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: awslbdnsname:9092

 - [ ] the consumer shows no span information,  but the zipkin ui has  trace info.
      bash-4.4# kafka-console-consumer.sh --bootstrap-server awslbdnsname:9092  --topic zipkin -from-beginning

i  really need your help, thanks a lot!

**Comment by codefromthecrypt** [comment]
sorry issues are not great for support. can you please try https://gitter.im/openzipkin/zipkin
