### ISSUE TITLE
[UI] order service names

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#2204]
It would make sense to alphabetically order the list of services in the 'Service Name' dropdown.

**Comment by jcchavezs** [comment]
Could you elaborate more on this? Since the dropdown allows you to search I
am curious about the value being added by sorting the service names. This
could be easy to do if we sort in frontend tho.

José Carlos Chávez


Den tor. 4. okt. 2018 kl. 15:46 skrev Jorg Heymans <notifications@github.com

**Comment by zeagord** [comment]
It is quite easy to do in the front end. I think it makes sense to sort it
alphabetically.

**Comment by jorgheymans** [comment]
Imagine service names like serviceA_dev, serviceA_test, serviceA_uat,
having them in predictable order instead of all over the place makes for a
better user experience.

Op do 4 okt. 2018 18:10 schreef Raja Sundaram <notifications@github.com>:

**Comment by codefromthecrypt** [comment]
The api doesn't promise any order, but that doesn't mean we can't
lexicographically sort by default in the UI especially as the data is
small. We can also sort in our own api even if that doesn't imply
alternate backends will.

iotw sounds fine.
