### ISSUE TITLE
UI enhancement: allow different units for duration input

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/zipkin#2208]
Currently, the duration input field on the UI forces users to use microseconds as the unit. Microseconds is not a familiar time unit for most people, I assume. We even convert trace durations displayed in trace search results into more familiar units when the duration is long enough (ms or s). I think we can provide a better experience by allowing users to input different units.

Some ideas:
1) dropdown selection of units next to the text field (could still default to microseconds if we want to be least jarring from the status quo)
2) allow specifying of units in the text field while defaulting to microseconds if no units are provided. ex. `1s` for 1 second, `50ms` for 50 milliseconds.

I assume we'll want to restrict the changes to the UI and not touch the actual API, so the UI would need to convert whatever is input to microseconds. If we did want to consider changing the API (in a backwards compatible way, I think), we could look at [Spring's support for `Duration` conversion](https://jira.spring.io/browse/SPR-13721) as long as we can default the units to microseconds.

/cc @zeagord

**Comment by tacigar** [comment]
I prefer 2nd idea! :)

**Comment by shakuzen** [comment]
Resolved by #2260
