### ISSUE TITLE
Configuring Elasticsearch index name monthly?

### ISSUE THREAD

**Issue by linhuiwz** [openzipkin/zipkin#2213]
Hi team,

as we know, zipkin used ES to store data whose index is like zipkin:span-2018-10-15, zipkin:span-2018-10-14, etc. Is there any configuration to set, so ES shows the index by month?

Thanks!

**Comment by codefromthecrypt** [comment]
Eventhough data is stored by day, you can use an index pattern to get
data by month. ex zipkin:span-2018-10-*

**Comment by linhuiwz** [comment]
@adriancole thanks for your quick reply.

**Comment by codefromthecrypt** [comment]
no problem. anything else hop on https://gitter.im/openzipkin/zipkin
