### ISSUE TITLE
Dependencies show non existing connection

### ISSUE THREAD

**Issue by danielkhan** [openzipkin/zipkin#2214]
What kind of issue is this?

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed and stay fixed. If you have a solution in mind, skip raising an issue and open a
       pull request instead.

In a demo environment I have 4 Node.js services.
Node.js is version 8.

The service methods look like that

```js
// express-frontend
router.get('/', async (req, res, next) => {
  try {
    const httpres = await axios.get('http://localhost:3001'); // == service-gateway
    res.render('index', { title: 'Express' });
  } catch(err) {
    return next(err);
  }
});
```
```js
// service-gateway
let toggle = false;

router.get('/', async (req, res, next) => {
  try {
    if(!toggle) {
      await axios.get('http://localhost:3010'); // service-green
      toggle = true;
    } else {
      await axios.get('http://localhost:3020'); // service-blue
      toggle = false;
    }
    res.render('index', { title: 'Express' });
  } catch (err) {
    console.log(err);
    return res.status(500).end();
  }
});
```
`service-blue` and `service-green` are simple express apps with one index route returning 200.

So it's clear that we have a graph in the form A-B=C or D
<img width="617" alt="capto_capture 2018-10-15_04-20-37_pm" src="https://user-images.githubusercontent.com/2722161/46956747-571d2600-d096-11e8-8fc4-82b34e6f5328.png">

Which would be A-B-C and A-D

If I use superagent and regular callbacks, the graph looks correct.
Looks as if there was a context problem with two consecutive http calls in conjunction with await.

**Comment by codefromthecrypt** [comment]
This is a good issue description, perhaps on the wrong project. I think you might be asking about zipkin-js.

Can you re-issue this there, and also include the example code and/or example json associated with the trace. Context issues are subtle so the setup is something likely to be helpful, hence the request for example code or failing unit test.

**Comment by danielkhan** [comment]
I will.
