### ISSUE TITLE
zipkin server cannot support elasticsearch-5.5.2?

### ISSUE THREAD

**Issue by yanggy11** [openzipkin/zipkin#2216]
I have configured es 5.5.2, and it tells me that cannot connect to es, so ziplin does not support es5.5 or higher versions?

**Comment by yanggy11** [comment]
yes, it doesn't support es 5.5, I replaced es5.5 to es 2.4.0, and it works.

**Comment by codefromthecrypt** [comment]
we have tests that run on every build, against ES 5.6.12 (currently)

Please go here for more support https://gitter.im/openzipkin/zipkin
