### ISSUE TITLE
Refactor UI to internally use the v2 model

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2217]
Right now, we pull data in v2 format #1802, but we still operate on it in v1.

**Comment by GuangmingLuo** [comment]
Hi, 
I recently find that I can't search trace by id in this UI [Go to trace] when I use 128 bit traceId for both version 2.10.4 and 2.11, even though it does exist in the DB. 
Does this relate to this issue, or maybe raise a new issue ?
BR

**Comment by codefromthecrypt** [comment]
I will try start this by changing the UI logic step-by-step to eventually use v2 data:

1. break shared v1 spans into single host spans, but still v1 format
Ex. {"cs" "sr" "sa" "ca" "ss" "cr"} -> {"cs" "cr", "sa"},  {"sr" "ss", "ca"}
1. add span.kind, remoteEndpoint annotation to the UI's model temporarily and use it
 {"cs" "cr", "sa"},  {"sr" "ss", "ca"} -> {kind = CLIENT, "cs" "cr", remoteEndpoint},  {kind = SERVER, "sr" "ss", remoteEndpoint}
1. add localEndpoint annotation to the UI's model temporarily and use it
{kind = CLIENT, "cs" "cr", remoteEndpoint},  {kind = SERVER, "sr" "ss", remoteEndpoint} -> {kind = CLIENT, "cs" "cr", localEndpoint, remoteEndpoint},  {kind = SERVER, "sr" "ss",  localEndpoint, remoteEndpoint}
1. complete switch to v2 model
{kind = CLIENT, "cs" "cr", localEndpoint, remoteEndpoint},  {kind = SERVER, "sr" "ss",  localEndpoint, remoteEndpoint} -> {kind = CLIENT, timestamp, duration, localEndpoint, remoteEndpoint},  {kind = SERVER, timestamp, duration,  localEndpoint, remoteEndpoint, shared=true}

**Comment by codefromthecrypt** [comment]
one interesting design luck is that in the current UI we are a little inefficient. We make one traces api query for the index, then redundantly make a trace api query to show the trace view. A better UI will reuse the same data. However when we are porting logic, this is a bit lucky. Since each screen uses a different api, I can break one screen and not break the other one. For example, I can port the search screen to use v2 without touching the trace view screen.

**Comment by codefromthecrypt** [comment]
Another thing to consider. We should have stub/mock data that includes some interesting traces:
* trace with clock skew
* regular RPC trace
* messaging trace

This way we can validate the UI behavior without being data dependent, even if that is visually comparing.

**Comment by codefromthecrypt** [comment]
sample data is now in. I will do the trace summary screen conversion to v2 first as it is simplest and decoupled from the trace view one
