### ISSUE TITLE
style error when text overflow

### ISSUE THREAD

**Issue by kawais** [openzipkin/zipkin#2221]
![image](https://user-images.githubusercontent.com/8424926/47602811-5da48980-da16-11e8-89cc-3bd21495bc04.png)

if annotate too long, it overflow the content div

**Comment by zeagord** [comment]
Can you let know whether this is happening in all the browsers? Or any
specific one?

**Comment by kawais** [comment]
it happening in
chrome  69.0.3497.100(64bit)
firefox 61.0.2 (64 bit)
edge  42.17134.1.0

and white blank page in ie11
![image](https://user-images.githubusercontent.com/8424926/47627945-e8e46300-db6d-11e8-86b7-e8d29d85d0b6.png)
