### ISSUE TITLE
Add support for pagination of trace query results

### ISSUE THREAD

**Issue by sunyaox** [openzipkin/zipkin#2240]
How to add scroll paging using ES？

**Comment by codefromthecrypt** [comment]
this would imply many things notably an api change for pagination tokens

**Comment by sunyaox** [comment]
Thank you for your quick response.I want to try again.

**Comment by codefromthecrypt** [comment]
I think for normal trace browsing, best to use the UI. If you need to scroll through many pages and hold your place between them, it might hint another tool right now. For example, we have a spark job to run through all data to make the dependency graph.

Are you interested in this for normal browsing? How many pages of traces do you think you'd need to see. I think some look at 100 traces (as opposed to 10 pages of 10), as long is the data is small you can consider just loading more.

**Comment by sunyaox** [comment]
We now have large amounts of data, millions, and we need a normal paging. That's why I consulted you. Just like using ES query, the'from'and'size' parameter is set.

**Comment by codefromthecrypt** [comment]
yes, this is not going to work in the API. I think a user will be unlikely
to scroll through millions of records, but anyway will hold the issue open
for you.

Meanwhile, it is like better to focus on using Elasticsearch tools as if
you need to sift through millions and you cannot through the query we
provide, maybe you can with their tools.

**Comment by sunyaox** [comment]
OK, thanks again for your reply. Thank you very much.
We need to customize some functions. But now using the Zipkin you developed is very good.
