### ISSUE TITLE
java.lang.IllegalArgumentException: Could not detect the span format

### ISSUE THREAD

**Issue by iwanskit** [openzipkin/zipkin#2242]
Hi,

I'm using
https://github.com/Yolean/kubernetes-kafka
project in latest version for kafka deployment
and I want to use zipkin (at latest version) as a tracing system 
but I'm stuck becouse when I publish message via kafka I get (on zipkin logs): 
**java.lang.IllegalArgumentException: Could not detect the span format**
I also see counter.zipkin_collector.messages_dropped.kafka incrementation on /metrics endpoint.
This is a bug? or it's me doing something wrong?

Thank you for any help.

**Comment by iwanskit** [comment]
I also tried to deploy kafka and zipkin locally (without kubernetes) but with the same error

**Comment by codefromthecrypt** [comment]
please use http://gitter.im/openzipkin/zipkin for support

otherwise we spam all watchers of the repo with question reply such as what
is producing the spans, what format etc.
