### ISSUE TITLE
How to regist zipkin server to Eureka？ 

### ISSUE THREAD

**Issue by Jungle666** [openzipkin/zipkin#2244]

**Comment by codefromthecrypt** [comment]
Eureka isn't formally supported, but there is a workaround available here: https://github.com/openzipkin/zipkin/issues/1870#issuecomment-432659584

please prefer https://gitter.im/openzipkin/zipkin for questions as issues alert everyone. Take care!

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/3671 will add eureka registration

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/brave-example/tree/master/webmvc5-sleuth shows this works.
