### ISSUE TITLE
JSON button misaligned in the latest UI

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2253]
![image](https://user-images.githubusercontent.com/3317638/48568623-a54f6000-e8b4-11e8-9c86-35c0552b0d32.png)

Not sure if it's wanted or a bug, but in the latest UI the JSON is not at the top-right corner of the container but it's treated just like another "total spans" label. Having that button floating in the middle seems a bit weird to me.
Those labels seem to be much more widely spaced than before too.

**Comment by drolando** [comment]
cc @zeagord

**Comment by zeagord** [comment]
Sure. I will fix this or can we wait for the new UI? Because I was under the impression that we don't want to spend effort on the current UI unless it is a show stopper.

**Comment by shakuzen** [comment]
Resolved by #2259
