### ISSUE TITLE
cannot send msg to client when use spring WebSocket and zipin 

### ISSUE THREAD

**Issue by HelloDhero** [openzipkin/zipkin#2255]
now this is my error message ,when i remove zipkin dependenys ,the web socket word success.

org.springframework.messaging.MessageDeliveryException: Failed to send message to ExecutorSubscribableChannel[clientOutboundChannel]; nested exception is java.lang.UnsupportedOperationException, failedMessage=GenericMessage [payload=byte[418], headers={spanTraceId=0b2fb4255f2c30dc, spanId=1d748c7d4faa4d13, spanParentSpanId=b7711fb5a760c9f8, simpMessageType=MESSAGE, nativeHeaders={spanTraceId=[0b2fb4255f2c30dc], spanId=[1d748c7d4faa4d13], spanParentSpanId=[b7711fb5a760c9f8], spanSampled=[0], simpOrigDestination=[/user/topic/img]}, simpSubscriptionId=sub-0, conversionHint=method 'greeting' parameter -1, spanSampled=0, contentType=application/json;charset=UTF-8, simpSessionId=3yk213vd, simpDestination=/topic/img-user3yk213vd}]

**Comment by HelloDhero** [comment]
the follow is spring document


Even though the MessageHeaders implements Map, it is effectively a read-only implementation. Any attempt to put a value in the Map will result in an UnsupportedOperationException. The same applies for remove and clear. Since Messages may be passed to multiple consumers, the structure of the Map cannot be modified. Likewise, the Message's payload Object can not be set after the initial creation. However, the mutability of the header values themselves (or the payload Object) is intentionally left as a decision for the framework user.

**Comment by codefromthecrypt** [comment]
please join https://gitter.im/openzipkin/zipkin as it isn't clear how this relates to the server project. possibly this is for the sleuth library?

**Comment by ivangfr** [comment]
@duanhairuo @adriancole I am having the same problem. Did you guys find the reason and, mainly, how to fix it? Best,

**Comment by codefromthecrypt** [comment]
I have the same feedback. it isn't clear how this problem relates to the code in this repo. Please join gitter if you'd like to discuss  https://gitter.im/openzipkin/zipkin
