### ISSUE TITLE
JS errors when loading the homepage in the UI

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#2257]
Seeing the attached errors when loading the homepage. Also only the label "Zipkin Investigate System Behavior" appears and rest of the UI then after few milliseconds. This issue is appearing only after upgrading to the latest UI, Zipkin version 2.11.8.

![image](https://user-images.githubusercontent.com/1772168/48600652-9d79d500-e921-11e8-8edb-cd6bb3979c06.png)

**Comment by codefromthecrypt** [comment]
seems related to https://github.com/openzipkin/zipkin/pull/2247 recently
improved by @tacigar

can you try snapshot? not sure the above fixes all of it. that i18n library
we use is unfortunately abandoned. we have an open issue to replace it.

**Comment by melloware** [comment]
I have this JS error as well on 2.11.8  Haven't tried the SNAPSHOT release yet to see if its fixed.

**Comment by codefromthecrypt** [comment]
snapshot should sort this out, so would appreciate if you can try it

**Comment by melloware** [comment]
Tested with 2.11.9 this morning and still happening.

![image](https://user-images.githubusercontent.com/4399574/49377947-72d99b80-f6d9-11e8-9ee4-cbb696ea8fce.png)

**Comment by codefromthecrypt** [comment]
This is related to the i18n library we use. We don't have cycles to address this in the classic UI. Lens might not use the same library in #2487
