### ISSUE TITLE
Support client certificate authentication Elasticsearch Storage

### ISSUE THREAD

**Issue by arap** [openzipkin/zipkin#2266]
Currently Zipkin uses OKHTTP client to connect to ES Storage.  Its built using builder in `zipkin2.autoconfigure.storage.elasticsearch.ZipkinElasticsearchOkHttpAutoConfiguration#elasticsearchOkHttpClient`. However, it ignores keystores loaded by `-Djavax.net.ssl.keyStore` parameter, making it impossible to authenticate using client certificate.

So far I managed to bypass this problem by adding `builder.sslSocketFactory((SSLSocketFactory) SSLSocketFactory.getDefault());`, so that everything looks like that:

```
  @Bean
  @Qualifier("zipkinElasticsearchHttp")
  @ConditionalOnMissingBean
  OkHttpClient elasticsearchOkHttpClient(
      @Value("${zipkin.storage.elasticsearch.timeout:10000}") int timeout) {
    OkHttpClient.Builder builder =
        elasticsearchOkHttpClientBuilder != null
            ? elasticsearchOkHttpClientBuilder
            : new OkHttpClient.Builder();


    for (Interceptor interceptor : networkInterceptors) {
      builder.addNetworkInterceptor(interceptor);
    }

    builder.sslSocketFactory((SSLSocketFactory) SSLSocketFactory.getDefault());
    builder.connectTimeout(timeout, TimeUnit.MILLISECONDS);
    builder.readTimeout(timeout, TimeUnit.MILLISECONDS);
    builder.writeTimeout(timeout, TimeUnit.MILLISECONDS);
    return builder.build();
  }
```

however I'm not sure if it's a full solution.

**Comment by devinsba** [comment]
It looks like OkHttp should already configure this by default with our configuration.

We don't change the default TLS modes and therefore would hit this block of code: https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java#L257...L259

I'm not sure the mechanisms this loader supports for X509 but you should be able to configure it in the way supported by OkHttp

**Comment by arap** [comment]
OKHttp configures only trustmanager verifying server certificates, but it does not configure keystore. 
Thats related with https://github.com/square/okhttp/issues/1711#issuecomment-377132486.

**Comment by codefromthecrypt** [comment]
we could consider supporting the javax.net.ssl.keyStore properties in our ES autoconfiguration. I don't really want to create any new variables and this. I understand okhttp's reply on the topic, but when we are running a server, we are controlling the binary and its only use is for zipkin.

@arap would you be up to trying this? Goal will be to only affect the autoconfiguration types in our ES code

**Comment by arap** [comment]
@adriancole I can contribute, but I don't fully understand Your point. 
Should autoconfiguration rely on javax.net.ssl.keyStore JVM variable, application property, or something else?

**Comment by codefromthecrypt** [comment]
as the server is most often used as a black box, and there's high value in
re-using existing docs, I'd prefer usage of "javax.net.ssl.keyStore"
properties and friends.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/tree/master/zipkin-server#using-a-custom-key-store-or-trust-store-ssl
