### ISSUE TITLE
Unsupport v1 format in trace viewer screen

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2269]
The current UI will soon be v2 format internally. Converting from v1 to v2 format is not trivial. I suggest we drop v1 from the trace viewer screen and suggest people ask on gitter if they need it.

Note: this does not mean we remove the `POST /api/v1/spans` endpoint. In fact that's an alternative to the trace viewer. This is only discussing the support tool we use which allows you to view a saved trace without it being in storage.

cc @openzipkin/ui

**Comment by codefromthecrypt** [comment]
spiked https://github.com/openzipkin/zipkin/pull/2270 in case folks agree

**Comment by shakuzen** [comment]
Sounds good to me. If it causes too much trouble for folks we can reconsider then.

**Comment by zeagord** [comment]
I think we can remove the v1 from the traceviewer page. If it is trouble, can we convert the v1 traces to v2 after the upload and present in the view ?

**Comment by codefromthecrypt** [comment]
indeed. we can convert using local server or post to the actual server

**Comment by codefromthecrypt** [comment]
rule of 3. if later things get hectic, it will force the issue of v1 -> v2 client side and we'll take it from there.
