### ISSUE TITLE
Revisiting zipkin-ui zoom feature

### ISSUE THREAD

**Issue by huydx** [openzipkin/zipkin#2283]
**Feature:**
We need better UX for zipkin-ui zoom feature. Current zoom feature is not user-friendly. Actually I don't even know that the zoom feature exist, before accidentally click in the trace graph.

**Prior Art**
 * Jaeger UI

**Comment by codefromthecrypt** [comment]
At atlassian, they like a "mini-map" like in video games. They like the preview version of zipkin lens.

**Comment by codefromthecrypt** [comment]
Others like mini-map as well. We can look at Chrome and Firefox developer tools for examples (besides Zelda)

**Comment by lambcode** [comment]
Some things I'd like to see:
* A way to reset zoom
* Zooming into a certain time frame will filter the spans below to only those that were open during the window. (and all of it's parent spans back to the root for contextual info). This would help manage "tall" traces

**Comment by codefromthecrypt** [comment]
@lambcode can you try latest zipkin with the lens UI and raise an issue for any glitches? we will close this issue as the zoom was rewritten as a minimap

**Comment by lambcode** [comment]
Thanks @adriancole. I've opened https://github.com/apache/incubator-zipkin/issues/2601 as an additional feature request to reset the zoom.
