### ISSUE TITLE
Differentiate services in the trace detail view by color

### ISSUE THREAD

**Issue by huydx** [openzipkin/zipkin#2284]
**Feature:**
Current trace search view only gives us a list of traces, which is not user friendly because user need to take a closer look to find what they're looking for. Have a nice representation of search result like plotting traces in timeline may make it easier to view

**Prior Art**
 * Jeager UI

**Comment by codefromthecrypt** [comment]
Atlassian said one reason they don't like jaeger was exactly this feature! What they said was that the plotting of traces in Jaeger seemed distracting and random. In other words, we should try not to emulate them.

What they suggest instead is make sure services are color-coded. They like that you can preview a trace by clicking on it. If doing histogram, do it in a different screen, and only do it based on service+span name (ex maybe same data as trace query but different screen)

**Comment by codefromthecrypt** [comment]
I think this is fixed in lens now
