### ISSUE TITLE
Resize or scroll span detail panel instead of wrapping

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2291]
When text is longer, it wraps. @drolando suggested we try to get on one line.. I agree

![image](https://user-images.githubusercontent.com/64215/49122102-253ee680-f307-11e8-9c61-23d48fcf7edf.png)

**Comment by codefromthecrypt** [comment]
@tacigar @zeagord either of you able to knock this one out?

**Comment by tacigar** [comment]
OK I'll do that

**Comment by codefromthecrypt** [comment]
so we should think about the default policy for formatting big text and the use cases where it would be big. Usually this is request/response tags like SQL query and it may well be the best to not wrap these data.

lens currently wraps

**Comment by jorgheymans** [comment]
This refers to Zipkin Classic UI which has been deprecated. If you find there are still similar wrapping issues in Lens please open a new ticket.
