### ISSUE TITLE
Don't pop-out span details

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2293]
Discussed with Atlassian and they said pop-out of span details is not nice compared to a sidebar which opens left when you click a span. The reason is that the pop-out loses your place in the trace. The trace detail screen should optimize for finding the place, so pop-out works against that.

IOTW consider replacing pop-out with sidebar or something else.

**Comment by devinsba** [comment]
I feel like having the details slide down like a drawer out of the span might be more natural way to show that information, then it is even tied to the context

**Comment by shakuzen** [comment]
What about a separate pane that instructs to click on a span to see details? This would provide a separate area that doesn't mess with viewing the trace and work to guide people to knowing they can click on spans to view more details.

**Comment by Logic-32** [comment]
Where ever this gets put it would be nice if consideration for a lot of annotations were made.  It doesn't happen often, but we sometimes get a lot of annotations on a span so a scrollbar/etc... for making it easy to navigate the details would be nice.

**Comment by codefromthecrypt** [comment]
>
> Where ever this gets put it would be nice if consideration for a lot of
> annotations were made. It doesn't happen often, but we sometimes get a lot
> of annotations on a span so a scrollbar/etc... for making it easy to
> navigate the details would be nice.
>
do you have an example trace? I agree we sometimes get large amounts of
tags or annotations, sometimes json.

**Comment by codefromthecrypt** [comment]
one way to visualize what I meant to suggest is comparing to other
things.. lacking a mock-up tool :)

so in the trace search screen, an accordion (down arrow or otherwise)
to show a trace preview seems ok because you aren't blocking a part of
the trace when viewing, rather the next result (a different trace).
This could be a problem in viewing one trace.. ex if you had an
accordion that pushed details down, you have the same block the trace
problem as pop-out, except that you can see above it.

Not UX person, but trying to relate the sentiment.. let's say instead
when you select a span you see a preview on a full length vertical
pane on the right side. This has the same position regardless of which
span you select, which means you can easily tell difference between
tags etc. It doesn't block the trace, or make you have to move too
much (you can consider we could use arrow keys to select a span, not
just mouse). It would re-render on each seletion similar to a checkout
screen where the right side has a total which updates when you change
shipping on the left.

**Comment by drolando** [comment]
@adriancole https://github.com/msindwan/zipkin-view has that same accordion that you're describing I think. And there's a screenshot there in the README

**Comment by codefromthecrypt** [comment]
> @adriancole https://github.com/msindwan/zipkin-view has that same accordion that you're describing I think. And there's a screenshot there in the README

Thanks, Daniele. Yeah so the idea is to move it to a pane on the
right, which fixes the position of things. As tags are less volatile
than timeline, might be best to actually order tags above. Anyway good
call that is the comparison I meant.

**Comment by codefromthecrypt** [comment]
Here's an image of what I meant. I used osx preview app with annotate function as I am not more fancy :)

<img width="1022" alt="screen shot 2018-11-29 at 9 07 59 pm" src="https://user-images.githubusercontent.com/64215/49215426-e26f3280-f41c-11e8-889a-2c944c0f423c.png">

**Comment by codefromthecrypt** [comment]
lens right now has a drop under which doesn't seem to lose place in the trace list as it is easy to undo it. I'll reopen this issue if folks feel it isn't working.
