### ISSUE TITLE
improve performance of our trace detail page

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2314]
I think we are probably not doing things in the most efficient way. I'm hoping maybe someone like @ghermeto could review some of our code for opportunities for improvement or even better improve it. Goal would be to ensure faster rendering of traces with 1k spans (look at zipkin-ui/testdata for examples)

Notably the following files would be helpful to get some performance advice on, and especially some thoughts on tooling to ensure we know how well they are doing:

zipkin-ui/js/component_data/skew.js
zipkin-ui/js/component_data/spanCleaner.js
zipkin-ui/js/component_data/spanNode.js
zipkin-ui/js/component_ui//traceSummary.js
zipkin-ui/js/component_ui//traceToMustache.js

cc @openzipkin/ui

**Comment by jcchavezs** [comment]
Spoiler alert, he is always doing benchmarks.

Den ons. 5. des. 2018, 13:02 skrev Adrian Cole <notifications@github.com:

**Comment by ghermeto** [comment]
I can take look this weekend... For Node.js I usually use [Benchmark.js](https://www.npmjs.com/package/benchmark) which powers JsPerf or [Autocannon](https://www.npmjs.com/package/autocannon) for HTTP/1.1.

Although Benchmark.js works for javascript in general, it doesn't help with rendering, so I ask around here...

**Comment by ghermeto** [comment]
@redsunsoft this is the ticket

**Comment by tcasparro** [comment]
We gave this a try with "smartthings-oauth-authorization.json" data and it rendered quite quickly.  Are we reproing correctly?

**Comment by codefromthecrypt** [comment]
@redsunsoft so mainly were hoping for a code review in case there are some ways to improve perf. There is a lag loading that trace, it doesn't snap, but larger traces can be slower. It is all subjective I guess. I know larger traces are problematic (approaching 10k spans), but we don't have one here.

At the moment, the new UI is under zipkin-lens, so probably feedback there will end up with highest value.

At any rate an example setup for benchmarking added to help track down perf concerns would be good if you have integration ideas and/or instructions.

**Comment by tcasparro** [comment]
Got it.  I'll take a read through the code.

**Comment by codefromthecrypt** [comment]
thanks @redsunsoft and happy holidays!

**Comment by tcasparro** [comment]
Took a good look at the code and React scripts but nothing jumped out to me.  Your composition and lifecycle hooks all seem to be fine.  So unless there's a specific issue that needs attention, you're looking good with the new codebase.

**Comment by codefromthecrypt** [comment]
thanks much!
