### ISSUE TITLE
Make zipkin-lens use the same or similar color scheme to the previous UI

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2321]
We've had a number of informal feedback that people like the old color scheme. Let's switch zipkin-lens to something that is less shocking?

**Comment by tacigar** [comment]
OK!

**Comment by tacigar** [comment]
Done.
Can I close this issue?

**Comment by codefromthecrypt** [comment]
I will close in a sec.. just waiting for latest docker build and will
verify manually :D

**Comment by codefromthecrypt** [comment]
oops I think I released docker too fast :) few more minutes

**Comment by codefromthecrypt** [comment]
<img width="971" alt="screen shot 2019-01-24 at 5 06 12 pm" src="https://user-images.githubusercontent.com/64215/51667364-e40f3e00-1ffa-11e9-9114-fd05022c69f3.png">
