### ISSUE TITLE
zipkin API do not work

### ISSUE THREAD

**Issue by yuanxuzhang** [openzipkin/zipkin#2336]
zipkin-server-2.10.1,
when i call "/api/v2/traces",it return: 
{
    "timestamp": "2018-12-20T06:12:35.399+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Request processing failed; nested exception is java.lang.IllegalStateException: response for aggregation failed: {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"zipkin:span-2018-12-20\",\"node\":\"rmzO69V0QZusghxl0KUsBA\",\"reason\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.\"}}]},\"status\":400}",
    "path": "/api/v2/traces"
}

**Comment by zeagord** [comment]
Looks like the index templates are getting created. It will be easier to troubleshoot and help in gitter. 

https://gitter.im/openzipkin/zipkin
