### ISSUE TITLE
Css Error Zipkin UI Not FIT BOX Details Trace

### ISSUE THREAD

**Issue by jhonatanforero** [openzipkin/zipkin#2339]
Hi ,

CSS style error in trace details for version major 0.13.0

Huge String not fit in the box.

<img width="1637" alt="captura de pantalla 2018-12-27 a la s 11 22 08 a m" src="https://user-images.githubusercontent.com/5290238/50487689-4e699a00-09cd-11e9-8081-09898e6aecdf.png">

<img width="1397" alt="captura de pantalla 2018-12-27 a la s 11 48 40 a m" src="https://user-images.githubusercontent.com/5290238/50487723-66411e00-09cd-11e9-8a6d-0593c5877f16.png">

**Comment by codefromthecrypt** [comment]
we should look into the formatting here.

**Comment by codefromthecrypt** [comment]
duplicate of #2417
