### ISSUE TITLE
[storage-elasticsearch] why all the es ports must be the same?

### ISSUE THREAD

**Issue by maoling** [openzipkin/zipkin#2340]
read the [doc ](https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/elasticsearch) to see this:
> You can alternatively supply a list of http base urls. This list is used to recover from failures. Note that all ports must be the same, and the scheme must be http, not https.

that means: **http://elasticsearch-1:9200,http://elasticsearch-2:19200** isn't  supprted?
if need this to be improved,I can give a PR!

**Comment by codefromthecrypt** [comment]
currently, we use okhttp DNS trick to round robin across the multiple
hosts. if you know an alternative way that works with mixed ports feel feel
free to propose!

**Comment by codefromthecrypt** [comment]
I can take a second look to see if there's a way

**Comment by maoling** [comment]
Let me take a look

**Comment by codefromthecrypt** [comment]
https://github.com/square/okhttp/issues/4530 will solve this the right way. meanwhile I will take a quick look to see if any way now (hack)

**Comment by codefromthecrypt** [comment]
we are currently using okhttp3.Dns which is InetAddress, not InetSocketAddress. Sorry we cannot support mixed ports until some other feature like loadbalancer happens or someone else is more clever.

cc @swankjesse

**Comment by maoling** [comment]
@adriancole 
- yes,if `okhttp3.Dns` use `InetSocketAddress`,the problem will be solved.
- the problem seems to be not very urgent,if really need,we can implement a simple `round robin` using the `InetSocketAddress` inside（：D）.
- I don't know why choose` okhttp3` which's more suitable for mobile development?

**Comment by codefromthecrypt** [comment]
- I don't know why choose okhttp3 which's more suitable for mobile
   development?

We chose okhttp because it is a clean, well designed library, that keeps
api portability in mind. It is not exclusively targeted to mobile dev even
if they care about android.

**Comment by codefromthecrypt** [comment]
everything works now. we changed the implementation. please try 2.16.2 or later!
