### ISSUE TITLE
Excuse me,Why I searched noting

### ISSUE THREAD

**Issue by liuzigenius** [openzipkin/zipkin#2346]
I use 2.11.12 zipkin-server, and start it.
Then I make a simple demo by brave-instrumentation-spring-webmvc, and could see data from request like  this : http://127.0.0.1:9411/api/v2/traces/

response:
[[{"traceId":"4e37a5676dad79c1","id":"4e37a5676dad79c1","kind":"CLIENT","name":"get","timestamp":1547112429074375,"duration":11127,"localEndpoint":{"serviceName":"lxtest","ipv4":"10.14.80.31"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":8014},"tags":{"http.method":"GET","http.path":"/logservice/log/v1/testrecive"}}],[{"traceId":"e6a3f3768f1b9378","id":"e6a3f3768f1b9378","kind":"CLIENT","name":"get","timestamp":1547112427774609,"duration":59735,"localEndpoint":{"serviceName":"lxtest","ipv4":"10.14.80.31"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":8014},"tags":{"http.method":"GET","http.path":"/logservice/log/v1/testrecive"}}]]

but use UI to search:
![default](https://user-images.githubusercontent.com/13098253/50959467-fa4ad380-14fd-11e9-9a55-797c64958a36.PNG)

it turned to noting like that:

![2](https://user-images.githubusercontent.com/13098253/50959484-06369580-14fe-11e9-9d17-4abbfbdc4493.PNG)

it seems no error:

![3](https://user-images.githubusercontent.com/13098253/50959529-223a3700-14fe-11e9-88ee-d688faa0a0e5.PNG)

If I missed something? please help

**Comment by liuzigenius** [comment]
![4](https://user-images.githubusercontent.com/13098253/50966003-9bda2100-150e-11e9-9cf9-8460075ec51e.PNG)

I see console has a error like that, it seems like js has some exception...

**Comment by codefromthecrypt** [comment]
can you please use gitter for troubleshooting? https://gitter.im/openzipkin/zipkin

issues spam people with lots of messages.
