### ISSUE TITLE
Return service only one but from the trace, you can find more services

### ISSUE THREAD

**Issue by huhu-sky** [openzipkin/zipkin#2349]
![62c30501-7a06-4beb-80b2-0e04bdc5ebc0](https://user-images.githubusercontent.com/12699301/51230273-5ac48f80-199a-11e9-9d6e-620691733dfe.png)

**Comment by huhu-sky** [comment]
Use zipkin-server 2.11.12 , storage_type is es(5.x), and use rabbitmq to transport data.
{"zipkin":{"version":"2.11.12"}}

**Comment by zeagord** [comment]
It's not a bug. what you're seeing is a remote endpoint service name which is not instrumented. Join the gitter https://gitter.im/openzipkin/zipkin if you have questions.

**Comment by huhu-sky** [comment]
@zeagord  but one day ago, i can find two service from /services api， and today it's just one.  This is the second time i found this situation.

**Comment by zeagord** [comment]
What is your backend? Are you trying out Zipkin? Please join gitter it will be easier to help and debug.

**Comment by huhu-sky** [comment]
ok, i will discuss it on gitter.
