### ISSUE TITLE
Feature request: logz.io storage option

### ISSUE THREAD

**Issue by yyyogev** [openzipkin/zipkin#2355]
logz.io is an elastic-search based monitoring service
We would like to contribute by adding logz.io storage option along with Cassandra, elastic-search and the rest. 
Is that something you would be willing to merge in?

**Comment by zeagord** [comment]
Logz.io is very interesting and would welcome additional storage support. However it is best to keep it separate for now. We have several attempts to add influxDB, Postgresql, MongoDB but the interest faded. We can keep this in your repo and move when the community feels it is appropriate to merge it zipkin code.

**Comment by yyyogev** [comment]
OK, Thanks.

**Comment by shakuzen** [comment]
@yyyogev To expand on Raja's answer, even if you build this outside of the Zipkin repo, it should be possible to run it with the standard Zipkin Server as an add-on module like some others we have (for example, see [zipkin-gcp's stackdriver storage component](https://github.com/openzipkin/zipkin-gcp#storage)).

**Comment by yyyogev** [comment]
I see.. If we do that, does that mean we'll need to maintain it with every update of your repo?

**Comment by codefromthecrypt** [comment]
there will be some maintenance. but usually only version bumps and this
would be the same maintenance in our org or elsewhere as extensions are
separate modules unless very reused and not saas only.

while a new page we are starting to inventory community options such as
scouter to help things become more popular.

https://zipkin.io/pages/extensions_choices.html

**Comment by yyyogev** [comment]
Ok then, so how does it work? you would open a zipkin-logzio repo that we could work on?

**Comment by codefromthecrypt** [comment]
we wouldn't open a contrib repo without user demand, but you could start one and then see how it goes. For example, we have a minimum policy of rule-of-three where the 3 are end user sites that use something.. this helps with the fact that almost all here are volunteers and time must be used wisely.

If the api is the same, you might get by with a simple auto-config integration such as exists in elasticsearch for AWS. https://github.com/openzipkin/zipkin-aws/tree/master/autoconfigure/storage-elasticsearch-aws

you could make that repo named zipkin-logzio and if a future makes sense to use github's move repo functionality we can consider that at the time. Meanwhile, you can plug it in the options site as well.

make sense?

**Comment by codefromthecrypt** [comment]
ps there isn't a near future where this will be in the main repo which the issue is opened on. let's stop re-opening the issue and move conversation to https://gitter.im/openzipkin/zipkin as this issue is spamming all watchers

**Comment by yyyogev** [comment]
Ok, sorry for that
