### ISSUE TITLE
Use es to store data, hit  /dependencies  api directly and set lookback to 0, then it returns data.

### ISSUE THREAD

**Issue by huhu-sky** [openzipkin/zipkin#2356]
## while i use /dependencies api directly and set lookback to zero, i hope it return empty list. but it still returns data.  Using es to store data.
![image](https://files.gitter.im/openzipkin/zipkin/yMfw/image.png)

```
IndexNameFormatter.java
public List<String> formatTypeAndRange(@Nullable String type, long beginMillis, long endMillis) {
    GregorianCalendar current = midnightUTC(beginMillis);
    GregorianCalendar end = midnightUTC(endMillis);
    if (current.equals(end)) {
      return Collections.singletonList(formatTypeAndTimestamp(type, current.getTimeInMillis()));
    }
……
```

**Comment by yinjihuan** [comment]
There is no data on my visit.

http://localhost:9411/zipkin/dependency/

Data is available when searching

What is the reason for this?

Version 2.12.0 used

**Comment by codefromthecrypt** [comment]
@yinjihuan you are using https://github.com/openzipkin/zipkin-dependencies/ ?

**Comment by yinjihuan** [comment]
![image](https://user-images.githubusercontent.com/17271895/52114738-c91a7a80-2647-11e9-8a53-4af9088d94d5.png)

**Comment by yinjihuan** [comment]
![image](https://user-images.githubusercontent.com/17271895/52115813-81e1b900-264a-11e9-8210-8b4bd2013650.png)


Data is displayed in the Spring Cloud document example

**Comment by codefromthecrypt** [comment]
can you join https://gitter.im/openzipkin/zipkin for troubleshooting instead of discussing on the issue?

**Comment by huhu-sky** [comment]
@yinjihuan  you can set lookback to 0 and try again.

**Comment by codefromthecrypt** [comment]
I will make this fail same way as /api/v2/traces when zeros are passed.
