### ISSUE TITLE
UI window location creates an invalid url

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2361]
When you execute a search, the window location changes from zipkin/ to zipkin (without slash), which results in a 404 if you execute that.

**Comment by drolando** [comment]
Can we add a redirect from zipkin to zipkin/ (or even better support both in the code)?

It's very annoying that /zipkin returns a 404

**Comment by codefromthecrypt** [comment]
we can also do something like this.. but mainly noting as we are not always
the UI proxy
