### ISSUE TITLE
endTs remains unchanged in Zipkin Lens

### ISSUE THREAD

**Issue by making** [openzipkin/zipkin#2364]
## Describe the Bug

`endTs` seems to remain unchanged until refreshing the page entirely (F5).
so new traces wouldn't come when clicking the lens icon

![image](https://user-images.githubusercontent.com/106908/51674242-79b6c780-2013-11e9-8362-4decd04752ee.png)

If this behavior is intentional, it would be nice to provide a refresh button.

## Steps to Reproduce

Enable Zipkin Lens => Click 🔍 => Change search criteria or Go to dependencies page and back to search page => click  🔍 again

## Expected Behaviour

I'd like to update traces without reloading the page

**Comment by jcchavezs** [comment]
+1

**Comment by making** [comment]
A current workaround to update `endTs` is:

 Click 🔍 => Click "Search" => Reload the browser => click 🔍 again

Pretty inconvenient 😕

**Comment by codefromthecrypt** [comment]
@zeagord or @tacigar can anyone dig into this? It is causing many user complaints
