### ISSUE TITLE
[zipkin-lens] Show both client and server timings in rpc spans

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2365]
This is something we talked about a while ago, but decided that it was too hard to do until we moved to SVG rendering. Filing here for reference so we don't forget.

Right now the blue bar for RPC spans shows client timings. It starts at the client ts and ends after the client duration. To check how much the network delay was and how long the server actually took you have to click on it and manually check the timestamps.

It'd be nice if that bar was actually composed of 2 different bars: a darker blue one that still represents client timings like now and an overlapping lighter bar that shows server timings. That way you can see the network delay just by looking at the trace view.

I don't know how hard it is to implement in CSS though... @tacigar @zeagord

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2386 fixes this.. note this was one popular part of the last UI attempt https://github.com/openzipkin-attic/zipkin-ui
