### ISSUE TITLE
Why I start zipkin webUI, it throws a Unknown method exception

### ISSUE THREAD

**Issue by netease-datastream** [openzipkin/zipkin#237]
When I start web UI and query the trace log,  it throws a Unknown method exception
Unsafe is a class in rt.jar. But I try all JDK such as JDk 7u17,openJDK7,JDK6u22,openJDK6 , I still cannot resolve this problem.
I wonder this sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V In which JDK version .  

FAT [20130402-13:28:03.663] ZipkinWeb: org.apache.thrift.TApplicationException: Internal error processing getTraceSummariesByIds: 'java.lang.NoSuchMethodError: sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V'
FAT [20130402-13:28:03.663] ZipkinWeb:     at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.zipkin.gen.ZipkinQuery$FinagledClient.decodeResponse(ZipkinQuery.scala:5263)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getTraceSummariesByIds$1.apply(ZipkinQuery.scala:5480)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getTraceSummariesByIds$1.apply(ZipkinQuery.scala:5479)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:477)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:476)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.util.Promise$$anonfun$transform$1.apply(Future.scala:883)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.util.Promise$$anonfun$transform$1.apply(Future.scala:879)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.util.Promise$$anonfun$respondWithoutChaining$1.apply(Future.scala:868)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.util.Promise$$anonfun$respondWithoutChaining$1.apply(Future.scala:863)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.concurrent.IVar$$anonfun$runqs$1.apply$mcV$sp(IVar.scala:174)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.concurrent.IVar$LocalScheduler.run(IVar.scala:125)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.concurrent.IVar$LocalScheduler.apply(IVar.scala:105)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.concurrent.IVar.runqs(IVar.scala:169)
FAT [20130402-13:28:03.663] ZipkinWeb:     at com.twitter.concurrent.IVar.set(IVar.scala:311)

**Comment by bmdhacks** [comment]
I've never seen that before.  What OS is this on?

**Comment by netease-datastream** [comment]
I run on Linux
version is 

Distributor ID:Debian
Description:Debian GNU/Linux 7.0 (wheezy)
Release:7.0
Codename:wheezy

At 2013-04-03 01:19:54,"Brian Degenhardt" notifications@github.com wrote:
I've never seen that before. What OS is this on?

On Mon, Apr 1, 2013 at 10:36 PM, Flume-patch-netease <
notifications@github.com> wrote:

> When I start web UI and query the trace log, it throws a Unknown method
> exception
> Unsafe is a class in rt.jar. But I try all JDK such as JDk
> 7u17,openJDK7,JDK6u22,openJDK6 , I still cannot resolve this problem.
> I wonder this
> sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V In
> which JDK version .
> 
> FAT [20130402-13:28:03.663] ZipkinWeb:
> org.apache.thrift.TApplicationException: Internal error processing
> getTraceSummariesByIds: 'java.lang.NoSuchMethodError:
> sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V'
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.zipkin.gen.ZipkinQuery$FinagledClient.decodeResponse(ZipkinQuery.scala:5263)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getTraceSummariesByIds$1.apply(ZipkinQuery.scala:5480)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getTraceSummariesByIds$1.apply(ZipkinQuery.scala:5479)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:477)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:476)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.util.Promise$$anonfun$transform$1.apply(Future.scala:883)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.util.Promise$$anonfun$transform$1.apply(Future.scala:879)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.util.Promise$$anonfun$respondWithoutChaining$1.apply(Future.scala:868)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.util.Promise$$anonfun$respondWithoutChaining$1.apply(Future.scala:863)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.concurrent.IVar$$anonfun$runqs$1.apply$mcV$sp(IVar.scala:174)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.concurrent.IVar$LocalScheduler.run(IVar.scala:125)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.concurrent.IVar$LocalScheduler.apply(IVar.scala:105)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.concurrent.IVar.runqs(IVar.scala:169)
> FAT [20130402-13:28:03.663] ZipkinWeb: at
> com.twitter.concurrent.IVar.set(IVar.scala:311)
> 
> ¡ª
> Reply to this email directly or view it on GitHubhttps://github.com/twitter/zipkin/issues/237
> .

¡ª

**Comment by bmdhacks** [comment]
I'm guessing there's a mismatch between the scala+jvm you're compiling with
versus the scala+jvm you're running with.

**Comment by netease-datastream** [comment]
I`m compiling and running on the same version 

mysql scala version is 
Scala code runner version 2.10.0 -- Copyright 2002-2012, LAMP/EPFL

I only run the command bin/web . Does it do compiling in this script or I should run sbt compile alone.

At 2013-04-03 10:48:53,"Brian Degenhardt" notifications@github.com wrote:
I'm guessing there's a mismatch between the scala+jvm you're compiling with
versus the scala+jvm you're running with.

**Comment by trustin** [comment]
@netease-datastream Are you using OpenJDK shipped by your distribution?  In that case, using the latest OpenJDK or the Oracle JVM should fix the problem.  A certain revision of OpenJDK was shipped with mistakenly removed unsafe operations.

**Comment by netease-datastream** [comment]
Thanks you very much 
it works now.
Maybe it is my faults of set JDK version wrongly

At 2013-04-03 11:21:02,"Trustin Lee" notifications@github.com wrote:

@netease-datastream Are you using OpenJDK shipped by your distribution? In that case, using the latest OpenJDK or the Oracle JVM should fix the problem. A certain revision of OpenJDK was shipped with mistakenly removed unsafe operations.

¡ª

**Comment by netease-datastream** [comment]
I wonder if I can add a message annotation in the RPC method by finagle-zipkin?
I cannot get the tracer referrence in the RPC method because it is hidden by the  Server of finagle.
I found the source code that  tracer only exists in ThriftServerFramedCodec. 

At 2013-04-03 11:21:02,"Trustin Lee" notifications@github.com wrote:

@netease-datastream Are you using OpenJDK shipped by your distribution? In that case, using the latest OpenJDK or the Oracle JVM should fix the problem. A certain revision of OpenJDK was shipped with mistakenly removed unsafe operations.

¡ª
