### ISSUE TITLE
Span display order is incorrect sometimes

### ISSUE THREAD

**Issue by ldcsaa** [openzipkin/zipkin#2370]
zipkin version: 2.12.0

Span display order is incorrect sometimes like these:
![image](https://user-images.githubusercontent.com/5990337/51963093-54a3d800-249d-11e9-889a-b9f2add3208d.png)

![image](https://user-images.githubusercontent.com/5990337/51963176-ad737080-249d-11e9-917b-1152a630e818.png)

**Comment by codefromthecrypt** [comment]
if the order is consistently not right, can you provide the JSON? this will
help us understand what is going on. Please make sure no private data is
inside.

**Comment by ldcsaa** [comment]
This is Examples, please check:
[examples.zip](https://github.com/openzipkin/zipkin/files/2815429/examples.zip)

**Comment by drolando** [comment]
We're having the same issue. I'll try to debug it tomorrow and send a fix

**Comment by codefromthecrypt** [comment]
@ldcsaa thank you for posting the example data. My first goal is to understand what is happening, so if I mention something is a problem in the data, please don't take it personally :P I will take a look now and see

**Comment by codefromthecrypt** [comment]
I agree with your assessment of trace 1. looking into the second

**Comment by codefromthecrypt** [comment]
also I agree with the 2nd. My hypothesis is that children are not sorted by timestamp as we traverse the trace

**Comment by codefromthecrypt** [comment]
so interestingly `traceToMustache` returns `modelview.spans` in the correct order. looking closer at what could cause this..

**Comment by codefromthecrypt** [comment]
`trace.js/showSpans` is invoked with the later span first.. guessing it is somewhere before this, then

**Comment by codefromthecrypt** [comment]
`page/traceViewer.js` gets the spans in the wrong order... looking between now

**Comment by codefromthecrypt** [comment]
component_ui/trace.js has the spans in opposite order (forgive me for posting notes, it is really hard to figure out what the heck is going on)

<img width="683" alt="screen shot 2019-02-07 at 10 20 10 am" src="https://user-images.githubusercontent.com/64215/52386700-6bdb5a80-2a87-11e9-9e96-1ec52e2350ad.png">

**Comment by codefromthecrypt** [comment]
ok taking a break maybe I can figure this out later

**Comment by codefromthecrypt** [comment]
ok yesterday I must not have noticed that traceViewer.js gets the span in the wrong order which is the same as presentation
<img width="751" alt="screen shot 2019-02-08 at 12 02 51 pm" src="https://user-images.githubusercontent.com/64215/52458290-90275c00-2b99-11e9-982a-76384b4b2b22.png">

**Comment by codefromthecrypt** [comment]
sorry about the delay https://github.com/openzipkin/zipkin/pull/2385

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2395 should fix this for real
