### ISSUE TITLE
The sample rate maybe wrong

### ISSUE THREAD

**Issue by foobarget** [openzipkin/zipkin#238]
The sample rate is 2, 4, 8, 16 ... 1024 in google Dapper, but  in the finagle source, I find the sample value is a float value and can be set by any rate. I thought that may lose some feature in zipkin.

**Comment by bmdhacks** [comment]
The reason dapper has divisible sample rates is because endpoints participating in the same trace can have independent sample rates, so dapper needs them to line up occasionally.  Zipkin preserves the sample rate down the line, thus allowing us to have a much more varied rate.
