### ISSUE TITLE
If client and server side has a same tag name, should it be display server side tag value ?

### ISSUE THREAD

**Issue by ldcsaa** [openzipkin/zipkin#2390]
Client side (hapi-demo) and server side (soa-demo-server) has same tag names '__serviceId & __serviceName', but tag values is not same. tag value is '0010100001/hapi-demo' and '0010100003/soa-demo-service', and now display client tag values, shoulde it display server side tag value ?

Trace JSON: 

[trace.zip](https://github.com/openzipkin/zipkin/files/2858841/trace.zip)

![image](https://user-images.githubusercontent.com/5990337/52687721-225ea400-2f8e-11e9-81c4-aa9a09ffea33.png)

**Comment by codefromthecrypt** [comment]
agree if they are different both values should show

**Comment by ldcsaa** [comment]
Do you have any plans to amend?

**Comment by codefromthecrypt** [comment]
sorry there are a lot of distractions this week. I want to fix this, if
that is your question, but if you have time to try you should first.

**Comment by ldcsaa** [comment]
OK, I will wait.
And another question: When will version 2.12.2 be released ?

**Comment by codefromthecrypt** [comment]
> And another question: When will version 2.12.2 be released ?

How about this.. ask on monday if it is not :)

**Comment by ldcsaa** [comment]
Thanks a lot ...

**Comment by codefromthecrypt** [comment]
this is next on my list

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2397
