### ISSUE TITLE
zipkin ui not show correctly in some condition

### ISSUE THREAD

**Issue by gougouzcm** [openzipkin/zipkin#2401]
![default](https://user-images.githubusercontent.com/16322041/52937105-2da03e00-3399-11e9-8703-36ac75b60d9b.png)

Pay attention to the red area.
It seems zipkin-ui show a long value not correctly when the long value is more then 16-bit

The correct value is 1292520862062216190L . The wrong show value is 1292520862062216200

The zipkin-server version is 2.6.1。
Any solutions about it or use a higher version of zipkin-server .
Thanks.

**Comment by codefromthecrypt** [comment]
the javascript libraries have been updated recently. Please try most recent and see if still an issue? we don't have custom json processing code

**Comment by gougouzcm** [comment]
> 
> 
> the javascript libraries have been updated recently. Please try most recent and see if still an issue? we don't have custom json processing code

I use the newest zipkin-servre , It still not work.

![default](https://user-images.githubusercontent.com/16322041/53461437-82b81000-3a7b-11e9-93c3-ea4dc42c4772.png)

**Comment by codefromthecrypt** [comment]
this only happens in "zipkin classic" which will be deleted soon. I checked and lens does not have this problem. Closing this as won't fix because we have to conserve energy. Thanks for reporting!

**Comment by shakuzen** [comment]
I would also note that if you are using the latest version of the Zipkin Server, you can switch to the new Zipkin Lens UI with the "Try Lens UI" button near the top right of the UI. This would avoid the issue reported, as Adrian mentioned.
