### ISSUE TITLE
Allow switching between Zipkin Lens and prior UI during transition phase

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/zipkin#2402]
**Feature:**
Allow Zipkin end-users to switch between Zipkin Lens and the historic UI.

**Rational**
We are transitioning between the two UIs and it would be a nicer user experience if individual users can switch between the two. Currently, only operators can decide which UI is used for all users of that deployment at startup. If users can switch, this gives them the choice of which UI to use when, and notably allows early adopters/testers of Zipkin Lens, while providing a fallback between when any issue is found and when a release is made with it fixed in Zipkin Lens.

**Example Scenario**
Power users want to try the latest and greatest UI for Zipkin without forcing all users to try it at once or all the time.

**Prior Art**
@adriancole may have found a way to hack this together ⛏️

**Comment by dnozay** [comment]
hmmmm, how do I go back to the prior UI after trying lens?

**Comment by dnozay** [comment]
looks like removing cookie works.

**Comment by codefromthecrypt** [comment]
re-opening as we lost the button to revert back to classic at some point. however, since https://github.com/openzipkin/zipkin/pull/2736 changes a lot of things we can wait until that's merged to add it again.

**Comment by jy1989** [comment]
still lost the button to revert back to classical ui with the latest version build from docker

**Comment by anuraaga** [comment]
@jy1989 Thanks for noticing. To reduce maintenance cost and focus on improvement going forward, we've gone ahead and removed the classic UI from zipkin. We will have more detailed notes when doing the official release. You can see discussion here

https://github.com/openzipkin/zipkin/pull/2971

We understand there are still some remaining issues but as a group of volunteers need to do this to best manage our resources. If any of the issues mentioned on that PR are important to you, would you be able to help with them? Or at least vote on what's most important to you if lens is still lacking functionality you need?

**Comment by jorgheymans** [comment]
The transition phase is over, Lens is now the default UI. The previous 'classic' UI is no longer packaged with the server, no more button to revert back to the old UI.
