### ISSUE TITLE
the trace page loads too slowly

### ISSUE THREAD

**Issue by houseyoung** [openzipkin/zipkin#2411]
We use ES store spans, and use zipkin version 2.4.6-SNAPSHOT.

When the span number exceeds a certain level (close to 10000), the trace page loads slowly. It takes about 5 seconds to call api to return json, but takes about 40 seconds to fully load the page.

We made our own modifications based on the source code of 2.4.6-SNAPSHOT, so upgrading the version is very troublesome. So, does the recent new version improve the performance of UI?

We have proposed some solutions to this problem:
1. Instead of loading all the spans at once, load them in layers according to the tree structure.
2. Limit the number of each load, more than 500, need to click the "more" button to query more.

I would like to ask if there is a similar plan in the zipkin official recently. It is very difficult for us to make changes on our own, so if the recent version will solve this problem, we will wait for the release of the new version.

**Comment by houseyoung** [comment]
My English is pretty limited, please don't mind :(

**Comment by codefromthecrypt** [comment]
can you update to snapshot and try the lens UI? you should see a button for it now. https://github.com/openzipkin/zipkin/pull/2404

**Comment by codefromthecrypt** [comment]
basically it sounds like the main problem is the rendering as 35 of 40seconds spent there.

**Comment by houseyoung** [comment]
> basically it sounds like the main problem is the rendering as 35 of 40seconds spent there.

I also think so. 
The size of the returned json is about 12MB, I don't know if this will greatly affect the rendering speed.

**Comment by codefromthecrypt** [comment]
for github issues, best one issue per topic. You have very large traces.. we can chat about if this is a great idea or not, or alternatives to huge traces here https://gitter.im/openzipkin/zipkin

**Comment by codefromthecrypt** [comment]
very related issue here, but yeah please validate on lens as the current UI will not be maintained after Lens is made default https://github.com/openzipkin/zipkin/issues/1460

**Comment by houseyoung** [comment]
Does the new version improve the page rendering speed?

> very related issue here, but yeah please validate on lens as the current UI will not be maintained after Lens is made default #1460

I'll try it, thanks.

**Comment by codefromthecrypt** [comment]
> Does the new version improve the page rendering speed?
>
you can decide if it improves speed or not. It will help for you to try it,
to see the scale of the problem, also because we aren't going to do any
performance work on the old UI

**Comment by codefromthecrypt** [comment]
related https://github.com/apache/incubator-zipkin/issues/2496

**Comment by jorgheymans** [comment]
@houseyoung would you mind testing those huge traces against the latest version of Zipkin ? The new UI has seen many performance improvements and i doubt that it would take 40s to render a huge trace. Also if you're in a position to anonymize the trace and upload it into a gist that would be great, so we can use it as a test case.

**Comment by jorgheymans** [comment]
Closing as no feedback anymore. Please test against latest Zipkin UI and open a new issue if you find the performance to be lacking still.
