### ISSUE TITLE
Hello, does zipkin support custom traceID? 

### ISSUE THREAD

**Issue by deanjo** [openzipkin/zipkin#2412]
Hello, 
does zipkin support custom traceID?
For example, the caller calls service A, and service B calls service C.
I want to customize the traceID in service A, and then return the taceID to the caller, so that when there is a problem with the service call, I can directly query through the resultID.

**Comment by codefromthecrypt** [comment]
what you are asking is best asked on gitter. issues are for changes to
the server, which is irrelevant to the question you asked
https://gitter.im/openzipkin/zipkin
