### ISSUE TITLE
Lens UI no space for the used-by pie

### ISSUE THREAD

**Issue by jcarres-mdsol** [openzipkin/zipkin#2425]
## Describe the Bug
Using the Lens UI, dependency view, when clicking on a service, I can see on the right I can see information about used-by and using services.

When I have a lot (40) services using one of my services, the tags take a lot of space and there is no space for the pie chart which gets crunched and almost invisible.

## Steps to Reproduce
Have a crazy architecture, lots of services connected to one particular service, go to dependencies, click on the service which is used by everyone.

## Expected Behaviour
I would expect the pie charts to have the same size and not depend on the size taken by the tags.

**Comment by tacigar** [comment]
Thank you for your feedback!! I'll take a look.
