### ISSUE TITLE
can I change embeded web contaner form undertow to tomcat for Collector module

### ISSUE THREAD

**Issue by botaruibo** [openzipkin/zipkin#2427]
1. my team want to embed the Collector server into our application server then add some controller before the span receiver (maybe the zipkin2.server.internal.ZipkinHttpCollector.handlerequest(). we don't familiar with undertow). is there any solution?
2. can we change the default web container from undertow to tomcat  (just to the  Conllector server)

**Comment by shakuzen** [comment]
We don't support custom Zipkin Servers - it is meant to be run as the executable JAR we publish or the Docker container we publish. That said, there are several ways to add-on features depending on what you are trying to accomplish. It will be easier to discuss this on Gitter, so feel free to join us there: https://gitter.im/openzipkin/zipkin
If you want to process the span data somehow before saving, there are folks doing this already and we would be happy to guide you to a solution.
