### ISSUE TITLE
elasticsearchERROR Illegal char <:> at index 6: zipkin:span-2019-03-06 windows7 elasticsearch-2.3.1

### ISSUE THREAD

**Issue by brightvip** [openzipkin/zipkin#2428]
windows7 
elasticsearch-2.3.1 
elasticsearchERROR Illegal char <:> at index 6: zipkin:span-2019-03-06
126  [https://github.com/openzipkin/zipkin/blob/release-2.12.3/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/IndexNameFormatter.java](url) 
350-355 [https://github.com/openzipkin/zipkin/blob/release-2.12.3/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/ElasticsearchStorage.java](url)

**Comment by codefromthecrypt** [comment]
can you give the full stack trace or error message? colon isn't disallowed
until elasticsearch 7

**Comment by brightvip** [comment]
@adriancole 
[elasticsearch.log](https://github.com/openzipkin/zipkin/files/2934383/elasticsearch.log)

Hello
  
Zipkin + elasticsearch-2.3.1 +WIN7 error
Zipkin + elasticsearch-2.3.1 + centos6.5 success
I don't think it is an elasticsearch error because win7 can't use a colon as a folder name.

**Comment by shakuzen** [comment]
Is your Elasticsearch server run on Windows and does it need to be? If it is just to test locally, maybe you can use Docker to run Elasticsearch?

**Comment by brightvip** [comment]
I hope this colon can be specified with a different symbol such as ES_DATE_SEPARATOR so I can specify @

**Comment by codefromthecrypt** [comment]
@brightvip this sounds like a bug in ES. let's please verify that first

@openzipkin/elasticsearch does anyone know if ES intentionally has a constraint about colons in index names in windows, or if this was a bug fixed.

I want to separate this from the other issue about ES 7 as we've gone multiple years with no problems reported on colons and need to conserve time as making a change here also implies one in other places.

**Comment by xeraa** [comment]
2.x is really old and I don't have a Windows machine at hand, so I cannot try it out, but I have a hunch: We used the index name as the folder name in Elasticsearch's data directory. I think with 5.0 this was changed to use a UUID to avoid any issues with file systems and special naming patterns in them (like calling an index `..`, etc). Is `:` generally not allowed on Windows and you are trying to create a folder with such a name?

From Elasticsearch's point of view the colon will only be disallowed in 7.0 and you can see the current rules for disallowed characters in https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java#L162-L188.

**Comment by codefromthecrypt** [comment]
thanks for the advice @xeraa
