### ISSUE TITLE
/metrics doesn't increment for kafka

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2430]
possibly because of the two kafka configs, the kafka section of the /metrics endpoint doesn't increment while it does on /actuator/prometheus

**Comment by codefromthecrypt** [comment]
actually many of the metrics endpoint seem more than a little off, for example, showing 100% dropped spans when clearly they are not 100%. Can someone run through this and see if they can detect an issue? (I'm looking at 2.12.3 variant)

One way is to run the example project and `wrk -t4 -c128 -d30s http://localhost:8081  --latency`

**Comment by codefromthecrypt** [comment]
@zeagord wanna try this one?

**Comment by zeagord** [comment]
Sure. I am on it.
