### ISSUE TITLE
Add ByteBuffer versions to BytesDecoder

### ISSUE THREAD

**Issue by anuraaga** [openzipkin/zipkin#2435]
**Feature:**
Description of the feature

Currently, `BytesDecoder` only supports operating on `byte[]`. It could define similar methods that work on `ByteBuffer`.

**Rational**
Why this feature should be in zipkin

As zipkin is migrating to using Netty via Armeria and looking into adding gRPC ingestion, optimizations become possible that use Netty's `ByteBuf`, which is a manually allocated buffer. Using `ByteBuf` more would reduce garbage and probably increase throughput of zipkin-server, and this can be done by making methods that accept `ByteBuffer`.

**Example Scenario**
When will this be used by operators?

zipkin-server would use it when ingesting spans.

Implementation would look like

- JSON - currently uses `ByteArrayInputStream`. While there is no `ByteBufferInputStream` in the JDK for some reason, it would be trivial to add one like this and the rest of the business logic would be unchanged

  https://stackoverflow.com/questions/4332264/wrapping-a-bytebuffer-with-an-inputstream/6603018#6603018

  Though it would also be worth considering moving from gson to Jackson - in my experience I've gotten better performance from the latter, and it would natively support working on `ByteBuffer`. Just for reference, here is some code that uses Jackson's incremental parser https://github.com/curioswitch/curiostack/blob/master/common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/ParseSupport.java#L65

- Thrift - currently uses `ByteBuffer.wrap`. As it already operates on `ByteBuffer`, there is basically no work involved

- Proto - Uses lots of manual operations on `byte[]`. Would need the most logic rewriting. My recommendation would be going ahead and converting to `ByteBuffer` and using `ByteBuffer.wrap` for the `byte[]` path

@adriancole does this seem like a reasonable idea?

**Comment by codefromthecrypt** [comment]
I would be ok with this except please don't redo internals without benchmarking. It is my experience that not only are most payload types byte arrays (ex kafka) but also buffers are a lot slower in benchmarks.

In other words I don't think this is important enough to hurt perf... a lot of energy was spent on getting perf to the place it is.. if you can manage to keep or beat those numbers with internal rewriting, though, knock yourself out :)

last thing is to watch for api level.. zipkin core is java 6.

**Comment by anuraaga** [comment]
It is a good point that since the focus would be perf of zipkin-server it's probably best to add custom decoders there than core. Anyways will try to create basic benchmarks first to compare and see if there is even any point in thinking about the details.

**Comment by codefromthecrypt** [comment]
thanks again for digging in! here's some baseline stuff
https://github.com/openzipkin/zipkin/tree/master/benchmarks/src/main/java/zipkin2/codec

**Comment by codefromthecrypt** [comment]
PS on the java 8 thing, as long as the signature isn't required, it might be ok. At any rate decoding is usually only on the read side and zipkin-collector is a java 8 library. Moreover, there's no need to use java 8 things to use bytebuffer.

The more important part would be that we may be implying a change to an interface (BytesDecoder) which would be a breaking change. If we instead do it on literally `SpanBytesDecoder`, we are ok. Not sure if this works for you.

**Comment by codefromthecrypt** [comment]
I guess the other thing we can consider is .. even if it is technically a breaking change to add a method to `BytesDecoder`, how much surface area of break are we talking.. It would be an issue for 3rd party and also anything that wraps.

We could make a helper type SpanByteBufferDecoder for avoiding this issue.. it also depends on the call sites you are interested in.. if they use all of the features of BytesDecoder or only are decoding lists..

**Comment by codefromthecrypt** [comment]
another thing we can do, if the motive of this is to understand performance, is a lesser change. Add to SpanBytesDecoder an offset option ( I think @narayaruna asked for this)

If decoding with an offset, you can use a thread-local byte array that's sized large enough to be bigger than most, but not too large to become a problem. This isn't to eliminate the byte buffer option, but it would be a lot less work. Then, if the goal is to see how much contribution there is to latency.. you could use this rendesvous array to figure that out. If it was a lot, then you can justify more work like switching to byte buffer.

I mean you can do more work like add byte buffer anyway, just mentioning options that are cheaper in terms of code.
