### ISSUE TITLE
client only trace will not shown of there is server side traces in zipkin ui

### ISSUE THREAD

**Issue by thegryfon** [openzipkin/zipkin#2439]
So I have the following:
1. zipkin-js SPA application (let's call this service-a) written in vue which will intercept api calls to backend, and instrument it with an axios plugin. Basically it will intercept any api request and add zipkin instrumentation:

```
    var instrumentation = new _zipkin.Instrumentation.HttpClient(options);
    const zipkinConfig = instrumentation.recordRequest(config, config.url, config.method);
```
this is the payload sent from service-a to zipkin api
```
duration: 3332000
id: "292135f69ada510c"
kind: "CLIENT"
localEndpoint: {serviceName: "service-a"}
name: "get"
tags: {http.path: "/customers/1",…}
timestamp: 1552275283625000
traceId: "292135f69ada510c"
```

2. spring boot application with spring cloud sleuth zipkin with an api endpoint (lets call this service aaa).

both of them are pointed to zipkin instance.

The problem is:
1. if BOTH the client and server send span data to zipkin, what I got in zipkin ui will be only bars of backend span only (service aaa). I expected there will be parent span shown from zipkin-js, and a child span shown from backend. But that's not what happening here

2. but if I intentionally does not send spring boot backend spans to zipkin (for example by using false zipkin host in my spring boot config), the span bars in zipkin ui will shown.

This is the json shown in zipkin ui 'show json' button for no.1 (note that the traceId of different request, of course will be different, but let's just assume it's the same to show my point, otherwise it's the same format)
```
 {
    "traceId": "292135f69ada510c",
    "id": "292135f69ada510c",
    "kind": "CLIENT",
    "name": "get",
    "timestamp": 1552275283625000,
    "duration": 3332000,
    "localEndpoint": {
      "serviceName": "service-a"
    },
    "tags": {
      "http.path": "/customers/1",
      "http.status_code": "200",
      "result": "{\"transformRequest <<cut for visibility purpose >>
    }
  }
]
```

and this is for no .2
```

  {
    "traceId": "292135f69ada510c",
    "id": "292135f69ada510c",
    "kind": "SERVER",
    "name": "get /customers/{id}",
    "timestamp": 1552275283634060,
    "duration": 10276,
    "localEndpoint": {
      "serviceName": "aaa",
      "ipv4": "172.17.0.1"
    },
    "remoteEndpoint": {
      "ipv6": "::1",
      "port": 39274
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/customers/1",
      "mvc.controller.class": "ApplicationCtrlr",
      "mvc.controller.method": "testAuth"
    },
    "shared": true
  },
  {
    "traceId": "292135f69ada510c",
    "id": "292135f69ada510c",
    "kind": "CLIENT",
    "name": "get",
    "timestamp": 1552275283625000,
    "duration": 3332000,
    "localEndpoint": {
      "serviceName": "service-a"
    },
    "tags": {
      "http.path": "/customers/1",
      "http.status_code": "200",
      "result": "{\"transformRequest <<cut for visibility purpose >>
    }
  }
]
```

This makes me assume that if only client span are being sent, then zipkin will display, but if there is also server side span, zipkin-ui will only display server side span. Is this the intended behaviour ? How can i also show client side span in zipkin ui when there is server side span ?

Note that I also try the same in jaeger, and it shows the result that i expected (i.e parent span for service-a and child span for service aaa)

Thanks

**Comment by codefromthecrypt** [comment]
it is probably better to use gitter for questions like this

**Comment by thegryfon** [comment]
Oh okay @adriancole , i'll try gitter .. i'm not aware of that

 thanks for the suggestions

**Comment by shakuzen** [comment]
Anyone finding this later and curious, here is the start of the linked Gitter conversation: https://gitter.im/openzipkin/zipkin?at=5c85f33f3162ec7bc751cd16
