### ISSUE TITLE
UI show nothing

### ISSUE THREAD

**Issue by aqqbjlgu** [openzipkin/zipkin#2444]
Hi
    When I used zipkin-server-2.12.6-SNAPSHOT to access "xxx.xxx.xxx.xxx:9411/zipkin/," there was nothing on the page, and the browser's console had no errors, the status code was 200.
![1552640506(1)](https://user-images.githubusercontent.com/16629886/54420207-591e0a80-4744-11e9-97ae-58121b506536.png)
![1552640617(1)](https://user-images.githubusercontent.com/16629886/54420209-59b6a100-4744-11e9-807d-9653956b52b1.png)
![1552640548(1)](https://user-images.githubusercontent.com/16629886/54420211-5b806480-4744-11e9-8d42-418b3297da06.png)
![1552640445(1)](https://user-images.githubusercontent.com/16629886/54420217-5cb19180-4744-11e9-92b8-d38fe1ab78f8.png)

**Comment by codefromthecrypt** [comment]
seems duplicate of #2443

will investigate tonight thank you for reporting
