### ISSUE TITLE
HTTPS support in REST API and UI

### ISSUE THREAD

**Issue by gquintana** [openzipkin/zipkin#2449]
**Feature:**
Allow to expose HTTP endpoint over TLS

**Rational**
HTTPS is more and more common, and is a classic security requirement.

**Prior Art**
 * Armeria Spring Boot integration doesn't support HTTPS as of 0.80.0 https://github.com/line/armeria/issues/1659

**Comment by codefromthecrypt** [comment]
I think we have example of how to do this now
