### ISSUE TITLE
Use CSS framework in lens

### ISSUE THREAD

**Issue by tacigar** [openzipkin/zipkin#2451]
Currently, most of the components are so special that CSS framework can not be used as it is. 
So I thought we did not need to use CSS framework.

However, it is expected that more general purpose components will added in the future.
So I'm going to begin to use CSS framework partially to develop such general components efficiently.

@zeagord Thank you for your great idea!!

**Comment by zeagord** [comment]
I think it is nice to use the css frameworks such as semantic-ui or material-ui. It will quicken the development and visually pleasing as well. Let me know if you need any help from my end.

**Comment by tacigar** [comment]
We use material-ui now.

**Comment by shakuzen** [comment]
Just for tracking purposes, I believe it was #2633 that introduced Material UI
