### ISSUE TITLE
Is it possible to update duration

### ISSUE THREAD

**Issue by AceHack** [openzipkin/zipkin#2452]
If I have already sent a {cs,cr} or {sr,cs} with a duration is it possible to "overwrite" what's currently there?  This seems to work fine if the first duration I sent was 0 then I can still update it in the future but if the first duration I sent was anything else I can't seem to overwrite it with a new duration.  Any help is appreciated.  Thanks.

**Comment by jcchavezs** [comment]
What language are you instrumenting?

Den tir. 19. mar. 2019, 07:17 skrev Aaron Stainback <
notifications@github.com>:

**Comment by codefromthecrypt** [comment]
It is better to send in v2 format, and duration explicitly vs derived. duration can be written again, but be careful to use correct instrumentation. For example, a shared field needs to be set if there is a server span re-using the same ID as the client. Otherwise duration precedence on merge will get messed up.

**Comment by AceHack** [comment]
I'm sending v2 protobuf format directly https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto.  Let's completely ignore the server span for right now and only talk about the client span.  I'm sending the exact same client span twice, except the first time I'm sending `uint64 duration` of 1 and the 2nd time I'm sending `uint64 duration` of 1234.  The UI never sees 1234, it only sees 1.

If I change the setup and on the first time I send `uint64 duration` 0 then the 2nd time I send `uint64 duration` of 1234 then in the UI I see 1234.

Are you saying the 2nd time I should set the shared flag?  I'll try that and let you know the results.

**Comment by codefromthecrypt** [comment]
it is best to not report duration unless you know what it is. why is it that you are sending a tentative duration?

**Comment by codefromthecrypt** [comment]
so not send duration meaning leave absent (zero is often coersed to absent as we define minimal duration of 1 due to nuance on this point)

**Comment by AceHack** [comment]
Because the process I'm instrumenting does not really know if it's complete.  It can keep getting woken up over and over and it never really knows if it's done, I would just like to report the best currently known information.

**Comment by codefromthecrypt** [comment]
so the problem is that certain tools will not expect varying duration as the general span contract is you start it, you finish it (once). Things like duration query won't work right when the value changes. Most stores are document oriented as opposed to SQL upsert. Readback might be ok. At any rate, problems like this are why we added the "shared" flag to the server span, so that it could be ignored when computing the client duration.

**Comment by codefromthecrypt** [comment]
my guess is that what you are experiencing is tension on span model as what you are modeling doesn't seem to have a defined start and finish. It might be helpful to be more concrete about what's going on as perhaps there are ways to model it differently.. not sure. there are some things that don't work well with span model, like chat sessions.

**Comment by AceHack** [comment]
Got ya, so you are saying it's not designed to work this way.  Can I always assume I can "update" an existing span that has no duration?  Like my 2nd scenario above, initially sending "empty" and then later sending a value for the same span id.  This is nice because at least I can see in the UI the "empty" span before the final span with duration will be received. Again I'm not just talking about client/server scenario.  I'm talking about all span types.

**Comment by codefromthecrypt** [comment]
yes you can send any fields late except trace id/span id. We did this for the use case of in-flight data that isn't complete actually :) before we had to play games with fields initialized to empty string.

**Comment by codefromthecrypt** [comment]
I should clarify it is more efficient to send as much of it at the same time (ideally complete). anyway hope this answers the question.

**Comment by AceHack** [comment]
With any backend will they show up in the UI "early" before they have a duration as they do with the in-memory backend?

**Comment by codefromthecrypt** [comment]
@AceHack no backend requires duration, though display won't look great lacking one.

timestamp is important though.. please send that if you can. It is also in some aggregation cases helpful. meaning if you have to send duration late, it can help some tooling to send timestamp in the same doc.

**Comment by codefromthecrypt** [comment]
PS I will add a unit test referencing this issue to ensure late duration is ok

**Comment by AceHack** [comment]
Do you have a list of common or standard tags and annotations?

**Comment by codefromthecrypt** [comment]
@AceHack usually I would have punted to gitter by now but I thought we were at the end of the duration dillemma :) can we chase up other questions on gitter as this is starting to spam the repo https://gitter.im/openzipkin/zipkin

**Comment by AceHack** [comment]
Okay thanks.
