### ISSUE TITLE
 No more detailed operation mode?

### ISSUE THREAD

**Issue by jzdayz** [openzipkin/zipkin#2455]
Hello , The zipkin not support on maven?  
Can I only use docker and java jar?

**Comment by shakuzen** [comment]
We do not offer support for custom-built servers anymore (using `@EnableZipkinServer`), but it is still possible for you to make them, technically. Join us on Gitter (https://gitter.im/openzipkin/zipkin) and share what is your use case for wanting to make a custom build. Perhaps there are ways to achieve your goals without making a custom server.
