### ISSUE TITLE
I want to know whether it is good to relay tracing on MQ consumers.

### ISSUE THREAD

**Issue by tbwork** [openzipkin/zipkin#2458]
As is known, Zipkin is a call-chain tracing system. However, our engineers propose to trace MQ consumers. And this encourage me to re-think the rationality. One call-chain should be the chain from service to the end of MQ, rather than the consumers.
The MQ consumer should restart its own new trace chain.
Image that if we trace all MQ consumers which may be massive, it will stain the call-chain and make it unfriendly for reading.

What do you think? @adriancole

**Comment by codefromthecrypt** [comment]
this is a good question. can you please ask on gitter or stackoverflow? we use issues for changes to the project code. https://gitter.im/openzipkin/zipkin

**Comment by tbwork** [comment]
https://stackoverflow.com/questions/55300666/whether-it-is-good-to-relay-tracing-on-mq-consumers
@adriancole
