### ISSUE TITLE
Merge script fails

### ISSUE THREAD

**Issue by johanoskarsson** [openzipkin/zipkin#246]
I attempted to merge a pull request, but it seems our little merge scripts is broken somehow.

[marburg zipkin (master)]$ bin/git-pull-request.rb merge 245
Executing: 'git config --get github.token'
warning: peer certificate won't be verified in this SSL session
Executing: 'git config --get github.token'
warning: peer certificate won't be verified in this SSL session
bin/git-pull-request.rb:187:in `merge': Not merging into master (RuntimeError)
    from bin/git-pull-request.rb:306

**Comment by bmdhacks** [comment]
Why not just use the web-based tools?

**Comment by johanoskarsson** [comment]
Mostly because I prefer squashed commits. I generally work on a branch and commit all kinds of crap while I work on it. It's the end result that counts.

/Johan

**Comment by bmdhacks** [comment]
That's a decent reason.  I'll take a look at it for merging the new build.

**Comment by bmdhacks** [comment]
I couldn't reproduce.  Maybe because I checkout everything over ssh?
