### ISSUE TITLE
setTag() to string

### ISSUE THREAD

**Issue by koushik9951** [openzipkin/zipkin#2468]
I am trying to send some information via Zipkin spans using set Tag() like hostname, application port, environment etc.  How to convert these values as Strings using SetTag().

Can someone help me on this

**Comment by codefromthecrypt** [comment]
Hi, I believe you were asking this on gitter, which is the correct place to do this. The same people who would work on an issue have been trying to help you there. Please try to explain on gitter. I feel perhaps there are some translation issues, but we'll get through them.
