### ISSUE TITLE
Make routing logic better in lens

### ISSUE THREAD

**Issue by tacigar** [openzipkin/zipkin#2473]
For example, When users click search button, the current implementation do the following.

![current-global-search](https://user-images.githubusercontent.com/19551419/55120516-c1ec8600-5139-11e9-86f3-ea5ba3efcdee.png)

This is very verbose.
I think this should be simplified as follows.
It is possible.

![new-global-search](https://user-images.githubusercontent.com/19551419/55120649-345d6600-513a-11e9-8839-82bcc24a0d69.png)

**Comment by codefromthecrypt** [comment]
I like simpler!

**Comment by tacigar** [comment]
Related #2384
