### ISSUE TITLE
Add dependencies analyze button to search bar

### ISSUE THREAD

**Issue by tacigar** [openzipkin/zipkin#2475]
To reuse search bar, I want to add dependencies analyze button to search bar and move the current search button like the following.

<img width="1540" alt="new" src="https://user-images.githubusercontent.com/19551419/55124345-4692d080-5149-11e9-8e50-9e1b463b368c.png">

@adriancole What do you think?

**Comment by codefromthecrypt** [comment]
only if the buttons are hand drawn like in your image :D

cc @openzipkin/ui

**Comment by codefromthecrypt** [comment]
@JordiPolo @drolando you tend to have opinions... what's yours on this?

**Comment by codefromthecrypt** [comment]
oops @jcarres-mdsol or whichever the real jordi is

**Comment by tacigar** [comment]
I'll try to implement it and make a PR.
Please give me feedback after that 🙇

**Comment by jcarres-mdsol** [comment]
I think both are real. Yeah, hand draw FTW

**Comment by drolando** [comment]
@tacigar do you want to completely remove the left sidebar?

**Comment by codefromthecrypt** [comment]
> do you want to completely remove the left sidebar?

interesting.. I kindof like the idea

**Comment by drolando** [comment]
I'm +1 on moving the search button out of the search box and maybe having it a bit bigger than now so that's it's more obvious.

I don't have any particular opinion on the dependency button as I don't use it. However we'd now have a pretty empty left sidebar. Maybe make it more narrow if we don't need to have any text there anymore and only icons?

What about that `?` button? What would it show?

Agreed that the new icons already look great! :D

**Comment by tacigar** [comment]
> do you want to completely remove the left sidebar?

Great idea!
I'll remove the left sidebar👍 
and I move the rest icons of the left sidebar to the footer.

> What about that ? button? What would it show?

Sorry, I forgot to explain that.
Because the screen will become a bit more complex, I want to add tooltip.
`?` button shows that.

**Comment by drolando** [comment]
>  I'll remove the left sideba and move the rest icons of the left sidebar to the footer.

Actually I'll downvote my own suggestion. Computer monitors are larger than they are higher and we don't really use the entire width anyway. I'd prefer being able to see more spans in the same screen rather than gain some extra useless space on the sides.

**Comment by codefromthecrypt** [comment]
My vote will go with the end users on this one... @tacigar @huydx maybe also run by some LINE end users?

**Comment by codefromthecrypt** [comment]
summary (my pov) on chat at the workshop. We agree we want context to be shared, specifically timerange between trace and dependenices graph. However, we want to ensure users aren't confused by what isn't supported (such as tag query) on the dependencies page.

Options discussed were disabling the dependencies screen like haystack does when extra fields are present, or greying out that criteria

**Comment by tacigar** [comment]
I think greying out is good idea

**Comment by shakuzen** [comment]
> greying out that criteria

This sounds like a decent solution as long as users understand why they are greyed out. Perhaps hovering over the greyed out elements should present a tooltip that explains why it is greyed out.
