### ISSUE TITLE
More visibility of the timing in spans

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin#2477]
**Feature:**
More visibility of the timing in spans

**Rational**
Currently it is not too intuitive to find the trace duration in the new UI, it gets lost together with the number of spans label. Since the number of spans in a trace is not as important as the latency I suggest we give more visibility to the time.

*Before*
![image](https://user-images.githubusercontent.com/3075074/55233912-30107600-522a-11e9-8f11-5fc182f1398a.png)

*After*
![image](https://user-images.githubusercontent.com/3075074/55233928-3999de00-522a-11e9-8548-9d1f094d29f4.png)

Ping @tacigar

**Comment by devinsba** [comment]
Agreed, makes sense to make the field that is sorted by (by default) be the one that is read first left-to-right

**Comment by tacigar** [comment]
I agree with you.
Could you make a PR?

**Comment by codefromthecrypt** [comment]
well done igarashi! it is a good idea to encourage others to help with the
code.

**Comment by jcchavezs** [comment]
Closing as https://github.com/openzipkin/zipkin/pull/2501
