### ISSUE TITLE
/api/v2 fails to handle CORS

### ISSUE THREAD

**Issue by JonasVerhofste** [openzipkin/zipkin#2486]
## Describe the Bug
When a reporter sends an OPTIONS request to /api/v2, the server gives an empty response and no tracing is done (no actual POST with data is done). See https://github.com/ewhauser/angular-tracing/issues/11

## Steps to Reproduce
In the above mentioned repo, run the demo with `yarn install` and `yarn quick`. When observing the developer tools of your browser, you should see OPTIONS-requests to localhost:9411, but no POST's with actual span data.

**Comment by devinsba** [comment]
Just want to make sure, have you configured CORS on the server: https://github.com/openzipkin/zipkin/tree/master/zipkin-server#cors-cross-origin-resource-sharing

It's possible this broke with the server engine change recently but want to validate

**Comment by JonasVerhofste** [comment]
I was using the docker container (both the version from two weeks ago and the newest one) and didn't touch the defaults. Seeing as the default is to allow all endpoints under `/api/v2`, I don't see why it shouldn't work.

Could be a problem with zipkin-js, but the response headers from the server are a tad strange, see the referenced issue, that's why I moved the issue here, as per @adriancole's request.

**Comment by codefromthecrypt** [comment]
please try zipkin 2.12.8!
