### ISSUE TITLE
Implement logs button in lens

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2491]
This is the description of the zipkin-ui README. Note that in lens we could implement the pattern differently. I recall someone asking to have properties besides traceId available. For example, localEndpoint.serviceName

## How do I find logs associated with a particular trace

Since zipkin provides a correlation id (the trace id), it's a good pattern to add it in your logs.
If you use zipkin, it's very likely that you have distributed logging sytem also and a way to query your logs (e.g. ELK stack).

One convenient way to switch from a trace to its logs is to get a button which directly links a trace to its logs.

This feature can be activated by setting the property `zipkin.ui.logs-url` or its corresponding environment variable:

* Kibana 3: `ZIPKIN_UI_LOGS_URL=http://kibana.company.com/query={traceId}`
* Kibana 4 or newer: `ZIPKIN_UI_LOGS_URL=http://kibana.company.com/app/kibana#/discover?_a=(index:'filebeat-*',query:(language:lucene,query:'{traceId}'))`
  This assumes that the log data is stored under the `filebeat-*` index pattern (replace this with the correct pattern if needed) and it uses the default timerange of 15 minutes (change it to 24 hours by adding `&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))` to the URL for example).

where `{traceId}` will be contextually replaced by the trace id.

If this feature is activated, you'll see on the trace detail page an additional button named `logs`.

![Logs Button](https://cloud.githubusercontent.com/assets/9842366/20482538/6e35ca66-afed-11e6-90e9-1e28f66d985e.png)

**Comment by codefromthecrypt** [comment]
this implies reading /config.json

**Comment by codefromthecrypt** [comment]
@tacigar fyi @shsamkit mentioned he can use lens once this is closed and until then is using classic

**Comment by aerfus** [comment]
Hello,
@adriancole are there plans to implement the feature
in the near future?

**Comment by codefromthecrypt** [comment]
we need someone to volunteer. there is no bench of people waiting for
tasks.. volunteer based. are you up for this?

**Comment by shsamkit** [comment]
I can help with it.

**Comment by aerfus** [comment]
Hello,
@adriancole sorry for misunderstanding.
I just wanted to know if someone is already implementing it...
@shsamkit do you need help?

**Comment by codefromthecrypt** [comment]
generally unless someone assigns themself or makes a comment that it is
being worked on, no one is on it.

that said it is polite when picking up something to say so.. that way just
in case someone is working on it, they can respond.

cheers!

**Comment by aerfus** [comment]
Hello,
@adriancole I'm up for this issue.
Could you please assign me to it or tell how to become a contributor?
Thank you in advance,

**Comment by codefromthecrypt** [comment]
Thanks @aerfus and good luck. You can raise a pull request using the normal github flow. Ex fork this project, make a branch for the work. look at the lens readme so you can verify. You can also look at existing similar unit tests. Once works, you can raise a pull request based on your branch. https://gitter.im/openzipkin/zipkin for questions. If you stop working on this, just comment back so that it doesn't block others. Take care and see you around.

**Comment by anuraaga** [comment]
@aerfus Thanks for the interest in helping out! We haven't heard from you in a while and as I've been on a sprint to get in features that are missing from lens in preparation of our full rollout of it, I've gone ahead and started working on this. Sorry if this squashes any existing work ><

**Comment by aerfus** [comment]
@anuraaga okay, then waiting for next release.
Thank you,
