### ISSUE TITLE
zipkin failed to startup

### ISSUE THREAD

**Issue by candy123360** [openzipkin/zipkin#2494]
i fetch the latest released server  version 2.12.8
use java -jar zipkin-server-2.12.8-exec.jar
and i get the following errors

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'armeria.ports[0].protocols[0]' to com.linecorp.armeria.common.SessionProtocol:

    Property: armeria.ports[0].protocols[0]
    Value: http
    Origin: class path resource [zipkin-server-shared.yml]:163:11
    Reason: 4

Action:

Update your application's configuration

how should i do?

**Comment by shakuzen** [comment]
Doing the following as mentioned [in our Quick Start instructions](https://github.com/openzipkin/zipkin#quick-start) worked for me:

```bash
curl -sSL https://zipkin.io/quickstart.sh | bash -s
java -jar zipkin.jar
```

Are you trying to use a custom zipkin-server-shared.yml file?
This kind of issue is easier to debug over chat. Join us on [our Gitter](https://gitter.im/openzipkin/zipkin)

**Comment by candy123360** [comment]
> Doing the following as mentioned [in our Quick Start instructions](https://github.com/openzipkin/zipkin#quick-start) worked for me:
> 
> ```shell
> curl -sSL https://zipkin.io/quickstart.sh | bash -s
> java -jar zipkin.jar
> ```
> 
> Are you trying to use a custom zipkin-server-shared.yml file?
> This kind of issue is easier to debug over chat. Join us on [our Gitter](https://gitter.im/openzipkin/zipkin)

i run the following command

curl -sSL https://zipkin.io/quickstart.sh | bash -s
java -jar zipkin.jar

and then i got the same errors as above
i am not use a custom zipkin-server-shared.yml file
i just fetch the jar file,and then run the jar file,i do nothing othes.

**Comment by candy123360** [comment]
the reason is the jdk version too old(1.8.0_20),upgrade the jdk version will resolve it.
