### ISSUE TITLE
have a threshold for when to use mini-map

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2503]
when a trace is small the minimap probably doesn't need to exist

![Screen Shot 2019-04-18 at 3 05 29 PM](https://user-images.githubusercontent.com/64215/56340031-8fd7bc80-61eb-11e9-9d00-375130f4d9fb.png)

<img width="992" alt="Screen Shot 2019-04-18 at 3 04 00 PM" src="https://user-images.githubusercontent.com/64215/56340035-936b4380-61eb-11e9-9f6b-e615edcc614a.png">

**Comment by tacigar** [comment]
What is the appropriate threshold?
Because we need the zoomup feature if we have more than one span, it is very difficult to set the threashold...

**Comment by tacigar** [comment]
One idea.
Set some threshold values (about 5 threasholds?).
Change the height of minimap component according to these threshold.

**Comment by codefromthecrypt** [comment]
I think if trace fits on screen maybe dont need minimap. not sure if this
can be detected

**Comment by tacigar** [comment]
Even if trace fits on screen, sometimes it needs zoom up like the following case.

<img width="650" alt="screenshot" src="https://user-images.githubusercontent.com/19551419/56429452-dae1f480-62fd-11e9-887c-6e4482be8b7b.png">

If there is not minimap, currently there is no other way to zoom up spans.

**Comment by codefromthecrypt** [comment]
good point. for starters we can set threshold for single span trace. no
minimap for that. later we can figure out more cases?

**Comment by shakuzen** [comment]
I would say two spans or less is a good start. Even if one is very short, I'm not sure zooming in on it makes sense if it is the only span to zoom in on.

**Comment by tacigar** [comment]
I think this issue is solved in #2529 
But I don't have permission to close issues 😭
