### ISSUE TITLE
Improve span view header size and content in lens

### ISSUE THREAD

**Issue by huydx** [openzipkin/zipkin#2514]
**Feature:**
When we click on the span detail view dropdown now, we have a little bit redundancy in information and the visualization (bold, big size) seems not neccessary.

![](https://i.gyazo.com/b328faa2fa2351724be68d1c1c222d98.png)

Proposal:
- Highlight the click span instead and remove the span name header (redis:evalsha in the image)

**Comment by jcchavezs** [comment]
Difficult to tell. As a user, maybe I don't need it so big but I think it
is still good to have the span name.

fre. 19. apr. 2019, 06:07 skrev 0x6875790d0a <notifications@github.com>:

**Comment by huydx** [comment]
@jcchavezs We talked about highlight the span row part which has the name, so we could have the same effect though, HDYT?

**Comment by jorgheymans** [comment]
In current Lens, the span detail view has moved out from being a dropdown to a permanent panel on the right. The service and span name are prominently visible, and being no longer close to the actual span location in the trace tree that's actually a good thing.  

![image](https://user-images.githubusercontent.com/193792/97629790-e227a980-1a2e-11eb-8167-9c0a8eafb6eb.png)

Closing this as no longer relevant, if you have other suggestion how to improve the trace detail view feel free to open a new ticket.
