### ISSUE TITLE
Zipkin api page is not available

### ISSUE THREAD

**Issue by Reo-LEI** [openzipkin/zipkin#2515]
from a few days ago, the [page](https://zipkin.io/zipkin-api/#/default/post_spans) of zipkin api is not available. Is it has been remove to another url? 

![image](https://user-images.githubusercontent.com/17312872/56404924-1b108b00-629c-11e9-870a-e014eaba81b5.png)

Actually, I just want to refer to the definition of span v2. Where I could look up this definition except the zipkin api definition page?

**Comment by shakuzen** [comment]
Sorry about the unexpected unavailability of the API documentation site. We are tracking fixing this in https://github.com/apache/incubator-zipkin-api/issues/62. Once that is fixed, it should be available again. In the meantime, the Swagger spec source can be found in that repository, though: https://github.com/apache/incubator-zipkin-api/blob/master/zipkin2-api.yaml
