### ISSUE TITLE
Search broken on traces page?

### ISSUE THREAD

**Issue by derekchiang** [openzipkin/zipkin#252]
Is it just me or is the search bar completely unusable?  No queries are returning any results.

Also, I wonder if `ctrl + F` works for your guys?  For me, In Firefox, `ctrl + F` doesn't highlight the text being searched, whereas in Chrome `ctrl + F` just doesn't work on the traces page.

**Comment by derekchiang** [comment]
I would certainly like to fix the bugs if this isn't a local issue.

**Comment by bmdhacks** [comment]
Are you talking about the text entry search bar in the web UI when viewing
a trace?  The one that collapses any spans that don't match it?  Works for
me.  Or are you specifically talking about Control-F in the browser, which
also works for me?  Maybe it's something else that I'm missing?

**Comment by derekchiang** [comment]
Yeah I'm talking about both.  Glad that it works for you.  Not working for me :(

**Comment by bmdhacks** [comment]
I'm not sure what I can do without more information.  The fact that Control-F isn't working on your browser seems to point to a client-side issue, but I'll leave this issue open for a bit to give you some time to track it down.

**Comment by derekchiang** [comment]
I think that's a front end issue.  I will look into it and reopen this if necessary.  Thanks for the support.
