### ISSUE TITLE
Broken link on the official site

### ISSUE THREAD

**Issue by Guchman** [openzipkin/zipkin#2522]
There is broken link on [Data Model](https://zipkin.io/pages/data_model.html) page.
I'm looking for API documentation, but it's [404](https://zipkin.io/zipkin-api/#/default/post_spans):(

**Comment by codefromthecrypt** [comment]
thanks this is a duplicated of https://github.com/apache/incubator-zipkin-api/issues/62 as we recently moved to apache org which broke some of our hosting setup. sorry! in the mean time you can look at https://zipkin.apache.org/
