### ISSUE TITLE
Change span details design in lens

### ISSUE THREAD

**Issue by tacigar** [openzipkin/zipkin#2525]
Now lens shows span details as dropdown in trace view.
At first glance this design looks good, because users seem enable to see multiple span details at the same time.
However, recently I think this design is not good for UX.
The reasons are as follows:

1. In most cases, we cannot see multiple span details at the same time because span details often have too much data (annotations & tags), so we can often see only one span details at the same time.
2. Span details prevent viewing the whole of trace.
3. I'm thinking of using SVG for trace view. But it is a bit hard for me to do it, because span details component is mostly composed of text data, so it's troublesome to make it with SVG...

Instead of current design, I recommend the design previously proposed by Adrian in #2293 .
I think this design is simple and perfect.

<img width="1000" alt="49215426-e26f3280-f41c-11e8-889a-2c944c0f423c" src="https://user-images.githubusercontent.com/19551419/56481739-75f3ed80-64fb-11e9-9973-a32510eda053.png">

What do you think about it?

**Comment by codefromthecrypt** [comment]
I also agree with old version of me :D

**Comment by shakuzen** [comment]
I'm torn on this. It loses horizontal real estate which means it will compress spans horizontally compared to the current design. On the other hand, I suppose it helps keep the context above and now also below the selected span available visually. Hopefully we can get some more feedback from sites about their thoughts on this - though to reiterate the original issue was feedback raised from Atlassian.

**Comment by jcchavezs** [comment]
I would prefer to keep the current details as it is for a couple of reasons:
1. Long tags (like SQL queries) might become very thight if moving the
details to the right.
2. In large traced, using the full screen is sometimes not enough and some
span look very small, I am concerned about using only a portion of the
screen.

If the concern is about the length of the current span details we could
maybe have two tag pairs per row? That would decrease the length of the
details view.

**Comment by shakuzen** [comment]
> It loses horizontal real estate which means it will compress spans horizontally compared to the current design.

On this comment from me, I think my concerns are mostly alleviated if the pane to the right can be resized/collapsed to regain horizontal space for the graph, if desired.
I also realize that there is a trend these days for monitors to be (much) wider than they are tall, so maybe not as big of a deal.
