### ISSUE TITLE
readme: Javadocs returns 404

### ISSUE THREAD

**Issue by olegrok** [openzipkin/zipkin#2528]
I tried to open http://zipkin.io/zipkin (as in https://github.com/apache/incubator-zipkin#javadocs)

But this resource returns `404 File not found`. Fix it please or remove from readme to avoid confusions

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/openzipkin.github.io  is for that website, which is being decommissioned.

zipkin.apache.org (https://github.com/apache/incubator-zipkin-website) is the replacement so any change should happen there. Unfortunately issues are currently disabled by accident, so we have to open a PR and reference this issue.

**Comment by jorgheymans** [comment]
https://zipkin.io/zipkin/ is correct as the README says.
