### ISSUE TITLE
Skip protoc execution when tests are skipped

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/zipkin#2530]
We tried to use Jitpack to test a build of the Zipkin Server from a pull request (#2328), but the build failed with the following.

https://jitpack.io/com/github/ewhauser/zipkin/experimental-grpc-1.5.0-g7a0c3ce-1160/build.log

```
[INFO] --- protobuf-maven-plugin:0.6.1:test-compile (test-compile-proto) @ zipkin-server ---
[INFO] Compiling 1 proto file(s) to /home/jitpack/build/zipkin-server/target/generated-test-sources/protobuf/java
[ERROR] PROTOC FAILED: /home/jitpack/build/zipkin-server/target/protoc-plugins/protoc-3.7.0-linux-x86_64.exe: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

[ERROR] /home/jitpack/build/zipkin-server/target/test/proto/zipkin.proto [0:0]: /home/jitpack/build/zipkin-server/target/protoc-plugins/protoc-3.7.0-linux-x86_64.exe: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

Since this protoc execution is only for tests and the build is skipping tests, we should be able to disable it when tests are skipped so Jitpack succeeds. This can probably be done in a Maven profile.
Alternatively, we can customize the command Jitpack uses to build, but I do like it working out-of-the-box (as it did before the pull request added GRPC collector support) and I wonder if Zipkin developers wouldn't also run into this problem on their machines.
/cc @bsideup

**Comment by anuraaga** [comment]
For reference, the libatomic dependency will go away in the next release of protoc I believe

https://github.com/protocolbuffers/protobuf/issues/5875

**Comment by shakuzen** [comment]
Thanks for the heads up. That's good to know.
@jorgheymans also mentioned that using `-Dmaven.test.skip=true` should skip compiling tests.

**Comment by codefromthecrypt** [comment]
testing now cc @ewhauser 

see https://github.com/apache/incubator-zipkin-website/issues/4#issuecomment-486511959

**Comment by codefromthecrypt** [comment]
looks like it works https://jitpack.io/com/github/ewhauser/zipkin/experimental-grpc-1.5.0-g94ac6cf-1164/build.log
