### ISSUE TITLE
Get links of traces

### ISSUE THREAD

**Issue by derekchiang** [openzipkin/zipkin#254]
Is there a way to get the URL to a specific trace?  So, having a trace id, how do I programmatically get the URL to the web page of that trace?

Thanks,
Derek

**Comment by bmdhacks** [comment]
http://your.zipkin.hostname.example.com/traces/<trace-id>

**Comment by derekchiang** [comment]
That's what I thought but it didn't appear so.  The trace id and the id in
the URL appeared different on my machine... What could be the reasons?

Best Regards,
Derek Chiang
(Sent from Android phone)

**Comment by bmdhacks** [comment]
One is signed hex and one is unsigned decimal?

**Comment by bmdhacks** [comment]
Sorry, I mean one is unsigned hex and one is signed decimal.

**Comment by derekchiang** [comment]
@bmdhacks  aha here we go!  thanks!
