### ISSUE TITLE
无法在注册中心是nacos的时候使用zipkin

### ISSUE THREAD

**Issue by gshjd** [openzipkin/zipkin#2540]
无法在注册中心是nacos的时候使用zipkin，能给一个解决方案吗？

**Comment by shakuzen** [comment]
Courtesy of Google Translate:

> Can't use zipkin when the registry is nacos, can you give a solution?

I assume this refers to this nacos: https://github.com/alibaba/nacos
I'm not familiar with nacos and I don't think we've had any users ask about it before. Can you explain more how you are trying to use nacos with Zipkin? For service discovery?

**Comment by nkorange** [comment]
@shakuzen I'm from Nacos team, let me explain this. Nacos is an open source registry center and configuration center originated from Alibaba and now more and more users are moving from Eureka to Nacos.

When users are replacing their registry center from Eureka to Nacos, they frequently get an error like 'service $zipkin-server not found'. We guess Zipkin must have implicitly registered its address to Eureka so it can be found via a service name. 

Turning off the service discovery option of Zipkin usually works, but I think it's better for Nacos to be able to recognize Zipkin service. I would like to contribute for it and can you provide some clues where should I start?

**Comment by shakuzen** [comment]
@nkorange thank you for reaching out. We have had several users ask about service discovery with Zipkin Server over the years (see #1870) and less ask about dynamic/external configuration. We don't currently support any service discovery as a first-class feature. There is a workaround to use Eureka mentioned in #1870. So unless a user is using that, or is building a custom Zipkin Server (which we don't officially support), there should be no service discovery.

If you want to come chat with us on Gitter (https://gitter.im/openzipkin/zipkin) about next steps, please do.

**Comment by chuntaojun** [comment]
> 无法在注册中心是nacos的时候使用zipkin，能给一个解决方案吗？

你好，我想问问，具体的问题表现是怎样的呢？

**Comment by mathcoder23** [comment]
我的可以使用呀，你需要说明具体的情况，你的zipkin是用什么方式引用的，会不会是fegin，nacos之类的http拦截器产生了冲突。

**Comment by chuntaojun** [comment]
> 我的可以使用呀，你需要说明具体的情况，你的zipkin是用什么方式引用的，会不会是fegin，nacos之类的http拦截器产生了冲突。

你使用zipkin是，是采用服务名的形式还是直接写上zipkin-server的ip地址

**Comment by mathcoder23** [comment]
> > 我的可以使用呀，你需要说明具体的情况，你的zipkin是用什么方式引用的，会不会是fegin，nacos之类的http拦截器产生了冲突。
> 
> 你使用zipkin是，是采用服务名的形式还是直接写上zipkin-server的ip地址

我使用的等价于ip地址(内部dns)，没有采用服务名称，因为zipkin服务和项目服务部署上是分离的。

**Comment by chuntaojun** [comment]
哦，可能有点使用者是将zipkin-server注册为一个服务然后使用的，这种情况下会有一些问题

**Comment by ChrisLeejing** [comment]
Maybe, the problem is solved.

**Comment by jorgheymans** [comment]
Question seems to have been answered, also https://github.com/openzipkin/zipkin/tree/master/zipkin-server#custom-servers-are-not-supported

**Comment by codefromthecrypt** [comment]
fyi eureka will end up as an option for registration of zipkin, but not discovery of resources zipkin uses. other options for registration are discussable, but there is work involved to do it right.

See https://github.com/openzipkin/zipkin/pull/3671
