### ISSUE TITLE
DEPENDENCIES file missing from sub-projects

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2543]
we made a change to disable root-level DEPENDENCIES file, but it seems it is not in the submodules either. We should fix this before graduation.

See https://github.com/apache/incubator-zipkin-brave-karaf/issues/42

**Comment by codefromthecrypt** [comment]
this is not a blocker per https://lists.apache.org/thread.html/4edaa84d2425b40f252f0ea0b1dbf7b8ca8299fd6d23de7f9df62d85@%3Cgeneral.incubator.apache.org%3E but it is a nice-to-have

**Comment by jorgheymans** [comment]
DEPENDENCIES, graduation huh what was all that about ??
