### ISSUE TITLE
Fix issues needed prior to graduation

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2544]
For each of the below, please cite a mail thread or closed issue when ticking the box.

- [x] rid the manual clicking of "Scan Repository Now" needed to build pull requests with jenkins
  * [INFRA-17787](https://issues.apache.org/jira/browse/INFRA-17787) -> [builds@a.o thread](https://lists.apache.org/thread.html/104cb2622ba97f69ce242521b5ae2982b1ebce06560650ea45eb5d29@%3Cbuilds.apache.org%3E)
  * [INFRA-18363](https://issues.apache.org/jira/browse/INFRA-18363)
- [x] Decision on what to do about the OpenZipkin brand
  * Apache Zipkin uses a different logo than the former used by OpenZipkin and Twitter
- [ ] Choose a new logo designed by LINE
  * vote thread https://lists.apache.org/thread.html/e5b3789bbeaca2335cc65c6e3919554c8bbc06b7613a954269ac12f9@%3Cdev.zipkin.apache.org%3E
- [ ] upload whatever our logo ends up as to http://www.apache.org/logos/
- [ ] Decision on what to do with repositories in the OpenZipkin org
  * See email thread here https://lists.apache.org/thread.html/6f7102b1205683e1846d012c6fd53f2913438283ac9984c1d3193aba@%3Cdev.zipkin.apache.org%3E
- [ ] Decision on what to do with Docker images
  * See email thread https://lists.apache.org/thread.html/ccc2104558d592671782c8c52417732c92a8f14d80ff416985cec33f@%3Cdev.zipkin.apache.org%3E
- [x] Decision on DEPENDENCIES file
  - nice to have per https://lists.apache.org/thread.html/4edaa84d2425b40f252f0ea0b1dbf7b8ca8299fd6d23de7f9df62d85@%3Cgeneral.incubator.apache.org%3E
- [ ] setup download page on zipkin.apache.org
  * https://github.com/apache/incubator-zipkin-website/issues/12
- [x] setup redirect of zipkin.io to zipkin.apache.org
  * https://github.com/apache/incubator-zipkin-website/issues/14
- [ ] do podling search thing https://incubator.apache.org/guides/names.html#conducting_a_suitable_name_search

**Comment by codefromthecrypt** [comment]
@zeagord can you do me a favor and hunt the issue tracking our need to click "Scan Repository Now" and cite it under the first bullet point? I think I've lost a fair amount of time so far forgetting for a half hour to click this and I think we need to track this somewhere in our domain.

**Comment by codefromthecrypt** [comment]
sorry above comment was for @abesto, not @zeagord (I started typing z and mind didn't work after!)

**Comment by abesto** [comment]
Wow I'm bad at GH notifications nowadays. On it right now.
... aaaand done.

**Comment by codefromthecrypt** [comment]
added some tasks coming out of https://lists.apache.org/thread.html/81b6cb8d23f287ec95f80f0ede0c00601a600d54a30a1bf4e7423283@%3Cdev.zipkin.apache.org%3E

cc @apache/zipkin-committers

**Comment by codefromthecrypt** [comment]
I've asked if maybe someone can help donate a new logo as that is easier than explaining how a logo already used widely is somehow exclusively now the property of apache

**Comment by wu-sheng** [comment]
@adriancole Good to have this issue. I forgot to share this.

## Docker image related
SkyWalking DockerHub repositories have been asked having potential branding issue as well, just before one month before graduation, because of the same name and same logo. This is the last thing I deal with before graduation proposal.

I moved the SkyWalking's to ASF official docker repo
- https://cloud.docker.com/u/apache/repository/docker/apache/skywalking-oap-server/general
- https://cloud.docker.com/u/apache/repository/docker/apache/skywalking-ui/general

**Comment by codefromthecrypt** [comment]
@wu-sheng can you share any issue with details about this, jira or github? right now, we publish via quay.io and we have access there and also dockerhub. I've noticed in ASF often we don't have full access to things.. can you share some details?

**Comment by wu-sheng** [comment]
> can you share any issue with details about this, jira or github? 

This comes from Justin as well, but in private ml. And our mentor, Ignasi, explained the concerns. The reason is very similar to the concerns of openzipkin logo. ASF doesn't want to make the confusions about which things belong to ASF or 3rd party, especially when the INFRA controlled by the same people in the PMC.

> right now, we publish via quay.io and we have access there and also dockerhub. I've noticed in ASF often we don't have full access to things.. can you share some details?

Right now, several PMC members(Hongtao Gao mostly) publish the docker image to dockerhub directly.

**Comment by codefromthecrypt** [comment]
On the docker topic, as I understand it, the problem is advertising a third party image. Clearly, there is no requirement to even have a docker image. For example, Kafka produces none, though the commercial company behind it does.

I can grok not wanting to be a sneaky ad for a commercial package, but I don't know where exactly a problem would be in mentioning images that predated apache and are completely non-commercial in nature. It seems odd that Apache would actually have a problem with a healthy ecosystem that produces tools for it to the point where it intentionally wants you to make it hard to find them. However, we seem to be in a culture which is against things and I am tired of arguing against the grain for sensible pragmatism.

I think the work and confusion involved in splitting our docker images between the openzipkin namespace and apache namespace is more of a burden than instructing people manually how to find docker images. What that seems to mean is deleting references to the openzipkin images until the leadership in ASF decide that OSS ecosystems are nothing to be afraid of.

**Comment by jeqo** [comment]
@adriancole could you explain what the `DEPENDENCIES` file is about? I'd like to help on tackling that one, and I can't find another apache project with that file.

**Comment by reta** [comment]
Sorry @jeqo, since @adriancole is still off, will try to help you here. This file is generated by `maven-remote-resources-plugin`, but due to the issue with submodules

https://issues.apache.org/jira/browse/MPOM-218
https://github.com/apache/incubator-zipkin-brave-karaf/pull/39/files

it was not generated anymore. Hope it helps.

**Comment by codefromthecrypt** [comment]
DEPENDENCIES is not a blocker per https://lists.apache.org/thread.html/4edaa84d2425b40f252f0ea0b1dbf7b8ca8299fd6d23de7f9df62d85@%3Cgeneral.incubator.apache.org%3E but it is a nice-to-have. removing from this issue description now.

**Comment by codefromthecrypt** [comment]
on the logo, we have a rough understanding that LINE (brokered by @syleeeee) will offer a logo to use for Apache Zipkin (different than OpenZipkin). Thanks in advance for the help!

Next step is to discuss on the mailing list https://lists.apache.org/list.html?dev@zipkin.apache.org
* ex email dev-subscribe@zipkin.apache.org, then email dev@zipkin.apache.org

**Comment by shakuzen** [comment]
Closing this as Zipkin has withdrawn from the Apache Incubator.
