### ISSUE TITLE
Current build process includes dependency-reduced-pom.xml which must be excluded 

### ISSUE THREAD

**Issue by zeagord** [openzipkin/zipkin#2553]
## Describe the Bug
During the preparation of the apache release, the source contains the `dependency-reduced-pom.xml` whihc is not supposed to be included in the source.

## Steps to Reproduce
Verify the source of 2.13.0 

## Expected Behaviour
`dependency-reduced-pom.xml` must be excluded

**Comment by codefromthecrypt** [comment]
another thing is to move it to the target directory so that it isn't included (assuming target/** are magically excluded in the assembly)
