### ISSUE TITLE
be able to handle large traces in UI

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#2554]
Currently, both Lens and Zipkin classic UIs do not handle large traces gracefully (see also https://github.com/apache/incubator-zipkin/issues/2496 and https://github.com/apache/incubator-zipkin/issues/1460). 

Pagination has been suggested several times (#2240) but from a UI perspective it's not clear how this would be represented.

I think that a drill-down mode could be more helpful here, a natural way to investigate a trace is by clicking your way through the parts that take up the most time until you get to the leaf spans.

**Comment by codefromthecrypt** [comment]
closing as a dupe as there's no value in creating another yet another fork on the same topic
