### ISSUE TITLE
lens: trace lookup criteria appear chopped off

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#2565]
![image](https://user-images.githubusercontent.com/193792/57297491-028fd580-70d0-11e9-8fac-c6536d901153.png)

This is on Chrome, Firefox 60 ESR does not have the issue.

**Comment by tacigar** [comment]
Maybe this issue is solved in #2633 .
Would you please check after merged?

**Comment by shakuzen** [comment]
@jorgheymans could you recheck this when you get a chance?

**Comment by jorgheymans** [comment]
Will do next week when back from holidays!

Op di 6 aug. 2019 13:13 schreef Tommy Ludwig <notifications@github.com>:

**Comment by jorgheymans** [comment]
seems fixed in latest 2.16.2-SNAPSHOT, thanks !
