### ISSUE TITLE
Display "Try Lens UI" in the center of the screen

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2566]
In a chat with @bulicekj we found that haystack also had problems with people knowing there was a new UI.

It could help to put the "Try Lens UI" button in the center of the screen when the UI is first loaded. I noticed today someone not noticing there was an option to try it.

from  @iwanskit
> ok thanks I was thinking that it is some kind of firefox feature. I never used that before.

Note: depending on progress towards the project to make lens default.. this could be moot

**Comment by jorgheymans** [comment]
Lens is now the default UI.
