### ISSUE TITLE
Delete zipkin-ui module

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2569]
When we delete the zipkin-ui module, we need to also delete any references to it. Here is a list of some of these

* LICENSE - at the bottom there are notices about chosen and dagre-d3 which should be removed. #2568
* pom.xml - license exclusions in both the license and rat plugin configuration

**Comment by codefromthecrypt** [comment]
It turns out that we can delete this a lot sooner than we expected, solving the problem by using an archive repo instead of constantly building the same code here: https://github.com/openzipkin/zipkin-classic/

once #2603 is merged we should do the following in one PR (@zeagord claimed the honors on this)

* move zipkin-ui/testdata to zipkin-lens
* remove exclusions in pom.xml `remove when deleting zipkin-ui #2569`
* remove recursively the zipkin-ui directory
* remove the following from the LICENSE file

```
This product contains a modified part of Chosen, distributed by Harvest:

  * License: MIT
  * Homepage: https://github.com/harvesthq/chosen

This product contains a modified part of Dager-D3, distributed by Dagre:

  * License: MIT
  * Homepage: https://github.com/dagrejs/dagre-d3
```

**Comment by jorgheymans** [comment]
zipkin-ui module was deleted.
