### ISSUE TITLE
customize  zipkin.ui.basepath  but  404

### ISSUE THREAD

**Issue by icodegarden** [openzipkin/zipkin#2574]
## Describe the Bug
I tried to use    zipkin.ui.basepath    to customize the basepath of the ui, but accessed 404.

## Steps to Reproduce
1.start zipkin server with  --zipkin.ui.basepath=/myzipkin 
2.visit http://zipkin:9411 on Browser， but the Browser redirect the location to http://zipkin:9411/zipkin/ and shows  "Zipkin   Investigate system behavior" ，When I try to visit http://zipkin:9411/myzipkin/          it still display 404 Not Found  .

## Expected Behaviour
visit http://zipkin:9411 redirect  to http://zipkin:9411/myzipkin/ and  Correct display .

**Comment by codefromthecrypt** [comment]
zipkin.ui.basepath doesn't control redirects, it controls the links inside the UI. It is used when a proxy is in front of zipkin. https://github.com/openzipkin/zipkin/tree/master/zipkin-server#configuration-for-the-ui

please join gitter for questions https://gitter.im/openzipkin/zipkin
