### ISSUE TITLE
使用阿里云的amqp rabbitmq时报错

### ISSUE THREAD

**Issue by bianxiaojin** [openzipkin/zipkin#2590]
使用阿里云的amqp rabbitmq时报错  reply-text=QueueConsumerNameInvalid，咨询阿里得知因为他们$是非法字符，而zipkin的consumertag是zipkin2.collector.rabbitmq.RabbitMQCollector$RabbitMQSpanConsumer0

**Comment by codefromthecrypt** [comment]
sorry google translate isn't working well. Do you mean to say if there are
chinese characters in a consumer tag, the rabbitmq feature errors?

**Comment by bianxiaojin** [comment]
"$"   this character

**Comment by codefromthecrypt** [comment]
This is in inner class that's why there is a `$` character.

I'm unclear what impact this has, can you post an exception or error message?

**Comment by codefromthecrypt** [comment]
please take a look at this https://github.com/openzipkin/zipkin/pull/2641
