### ISSUE TITLE
Try to downsize a little

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2596]
When updating to Kafka 2.2 we are now over 50Mib again (52.5M).

Here are the top 10 biggest single-file dependencies. Note that this doesn't imply they are the largest dep trees.
```
6328131 Fri May 10 15:43:50 CEST 2019 BOOT-INF/lib/armeria-0.85.0.jar
3874332 Tue Jan 08 16:44:40 CET 2019 BOOT-INF/lib/zstd-jni-1.3.8-1.jar
3113599 Sat Mar 23 20:40:48 CET 2019 BOOT-INF/lib/netty-tcnative-boringssl-static-2.0.23.Final.jar
2726299 Fri Mar 01 17:37:00 CET 2019 BOOT-INF/lib/cassandra-driver-core-3.7.1-shaded.jar
2661351 Sat Mar 09 11:44:42 CET 2019 BOOT-INF/lib/kafka-clients-2.2.0.jar
2442264 Wed May 15 16:15:32 CEST 2019 BOOT-INF/lib/zipkin-ui-2.13.1-SNAPSHOT.jar
2370102 Tue Apr 09 15:00:16 CEST 2019 BOOT-INF/lib/jooq-3.11.11.jar
2308517 Wed Dec 09 15:58:22 CET 2015 BOOT-INF/lib/guava-19.0.jar
2018686 Mon May 21 18:18:34 CEST 2018 BOOT-INF/lib/snappy-java-1.1.7.2.jar
1629585 Tue Feb 05 18:12:30 CET 2019 BOOT-INF/lib/log4j-core-2.11.2.jar
```

**Comment by codefromthecrypt** [comment]
Kafka has a bunch of the largest deps. I think on gitter we discussed that likely there is nothing we can do about it as it isn't appropriate to remove one of its compression libraries. It is a shame they are so huge. cc @jeqo 

```
[INFO] +- org.apache.zipkin.zipkin2:zipkin-collector-kafka:jar:2.13.1-SNAPSHOT:compile (optional) 
[INFO] |  \- org.apache.kafka:kafka-clients:jar:2.2.0:compile (optional) 
[INFO] |     +- com.github.luben:zstd-jni:jar:1.3.8-1:compile (optional) 
[INFO] |     +- org.lz4:lz4-java:jar:1.5.0:compile (optional) 
[INFO] |     \- org.xerial.snappy:snappy-java:jar:1.1.7.2:compile (optional) 
```

**Comment by codefromthecrypt** [comment]
once the UI is finally killed we will be under 50 again anyway

**Comment by codefromthecrypt** [comment]
@anuraaga do you think it is important for us to bundle netty-tcnative-boringssl-static? What would not work if we didn't?

**Comment by codefromthecrypt** [comment]
I looked at some suspicious once.. jsoup is 400K and deals with something that seems normal string replacement should work out. Basically, we should be able to control our index.html generation in lens and ui to always emit the base tag, eliminating this logic: https://github.com/apache/incubator-zipkin/blob/master/zipkin-server/src/main/java/zipkin2/server/internal/ui/ZipkinUiConfiguration.java#L116-L120

then, the replacement here should be normal string replacement.

Note: I just checked and here is the base tag in our two UIs
zipkin-ui: `<base href="/zipkin/">`
zipkin-lens: `<base href=/ />`

**Comment by codefromthecrypt** [comment]
note if we update from guava 19 -> guava 27 the size grows about 1MiB not just because the increase in stuff inside guava, but also because its growing dependency tree

**Comment by jorgheymans** [comment]
I'ld think excluding `netty-tcnative-boringssl-static` is definitely worth a try, i know grpc with the netty transport works without it if you don't use TLS.

**Comment by jeqo** [comment]
@adriancole yes, we discussed that. We could potentially remove compression libraries and offer a way to add them to the classpath if required; or we could have different distributions with/without. WDYT?

**Comment by codefromthecrypt** [comment]
good news is that these kafka compression jars have no dependencies.. it
could be reasonable to explain how to get them (using curl for example)
except that knowing which versions might take some shell scripting..
(haven't looked to see how stable the APIs are)

**Comment by codefromthecrypt** [comment]
I wonder if even if you do use SSL if boring SSL is required (ex jre 11..
does it need this?)

**Comment by anuraaga** [comment]
Java 11 (technically 9+) don't need boringssl for TLS. I've had mixed results with comparing performance of Java vs boringssl anyways, so seems fine to exclude it if we're ok with making it more annoying to use on Java 8.

**Comment by jorgheymans** [comment]
also `jooq` for a feature that is not really recommend to be used in production ...

**Comment by codefromthecrypt** [comment]
thanks for the feedback folks. I think our next minor can get more slim

**Comment by codefromthecrypt** [comment]
Jorge, in the use case of span data reporting.. if you had to pick one
compression which would it be? since this is only for the server we can
take an opinion

**Comment by jeqo** [comment]
Have been using snappy lately but haven't benchmark them myself. 
Found [this benchmark from cloudflare](https://blog.cloudflare.com/squeezing-the-firehose/) and seems like the best choice would be between snappy for kafka <2.1 and zstd for >=2.1.
Probably worth making a benchmark based on tracing data and ship zipkin server with recommended compression libs.

**Comment by anuraaga** [comment]
By the way, I think this is a zipkin server running on Java 8. I'm currently trying to recommend reducing the list of ciphers and using boringssl, for what it's worth.

https://github.com/line/armeria/issues/1772

Paper trail
https://github.com/line/armeria/issues/1711
https://github.com/apache/incubator-zipkin/issues/2449

**Comment by anuraaga** [comment]
Additional thought, a compromise would be to include netty-tcnative instead of netty-tcnative-boringssl-static. It's only 25K as opposed to 3MB and still allows using OpenSSL if it happens to be on the system and linkable. I've never used it though and don't know what the success chance of such linking actually happening is. But if it didn't work and it's Java 9+, it'd still work with the JDK provider.

**Comment by codefromthecrypt** [comment]
On Thu, May 16, 2019 at 10:55 AM Anuraag Agrawal <notifications@github.com>
wrote:

> Additional thought, a compromise would be to include netty-tcnative
> instead of netty-tcnative-boringssl-static. It's only 25K as opposed to 3MB
> and still allows using OpenSSL if it happens to be on the system and
> linkable. I've never used it though and don't know what the success chance
> of such linking actually happening is.
>
Do we know anyone who would know if it were working or not? Perhaps we can
have an ad-hoc test..

**Comment by anuraaga** [comment]
It's easy to check, armeria logs at startup whether it's using openssl or not. But I was more thinking of the fact that when others use it, it will depend highly on their OS setup, etc whether openssl gets loaded or not correctly, which isn't something we can test for.

**Comment by codefromthecrypt** [comment]
suppose an answer could be that we remove it and wait for someone to ask
about this ;) the jar is self contained so they could add to classpath.

**Comment by jorgheymans** [comment]
Effort was completed to create a "slim" version which currently weighs in at about half the size of the 'classic' zipkin server , and further additions of any new dependencies are heavily scrutinized first.
