### ISSUE TITLE
Opentelemetry

### ISSUE THREAD

**Issue by JonasVerhofste** [openzipkin/zipkin#2598]
I'm probably a bit late to the party, but I just stumbled across OpenTelemetry, OpenTracing and OpenCensus' effort to [merge their projects](https://medium.com/opentracing/merging-opentracing-and-opencensus-f0fe9c7ca6f0) and bundle their powers.

I know Zipkin doesn't have anything to do with both (or not anymore at least, if I understand correctly), but seeing as OpenTelemetry's goal is mainly to "reduce the number of instrumentation standards to one", I'm wondering where Zipkin stands in all of this, being, in my opinion, the most widespread of the currently existing projects, having that extensive list of supported languages and frameworks.

**Comment by codefromthecrypt** [comment]
this project is a server backend and the project currently named OpenTelemetry sends data to Zipkin.

considering there are few projects that call themselves standards they may achieve the goal of merging the standards they formerly made into one. That will be measured by the former ones (opentracing notably) actually migrating to whatever is made here as opposed to tools being revlocked to the former.

Ambitious goals aside, I think folks should tread carefully as all new projects drift and mapping and misunderstandings are common when things are run at a distance from end users.

We have no plans to drop support for our data format, or drop our server for what the project currently named opentelemetry is doing. I do anticipate mapping problems, as already we've seen things creating overly chatty and/or redundant data. However, there's no reason some of these things could not work out.

That said, we have no goal to choose opentelemetry at the expense several years of work done by a far more diverse number of parties. In other words, don't expect us to choose this project favorite at the expense of others, based solely on their ambition or project naming convention. Concretely, we won't be deleting our data types for example. Other instrumentation and export to other systems via the specifications we have published will continue.

I'm closing this issue as issues as we define them are changes to this codebase. This is more a question, which I hope I've answered. If you want to chat more, there's https://gitter.im/openzipkin/zipkin

Cheers,
-a

**Comment by JonasVerhofste** [comment]
> We have no plans to drop support for our data format, or drop our server for what the project currently named opentelemetry is doing.

> That said, we have no goal to choose opentelemetry at the expense several years of work done by a far more diverse number of parties. In other words, don't expect us to choose this project favorite at the expense of others, based solely on their ambition or project naming convention. Concretely, we won't be deleting our data types for example.

@adriancole And I didn't/don't expect you to, just wanted to know the general opinion on the matter. Choose an issue over gitter so the answer can be found in the future by people who have the same question. Thanks for answering!

**Comment by codefromthecrypt** [comment]
opened https://github.com/openzipkin-contrib/zipkin-otel to carry any of this forward, if people decide to commit to review and maintenance there.
