### ISSUE TITLE
request parameter details

### ISSUE THREAD

**Issue by halower** [openzipkin/zipkin#2599]
the latest version does not see the request parameter details?

**Comment by codefromthecrypt** [comment]
can you clarify what you mean? are you talking about logging? maybe paste screenshot before and after?

**Comment by halower** [comment]
I have used a very early version before, I will see the `Key`, `Value` and other request parameter information when requesting, but the current version, I did not find such parameter information.
![](https://github.com/blacklau/http-dubbo-zipkin/raw/master/request-params.png)

**Comment by codefromthecrypt** [comment]
if you can paste trace json we might be able to tell what the issue is.

**Comment by jorgheymans** [comment]
@halower feel free to hop on over on our [gitter](https://gitter.im/openzipkin/zipkin) channel if you have more questions like this.
