### ISSUE TITLE
lens trace viewer seems busted

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2600]
Tried to load a trace json and got this. same trace doesn't break in zipkin classic.

<img width="952" alt="Screen Shot 2019-05-16 at 1 46 38 PM" src="https://user-images.githubusercontent.com/64215/57851570-327e5d80-77e1-11e9-8e15-bea85f299e80.png">

**Comment by shakuzen** [comment]
I'm also seeing this with 2.13.0

**Comment by jcchavezs** [comment]
Is the PR closing this issue @tacigar? If that is the case I suggest we use the key `Closes #xxx` to automagically close the issue on PR merge :).

**Comment by jorgheymans** [comment]
Works for me now, issue can be closed i think.

**Comment by shakuzen** [comment]
Resolved by #2608
