### ISSUE TITLE
Reset zoom capability in lens

### ISSUE THREAD

**Issue by lambcode** [openzipkin/zipkin#2601]
Once you've zoomed in using the minimap in lens, it is cumbersome to zoom out again to the full trace. It's too easy to cut off a small section at the beginning or end without having pixel perfect cursor placement. I recommend that a simpler solution to zooming out is implemented. One idea would be to use the grayed out area as an area to click on to zoom out. Another is a dedicated zoom out button placed somewhere near the minimap.

![mockup](https://user-images.githubusercontent.com/5820125/57870887-4a47e880-77c5-11e9-9f11-ad0c6486f549.png)

**Comment by jorgheymans** [comment]
quite like the idea of using the grey area to end zoom, to me at least it feels rather intuitive

**Comment by tacigar** [comment]
Great idea!!
