### ISSUE TITLE
ZipKin with Mysql

### ISSUE THREAD

**Issue by JaveedAliKhanA** [openzipkin/zipkin#2607]
Hi Team,
I Configured Zipkin with spring boot micro service projects. i am able to run and watch service details on Zipkin UI. I would like to store span, dependecies and annotationas in to my SQL Database. 
  I did MySQl configuration in application.property file, but need help how to store data from springboot request controller to mysql tables. 

Thank you
Javeed Ali Khan A

**Comment by devinsba** [comment]
Hi, it looks like you are building a custom zipkin server. Unfortunately we cannot provide support for custom servers, we are a small group of volunteers and custom servers can have so many variables that it is too big of a burden on our community.

Did you know there are pre-built distributions of zipkin? Please check out our documentation for more information: https://github.com/apache/incubator-zipkin/blob/master/zipkin-server/README.md
