### ISSUE TITLE
User friendly span duration on reload

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin#2612]
**Feature:**
User friendly span duration on reload

**Rational**
Right now if you set a minimum duration in let's say seconds and then reload, the search bar converts seconds into microseconds (e.g. 5s into 5000000ms). I believe searchbar should be as friendly as possible.

**Comment by shakuzen** [comment]
Do you mean in the URL? It seems the classic UI does use what the user enters in the URL (e.g. `5s`), but Lens does convert to microseconds and use that in the URL with no units.

**Comment by jcchavezs** [comment]
Yeah, si I believe lens can easily detect that 300000 is divisible by 1000
but not by 10000000 and hence show 300ms.

tir. 28. mai 2019, 18:02 skrev Tommy Ludwig <notifications@github.com>:
