### ISSUE TITLE
Fontawesome is loaded from CDN, so Zipkin Lens doesn't work well offline

### ISSUE THREAD

**Issue by pete-woods** [openzipkin/zipkin#2615]
## Describe the Bug
index.html directly refers to fontawesome via CDN

## Expected Behaviour
Fontawesome should be an NPM dependency, and packed with WebPack. I would also recommend using Create React App, rather than doing all the build script stuff yourselves. It's much easier, IMO!

**Comment by jcchavezs** [comment]
Ping @tacigar

fre. 24. mai 2019, 20:16 skrev Pete Woods <notifications@github.com>:

**Comment by codefromthecrypt** [comment]
I completely agree this is an issue. Can you raise a pull request with the minimal changes needed here?

**Comment by pete-woods** [comment]
If you're asking me, alas I'm not a strong enough web-packer to do it myself (tried for a bit and failed). I've always relied on [CRA](https://github.com/facebook/create-react-app) to do all the heavy lifting of that side for me in the past.

**Comment by codefromthecrypt** [comment]
I wonder if the bat signal works.. tap tap @abesto tap..

**Comment by abesto** [comment]
Heh. Yeah, today happens to be a Zipkin evening for me. (I'll be looking at this plus issues on the release checker, feel free to point me at anything more urgent)
