### ISSUE TITLE
Not all client to client relations taken into account in 'Dependencies' tree 

### ISSUE THREAD

**Issue by tommic81** [openzipkin/zipkin#2616]
## Describe the Bug

zipkin: 2.12.9

Some relations between  client services are not visible  on the graph.

## Steps to Reproduce

We came across two problems when analyzing dependencies.

The first one,  when component A (within service 1) calls component B  (still within service 1)  and then  component B  calls component C in service 2.
It turned out that only relation B --> C is visible.

I found in **zipkin2.internal.DependencyLinker** a condition causing this problem:
**line: 70**

```
// When processing links to a client span, we prefer the server's name. If we have no child
// spans, we proceed to use the name the client chose.
if (Kind.CLIENT.equals(kind) && !current.children().isEmpty()) {
   continue;
}
```

It looks like it's done on purpose but I do not understand why. 
Why do we want to  skip CLIENT spans which might possess some children?

When I commented out that suspicious condition, the dependency graph was almost correct.

I am saying "almost" because I spotted another thing.

When CLIENT span A calls CLIENT span B and they have the same service name, the link is not built. IMHO it might be visible on the graph  as a node with a link to itself.

I found in **zipkin2.internal.DependencyLinker** there is code probably preventing this kind of relations: 
**line 127**
```
 if (kind == Kind.CLIENT && serviceName != null && !remoteAncestorName.equals(serviceName)) {
///.......//
}
```

[zipkin-sample-spans.txt](https://github.com/apache/incubator-zipkin/files/3223851/zipkin-sample-spans.txt)

## Expected Behaviour

The dependency diagram including all relations.

**Comment by codefromthecrypt** [comment]
the dependency graph is about remote links, and in terms of RPC model a client calls a server, not a client calling a client. It sounds like an instrumentation bug or misconfiguration, or otherwise redundant client spans. A loopback call on the same host, for example, is still a client calling a server (just they have the same localEndpoint)

**Comment by tommic81** [comment]
Hi @adriancole ,

Don't you think it is worth to present on the  dependency graph all the requests even within the same runtime? 
I believe it is quite normal that developers may want to generate  spans to measure/visualize requests/responses between different components of the same application.

For example someone might generate spans to profile/measure  the code flow connecting to some database. 
It would be pretty valuable to see what happened  on the dependency graph.

Assuming that, the dependency graph must be limited only  to RPC CLIENT --> SERVER calls, there 
is still something wrong. 

The condition which I mentioned above:

```
if (Kind.CLIENT.equals(kind) && !current.children().isEmpty()) {
   continue;
}
```
omits relations between server and client as client component has some descendants.  

 component A ( SERVER) -->  component B  (CLIENT) --> SOME_OTHER_SPANS

**Comment by codefromthecrypt** [comment]
The dependency graph is an aggregation of remote calls even loopback ones. This includes support for RPC and messaging links as we define them. There are facets to handle some instrumentation problems, however the goal is definitely not to aggregate intermediate/local spans. If we did, it would break everyone who for the last few years have always had remote aggregations.. some sites, this would explode the amount of links for example.

The line you are looking at is relating to a leaf-call to an uninstrumented node (ex client calling a SaaS like an authorization service that isn't traced). Our linker supports creating a virtual link in these circumstances, provided a remote service name exists on the client span.

If there is a bug, it is better to use a unit test vs eyeballing as things are quite nuanced. You can try breaking it with valid data if you like by adding a test. Just understand this line is totally about establishing a virtual link for a remote service.. not links inside the same process.

At any rate, here are a couple layers of tests that exist should you want to carry this forward.

unit test: https://github.com/apache/incubator-zipkin/blob/master/zipkin/src/test/java/zipkin2/internal/DependencyLinkerTest.java
integration test: https://github.com/apache/incubator-zipkin/blob/master/zipkin-tests/src/main/java/zipkin2/storage/ITDependencies.java

**Comment by codefromthecrypt** [comment]
ps looking at your data span 076fecc8a861e28e, I think localEndpoint.serviceName ="auth" should have been remoteEndpoint.serviceName= "auth" if in the same process.

you could make the case that a child span of a client that is an incidental request could make another link to an uninstrumented service.. just it would need to be a link to the service identified as remoteEndpoint.serviceName. localEndpoint.serviceName should be constant for the local call tree starting with the inbound server request. IOTW I think there is a little bit of things in the wrong spot. Does that make sense?

**Comment by codefromthecrypt** [comment]
here's an [example json](https://github.com/apache/incubator-zipkin/blob/master/zipkin-lens/testdata/simple-db-p6.json) showing a remote service name used. Anyway since this thread will spam watchers. let's use chat for follow-up https://gitter.im/openzipkin/zipkin
