### ISSUE TITLE
Request method 'POST' not supported

### ISSUE THREAD

**Issue by panchen66** [openzipkin/zipkin#2625]
i use spring-boot-starter-parent （2.1.2.RELEASE）  and zipkin-autoconfigure-ui/zipkin-server(2.12.0)  to make zipkin-server. 
i don't used official jar ，  because i need to Adding a layer to intercept at the server so that the sending link reaches our service。
then my zipkin-client is use spring-cloud-starter-zipkin-2.0.0.RC2.

When the client sends to the server， log is 
`TEST2019-06-09 18:01:26.879  WARN 134340 --- [  XNIO-1 task-1] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]`

i see ， the request is POST /api/v2/spans  
and ZipkinHttpCollector.java is not changed。

**Comment by codefromthecrypt** [comment]
we don't support custom servers. Moreover, gitter is for q/a and support, not issues. You can discuss in gitter your need for a custom server, in case there's a way to do it without making one. Good luck https://gitter.im/openzipkin/zipkin
