### ISSUE TITLE
HTTPS/SSL failing for 2.14 zipkin

### ISSUE THREAD

**Issue by koushik9951** [openzipkin/zipkin#2627]
I am trying to enable HTTPS for 2.14 Zipkin version, but SSL arguments are not picking by the jar file, whereas for 2.12 version HTTPS is working fine.

can some help me with this ...!

**java -jar /opt/zipkin/zipkin-server-2.14.0.jar --LOG_LEVEL=INFO --server.port=9141 --server.ssl.key-store=/opt/Zipkin/2.14/zipkin.jks --server.ssl.key-store-password=123123 --server.ssl.key-password=123123 --security.require-ssl=true**

**Comment by codefromthecrypt** [comment]
Hi @koushik9951 we have a related issue for armeria to accept spring boot defaults for TLS configuration. Meanwhile, here are working instructions you can use.

```bash
# assuming you generate the key like this
keytool -genkeypair -alias koushik9951 -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore zipkin.p12 -validity 3650

# enter the following overrides, note the password is key-store-password not key-password
java -jar zipkin.jar --armeria.ssl.key-store=zipkin.p12 --armeria.ssl.key-store-type=PKCS12 --armeria.ssl.key-store-password=123123 --armeria.ssl.key-alias=koushik9951  --armeria.ssl.enabled=true --armeria.ports[0].port=9411 --armeria.ports[0].protocols[0]=https
```

cc also @gquintana

**Comment by koushik9951** [comment]
@adriancole: Thanks for updating with SSL details

**Comment by abkura** [comment]
@koushik9951 i'm having the same issue enabling https(TLSv1.2) on ZipkinServer.  Can you please share your insights if you were able to solve the issue

Versions: OpenJDK 8, Zipkin-Server-2.19.2; self-signed JKS cert

**Comment by kajalkotian94** [comment]
> HTTPS

@koushik9951 Can you please share the data used to enable https for 2.12 version
