### ISSUE TITLE
Zipkin issues with MariaDB Integration

### ISSUE THREAD

**Issue by harishkadamudi** [openzipkin/zipkin#2628]
## Describe the Bug
**Zipkin integrated with MariaDB creating duplicate Indexes**

We have Zipkin server integrated with MariaDB.
Of late, we found MariaDB is slow in responding, Calls from zipkin-UI are taking longer than usual time, we thought it could be because of data
After close investigation, we found out that, multiple indexes on table zipkin span
Indexes looks like below
trace_id_high
trace_id_high_2
trace_id_high_2
....
....
trace_id_high_15

since it is creating multiple indexes, CPU usage is very high and doing lot of IO operations, hence delaying even a simple queries.

## Steps to Reproduce
Below is my pom details to reproduce the Issue.

```
<zipkin.main.version>2.4.6</zipkin.main.version>
<zipkin.server.version>2.4.6</zipkin.server.version>
<spring.cloud.version>Dalston.RELEASE</spring.cloud.version>
<spring.boot.version>1.5.14.RELEASE</spring.boot.version>

<dependency>
	<groupId>io.zipkin.java</groupId>
	<artifactId>zipkin</artifactId>
	<version>${zipkin.main.version}</version>
</dependency>
<dependency>
	<groupId>io.zipkin.java</groupId>
	<artifactId>zipkin-server</artifactId>
	<version>${zipkin.server.version}</version>
</dependency>
<dependency>
	<groupId>io.zipkin.java</groupId>
	<artifactId>zipkin-autoconfigure-ui</artifactId>
	<version>${zipkin.server.version}</version>
	<scope>runtime</scope>
</dependency>
```
It also looks like every time we restart zipkin server indexes are growing in numbers

## Expected Behaviour
Zipkin server shouldn't create multiple/duplicate Indexes

**Comment by codefromthecrypt** [comment]
you are commenting about an old version of zipkin, about a custom server configuration, and about a configuration known to not be performant.

https://github.com/apache/incubator-zipkin#mysql

I'm going to close this issue as we don't support custom servers. Also, our mysql module doesn't install schemas (install DDL) either, so something else might be up.

We use chat for support, but as noted custom servers are not supported. Please use most recent zipkin and a standard distribution when asking for support. If you need support on a build we produce, feel free to chat on gitter https://gitter.im/openzipkin/zipkin
