### ISSUE TITLE
Revert migration to the ASF

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2629]
As you know, [we voted to withdraw](https://lists.apache.org/thread.html/e3d911151dff081145886b620145924067267de998da40495b1f996b@%3Cdev.zipkin.apache.org%3E) from the Apache Incubator. This issue tracks work towards that across all repos and will be updated with tick boxes as we proceed.

- [x] Restore license, build and deployment configuration
  - [x] openzipkin/zipkin 2.4.2 https://github.com/apache/incubator-zipkin/pull/2630
  - [x] openzipkin/zipkin-dependencies 2.3.0 https://github.com/apache/incubator-zipkin-dependencies/pull/141
  - [x] openzipkin/zipkin-api 0.2.1 https://github.com/apache/incubator-zipkin-api/pull/76
  - [x] openzipkin/b3-propagation https://github.com/apache/incubator-zipkin-b3-propagation/pull/35
  - [x] openzipkin/zipkin-reporter-java 2.8.4 https://github.com/apache/incubator-zipkin-reporter-java/pull/148
  - [x] openzipkin/brave 5.6.5 https://github.com/apache/incubator-zipkin-brave/pull/925
  - [x] openzipkin/brave-cassandra 0.10.3 https://github.com/apache/incubator-zipkin-brave-cassandra/pull/24
  - [x] openzipkin/brave-karaf 0.1.2 https://github.com/apache/incubator-zipkin-brave-karaf/pull/43
  - [x] openzipkin/zipkin-layout-factory 0.0.5 https://github.com/apache/incubator-zipkin-layout-factory/pull/12
- [x] Move repos back to the OpenZipkin org https://issues.apache.org/jira/browse/INFRA-18604
  - [x] openzipkin/zipkin
  - [x] openzipkin/zipkin-dependencies
  - [x] openzipkin/zipkin-api
  - [x] openzipkin/b3-propagation
  - [x] openzipkin/zipkin-reporter-java
  - [x] openzipkin/brave
  - [x] openzipkin/brave-cassandra
  - [x] openzipkin/brave-karaf
  - [x] openzipkin/zipkin-layout-factory
- [x] Re-encrypt travis credentials and re-webhook gitter once repos are back in the OpenZipkin org
  - [x] openzipkin/zipkin
  - [x] openzipkin/zipkin-dependencies
  - [x] openzipkin/zipkin-api
  - [x] openzipkin/b3-propagation (no travis credentials needed)
  - [x] openzipkin/zipkin-reporter-java
  - [x] openzipkin/brave
  - [x] openzipkin/brave-cassandra
  - [x] openzipkin/brave-karaf
  - [x] openzipkin/zipkin-layout-factory
- [ ] Restore zipkin.io website
  - [x] move repo back to openzipkin
  - [x] remove cloudflare forwarding rule that pushes zipkin.io -> zipkin.apache.org
  - [x] merge any website updates made since https://github.com/openzipkin/openzipkin.github.io/pull/129
  - [x] update zipkin.apache.org to redirect to zipkin.io or similar
  - [ ] attic apache/incubator-zipkin-website
- [x] move content in https://cwiki.apache.org/confluence/display/ZIPKIN to OpenZipkin
  - [x] bulk content https://github.com/openzipkin/openzipkin.github.io/issues/130
  - [x] [Designs/b3 single header format](https://cwiki.apache.org/confluence/display/ZIPKIN/b3+single+header+format) -> [b3-propagation/RATIONALE.md](https://github.com/apache/incubator-zipkin-b3-propagation/blob/master/RATIONALE.md)
  - [x] [Feature Tracking/128-bit Trace ID support](https://cwiki.apache.org/confluence/display/ZIPKIN/128-bit+Trace+ID+support) -> [b3-propagation/STATUS.md](https://github.com/apache/incubator-zipkin-b3-propagation/blob/master/STATUS.md)
  - [x] [Feature Tracking/b3 single header support](https://cwiki.apache.org/confluence/display/ZIPKIN/128-bit+Trace+ID+support) -> [b3-propagation/STATUS.md](https://github.com/apache/incubator-zipkin-b3-propagation/blob/master/STATUS.md)
- [x] revert quickstart.sh to point to openzipkin deployment
  - [x] zipkin.io
  - [x] zipkin.apache.org
- [x] Revert docker images to openzipkin/zipkin dependencies https://github.com/openzipkin/docker-zipkin/pull/211
- [x] Revert downstream projects to openzipkin/zipkin dependencies
  - [x] zipkin-gcp 0.13.0 https://github.com/openzipkin/zipkin-gcp/pull/128
  - [x] zipkin-aws 0.17.1 https://github.com/openzipkin/zipkin-aws/pull/131
- [ ] Edit podlings.xml to say something like `The Zipkin podling has retired to its former community [OpenZipkin](https://zipkin.io)`

## Get releases back online ASAP
We are critically behind schedule for things like brave releases: 3 months which is a time period we've never experienced before. Above all, we need to get functional again so that we don't further injure our community.

### License, group IDs etc.
First step is to change project assets back to the old group IDs, remove mention of the disclaimer and revert the license headers to the more generic one we had before (except possibly leaving out the year).

### Deploying under zipkin.io
Deployment wise, the quickest way to get back online would be to deploy to sonatype directly and skip setting up bintray again, using the same tooling as we have with ASF. This is probably better anyway, as bintray we were over resources with anyway.

### Signing keys
There is no legal exclusivity as far as I know to the GPG keys we have. IOTW, we can use them to sign anything, including things not in the ASF.  Folks who desire to make new keys surely can, but I don't think it is required to.

## Migration of repos back to OpenZipkin
You'll remember github was a one way street access wise.. we had to grant Apache INFRA admin, and lose our access except to commit files (ex we have no control over anything including webhooks, much less the ability to move our repos back). This means we need to place a ticket and that might happen soon or not depending on their workload.

## Migration of Website
The website is more straightforward as almost all content updates were ASF in nature and in a new repo. If it is possible to "un-archive" our old repo, I suggest we just do that and fix the DNS.

cc @apache/zipkin-committers

**Comment by codefromthecrypt** [comment]
added rough draft of steps for the website

**Comment by codefromthecrypt** [comment]
Added reference to https://issues.apache.org/jira/browse/INFRA-18604

**Comment by codefromthecrypt** [comment]
note: until the repositories are moved back to the openzipkin org, our deployment automation will fail (ex bintray will reject uploads even with encrypted credentials). Until https://issues.apache.org/jira/browse/INFRA-18604 is solved, or another mechanism is made, uploads are manual similar to apache.

**Comment by codefromthecrypt** [comment]
all repos are back now

**Comment by codefromthecrypt** [comment]
https://issues.apache.org/jira/browse/INFRA-18809 is about getting zipkin.apache.org decommissioned or redirecting or something thx @abesto for raising it

**Comment by abesto** [comment]
Redirect is up:

```
$ curl -D- https://zipkin.apache.org/quickstart.html
HTTP/1.1 301 Moved Permanently
Date: Tue, 30 Jul 2019 08:32:06 GMT
Server: Apache/2.4.18 (Ubuntu)
Location: https://zipkin.io/quickstart.html
Content-Length: 241
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://zipkin.io/quickstart.html">here</a>.</p>
</body></html>
```

**Comment by jorgheymans** [comment]
Migration reverted thanks.
