### ISSUE TITLE
can zipkin provide the function of collecting some specific request trace?

### ISSUE THREAD

**Issue by wuchenglong1** [openzipkin/zipkin#2634]
now zipkin provides the sampler,but sometimes i want to collect some specific request trace by configuration file for example,in springboot application.properties,i configurate the service interface like 'com.xxx.xxservice__1_0/execute'，and last zipkin will read the configuration file's service interface and only collect the trace info of  the service interface: 'com.xxx.xxservice__1_0/execute'. can i do the exention of this function?

**Comment by codefromthecrypt** [comment]
I'm guessing this is a question about sleuth or brave as this would be addressed in the client. possibly this https://cloud.spring.io/spring-cloud-sleuth/2.1.x/single/spring-cloud-sleuth.html#_http

We don't use issues for questions, so please follow-up on gitter https://gitter.im/openzipkin/zipkin
