### ISSUE TITLE
Use friendly timestamp like old UI

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin#2635]
**Feature:**
Labels like `less than a minute ago` were good to catch when something was recent over some trace that was old (mostly interesting when you have recent traces you wanna see). Also having labels for `x minutes ago` feels more natural to read.

**Rational**
It was in old UI and I think it was good.
![image (2)](https://user-images.githubusercontent.com/3075074/59840737-40c91780-9353-11e9-88f3-85884828bccd.png)

**Prior Art**

![image (1)](https://user-images.githubusercontent.com/3075074/59840754-46266200-9353-11e9-8161-6622208ce5f9.png)

Ping @kirkov

**Comment by jorgheymans** [comment]
Also https://github.com/openzipkin/zipkin/issues/2351#issuecomment-490047313, but a separate issue here makes it more visible.

**Comment by tacigar** [comment]
We can use `fromNow` method of `moment`.

https://momentjs.com/docs/#/displaying/fromnow/
