### ISSUE TITLE
Make Zipkin browser extension use templates

### ISSUE THREAD

**Issue by IceCreamYou** [openzipkin/zipkin#264]
As discussed in https://github.com/twitter/zipkin/pull/261, the Zipkin browser extension currently renders the Firebug panel by directly constructing HTML. There's not a whole lot of HTML to construct, but it would be easier to maintain and audit for security if it was done using templates instead. Unfortunately we can't easily drop in something like [Hogan](https://github.com/twitter/hogan.js) because it has to execute in the Chrome context which doesn't have the same APIs available as the browser window. Firebug uses [Domplate](https://getfirebug.com/wiki/index.php/Domplate), which uses JS to build the DOM instead of HTML templates with substitutions, but that's annoyingly verbose. It's not clear to me what the canonical approach is for Firefox addons, if there is one, but it probably leans towards Domplate.

Using HTML-based templates is feasible, but will require a little work.

**Comment by rtyler** [comment]
I've moved this ticket along with the source code, see openzipkin/browser-extension#1
