### ISSUE TITLE
should we be filtering our metrics?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2643]
@mstaalesen noticed we have some less useful metrics which can pollute folks prometheus

![image](https://user-images.githubusercontent.com/64215/60331237-ca698c80-99c6-11e9-9c3e-6a7a1e733be3.png)

**Comment by jorgheymans** [comment]
@jorgheymans notes we have a less useful stamp sized screenshot here which does not help deciding what needs to be done. @mstaalesen do you remember what this is about ?

**Comment by jorgheymans** [comment]
Apparently not. Current metrics are accessible on `/metrics` :

![image](https://user-images.githubusercontent.com/193792/95476149-389d4d00-0987-11eb-9df9-20e060cfdf94.png)


If anyone still has an issue with this feel free to create a separate issue.
