### ISSUE TITLE
what is the difference between zipkin v1 with v2?

### ISSUE THREAD

**Issue by keets2012** [openzipkin/zipkin#2644]
hello. I'm building micro-service in go. I found several go clients, such as zipkin-go and zipkin-go-opentracing while `zipkin-go-opentracing` supports v1,`zipkin-go` supports v2. 

i wanna know  the difference between zipkin v1 with v2.

**Comment by jcchavezs** [comment]
The format is different. Zipkin V1 is and old (on deprecation) much more
verbose and requieres more data whereas zipkin v2 is the new, simple and
concise. While zipkin-go-opentracing is supporting only v1 ATM, there is an
ongoing effort to move it into v2 (which will be finished in the upcoming
weeks, see
https://github.com/openzipkin-contrib/zipkin-go-opentracing/pull/123). We
highly recommend to avoid v1 clients if possible.

BTW, for further questions like this join us on gitter: https://gitter.im/openzipkin/zipkin

**Comment by keets2012** [comment]
ok, got it. Hope to see  that ` zipkin-go-opentracing`  supports for zipkin v2.
