### ISSUE TITLE
Apache Pulsar collector and reporter.

### ISSUE THREAD

**Issue by codelipenghui** [openzipkin/zipkin#2645]
**Feature:**

Pulsar is a highly scalable, low latency messaging platform running on
commodity hardware. It provides simple pub-sub semantics over topics.

Hope zipkin can use pulsar as collector and reporter, In this way, users who only use pulsar but not Kafka do not need to maintain Kafka anymore.

I'd be happy to do that if the community agrees.

**Comment by codefromthecrypt** [comment]
dupe of #2297 please carry on there as while there was interest as far as I know, no one did anything

**Comment by sijie** [comment]
@codelipenghui if you are starting implementing Pulsar collector and reporter, you might consider leaving a comment in #2297 so other people know you are starting the work to avoid duplicated work.
