### ISSUE TITLE
How to filter the zipkin error tag

### ISSUE THREAD

**Issue by donydex** [openzipkin/zipkin#2648]
Please first, look at [existing issues](https://github.com/openzipkin/zipkin/issues) to see if the feature has been requested before. If you don't find anything tell us what problem you’re trying to solve. Often a solution already exists! Don’t send pull requests to implement new features without first getting our support. Sometimes we leave features out on purpose to keep the project small.

**Feature:**
Description of the feature
Filte zipkin
![image](https://user-images.githubusercontent.com/11333398/60525533-1ac35000-9d21-11e9-8dbe-dd818a4de2ac.png)
There are  some error tag data in zipkin output ,such as 
![image](https://user-images.githubusercontent.com/11333398/60525597-45ada400-9d21-11e9-9b5f-49e7a91f7480.png)
with error tag in it's json data 
![image](https://user-images.githubusercontent.com/11333398/60525659-670e9000-9d21-11e9-87b5-ac1dda8178a5.png)

we would like to filter this data, but we don't know how to get a output without error data into mysql database.

**Rational**
Why this feature should be in zipkin

**Example Scenario**
When will this be used by operators?

**Prior Art**
 * Links to prior art
 * More links

**Comment by codefromthecrypt** [comment]
you can type error into the annotation box or "error=exactmatch" there is partial match.

Also, please upgrade and click the lens button for the new UI as the controls are more intuitive

Next time use gitter for questions please! https://gitter.im/openzipkin/zipkin
