### ISSUE TITLE
unkotlin the tests

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2655]
we kindof rushed a decision in #2570 to kotlin the tests. This was from an understanding that folks wanted to get more familiarity with kotlin as we were being asked about it in Brave for example. In hind sight, I don't think those who were interested in the idea were impacted much, for better or for worse. On the other hand @anuraaga has been stifled in attempts to refactor elasticsearch.

We can still have a kotlin module somewhere, but I think this may have done more bad than good in hindsight.

I offer labor to undo the kotlinification.. whether that's before or after @anuraaga's in flight change. up to him

cc @huydx @shakuzen

**Comment by shakuzen** [comment]
If it is slowing down progress on things, I'd be for converting back to Java. I know I would have to spend some time learning before I would be able to touch the Kotlin code with confidence or debug when running into something unexpected. As suggested, perhaps a more isolated area is best for easing our way into more Kotlin familiarity.

**Comment by anuraaga** [comment]
Thanks for the consideration - I'd be fine with the undo happening before or after my change, either way is fine.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2679 fixes this
