### ISSUE TITLE
compile error: address.getHostString can't be accessed

### ISSUE THREAD

**Issue by shijinkui** [openzipkin/zipkin#268]
![qq20130628-2](https://f.cloud.github.com/assets/648508/719692/107b3514-df94-11e2-8417-a0c3192faccb.png)

in my local branch, i have modify it.  

who can fix it in master branch ?

**Comment by bmdhacks** [comment]
You can!  Send a pull request and I'll merge it!

**Comment by xbeta** [comment]
I still have this issue, but I don't see the fix got merged as part of a pull request. Was this fixed?
