### ISSUE TITLE
docker进入kafka执行查看消费者命令显示not found

### ISSUE THREAD

**Issue by Neptoned** [openzipkin/zipkin#2681]
## Describe the Bug
docker进入kafka执行查看消费者命令显示not found，将kafka-console-consumer.sh命令第一行#!/bin/bash改成#!/busybox/sh后才能执行

## Steps to Reproduce
[root@localhost middle]# docker exec -it kafka-zookeeper /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
[root@localhost middle]# docker exec -it kafka-zookeeper /busybox/sh
/kafka # ./bin/kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic test --from-beginning
/busybox/sh: ./bin/kafka-console-consumer.sh: not found

## Expected Behaviour
docker-zipkin-2.11.12版本正常，docker-compose.yml使用image: openzipkin/zipkin-kafka:2.11.12

**Comment by codefromthecrypt** [comment]
try more recent docker image version (ex 2.15) please as we won't make
changes to old ones.

**Comment by codefromthecrypt** [comment]
wrong repo
