### ISSUE TITLE
Remove trace preview feature

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2685]
Many may recall we had a trace preview feature in the search results screen. This I believe was an idea borrowed from jaeger. As discussed with @tacigar this is probably not a worthwhile feature.

For example, it appears to solve the trace comparison use case but it doesn't. For example, it is unlikely you will have two traces near each-other in the results and even if you did, the scrolling up and down wildly through expanded traces thing isn't that effective.

Moreover, there's recent work in the UI to share data between the trace list and the trace view page, which obviates network calls. In other words, as long as navigation such as "back" works properly, there's no reason to overload the screen, especially for performance reasons.

This should buy back code and complexity for better purposes. For example, right now no screen is ideal for comparing multiple traces. However, we could build a compare screen and let people select into it.

cc @openzipkin/ui @narayaruna

**Comment by codefromthecrypt** [comment]
Ex the part to remove is the expansion here. You'll notice it is only luck that the traces of interest (expanded) are with only one trace between them. In simple traces like from zipkin server, only 4-7 spans, this looks benign, but you could imagine LINE and others have 800 span traces, so expanding them inline is not that useful.

<img width="1012" alt="Screenshot 2019-07-19 at 10 04 36 AM" src="https://user-images.githubusercontent.com/64215/61501932-a4a33680-aa0c-11e9-8627-d0e441d19507.png">


cc also @bulicekj

**Comment by jorgheymans** [comment]
+1 because less screen overload.
