### ISSUE TITLE
question in using zipkin

### ISSUE THREAD

**Issue by shijinkui** [openzipkin/zipkin#269]
in `TracingFilterBenchmark` line `val echoServiceWithZipkin = new TracingFilter(ZipkinTracer.mk(sampleRate=0.0f)) andThen echoService
`

Trace is the record entrance,  it's a traint; ZipkinTracer is the implements class. 

how the `Trace` invoke the method `record` of `ZipkinTracer`?

i'm not familiar with scala principle.  :(   help me

**Comment by shijinkui** [comment]
@bmdhacks @mosesn

**Comment by mosesn** [comment]
[TracingFilter](https://github.com/twitter/finagle/blob/master/finagle-core/src/main/scala/com/twitter/finagle/tracing/TracingFilter.scala) will register a [Tracer](https://github.com/twitter/finagle/blob/master/finagle-core/src/main/scala/com/twitter/finagle/tracing/Tracer.scala) with [Trace](https://github.com/twitter/finagle/blob/master/finagle-core/src/main/scala/com/twitter/finagle/tracing/Trace.scala).

**Comment by shijinkui** [comment]
find it. thanks
