### ISSUE TITLE
zipkin web should remember your sort order

### ISSUE THREAD

**Issue by astubbs** [openzipkin/zipkin#271]
It keeps defaulting back to slowest request. I am currently preferring timestamp descending, and every-time i refresh or navigate back to the page i have to reset the sort order.

**Comment by jdb8** [comment]
Seconding this request, needing to update the sort dropdown every time after querying for new traces is a bit inconvenient.

**Comment by t-yuki** [comment]
I want to implement this.
Well, Which storage we should use? Cookie? Local/Session Storage?
Currently the cookie has `last-serviceName` param.

**Comment by yurishkuro** [comment]
to ease the maintenance, it's better to use the same storage mechanism as the serviceName dropdown.

**Comment by jdb8** [comment]
Any reason these kind of settings can't just be query params? Then they'd also be linkable to others/bookmarkable.

**Comment by yurishkuro** [comment]
@jdb8 good idea! The JS can manipulate the current URL. But I think the setting still needs to be saved into a cookie, because when people want a new search they click on the home icon, and that wouldn't preserve the sorting field.

**Comment by codefromthecrypt** [comment]
Depends on what you mean..

Ordering the spans that are returned is pretty commodity and doesnt need to
be done server side. Hidden form etc (or query which only applies to the
UI) are low hanging fruit.

Changing the actual query is overkill for the problem and would be
expensive to implement

**Comment by yurishkuro** [comment]
@adriancole the way I understood it, the sorting is still done on UI side, but the sorting order is determined by
1. if in query param, use that
2. otherwise, if in cookie, use that
3. otherwise use the default order "longest first"

**Comment by eirslett** [comment]
My understanding is that this was implemented in a PR. So this issue should be fixed. If not, please reopen!
