### ISSUE TITLE
enlist empty endpoint group exceptions as RejectedExecution

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2714]
With the new elasticsearch code, we will have dynamic endpoints. This is good because it can shrink and grow due to health. It is also possible to get an empty endpoint group exception invoking a request. This needs to integrate with the storage throttling code, and I think the easiest way is to throw a RejectedExecutionException when the endpoints are empty

cc @Logic-32

**Comment by Logic-32** [comment]
Not quite up to speed with the new Elasticsearch code, can you provide some more details on how to reproduce this?  E.g. versions, rough order of events that have to occur?

Mostly, I want to just make sure that an UnprocessedRequestException actually follows the model of "the server was overloaded" and not something as simple as "our node got taken offline while we were trying to use it so we need to try again on a different node" (assuming "dynamic endpoints" means were talking about an elastic cluster).

**Comment by codefromthecrypt** [comment]
@Logic-32 let's let behavior drive this. Are you saying that when no hosts are available you would let the calls crash?

**Comment by codefromthecrypt** [comment]
no hosts available is because nothing passed elasticsearch health check at the moment, so if we decide to act differently, it should make sense. Ex why do we back off when the busy queue is full, but not when the health check is red. It is ok to drop, just when the next person asks we need to refer to this discussion

**Comment by codefromthecrypt** [comment]
I opened https://github.com/openzipkin/zipkin/issues/2721 for doing work to not depend on RejectedExecutionException as I think arguing about a wrapped message is not fruitful

**Comment by Logic-32** [comment]
> why do we back off when the busy queue is full, but not when the health check is red

The point of throttling is to slow your throughput in order to make sure we don't overwhelm storage.  If storage is dead, it doesn't matter how slow we go, it won't be able to store anything.  We also don't ever slow to 0 so messages will continue to drop while it is down.  I suppose you could argue that storage "could revive", in which case, the buffered items should be persisted.  But this is just my 2 cents. If it is decided that buffering while storage is dead is acceptable then I won't argue against it :)

**Comment by anuraaga** [comment]
I agree with you :) But have crossed the burnout line so prefer to make changes without thinking too much. If there's a better approach I'm happy to help review it.

**Comment by codefromthecrypt** [comment]
your comments make total sense, craig. I think you (luckily) missed some
context that there are sometimes where blips of unavailability occur and it
would seem the same for the reasons you earlier mentioned. If things are
super down, the bounding of the queue should sort it out (drop all).

Also, the context missed .. or maybe not missed heh.. is what Rag said, we
are super dead right now. Maybe this leads to nervousness to not drop on
blips found a day or two ago, or reduce the effort of hunting errors which
was super real this last week.  This context prioritizes these perhaps
artificially more than others.

Even more foreground is that the server hasn't released in ages (in zipkin
years), and also no one finished the exception handling from when this
feature started (ex no one looked at cassandra). So there's a pressure to
complete things also, and not letting best be enemy of good, especially
when probably no one will give feedback on the cassandra stuff.

Anyway sorry for curtness, but I agree with Rag on let's make room for
getting server releasable. Strong feeling will need BYO(change) because we
are dead tired.

**Comment by Logic-32** [comment]
No worries, thanks for the context!  I like the official support in StorageComponent for `isOverCapacity` now btw :)  Go get some rest if you can!

**Comment by codefromthecrypt** [comment]
thx on my way ;)
