### ISSUE TITLE
don't show minimap when trace fits on screen

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2716]
it is redundant to see minimap when you can already see whole trace.

ex.

![Screenshot 2019-07-31 at 11 57 37 AM](https://user-images.githubusercontent.com/64215/62183229-f55f4b80-b38b-11e9-9245-0575b7b82b06.png)

**Comment by jorgheymans** [comment]
we no longer have a minimap so this one can be closed @jcchavezs

**Comment by jcchavezs** [comment]
Thanks!

**Comment by shakuzen** [comment]
Could we link the issue that removed the minimap just to make it easier to follow the trail?

**Comment by jorgheymans** [comment]
Makes sense, i think it was contained in one of @tacigar big UI revamp issues but can't seem to find it.
