### ISSUE TITLE
Implement client-side check for multiple elasticsearch servers

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2720]
This is a backported rationale which may affect the design already in master. TL;DR; is we should tread carefully when adding health checks so that we don't shoot ourselves in the foot or end up with emergency bug fixes to turn them off.

# Background

We raised a #1611 a while back for the ability to handle multiple TLS endpoints for elasticsearch in at least the same way we do for non TLS (connection based round-robin)
https://github.com/square/okhttp/issues/4530

Now that we are using Armeria, we have multiple options for health checking and should be very careful about what mechanisms we use and that it can be turned off.

## On what mechanism to use?
If we do health checking at all, minimally we could use TCP/TLS connection level. This is cheap and unaffected by what Elasticsearch may return in an http request. It might be advantageous to use this verses ES health endpoint because of a few factors:

### Reasons to use http level checks
  * ES may have a status where a node is technically available, but out of service

### Reasons to not use http level checks
  * People upgrading may not be prepared to add the additional load or latency implied by ES http-level health check
  * ES itself has been known to have unpredictable behavior at times, hanging or otherwise having load problems. Adding an http layer check can add risk.
  * ES themselves do not do any active checking using their own apis https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/RestClient.java#L178-L194
  * Flurry of requests can hide real problems when debugging ( ex literally debugging, wireshark or `--logging.level.com.linecorp.armeria.logging.traffic.client=trace`)

## Health checks should be disablable
As the code we are using in armeria is new, that we don't have experience in how this will affect the cluster itself, and also that debugging is much harder with another system involved, we should allow disabling health checks. For example, setting zipkin.storage.elasticsearch.health-check.enabled=false

**Comment by anuraaga** [comment]
I think we should have flags to disable health check and configure the check interval (default is 3s). We'll export the health check status to micrometer. 

Okhttp is cool in falling back to the next IP in a DNS response if connect fails but Armeria currently doesn't. We're currently working on a big redesign to combine endpoint selection and connection acquisition at which point I think that becomes somewhat simple to implement but it will take some time.

So there isn't really any option not to issue http requests from an armeria endpoint group for now, and the above flags should keep it manageable I think.

**Comment by codefromthecrypt** [comment]
sounds good 3s default to kill switch works for me.
