### ISSUE TITLE
web query error

### ISSUE THREAD

**Issue by shijinkui** [openzipkin/zipkin#273]
http://127.0.0.1:8080/

help me 

```
com.twitter.finagle.FailedFastException


com.twitter.zipkin.gen.QueryException$Immutable$.decode(QueryException.scala:67)
com.twitter.zipkin.gen.QueryException$.decode(QueryException.scala:25)
com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$Immutable$.decode(ZipkinQuery.scala:3486)
com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$.decode(ZipkinQuery.scala:3432)
com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$.decode(ZipkinQuery.scala:3420)
com.twitter.zipkin.gen.ZipkinQuery$FinagledClient.decodeResponse(ZipkinQuery.scala:5512)
com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getServiceNames$1.apply(ZipkinQuery.scala:5832)
com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getServiceNames$1.apply(ZipkinQuery.scala:5831)
com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:607)
com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:606)
com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:67)
com.twitter.util.Promise$Transformer.k(Promise.scala:67)
com.twitter.util.Promise$Transformer.apply(Promise.scala:76)
com.twitter.util.Promise$Transformer.apply(Promise.scala:58)
com.twitter.util.Promise$$anon$1.run(Promise.scala:271)
com.twitter.concurrent.Scheduler$LocalScheduler.run(Scheduler.scala:60)
com.twitter.concurrent.Scheduler$LocalScheduler.submit(Scheduler.scala:40)
com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:26)
com.twitter.util.Promise.runq(Promise.scala:248)
com.twitter.util.Promise.updateIfEmpty(Promise.scala:502)
com.twitter.util.Promise.update(Promise.scala:475)
com.twitter.util.Promise.setValue(Promise.scala:458)
com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:71)
com.twitter.finagle.transport.ClientChannelTransport.handleUpstream(ChannelTransport.scala:127)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:458)
org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:439)
org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
com.twitter.finagle.thrift.ThriftFrameCodec.handleUpstream(ThriftFrameCodec.scala:17)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
com.twitter.finagle.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:74)
org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
com.twitter.finagle.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:35)
org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:553)
org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:84)
org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
java.lang.Thread.run(Thread.java:662)
```

**Comment by jaredlwong** [comment]
I don't know Zipkin in depth, but it seems as if you might not have the
database set up. Or, you are somehow putting bad data into your database.

Can you ensure that everything is running? The collector, querier and web
applications. As well as your database, usually either cassandra or redis.

Additionally, are you using the collector to store data into the database?
Or rather, how are you storing data into your database?

Best,
Jared

On Wed, Jul 10, 2013 at 3:28 AM, 时金魁 notifications@github.com wrote:

> http://127.0.0.1:8080/
> 
> help me
> 
> com.twitter.finagle.FailedFastException
> 
> com.twitter.zipkin.gen.QueryException$Immutable$.decode(QueryException.scala:67)
> com.twitter.zipkin.gen.QueryException$.decode(QueryException.scala:25)
> com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$Immutable$.decode(ZipkinQuery.scala:3486)
> com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$.decode(ZipkinQuery.scala:3432)
> com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$.decode(ZipkinQuery.scala:3420)
> com.twitter.zipkin.gen.ZipkinQuery$FinagledClient.decodeResponse(ZipkinQuery.scala:5512)
> com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getServiceNames$1.apply(ZipkinQuery.scala:5832)
> com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getServiceNames$1.apply(ZipkinQuery.scala:5831)
> com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:607)
> com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:606)
> com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:67)
> com.twitter.util.Promise$Transformer.k(Promise.scala:67)
> com.twitter.util.Promise$Transformer.apply(Promise.scala:76)
> com.twitter.util.Promise$Transformer.apply(Promise.scala:58)
> com.twitter.util.Promise$$anon$1.run(Promise.scala:271)
> com.twitter.concurrent.Scheduler$LocalScheduler.run(Scheduler.scala:60)
> com.twitter.concurrent.Scheduler$LocalScheduler.submit(Scheduler.scala:40)
> com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:26)
> com.twitter.util.Promise.runq(Promise.scala:248)
> com.twitter.util.Promise.updateIfEmpty(Promise.scala:502)
> com.twitter.util.Promise.update(Promise.scala:475)
> com.twitter.util.Promise.setValue(Promise.scala:458)
> com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:71)
> com.twitter.finagle.transport.ClientChannelTransport.handleUpstream(ChannelTransport.scala:127)
> org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
> org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
> org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
> org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
> org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
> org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
> org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
> org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:458)
> org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:439)
> org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
> org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
> com.twitter.finagle.thrift.ThriftFrameCodec.handleUpstream(ThriftFrameCodec.scala:17)
> org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
> org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
> org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
> com.twitter.finagle.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:74)
> org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
> org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
> org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
> org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
> com.twitter.finagle.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:35)
> org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
> org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
> org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:553)
> org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
> org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
> org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:84)
> org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:471)
> org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:332)
> org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
> org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:102)
> org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
> java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
> java.lang.Thread.run(Thread.java:662)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/twitter/zipkin/issues/273
> .

## 

Jared Wong :: jwong@pinterest.com
