### ISSUE TITLE
re-logo the things

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2737]
for @syleeeee 

we need to update
./zipkin-lens/src/img/zipkin-sm-logo.svg
./zipkin-lens/src/img/zipkin-logo.svg

Also the banner, which was originally made by @making in #1612
./zipkin-server/src/main/resources/banner.txt

you can verify afterwards by starting the server using the instructions here:
https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#building-locally

maybe during this or after, the color scheme should change for lens. cc @openzipkin/ui

**Comment by making** [comment]
I'll contribute banner.txt ;)

**Comment by jorgheymans** [comment]
Things were re-logo'd, thanks !

**Comment by jcchavezs** [comment]
Did we relogoed for attic and contrib too?

**Comment by codefromthecrypt** [comment]
Did we relogoed for attic and contrib too?
>
we could use the old logo for attic, for the sake of irony :)

**Comment by jorgheymans** [comment]
Attic still has the old logo +1 to keep it, i wanted to re-logo contrib but i think it requires more rights than I currently have. After that we can close this issue.

**Comment by codefromthecrypt** [comment]
heh.. try now?

**Comment by jorgheymans** [comment]
Yep, new logo applied to contrib thanks,

**Comment by making** [comment]
https://twitter.com/zipkinproject is still using old one 🤔

**Comment by codefromthecrypt** [comment]
unfortunately we have no access to the twitter account to change that, and
have failed for years getting someone to help us do that. I'll try again..
