### ISSUE TITLE
zipkin-server 2.15.0 新UI界面的Bug

### ISSUE THREAD

**Issue by ltlwill** [openzipkin/zipkin#2739]
zipkin server 2.15.0的新UI界面有个bug，第一次搜索时会在 url上加endTs参数(如：endTs=1565158903330)，再次点击搜索时，这个 endTs参数并不会变化，导致以后每次点击搜索按钮时，查不出新的数据，必须手动在URL上去掉endTs参数，才能查询出新数据
![{3F498914-51D3-4862-88C1-B53696B82798}_20190807142802](https://user-images.githubusercontent.com/16695334/62599717-88b1f700-b91f-11e9-8e86-9a3c41701cc5.jpg)

**Comment by shakuzen** [comment]
Via Google translate:

> The new UI interface of zipkin server 2.15.0 has a bug. When searching for the first time, the endTs parameter will be added to the url (for example: endTs=1565158903330). When you click search again, the endTs parameter will not change, resulting in each subsequent When the search button is clicked, no new data can be found. The endTs parameter must be manually removed from the URL to query the new data.

I thought there was a GitHub issue regarding this already, but I couldn't find it.

**Comment by codefromthecrypt** [comment]
yes this is fixed, but I think it was released after 2.15..

can you try snapshot?

**Comment by ltlwill** [comment]
thank you !
I will use the old version first.

**Comment by codefromthecrypt** [comment]
can you try 2.16.0 please? we will re-open if still problem

**Comment by ltlwill** [comment]
> can you try 2.16.0 please? we will re-open if still problem

This problem is no longer in version 2.16.0.   Thanks!
