### ISSUE TITLE
consider if JDK 9+ --release flag obviates animal sniffer

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2752]
from @shakuzen 

> Also, I know we use animalsniffer, but upgrading to JDK9+ presents the opportunity to use the new release compiler arg instead, where the compiler can enforce that Java API is not used beyond the specified version. This doesn't need to happen in this pull request, though.
ref: http://openjdk.java.net/jeps/247

Someone can try this and see if it works, or if it requires some hard to setup things like libraries containing 1.6 apis and things.

**Comment by jorgheymans** [comment]
I don't think this can work in our situation. 

The release compiler argument is specified like this:
```
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
          <inherited>true</inherited>
          <configuration>
            <fork>true</fork>
            <showWarnings>true</showWarnings>
            <release>6</release>
          </configuration>
        </plugin>
```
It will refuse to compile sources that are not compliant to jdk1.6.

What we actually currently do is specify compiler target 1.8 and then retrofit it down to 1.6. 

So if we specify <release>6</release> our sources will not compile, but if we specify <release>8</release> to make it compile we're not actually validating anymore that the result is still jdk6 compatible.

See https://github.com/jorgheymans/zipkin/tree/javac--release-compiler-arg for an attempt at this.

**Comment by shakuzen** [comment]
> What we actually currently do is specify compiler target 1.8 and then retrofit it down to 1.6.

Thank you for trying this out. I must have forgot that we do some retro conversions of things like lambdas.

**Comment by jorgheymans** [comment]
Tried, but no.
