### ISSUE TITLE
log related regression

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2756]
In Zipkin 2.15, when there were http timeouts, we didn't flood the console with warning messages. We incremented metrics instead. Now, for every request attempt that times out, we get a warn line. We don't get log lines for any other type of failure unless you set ES_HTTP_LOGGING.

I'd like someone who uses elasticsearch in production to comment if this is ok.

cc @huydx @jcarres-mdsol @jcchavezs @jonathan-lo (I think you use ES in production)
cc @anuraaga @trustin (about the error handling)

Example warn logs
```
zipkin                      | 2019-08-17 12:16:38.308  WARN 1 --- [orker-epoll-2-4] c.l.a.c.HttpResponseDecoder              : Unexpected exception:
zipkin                      | 
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
zipkin                      | 
zipkin                      | 2019-08-17 12:16:40.251  WARN 1 --- [orker-epoll-2-6] c.l.a.c.HttpResponseDecoder              : Unexpected exception:
zipkin                      | 
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
zipkin                      | 
zipkin                      | 2019-08-17 12:16:41.656  WARN 1 --- [orker-epoll-2-7] c.l.a.c.HttpResponseDecoder              : Unexpected exception:
zipkin                      | 
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
zipkin                      | 
zipkin                      | 2019-08-17 12:16:42.561  WARN 1 --- [orker-epoll-2-8] c.l.a.c.HttpResponseDecoder              : Unexpected exception:
zipkin                      | 
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
zipkin                      | 
zipkin                      | 2019-08-17 12:16:45.190  WARN 1 --- [orker-epoll-2-1] c.l.a.c.HttpResponseDecoder              : Unexpected exception:
zipkin                      | 
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
zipkin                      | 
zipkin                      | 2019-08-17 12:16:48.888  WARN 1 --- [orker-epoll-2-3] c.l.a.c.HttpResponseDecoder              : Unexpected exception:
zipkin                      | 
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
zipkin                      | 
zipkin                      | 2019-08-17 12:16:48.892  WARN 1 --- [orker-epoll-2-2] c.l.a.c.HttpResponseDecoder              : Unexpected exception:
zipkin                      | 
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
zipkin                      | 
```

**Comment by codefromthecrypt** [comment]
FWIW the way the old okhttp logger worked was that in the logger it would show if there was a timeout.

ex. like this:
```
zipkin                      | 2019-08-17 12:36:26.032  INFO 1 --- [search:9200/...] z.e.ElasticsearchStorage                 : --> POST http://elasticsearch:9200/_bulk http/1.1 (-1-byte body)
zipkin                      | 2019-08-17 12:36:27.622  INFO 1 --- [search:9200/...] z.e.ElasticsearchStorage                 : <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
```

what was nice about this is that you have context. also, you can use the same logging category for any kind of http failure, regardless of if that was status or timeout.

**Comment by codefromthecrypt** [comment]
Now, what happens is we have (with the same config) a summary message plus also the WARN. The thing to pay attention to when deciding if this is ok or not is that this is request-scoped and WARN level will always be in console unless we turn it off. In an overload situation you can be filling up logs. however, if they aren't stored anywhere, like shipped to elasticsearch, getting a WARN line every few milliseconds may not be a problem.

Here's the current log with BASIC on.
```
zipkin                      | 2019-08-17 12:39:20.000  INFO 1 --- [orker-epoll-2-4] c.l.a.c.l.LoggingClient                  : Request: {startTime=2019-08-17T12:39:19.994Z(1566045559994257), length=4970KiB(5089733B), duration=6198?s(6198300ns), scheme=none+h1c, headers=[]}
zipkin                      | 2019-08-17 12:39:20.117  WARN 1 --- [orker-epoll-2-4] c.l.a.c.l.LoggingClient                  : Response: {startTime=2019-08-17T12:39:20.117Z(1566045560117742), length=0B, duration=0ns, cause=com.linecorp.armeria.client.ResponseTimeoutException, headers=[]}
zipkin                      | 
zipkin                      | com.linecorp.armeria.client.ResponseTimeoutException: null
```

You'll notice that while the info has enough data to describe what the timeout is about the WARN one does not. it just says a timeout occurred. We can guess that it was ES falling over though.

**Comment by anuraaga** [comment]
Filed https://github.com/line/armeria/issues/2000 since I think it's just a bug

**Comment by codefromthecrypt** [comment]
we can also consider putting tracing alway-on, but in no-op mode so at least we get trace/span IDs in logs. Not sure it will cover this exception, but it might help validate if timeouts are working properly, or firing too soon, or something else. right now, obviously we cannot correlate

**Comment by anuraaga** [comment]
Also filed https://github.com/line/armeria/issues/2001 I think it's better if armeria generated a request ID for logs to not have to tweak trace sampling just to associate logs.
