### ISSUE TITLE
design idea: blocking http proxy until resources initialized

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2758]
We intentionally make the storage component internals lazy, which implies first requests block before service. This addresses things like subtle race conditions when zipkin and a dependency start at the same time. For those who remember, we crashed back when it was finagle, and this caused a mess of questions. Users do not like having to orchestrate things to deal with a second delay.

Yet, there are some resources that have a delay, like looking up DNS for elasticsearch domains and waiting for the health check to come back. We also have intentional delay, like a guard on ES templates being there because it is even worse chaos if we let requests pass without setting the template.

Meanwhile, I think armeria/netty could possibly handle some things better if things were not lazy. While it is risk to do things on event loop, as you can smash the entire server (See #2697), it does offer choices.

I was thinking (in the shower).. what if we can have both words? Could we startup with a throwaway blocking router, which then unhooks itself once storage is initialized? This might dramatically simplify thread pools etc.. in theory anyway..

cc also @kojilin in case you do things like this in normal services :P

**Comment by anuraaga** [comment]
I think the code version is something like

```java
if (initialized)
  run();
else
  blockingExecutor.execute(() -> {
    run();
    initialized = true
}
```

I would be worried though if at some point that initialized does not reflect reality and something later blocks. If the server codebase enforced a practice of

1) Blocking I/O methods do not take callbacks
2) Callbacks passed to methods do not do blocking I/O

then it would be safe but without that, it would be quite realistic to accidentally add back a block. Don't think it's worth trying that until a potential zipkin 3 - we discussed a major version would probably be needed to codify blocking guidelines on APIs.

Even better would be to not ever do blocking I/O - not blocking does not imply not ordering. Composition of CompletableFuture can ensure ordering, caching of futures can ensure synchronization. But it makes the codebase much more complex so it might be too much of a shift.

Just a memo of my thoughts

**Comment by codefromthecrypt** [comment]
interesting.. I was thinking about really like a proxy an in-memory proxy/barrier which intercepts the http traffic, but blocks callers on a configuration gate. somehow, this proxy/interceptor is removed. he other code actually stays the same except it could rely on no ordering or initialization proxy.

It seems a lot simpler without a rewrite which I don't think anyone has time for right now. It would be very easy to get the blocking ordering part (which does the most suprising I/O) off the main line.

This doesn't mean the ideas you have for zipkin 3 aren't cool, I like them, just I was wondering about a tactical change as I don't think at the moment we'd require having time resources and desire to do a full rewrite for an optimization like this. I think we can make a Zipkin 3 wishlist with what you've mentioned regardless. I think in Brave for example, we have // BRAVE 6 notes scattered around in relevant places which identify trouble spots.

**Comment by codefromthecrypt** [comment]
@anuraaga Just opened a zipkin3 also and assigned you as the lead but this is not implying sending you to coal mine :) just to what degree you are interested and have time on more strategic things, please note or progress what you can https://github.com/openzipkin/zipkin/issues/2759

We put a lot of time into refactoring the server and deserve to benefit from that. For example we've had significant work done since march and this has impacted users not always in good ways. We have a brand of being the stable option and we should live up to that.

I think you get it, I'm just trying to find a way of being objective about duty and how we could. Ex. we have been in process of armeria transition on and off the last 5 months. We deserve a break at some point, and users do too. Having 3 if not 6 months of stability before the next huge refactor seems reasonable. Since we're not out of the woods, yet, on this one.. I was looking for tactical ways to get things stable, but understand this idea could be misplaced. take it as a grain of salt if it isn't helpful.

**Comment by anuraaga** [comment]
Yeah I agree we shouldn't do any big rework any time soon, just ideas for how to get to safe async. I think for now, we're already where we need to be - running calls on the blocking executor since our logic we can never assume to be fully async. Without assurances on the blocking properties of business logic, I think we would always be nervous about accidentally blocking an event loop but now it's basically not possible (well, that does assume we don't add a redis layer or something to our span decoders, currently the only significant business logic run on the event loop ;) )

The performance impact of the switch is marginal, I'd guess at max a couple ms in a very worst case - for the other issue I didn't see any visible impact from removing it unlike the weirdness of handleAsync. Hopefully we can look at getting that back, in a couple of years or something :)

**Comment by codefromthecrypt** [comment]
works for me, @anuraaga, let's reserve effort towards other things in the air and eventually a zipkin3!
