### ISSUE TITLE
Add `zipkin.collector.abc.enabled` conditional property to enable collectors

### ISSUE THREAD

**Issue by jeqo** [openzipkin/zipkin#2762]
**Feature:**

Add conditional property to enable collectors, similar to Scribe, HTTP or Grpc

**Rational**

Currently, most messaging collectors are enabled based on env. variables defined (e.g. Kafka collector enabled when KAFKA_BOOTSTRAP_SERVERS is defined).
 

**Example Scenario**

While developing a [Kafka-based storage](https://github.com/jeqo/zipkin-storage-kafka) I would like to reuse variable names (KAFKA_xxx) without forcing users to enable Kafka Collector. 
Is not probable for this to happen when RabbitMQ or ActiveMQ are used as collector, but might be good to standardize the same property to enable collectors, as we do with `zipkin.storage.type`. 

**Prior Art**
 
* HTTP: <https://github.com/openzipkin/zipkin/blob/b84bb3261d8402507a2d54f3b55e017484c50a85/zipkin-server/src/main/java/zipkin2/server/internal/ZipkinHttpCollector.java#L59>
* Scribe: <https://github.com/openzipkin/zipkin/blob/b84bb3261d8402507a2d54f3b55e017484c50a85/zipkin-server/src/main/java/zipkin2/server/internal/scribe/ZipkinScribeCollectorConfiguration.java#L31>

**Comment by codefromthecrypt** [comment]
makes sense
