### ISSUE TITLE
Option to index hourly in to Elasticsearch

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#2767]
In order to reduce search scope for smaller time ranges and increase query performance, having an option to index hourly will be helpful.

The zipkin-server `annotation query` is converted to a ES aggregation query to list trace ids and then the spans are fetched. Recently with our scale, I noticed the queries timeout and having hourly indices might speed things up.

It's a quick win to gain some performance this way.

**Comment by codefromthecrypt** [comment]
folding this into #2369 thanks
