### ISSUE TITLE
When gateway kind is CLIENT, http.path: is "/", Why is that?

### ISSUE THREAD

**Issue by songwenh** [openzipkin/zipkin#2768]
This is the version I am currently using.
Spring Cloud Greenwich SR2
Spring Cloud Gateway 2.1.2
Spring boot2.1.6
Spring Cloud Zipkin 2.1.2

Show-how
Spring Cloud Gateway Configuration 
![image](https://user-images.githubusercontent.com/31386856/63406676-2f68be00-c41d-11e9-86ee-f1c2479cebf9.png)

Request url
![image](https://user-images.githubusercontent.com/31386856/63406770-69d25b00-c41d-11e9-939f-bb1046b0f685.png)

zipkin ui
![image](https://user-images.githubusercontent.com/31386856/63406786-72c32c80-c41d-11e9-83cb-808493200e20.png)
![image](https://user-images.githubusercontent.com/31386856/63406793-75be1d00-c41d-11e9-9141-9cacadc4a0df.png)

[
  {
    "traceId": "f86c4c36d0718024",
    "parentId": "f86c4c36d0718024",
    "id": "3d95b7b0c8fdde88",
    "kind": "SERVER",
    "name": "get /demo1/test/auto/refresh/names",
    "timestamp": 1566366796911115,
    "duration": 2681,
    "localEndpoint": {
      "serviceName": "msa-demo1",
      "ipv4": "172.17.101.50"
    },
    "remoteEndpoint": {
      "ipv4": "172.17.101.50"
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/demo1/test/auto/refresh/names",
      "mvc.controller.class": "AutoRefreshController",
      "mvc.controller.method": "autoRefreshNames"
    },
    "shared": true
  },
  {
    "traceId": "f86c4c36d0718024",
    "parentId": "f86c4c36d0718024",
    "id": "3d95b7b0c8fdde88",
    "kind": "CLIENT",
    "name": "get",
    "timestamp": 1566366796904700,
    "duration": 9697,
    "localEndpoint": {
      "serviceName": "msa-gateway",
      "ipv4": "172.17.101.50"
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/demo1/test/auto/refresh/names"
    }
  },
  {
    "traceId": "f86c4c36d0718024",
    "id": "f86c4c36d0718024",
    "kind": "CLIENT",
    "name": "get",
    "timestamp": 1566366796908788,
    "duration": 7110,
    "localEndpoint": {
      "serviceName": "msa-gateway",
      "ipv4": "172.17.101.50"
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/"
    }
  }
]

traceId,parentId is the same.very strange.

End

I hope to answer my questions. Thank you.

**Comment by codefromthecrypt** [comment]
Hi, can you either as on sleuth's gitter or open an issue against sleuth please? This repo is for the zipkin server code https://gitter.im/spring-cloud/spring-cloud-sleuth
