### ISSUE TITLE
Cassandra schema create keyspace only if not exist

### ISSUE THREAD

**Issue by xbeta** [openzipkin/zipkin#277]
I believe it's a Cassandra issue, but can we quickly add a check when we create schema on Cassandra as a workaround for this?

I'm currently in process of writing a cookbook for Zipkin, and it will throw an error if the keyspace is already existed (which happens when it gets re-deploy again).

**Comment by bmdhacks** [comment]
Thanks for the recommendation.  We don't have a ton of manpower to satisfy external requests like this, but I'd love to work with you through the process of submitting a pull request to fix the things you see that are broken.
