### ISSUE TITLE
Is 1 hour the best search default? What if it were 5, 15, or 30m?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2772]
Right now, certain storage backends are impacted by the default search terms more than others. For example, there's often concerns about sorting within the interval which can cause some queries to take longer than others, even if only 10 results come back.

<img width="1024" alt="Screenshot 2019-08-22 at 8 24 28 AM" src="https://user-images.githubusercontent.com/64215/63477505-fa5d7980-c4b7-11e9-8e5e-826cb30ad699.png">

Currently, our default lookback is 1hr. Possibly we discussed this before, but what if it were less? For example, in grafana there are built-in units of 5, 15 and 30minutes.

Remember this is how long ago to look for the start of a trace. usually it results in a follow-up requests to collect the traces by ID.

cc @openzipkin/core

**Comment by codefromthecrypt** [comment]
btw I think I maybe was the one that set the lookback to 1hr. Before deb408fb773310d4c467ee45f444f7a991f0273e, it was *7 days* which wreaked havoc on cassandra by default.

Strawman proposal is 15minutes, which is long enough to deal with any clock skew and longer than most traces would be. Whatever our default lookback is, it should be as long or longer than the time units folks use for windowing typical traces, imho.

**Comment by codefromthecrypt** [comment]
by the way, anyone can change this value now. This is more about what the default is, because it can help optimize storage concerns.

https://github.com/openzipkin/zipkin/tree/master/zipkin-server#configuration-for-the-ui

**Comment by jcchavezs** [comment]
Very specific use case from my side:

I usually use tracing as try-error for debugging so the default use case I
see in medium scale company is that one wants usually to see latest traces
(5-10 minutes ago). I would say 15 minutes was enough every time I used
zipkin so I would vote for that.

Notice kibana offers times like: 15m, 30m, 1h, 4h but again I never use
more than 15 minutes unless I want to do a very specific search.

tor. 22. aug. 2019, 02:45 skrev Adrian Cole <notifications@github.com>:

**Comment by jcarres-mdsol** [comment]
15min is good for us also. We do 100% sampling so we are bound to already find interesting stuff within 15min

**Comment by codefromthecrypt** [comment]
ok from feedback I think sensible to default to 15m and provide a built-in label for 5 (there are no ones before 1 hour right now)

**Comment by shakuzen** [comment]
Resolved by #2773 I believe
