### ISSUE TITLE
defer processing of traces in list view

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2785]
@driesdeproost  noticed that if you have retrieved 1000 traces (possibly even hundreds), where a trace has a few hundred spans, the list view renders slowly vs before. This is almost certainly due to pre-emptive construction of trace tree. I think we can defer this and make performance pop even better than before lens.

**Comment by codefromthecrypt** [comment]
This might imply some work like partial summary which doesn't need to render the trace into a tree to do.

**Comment by codefromthecrypt** [comment]
I also think jason from haystack noticed this before, we just didn't make an issue at that point. Right now, I think this is important as we want people to not want to revert from lens :)

**Comment by jorgheymans** [comment]
@driesdeproost are you in a position to test this again ? Many improvements have been made on the list view since then. I have tested it for my site and had several hundreds of traces in the overview of which many had several thousands of spans.

**Comment by driesdeproost** [comment]
@jorgheymans 

Not right now, I think I mentioned this once on gitter and I don't really remember where we encountered this.

**Comment by jorgheymans** [comment]
Alright thanks, closing this one then. If you find later you still have specific performance issues with the latest released version feel free to create a new issue.
