### ISSUE TITLE
Directly support endpoints we use in support vs implicit redirects to Spring Boot Actuator

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2788]
In former versions we mounted /health and /prometheus at root. I think starting with spring boot 2 or armeria, I forget which, we redirected instead of forwarding (dual-mounting) these paths.

I think this dependency is unnecessary and requires us to use one of the heftiest parts of spring boot for routine work (actuator) actuator has a lot of slow paths and is itself bulky and ultimately built on servlet layers. If instead we mount the required urls /prometheus /info and /health directly, we have flexibility in terms of certain dependencies and to increase our startup time as well memory usage.

So, I prefer we directly mount the following

* /health
* /info
* /prometheus

cc @openzipkin/core

**Comment by codefromthecrypt** [comment]
the other thing to consider is that our http runtime doesn't support all the things actuator expects anyway (ex spring-security), by directly mounting these, we have a much more honest relationship, too. Finally anyone wanting to clone the server can just implement these and env variables  vs trying to re-implement all of spring boot. Even if we eventually unhook actuator, we can always add an optional module to add it back for sites who really want it.

**Comment by codefromthecrypt** [comment]
here's some examples of investigations opting out of actuator

https://github.com/dsyer/spring-boot-memory-blog#summary-of-data
https://github.com/dsyer/spring-boot-startup-bench#actuator

**Comment by shakuzen** [comment]
I'm not sure I'm understanding the problem or proposed solution. We explicitly enable all Actuator endpoints because this was the behavior with Spring Boot 1 and we thought some users would expect these endpoints or find them helpful (even if their path changed). I know we have used the env/configprops endpoints for troubleshooting user-reported issues in the past, at least.

https://github.com/openzipkin/zipkin/blob/9885c8cc6ec302f7689047d17833d7c362f6dbd8/zipkin-server/src/main/resources/zipkin-server-shared.yml#L237-L241

We can limit that to a subset of endpoints if we don't want other endpoints because of some perceived cost.

Actuator does not require Spring Security - it's an optional dependency if you want to add security features it provides.

Is the proposal that we reimplement any endpoints we care about ourselves instead of use the Actuator-provided endpoints? Is the startup and memory increase caused by Actuator that bad for us? As a datapoint, Zipkin Server 2.16.2 starts up in under 3 seconds on my laptop. And from Dave's summary of memory linked, we'd expect to save 1 MB of heap and 4 MB of non-heap assuming our replacement implementation costs virtually nothing.

**Comment by codefromthecrypt** [comment]
The intent here is to stop requiring dragging in the earth especially as integrated features.. people don't understand that spring security isn't there. We can make actuator opt-in, it was almost by accident that when everything broke moving to boot 2, that we migrated under that path via redirects.

**Comment by codefromthecrypt** [comment]
literally yesterday someone backchanneled me about 30 second startup eventually resolved when they rebooted, then down to a few seconds.

Then we also had kafka having to rework to avoid compressed jars due to boot loading. When you remove actuator as a strict requirement (even if you leave it available), folks have a lot of flexibility.

This is not a general purpose app, it is a telemetry tool, we do most of the work custom and it seems suspect to be required to forever hold actuator which changes on spring boot releases outside our control, and also adds overhead.

**Comment by shakuzen** [comment]
After chatting offline with Adrian about this, my conclusion (which may be different from his :P) is to say: I am in agreement with making Actuator optional and making our core endpoints mentioned not redirects/forwards. I do think having the option of enabling Actuator will be useful for users who do use Actuator endpoints besides our core ones.

**Comment by codefromthecrypt** [comment]
Capturing research as working on other things..

* directly implement the json for /health like we do for /metrics and overwrite /actuator/health in case people saved redirect results
* directly implement /info and redirect /actuator/info to it
* mount directly /prometheus and /actuator/prometheus in case people saved redirect results

Most of the above doesn't change our README, but worth a scrub.

Then there are two code-level exposures to actuator classes:
* ArmeriaSpringActuatorAutoConfiguration - we directly use this, but it is supposed to be auto-loaded via meta-inf. maybe it is an ordering concern
* MeterRegistryCustomizer - this is in the actuator package.. we currently implement this, which pins us to the actuator class hierarchy. Another option @anuraaga suggests is to use `Consumer` instead for customizing until this is unwound upstream (likely not until boot 3). Then similar to others retrofit.

**Comment by codefromthecrypt** [comment]
Something similar came up today. I really do think we need to decouple things we rely on from actuator specifics. /info needn't be so strictly compliant with whatever versions and tooling dictate. we just want to check the version output.

https://gitter.im/openzipkin/zipkin?at=5d764520d5c7bd5794602d72

> Hello guys, first contribution here, sorry if it's not the right place. Is it known that Zipkin server returns an invalid content-type from http://localhost:9411/actuator ?
It returns "application/json" instead of "application/vnd.spring-boot.actuator.v2+json"
Actual actuator endpoints such as "actuator/info" return a correct content-type
As a consequence Zipkin server is not correctly displayed by Spring Boot Admin

**Comment by codefromthecrypt** [comment]
Since we have some new features that warrant a new minor bump, I'd offer to write /info and /health directly (regardless of /actuator) prior to next release if no one else does first.

**Comment by codefromthecrypt** [comment]
This fixes the issue, though actuator is still bundled by default https://github.com/openzipkin/zipkin/pull/2815
