### ISSUE TITLE
document annotation query in the UI

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#2795]
zipkin classic UI has an example annotation query in the text field, making it very intuitive for people to start using it based on the example syntax. Can we somehow put this in Lens as well, maybe in the same way or a `?` tooltip perhaps ?

**Comment by shakuzen** [comment]
There's a general tooltips issue: https://github.com/openzipkin/zipkin/issues/2488
It's probably fine to track this specific request separately, but it may be blocked on a general tooltip solution being introduced first (I'm not sure though).

**Comment by jorgheymans** [comment]
This will be fixed by https://github.com/openzipkin/zipkin/pull/3076 when it lands.
