### ISSUE TITLE
http collector logs not working at least Zipkin 2.16.2

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2797]
do this:

```bash
curl -sSL https://zipkin.io/quickstart.sh | bash -s
java -jar zipkin.jar --logging.level.zipkin2=DEBUG
```

then do this:

```bash
cd zipkin-lens/testdata
curl -X POST -s localhost:9411/api/v2/spans -H'Content-Type: application/json' -d @netflix.json -v
```

notice no logs in the console. `zipkin2.collector.Collector` should log eventhough it uses java logging as we had intended to setup the log manager in `zipkin.server.ZipkinServer`

Thanks @fbeaufume for reporting

**Comment by codefromthecrypt** [comment]
trying 2.15.0

```bash
curl -fL -o 'zipkin.jar' 'https://repo1.maven.org/maven2/io/zipkin/zipkin-server/2.15.0/zipkin-server-2.15.0-exec.jar'
```

**Comment by codefromthecrypt** [comment]
weird that shows nothing also..

**Comment by codefromthecrypt** [comment]
even 2.14.2... maybe I misunderstand the syntax? It looks correct (back to latest)

```bash
curl -s localhost:9411/actuator/loggers/zipkin2|jq .
{
  "configuredLevel": "TRACE",
  "effectiveLevel": "TRACE"
}
```

**Comment by codefromthecrypt** [comment]
whoops forgot. We don't log on success.

```
2019-09-11 19:06:15.158 DEBUG 61349 --- [cking-tasks-1-1] z.s.i.ZipkinHttpCollector                : Cannot store spans [5982fe77008310cc80f1da5e10147517/8f6bc3f30fa5b0bf, 5982fe77008310cc80f1da5e10147517/6c59056709a0b1e4, 5982fe77008310cc80f1da5e10147517/6c59056709a0b1e4, ...] due to RejectedExecutionException(Connection refused: localhost/127.0.0.1:9200)
```

If you want to see success, look at metrics or upvote https://github.com/openzipkin/zipkin/issues/2680

**Comment by fbeaufume** [comment]
@adriancole When using "java -jar zipkin-server-2.16.2-exec.jar --logging.level.zipkin2=TRACE", I get no log at all when the server receives traces or displays them in Lens.
Is this the expected behavior ?
Is there a way to get debugs and traces showing what Zipkin server is doing (to learn about Zipkin internals)?

**Comment by codefromthecrypt** [comment]
@fbeaufume best option is not use logs for this

set SELF_TRACING_ENABLED=true and then you get a trace for each interaction. use zipkin to learn zipkin!
