### ISSUE TITLE
Zipkin over RabbitMQ

### ISSUE THREAD

**Issue by vikash2u** [openzipkin/zipkin#2836]
I have implemented different microservice where internal communication is taking place by RabbitMQ with different exchange and queue 

Ex: Service1 Publish message to RabbitMQ ( i.e Exchange 1 -> Queue 1) where Service2 Consume message
Service2 Publish message to RabbitMQ ( i.e Exchange 2 -> Queue 2) where Service3 Consume message
Service3 Publish message to RabbitMQ ( i.e Exchange 3 -> Queue 3) where Service4 Consume message
Cont…
![image](https://user-images.githubusercontent.com/13733672/66349710-69503e00-e951-11e9-86f0-ebb01d399eb9.png)

I have configured sleuth and Zipkin where trace id is getting generated when sender type is defined as web but while message is passing to different Exchange , a unique traceId is getting generated.

Question: 
1. Is Zipkin support sender type is rabbitmq?
2. Is it possible to have a unique traceID for entire data traverse from Service 1 to Service N via RabbitMQ.

Thank you in advance.

**Comment by jeqo** [comment]
@vikash2u I would recommend to use [gitter](https://gitter.im/openzipkin/zipkin) to ask questions. We keep github for bugs and improvements.

To answer your questions: https://github.com/openzipkin/zipkin/tree/master/zipkin-collector/rabbitmq and https://github.com/openzipkin/brave/tree/master/instrumentation/spring-rabbit
