### ISSUE TITLE
Bug in AnormStorage where annotation durations get converted to strings instead of longs.

### ISSUE THREAD

**Issue by ivolyn** [openzipkin/zipkin#285]
On Wednesday, July 31, 2013 1:52:30 AM UTC+8, Isaac Sukin wrote:
Looks like there is in fact a bug in AnormStorage where annotation durations get converted to strings instead of longs. I'm surprised that made it past the tests (and manual testing) and I would have expected it to show up on storage rather than retrieval given that the durations column is declared as a BIGINT... in any case, the fix is to append .map(_.inNanoseconds) to a.duration on this line, and I'll try to get that into master ASAP.

Thanks for the report. In the future, we prefer that issues be reported in the Github issue tracker just to make them easier for everyone to find for posterity. :)

Cheers,
Isaac

On Mon, Jul 29, 2013 at 8:48 PM, Igor Volynskiy ivo...@gmail.com wrote:
For the past month or so I have been working on setting up a Zipkin solution at my company. I had a local Zipkin instance running for development. Yesterday I updated to the latest code on master. I started getting the exception below when searching for traces in Zipkin web using the new default configuration. When I run the collector and query service using the Cassandra config, everything works ok again.

This works fine:
bin/sbt 'project zipkin-collector-service' 'run -f zipkin-collector-service/config/collector-cassandra.scala'
bin/sbt 'project zipkin-query-service' 'run -f zipkin-query-service/config/query-cassandra.scala'

This results in an exception:
bin/collector
bin/query

[error] INF [20130730-11:43:20.453] finatra: GET /api/query?serviceName=NatpalLive&spanName=all&endDatetime=07-30-2013+11%3A43%3A16&limit=100
[error] DEB [20130730-11:43:20.454] web: QueryRequest(NatpalLive,None,None,None,1375155796000000,100,DurationDesc)
[error] ERR [20130730-11:43:20.728] finatra: Internal Server Error
[error] ERR [20130730-11:43:20.728] finatra: org.apache.thrift.TApplicationException: Internal error processing getTraceSummariesByIds: 'java.lang.RuntimeException: TypeDoesNotMatch(Cannot convert 2.milliseconds:class java.lang.String to Long for column ColumnName(zipkin_annotations.duration,Some(duration)))'
[error] ERR [20130730-11:43:20.728] finatra:     at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.zipkin.gen.ZipkinQuery$FinagledClient.decodeResponse(ZipkinQuery.scala:5504)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getTraceSummariesByIds$1.apply(ZipkinQuery.scala:5774)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.zipkin.gen.ZipkinQuery$FinagledClient$$anonfun$getTraceSummariesByIds$1.apply(ZipkinQuery.scala:5773)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:607)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:606)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:67)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise$Transformer.k(Promise.scala:67)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise$Transformer.apply(Promise.scala:76)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise$Transformer.apply(Promise.scala:58)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise$$anon$1.run(Promise.scala:271)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.concurrent.Scheduler$LocalScheduler.run(Scheduler.scala:60)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.concurrent.Scheduler$LocalScheduler.submit(Scheduler.scala:40)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:26)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise.runq(Promise.scala:248)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise.updateIfEmpty(Promise.scala:502)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise.update(Promise.scala:475)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.util.Promise.setValue(Promise.scala:458)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:71)
[error] ERR [20130730-11:43:20.728] finatra:     at com.twitter.finagle.transport.ClientChannelTransport.handleUpstream(ChannelTransport.scala:127)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:558)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:786)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:458)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:439)
[error] ERR [20130730-11:43:20.728] finatra:     at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
[error] ERR [20130730-11:43:20.728] finatra:     (...more...)

Igor

**Comment by IceCreamYou** [comment]
Committed [fix](https://github.com/twitter/zipkin/commit/6f7ffec57d03127cfcdb02e64e424563010543ba) to master :)
