### ISSUE TITLE
Zipkin UI LENS (NEW) download huge data from TAG

### ISSUE THREAD

**Issue by jhonatanforero** [openzipkin/zipkin#2855]
Hi,

The new zipkin UI Lens truncate the data tagged, we need all data from any tag to analyze incidents, I think is useful a button link as download (For tag) to get all data from tag or Modal window as old version

**Feature:**
Download truncate data from TAG or Modal Windows as old version

**Rational**
analyze incidents

**Example Scenario**

![Captura de pantalla 2019-10-17 a la(s) 4 57 55 p m](https://user-images.githubusercontent.com/5290238/67051613-2df80100-f101-11e9-8864-1e39d92b1ae8.png)

**Comment by codefromthecrypt** [comment]
sounds fine, but please also watch this issue because tagging request/response bodies is generally problematic for reasons like this and also it can clog up the data pipeline. There are other tools like Haystack Blobs which can eventually integrate in such a way that you see links not huge data cc @ mchandramouli  https://github.com/ExpediaDotCom/haystack-blob-example/issues/5

**Comment by codefromthecrypt** [comment]
@tacigar if you have time, could you try to accommodate tags that are huge (with scroll bar over some threshold). it will help folks transition off classic

**Comment by jorgheymans** [comment]
@jhonatanforero have you tried using more recent versions of Lens, I just tested this using 2.21.1 and tag data is not truncated:

![image](https://user-images.githubusercontent.com/193792/79697801-143c9f80-8285-11ea-87b3-8a08463d169f.png)

Trace with huge tag data here : [huge-tag.txt](https://github.com/openzipkin/zipkin/files/4500008/yep-huge-tag.txt)

I also tested using tag data 5 times bigger than the one posted above, the tag column scrolls along nicely. 

Also, for downloading the tag data you can download the complete json of the trace and extract it from there:

![image](https://user-images.githubusercontent.com/193792/79698220-cffece80-8287-11ea-9d73-5ff3e739354d.png)

**Comment by jorgheymans** [comment]
@jhonatanforero feel free to reopen if you find this issue crops up again.
