### ISSUE TITLE
Env variable to make lens the default UI

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2884]
Lens has been around for more than a year now and a lot of development has gone into it. Before removing the old UI we should make it possible to have lens as default ui (most people at my company have never clicked the try lens button afaik).

While we do this we should also add the button to go back to the default ui if people have any issue with lens though

**Comment by jorgheymans** [comment]
makes sense actually, next release set Lens as default but still offer to
navigate back for one more release or so. Then the release after that
remove old UI.

**Comment by drolando** [comment]
Just to clarify, I didn't seen any issue or chat in gitter about actually deleting the old UI soon. I just think this is a good next step.
Also afaik most people in my company have never clicked on the try lens button, so changing the default is an easy way to have them try it out.

**Comment by codefromthecrypt** [comment]
ps zipkin-slim has lens as default, but I think you use cassandra which is not in slim.

**Comment by codefromthecrypt** [comment]
IIRC the reason we didn't make an env variable was that we didn't want to create a variable then have to delete it later. As mentioned, the transition is at a year so far, so might be fair enough to add a variable. So, I would recommend a variable to set lens as default vs set classic or lens. This way, even if we delete it later due to lens being default, it isn't breaking.

**Comment by codefromthecrypt** [comment]
I raised this as take it or leave it. I'm not wandering down the path to make the cookies reversable as I think it is only checked for existence now. If it doesn't fit, someone else can do it (likely they won't), so I'd suggest just taking it :P https://github.com/openzipkin/zipkin/pull/2886
