### ISSUE TITLE
Add download/view json button in lens ui

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2885]
**Feature:**
The regular UI has a download/view JSON button which shows you the JSON representation of the current trace. Lens doesn't have such thing.

**Rational**
It's super useful when debugging UI issues and it's also one of the only ways to share traces in a ticket (unless you want to manually curl the /trace endpoint)

**Comment by lambcode** [comment]
+1 The "Upload JSON" button is less useful when there's no way to download the json.
