### ISSUE TITLE
Lens UI not showing service names after latest redesign

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2891]
After #2736 the lens UI doesn't show the service name for any of our traces. To reproduce, run lens locally and load `zipkin-lens/testdata/yelp.json`.

cc @tacigar

**Comment by tacigar** [comment]
Thank you for sharing trace data!
I'll investigate the causes.

**Comment by codefromthecrypt** [comment]
search screen from latest:

![Screenshot 2019-10-31 at 8 35 10 AM](https://user-images.githubusercontent.com/64215/67909205-5b40b680-fbb9-11e9-964c-732554f4d054.png)

trace detail from latest:

![Screenshot 2019-10-31 at 8 36 04 AM](https://user-images.githubusercontent.com/64215/67909237-76132b00-fbb9-11e9-9a8c-935c080531f1.png)

dependencies from latest:

![Screenshot 2019-10-31 at 8 36 59 AM](https://user-images.githubusercontent.com/64215/67909270-9347f980-fbb9-11e9-8994-bb6d22763c7f.png)

**Comment by codefromthecrypt** [comment]
the root span is incorrect as it has the shared flag set, but there's no corresponding client for it. I suspect that's an instrumentation bug an earlier version worked around. When you delete the shared flag, it looks fine.

I would have guessed span-cleaner would have cleaned this..

![Screenshot 2019-10-31 at 8 43 33 AM](https://user-images.githubusercontent.com/64215/67909546-94c5f180-fbba-11e9-87fc-596477afa5d4.png)
![Screenshot 2019-10-31 at 8 44 41 AM](https://user-images.githubusercontent.com/64215/67909577-a7402b00-fbba-11e9-9d3f-08674c3f812f.png)

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2900
