### ISSUE TITLE
zipkin-server- 2.19.1-exec  /zipkin/api/v2/services  503 Service Unavailable

### ISSUE THREAD

**Issue by brightvip** [openzipkin/zipkin#2898]
java -jar zipkin-server- 2.19.1-exec.jar \
--ZIPKIN_QUERY_ALLOWED_ORIGINS=* \
--logging.level.zipkin2=INFO \
--STORAGE_TYPE=elasticsearch \
--QUERY_PORT=9412            \
--QUERY_ENABLED=true         \
--SEARCH_ENABLED=true        \
--QUERY_LOG_LEVEL=INFO		\
--STORAGE_TYPE=elasticsearch  \
--ES_HOSTS=\
http://******:9200,\
http://*******:9200,\
http://*:9200,\
http://*:9200,\
http://*:9200,\
http://*:9200,\
http://*:9200,\
http://*:9200,\
http://*:9200,\
http://*:9200 \
--ES_TIMEOUT=600000  \
--ES_USERNAME=****\
--ES_PASSWORD=****\
--ES_HTTP_LOGGING=HEADERS

==========================================================
log
==========================================================
```
2019-10-30 15:17:12.638  INFO 26621 --- [orker-epoll-2-2] c.l.a.c.l.LoggingClient                  : Request: {startTime=2019-10-30T07:17:12.637Z(1572419832637000), length=283B, duration=208µs(208269ns), scheme=none+h1c, headers=[:method=POST, :path=/zipkin*span-2019-10-29,zipkin*span-2019-10-30/_search?allow_no_indices=true&expand_wildcards=open&ignore_unavailable=true, :authority=10.229.10.74:9200, :scheme=http, content-type=application/json; charset=utf-8, content-length=283, accept-encoding=gzip,deflate, authorization=Basic ****, user-agent=armeria/0.94.0]}
2019-10-30 15:17:24.566  INFO 26621 --- [orker-epoll-2-2] c.l.a.c.l.LoggingClient                  : Response: {startTime=2019-10-30T07:17:24.550Z(1572419844550000), length=732B, duration=16102µs(16102293ns), headers=[:status=200, content-type=application/json; charset=UTF-8, content-encoding=gzip, content-length=732]}

=====================================================
es 
zipkin*span-2019-10-29,zipkin*span-2019-10-30/_search?allow_no_indices=true&expand_wildcards=open&ignore_unavailable=true

total : 565003201
```

**Comment by jeqo** [comment]
@brightvip could you help us by adding more context to your issue? Is not clear to me what are we trying to solve here.

**Comment by brightvip** [comment]
@jeqo 

Hi jeqo
I am using zipkin-server- 2.19.1-exec now.
Data is stored in elasticsearch_6.8
Service name cannot be displayed
I checked the log and found that he needs
Elasticsearch_6.8 Data zipkin*span-2019-10-29,zipkin*span-2019-10-30
The total number of my data is: 565003201
I see the URL to get the service name: /zipkin/api/v2/services but return 503
And takes a long time

But in zipkin-server-2.12.2-exec.jar is normal
But it takes a long time

**Comment by anuraaga** [comment]
Thanks for the information @brightvip - I wonder if it's similar to #2809. Does the query fail after 11 seconds?

**Comment by brightvip** [comment]
@anuraaga 
Yes 
He will fail after a certain time and return to 503
Should be query timeout
Are you considering finding a more efficient way to query?

**Comment by brightvip** [comment]
I will wait first  #2809

**Comment by anuraaga** [comment]
Thanks for understanding - if possible, I was wondering whether the time to failure is almost exactly 11s, as opposed to for example 5s. If it's 11s, then indeed the fix to that issue will help you :)

**Comment by brightvip** [comment]
@anuraaga 
thank you very much

Browser display time consuming

![1](https://user-images.githubusercontent.com/5554201/68270514-6ce1fc80-0098-11ea-8688-1490186b384d.png)

**Comment by anuraaga** [comment]
Hi @brightvip - `QUERY_TIMEOUT` environment variable was added in 2.19.2. Can you see if setting it to `700s` (larger than your `ES_TIMEOUT`) fixes your issue?

**Comment by brightvip** [comment]
@anuraaga 
Thanks again
I have tested my running environment
The problem has been solved

ES_TIMEOUT is set to 60s
