### ISSUE TITLE
Support java.instrument module in docker base image

### ISSUE THREAD

**Issue by quangnguyen** [openzipkin/zipkin#2909]
**Feature:**
It's needed to be able to run zipkin in docker with java agent option **JAVA_OPTS=-javaagent:AgentImplementation.jar**

**Current State:**
If trying to do that with the docker image **openzipkin/zipkin:2.19.1**, the following exceptions will be thrown and the container was stopped.

`zipkin_1  \| Error occurred during initialization of VM`
 `zipkin_1  \| Could not find agent library instrument on the library path, with error: libinstrument.so: cannot open shared object file: No such file or directory`                     
`zipkin_1  \| Module java.instrument may be missing from runtime image.`
`dev_zipkin_1 exited with code 1`

**Example Scenario**
For example: ignoring host name verification with connection to TLS storage service through java agent with manipulation of method, that verify host name, at runtime.

**Prior Art**
Issue was already mentioned by this ticket #1683 but was closed without a solution

**Comment by anuraaga** [comment]
Thanks for the report - going to add the instrumentation module back in with https://github.com/openzipkin/docker-jre-full/pull/16

**Comment by anuraaga** [comment]
I have repushed openzipkin/zipkin:2.19.1 with a new base image including the instrument module. Can you give it a try? Please let us know if you still have an issue.

**Comment by quangnguyen** [comment]
Hey, thanks for your contribution, and i'm pretty sure that it will work because i just did the same as your commit on the base JRE image and build the master on my local and does not see the error anymore.
