### ISSUE TITLE
Elastic Storage - Make index type delimiter configurable

### ISSUE THREAD

**Issue by koalalam** [openzipkin/zipkin#2911]
**Feature:**
Colon ":" is an invalid char in index name from Elastic 7, and Zipkin addresses this in version 2.14 by using hyphen "-" instead. Can we actually have this configurable similar to other config e.g. `ES_DATE_SEPARATOR`

**Rational**
In our use case, hyphen "-" is restricted char used as a delimiter for specific purpose, and having hyphen in the index name would fail our application.

**Comment by jorgheymans** [comment]
@koalalam this looks like a fairly niche bit of functionality, not many sites will have a restriction on specific characters in ES index names. Nobody else has complained about this, so we're hesitant to support such feature. Is this still an issue for you, did you find a workaround ?

**Comment by jorgheymans** [comment]
Closing as no more feedback received. If you feel this is still relevant for your site, feel free to reopen and raise a PR, as it's unlikely to get addressed by the Zipkin community.
