### ISSUE TITLE
Springboot instance could not register zipkin

### ISSUE THREAD

**Issue by developers-youcong** [openzipkin/zipkin#2914]
My version of SpringBoot 2.0.3
Zipkin-server 2.11.2
As shown in figure:
![image](https://user-images.githubusercontent.com/45055576/68768343-4b1ae380-065d-11ea-844b-8e91d3b8611f.png)

There is no problem with normal startup

My configuration file is shown below:
![image](https://user-images.githubusercontent.com/45055576/68768525-9d5c0480-065d-11ea-9825-2ad8aac90f2a.png)
No error information, is unable to register, so I am very confused

**Comment by johnxiaohe** [comment]
I have few instance registed zipkin , And other doesn`t register :(

**Comment by jorgheymans** [comment]
please drop by in the gitter channel for questions https://gitter.im/openzipkin/zipkin
