### ISSUE TITLE
Tabs in span name breaks span name dropdown

### ISSUE THREAD

**Issue by lambcode** [openzipkin/zipkin#2915]
We have some span names that contain tabs. This is breaking zipkin ui (both classic and lens) in recent versions of zipkin because the browser cannot parse the JSON returned from the /api/v2/spans endpoint. I get an error like "SyntaxError: JSON.parse: bad control character in string literal at line 1 column 916 of the JSON data". Looking at the raw data returned from this endpoint the "bad character" is a tab. In older versions of zipkin (confirmed in 2.11.12) this character would have been encoded as "\t".

![image](https://user-images.githubusercontent.com/5820125/68806348-f0649600-0622-11ea-97a6-07557cc58ecc.png)

## Steps to Reproduce (using zipkin version 2.19.1)
1. Save a span with a tab in the span name
2. Load the investigation page and enter the service name for the above span
- See error produced by classsic ui
  - Note that the lens-ui doesn't report any error, even though span names failed to load
- See JSON.parse error in inspector

**Comment by anuraaga** [comment]
Thanks for reporting! Will try to get this released soon
