### ISSUE TITLE
Basic permission authentication

### ISSUE THREAD

**Issue by caoxiaojian** [openzipkin/zipkin#2918]
Hello, gods. Is there any built-in UI login permission Settings?

**Comment by jcchavezs** [comment]
As the [issue template](https://github.com/openzipkin/zipkin/blob/master/.github/ISSUE_TEMPLATE/question.md) say, questions should be asked on [gitter](https://gitter.im/openzipkin/zipkin). Please head there and we will help you. Regarding the login, you can check this comment: https://github.com/openzipkin/zipkin/issues/782#issuecomment-433306013
