### ISSUE TITLE
Lens 'collapse all' not recursive

### ISSUE THREAD

**Issue by lambcode** [openzipkin/zipkin#2920]
## Describe the Bug
Lens UI does not recursively collapse spans when clicking collapse all buttons like the classic UI does. This ability is useful with large traces when you want to see all the child spans of a span next to each other. Classic UI made this simple by being able to collapse all spans then re-open them one level at a time.

## Steps to Reproduce
1. Open a trace with multiple levels and multiple spans at each level.
2. Collapse all the spans
![image](https://user-images.githubusercontent.com/5820125/68893920-67f9fa00-06e3-11ea-8e3c-c55bc7fdeb6d.png)
3. Uncollapse the root span
- Note that the whole tree has been uncollapsed.

## Expected Behaviour
On step 3 above, only one level of the tree should be un-collapsed. In other words, after step 3 I expect there to only be two levels of spans visible.

## Other notes
These 'collapse all' and 'expand all' buttons are not labeled. Can we at least get a tooltip on them?

**Comment by delanym** [comment]
i only work with large traces - zipkin is unusable without this

**Comment by jcchavezs** [comment]
@delanym would you come up with a PR for this?

**Comment by delanym** [comment]
Sorry. I only need one dashboard and zipkin is crashing all the time due to OOM (even with - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError) and not providing any benefit over Jaeger (as far as I can tell)

**Comment by tacigar** [comment]
This has been fixed by #3486 🙇 

https://user-images.githubusercontent.com/19551419/209486970-3507d335-95e2-467e-9018-4ae9eddec2e7.mov
