### ISSUE TITLE
log4j2_events metric missing from actuator/prometheus

### ISSUE THREAD

**Issue by mstaalesen** [openzipkin/zipkin#2927]
## Describe the Bug
In the Grafana-dashboard, we rely on the following metric "log4j2_events". This is used to show how many trace, debug, info, warn, error-messages are logged by Zipkin it self. Right now we are in the dark because there are no metric for these events.

## Steps to Reproduce
Load the grafana-dashboard from grafana.com on a freshly installed zipkin. Ensure that prometheus is scraping the zipkin-instance and observe that it states "NO DATA" on the dashboard.

## Expected Behaviour
Expected that the metric would still be there.

**Comment by devinsba** [comment]
These were dropped when we switched away from Log4J2 for logging. Our intent was to have the dashboard updated to not have the logging metrics because we almost never log anyway.

https://github.com/openzipkin/zipkin/pull/2905#issuecomment-548995852

**Comment by mstaalesen** [comment]
Ok! Want me to update dashboard?

**Comment by jeqo** [comment]
@mstaalesen please do, I'll be happy to review. Thanks!
