### ISSUE TITLE
Too many metrics/timeseries in zipkin

### ISSUE THREAD

**Issue by mstaalesen** [openzipkin/zipkin#2928]
## Describe the Bug
As of right now, there are way to many metric/timeseries in zipkin that prometheus is scraping. The reason for this seems to be that among other things, the server_requests creates timeseries for ALL urls that is accessed on the server. Some examples:

http_server_requests_seconds_bucket{method="GET",status="200",uri="/zipkin/webfonts/fa-brands-400-cccc9d29470e879e40eb70249d9a2705.woff2",le="0.003844776",} 8.0
http_server_requests_seconds_bucket{method="GET",status="200",uri="/zipkin/traces.properties",le="0.003495251",} 7.0
http_server_requests_seconds_bucket{method="GET",status="200",uri="/zipkin/main.5676091b5509c77eec8a.css",le="1.789569706",} 7.0

## Steps to Reproduce
Look at the metrics under /actuator/prometheus

## Expected Behaviour
It is very nice that we can monitor how long requests the server processes takes, but it is not interesting to see how long it uses to load .css and .js files. 

On some parts of the metrics, it looks like this: 
http_server_requests_seconds_bucket{method="GET",status="200",uri="/api/v2/trace/{traceId}",le="0.008388607",} 16.0

This ({traceid}) is a very nice way of sorting the metrics, either use that way or perhaps look into only creating metrics for /api/-uris would be nice.

**Comment by anuraaga** [comment]
Thanks for reporting, the intent was definitely not to have those metrics for static resources but I think might have broke in a refactoring. Will fix it to only track API
