### ISSUE TITLE
How to add a new span or data into a closed trace which was created 5 mins ago ?

### ISSUE THREAD

**Issue by xia-deng** [openzipkin/zipkin#2944]
Hi, I have a question:
In our codes, we finished a operation and save it to zipkin.
After 5mins, we need to add some new span or data into the trace created 5 mins ago.

How can I do that?

**Comment by xia-deng** [comment]
I tried to add the span into es directly, but is showed error in the zipkin UI.

**Comment by jcchavezs** [comment]
I recommend you ask such questions on gitter. There is not such concept as
"closed trace", you can still add spans to the trace, I don't recommend you
do that directly to ES.

man. 9. des. 2019, 06:24 skrev xia-deng <notifications@github.com>:
