### ISSUE TITLE
spring boot2.1.11 upgrade to spring boot2.2.2 stucked when server setups 

### ISSUE THREAD

**Issue by sparkcai** [openzipkin/zipkin#2945]
when spring cloud greenwich upgrade  to spring cloud hoxton,  the main tread get stuck.
https://github.com/spring-projects/spring-boot/issues/19432#issuecomment-568636879

there is a sample https://github.com/spring-projects/spring-boot/files/3997033/testp.zip

related issues  https://github.com/spring-projects/spring-boot/issues/19432

**Comment by codefromthecrypt** [comment]
if anything this is related to spring-cloud-sleuth not this project. if you don't believe this to be true, contact us on chat to clarify https://gitter.im/openzipkin/zipkin
