### ISSUE TITLE
Build EC2 on Ubuntu failed

### ISSUE THREAD

**Issue by robbinfan** [openzipkin/zipkin#295]
When I build zipkin, got error like this:
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/builder/ZipkinServerBuilder.scala:18: StatsReceiver is not a member of com.twitter.finagle.stats
[error] import com.twitter.finagle.stats.{StatsReceiver, OstrichStatsReceiver}
[error]        ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/builder/ZipkinServerBuilder.scala:19: object tracing is not a member of package com.twitter.finagle
[error] import com.twitter.finagle.tracing.{Tracer, NullTracer}
[error]                            ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/builder/ZipkinServerBuilder.scala:38: not found: type StatsReceiver
[error]   statsReceiver           : StatsReceiver            = new OstrichStatsReceiver,
[error]                             ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/builder/ZipkinServerBuilder.scala:38: class file needed by OstrichStatsReceiver is missing.
[error] reference type StatsReceiverWithCumulativeGauges of package com.twitter.finagle.stats refers to nonexisting symbol.
[error]   statsReceiver           : StatsReceiver            = new OstrichStatsReceiver,
[error]                                                            ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/builder/ZipkinServerBuilder.scala:48: not found: type StatsReceiver
[error]   def statsReceiver(s: StatsReceiver)   : ZipkinServerBuilder = copy(statsReceiver     = s)
[error]                        ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/config/ZipkinConfig.scala:19: StatsReceiver is not a member of com.twitter.finagle.stats
[error] import com.twitter.finagle.stats.{OstrichStatsReceiver, StatsReceiver}
[error]        ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/config/ZipkinConfig.scala:20: object tracing is not a member of package com.twitter.finagle
[error] import com.twitter.finagle.tracing.{NullTracer, Tracer}
[error]                            ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/config/ZipkinConfig.scala:38: not found: type StatsReceiver
[error]   lazy val statsReceiver: StatsReceiver = new OstrichStatsReceiver
[error]                           ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/config/ZipkinConfig.scala:38: class file needed by OstrichStatsReceiver is missing.
[error] reference type StatsReceiverWithCumulativeGauges of package com.twitter.finagle.stats refers to nonexisting symbol.
[error]   lazy val statsReceiver: StatsReceiver = new OstrichStatsReceiver
[error]                                               ^
[error] /home/ubuntu/twitter/zipkin/zipkin-common/src/main/scala/com/twitter/zipkin/query/Trace.scala:18: object tracing is not a member of package com.twitter.finagle
[error] import com.twitter.finagle.tracing.{Trace => FTrace}
[error]                            ^
[error] 10 errors found
[error](zipkin-common/compile:compile) Compilation failed

**Comment by bmdhacks** [comment]
That's crazy.  Try deleting your ~/.m2 directory.  or at least running sbt
clean.  Or just trying on a different machine.

**Comment by Jeffliu** [comment]
I met the problem too.  But my Zipkin project worked a few days ago. 

Update: I finally make it work by removing the jars downloaded in the latest 2 days:

```
find ~/.ivy2/cache/com.twitter -type f -mtime -2 -exec rm -rf {} \;
```

**Comment by rtyler** [comment]
@robbinfan With the new Gradle-based build system that #503 introduced, I believe this issue has been fixed. Will you re-open it if that's not the case?
