### ISSUE TITLE
How to ignore span which is not important (such as periodic health check task span)

### ISSUE THREAD

**Issue by Costriod** [openzipkin/zipkin#2952]
In our product, we use the consul as configuration center,  and there is a ThreadPoolTaskScheduler instance has been injected to ConsulCatalogWatch,  the ThreadPoolTaskScheduler instance is a proxy which is proxied by cglib, and there is a LazyTraceThreadPoolTaskScheduler instance within ThreadPoolTaskScheduler proxy.
there is a new TraceRunnable instance when a task was submitted to the LazyTraceThreadPoolTaskScheduler (the task is wrapped as a TraceRunnable instance).  but TraceRunnable always create a new span instance when the task was executed.  

ConsulCatalogWatch was a periodic task which means a large amount of span will be created. some other infrastructural instances may also submit tasks to this ThreadPoolTaskScheduler proxy. so we need a solution that we can ignore the span which is less important.

![image](https://user-images.githubusercontent.com/32225219/71820344-ca5eed80-30c9-11ea-9cfe-d76694b3fccb.png)

**Comment by Costriod** [comment]
the zipkin reporter is a final inner class (zipkin2.reporter.AsyncReporter.BoundedAsyncReporter), it is not convenient for us, so we copy these code, and create a new class,  and it supports span filtering now.  but ungracefully.

**Comment by jorgheymans** [comment]
please use gitter, does https://github.com/openzipkin/brave/tree/master/brave#handling-finished-spans help ?

**Comment by Costriod** [comment]
> please use gitter, does https://github.com/openzipkin/brave/tree/master/brave#handling-finished-spans help ?

thanks, it works.
