### ISSUE TITLE
‘showing’  Functional suggestions

### ISSUE THREAD

**Issue by yanghaiji** [openzipkin/zipkin#2954]
Can we change "showing:" to substitute the way of counting the total number of entries? This will help us to see the number of accesses to each interface，

**Comment by jcchavezs** [comment]
@Dylan-haiji could you share a screenshot? If what you want is that zipkin displays the numnber of matching traces for a given search, that could be an expensive operation depending on the storage. Also, such observation belongs more to the metrics space IMO.

**Comment by yanghaiji** [comment]
![zipkin](https://user-images.githubusercontent.com/37392164/72031056-2d1cd880-32c6-11ea-8a9c-e99fa10683c2.png)
As shown in the figure above, I think the display of this part can be optimized. For example, I now have 13 pieces of data, but if my facility displays 10 pieces of data per page, it will display 10 pieces, but if I set it to be more than the total number of data, it will now display the total number of pieces. I think it should always display the total number of pieces, so that the accurate results can be queried according to the conditions! How do you feel?

**Comment by jorgheymans** [comment]
@Dylan-haiji this refers to the classic zipkin UI which has now been replaced by Lens., the new UI. Is it possible for you to check if the issue still occurs there ? Upgrading to one of the latest versions should do the trick.

**Comment by jorgheymans** [comment]
in Lens, the pagination notion no longer exists :

![image](https://user-images.githubusercontent.com/193792/80279258-9d782a00-86fc-11ea-8966-da106e6a3395.png)

**Comment by yanghaiji** [comment]
OK
