### ISSUE TITLE
Object should not be used for the type of tags.http.url

### ISSUE THREAD

**Issue by yanghaiji** [openzipkin/zipkin#2957]
![image](https://user-images.githubusercontent.com/37392164/72242538-af89fd00-3624-11ea-9695-c3be38243fd4.png)
Because the field type is object, elasticsearch cannot query it as a conditional line. You need to change the object type to nested

**Comment by codefromthecrypt** [comment]
indexing is done differently in service of our HTTP api and the
constraints needed for it
https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/elasticsearch#query-indexing

no warranty, but you can look at this which discusses a feature
supported by Elasticsearch: secondary index template
https://gist.github.com/adriancole/1af1259102e7a2da1b3c9103565165d7

**Comment by codefromthecrypt** [comment]
feel free to follow-up on chat https://gitter.im/openzipkin/zipkin
