### ISSUE TITLE
On the calculation of Zipkin dependencies

### ISSUE THREAD

**Issue by uckyk** [openzipkin/zipkin#2963]
[{"traceId":"df3e4c4d2750fb1e","id":"df3e4c4d2750fb1e","kind":"CLIENT","name":"realnamerelation/selectbyreplyidandstatus","timestamp":1579597468311016,"duration":4072,"localEndpoint":{"serviceName":"grpc-client","ipv4":"10.11"}},{"traceId":"df3e4c4d2750fb1e","id":"df3e4c4d2750fb1e","kind":"SERVER","name":"realnamerelation/selectbyreplyidandstatus","timestamp":1579597468311004,"duration":3137,"localEndpoint":{"serviceName":"grpc-server","ipv4":"10.12"},"shared":true}]

This is a trance record of span, and I want to know how they calculate dependency dependence. There are some parts of the source code that I don't quite understand, so I came to ask for help.

I tried to convert the process of computing depencency into SQL computing (doris,clickhouse). I encountered some problems in the process of reading the source code. I was confused about some calculations and had no way to start.

SELECT child , parent, COUNT(1) ,SUM(error) AS callCount FROM
 ( ( SELECT traceId, name, localEndpoint.serviceNameAS child ,remoteEndpoint.serviceName AS parent ,tag.errorAS error
 FROM test
 WHERE kind = 'SERVER' OR kind = 'CONSUMER') 
UNION ALL
( SELECT traceId,name, localEndpoint.serviceNameAS parent ,remoteEndpoint.serviceName AS child ,tag.errorAS error 
 FROM test
 WHERE kind = 'CLIENT' OR kind = 'PRODUCER' )) AS SPAN 
GROUP BY parent, child ;

This is the SQL I tried to write. There is no doubt that there is a problem. Normally, it should be {child = client, parent = server, callcount = x, errorcount = y}. With this SQL, I can't find the remoteservice, so {child = client, parent = null, callcount = x, errorcount = y} {child = server, parent = null, callcount = x, errorcount = y}

I hope I can get your help Thank you

**Comment by jorgheymans** [comment]
Issue was transferred to https://github.com/openzipkin/zipkin-dependencies/issues/161
