### ISSUE TITLE
WARN zipkin2.server.internal.BodyIsExceptionMessage - Unexpected error handling request. com.linecorp.armeria.common.ClosedSessionException: nulle is:open 

### ISSUE THREAD

**Issue by peacejj** [openzipkin/zipkin#2972]
## Describe the Bug
WARN zipkin2.server.internal.BodyIsExceptionMessage - Unexpected error handling request. com.linecorp.armeria.common.ClosedSessionException: nulle is:open 

## Steps to Reproduce
Sometimes,This is an exception after requesting the webpage.Page 503 error.
I don't know it's reason 

## Expected Behaviour
solve it!

**Comment by codefromthecrypt** [comment]
@peacejj this is usually when there is a connection or latency problem. please use gitter for troubleshooting https://gitter.im/openzipkin/zipkin
