### ISSUE TITLE
zipkin-lens constantly flashes in and out a scroll bar

### ISSUE THREAD

**Issue by anuraaga** [openzipkin/zipkin#2973]
## Describe the Bug
On Chrome in Windows, after opening a trace, the vertical scroll bar flashes in and out at ~60FPS causing a dancing page.

Screen capture tools can't capture the behavior since it seems to flash between the frames of a 30FPS video perfectly.

My camera can barely capture it
https://drive.google.com/open?id=1I3iSPvYDLdDxsQQPdbFJAfvkgyGprX88

## Steps to Reproduce
Start current master zipkin server locally with SELF_TRACING_ENABLED
Open home page a couple of times
Search traces with no conditions
Click on first trace

## Expected Behaviour
The page doesn't dance.

I'm not sure if this will repro for anyone else. But maybe if @tacigar has any ideas on any panel that may be missing an `overflow: hidden` that could cause fix corner cases

**Comment by tbdyzm** [comment]
Hi, Sir
  I suffered from what you've met, I solved it by changing the resolution of Chrome. 90% or 110% fixed the problem.
![image](https://user-images.githubusercontent.com/41499236/74325453-9612d700-4dc3-11ea-8d14-d48627a180a9.png)

**Comment by codefromthecrypt** [comment]
agree that changing the size is a workaround, but it is a very bad experience and may cause dissatisfaction if not fixed and we switch lens to default. cc @openzipkin/ui
