### ISSUE TITLE
a question about span basic data

### ISSUE THREAD

**Issue by uckyk** [openzipkin/zipkin#2975]
I suspect there is a problem with the reported data. Zipkin should generate two span in one service node, one is the server and the other is the client. Now some nodes only have client data but no server data.
Is there error reporting for such span data?
I think the correct data is a node, a client and a server. Is my understanding correct?

**Comment by codefromthecrypt** [comment]
when a client is calling a server that isn't instrumented with zipkin, you will only see the client. in the shape of tree, the uninstrumented client will be the leaves.

we don't use github for question/answer so please follow-up on gitter https://gitter.im/openzipkin/zipkin
