### ISSUE TITLE
Missing public logo asset required by Zipking UI

### ISSUE THREAD

**Issue by javigomez** [openzipkin/zipkin#2988]
## Describe the Bug
![Screenshot 2020-02-26 at 11 14 10](https://user-images.githubusercontent.com/1375475/75335140-420af680-5889-11ea-9772-41ac0102a651.png)

Public asset https://zipkin.io/public/img/zipkin-logo-200x119.jpg is not available in zipkin server

## Steps to Reproduce

- `docker run -d -p 9411:9411 openzipkin/zipkin:latest`

You will see that the logo is missing in the UI

## Expected Behaviour
Logo is available in the server and the UI can load it.

**Comment by codefromthecrypt** [comment]
this has already been fixed in master. you can verify with the master tag. we'll have a release soon.

docker pull openzipkin/zipkin:master, etc.

**Comment by codefromthecrypt** [comment]
Actually, you are referring to the classic ui. This is removed on next release anyway. In any case, please try master and report feedback to chat https://gitter.im/openzipkin/zipkin

**Comment by codefromthecrypt** [comment]
fyi this is the version of the old UI that fixed the problem you mention https://github.com/openzipkin/zipkin/commit/d9d5dc8832f7db9565b02ee041731ca4062f8eb7
