### ISSUE TITLE
Lens UI fails to list traces

### ISSUE THREAD

**Issue by javigomez** [openzipkin/zipkin#2989]
## Describe the Bug
_Lens UI_ shows no traces while the _standard ui_ does

## Steps to Reproduce
- open a project that generates traces
- execute latest zipkin: `docker run -d -p 9411:9411 openzipkin/zipkin:latest`
- go to default UI and list them. You will see your traces:
![standard](https://user-images.githubusercontent.com/1375475/75335587-015fad00-588a-11ea-87ef-b3b1db8b2603.png)

The XHR request is:
`Request URL:http://localhost:9411/zipkin/api/v2/traces?limit=10&lookback=900000`

- click "Lens UI" and click the "magnifying glass" icon to list all your traces (without modifying any of the default filters), you will see that no traces are listed:
![lens ui](https://user-images.githubusercontent.com/1375475/75335688-2c4a0100-588a-11ea-9f57-d2d6a98071bd.png)
 
The XHR request is:
`Request URL:http://localhost:9411/zipkin/api/v2/traces?endTs=1582712351352&limit=10&lookback=300000&remoteServiceName=all&serviceName=all&spanName=all
`

Note this last XHR request does not return any trace

## Expected Behaviour
Traces are listed the same way in both UIs

**Comment by codefromthecrypt** [comment]
What happens if you just do normal reload of lens without retaining parameters from the old ui.. then execute search by constructing it?

a guess is that lens isn't clearing the "=all" stuff added by the old UI, so this problem will go away in the next release anyway as the old UI is no longer mounted anyway.

**Comment by jorgheymans** [comment]
@javigomez Lens is now the default UI, the 'Try Lens UI' button has been removed so this should no longer be problem. OK to close this issue ?

**Comment by dnozay** [comment]
I am having the same issue

```
java \
    -Dzipkin.collector.kafka.topic=xxxxxxxx_zipkin \
    -Dzipkin.collector.kafka.bootstrap-servers=XXXXXXXXXXXXX:9092 \
    -Dzipkin.collector.kafka.overrides.auto.offset.reset="earliest" \
    -Dzipkin.collector.kafka.overrides.sasl.mechanism="PLAIN" \
    -Dzipkin.collector.kafka.overrides.security.protocol="SASL_SSL" \
    -Dzipkin.collector.kafka.overrides.ssl.endpoint.identification.algorithm="https" \
    -Djava.security.auth.login.config="jaas.config" \
    -jar zipkin-2.19.2.jar
```

![image](https://user-images.githubusercontent.com/205466/83209139-671f3780-a10c-11ea-987d-c709e7bc6153.png)

In the Lens UI:
![image](https://user-images.githubusercontent.com/205466/83209201-9766d600-a10c-11ea-9347-69eff9c892d6.png)

Latest from today shows JS error:
```
TypeError: Cannot read property 'map' of undefined
    at TracesTableRow.jsx:141
    at Xo (react-dom.production.min.js:153)
    at ms (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at $s (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ui (react-dom.production.min.js:122)
    at Yi (react-dom.production.min.js:123)
```

but on the screenshot, you can see that it did find traces.
using a direct url to one of the traces is fine.
 
![image](https://user-images.githubusercontent.com/205466/83209636-a7cb8080-a10d-11ea-986a-84c97145cb5b.png)

**Comment by jorgheymans** [comment]
Closing as it's an artifact of the transition period where we had both Lens and Zipkin classic running, that time is long behind us. Also no further feedback since February.
