### ISSUE TITLE
Cannot open traces in a new tab

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#2998]
## Describe the Bug
In the latest version of lens, I'm unable to open the search results in a new tab. If I cmd + click on a trace it still opens it in the current window and if I right click there's no "open in new tab" option.

## Steps to Reproduce
search for anything and try to open any of the result traces in a new tab.

**Comment by anuraaga** [comment]
@tacigar I guess this has a good chance of happening automatically with #2997. What do you think?

**Comment by tacigar** [comment]
I think this is a problem with the discover page not trace page.
So I think we can solve this issue only by change the following Box which has onClick callback to anchor tag.

https://github.com/openzipkin/zipkin/blob/956cdd5cd2f9b4f649c6fecd645e3fe52964244a/zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableRow.jsx#L106
