### ISSUE TITLE
how to split grouped nodes 

### ISSUE THREAD

**Issue by fulinlin924** [openzipkin/zipkin#300]
File: zipkin / zipkin-web / src / main / resources / public / js / zipkin-filter-span.js 

it is a great idea to split grouped nodes to sub-groups, but

Line: 132-134

```
$.each(nodeSet, function(i, n) {
  sum = n.duration * Math.abs(weightedAvg - ((n.getEndTime() + n.getStartTime()) / 2));
});
```

should be sum += ... ?

**Comment by franklinhu** [comment]
Hmm looks like you're right. We're happy to merge pull requests :)
