### ISSUE TITLE
Lens doesn't show the service name if any span in the trace is missing

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#3001]
## Describe the Bug
Some of my traces render just fine, but some of them render without service names. The span names and timing bars are fine, but the service names and the hierarchy doesn't show.

## Steps to Reproduce
Load this trace: https://i.fluffy.cc/wzGSB8HvZ83FHJ5RWk70cs8ZZwDSZ1TH.html

## Expected Behaviour
I can see the service names

**Comment by codefromthecrypt** [comment]
so looks like the results view has 1 span it thinks is unknown

![Screenshot 2020-06-18 at 4 18 35 PM](https://user-images.githubusercontent.com/64215/84996094-6748ab00-b17f-11ea-9f33-9a415f154661.png)

the trace view identifies the root span's service (routing), but yeah the service labels don't show

![Screenshot 2020-06-18 at 4 18 42 PM](https://user-images.githubusercontent.com/64215/84996140-762f5d80-b17f-11ea-8616-211c5a6aacb7.png)

also there's no error in the console

**Comment by codefromthecrypt** [comment]
the problem specifically is this span, which is marked shared but is missing the client span:

```json
    "traceId": "e16be24f11073022",
    "parentId": "71f8077e2923a571",
    "id": "41b68e37ddbdb23e",
    "kind": "SERVER",
    "name": "get biz .__fallback__ ",
```

**Comment by codefromthecrypt** [comment]
taking the "shared" flag off that span allows rendering the service name list in the details view. So, we are tolerant to the bad data, but not enough..

**Comment by codefromthecrypt** [comment]
I still have no idea what's rendering the services column. Anyway I suspect fixing the trace tree would be the best idea. One day, I'd love to know how that services column works, cc @tacigar if you have any pointers.

![Screenshot 2020-06-18 at 8 20 25 PM](https://user-images.githubusercontent.com/64215/85019331-37aa9a80-b1a1-11ea-9fdc-547a5dbf0d16.png)

**Comment by codefromthecrypt** [comment]
This is hard to fix as there are a lot of data problems here.. particularly it is missing client spans or they are possibly not client and marked as server. I will see how hard it is to detect and correct.

**Comment by codefromthecrypt** [comment]
saved by the bell :) turned out it was more about the misclassified root span than anything else #3121 (still want to know how service column is rendered one day)
