### ISSUE TITLE
Use a mutable empty map instead of Collections.emptyMap

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#3005]
https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin2/Span.java#L759

`tags = builder.tags == null ? Collections.emptyMap() : new LinkedHashMap<>(builder.tags);`

The empty map is immutable and makes it difficult to add a tag to a already created span. This will be helpful with performance. Otherwise, have to turn it in to builder and back to a Span when this type is used in the stream processing pipeline.

@adriancole

**Comment by codefromthecrypt** [comment]
Hi, nara. The span is and has always been intentionally immutable. Can you use another type for mutable changes? like Brave's MutableSpan? or a normal pojo? I can help with a json codec if it helps you..

**Comment by codefromthecrypt** [comment]
I think we had an old issue about collector-side mutations, and agree that the span type isn't efficient. Just I don't think retroactively a make Span mutable is the answer. Doesn't mean we can't make another option.. worst case we add a version of MutableSpan here... @jeqo thoughts?

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2807 should be updated based on this discussion and work

**Comment by connectwithnara** [comment]
`MutableSpan` is helpful also. JSON codec is necessary to be able to create this type from the data published by the tracers. This is not a critical ask, just a nice to have for us.

**Comment by anuraaga** [comment]
Just a thought, is it possible to use the proto? Protos are also immutable but conversion to builder is shallow so usually is pretty fast. Though perhaps not fast enough - wondering if it could work though.

**Comment by codefromthecrypt** [comment]
netflix pipeline is in json format, so for this use case probably isn't that useful even if they were ok adding the chain of deps for google's proto plus json.

**Comment by codefromthecrypt** [comment]
@narayaruna in case it works for you, I think what rag might be suggesting is to use our backported proto def https://github.com/openzipkin/zipkin-api/blob/master/zipkin-jsonv2.proto and generate the json stuff from that, which would match the same model as zipkin2.Span

worth thinking about it, as it kicks the can further down and might buy time depending on urgency.

**Comment by anuraaga** [comment]
Yeah was hoping one or the other :) Also shameful plug for fast proto - json 

https://github.com/curioswitch/curiostack/blob/master/common/grpc/protobuf-jackson/README.md

**Comment by codefromthecrypt** [comment]
@narayaruna PS MutableSpan in brave is almost complete. Version 5.12 will have all (actually more) fields than zipkin2.Span and should be possible to make jackson support for.

**Comment by codefromthecrypt** [comment]
meanwhile I think the easiest thing is to create your own type, as the data structure is not complicated.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/brave/pull/1212 might help as we have an encoder now in the default jar. decoding would be separate, though I expect something out-of-box could be fine for that..

**Comment by codefromthecrypt** [comment]
Since the model is so simple, and also so stable, I think the best way forward is a pipeline-specific mutable type vs more coupling. In the domain of a pipeline, very efficient (more efficient than ours!) codecs can be used. Also, the functions can match up to the transformation libraries (ex kafka streams etc).

I don't expect us to make the zipkin span mutable, so I'll close this instead of leaving it open without an answer. Here's the closest we have at the moment, which may work for those disinterested in using jackson etc. https://github.com/openzipkin/zipkin-reporter-java/tree/master/brave
