### ISSUE TITLE
Zipkin with sqlite duplicates some spans

### ISSUE THREAD

**Issue by henrikno** [openzipkin/zipkin#301]
I was testing out [brave-resteasy-example](https://github.com/kristofa/brave-resteasy-example) with it's ZipkinSpanCollector when I got this strange result:

![brave-duplicate](https://f.cloud.github.com/assets/147660/1232284/b598b0b0-28a2-11e3-8aef-c08f339cb60c.png)

I thought it might be was brave submitting spans twice, but we found that the bug was not in brave.
Logs from running the test:
https://gist.github.com/zerd/6752929
The debug output from zipkin-collector notes 4 spans, which is correct.
When I run with the redis backend there are no duplicates.

I'm using master branch of zipkin.

**Comment by wadey** [comment]
I ran into the same issue while testing zipkin (1.1.0 and master) with the sqlite backend. Changing to redis fixed it.

**Comment by franklinhu** [comment]
So it looks like this was an oversight in the way that AnormDB joined spans with annotations and binary annotations. I've posted #308, which should fix this issue. @wadey if you try the branch `fix-anorm-span-merging` does it work?
