### ISSUE TITLE
The search results page kept flashing

### ISSUE THREAD

**Issue by andriodjinguang** [openzipkin/zipkin#3020]
zipkin-server-2.20.0 The search results page kept flashing
![645Q@3BNV$7SF8_I0(677NV](https://user-images.githubusercontent.com/13514252/76400771-cf873400-63bb-11ea-8c15-801c914eb4b7.png)
It keeps flashing

**Comment by adriancole** [comment]
interesting.. we thought this was fixed in https://github.com/openzipkin/zipkin/pull/2991

**Comment by andriodjinguang** [comment]
Dependencies no data
![_K3AVV3%E`H$) `LKKVNES7](https://user-images.githubusercontent.com/13514252/76408465-f5b2d100-63c7-11ea-9761-d2a4054c2d78.png)
discover have data
![`LI9O58V7 H$1$CK14KIMQT](https://user-images.githubusercontent.com/13514252/76408635-314d9b00-63c8-11ea-82d4-1a1353c4fbbb.png)

**Comment by adriancole** [comment]
for general troubleshooting please use https://gitter.im/openzipkin/zipkin

let's keep this issue about the flashing
