### ISSUE TITLE
Disable index template creation at startup

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#3025]
The ES index templates are created during server startup. Sites like Netflix have customized the template and prefer managing the templates outside the server runtime.

We would like if the template creation can be controlled via a property.

@adriancole

**Comment by codefromthecrypt** [comment]
I'm curious why this is needed? if you use the same template name as us, we don't install it.

**Comment by codefromthecrypt** [comment]
we never opened an issue for this, but I also remember @basvanbeek asking to do offline index template install https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/VersionSpecificTemplates.java#L19

**Comment by codefromthecrypt** [comment]
PS I'm cool with this. ES_ENSURE_TEMPLATES ok?

**Comment by basvanbeek** [comment]
+1

**Comment by uckyk** [comment]
+1

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/3063
