### ISSUE TITLE
Dependencies no data

### ISSUE THREAD

**Issue by andriodjinguang** [openzipkin/zipkin#3027]
Dependencies no data
![_K3AVV3%E`H$) `LKKVNES7](https://user-images.githubusercontent.com/13514252/76495475-eb4d1180-6471-11ea-87e9-a32fca9617a6.png)
Discover have data
![`LI9O58V7 H$1$CK14KIMQT](https://user-images.githubusercontent.com/13514252/76495518-fbfd8780-6471-11ea-8386-7b1fc95c171a.png)

**Comment by adriancole** [comment]
please stop opening issues and ask on gitter first? https://gitter.im/openzipkin/zipkin
