### ISSUE TITLE
Zipkin UI logsUrl does not support multiple occurrence of {traceId} 

### ISSUE THREAD

**Issue by matrixvampire** [openzipkin/zipkin#3033]
## Describe the Bug
I am trying to link Kibana in Zipkin UI (Lens). The button is shown correctly. `{traceId}` are not replaced in the URL.

I tried with simple URL with multiple occurence of `{traceId}`. It is able to replace the first occurence of {traceId}.

## Steps to Reproduce
`zipkin.ui.logs-url=https://kibana.company.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'ca487de6-0028-4e74-b14b-65eddbcf1f5a',key:Trace_ID,negate:!f,params:(query:'{traceId}'),type:phrase,value:'{traceId}'),query:(match:(Trace_ID:(query:'{traceId}',type:phrase))))),index:'ca487de6-0028-4e74-b14b-65eddbcf1f5a',interval:auto,query:(language:kuery,query:''),sort:!('@timestamp',desc))`

## Expected Behaviour
Zipkin UI should able to replace multiple occurence of `{traceId}`.

**Comment by anuraaga** [comment]
Thanks for the report, will fix it!
