### ISSUE TITLE
Pagination on the result page broken

### ISSUE THREAD

**Issue by bigon** [openzipkin/zipkin#3034]
Hello,

I just updated to 2.20.2 and when doing a search, I get the following on the top instead of the number of results/pagination:

`{0, plural, one {# Result} other {# Results}}`

**Comment by anuraaga** [comment]
Hi @bigon - thanks for the report. I'm not being able to reproduce. Do you happen to have any steps to reproduce?

I run with
`docker run -it --rm -e SELF_TRACING_ENABLED=true -p 9411:9411 openzipkin/zipkin:2.20.2`

And open `http://localhost:9411` and hit search button a few times and it shows `1 Result`, `2 Results`, etc.

I tried with `java -jar` of the quickstart jar too and couldn't repro. Let me know if you have any steps to trigger this.

**Comment by anuraaga** [comment]
Also if you can post the language detected on https://www.whatsmybrowser.org/ that would be helpful. I suspected a browser language that isn't one of our supported may do that, though even then I'm not able to reproduce.

**Comment by bigon** [comment]
OK indeed it's an issue with the language, I've `fr-BE` (I tried with plain `fr`, same result). If I set the language to `en` (or `en-us`) it works fine
