### ISSUE TITLE
lens: hovering over [download json] button could show REST url to fetch trace

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#3039]
**Feature:**
When hovering over the download json button, it seems intuitive to show the full link to the trace (ie http://myhost/api/v2/trace/4f711e17e7e2290a) , in the browser status bar just as if you would hover over a normal href. 
 
**Rational**
I could not remember the location of the swagger api definition at https://zipkin.io/zipkin-api/ , i wanted to fetch a trace using curl | jq . So i looked at the download button hoping to find the REST url there.

**Comment by anuraaga** [comment]
I love how this idea will both improve UX a bit and remove a significant amount of complexity from the code at the same time, thanks!
