### ISSUE TITLE
Ephemeral credentials support (e.g. HashiCorp Vault)

### ISSUE THREAD

**Issue by basvanbeek** [openzipkin/zipkin#3041]
**Feature:**

Some companies require the usage of ephemeral credentials for storage resources as for instance HashiCorp Vault provides. It would be great if we can add the ability to watch a credentials file for items like usernames, passwords, tokens, etc. and allow updates to these while Zipkin is running and trying to connect to storage solutions like ElasticSearch and Cassandra.

**Rational**

Not supporting ephemeral credentials is a blocker for some companies to approve usage of Zipkin in production. 

**Example Scenario**

-

**Prior Art**
 
Similar efforts have been made in SkyWalking: 

https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-storage.md#secrets-management-file-of-elasticsearch-authentication

**Comment by codefromthecrypt** [comment]
@basvanbeek it appears in skywalking they are watching a plain text properties file. how this is updated seems distracting, as the feature is much simpler if this is only about watching properties files for secrets..

@wu-sheng do I understand this right? the secrets file is just a plain text file which has a watch on it (and recreates server connections on update)

**Comment by codefromthecrypt** [comment]
PS I didn't mean to imply use cases aren't relevant, actually very happy use case of vault was mentioned.

Just I didn't want to over romanticize the code change, if we are mainly talking about  whitelist some properties as dynamic and scope components that use them to be refreshable. When there's no specific security plug-in we have a lot of choices on how to implement this, including normal things done in spring (refresh scope etc)

**Comment by codefromthecrypt** [comment]
one thing that might not be obvious is that externalizing certain properties works today. it is just that you have to restart the server. Hot credentials will be limited to the code we have to work with.. luckily the elasticsearch we have full control over and could easily make work with dynamic credentials. Some components might be more tricky due to what the library exposes (ex kafka and cassandra we re-use their libraries and in worst case would have to reboot the entire connector)

```bash
$ cat zipkin-server-security.properties 
zipkin.storage.elasticsearch.username=foo
zipkin.storage.elasticsearch.password=bar

# notice: authorization=****
$ STORAGE_TYPE=elasticsearch ES_HTTP_LOGGING=BODY  java -Dspring.profiles.active=security -jar zipkin.jar
---snip---
2020-03-25 19:06:17.376  INFO 62010 --- [-worker-nio-2-2] c.l.a.c.l.LoggingClient                  : Request: {startTime=2020-03-25T11:06:17.375Z(1585134377375857), length=0B, duration=252µs(252863ns), scheme=none+h1c, headers=[:method=GET, :path=/_cluster/health/zipkin*span-*, :authority=localhost:9200, :scheme=http, accept-encoding=gzip,deflate, user-agent=armeria/0.97.0, authorization=****]}
```

**Comment by anuraaga** [comment]
Yup I agree this issue is about watching a file for properties. And handling it for ES does seem simpler, though I suspect someone with stronger spring-fu skills could reload storage on property change if we needed.

**Comment by basvanbeek** [comment]
I specifically downscoped this issue to just watch for a file. Reason is that we don't want to burden ourselves with adding specific API's, token renewal, initial token exchange, etc. Those things are customer concerns and depending on environment they might differ.

In the use case of Vault there are various tools that all would allow for a credentials file to be written. This could either be a JSON, YAML or a `key: value` style file.

In a K8s environment one would use the `vault-k8s` tool, see: https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/

In most other environments one would use the `vault` cli tool, see: https://www.vaultproject.io/docs/secrets/databases/elasticdb/

So by allowing for a file watcher and reloading the storage user/pass credentials on change we support most cases while keeping our end of supporting ephemeral credentials to a minimum.

My immediate need is for ElasticSearch but if we could do this more generically (Vault has ephemeral credential support for our ES, Cassandra and Mysql storage engines) that would be better.

**Comment by codefromthecrypt** [comment]
spring has vault support but it is still better I think to step into this, and resort to full credential management later if necessary https://spring.io/projects/spring-vault

thanks for the tips. I know that it is more typical to automate a /refresh endpoint vs watching files due to scheduling issues between file update and when you should apply them. otoh assuming file update is enough constrains things.

There are some known implementation options listed here https://www.baeldung.com/spring-reloading-properties

**Comment by codefromthecrypt** [comment]
There's a recent PR in presto about a feature using watcher with some decent feedback https://github.com/prestodb/presto/pull/14056 Note, they do NOT use this for credentials, they have a [different solution](https://github.com/prestodb/presto/pull/11742). Also, LINE uses something different entirely, a ZK based file abstraction named central dogma. Many spring users use spring cloud config.

Anyway if someone wants to punt a special case for ES, maybe this sketch can help you start!

```java
  static final String QUALIFIER = "zipkinElasticsearch";
  static final String PROPERTIES_SOURCE = "zipkin-server-security.properties";
  static final String USERNAME_PROP = "zipkin.storage.elasticsearch.username";
  static final String PASSWORD_PROP = "zipkin.storage.elasticsearch.password";

  // credentials need to be updated independent of the actual interceptor
  static final class BasicCredentials {
    volatile String basicCredentials;

    BasicCredentials(String username, String password) {
      if (username == null) throw new NullPointerException("username == null");
      if (password == null) throw new NullPointerException("password == null");
      updateCredentials(username, password);
    }

    void updateCredentials(String username, String password) {
      String token = username + ':' + password;
      basicCredentials = "Basic " + Base64.getEncoder().encodeToString(token.getBytes(UTF_8));
    }
  }

  // initial password is important as you need something before the watch starts
  @Bean @Qualifier(QUALIFIER)
  BasicCredentials dynamicElasticsearchBasicCredentials(
    @Value("${" + USERNAME_PROP + "}") String initialUsername,
    @Value("${" + PASSWORD_PROP + "}") String initialPassword
  ) {
    return new BasicCredentials(initialUsername, initialPassword);
  }


  // wire into the code that exists already
  @Bean @Qualifier(QUALIFIER)
  Consumer<ClientOptionsBuilder> dynamicElasticsearchAuth(
    @Qualifier(QUALIFIER) BasicCredentials basicCredentials) {
--snip--

       // somewhere enter a watch poll loop and be defensive about it.
        for (WatchEvent<?> event : key.pollEvents()) {
          Path changed = (Path) event.context();
          if (changed.toString().equals(PROPERTIES_SOURCE) && event.kind().equals(ENTRY_MODIFY)) {
            Properties file = new Properties();
            try (FileInputStream is = new FileInputStream(changed.toFile())) {
              file.load(is);
              basicCredentials.updateCredentials(
                file.getProperty(USERNAME_PROP),
                file.getProperty(PASSWORD_PROP)
              );
--snip--
```

**Comment by codefromthecrypt** [comment]
for history, only dynamic thing we ever did was update a collector sample rate. here's some code if only interesting for log format? https://github.com/openzipkin-attic/zipkin-zookeeper/blob/master/src/main/java/zipkin/collector/zookeeper/SampleRateUpdater.java

**Comment by hanahmily** [comment]
@basvanbeek @adriancole I would like to contribute username/password property file refreshing based on the sketch @adriancole share with us.

**Comment by codefromthecrypt** [comment]
@hanahmily sweet. feel free to drop by https://gitter.im/openzipkin/zipkin with questions or https://line-armeria.slack.com/ if about the ES client interceptor hooks

**Comment by wu-sheng** [comment]
@hanahmily Haha, you are having fun here. Same feature in different projects :)
