### ISSUE TITLE
Error while trying to use openzipkin with elastic search engine

### ISSUE THREAD

**Issue by FIVIL** [openzipkin/zipkin#3042]
Hi, I am trying to start an open zipkin stack with docker and elastic search as data storage engine, I am using `openzipkin/zipkin-elasticsearch7` image for starting elasticsearch7. however, starting the container fails and in the log section there is this error:
`/elasticsearch/bin/elasticsearch: /elasticsearch/bin/elasticsearch-env: line 113: syntax error: unexpected word (expecting ")")`

**Comment by codefromthecrypt** [comment]
This is legit.

```bash
± |master {1} ?:3 ✗| → docker run -d -p 9200:9200 openzipkin/zipkin-elasticsearch7
c7fcf7c00998136518164158dd42708c99499cf75d4aaab2ded1fee3ea9721ff
 2020-03-25 08:58:43 ⌚  MacBook-Pro-8 in ~/oss/brave-webmvc-example
± |master {1} ?:3 ✗| → docker logs c7fcf7c00998136518164158dd42708c99499cf75d4aaab2ded1fee3ea9721ff
/elasticsearch/bin/elasticsearch: /elasticsearch/bin/elasticsearch-env: line 113: syntax error: unexpected word (expecting ")")
```
