### ISSUE TITLE
Flickering list of Traces in Chrome 

### ISSUE THREAD

**Issue by prostdenis** [openzipkin/zipkin#3045]
## Describe the Bug
In Chrome only : after a search, the list of traces flickers. It occurs only for maximised window, but very annoying.

## Steps to Reproduce
Open Zipkin in a maximised Chrome window. Select a service which contains some traces, search... the list of traces starts flickering.

**Comment by anuraaga** [comment]
Can you confirm this is on latest version? We fixed a flickering bug before but I think there may still be some corner cases left and will look in.

Also would you mind sharing your screen resolution, which I guess influences the size of the maximized window?

**Comment by prostdenis** [comment]
version is 2.20.1
resolution is 1920*1080 
Important : flickering happens only with a 150% size of text (display settings). With 125% and 100% it's fine.

**Comment by tacigar** [comment]
This issue may be solved #3180 and #3076
