### ISSUE TITLE
Lens gets wobbly

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#3054]
In Firefox (Ubuntu), there seems to be some instability in the layout when you mouseover on the right most search criteria. GIF explains it much better:

![wobbly](https://user-images.githubusercontent.com/193792/78427323-3d99e080-7674-11ea-9ecd-d20fcc7178c6.gif)

**Comment by ajacques** [comment]
In Chrome (Windows), this actually results in constant vibrating of the UI. I'm not strong enough on my CSS on how to fix it, but it seems that this JSX component is the one that changes width:

https://github.com/openzipkin/zipkin/blob/951cf697e30cbc292ab7427e1646df67e8fe2d5b/zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTab.jsx

**Comment by jorgheymans** [comment]
This is no longer an issue, due to extensive refactoring and redesign work on the search bar thanks @tacigar !

**Comment by tacigar** [comment]
Thanks!!!
