### ISSUE TITLE
Allow config to disable the Lens UI dependencies page

### ISSUE THREAD

**Issue by basvanbeek** [openzipkin/zipkin#3056]
The dependencies page only works in a production (Cassandra / ES) deployment when accompanied with a specific aggregation job. Since not all customers deploy such a job or even need it, it would be nice if we can disable the Lens UI dependencies page through Zipkin configuration.

**Comment by codefromthecrypt** [comment]
SEARCH_ENABLED controls the trace query screen (or used to ;P)
DEPENDENCIES_ENABLED?

**Comment by jcchavezs** [comment]
+1 to the flag that disables this. Side issue: when there is no data I
would add a text saying: did you run the aggregation job? and a link to it.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/3065
