### ISSUE TITLE
long service names should be wrapped

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/zipkin#3058]
Similar to https://github.com/openzipkin/zipkin/issues/2183 logged against classic UI, Lens could wrap long service names where needed. 

See the gif with an example of a really long service name, included below for testing convenience.

![long-text](https://user-images.githubusercontent.com/193792/79000358-c0c3a680-7b4c-11ea-8c36-fdd6381cd6bd.gif)

```
[
  {
    "traceId": "77047bf9cf04ed5d",
    "id": "77047bf9cf04ed5d",
    "name": "get",
    "timestamp": 1484722951945904,
    "duration": 156470,
    "annotations": [
      {
        "timestamp": 1484722951945904,
        "value": "sr",
        "endpoint": {
          "serviceName": "com.alipay.sofa.tracer.demo.facade.rpccallservice.okay.we.can.go.a.bit.further.to.see.how.lens.copes.with.this"
        }
      },
      {
        "timestamp": 1484722952102374,
        "value": "ss",
        "endpoint": {
          "serviceName": "com.alipay.sofa.tracer.demo.facade.rpccallservice.okay.we.can.go.a.bit.further.to.see.how.lens.copes.with.this"
        }
      }
    ]
  },
  {
    "traceId": "77047bf9cf04ed5d",
    "id": "40ef4e93ab3b1507",
    "name": "get",
    "parentId": "77047bf9cf04ed5d",
    "annotations": [
      {
        "timestamp": 1484722952100852,
        "value": "cs",
        "endpoint": {
          "serviceName": "com.alipay.sofa.tracer.demo.facade.rpccallservice.okay.we.can.go.a.bit.further.to.see.how.lens.copes.with.this"
        }
      }
    ]
  }
]
```

**Comment by codefromthecrypt** [comment]
@openzipkin/ui anyone have some time to contribute? This should be an easier one

**Comment by jorgheymans** [comment]
There's probably an overlap with https://github.com/openzipkin/zipkin/issues/2291 which says to scroll instead of wrap, but i'll let the UX guys do the debate on that.

**Comment by tacigar** [comment]
Thank you for your report.
I fixed this bug in #3061 .

**Comment by jorgheymans** [comment]
@tacigar thanks, looks good to me. Do you think anything could (should) be done for the service names in the trace diagram itself ?

**Comment by tacigar** [comment]
Yes, I know the problem, but I haven't fixed it yet.

Currently this trace diagram written by SVG.
Since SVG is not good at wrapping text and doing text ellipsis, I am thinking of re-implementing the trace diagram with regular html tags instead of SVG.
Regular html can style with powerful css.

I'll do it as soon as possible.

FYI: This is a PR that tried to solve this problem before. (I once merged it by mistake, but soon reverted ...) https://github.com/openzipkin/zipkin/pull/2949
