### ISSUE TITLE
not found packages

### ISSUE THREAD

**Issue by AllienPhone** [openzipkin/zipkin#307]
Resolving junit#junit;4.7 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.thrift#libthrift;0.5.0: not found
[warn]  :: com.twitter.common.zookeeper#client;0.0.35: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.apache.thrift#libthrift;0.5.0: not found

**Comment by bmdhacks** [comment]
It's located here: http://maven.twttr.com/org/apache/thrift/libthrift/
which should be in the repositories listed in the build.  I've seen people have trouble building in China because of the great firewall blocks twitter properties, perhaps that's what you're seeing?

**Comment by rtyler** [comment]
@AllienPhone I'm not seeing this behavior, can you please confirm it's still broken for you?

Also, what is the command that is being executed originally?

**Comment by rtyler** [comment]
With the merge of #503, the only potential way that I think this would be a problem is if a user were on a network that was blocking the maven repo. I'm going to close this out.

Please re-open if you can reproduce this error on HEAD of master
