### ISSUE TITLE
Zipkin-slim complains "NoClassDefFoundError" when setting up ES_CREDENTIALS_FILE

### ISSUE THREAD

**Issue by hanahmily** [openzipkin/zipkin#3086]
## Describe the Bug
When setting up ES_CREDENTIALS_FILE to enable credentials file for `zipkin-slim`, a `java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ThreadFactoryBuilder` is raised. The exception is from https://github.com/openzipkin/zipkin/blob/3aa6695bfdee6d0352a589ee10355b0fde705861/zipkin-server/src/main/java/zipkin2/server/internal/elasticsearch/ZipkinElasticsearchStorageConfiguration.java#L166
which leverages guava `ThreadFactoryBuilder` to build a thread factory for credentials file refresher.

I found that's because`guava` is excluded from slim. 
https://github.com/openzipkin/zipkin/blob/3aa6695bfdee6d0352a589ee10355b0fde705861/zipkin-server/pom.xml#L510

There seem two paths to fix it.

1. Remove ThreadFactoryBuilder to get rid of guava dependency.
1. Add guava back to slim.

I prefer the first approach. @adriancole WDYT?

**Comment by codefromthecrypt** [comment]
yeah threadfactorybuilder is overkill. go for 1. Also I remember this will
not work with self-tracing.. you can do something like this using your own
naming thread factory or with micrometer's

new NamedThreadFactory("zipkin-throttle-pool") {
  @Override public Thread newThread(Runnable runnable) {
    return super.newThread(new Runnable() {
      @Override public void run() {
        RequestContextCurrentTraceContext.setCurrentThreadNotRequestThread(true);
        runnable.run();
      }

      @Override public String toString() {
        return runnable.toString();
      }
    });
  }
},

**Comment by codefromthecrypt** [comment]
sorry ignore the comment about RequestContextCurrentTraceContext.

ES credentials thread only looks at file. If it made a RPC call to get credentials using armeria client, it would create a trace context break. So no need to worry about that as we only look at file which should not trigger any trace as we don't auto-instrument anything in this part.
