### ISSUE TITLE
Ui lens is blank when touch search button

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin#3088]
api return data , but ui failed render
![微信截图_20200520171231](https://user-images.githubusercontent.com/29320441/82428561-424c1400-9abd-11ea-9701-86fdca2c8fba.png)
![微信截图_20200520171420](https://user-images.githubusercontent.com/29320441/82428574-46783180-9abd-11ea-92a7-0b26c87a3230.png)

**Comment by jorgheymans** [comment]
Can you confirm the zipkin version you're using, and what is the storage backend ?

**Comment by ghost** [comment]
> Can you confirm the zipkin version you're using, and what is the storage backend ?

not use the storage backend,it used in memory, the zipkin version is  latest.

**Comment by ghost** [comment]
> Can you confirm the zipkin version you're using, and what is the storage backend ?

the excute.jar by mvn install source code ! . i dont konw the way of package is correct?

**Comment by jorgheymans** [comment]
Building from source is not needed, follow the quick-start to get going https://github.com/openzipkin/zipkin#quick-start and report back if you encounter any issues.

**Comment by ghost** [comment]
> encounter

I need change the  storage backend to support oracle , but i dont find related way,so i want change the source code .

**Comment by ghost** [comment]
> I need change the storage backend to support oracle , but i dont find related way,so i want change the source code .

it has been supported oracle?

**Comment by jorgheymans** [comment]
Oracle is not a supported storage option, there is a mysql storage option but it's not recommended for (high volume) production usage. See https://github.com/openzipkin/zipkin/tree/master/zipkin-storage if you want to explore making your own storage backend.

Apart from that, cloning and following the instructions here https://github.com/openzipkin/zipkin#running-the-server-from-source should give you a running server.

**Comment by ghost** [comment]
> e. See https://github.com/openzipkin/zipkin/tree/master/zipkin-storage if you want to explore making your own storage backend.

thanks for much
