### ISSUE TITLE
Zipkin UI shows blank page if endpoint serviceName is empty

### ISSUE THREAD

**Issue by ffahri** [openzipkin/zipkin#3097]
Zipkin UI shows blank page if we use an empty service name.

**How to reproduce**
Set an empty string for Zipkin.NewEndpoint function
```
zipkin.NewEndpoint("", "127.0.0.1:8080")
```

Chrome console output
```
react-dom.production.min.js:209 TypeError: Cannot read property 'map' of undefined
    at TracesTableRow.jsx:141
```

Maybe we can null check in this line? 
 https://github.com/openzipkin/zipkin/blob/master/zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableRow.jsx#L142

**Comment by codefromthecrypt** [comment]
dupe of #3072 I think. thanks for the hint.. if you are up to raising a PR with the fix and unit test, would be grand!

**Comment by ffahri** [comment]
Actually thats not happening on master branch, this error happens on :latest tag of openzipkin/zipkin image. 

Master branch and :master tag does no having this issue 🎉

**Comment by codefromthecrypt** [comment]
@ffahri thanks for the note.. not sure why the webhook didn't take, but I pushed our rebuild docker tag ( git push origin docker-2.21.3) so should ideally work in the next hour https://hub.docker.com/repository/registry-1.docker.io/openzipkin/zipkin/builds/47b1682b-90da-429c-bfd6-7769ee6dd470
