### ISSUE TITLE
cassandra issue

### ISSUE THREAD

**Issue by fulinlin924** [openzipkin/zipkin#310]
Zipkin runs on cassandra, but cannot find traces with any specified annotation. The cassandra is setup with zipkin-cassandra/src/schema/cassandra-schema.txt. Should any indexes be created?

**Comment by bmdhacks** [comment]
I think that's a known issue.  I haven't had time to look into it.

**Comment by fulinlin924** [comment]
The root cause is, in cassandra database, AnnotationsIndex stores RowKey with uppercase letters, but ServiceNames, ServiceNameIndex, SpanNames, ServiceSpanNameIndex use only lowercase letters.

There are two solution, one is AnnotationsIndex uses lowercase letters, the other solution is ServiceNames, ServiceNameIndex, SpanNames, ServiceSpanNameIndex NOT convert to lowercase. Which solution is preferred from your perspective? I can make the change and send a pull request.

**Comment by johanoskarsson** [comment]
Apologies for the slow reply on my part. Lowercasing the AnnotationsIndex would be fine by me.

Thanks!

/Johan

**Comment by theatrus** [comment]
Concur on lowercasing.
