### ISSUE TITLE
javascript console warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#3108]
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `GlobalSearchConditionList`. See https://fb.me/react-warning-keys for more information.
    in Styled(MuiBox) (at GlobalSearchConditionList.jsx:93)
    in GlobalSearchConditionList (at GlobalSearch.jsx:55)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at GlobalSearch.jsx:54)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at GlobalSearch.jsx:46)
    in GlobalSearch (created by Context.Consumer)
    in withRouter(GlobalSearch) (at DiscoverPage.jsx:272)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at DiscoverPage.jsx:270)
    in DiscoverPageContent (at DiscoverPage.jsx:323)
    in DiscoverPageImpl (created by Context.Consumer)
    in withRouter(DiscoverPageImpl) (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at App.jsx:51)
    in main (created by Styled(MuiBox))
    in Styled(MuiBox) (at Layout.jsx:132)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at Layout.jsx:85)
    in Layout (at App.jsx:50)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.jsx:49)
    in I18nProvider (at App.jsx:48)
    in Provider (at App.jsx:46)
    in ThemeProvider (at App.jsx:43)
    in MuiPickersUtilsProvider (at App.jsx:42)
    in UiConfig (at App.jsx:41)
    in Suspense (at App.jsx:40)
    in App (at src/index.tsx:21)

**Comment by codefromthecrypt** [comment]
NOTE: this is only visible in dev mode (ex npm start)

**Comment by tacigar** [comment]
This is resolved in #3076
