### ISSUE TITLE
UI Search Optimize 

### ISSUE THREAD

**Issue by lzhm** [openzipkin/zipkin#3110]
## Describe the Bug
1. How to change the sorting condition in the UI for the first time to the default **Newest** (default is longest ), I want to see the latest log.
2. Switch to Try Lens UI. Multiple queries, the latest record cannot be queried ,
You have to refresh the page to query the latest record, but the query condition disappears after the page is refreshed,but default Search UI  is not disappeared.
3. so I hope that the query condition is the default page, and the log detailed display will use Try Lens UI.

**Comment by codefromthecrypt** [comment]
hmm there's no more "Try Lens UI" button as lens is default. Can you validate you are running a recent version of zipkin?

**Comment by lzhm** [comment]
I run in windows os , so I use  zipkin-server-2.12.9-exec.jar ,from page 
 [ https://dl.bintray.com/openzipkin/maven/io/zipkin/java/zipkin-server](https://dl.bintray.com/openzipkin/maven/io/zipkin/java/zipkin-server/) , UI Search printscreen:
![z1](https://user-images.githubusercontent.com/7985398/83854970-031ef380-a74a-11ea-9a4f-3efdfb6e097d.png)
![z2](https://user-images.githubusercontent.com/7985398/83854978-05814d80-a74a-11ea-9e0d-e822f64c4500.png)

**Comment by codefromthecrypt** [comment]
I see. As a project we don't accept support requests on old versions as we can't re-release old versions anyway. If you update to latest you'll notice there's no question on this issue as lens is default. Do you mind giving a try?

**Comment by lzhm** [comment]
ok
