### ISSUE TITLE
Set fielddata=true on [localEndpoint.serviceName] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

### ISSUE THREAD

**Issue by heppytt** [openzipkin/zipkin#3149]
![image](https://user-images.githubusercontent.com/17058423/87876504-0ffe5a80-ca0b-11ea-95a5-bd19bdf6b591.png)
I used openzipkin / Zipkin 2.21.6 and es6.8.10.
i see https://github.com/openzipkin/zipkin/issues/2388 is not solve my question。

**Comment by codefromthecrypt** [comment]
Very likely the index template of elasticsearch conflicts with another template or somehow it did not install. 

you can check some comments here https://github.com/openzipkin/zipkin-support/issues/23#issuecomment-653547886

or you can join gitter for questions https://gitter.im/openzipkin/zipkin

good luck
