### ISSUE TITLE
fuzzy search traces by annotations

### ISSUE THREAD

**Issue by fulinlin924** [openzipkin/zipkin#315]
I'm wondering whether it is possible to support fuzzy query to find traces by an annotation. The annotation is now indexed and encoded in cassandra database, so currently the annotation must be literally matched. Is there any plan or idea to support fuzzy search? Thank you.

**Comment by bmdhacks** [comment]
Most of our storage backends don't really support it, so you'd probably have to write an alternate indexer to do this.  It might be interesting to use something like Elasticsearch for indexing and then proxy through to the actual storage layer.  Or use Elasticsearch for the whole thing.  We don't have any plans for any of this though.

**Comment by fulinlin924** [comment]
Thank you.

**Comment by codefromthecrypt** [comment]
old issue, but fyi elasticsearch is being implemented here: https://github.com/openzipkin/zipkin-java/pull/107
