### ISSUE TITLE
I can't finish the quickstart

### ISSUE THREAD

**Issue by zztztt** [openzipkin/zipkin#316]
$ bin/collector
[info] Loading project definition from /opt/zipkin/project
[warn] Multiple resolvers having different access mechanism configured with same name 'local'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Updating {file:/opt/zipkin/project/}default-fff2bb...
[info] Resolving com.github.spullara.mustache.java#compiler;0.8.12 ...
[error] Server access Error: Connection timed out url=http://maven.twttr.com/com/github/spullara/mustache/java/compiler/0.8.12/compiler-0.8.12.pom
[info] Resolving com.github.spullara.mustache.java#mustache.java;0.8.12 ...
[error] Server access Error: Connection timed out url=http://maven.twttr.com/com/github/spullara/mustache/java/mustache.java/0.8.12/mustache.java-0.8.12.pom
[error] Server access Error: Connection timed out url=http://maven.twttr.com/com/github/spullara/mustache/java/mustache.java/0.8.12/mustache.java-0.8.12.jar

**Comment by bmdhacks** [comment]
maven.twttr.com is blocked from China because Twitter is blocked from China.

**Comment by zztztt** [comment]
I can over the wall, I can access the http://maven.twttr.com/,but I can't find the http://maven.twttr.com/com/github/spullara/mustache/java/mustache.java/0.8.12... and more.
in the http://maven.twttr.com/com/github/.I can only see the "igor-petruk".

**Comment by mosesn** [comment]
It looks like mustache.java is on maven central.  Which version of sbt are
you using?

**Comment by zztztt** [comment]
> about
> [info] This is sbt 0.12.3
> [info] The current project is {file:/opt/zipkin/}zipkin
> [info] The current project is built against Scala 2.9.2
> [info] Available Plugins: com.twitter.scrooge.ScroogeSBT, ZipkinResolver, com.twitter.sbt.GitProject, com.twitter.sbt.PackageDist, com.twitter.sbt.BuildProperties
> [info] sbt, sbt plugins, and build definitions are using Scala 2.9.2
