### ISSUE TITLE
Support building Zipkin on ARM64

### ISSUE THREAD

**Issue by odidev** [openzipkin/zipkin#3166]
Hi Team,

I am interested in adding ARM64 support to Zipkin. 

There is an ‘elasticsearch’ binary for x86_64, getting downloaded in the RUN clause of the Dockerfile in zipkin/docker/storage/elasticsearch7/Dockerfile. The binary is available for aarch64 as well. I tried replacing the binary with aarch64, but build fails for zipkin-cassandra:2.21.5 docker image.

Please find my ARM64 job here : https://travis-ci.com/github/odidev/zipkin-1/jobs/368528378

Here is the failure logs : 
~~~
2020-08-05 06:53:00:414 [main] WARN zipkin2.storage.cassandra.v1.CassandraStorageExtension - Couldn't connect to docker image openzipkin/zipkin-cassandra:2.21.5: Assumption failed: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9042] Cannot connect))
~~~
I have checked in the docker hub <https://hub.docker.com/r/openzipkin/zipkin-cassandra/tags> that zipkin-cassandra is only available for LINUX/AMD64. 
I am suspecting that the further issues I am getting in the ARM64 build is due to zipkin-cassandra docker image unavailable for ARM64.
~~~
[ERROR]  HttpCallTest.wrongScheme:224
 
Expecting throwable message:
 <"not an SSL/TLS record: 485454502f312e31203430302042616420526571756573740d0a636f6e74656e742d747970653a20746578742f706c61696e3b20636861727365743d7574662d380d0a636f6e74656e742d6c656e6774683a2033310d0a7365727665723a2041726d657269612f302e39392e380d0a646174653a205468752c203330204a756c20323032302031353a35323a333720474d540d0a0d0a3430302042616420526571756573740a4465636f646572206661696c757265">
to contain:
 
 <"OPENSSL_internal">
 
but did not.
~~~
It would be really helpful if zipkin-cassandra docker image becomes available for LINUX/ARM64 platform as well. 
Please share your opinion on this.

**Comment by codefromthecrypt** [comment]
hi. how are you using this? what you are mentioning is a test image. what is your tracing setup use as it is odd to try multiple storage as typically end users only use one.

regardless does the main Cassandra docker image work on arm64? if not then probably try that first or reference back here how it is working upstream as this is only a dev copy.

**Comment by jorgheymans** [comment]
@odidev any progress your investigation ? Cassandra does have ARM64 docker images available.

**Comment by odidev** [comment]
@jorgheymans 
Yes, Cassandra does contain ARM64 support from version 3.11.0 and above. But Zipkin is using a zipkin-cassandra docker image, which is not available for ARM64. To build that docker image for ARM64, we would require Cassandra version 3.11.3 or above (Zipkin has a minimum cassandra version requirement of 3.11.3). However, I am able to successfully build a zipkin-cassandra docker image for ARM64 only with cassandra version 3.11.0. Higher versions of cassandra are showing below error:
~~~
ERROR [main] 2020-08-11 08:38:45,512 NativeLibraryLinux.java:64 - Failed to link the C library against JNA. Native methods will be unavailable.
java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna6661864102162995724.tmp: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /tmp/jna-3506402/jna6661864102162995724.tmp)
~~~
I have raised a JIRA in Cassandra for the ARM64 support in higher versions. Please find it here <https://issues.apache.org/jira/browse/CASSANDRA-16212#>

**Comment by codefromthecrypt** [comment]
dupe of #3141

Note cassandra is pinned to JDK 1.8 and we probably won't update that as it is a demo image...

**Comment by codefromthecrypt** [comment]
re-opened because this is more work than it seems. our builder images are at parity with our runtime. Unfortunately, ARM64 is not supported with musl, yet https://github.com/nodejs/node/blob/master/BUILDING.md

```
#10 1028. [INFO] Downloading https://unofficial-builds.nodejs.org/download/release/v12.18.4/node-v12.18.4-linux-arm64-musl.tar.gz to /root/.m2/repository/com/github/eirslett/node/12.18.4/node-12.18.4-linux-arm64-musl.tar.gz
--snip--
#10 1035. [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.2:install-node-and-npm (default-cli) on project zipkin-lens: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
```

This only works with amd64 at the moment until someone builds a variant we can download.

**Comment by codefromthecrypt** [comment]
a hint on this, when running tests, testcontainers runs docker for our storage tests (ex ITCassandraStorage). right now, the images are pointed to the last release which not multi-arch. after a successful green build on travis, you can swap these for :master tag. ex "openzipkin/zipkin-cassandra:2.21.7" -> "openzipkin/zipkin-cassandra:master"

if the arch doesn't have a working docker, tests might pass too quickly because it is ignoring the docker tests

**Comment by codefromthecrypt** [comment]
@odidev I temporarily blocked cassandra from trying to build on arm64 https://github.com/openzipkin/zipkin/commit/30bd4616b1bb92ede03c6d11e96351ff42330b32

It might be worth exploring if cassandra 4 also fails on arm. Reason is this is a test image anyway, we could possibly switch our cassandra to v4 if the protocol is compatible (eg ideally our java code doesn't change at all, only our docker image). If you have some time to try to update it, go for it. cc @openzipkin/cassandra

**Comment by odidev** [comment]
@adriancole 
Here is the further analysis after your PR for the basic ARM64 support is merged.

After deprecating test for “zipkin-cassandra” docker image, build is terminating for “zipkin-elasticsearch6”, “zipkin-elasticsearch7”, “zipkin-mysql”, “zipkin-kafka” docker images.
These images are available for Linux/AMD64, but not for Linux/ARM64. 
Below are the errored logs in brief:
~~~
2020-11-05 08:46:18:283 [main] ERROR 🐳 [ghcr.io/openzipkin/zipkin-mysql:2.22.1] - Log output from the failed container:
standard_init_linux.go:211: exec user process caused "exec format error"

2020-11-05 08:46:47:658 [main] ERROR 🐳 [ghcr.io/openzipkin/zipkin-elasticsearch7:2.22.1] - Could not start container
java.lang.IllegalStateException: Container did not start correctly.

2020-11-05 08:47:53:809 [main] ERROR 🐳 [ghcr.io/openzipkin/zipkin-elasticsearch6:2.22.1] - Log output from the failed container:
standard_init_linux.go:211: exec user process caused "exec format error"

2020-11-05 08:48:11:617 [main] ERROR 🐳 [ghcr.io/openzipkin/zipkin-kafka:2.22.1] - Could not start container
java.lang.IllegalStateException: Container did not start correctly.
~~~

I have tried building them on a local Linux/ARM64 machine. “zipkin-elasticsearch6”, “zipkin-mysql”, “zipkin-kafka” docker images are building successfully on the ARM64 platform. But “zipkin-elasticsearch7” fails to build on ARM64 because the Dockerfile is downloading an elasticsearch binary (with no jdk) from here  <https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.9.3-no-jdk-linux-x86_64.tar.gz>.  
This binary is not available for the AArch64 platform. However elasticsearch is releasing another binary for AArch64 (with jdk). Please find it here <https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.3-linux-aarch64.tar.gz>. 
“Zipkin-elasticsearch7” docker image is successfully getting built for ARM64 after using this binary for elasticsearch on a local ARM64 machine.

It will be really helpful if “zipkin-elasticsearch6”, “zipkin-mysql”, “zipkin-kafka” docker images become available for Linux/ARM64 on the zipkin Docker Hub.
Also, can you please suggest whether we can use elasticsearch binary (with jdk) for building “zipkin-elasticsearch7” docker image? If yes, then I can raise a PR for the ARM64 support in the Dockerfile used to build “zipkin-elasticsearch7” docker image.

**Comment by codefromthecrypt** [comment]
@odidev there was a problem in our build identified yesterday on the base layers. Can you re-try (re-pull as we re-pushed them yesterday)?

We don't use the JDK in Elasticsearch anymore so that part might be a distraction, as we are only using jars there correct, not OS binaries.

**Comment by codefromthecrypt** [comment]
also feel free to raise a work in progress PR, with GH action or travis config that adds CI.

Ex. I noticed the same thing you did about our images experimenting here

https://travis-ci.org/github/openzipkin/zipkin-reporter-java/builds/741595257

Then I put a sanity check in the travis config as initially our JRE as you mentioned was messed up.

Then I added this to the base image to fix the JRE https://github.com/openzipkin/docker-java/commit/8a47a19314bf02e60dadda0fa621d920431adf62

Then you notice in the above logs the java image works, but our reporter build runs, but still fails on rabbit, which I'll note in another issue (fail is silently as we use a assumption condition, but there's stuff in the logs)

**Comment by odidev** [comment]
@adriancole 

Thank you for releasing ARM64 docker images for “zipkin-mysql”, “zipkin-kafka”, “zipkin-elasticsearch6” and “zipkin-elasticsearch7”.
I have again forked zipkin and built it for arm64-graviton2 using Travis utility. Issues related to openzipkin docker images are now resolved. But the ARM64 job is terminating to start ryuk containers. Please find the error logs below:
~~~
2020-11-06 06:29:08:460 [testcontainers-ryuk] WARN org.testcontainers.utility.ResourceReaper - Can not connect to Ryuk at localhost:32769

2020-11-06 06:29:08:625 [main] ERROR org.testcontainers.utility.ResourceReaper - Timed out waiting for Ryuk container to start. Ryuk's logs:
standard_init_linux.go:211: exec user process caused "exec format error"
~~~

With reference to the comment in the issue <https://github.com/openzipkin/zipkin/issues/3279#issuecomment-722937650>,  RYUK does not contain ARM64 support:
>> arm64 won't work since we don't have ARM support in Ryuk (yet). You can disable it, but some other images may fail too

I have disabled RYUK as below:
~~~
export TESTCONTAINERS_RYUK_DISABLED=true
~~~
After disabling, ryuk does not bother anymore in arm64 logs, and both ARM64 and AMD64 jobs reach a common point, where both fail to decrypt gpg passphrase. Here are the error logs:
~~~
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project zipkin-parent: Unable to decrypt gpg passphrase: org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException: /home/travis/.m2/settings-security.xml (No such file or directory) -> [Help 1]
~~~
Please find the related error jobs here : <https://travis-ci.com/github/odidev/zipkin/jobs/429516679#L5780>

And when I skip maven-gpg-plugin in my forked repo, then both the jobs fail to deploy the artifacts, which is obvious because I do not possess the permissions for the deployment. Please find the error logs:
~~~
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project zipkin-server: Failed to deploy artifacts: Could not transfer artifact io.zipkin.zipkin2:zipkin:jar:2.22.3-20201106.071057-6 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Transfer failed for https://oss.sonatype.org/content/repositories/snapshots/io/zipkin/zipkin2/zipkin/2.22.3-SNAPSHOT/zipkin-2.22.3-20201106.071057-6.jar 401 Unauthorized -> [Help 1]
~~~
Please find the related error jobs here : <https://travis-ci.com/github/odidev/zipkin/jobs/429518136#L8423>

Please find my analysis below:

1. .travis.yml file : <https://github.com/odidev/zipkin/blob/master/.travis.yml#L74>
2. Travis-CI jobs : <https://travis-ci.com/github/odidev/zipkin/builds/198692829>

If you think we can disable the ryuk containers, then I will raise the PR with arm64-graviton2 jobs in the Travis. ‘arm64-graviton2’ makes use of a VM with dist: focal, and not Lxd containers.
Please share your opinion on this.

**Comment by codefromthecrypt** [comment]
Thanks for the research and looks good. I visually verified that the IT* for collector and storage are not skipping 👍 Notably, we also have a re-pushed an image for rabbit, and it is good to know that worked, too.

If we are using a special-cased matrix, maybe we should just run `./mvnw verify -nsu -DskipActuator` instead of the publish script, as we wouldn't want to dual-publish anyway. This will avoid any accidents.

ex. keeping comments like this:
```
  # verify runs both tests and integration tests (Docker tests included)
  # -DskipActuator ensures no tests rely on the actuator library
  ./mvnw verify -nsu -DskipActuator
```

> If you think we can disable the ryuk containers, then I will raise the PR with arm64-graviton2 jobs in the Travis.

Maybe link https://github.com/testcontainers/moby-ryuk/issues/15 in the comments and also see if you can use `~/.testcontainers.properties` Also good to note https://github.com/testcontainers/moby-ryuk/issues/16 as I forgot about ryuk (it is yet another docker hub pull until this is resolved)

> ‘arm64-graviton2’ makes use of a VM with dist: focal, and not Lxd containers.

I think we'd want to use arm64, not graviton in our build. We are running off https://travis-ci.org/ and our goal is arm64, not specifically using graviton to do this. If we ever migrate to travis.com it should be decoupled from using arm (ex move to arm then maybe migrate). Migrating yet another build tool is probably too much right now, as personally I've spent the last entire month on the build and various pro/cons discussions.. Don't really want to research and champion another cause.

Despite the changes here being something I could easily pop into the build now, definitely prefer you doing the honors, since you did all the research. Much appreciated!

If following this, you'd like to make our github integrated docker tests a build matrix of arm64 that would be cool, as that actually tests the zipkin images we build continue to work (before we release them).

**Comment by codefromthecrypt** [comment]
fyi https://github.com/openzipkin/zipkin-reporter-java/pull/192

**Comment by codefromthecrypt** [comment]
and https://github.com/openzipkin/brave/pull/1277

I'll make the testcontainers changes here directly independent of arm64 as I didn't realize we were pulling images until this topic.

**Comment by codefromthecrypt** [comment]
#3290 will make finishing this up easy I think. go for it when ready

**Comment by codefromthecrypt** [comment]
hmm regardless of independent topic or not, I missed the memo. It looks like Travis is shutting down .org https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom so might as well get in front of this (like it or not!) cc @openzipkin/core 

@odidev I'll transfer this repo and the others to travis-ci.com

**Comment by codefromthecrypt** [comment]
@odidev so I noticed you said "‘arm64-graviton2’ makes use of a VM with dist: focal, and not Lxd containers."

I noticed that setting up an LXD matrix job with arm64-graviton2 fails unexpectedly (boot cycling), but it isn't documented as unsupported either.. https://docs.travis-ci.com/user/reference/overview/

Is there some document somewhere that notes arm64-graviton2 as LXD only? The boot time is a bigger deal in most of our projects vs execution speed, as boot delays are often several minutes and execution times often a minute or two.

cc @anuraaga

**Comment by odidev** [comment]
@adriancole 
I have raised the PR to add the ARM64 job to Travis-CI.
>> I noticed that setting up an LXD matrix job with arm64-graviton2 fails unexpectedly (boot cycling), but it isn't documented as unsupported either.. https://docs.travis-ci.com/user/reference/overview/

Graviton is available for travis.com only, not travis.org. Graviton can be used with both LXD and VM. With ‘virt: vm’, we can only specify ‘dist: focal’; and ‘virt: lxd’ goes with these three dist: ‘focal’, ‘xenial’, ‘bionic’.

**Ex: ‘with VM’**
~~~    
virt: vm
group: edge
arch: arm64-graviton2
os: linux
dist: focal
~~~


**Ex: ‘with LXD’**
~~~    
virt: lxd
group: edge
arch: arm64-graviton2
os: linux
dist: focal    // or ‘dist: bionic’ or ‘dist: xenial’
~~~

**Comment by codefromthecrypt** [comment]
@odidev thanks I'll copy you on any next fail.. it was just odd because I tried to setup a matrix and it was flipping out (graviton never passed it just kept cycling on boot). I *didn't* add `group: edge` though

**Comment by codefromthecrypt** [comment]
PS I've tried in a couple different repos, and LXD graviton is on a reboot cycle.. we can try again later in the year or if you want to raise an issue with them, go ahead..

Ex. from brave-cassandra
```diff
diff --git a/.travis.yml b/.travis.yml
index f8c9232..8b3d929 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,11 +1,10 @@
 # Run `travis lint` when changing this file to avoid breaking the build.
 
 # See https://docs.travis-ci.com/user/reference/overview/#for-a-particular-travisyml-configuration
-arch: arm64-graviton2 # Use AWS Graviton2
-group: edge           # Required with arm64-graviton2 per https://blog.travis-ci.com/2020-09-11-arm-on-aws
-virt: lxd             # LXD containers where possible as they boot much faster than full VMs
-os: linux             # required for arch different than amd64
-dist: focal           # newest available distribution
+arch: arm64 # Can't use arm64-graviton2 as it cycles on boot as of 2020-11-02
+virt: lxd   # LXD containers where possible as they boot much faster than full VMs
+os: linux   # required for arch different than amd64
+dist: focal # newest available distribution
 
 # license-maven-plugin needs the full history to generate copyright year range. Ex. 2013-2020
 # Don't do a shallow clone, as it interferes with this.
```

![looper](https://user-images.githubusercontent.com/64215/98610927-c6c07680-232b-11eb-939f-df4a6abeb53a.gif)

**Comment by codefromthecrypt** [comment]
incidentally, left alone long enough the graviton2 LXD build eventually booted.. however, it took so long it is still not a viable configuration.. perhaps there aren't that many free nodes available. anyway it is good to know it is possible, even if not yet viable, to use graviton2 LXD

EOF!
