### ISSUE TITLE
Requirement Zipkin setup on linux machine

### ISSUE THREAD

**Issue by prashantnitt07** [openzipkin/zipkin#3174]
please share the document or guide for instrument zipkin on linux machine.

I have starting new project for zipkin

**Comment by prashantnitt07** [comment]
Team , please help for new setup

**Comment by prashantnitt07** [comment]
zipkin has setup has ready 

i want to integrate with java

**Comment by jorgheymans** [comment]
Please drop by on gitter for things like this https://gitter.im/openzipkin/zipkin.
