### ISSUE TITLE
How to register zipkin server to eureka

### ISSUE THREAD

**Issue by littlekelvin** [openzipkin/zipkin#3190]
Follow zipkin usage, recommend to run a zipkin server with a jar.
`$ curl -sSL https://zipkin.io/quickstart.sh | bash -s
$ java -jar zipkin.jar`

But this way, the zipkin server is out of eureka server. How should I register the zipkin server to euraka.

**Comment by jorgheymans** [comment]
Some options are explained here https://github.com/openzipkin/zipkin/issues/1870, currently it's not supported out of the box.
