### ISSUE TITLE
Show new lines in UI

### ISSUE THREAD

**Issue by fredy-virguez-adl** [openzipkin/zipkin#3195]
**Feature:**
Add 'white-space: pre-line' or equivalent style to show new lines in tagged information.

**Rational**
In previous version new lines were shown, this allow users to read easily the multiline tagged information.

**Example Scenario**
Reading multiline tagged information

**Prior Art**
![image](https://user-images.githubusercontent.com/45631796/91884813-57077e80-ec4c-11ea-988c-54728feba27d.png)

![image](https://user-images.githubusercontent.com/45631796/91884649-0e4fc580-ec4c-11ea-93f1-2d8e3bf12443.png)

**Comment by codefromthecrypt** [comment]
do you want to go ahead and make this change? seems legit

**Comment by fredy-virguez-adl** [comment]
Ok, can you add me as a contributor? please

**Comment by jcchavezs** [comment]
The usual workflow is that you fork the repo and then submit a PR. Could
you do that please?

**Comment by fredy-virguez-adl** [comment]
Done. This is the PR https://github.com/openzipkin/zipkin/pull/3196

But travis-ci check is failing for not related reason.
