### ISSUE TITLE
How to fix inconsistent time or time-zone settings

### ISSUE THREAD

**Issue by fulinlin924** [openzipkin/zipkin#320]
There are 4 services deployed on different servers, and those servers may have inconsistent time. As shown in the attached image, the WEB server has 5 minutes intervals compared with other servers. Is there any suggestion to fix this issue? Currently, for each server, a cron job is setup to periodically sync date with time server.

Another question is how to handle time-zone. Those server may located in different sites around the world. It seems that the timestamp of annotation doesn't have time-zone info.

Thank you.

![screen shot 2013-12-19 at 11 16 26 am](https://f.cloud.github.com/assets/5575667/1779979/70dcad0a-685d-11e3-8d58-fd99cbf0d129.png)

**Comment by fulinlin924** [comment]
Is this the desired solution: all services convert the date to a fixed time zone, such as UTC+00:00 time zone, and then store the long-type date (e.g. 1387443073166000) into the database.

**Comment by johanoskarsson** [comment]
The standard approach to this is to have all servers on UTC time and ntpd running to sync the times. We do try to "rejig" the times during display as best we can, but the assumption made is that the servers are reasonably in sync.
