### ISSUE TITLE
Empty trace list despite matches

### ISSUE THREAD

**Issue by AlexandreCassagne** [openzipkin/zipkin#3211]
## Describe the Bug

The UI (see screenshot) does not display any spans, even though there are some search results.

<img width="1439" alt="Screenshot of Interface" src="https://user-images.githubusercontent.com/541043/93616826-3d339e80-f9a3-11ea-852a-2aa6ff1e17b4.png">

In fact, the following JSON is returned by the Zipkin backend when I inspect the network requests:

<img width="1440" alt="Network Requests for https://***/zipkin/api/v2/traces?endTs=1600443528732&limit=10&lookback=900000" src="https://user-images.githubusercontent.com/541043/93617164-9f8c9f00-f9a3-11ea-94b3-f37570f7d5a7.png">

```json
[[{
    "traceId": "9e8189bd08e4493c",
    "id": "9e8189bd08e4493c",
    "name": "rxjava",
    "timestamp": 1600443526950815,
    "duration": 111,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}], [{
    "traceId": "af4b1f57aff1be73",
    "id": "af4b1f57aff1be73",
    "name": "rxjava",
    "timestamp": 1600443525451017,
    "duration": 106,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}], [{
    "traceId": "dfe4e47cf3ce99b2",
    "id": "dfe4e47cf3ce99b2",
    "name": "rxjava",
    "timestamp": 1600443525951231,
    "duration": 84,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}], [{
    "traceId": "0490f0c3a01ff5dd",
    "id": "0490f0c3a01ff5dd",
    "name": "rxjava",
    "timestamp": 1600443524450494,
    "duration": 94,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}], [{
    "traceId": "0734dc2ed65857fd",
    "id": "0734dc2ed65857fd",
    "name": "rxjava",
    "timestamp": 1600443527951278,
    "duration": 158,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}], [{
    "traceId": "1013644077ac0343",
    "id": "1013644077ac0343",
    "name": "rxjava",
    "timestamp": 1600443526450430,
    "duration": 109,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}], [{
    "traceId": "1e5a32410a5163fe",
    "id": "1e5a32410a5163fe",
    "name": "rxjava",
    "timestamp": 1600443524950742,
    "duration": 99,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}], [{
    "traceId": "26ecb5641540a59c",
    "id": "26ecb5641540a59c",
    "kind": "SERVER",
    "name": "get /**",
    "timestamp": 1600443526083376,
    "duration": 2207,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "remoteEndpoint": {
        "ipv4": "35.199.77.186"
    },
    "tags": {
        "http.method": "GET",
        "http.path": "/",
        "mvc.controller.class": "ResourceHttpRequestHandler"
    }
}], [{
    "traceId": "376e9201cc15f3e3",
    "id": "376e9201cc15f3e3",
    "name": "rxjava",
    "timestamp": 1600443523951278,
    "duration": 120,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}], [{
    "traceId": "5f2c0aa9171388cb",
    "id": "5f2c0aa9171388cb",
    "name": "rxjava",
    "timestamp": 1600443527451075,
    "duration": 95,
    "localEndpoint": {
        "serviceName": "gateway",
        "ipv4": "10.8.2.4"
    },
    "tags": {
        "thread": "RxIoScheduler-2"
    }
}]]
```

## Steps to Reproduce

- Deployed OpenZipkin docker image (latest as of september 18th 2020) in Kubernetes with a MySQL storage;
- Open the Zipkin UI;
- Click the "search" icon. Here, a limit of 10 is set and no filters, but any combination yields the same result.

## Expected Behaviour

The expected behaviour is that the traces are displayed correctly.

**Comment by codefromthecrypt** [comment]
Interesting.. the traces are all, single-span non-remote traces. Even though they are probably a bug (ex I have seen this when people made a mistake in trace configuration), I agree they should show up.

Can you try the :master tag of the docker image in case it isn't an issue there?

**Comment by AlexandreCassagne** [comment]
@adriancole that's surprising, I think my configuration is pretty much vanilla Spring Sleuth / Zipkin. I'll review that, could you give me an idea of what seems to be missing from my spans?

Also, I will be testing that image and sending the results this weekend.

**Comment by codefromthecrypt** [comment]
you can ask in sleuth to update the skip pattern maybe? spring.sleuth.rxjava.schedulers.ignoredthreads possibly you are using a different rxjava version than it knows to ignore :)

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/docs/src/main/asciidoc/_configprops.adoc

**Comment by AlexandreCassagne** [comment]
I can confirm the :master image does not fix this issue! I'm about to test making the changes you suggested, though as you said, this should work nonetheless

**Comment by DriesCleymans** [comment]
I'm running into the same problem. I run several spring boot services, and trying to send the logging to a OpenZipkin-slim docker image.

The services include these dependencies (from Hoxton.SR5):
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>
		
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-zipkin</artifactId>
</dependency>
```

With these extra configuration for the services:
```
spring:
  zipkin:
    enabled: true
    baseUrl: 
      http://MYSERVER:9411
  sleuth:
    enabled: true 
    sampler:
      probability: 1.0
```

When i open the Zipkin UI, i get no trace list, but filters are filled in.

Tracing the data fetched from zipkin ui when doing a default search for 10 results:
```
[
	[{
		"traceId": "cbe819c58beab32e",
		"id": "cbe819c58beab32e",
		"name": "rxjava",
		"timestamp": 1601651584843001,
		"duration": 438,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "70c17845702ad059",
		"id": "70c17845702ad059",
		"name": "rxjava",
		"timestamp": 1601651584344001,
		"duration": 438,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "bf74190c6004f726",
		"id": "bf74190c6004f726",
		"name": "rxjava",
		"timestamp": 1601651583844001,
		"duration": 447,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "c522a071490ae94a",
		"id": "c522a071490ae94a",
		"name": "rxjava",
		"timestamp": 1601651583343001,
		"duration": 446,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "41b70af2492bca74",
		"id": "41b70af2492bca74",
		"name": "rxjava",
		"timestamp": 1601651582843002,
		"duration": 448,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "b54b5930f772101c",
		"id": "b54b5930f772101c",
		"name": "rxjava",
		"timestamp": 1601651582344001,
		"duration": 442,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "66714b77e3b735ee",
		"id": "66714b77e3b735ee",
		"name": "rxjava",
		"timestamp": 1601651581843001,
		"duration": 462,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "aab769fefa639e54",
		"id": "aab769fefa639e54",
		"name": "rxjava",
		"timestamp": 1601651581343001,
		"duration": 478,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "c34d42aff90f124e",
		"id": "c34d42aff90f124e",
		"name": "rxjava",
		"timestamp": 1601651580844001,
		"duration": 481,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}],
	[{
		"traceId": "ba76bd503317443a",
		"id": "ba76bd503317443a",
		"name": "rxjava",
		"timestamp": 1601651580343001,
		"duration": 462,
		"localEndpoint": {
			"serviceName": "t4-zuul-server"
		},
		"tags": {
			"thread": "RxIoScheduler-4"
		}
	}]
]
```

**Comment by DriesCleymans** [comment]
It looks like this is a problem with safari (I'm using Mac).

When the same page is opened in chrome, all the data is there.

By looking at the source code of the generated html page in safari, i noticed that the data and the elements are all there, they are just not showing up.

**Comment by codefromthecrypt** [comment]
Summary: in this cases, there is a missing exclude (you can check the sleuth issue list) resulting in junk single-span traces. It is true the UI should show them anyway, but there is enough information to solve this now, thanks.

Help wanted! this is a volunteer run project.

At any rate, I highly suggest looking at docs and/or raising an issue with sleuth so that these junk traces don't pollute your data store and UI, once the UI is fixed to show them

**Comment by codefromthecrypt** [comment]
sorry @DriesCleymans I misread your input as I read the older message. Your analysis is quite helpful and can allow this to be narrowed down quicker.  We don't have browser tests on safari, so would need to catch this manually I suppose.

**Comment by AlexandreCassagne** [comment]
I can confirm that changing the browser to Chrome fixes the issue. I also removed the single span traces and see the empty list, so I believe that this issue goes beyond single span traces. Finally, and maybe this should be a separate issue, the dependencies suffer from the same problem.

**Comment by codefromthecrypt** [comment]
@tacigar do you have a chance to check this?

**Comment by codefromthecrypt** [comment]
@tacigar do you have a moment to look into this? when there are traces that only include a single span, in safari they do not show up while in chrome they do

**Comment by codefromthecrypt** [comment]
@seedarren @AlexandreCassagne can you please try the docker image openzipkin/zipkin:master? I verified it fixes the issue.

**Comment by AlexandreCassagne** [comment]
@adriancole I can confirm the image seems to work on Safari. Although, dependencies that show up in Chrome do not show up in Safari (similar issue?)

**Comment by codefromthecrypt** [comment]
eesh ;)

**Comment by codefromthecrypt** [comment]
@AlexandreCassagne single span traces shouldn't show up as dependencies anyway. dependency link requires 2 services. can you open another issue with test data on what you see is missing?

**Comment by codefromthecrypt** [comment]
@AlexandreCassagne nag :P you can try ghcr.io/openzipkin/zipkin:master just in case a dependency bump fixed the.. dependency issue. otherwise please raise an issue with the test data and browser it fails on

**Comment by codefromthecrypt** [comment]
assuming there are 2 spans :D to form a link :P
