### ISSUE TITLE
inline replace @git.commit.id.abbrev@ in CI instead of relying on .git

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#3224]
The .git folder on a default clone copies 77MB into the Docker context. We only need it for the git-commit-id-plugin, which replaces `@git.commit.id.abbrev@` in a couple files in the zipkin-server directory.

If you don't have the .git folder the replacement fails silently and the server console looks like this:
```
:: version 2.21.8-SNAPSHOT :: commit @git.commit.id.abbrev@ ::
```

Instead of this:
```
:: version 2.21.8-SNAPSHOT :: commit ef5f838 ::
```

We definitely want the git SHA, but in CI, we should be able to get it another way. If we had it, we could replace `@git.commit.id.abbrev@` using `sed` instead, and no longer need the massive `.git` directory in our docker context.

When this issue is finished, `!.git` will no longer be in the `.dockerignore` file

**Comment by jcchavezs** [comment]
Yeah, definitively a good optimization.

**Comment by codefromthecrypt** [comment]
found a less engineering way, considering dockerhub defaults to shallow clones per https://docs.docker.com/docker-hub/builds/advanced/#source-repository--branch-clones

https://github.com/openzipkin/zipkin/pull/3227
