### ISSUE TITLE
Zipkin UI Always Show Empty Result

### ISSUE THREAD

**Issue by seedarren** [openzipkin/zipkin#3237]
## Describe the Bug
I setup zipkin with cassandra3 as storage type, it seems that the zipkin UI always display empty result, however it seems that the total results is more than zero as highlighted in yellow color in the screenshot below

![image](https://user-images.githubusercontent.com/32858519/96082789-77368880-0eee-11eb-85bb-2543848a3ff8.png)

## Expected Behaviour
Zipkin UI should display list of trace results

**Comment by codefromthecrypt** [comment]
can you paste the results of the endpoint `/api/v2/traces`?

**Comment by seedarren** [comment]
Hi,

Here the result:

`[[{"traceId":"07a076b27007a218","id":"07a076b27007a218","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742059538012,"duration":4605,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":35308},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"090065cbff4d2384","id":"090065cbff4d2384","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742059938012,"duration":2096,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":47804},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"648317c7e7ef32d7","id":"648317c7e7ef32d7","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742059638012,"duration":2668,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":47758},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"6af8da6585355642","id":"6af8da6585355642","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742060138015,"duration":2249,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":35362},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"7aefd9de831c7241","id":"7aefd9de831c7241","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742059738010,"duration":1638,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":47698},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"99ada91025884d58","id":"99ada91025884d58","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742059538007,"duration":2794,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":47780},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"b72c58f09737b121","id":"b72c58f09737b121","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742060038015,"duration":3341,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":47814},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"b821c1e6ee2fec9e","id":"b821c1e6ee2fec9e","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742059238010,"duration":3452,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":47722},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"e7a066e36a6dfb08","id":"e7a066e36a6dfb08","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742059838011,"duration":1983,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":47794},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}],[{"traceId":"fc9645a39e2250ab","id":"fc9645a39e2250ab","kind":"SERVER","name":"get /api/merchant-transactions","timestamp":1602742059438012,"duration":4880,"localEndpoint":{"serviceName":"abo-main","ipv4":"192.168.225.121"},"remoteEndpoint":{"ipv4":"192.168.178.0","port":35294},"tags":{"http.method":"GET","http.path":"/api/merchant-transactions","mvc.controller.class":"MerchantTransactionServiceProxy","mvc.controller.method":"findOneMerchantTransaction"}}]]`

**Comment by codefromthecrypt** [comment]
this is a duplicate of #3211, so please track that issue
