### ISSUE TITLE
Add Query / UI support for traces with multiple parent spans

### ISSUE THREAD

**Issue by hoxworth** [openzipkin/zipkin#324]
While instrumenting a number of distributed services recently to enable end to end tracing, I ran into a snag: zipkin's UI seems to only support displaying a single span that lacks a parent ID in a trace. 

My services are all guaranteed to receive a unique ID which the trace ID is based off of, but services that read from a queue are not dependent on an invocation from a parent service, and thus start their own new spans. This introduces multiple spans in a trace that do not have parent IDs, which the zipkin UI (and possibly query engine) cannot handle currently.

Yes, I could possibly pass a parent ID along in the message queue, but the services are logically separated; this just seems like a hack.

**Comment by bmdhacks** [comment]
Yeah, this is related to other issues where some work unit will get enqueued to be executed later, such as a web submission that spawns (or contributes to) a hadoop job an hour later.  It would be nice to link individual traces together if they are related.

**Comment by jorgheymans** [comment]
This is an older issue relating to zipkin classic. Nevertheless i verified that Lens, the new UI, is able to handle such spans and it does. I took the yelp test trace https://github.com/openzipkin/zipkin/blob/master/zipkin-lens/testdata/yelp.json and modified both mysql spans to have no parent. 

![image](https://user-images.githubusercontent.com/193792/79500161-4f906180-802c-11ea-850f-3ae96d931fbe.png)

In any case, tracing over messaging systems is very well supported in brave nowadays so it would be more natural to let the trace continue over the broker into the consumer.
