### ISSUE TITLE
Zipkin ElasticSearch module didn't create timestamp_millis field for version 2.21.7

### ISSUE THREAD

**Issue by shiyishuoshuo** [openzipkin/zipkin#3247]
I am using zipkin Elasticsearch library to create a new zipkin server for our company usage and I am using version 2.21.7 version and in 2016 for ticket #1209, we already define a method called prefixWithTimestampMillis in ElasticsearchSpanConsumer.java for creating a date field "timestamp_mills" and this is very convenient for creating event-based Kibana dashboard, but for this version 2.21.7, this method was gone and the timestamp for each span again turns to epoch_millis, do you why we remove this method?

**Comment by codefromthecrypt** [comment]
As far as I can tell, we still write that field when used as designed.

```java
  static void addSearchFields(Span span, JsonGenerator writer) throws IOException {
    long timestampMillis = span.timestampAsLong() / 1000L;
    if (timestampMillis != 0L) writer.writeNumberField("timestamp_millis", timestampMillis);
```

To answer you directly, our storage implementations are considered internal (ElasticsearchSpanConsumer being package private double-downs on this). Among many things, this allows us to upgrade libraries whenever we need to.

Anyone using the storage (or collector) libraries directly should watch for drift, in other words. The only library with compatibility guarantees is the core library.

**Comment by shiyishuoshuo** [comment]
but timestamp_millis was still a type of number instead of Date in Kibana, do you know how to resolve this issue?

**Comment by shiyishuoshuo** [comment]
@adriancole 

timestamp_millis | number
-- | --

and also I checked mapping when zipkin index created and seems like the type was defined as long instead of Date

"timestamp_millis": {
            "type": "long"
          },

posting below mapping for our use case:

{
  "zipkin:span-2020-11-19": {
    "mappings": {
      "span": {
        "properties": {
          "_q": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "annotations": {
            "type": "object"
          },
          "duration": {
            "type": "long"
          },
          "id": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "kind": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "localEndpoint": {
            "properties": {
              "serviceName": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          },
          "name": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "remoteEndpoint": {
            "properties": {
              "ipv4": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "port": {
                "type": "long"
              }
            }
          },
          "tags": {
            "properties": {
              "env": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "error": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "http": {
                "properties": {
                  "status_code": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  }
                }
              },
              "mvc": {
                "properties": {
                  "controller": {
                    "properties": {
                      "class": {
                        "type": "text",
                        "fields": {
                          "keyword": {
                            "type": "keyword",
                            "ignore_above": 256
                          }
                        }
                      },
                      "method": {
                        "type": "text",
                        "fields": {
                          "keyword": {
                            "type": "keyword",
                            "ignore_above": 256
                          }
                        }
                      }
                    }
                  }
                }
              },
              "userName": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          },
          "timestamp": {
            "type": "long"
          },
          "timestamp_millis": {
            "type": "long"
          },
          "traceId": {
            "type": "keyword"
          }
        }
      }
    }
  }
}

**Comment by codefromthecrypt** [comment]
millis as a numeric field is common and kibana should be ok with it. https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html

we are past zipkin-specific questions at this point. if you are having trouble with ES or kibana, check out their forums.
