### ISSUE TITLE
Find a replacement for "rabbitmq:3.8-management-alpine"

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#3279]
"rabbitmq:3.8-management-alpine" used by RabbitMQCollectorRule is a docker hub registry image, which means each time a pull request runs potentially, this decrements a count and possibly can cause a build outage.

Can someone help find a replacement registry for it? ex in ghcr.io, gcr.io or quay? possibly we can layer it on our own image... not sure how complex it is.

cc @shakuzen @making @bsideup

**Comment by codefromthecrypt** [comment]
I've temporarily pushed a mirror to our github registry

```Dockerfile
ARG version=3.8.9
ARG image=rabbitmq:$version-management-alpine
FROM $image
LABEL org.opencontainers.image.description="Internal to Zipkin. Do not use in production. Mirror of $image as no alternate registry to docker.io is known, yet. See #3279"
LABEL org.opencontainers.image.source=https://github.com/docker-library/rabbitmq
LABEL org.opencontainers.image.version=$version
```

```bash
$ docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/openzipkin/rabbitmq-management-alpine:latest --push .
```

**Comment by codefromthecrypt** [comment]
ps ran across and chatted with @anuraaga about the implicit mirror by google here https://cloud.google.com/container-registry/docs/pulling-cached-images

This is probably good to add to the build, to reduce the chance of someone's pull request that switches our image to a normal one killing our account. However, it won't prevent docker hub pulls as it is only caching what it considers frequently requested images, and we have no control over that.

**Comment by codefromthecrypt** [comment]
Our code uses this image: `ghcr.io/openzipkin/rabbitmq-management-alpine:latest` which we mirrored from https://hub.docker.com/layers/rabbitmq/library/rabbitmq/3.8.9-management-alpine, but even switching to that gives an error in arm64

```
at java.base/java.lang.Thread.run(Thread.java:834)

10:13:07.175 [main] ERROR o.t.utility.ResourceReaper - Timed out waiting for Ryuk container to start. Ryuk's logs:

standard_init_linux.go:211: exec user process caused "exec format error"
```

I wonder if rabbit's image is busted, or if somehow it is being misinterpreted. Only thing I notice is that the arch mentioned here is linux/arm64/v8 not linux/arm64, but then again travis slaves are v8. 

cc @odidev

**Comment by bsideup** [comment]
arm64 won't work since we don't have ARM support in Ryuk (yet). You can disable it, but some other images may fail too

**Comment by codefromthecrypt** [comment]
ack it was indeed ryuk. We have a workaround here. there's no problem with the rabbitmq image we are using, though it would be nice to have an official one not in docker.io https://github.com/openzipkin/zipkin/pull/3290
