### ISSUE TITLE
dependencies didn't show anything when using elasticsearch storage

### ISSUE THREAD

**Issue by RexChengZhu** [openzipkin/zipkin#3308]
hi . i'm using zipkin-2.22.1 version and found the dependencies always empty . i can see data in trace. 
here is my running script java -jar zipkin-server-2.22.1-exec.jar --STORAGE_TYPE=elasticsearch --ESHOSTS=...... --KAFKA_BOOTSTRAP_SERVERS=......
and when i remove the STORAGET_TYPE and ESHOSTS . using in memory mode . i can see the dependencies

**Comment by jorgheymans** [comment]
You need to setup a spark job for this https://github.com/openzipkin/zipkin-dependencies
