### ISSUE TITLE
bad request when using maxDuration or minDuration search condition

### ISSUE THREAD

**Issue by RexChengZhu** [openzipkin/zipkin#3309]
the zipkin version is 2.22.1. other query conditions were fine. just duration return code 400

**Comment by codefromthecrypt** [comment]
should be better than 400.. no error is shown? there is a constraint between the two https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml#L115-L126

**Comment by RexChengZhu** [comment]
i try it again . only maxDuration response 400 . minDuration works for me ...
