### ISSUE TITLE
Cannot send trace to ElasticSearch 7.9 

### ISSUE THREAD

**Issue by Filippo125** [openzipkin/zipkin#3331]
## Describe the Bug
The version 2.23.1 cannot send data to ElasticSearch version 7.9

The log is:
`Dec 23 08:35:47 localhost java[65500]: 2020-12-23 08:35:47.945  WARN [/] 65500 --- [ing-tasks-1-207] z.s.i.BodyIsExceptionMessage             : Unexpected error handling req
Dec 23 08:35:47 localhost java[65500]: java.lang.NullPointerException: null
Dec 23 08:35:47 localhost java[65500]: at zipkin2.server.internal.elasticsearch.InitialEndpointSupplier.get(InitialEndpointSupplier.java:61) ~[classes!/:?]
Dec 23 08:35:47 localhost java[65500]: at zipkin2.server.internal.elasticsearch.InitialEndpointSupplier.get(InitialEndpointSupplier.java:28) ~[classes!/:?]
Dec 23 08:35:47 localhost java[65500]: at zipkin2.server.internal.elasticsearch.LazyHttpClientImpl.getEndpoint(LazyHttpClientImpl.java:60) ~[classes!/:?]
Dec 23 08:35:47 localhost java[65500]: at zipkin2.server.internal.elasticsearch.LazyHttpClientImpl.get(LazyHttpClientImpl.java:52) ~[classes!/:?]
Dec 23 08:35:47 localhost java[65500]: at zipkin2.elasticsearch.ElasticsearchStorage.http(ElasticsearchStorage.java:387) ~[zipkin-storage-elasticsearch-2.23.1.jar!/:?]
Dec 23 08:35:47 localhost java[65500]: at zipkin2.elasticsearch.AutoValue_ElasticsearchStorage.http(AutoValue_ElasticsearchStorage.java:43) ~[zipkin-storage-elasticsearch-2.
Dec 23 08:35:47 localhost java[65500]: at zipkin2.elasticsearch.ElasticsearchStorage.doEnsureIndexTemplates(ElasticsearchStorage.java:334) ~[zipkin-storage-elasticsearch-2.2
Dec 23 08:35:47 localhost java[65500]: at zipkin2.elasticsearch.ElasticsearchStorage.ensureIndexTemplates(ElasticsearchStorage.java:327) ~[zipkin-storage-elasticsearch-2.23.
Dec 23 08:35:47 localhost java[65500]: at zipkin2.elasticsearch.ElasticsearchStorage.spanStore(ElasticsearchStorage.java:228) ~[zipkin-storage-elasticsearch-2.23.1.jar!/:?]
Dec 23 08:35:47 localhost java[65500]: at zipkin2.server.internal.ZipkinQueryApiV2.getTraces(ZipkinQueryApiV2.java:147) ~[classes!/:?]
Dec 23 08:35:47 localhost java[65500]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:331) ~[armeria-1.3.0.jar!/:?]
Dec 23 08:35:47 localhost java[65500]: at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$6(AnnotatedService.java:306) ~[armeria-1.3.0.jar!/:?
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:502) ~[armeria-1.3.0.jar!/:?]
Dec 23 08:35:47 localhost java[65500]: at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44) [micrometer-core-1.6.1.jar!/:1.6.1]
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
Dec 23 08:35:47 localhost java[65500]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.54.Final.jar!/:4.1.54.Final
Dec 23 08:35:47 localhost java[65500]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]`

## Steps to Reproduce
Use elasticsearch 7.9 and zipkin 2.23.1 
## Expected Behaviour
Can use elasticsearch 7.9 as backend

**Comment by codefromthecrypt** [comment]
This looks like a parsing failure. What is value of ES_HOSTS you are using?

This is the line that fails.. only sensible explanation is the host part was null
```
      if (isIpAddress(host) || host.equals("localhost")) {
```

**Comment by codefromthecrypt** [comment]
It looks like there was possibly a blank entry. in JRE 15, it will say what was null in cases like this.

```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "host" is null

	at zipkin2.server.internal.elasticsearch.InitialEndpointSupplier.get(InitialEndpointSupplier.java:61)
```

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/3332

**Comment by codefromthecrypt** [comment]
as our tests run with ES 7.9 I think this is mostly about input failure of some kind.
