### ISSUE TITLE
When I request repeatedly, more and more span will be generated

### ISSUE THREAD

**Issue by wusuobuzai** [openzipkin/zipkin#3344]
![image](https://user-images.githubusercontent.com/36450583/110242785-88159280-7f92-11eb-8db8-d5697e2eb860.png)
request is gateway->JOOLUN-MEAL-API->JOOLUN-BASE-API
When I request repeatedly,more and more “JOOLUN-MEAL-API” will be generated
Many of the following span are useless requests “JOOLUN-MEAL-API”

**Comment by jorgheymans** [comment]
This seems more of a https://github.com/Joolun issue, please check with them.
