### ISSUE TITLE
Helm chart for zipkin

### ISSUE THREAD

**Issue by jonkerj** [openzipkin/zipkin#3374]
## Feature
A helm chart to deploy zipkin on Kubernetes, maintained by the openzipkin community. Helm charts are a (very) common means to install software on Kubernetes. There are a couple of charts for zipkin floating around, but (warning, opions ahead) none of them is official + up to date + of good quality. Most mature projects around Kubernetes offer charts supported by the project nowadays.

## Rationale
This makes it easy for Kubernetes users to install Zipkin.

## Example Scenario
n/a

## Prior Art
* [zipkin results on artifacthub](https://artifacthub.io/packages/search?ts_query_web=zipkin&sort=relevance&page=1)

We (Equinix Managed Service NL) are willing to submit our own (currently closed source) chart if it's going to be included "upstream".

**Comment by basvanbeek** [comment]
Hi @jonkerj,

Great to see you and your company are willing to contribute. As community we see the value of providing good generic helm charts for Zipkin so please submit a PR and we'll review.

**Comment by jcchavezs** [comment]
I think this is also something @jbahire could be curious about as he has
done great work with helm charts in @hypertrace.

**Comment by jcchavezs** [comment]
Thanks @jonkerj!

**Comment by jcchavezs** [comment]
Follow up for this https://github.com/openzipkin/zipkin/issues/3408

**Comment by codefromthecrypt** [comment]
a combination of factors including abandoned and/or unmerged PRs, as well version and tag clutter in this repo led to moving helm to its own repo, owned by its contributors. Looking forward to https://github.com/openzipkin/zipkin-helm/issues/1 completing and things getting online again.
