### ISSUE TITLE
chart/zipkin-server - elasticsearch support

### ISSUE THREAD

**Issue by mrfelek** [openzipkin/zipkin#3401]
Rightnow chart/zipkin-server supports only "mem" storage type. As docker image allows to use elasticsearch I've prepared deployment.yaml file that supports elasticsearch. 
It was tested and it works. It doesn't require to make any changes in values.yaml as default STORAGE_TYPE is still set to mem.

Don't be hesitate to modify code. It can always be better :)

## Feature
zipkin-server helm chart that supports elasticsearch.

@jonkerj Would you be so kind and verify it and add to code? Deployment file in attachment. 
[deployment.zip](https://github.com/openzipkin/zipkin/files/7694609/deployment.zip)

**Comment by jonkerj** [comment]
Sure, I'll look into it this week

**Comment by bursztyn-pl** [comment]
Would be nice to have that feature out of the box. I've also verified it in my helm and it works :)

**Comment by ywilkof** [comment]
+1 
Would be great to have this implemented!

**Comment by jonkerj** [comment]
Sorry, it took a bit longer than expected: I've been busy and/or on holidays. Please see #3415, I'm looking for someone to confirm this actually works with ES (I don't run ES with Zipkin personally).
