### ISSUE TITLE
Align appVersion from chart with release version

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin#3408]
## Describe the Bug
Currently appVersion is no aligned with the release version (See https://github.com/openzipkin/zipkin/blob/master/chart/zipkin-server/Chart.yaml#L17). We should update that after https://github.com/openzipkin/zipkin/blob/master/.github/workflows/create_release.yml#L40 and then publish helm chart after https://github.com/openzipkin/zipkin/blob/master/.github/workflows/deploy.yml#L71. This will trigger a consistent workflow.

Notice we wouldn't restrict helm charts publish to changes in the chart itself by this change (which actually makes sense to me).

Ping @jonkerj

**Comment by jonkerj** [comment]
Yeah, sounds like a great plan to me.

**Comment by jcchavezs** [comment]
Do you have time to work on this @jonkerj?

**Comment by jonkerj** [comment]
Not anytime soon, holidays are coming and working at home with kids (schools closing).
