### ISSUE TITLE
Big typo on version number on the GitHub release page related to log4j issue

### ISSUE THREAD

**Issue by edwardxia** [openzipkin/zipkin#3409]
https://github.com/openzipkin/zipkin/releases/tag/2.23.14

The latest release tag is `2.23.14`, but the release info page has title saying `2.23.4`. I almost pulled the incorrect docker image that still have log4j vulnerability by looking at the title.

**Comment by jcchavezs** [comment]
We are sorry about this one. I just fixed it.
