### ISSUE TITLE
Click twice the query button of 'RUN QUERY' ,then get a blank page

### ISSUE THREAD

**Issue by Eric-1208** [openzipkin/zipkin#3410]
I install zipkin by the way: docker run -d -p 9411:9411 openzipkin/zipkin.
then I visit http://ip:9411. When I click twice the query button of 'RUN QUERY' ,then get a blank page.
I try many times ,but the result is same.

**Comment by jcchavezs** [comment]
Any JavaScript error in console?

**Comment by Eric-1208** [comment]
no

**Comment by Eric-1208** [comment]
![image](https://user-images.githubusercontent.com/84486949/146520201-35649585-7086-4d46-b670-47b7f6de5a19.png)

**Comment by Eric-1208** [comment]
![image](https://user-images.githubusercontent.com/84486949/146520480-5c12b544-078d-491d-8355-afcfc5e76cd4.png)

**Comment by codefromthecrypt** [comment]
as the javascript infrastructure changed, possibly there's no issue any more. If there is, please reply back.
