### ISSUE TITLE
ContentTooLargeException: maxContentLength: 10485760

### ISSUE THREAD

**Issue by Luubosi** [openzipkin/zipkin#3416]
##  ContentTooLargeException: maxContentLength: 10485760
- Zipkin - version 2.23.16
- Elasticsearch - 7.10.0

4 May 2021 - Allow specifying current/max content length when creating ContentTooLargeException
https://github.com/line/armeria/issues/3520

`
cat zipkin_spring.log | grep ContentTooLargeException
com.linecorp.armeria.common.ContentTooLargeException: maxContentLength: 10485760, contentLength: 16345532, transferred: 10491189
        at com.linecorp.armeria.common.ContentTooLargeExceptionBuilder.build(ContentTooLargeExceptionBuilder.java:78)
com.linecorp.armeria.common.ContentTooLargeException: maxContentLength: 10485760, contentLength: 11470475, transferred: 10491189
        at com.linecorp.armeria.common.ContentTooLargeExceptionBuilder.build(ContentTooLargeExceptionBuilder.java:78)
`

## Steps to Reproduce - UI issue
 zipkin search limit for examle 1300 and last 7 days.
-> Failed to search: Internal Server Error

## Expected Behaviour
- define maxContentLength
- zipkin search for examle 1300 and last 7 days.

**Comment by Luubosi** [comment]
solution for this issue

https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.7.2/com/linecorp/armeria/common/Flags.html

public static long defaultMaxResponseLength()
Returns the default client-side maximum length of a response. Note that this flag has no effect if a user specified the value explicitly via [ClientBuilder.maxResponseLength(long)](https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.7.2/com/linecorp/armeria/client/ClientBuilder.html#maxResponseLength(long)).
The default value of this flag is 10485760L. Specify the -Dcom.linecorp.armeria.defaultMaxResponseLength=<long> to override the default value. 0 disables the length limit.

-Dcom.linecorp.armeria.defaultMaxResponseLength=<long>

**Comment by jcchavezs** [comment]
Thanks a lot. Do you think something es missing in the documentation?
