### ISSUE TITLE
helm-chart - JAVA_OPTS support

### ISSUE THREAD

**Issue by mrfelek** [openzipkin/zipkin#3429]
There is no possibility to set JAVA_OPTS in helm chart.  Right now we are using "elasticsearch" as STORAGE_TYPE and [start-zipkin](https://github.com/openzipkin/zipkin/blob/master/docker/start-zipkin) file uses hardcoded values (  JAVA_OPTS=${JAVA_OPTS:-"-Xms32m -Xmx32m -XX:+ExitOnOutOfMemoryError"} in this case)

## Feature
Additional value for JAVA_OPTS handled by helm chart should be supported.

## Rationale
Rightnow zipkin takes hardcoded values that are not working with elasticsearch ( no more than 100 values can be shown in zipkin because of Terminating due to java.lang.OutOfMemoryError: Java heap space

## Example Scenario
This will help with setting up values for java to zipkin be able to show more than 100 results (in case of elasticsearch is used)

**Comment by mrfelek** [comment]
@jonkerj Can you please take a look on this one? Already checked on running environment and when I added variable to deployment on cluster I was able to get more than 800 results.
      env:
        [...some other envs...]
        - name: JAVA_OPTS
          value: '-Xms128m -Xmx512m -XX:+ExitOnOutOfMemoryError'

**Comment by jonkerj** [comment]
I've created a PR to include extra environment variables, should to the trick.

**Comment by codefromthecrypt** [comment]
@mrfelek FYI, a combination of factors including abandoned and/or unmerged PRs, as well version and tag clutter in this repo led to moving helm to its own repo, owned by its contributors including you. Looking forward to help with https://github.com/openzipkin/zipkin-helm/issues/1 so that things are online and folks can move easily.
