### ISSUE TITLE
Add support for ppc64le

### ISSUE THREAD

**Issue by NishikantThorat** [openzipkin/zipkin#3443]
# Feature
To make the docker images available for ppc64le(Power arch)

## Rationale
For Knative components, we need Zipkin on power(ppc64le), like support added for s390x(#3310)

## Example Scenario
Clients want to use knative, on top of it, they can use zipkin.

**Comment by codefromthecrypt** [comment]
On the way, but ppc64le's last LTS was openjdk 11 https://pkgs.alpinelinux.org/packages?name=openjdk11&branch=edge

There is work in progress to resurrect it, and meanwhile we'll wait on that https://gitlab.alpinelinux.org/alpine/aports/-/issues/15128

If any end users are interested in this, please thumbsup this issue as sometimes it is difficult to know if something is actively desired by a site vs completing a version matrix.

**Comment by codefromthecrypt** [comment]
cc also @BbolroC in case years later you are interested in this (or prefer to hide ;))
