### ISSUE TITLE
Zipkin server 2.12.3 springBoot projects add custom information to the span's json data structure

### ISSUE THREAD

**Issue by Layfolk-zcy** [openzipkin/zipkin#3451]
The version used when customizing the springBoot project on the zipkin server is 2.12.3. springBoot 2.1.17.RELEASE; I want to add custom information to the json result of the span. The kafka+es method collects and stores span data. thank you~!

**Comment by codefromthecrypt** [comment]
if you still have questions, please join gitter to ask them https://app.gitter.im/#/room/#openzipkin_zipkin:gitter.im
