### ISSUE TITLE
Empty traces due to some UI/React issues

### ISSUE THREAD

**Issue by frosiere** [openzipkin/zipkin#3455]
Traces cannot be displayed due to some UI/React issues.

The issue has been reproduced with both, the elasticsearch and mem storages on the latest version of Zipkin.

Traces are generated by Spring Boot 2.7.0 and Sleuth 3.1.3

Business flow: a chain of Spring Boot micro-services communicating with each others using Kafka, grpc, etc.

See the json at the end of the question.

It seems the last trace is always working. So, a working trace will be "corrupted" once a new trace will be available in the UI.
Any link with in flight traces?!

Fee free to ask if you need more details.

See the stackoverflow post for more details (json, screenshots, etc)
https://stackoverflow.com/questions/72645466/empty-traces-due-to-some-ui-react-issues

**Comment by frosiere** [comment]
The issue was caused by an incorrect definition of spans.
Some spans were created but not started and not finished in the finally clause. 
By fixing the code creating the spans, the issue disappeared.

**Comment by jcchavezs** [comment]
Thanks!
