### ISSUE TITLE
Disable Zipkin UI without disabling read endpoints

### ISSUE THREAD

**Issue by jsbali26** [openzipkin/zipkin#3456]
## Feature
Add a runtime property that only disables zipkin UI without disabling read endpoints.

## Rationale
Currently, if you need to disable Zipkin UI, the only option is to set QUERY_ENABLED to false. However, this disables the HTTP read endpoint. If you want to get trace data using the Zipkin read endpoint, but you need to disable the UI, there is no solution.

## Example Scenario
Example scenario can be explained as follows:-

1. Zipkin does not have OAuth 2.0 natively integrated. Therefore, OAuth 2.0 compliant integration like Okta is not possible with Zipkin.
2. Instead of providing users with Zipkin UI without OAuth 2.0 auth, use Grafana as Grafana has built-in Okta integration support. Trace data is sent from line-of-business applications to Zipkin. Use Grafana's built-in Zipkin support to use Zipkin as your data source.
3. View trace data from the Grafana UI.
4. Disable Zipkin UI to avoid unauthenticated access.

As you can see from the steps above,  Grafana will not be able to retrieve trace data from Zipkin if the Zipkin read endpoint is disabled.

**Comment by priyavivek2307** [comment]
@jcchavezs , will you be able to provide any feedback on this pls.

**Comment by codefromthecrypt** [comment]
sorry no one answered you that while QUERY_ENABLED can disable the UI, it is a shorcut for ZIPKIN_UI_ENABLED. I'll make one named UI_ENABLED so it is easier to find.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/3731
