### ISSUE TITLE
[FR] Support of junit5 engine

### ISSUE THREAD

**Issue by hezhangjian** [openzipkin/zipkin#3466]
## Feature
Now zipkin provides `zipkin-junit` module, it's very useful in tests. However, it only works with junit4, I hope it can support junit5 too.

## Rationale
This feature benefits all junit5 users.

## Example Scenario
People who using junit5 and want to use `zipkin-test` module

**Comment by jcchavezs** [comment]
Up for a PR?

**Comment by hezhangjian** [comment]
@jcchavezs Thanks for your reply. I don't think I can do the job. I'm not familiar with zipkin and haven't had enough time lately :)

**Comment by hezhangjian** [comment]
@jcchavezs I have created #3467 trying to fix this. waiting for your opinion. Thanks

**Comment by jcchavezs** [comment]
I am OOO. @llinder could you please have a look?

**Comment by hezhangjian** [comment]
closed by #3467
