### ISSUE TITLE
Elasticsearch versions 5-7.x are supported, was: 8.0 

### ISSUE THREAD

**Issue by developer-tahir-saleem** [openzipkin/zipkin#3468]
## openstack/zipkin-slim not connect with elasticsearch 8.3.0
We are using the docker image form https://hub.docker.com/r/openzipkin/zipkin-slim with  elastic search 8.0.0 or 8.3.0 Zipkin is not able to connect showing me error :

java.lang.IllegalArgumentException: Elasticsearch versions 5-7.x are supported, was: 8.0
        at zipkin2.elasticsearch.VersionSpecificTemplates.get(VersionSpecificTemplates.java:227)
        at zipkin2.elasticsearch.ElasticsearchStorage.versionSpecificTemplates(ElasticsearchStorage.java:356)
        at zipkin2.elasticsearch.ElasticsearchStorage.doEnsureIndexTemplates(ElasticsearchStorage.java:338)
        at zipkin2.elasticsearch.ElasticsearchStorage.ensureIndexTemplates(ElasticsearchStorage.java:330)
        at zipkin2.elasticsearch.ElasticsearchStorage.spanConsumer(ElasticsearchStorage.java:249)
        at zipkin2.server.internal.brave.ZipkinSelfTracingConfiguration$LocalSender.sendSpans(ZipkinSelfTracingConfiguration.java:163)
        at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:299)
        at zipkin2.reporter.AsyncReporter$Flusher.run(AsyncReporter.java:378)
        at zipkin2.server.internal.brave.ZipkinSelfTracingConfiguration$1.run(ZipkinSelfTracingConfiguration.java:55)
        at java.base/java.lang.Thread.run(Unknown Source)

Can you please confirm if is there any version to support ES 8.3.0 .

**Comment by lmarkusl** [comment]
same here.

https://github.com/openzipkin/zipkin/blob/c6ad4a2bb67104ce72ed138a98291e4c4339c61c/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/VersionSpecificTemplates.java#L225

```
  IndexTemplates get(ElasticsearchVersion version) {
    if (version.compareTo(V5_0) < 0 || version.compareTo(V8_0) >= 0) {
      throw new IllegalArgumentException(
        "Elasticsearch versions 5-7.x are supported, was: " + version);
    }
```
    
@llinder @jcchavezs 

Do you know any plans for supporting Version 8?

thx Markus

https://github.com/openzipkin/zipkin/issues/3453

**Comment by jcchavezs** [comment]
We don't have any plan to support 8.0. I don't even know what the scope og
the change would be (cc @xeraa) but given our current capacity (zipkin
being a volunteering project) I would expect some user or the community to
lead this effort of course with our guidance and based on the fact our test
suite is very strong.

**Comment by lmarkusl** [comment]
@jcchavezs thx a lot for answer.

In the meantime we remove the "version.compareTo(V8_0) >= 0".
Sure its it was a short test! but till yet :) its working fine. So we compile the the code and build a docker.

I think with another day or two we can add the version 8.x into supported Versions.
Let's see how it goes,...

**Comment by xeraa** [comment]
There's a full page on [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-8.0.html). Though IMO the number 1 thing is that security is now enabled by default. Otherwise this upgrade should (hopefully) be less painful than earlier ones 😅

**Comment by lmarkusl** [comment]
so in our setup it worked only remove the "check". So i can search for traces inside the elastic. 

```
{
    "status": "UP",
    "zipkin": {
        "status": "UP",
        "details": {
            "ElasticsearchStorage{initialEndpoints=https://xxxxxxxxxx:443, index=stash-zipkin}": {
                "status": "UP"
            },
            "ScribeCollector{port=9410, category=zipkin}": {
                "status": "UP"
            }
        }
    }
}
```

Yes thx i saw that breaking changes :D and thought give it a try.

**Comment by jcchavezs** [comment]
If you open a PR with it, tests might do the trick.

**Comment by lmarkusl** [comment]
sure https://github.com/openzipkin/zipkin/pull/3510

**Comment by codefromthecrypt** [comment]
Next step for this is to make a new elasticsearch8 image. The core infrastructure is the same as this https://github.com/openzipkin/zipkin/pull/3636 except the image will be more like elasticsearch7. It won't be exactly because not only has the download URL changed, but also there is only a JDK version (you can skip the jdk directory to use our JRE). once a PR like this is merged, someone with commit access needs to go to that package and mark it as public so it is downloadable.

After that happens "ghcr.io/openzipkin/zipkin-elasticsearch8:master" should work and progress on the actual driver can resume.

**Comment by codefromthecrypt** [comment]
zipkin 2.26.0 includes ES 8.x support
