### ISSUE TITLE
Some plugins still have log4j vulnerabilities when building

### ISSUE THREAD

**Issue by didoux** [openzipkin/zipkin#3473]
When build winht maven log4-1.2.12.jar is being download by license-maven-plugin & maven-dependency-plugin and store in maven .m2 cache.  Simple fix to upgrade plugins.  

    <license-maven-plugin.version>4.2.rc3</license-maven-plugin.version>
    <maven-dependency-plugin.version>3.3.0</maven-dependency-plugin.version>

For those computer like mine who are being scanned for the log4j vulnerabilities by just the existance of the jar on my computer cause consure.  Please make it stop.

**Comment by jcchavezs** [comment]
Up for a PR?

**Comment by jcchavezs** [comment]
Up for a PR? cc @llinder

**Comment by codefromthecrypt** [comment]
trivy is enabled and there are no longer any high/critical CVEs
