### ISSUE TITLE
OpenZipkin Docker image needs upgrading Java opensdk 

### ISSUE THREAD

**Issue by didoux** [openzipkin/zipkin#3475]
Looking at the Docker layers.  

["Image Layers"](https://hub.docker.com/layers/openzipkin/zipkin/latest/images/sha256-8a0fb7d6871c9d617b2e951b629f94b33affb8aa039110a69f3d466afd3e2d6b?context=explore)

Scanners are detecting vulnerablities on docker image because of Java 15.   I'd have to remove it or look for an alternative Tracing solution. 

Plugin Output:
The following Java JRE installation is unsupported :

 Path              : /var/lib/docker/overlay2/e5359f7882becb7615e423493538755a692dc00ec542285914111a0a06e072a0/diff/usr/lib/jvm/java-15-openjdk
  Installed version : 1.15.0_5_
  Latest versions   : 1.11.x / 1.17.x / 1.18.x
  Support dates     : 2021-03-01 (end of Premier Support)

Can this be updated from Java 15 to 17?

**Comment by jcchavezs** [comment]
Ping @llinder

**Comment by llinder** [comment]
Upgrading to Java 17 makes sense. Not sure if it will be seamless but I will look for time to give it a try.

**Comment by didoux** [comment]
@llinder Any update on this?

**Comment by codefromthecrypt** [comment]
zipkin is all the latest things lately
