### ISSUE TITLE
Not able to upgrade os packages of docker image

### ISSUE THREAD

**Issue by wim-de-groot** [openzipkin/zipkin#3479]
## Describe the Bug
When I want to update the os packages of the docker image, then I receive the following errors:

- ERROR: ca-certificates-bundle-20220614-r2: trying to overwrite etc/ssl1.1/cert.pem owned by libcrypto1.1-1.1.1n-r0.
-  ERROR: ca-certificates-bundle-20220614-r2: trying to overwrite etc/ssl1.1/certs owned by libcrypto1.1-1.1.1n-r0.

## Steps to Reproduce

1. Create a dockerfile containing the following:
```sh
FROM openzipkin/zipkin:2.23

USER root
RUN apk upgrade --no-cache

USER zipkin
``` 
2. Run the docker build command
`docker build -t test .`

## Expected Behaviour
The expected behaviour is that the packages are upgraded and the docker build does not fail.

**Comment by codefromthecrypt** [comment]
Sorry no one looked into this, but I just verified this works with latest.
