### ISSUE TITLE
Trace with missing root span is not rendered correctly in zipkin-lens

### ISSUE THREAD

**Issue by drewby** [openzipkin/zipkin#3505]
## Describe the Bug
In zipkin-lens 2.24, viewing trace details where the root span is missing (a parentid is referring to a missing span), a blank page is rendered and an error is show in developer tools console. 

An example trace (abbreviated) looks like. Span with id "ebec1841bdb48ba1" is missing.

```
[
    {
        "traceId": "b523777284bbb42aa6304c7a5cd35fd7",
        "parentId": "ebec1841bdb48ba1",
        "id": "3eca62ab99ac8e84",
        "timestamp": 1675053275397814,
    },
    {
        "traceId": "b523777284bbb42aa6304c7a5cd35fd7",
        "parentId": "3eca62ab99ac8e84",
        "id": "7021b3404bd7b9d6",
        "timestamp": 1675053275401192,
    }
]
```
Here is the full trace: [gist](https://gist.github.com/drewby/1782583a17c5930905de11e2c97db320)

In 2.24, this renders as follows: 
<img width="867" alt="error-2 24" src="https://user-images.githubusercontent.com/192652/215644493-5a81e8dc-00af-4916-b0d4-bac0d99363a2.png">

## Steps to Reproduce
1. Post a trace to Zipkin with one or more spans with the root span missing. 
2. Click "show" to view details in zipkin-lens

## Expected Behaviour
Traces should render correctly even if root span is missing. Or an error message should be shown instead of a blank page. 

In 2.23, this example renders correctly as:
<img width="866" alt="correct-2 23" src="https://user-images.githubusercontent.com/192652/215644604-38519edb-f7e8-4a31-924b-6bb1fb669c7a.png">

**Comment by jcchavezs** [comment]
Ping @tacigar
