### ISSUE TITLE
autoscaling/v2beta1 is removed from kubernetes 1.25

### ISSUE THREAD

**Issue by lz000** [openzipkin/zipkin#3514]
Please first, look at [existing issues](https://github.com/openzipkin/zipkin/issues) to see if the feature has been requested before. If you don't find anything tell us what problem you’re trying to solve. Often a solution already exists! Don’t send pull requests to implement new features without first getting our support. Sometimes we leave features out on purpose to keep the project small.

## Feature
Please update to autoscaling/v2

## Rationale
Why would this feature help others besides me?

## Example Scenario
What kind of use cases would benefit from this feature?

## Prior Art
* Links to prior art
* More links

**Comment by codefromthecrypt** [comment]
this looks created on the wrong repo? If it was about helm, then please have a second look as I don't know it is currently valid for there either https://github.com/openzipkin/zipkin-helm
