### ISSUE TITLE
Cassandra docker image build is broken

### ISSUE THREAD

**Issue by jeqo** [openzipkin/zipkin#3525]
## Describe the Bug

When building Cassandra image it's failing when using Python.

https://github.com/openzipkin/zipkin/actions/runs/4712733913/jobs/8357966030?pr=3524#step:11:190

## Steps to Reproduce

```
DOCKER_FILE=docker/test-images/zipkin-cassandra/Dockerfile build-bin/docker/docker_build openzipkin/zipkin-cassandra:test
```

**Comment by codefromthecrypt** [comment]
fixed sometime between then and now
