### ISSUE TITLE
zipkin dependencies graph not work with elasticsearch storage

### ISSUE THREAD

**Issue by sal22-hab** [openzipkin/zipkin#3529]
I am starting to use Zipkin and I have an issue when I run `docker-compose -f docker-compose-elasticsearch.yml up -d ` at docker/examples and the dependencies graph is not displayed when using Elasticsearch but it does work when I use MySQL or memory storage.

could anyone help me, please?
Thank you!

**Comment by basvanbeek** [comment]
Please refer to https://github.com/openzipkin/zipkin-dependencies for setting up a spark job to process the dependencies.

**Comment by sal22-hab** [comment]
Dear Bas Van Beek,

In setting up spark job that you have provided on GitHub. I have tried to
set it up on my own, but I am having some difficulties and I do not fully
understand the project.

I have reviewed the instructions on the project's GitHub page, but I am
still having trouble getting it up and running. I believe that I may be
missing some key information or steps.

I would greatly appreciate it if you could provide me with some guidance on
how to properly set up the project. Specifically, I would appreciate any
additional information or step-by-step instructions that you may have.

I believe that with your assistance, I will be able to make progress.

Thank you for your time and consideration. I look forward to hearing back
from you soon.

Best regards,
Hab Sal

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/releases/tag/2.25.2 cites the docs I revamped in the examples, to show literally the command to use when not waiting for the hourly cron to finish. https://github.com/openzipkin/zipkin/blob/master/docker/examples/README.md#elasticsearch

Any more questions, please follow-up on [gitter](https://app.gitter.im/#/room/#openzipkin_zipkin:gitter.im), thanks!
