### ISSUE TITLE
Color optimization for color blindness

### ISSUE THREAD

**Issue by Filippo125** [openzipkin/zipkin#3537]
A friend of mine is daltonist and he is an extensive Zipkin user.
He often struggles with distinguishing certain colors, especially when it comes to visualizations or color-coded elements in the Zipkin UI. It makes it quite challenging for him to effectively analyze and make sense of the presented data.

## Feature
My proposal to help him are:

* Alternative Color Indicators: Adding extra indicators or alternative methods to convey information, rather than solely relying on color differentiation, would be super helpful. It could be things like patterns, symbols, or text labels alongside colors.

* Contrast Enhancement: Improving the contrast between background and foreground colors throughout the application would greatly assist users with Daltonism. It would make it easier for us to read text and identify important elements.

**Comment by jcchavezs** [comment]
I would really love to see this happening in lens cc @tacigar @wu-sheng @basvanbeek

**Comment by basvanbeek** [comment]
I'm all for it, ideally we'd allow themes so we can bring back a dark theme too like we had in the initial design for lens (ideal for those late night troubleshooting sessions).

**Comment by wu-sheng** [comment]
![trace-list](https://github.com/openzipkin/zipkin/assets/5441976/213352a0-e036-4c27-b88f-80de9c8ac896)

This is a trace graph from SkyWalking trace layout. The colors of services are not going to cover the whole row.
And a small icon indicates entry or exit spans, in Zipkin, it means producer or consumer.

<img width="315" alt="image" src="https://github.com/openzipkin/zipkin/assets/5441976/e655b25b-6333-4e7e-bc92-65c631f796bd">

**Comment by codefromthecrypt** [comment]
fixed https://github.com/openzipkin/zipkin/releases/tag/3.2.0
