### ISSUE TITLE
Constant "major GC", "Old Gen" heap keeps increasing linearly

### ISSUE THREAD

**Issue by loisfa** [openzipkin/zipkin#3550]
## Describe the Bug
Zipkin spends a lot of time in major GC. This is triggered due to the Old Gen reaching the max limit, endlessly. We have tried G1GC and SerialGC garbage collectors.

Currently, this does not impact our usage of zipkin. Still, we remain careful about the metrics of all the app in our kubernetes cluster.

### Graphs
 
Time spent during major GC:
![Screenshot from 2023-06-09 15-30-27](https://github.com/openzipkin/zipkin/assets/14874955/31d60714-7b41-4d05-a142-9e28d6248f1a)

"Old Gen" heap constantly reaching the max limit:
![Screenshot from 2023-06-09 15-30-58](https://github.com/openzipkin/zipkin/assets/14874955/a5e65e2f-9dbe-4230-994f-574505ef3d48)

### Additional information
- We are using the zipkin image (not the slim one).
- We have 8 spring-boot apps in the cluster, all reporting spams to zipkin server via the 'spring-cloud-sleuth-zipkin' client.
- The more the traffic, the more time "major GC". Still, the traffic for our most "active" environments is quite low (<1req/s onto the zipkin server over 24h).
- Some figures for most active environments: zipkin JVM spends ~25s/day for major GC and ~100s/day for minor GC (1/4 seems to be a huge ratio between major/minor GC).
- The major GC run of is evenly distributed over 24h: no particular spikes based on actual traffic.

### What we tried
1. change JVM GC from SerialGC to G1GC. 
--> we first thought the issue was solved thanks to "proactive cleaning of G1GC" (before the upper limit is reached), the proactive G1GC cleaning of "Old Gen" also leads to frequent "major GC"
2. increase heap size from 64Mi to 1Gi to verify whether "Old Gen" would converge somewhere.
--> the "Old Gen" has never converged and kept increasing linearly up to the limit.

We are not expert at JVM heap analysis but in comparison with our apps:
- for our "home-made" apps: in the first minutes the "Old Gen" grows super fast, then slows down, and "almost" converge toward a limit.
- the zipkin server: in the first monutes the "Old Gen" grows super fast, then grows slower but linearly, no convergence.
We guess this is related to the nature of the app. 

## Steps to Reproduce
Setup and run zipkin server, setup zipkin client on spring boot apps, have regular (even low) traffic sent on the spring boot apps.

## Expected Behaviour
Few major GC occurrences triggered.

Do some of you experience the same? Thanks in advance, any sort of feedback will be welcome!
Same message posted in the Gitter chat last week (still waiting for feedback):
https://matrix.to/#/!nCyOaFcJAqomeUsviF:gitter.im/$cSd84hVKxWH2CjegMqRZnikxrCk0D3-LIc3Y6BiogJQ?via=gitter.im

**Comment by xavbourdeau** [comment]
+1

**Comment by codefromthecrypt** [comment]
Curious.. is this about the in-memory (test) configuration of zipkin, or using a particular storage option.

**Comment by codefromthecrypt** [comment]
I'm assuming this is about in-memory storage, which isn't a production config, but I know people use it anyway ;)

As the JVM and other infrastructure changed lately, and this topic shouldn't have anything to do with sleuth. I'd suggest if someone is interested to use our docker examples as they are known working configurations.

https://github.com/openzipkin/zipkin/tree/1ed6c4a3c337257e7890be8932dca133789ffa33/docker/examples#example

then, hit localhost:8081 with any additional monitoring configuration you desire. If something actionable turns up, please comment and we can consider re-opening the issue.
