### ISSUE TITLE
Does Zipkin 2.24.3 support Java17 and Elasticsearch8. x

### ISSUE THREAD

**Issue by Layfolk-zcy** [openzipkin/zipkin#3558]
Does Zipkin 2.24.3 support Java17 and Elasticsearch8. x

**Comment by codefromthecrypt** [comment]
Zipkin 2.25 will target ES 8 per https://github.com/openzipkin/zipkin/releases/tag/2.24.4

**Comment by codefromthecrypt** [comment]
zipkin 2.26.0 includes ES 8.x support
