### ISSUE TITLE
Error message shows: Text fields are not optimised for operations that require Opensearch

### ISSUE THREAD

**Issue by phuoclh-jienielabs** [openzipkin/zipkin#3559]
"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [traceId] in order to load field data by uninverting the inverted index. Note that this can use significant memory."

Zipkin show this error message. Please help me resolve this. Thank you so much.

**Comment by codefromthecrypt** [comment]
I think if we want to support open search, we need a docker image for it. similar to https://github.com/openzipkin/zipkin/tree/master/docker/test-images/zipkin-elasticsearch7

Are you able to help create this? If not, let us know.

**Comment by eli-gc** [comment]
I was able to resolve this error by removing my manually defined index template for zipkin spans. For some reason the traceId was getting mapped to text. When I use the one generated by Zipkin, it maps traceId to keyword only which allowed me to perform searches in the Zipkin ui.

**Comment by codefromthecrypt** [comment]
thanks for explaining your resolution, as it helps the next person!
