### ISSUE TITLE
Zipkin 2.24.3 not support Elasticsearch8. x

### ISSUE THREAD

**Issue by c8679724** [openzipkin/zipkin#3562]
Hello, I'm currently using Elasticsearch 8.x, and when consuming Kafka and writing to Elasticsearch with Zipkin 2.24.3, I encounter an error indicating that it does not support versions 7 and above.

**Comment by wu-sheng** [comment]
Zipkin v2 backend doesn't support that.
We are working on Zipkin v3 server, which should be able to bring Elasticseach8 on the support list.

**Comment by codefromthecrypt** [comment]
Zipkin 2.25 will target ES 8 per https://github.com/openzipkin/zipkin/releases/tag/2.24.4

**Comment by codefromthecrypt** [comment]
added next steps to #3468 as I am on holiday for a bit I cannot finish this now. I ended up needing a lot of time to address lack of maintenance on all projects including brave. In any case, this issue is a dupe

**Comment by codefromthecrypt** [comment]
zipkin 2.26.0 includes ES 8.x support
