### ISSUE TITLE
When there are too many spans, UI rendering fails.

### ISSUE THREAD

**Issue by huangdijia** [openzipkin/zipkin#3565]
<img width="1253" alt="image" src="https://github.com/openzipkin/zipkin/assets/8337659/cca511e6-f294-4151-af96-7d8fd8467b0f">
<img width="1279" alt="image" src="https://github.com/openzipkin/zipkin/assets/8337659/75aed295-458f-4dbb-8557-da5e5cb22595">

Front-end rendering fails, even causing the browser to freeze.

**Comment by codefromthecrypt** [comment]
hmm at some point, we had support for very large traces (1000s of spans). perhaps there are a lot of tags in your spans? Is there a way for you to share a file that scrubs personal data to test with? https://github.com/openzipkin/zipkin/tree/master/zipkin-lens/testdata

**Comment by huangdijia** [comment]
I have given up on zipkin and switched to sentry
