### ISSUE TITLE
bin/web fails out of the box: missing bootstrap & jquery

### ISSUE THREAD

**Issue by pteichman** [openzipkin/zipkin#360]
As of commit 257f3135e78afd3894213ae2500f00ee53e28c35, the Zipkin web interface throws 500's when trying to reach the following:
- bootstrap.min.css
- bootstrap.min.js
- jquery.min.js

They're all missing in the tree.

Running `bower install` doesn't fix this, but copying the files manually into zipkin-web/src/main/resources/app/libs/\* produces a working UI. If these are meant to be committed to the tree, I can make a pull request.

**Comment by sprsquish** [comment]
yea.. sorry about this. I have a fix ready to go.
