### ISSUE TITLE
Add a way to install zipkin through homebrew on macos

### ISSUE THREAD

**Issue by remyleone** [openzipkin/zipkin#3649]
## Feature

I would like to install zipkin using homebrew using `brew install zipkin`

## Rationale

It would be helpful for other macos user to have a way to experiment quickly and easily with zipkin while keeping it up to date with brew

## Example Scenario

I got a mac, I don't have docker, I want to try zipkin out, I would like to have a way to test it without compiling.

## Prior Art
* Links to prior art
* More links

**Comment by codefromthecrypt** [comment]
sounds very sensible

**Comment by codefromthecrypt** [comment]
for now you can try the quick start https://zipkin.io/pages/quickstart.html

```bash
$ curl -sSL https://zipkin.io/quickstart.sh | bash -s
$ java -jar zipkin.jar
```

One question for the home-brew thing, is if this should be the full zipkin build (includes kafka etc) or slim (smaller and a bit quicker to startup, but no messaging support)

**Comment by remyleone** [comment]
Kafka is already available in [homebrew](https://github.com/Homebrew/homebrew-core/blob/f49bf3578641d7bd93021553c7ecf99255b137e7/Formula/k/kafka.rb), maybe the other components in the full zipkin build are also present.

I guess you could have a jar that contains only zipkin code and either include a dependency on kafka explicitly (and the other dependencies) or having something without kafka support included but that could find it opportunistically if present.

**Comment by codefromthecrypt** [comment]
oh zipkin's support of kafka is optional. I'm leaning towards the full build

**Comment by codefromthecrypt** [comment]
someone who wants to help with this can copy something like this https://github.com/Homebrew/homebrew-core/blob/4ef4ac3f2708daa8be276fcea3fdaade8ddded3a/Formula/d/denominator.rb into a new pull request

except use https://repo1.maven.org/maven2/io/zipkin/zipkin-server/2.26.0/zipkin-server-2.26.0-exec.jar as the jar

@reta wanna give this a try? I've done several homebrew recipes and the community is nice.

**Comment by reta** [comment]
> @reta wanna give this a try? I've done several homebrew recipes and the community is nice.

@codefromthecrypt really want to help here, but I don't have MacOS box available to me (I have Windows and Linux boxes) :(

**Comment by codefromthecrypt** [comment]
ah yeah indeed macos is important for testing. I'll help with this!

**Comment by codefromthecrypt** [comment]
as promised https://github.com/Homebrew/homebrew-core/pull/159482 please 👍 cc @openzipkin/devops-tooling

**Comment by codefromthecrypt** [comment]
https://formulae.brew.sh/formula/zipkin is shipped. only thing left is to update the README here and the website [quick start](https://github.com/openzipkin/openzipkin.github.io/blob/master/pages/quickstart.md). Volunteer anyone?

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/3692 for the readme
https://github.com/openzipkin/openzipkin.github.io/pull/178 for the website
