### ISSUE TITLE
About install zipkin？

### ISSUE THREAD

**Issue by bbgasj** [openzipkin/zipkin#366]
I have downloaded zipkin, and ran bin/sbt, but it halted on download jna like this:

downloading http://repo1.maven.org/maven2/net/java/dev/jna/jna/3.2.3/jna-3.2.3.jar ...

I don't why it can't download this, and i try wget this jar, and it works, but I don't know where it put to.So has anyone got the same problem? and could you tell me how to solve this or where to put this jar?

thank you!

**Comment by bmdhacks** [comment]
Works for me.  Perhaps it's a problem with your network requiring a proxy of some sort?

**Comment by bbgasj** [comment]
but I used wget, it can download this jar, I don't know why? And could you
tell me where the
jna-3.2.3.jarhttp://www.google.com/url?q=http%3A%2F%2Frepo1.maven.org%2Fmaven2%2Fnet%2Fjava%2Fdev%2Fjna%2Fjna%2F3.2.3%2Fjna-3.2.3.jar&sa=D&sntz=1&usg=AFQjCNHY8wq_StPyxPv5IWFA5fJ2kOgvuw
put
to?
thank you!

On Sat, Mar 29, 2014 at 1:23 AM, Brian Degenhardt
notifications@github.comwrote:

> Closed #366 https://github.com/twitter/zipkin/issues/366.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/twitter/zipkin/issues/366
> .

## 

@冯欣伟 | 艺龙旅行网 | 研发工程师
微信 bbgasj | QQ 11538018
