### ISSUE TITLE
Docker container ends up with defunkt wget processes

### ISSUE THREAD

**Issue by rogierslag** [openzipkin/zipkin#3670]
## Describe the Bug
When running the Docker container for longer periods of time, zombie proceses for wget show up, which can be traced back to the `openzipkin/zipkin` container.

Based on the code, the wget seems to originate from the healthcheck as done here https://github.com/openzipkin/zipkin/blob/master/build-bin/docker/docker-healthcheck#L48.

## Steps to Reproduce
Keep the Docker container running for a while (at least on our infrastructure)

## Expected Behaviour
Whenever wget fails for whatever reason, it should be terminated gracefully and not become a zombie process

**Comment by codefromthecrypt** [comment]
hmm could it be that the interval is 1s and for some reason the wgets are taking longer?

I raised this which should be sensible in context https://github.com/openzipkin/zipkin/pull/3677

what is the ad-hoc latency for your /health endpoint?

**Comment by rogierslag** [comment]
Ran a quick test with `ab` which yields well below 1s response times.

```
ab -c 5 -n 500 https://zipkin.internal.magnet.me/health
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking zipkin.internal.magnet.me (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests


Server Software:        nginx/1.24.0
Server Hostname:        zipkin.internal.magnet.me
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-GCM-SHA256,2048,128
Server Temp Key:        ECDH P-384 384 bits
TLS Server Name:        zipkin.internal.magnet.me

Document Path:          /health
Document Length:        410 bytes

Concurrency Level:      5
Time taken for tests:   13.170 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      324500 bytes
HTML transferred:       205000 bytes
Requests per second:    37.96 [#/sec] (mean)
Time per request:       131.704 [ms] (mean)
Time per request:       26.341 [ms] (mean, across all concurrent requests)
Transfer rate:          24.06 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       63   91  15.0     88     161
Processing:    19   39  11.6     37     115
Waiting:       19   38  11.2     36     107
Total:         89  130  20.2    126     235

Percentage of the requests served within a certain time (ms)
  50%    126
  66%    134
  75%    142
  80%    147
  90%    156
  95%    168
  98%    181
  99%    195
 100%    235 (longest request)
```

However on two separate hosts we run zipkin on, the timing of the defunkt processes seems to be matching

| Host 1 | Host 2|
|---|---|
|  | `0.0  0.0      0     0 ?        Z    00:16   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` |
| | `0.0  0.0      0     0 ?        Z    01:05   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    01:21   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    01:21   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    01:21   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    01:21   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    01:22   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    01:22   0:00 [wget] <defunct>` |
| | `0.0  0.0      0     0 ?        Z    01:22   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    02:00   0:00 [wget] <defunct>` | `0.0  0.0      0     0 ?        Z    02:00   0:00 [wget] <defunct>` |
| `0.0  0.0      0     0 ?        Z    02:07   0:00 [wget] <defunct>` | |

**Comment by codefromthecrypt** [comment]
are you able to try the master docker tag, which adjusts the wget timeout?

There are a couple articles which hint this could be about the HEALTHCHECK process quitting before wget does. If you are using in-memory storage it could be slow GC that could cause this? What is the output of /health? that will show what is running..

https://github.com/gliderlabs/docker-consul/issues/45
https://stackoverflow.com/questions/77105400/docker-compose-hundreds-of-health-check-processes-not-terminated
https://github.com/zadam/trilium/issues/3582

**Comment by codefromthecrypt** [comment]
@anuraaga I wonder if we shouldn't change our HEALTHCHECK interval to 2s, as in worst case even a timed out wget or nc would result in slightly more than a second. We keep a tight interval to help responsiveness in dev, but 2s is also not a big deal vs 1s.. wdyt?

**Comment by anuraaga** [comment]
I think changing the interval would be fine if it solves the problem. From what it sounds like, it would at best solve it or at worst make it extremely unlikely (maybe there's some reason other than timeout that causes health check script to get killed before wget).

I found this thread about patterns to propagate kill to child processes. It looks wordy but maybe it's worth doing instead or in addition to tweaking the interval?

https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash

Another idea but not recommendation is replacing the shell script+wget with a small cross compiled go binary.

**Comment by codefromthecrypt** [comment]
@anuraaga interesting idea on a cross-compiled healthcheck binary... I guess it would be most appropriate to compile and add to https://github.com/openzipkin/docker-alpine, since there's nothing java about it. Are you interested enough to emulate the shell script in Go or favorite and add it there?

**Comment by codefromthecrypt** [comment]
> https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash

seems like it wants us to background the child so we can handle signals manually. I worry about this being hard to test and may become worse if not carefully done..

**Comment by anuraaga** [comment]
Agree it is tricky, I was hoping to just find some setopt to propagate signals 😂

I can look at adding a health binary to docker-alpine, it may take a few days to get to it

**Comment by anuraaga** [comment]
Agree it is tricky, I was hoping to just find some setopt to propagate signals 😂

I can look at adding a health binary to docker-alpine, it may take a few days to get to it

**Comment by codefromthecrypt** [comment]
> I can look at adding a health binary to docker-alpine, it may take a few days to get to it

no rush on this, as it is an optimization. I'll leave this open for a bit as we'll soon release 2.27.0 with the timeout changes.

p.s. actually only test images are interval 1s, the main image is 5s

**Comment by rogierslag** [comment]
> are you able to try the master docker tag, which adjusts the wget timeout?

Sure no problem. To be clear, do you mean https://hub.docker.com/layers/openzipkin/zipkin/2.27/images/sha256-9f214e262bb389093ed2df22972625ecefb675c547e7987a00567476fb5e0ab6?context=explore or https://github.com/openzipkin/zipkin/pkgs/container/zipkin/164227092?tag=master? The `master` on Docker Hub appears to be outdated

**Comment by codefromthecrypt** [comment]
@rogierslag actually you can try 2.27.0 now. p.s. sorry I didn't clarify, master is on ghcr.io/openzipkin/zipkin if there's a master tag on docker hub it should probably be removed!

**Comment by rogierslag** [comment]
Shipping that on Monday. I'll circle back on Friday!

**Comment by rogierslag** [comment]
On two nodes after a couple of days exactly 0 defunkt processes, where it used to be more

**Comment by codefromthecrypt** [comment]
great. I'll close this out and if something recurs we can reopen it. Appreciate the looping back @rogierslag!
