### ISSUE TITLE
java 21 java -jar zipkin.jar

### ISSUE THREAD

**Issue by jinyulei0710** [openzipkin/zipkin#3694]
## Describe the Bug
java.lang.IllegalArgumentException: Unsupported URL: jar:nested:/root/zipkin.jar/!BOOT-INF/lib/zipkin-lens-3.0.3.jar!/zipkin-lens/static/js/main.d21e7047.js (must start with 'file:', 'jar:file', 'jrt:' or 'bundle:').
And the ui load error.

## Steps to Reproduce
curl -sSL https://zipkin.io/quickstart.sh | bash -s
java -jar zipkin.jar

java -version
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)
## Expected Behaviour
ui showed

**Comment by codefromthecrypt** [comment]
looking, thanks

**Comment by codefromthecrypt** [comment]
opened https://github.com/line/armeria/issues/5390 while try to think about a workaround..

**Comment by codefromthecrypt** [comment]
patching HttpFile to pass on the path starting with "nested" works, but adding a patched file from Armeria is a NOTICE pain, because it is not a file we wrote.. cc @openzipkin/armeria I'll try to find another way, but all the classes we couldl work around this with seem package protected. At the moment zipkin is toast over this

**Comment by codefromthecrypt** [comment]
https://github.com/line/armeria/pull/5391 should fix this but we need to figure out if we can wait for the release. since the project is busted, probably we need a temporary workaround.

**Comment by codefromthecrypt** [comment]
once https://github.com/openzipkin/zipkin/pull/3696 lands I'll release and raise a patch to homebrew also

**Comment by codefromthecrypt** [comment]
verified back to working in 3.0.4

**Comment by codefromthecrypt** [comment]
https://github.com/Homebrew/homebrew-core/pull/160208 for homebrew update (`brew bump-formula-pr zipkin --version 3.0.4`)
