### ISSUE TITLE
ES_HTTP_LOGGING appears broken

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#3712]
## Describe the Bug

I was going to suggest in a different issue to use `ES_HTTP_LOGGING=BODY` in order to know if zipkin would have a problem with preexisting indices which were aliases. I tried myself first, but it didn't do anything.

## Steps to Reproduce

I applied this diff

```diff
--- a/docker/examples/docker-compose-elasticsearch.yml
+++ b/docker/examples/docker-compose-elasticsearch.yml
@@ -37,8 +37,8 @@ services:
       - STORAGE_TYPE=elasticsearch
       # Point the zipkin at the storage backend
       - ES_HOSTS=elasticsearch:9200
-      # Uncomment to see requests to and from elasticsearch
-      # - ES_HTTP_LOGGING=BODY
+      - ES_HTTP_LOGGING=BODY
+      - SELF_TRACING_ENABLED=true
     depends_on:
       storage:
         condition: service_healthy
```

then, I did the following:

```bash
$ cd docker/examples
$ docker-compose -f docker-compose-elasticsearch.yml up
```

And then I kept clicking reload on http://localhost:9411/zipkin which made self-traces, but the whole time zipkin had no output.

## Expected Behaviour

There should have been logs in the console. I'm not sure when this stopped working.. we should have had a test for this, but didn't. Admittedly due to the packaging difference between slim and normal server (former uses slf4j and the other log4j2), actually getting tests to work might be tricky unless using invoker. Note that the docker-compose example uses slim.

**Comment by codefromthecrypt** [comment]
@reta got another interesting one for you 💪

**Comment by codefromthecrypt** [comment]
ps while looking at this, it seems there is progress as we can specify a logger. this may make it testable https://github.com/line/armeria/issues/2220

**Comment by reta** [comment]
@codefromthecrypt I've briefly looked into the issue and indeed,  I don't see relevant logs (like BODY) in the console. My initial suspect was mix of slf4j 1.x and slf4j 2.x but it seems to be not having an impact of logging, I will continue looking.

**Comment by reta** [comment]
Closed by https://github.com/openzipkin/zipkin/pull/3714
