### ISSUE TITLE
lens: i18n doesn't work anymore

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#3723]
If you click the language toggle, nothing happens. We need to make sure the language features work, both defaulting from locale and also via language toggle before the next release.

cc @SamTV12345 if you can look into this

**Comment by SamTV12345** [comment]
@codefromthecrypt Sorry for that. Fyi I'm working on a fix.

**Comment by codefromthecrypt** [comment]
> @codefromthecrypt Sorry for that. Fyi I'm working on a fix.

don't worry about it. Literally every time we switch a major framework, there are glitches (usually caused by me). The saying goes "You can't make an omelet without breaking a few eggs"

**Comment by SamTV12345** [comment]
Yeah you're right. We converted the whole frontend to a new bundler, runtime and even switched the language library. Thanks for your understanding and sorry for the broken language selector. I fixed it in #3725.

**Comment by codefromthecrypt** [comment]
I believe this one is sorted now!
