### ISSUE TITLE
Possbility to override the default namin strategy of span names.

### ISSUE THREAD

**Issue by suikast42** [openzipkin/zipkin#3735]
Currently the building of Span names are hard coded in  the span builder. 

```zipkin2.Span.Builder```

```java
    public Builder name(@Nullable String name) {
      this.name = name == null || name.isEmpty() ? null : name.toLowerCase(Locale.ROOT);
      return this;
    }
```

Imn a distrubuted world  not all using zpking as tracer. For having common naming strategy it cloud be very helpgul to make that area modifyable.

**Comment by codefromthecrypt** [comment]
@suikast42 are you asking about...

* using zipkin2.Span in code you control
* using zipkin2.Span in code you use, but don't control (e.g. otel's java library)
  * maybe that library has a way to change it
* zipkin's internal use of zipkin2.Span
  * the default would only apply for the rare case of a span with no name

I'll give you a link to one way people modify data *after* zipkin collected it when using elasticsearch https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/elasticsearch#customizing-the-ingest-pipeline

I don't expect us to change the builder type itself as it is uncommon and surprising for a builder to take defaults externally.

However, but there's probably a way to help you with your problem. as we use issues for code, mind moving to https://app.gitter.im/#/room/#openzipkin_zipkin:gitter.im ?
