### ISSUE TITLE
Discussion - h2 as the default database

### ISSUE THREAD

**Issue by mjwall** [openzipkin/zipkin#378]
I have been playing with Zipkin using the default SQLite implementation and have run into random failures writing traces in the collector.  The application I was attempting to trace had spans that were very short, and I would get errors like the following

```
[error] ERR [20140416-14:43:14.253] processor: storeSpan
[error] ERR [20140416-14:43:14.253] processor: java.sql.SQLException: SQL logic error or missing database
[error] ERR [20140416-14:43:14.253] processor:     at org.sqlite.DB.throwex(DB.java:370)
[error] ERR [20140416-14:43:14.253] processor:     at org.sqlite.DB.exec(DB.java:76)
[error] ERR [20140416-14:43:14.253] processor:     at org.sqlite.Conn.rollback(Conn.java:351)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.zipkin.storage.anormdb.DB.withTransaction(DB.scala:70)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.zipkin.storage.anormdb.AnormStorage$$anonfun$storeSpan$1.apply$mcV$sp(AnormStorage.scala:63)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.zipkin.storage.anormdb.AnormStorage$$anonfun$storeSpan$1.apply(AnormStorage.scala:58)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.zipkin.storage.anormdb.AnormStorage$$anonfun$storeSpan$1.apply(AnormStorage.scala:58)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.util.Try$.apply(Try.scala:13)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:111)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
[error] ERR [20140416-14:43:14.253] processor:     at java.lang.Thread.run(Thread.java:695)
[error] ERR [20140416-14:43:14.253] processor: storeSpan
[error] ERR [20140416-14:43:14.253] processor: java.sql.SQLException: database in auto-commit mode
[error] ERR [20140416-14:43:14.253] processor:     at org.sqlite.Conn.rollback(Conn.java:350)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.zipkin.storage.anormdb.DB.withTransaction(DB.scala:70)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.zipkin.storage.anormdb.AnormStorage$$anonfun$storeSpan$1.apply$mcV$sp(AnormStorage.scala:63)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.zipkin.storage.anormdb.AnormStorage$$anonfun$storeSpan$1.apply(AnormStorage.scala:58)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.zipkin.storage.anormdb.AnormStorage$$anonfun$storeSpan$1.apply(AnormStorage.scala:58)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.util.Try$.apply(Try.scala:13)
[error] ERR [20140416-14:43:14.253] processor:     at com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:111)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
[error] ERR [20140416-14:43:14.253] processor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
[error] ERR [20140416-14:43:14.253] processor:     at java.lang.Thread.run(Thread.java:695)
```

Thinking maybe the file based SQLite implementation couldn't handle the rapid spans I was sending it, I switched to file based H2.  Had to tweak the SQL statements, as some of the GROUP BY portions were non standard and didn't work.  No more errors and it appears all the spans are stored.

I also added a small h2-client script to launch a web gui into the same H2 database, which I found useful for seeing what was stored.    Would this change be useful to contribute?  If so, I would need to update the tests.  Thinking I might pull out the database configuration as well, so you could switch databases without recompiling.  That would make it easier to unit test all database backends, instead of just the default.

Thanks

**Comment by sprsquish** [comment]
The newer code is flag based and lets you change databases without recompiling. I don't think all the backends have been fully tested though. The SQL may still fail.

**Comment by mjwall** [comment]
Thanks for the reply Jeff.  Happy to move this to the google group if that is better.

Any thoughts on the sqlite errors?  My thought was that too many spans where coming in asynchronously, and sqlite couldn't handle it.  But I wasn't sure.

I think I am using the "newer code".  My testing was on master, commit 20f148b35ed18fa543cbedbc8ad977de54990b7a from 2 Apr.

When you say flag, do you mean "sqlite-persistent"  on https://github.com/twitter/zipkin/blob/master/zipkin-anormdb/src/main/scala/com/twitter/zipkin/util/DBConfig.scala#L54 and https://github.com/twitter/zipkin/blob/master/project/Project.scala#L272?  If so, I don't see how to change backends without changing those values and recompiling.

At the very least, I'd like to try to get unit tests for sqlite (memory and persistent) and h2 (memory and persistent) against the SQL changes I made.  I can test manually against MySQL and Postgres.

**Comment by sprsquish** [comment]
I'm not sure about the SQLite issues. How fast were you pushing data into it?

By new code, I meant the new SpanStore: https://github.com/twitter/zipkin/blob/master/zipkin-anormdb/src/main/scala/com/twitter/zipkin/storage/anormdb/AnormSpanStore.scala

It's still undocumented, but pretty easy to get working (https://github.com/twitter/zipkin/blob/master/zipkin-example/src/main/scala/com/twitter/zipkin/example/Main.scala). 

Better unit tests would be great.

**Comment by mjwall** [comment]
I pushed in about 50 spans/second for 2 seconds.  Got about 8 of those exceptions, but it was hard to tell exactly which spans failed.

I'll take a look at the AnormSpanStore, thanks.  I did notice the SQL was duplicated there and in AnormIndex.  Thanks.

**Comment by mjwall** [comment]
So with the AnormDBSpanStoreFactory, it looks like only the AnormSpanStore and SpanStoreDB are needed from the rest of zipkin-anormdb subproject.  Is that right and what is the plan for the rest of the subproject?  Is there a ticket to refactor out old and unneeded code out of anormdb I can watch?

Thanks

**Comment by sprsquish** [comment]
That's correct. The rest will be deprecated, but I don't want to start that until I have excellent documentation for the new way of building and configuring a service.

I've created a milestone to track next steps: https://github.com/twitter/zipkin/issues?milestone=2&state=open

**Comment by codefromthecrypt** [comment]
Closing this issue a we are removing H2 from the default list. Since we don't run tests or allow docker configuration, H2 may already be broken without us knowing: #853

In the near future, we will release an alternative to anorm, jOOQ, in the [java project](https://github.com/openzipkin/zipkin-java/blob/master/zipkin-java-jdbc). If there's enough interest to contribute docs and tests for other databases, we can always pick this back up.
