### ISSUE TITLE
File symlink error

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin#385]
File zipkin-gems/zipkin-query/thrift/zipkinQuery.thrift  should be link to '../../../zipkin-thrift/src/main/resources/thrift/zipkinQuery.thrift', not '../../../zipkin-thrift/src/main/thrift/zipkinQuery.thrift'

**Comment by suchang** [comment]
Would you like to make a pull request?

**Comment by sprsquish** [comment]
fixed: e1a0b5b
