### ISSUE TITLE
Time zone error

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin#388]
There's a 1 hour difference in time zone from UTC here, so we don't get to see the last traces (newer than 1 hour) unless we adjust the "end time" in the Zipkin UI one hour ahead.
(I guess it's my laptop computer that is set to local time, and the servers running UTC).
Anyways, could the "end time" option in Zipkin be turned off by default?

**Comment by sprsquish** [comment]
I believe this is now fixed in the latest version of the UI.
