### ISSUE TITLE
Document how to instrument other servers

### ISSUE THREAD

**Issue by sprsquish** [openzipkin/zipkin#401]
We need good documentation on how to properly instrument a service that doesn't already have an implementation.

**Comment by ggsonigg** [comment]
does anyone really have pointers on this? I wanted to try out brave APIs with my java code, as an example, but there is nothing I could found which could help me use zipkin.

**Comment by codefromthecrypt** [comment]
@ggsonigg you'll have better luck raising such a question on the Brave repo, as that's the repo which would have a change (about how to use Brave). When you do, please be specific about which README files you read and found they aren't instructive enough. It is hard to guess what type of docs people want. https://github.com/openzipkin/brave/issues

**Comment by eirslett** [comment]
Is this in the context of Java, instrumenting a Java application with Brave, but it doesn't already have a Brave plugin for it? Or is it more general, like a haskell application, given we have no haskell zipkin library?

**Comment by yurishkuro** [comment]
@sprsquish have you seen http://opentracing.io ?  The OpenTracing Spec does not have examples specifically for Java, but the API is nearly identical across all languages and there are already contributed projects that show instrumentations of various server frameworks, e.g.
- https://github.com/opentracing-contrib/
- https://github.com/uber/jaeger-client-java (JAXRS2 / Dropwizard)

The Jaeger lib above implements OpenTracing API, and is Zipkin-compatible even on the wire, thanks to recent PRs from @adriancole (I owe him a published version, will release one today, but meanwhile there are snapshots on [sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/uber/jaeger/) )

**Comment by codefromthecrypt** [comment]
super old
