### ISSUE TITLE
Service View UI explodes on long annotation names

### ISSUE THREAD

**Issue by tdrisdelle** [openzipkin/zipkin#403]
If an annotation is extremely long it explodes out the Service View UI. You can also see that odd lines have a transparent background which makes it look even worse.

This is on Chrome Version 36.0.1985.125
Same experience on Safari Version 7.0.5

![screen shot 2014-08-05 at 10 20 22 am](https://cloud.githubusercontent.com/assets/6126182/3815440/ff3d63de-1cc4-11e4-8a1e-f473a80107b7.png)

**Comment by zeagord** [comment]
This must be fixed in the latest versions after https://github.com/openzipkin/zipkin/pull/2224
