### ISSUE TITLE
Service UI duration and relative time columns are difficult to read using mixed units of time

### ISSUE THREAD

**Issue by tdrisdelle** [openzipkin/zipkin#404]
Using mixed-units of time in the duration field and the relative time field in the Service View UI make it difficult to get obvious at-a-glance sense of where the trouble lies.

It would be ideal to settle on a single unit of time, e.g. milliseconds.

![screen shot 2014-08-05 at 10 20 22 am](https://cloud.githubusercontent.com/assets/6126182/3815490/69dbff34-1cc5-11e4-80a6-409fc8a97c0c.png)

![screen shot 2014-08-05 at 10 26 11 am](https://cloud.githubusercontent.com/assets/6126182/3815511/a3e3cb26-1cc5-11e4-8a0d-0608cf501864.png)

**Comment by jorgheymans** [comment]
This issue refers to the "classic" zipkin UI which is no longer maintained (https://github.com/openzipkin-attic/zipkin-classic), please reopen against Lens if still applicable.
