### ISSUE TITLE
Many duplicate traces shown in zipkin web UI using Cassandra. SQLite was OK

### ISSUE THREAD

**Issue by hzhaofb** [openzipkin/zipkin#407]
I've been testing my instrumentation using Zipkin service with SQLite persistence store. Everything works well. However, in preparation of production release, I switched to use Cassandra 2.0.9, I see  large number of duplicate traces in the web UI, all pointing to the same trace link. 
![screen shot 2014-08-27 at 4 00 31 pm](https://cloud.githubusercontent.com/assets/7967571/4068928/1f477df6-2e3e-11e4-8bb3-b9d5355790b1.png)

Any help would be greatly appreciated. 

Howard. 

BTW, what Cassandra version is officially supported?

**Comment by hzhaofb** [comment]
Found following log showing duplicate traceIds in the ArrayBuffer.

error DEB [20140827-22:47:00.036] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], java.nio.HeapByteBuffer[pos=0 lim=8 cap=8]], ColumnParent(column_family:SpanNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)[0m
error DEB [20140827-22:47:00.051] query: getTraceSummariesByIds. traceIds: ArrayBuffer(-418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004, -418964871134254004) adjust ArrayBuffer(TimeSkew)[0m
error[0m] [0mDEB [20140827-22:47:00.052] cassie: multiget_slice(Zipkin, [-418964871134254004], ColumnParent(column_family:Traces), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:100000)), ONE)[0m
error[0m] [0mDEB [20140827-22:47:01.455] query: getServiceNames[0m

**Comment by boernd** [comment]
Did you find a solution to this problem?

**Comment by postwait** [comment]
I also have this problem... I had a trace repeat listed for each span it contains.

**Comment by postwait** [comment]
This works for me:

```
diff --git a/zipkin-web/src/main/scala/com/twitter/zipkin/web/Handlers.scala b/zipkin-web/src/main/scala/com/twitter/zipkin/web/Handlers.scala
index dbb14f9..0d5f7e7 100644
--- a/zipkin-web/src/main/scala/com/twitter/zipkin/web/Handlers.scala
+++ b/zipkin-web/src/main/scala/com/twitter/zipkin/web/Handlers.scala
@@ -76,7 +76,7 @@ class Handlers(jsonGenerator: ZipkinJson, mustacheGenerator: ZipkinMustache) {

         case ids =>
           val adjusters = getAdjusters(request)
-          client.getTraceSummariesByIds(ids, adjusters) map { _.map { _.toTraceSummary } }
+          client.getTraceSummariesByIds(ids distinct, adjusters) map { _.map { _.toTraceSummary } }
       }
     }
   }
```

**Comment by codefromthecrypt** [comment]
please verify. I think this is fixed now
