### ISSUE TITLE
zipkin-web display too narrow for long traces

### ISSUE THREAD

**Issue by erikvanoosten** [openzipkin/zipkin#414]
On some of our longer traces the default screen width is not sufficient. My screen is quite wide, still only 1170px are used while 1800px would fit nicely.

However, even with 1800px our longest (and most interesting) traces would not fit. It would be great if these are shown with a horizontal scroll bar.

**Comment by tdrisdelle** [comment]
Duplicate of one that I raised:
https://github.com/twitter/zipkin/issues/403

**Comment by rtyler** [comment]
Closing this as a duplicate
