### ISSUE TITLE
Typo in documentation 

### ISSUE THREAD

**Issue by drpacman** [openzipkin/zipkin#421]
Not sure if this is the right list to point out a typo in the QuickStart documention

http://twitter.github.io/zipkin/Quickstart.html

In the "Packaging for production" section it currently says to run

./bin/sbt "project zipkin-example/package-dist"

This should say
./bin/sbt "project zipkin-example" package-dist

**Comment by sprsquish** [comment]
Thanks for catching! Fixed.

The docs themselves will be part of the repo with the next sync. That should happen soon.
