### ISSUE TITLE
Replacing of Scribe on roadmap

### ISSUE THREAD

**Issue by schrepfler** [openzipkin/zipkin#428]
As Scribe seems to have been archived, is there any plan to replace it with something else?

**Comment by bmdhacks** [comment]
I haven't tried the Kafka receiver, does that not work?

**Comment by bmdhacks** [comment]
But no, there's no plans at twitter to replace scribe.

**Comment by eirslett** [comment]
I'm late here, but I think it should be possible to replace scribe with fluentd: https://github.com/fluent/fluentd
Fluentd comes with a Scribe plugin, so you wouldn't need to make any changes to the Zipkin source code.
It's also possible to set up fluentd with secure forwarding, so you could potentially ship your trace data to a public cloud, different from where you're running your application, and then run Zipkin there.

**Comment by kristofa** [comment]
You can also use [Flume](https://flume.apache.org/). It supports a ScribeSource (I guess like fluentd).  It did not have a Scribe Sink out of the box but you can use [flume-zipkin-collector-sink](https://github.com/openzipkin/flume-zipkin-collector-sink) and I also found [flume-ng-scribe](https://github.com/streamz/flume-ng-scribe) just now.

I used Flume with flume-zipkin-collector-sink as a drop-in replacement for Scribe and it worked well.

**Comment by eirslett** [comment]
It would be nice to have a logstash-compatible data collection pipeline as well. It should be safe to assume that people have something logstash-ish on their servers, if they are building a microservice platform in the first place?

**Comment by kristofa** [comment]
@eirslett Yes, agree. When I initially started integrating Zipkin we were actually using logstash but logstash had no codec support at that time. This is supported as of [version 1.2.0](https://logstash.jira.com/browse/LOGSTASH-658).  So I guess it should be possible now to use logstash with Thrift.

**Comment by eirslett** [comment]
I know fluentd does "routing pr topic", so you can send "zipkin" messages to zipkin-collector and "log" messages to elasticsearch/kibana. Can we do the same thing with logstash now?

**Comment by schrepfler** [comment]
I think this can be closed now as per https://github.com/openzipkin/zipkin-java/pull/30 ?

**Comment by codefromthecrypt** [comment]
Yeah I suspect so. Folks are generally moving towards Kafka, though some
use other systems like kenesis.

We have an issue about Kafka so maybe high time we call this a few real
decision ;)

**Comment by codefromthecrypt** [comment]
closed via #682
