### ISSUE TITLE
Support For Cassandra Internal Authentication In Client

### ISSUE THREAD

**Issue by kmckenney-PayPal** [openzipkin/zipkin#437]
This request is specifically aimed at providing support for connecting to Cassandra clusters configured to use 'org.apache.cassandra.auth.PasswordAuthenticator'.

**Comment by rtyler** [comment]
I believe this overlaps with some work that @jamescway did, which is getting superseded by @michaelsembwever's Datastax work

**Comment by jamescway** [comment]
Now that the big switch to use datastax is is committed, we can revisit this issue... :grin:

**Comment by michaelsembwever** [comment]
work is started in https://github.com/openzipkin/zipkin/commit/cb9f063f5e9b

it's implemented i believe but just needs a unit test for it.

**Comment by kmckenney-PayPal** [comment]
I realize that I didn't call it out in the original issue description, so maybe it should be addressed in a follow-on, but I believe the support for providing credentials should support the possibility of **securely** providing the credentials.

Different organizations will certainly have different mechanisms for providing these credentials, so perhaps the implementation should provide an interface for providing credentials. The default implementation may be as simple as the command line option approach used here (and/or securely prompting for credentials).

**Comment by michaelsembwever** [comment]
Yeah, i just wanted to throw a simple implementation out there to begin with.

You also have the AuthProvider class in the datastax cql driver, along with the PlainTextAuthProvider implementation of it.

**Comment by eirslett** [comment]
@michaelsembwever was this fixed?

**Comment by jorgheymans** [comment]
[Cassandra storage configuration](https://github.com/openzipkin/zipkin/tree/master/zipkin-server#cassandra-storage) has this option now:

```
* `CASSANDRA_USERNAME` and `CASSANDRA_PASSWORD`: Cassandra authentication. Will throw an exception on startup if authentication fails. No default
```
