### ISSUE TITLE
Builds are flakey and take way too long

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#440]
`./sbt clean test` is long on laptops and extremely long (like 30m) on travis. It often flakes on downloads, too. 

zipkin has a vast and uncached dependency tree. There are likely many ways to improve this.

**Comment by rtyler** [comment]
Hopefully some of @jamescway's work for #457 will help alleviate this, but I think this is a separate task unto itself

**Comment by rtyler** [comment]
I think @abesto's work moving us over to Gradle in  #503 has helped tremendously. I'm going to close this now
