### ISSUE TITLE
dynamic sample rates based on span/annotations, rather than just trace id

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#446]
Sample decision should be decoupled from span creation and not resolved locally. For example, in an unknown case, always buffer and use rules based on child spans to determine whether or not to sample. This particularly facilitates low-frequency sample decisions. For example, addressing 503 scenarios.

reported by @jpinner

**Comment by yurishkuro** [comment]
@adriancole 

> always buffer and use rules based on child spans

Buffer where? Given that spans of a single trace can be reported by different hosts to different collectors, it seems like this would need:
1. consistent hashing to assemble spans of the same trace in a single collector
2. short term storage of all traces, until sampling decision can be made and the trace is either saved or dropped

Is that what you had in mind?

**Comment by codefromthecrypt** [comment]
@yurishkuro I didn't have a design in mind, but your thoughts seem to be on the right path

**Comment by jorgheymans** [comment]
AFAIU this has been implemented, sampling can be done [declaratively](https://github.com/openzipkin/brave/tree/master/brave#declarative-sampling) or [custom](https://github.com/openzipkin/brave/tree/master/brave#custom-sampling) which is what this issue refers to:

```
SamplerFunction<Request> requestBased = (request) -> {
  if (request.url().startsWith("/experimental")) {
    return true;
  } else if (request.url().startsWith("/static")) {
    return false;
  }
  return null;
};
```
