### ISSUE TITLE
Move to OpenZipkin repo

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#453]
In support of community-driven zipkin, Twitter decided to join the OpenZipkin org, including moving the authoritative repository (currently twitter/zipkin) there.

This needs coordination with one of @rtyler @jamescway @michaelsembwever @eirslett as I think the zipkin fork there will need to be removed first.

**Comment by codefromthecrypt** [comment]
I believe twitter/zipkin has all the changes present in openzipkin/zipkin.

**Comment by rtyler** [comment]
@adriancole tomorrow let's move this, you will need admin privs to the twitter/zipkin repo and owner privs to openzipkin org (which you already have)

Once that's ready, I can walk you through it so we don't lose anytihng

**Comment by caniszczyk** [comment]
@adriancole should have the power now :)

**Comment by eirslett** [comment]
Remember to assign adrian to the issues first!

**Comment by codefromthecrypt** [comment]
and done!

**Comment by johanoskarsson** [comment]
Nice one!
