### ISSUE TITLE
Http Trace samplerate  don't work!

### ISSUE THREAD

**Issue by 3thinkthendoit** [openzipkin/zipkin#454]
when i use the samplerate  in the http trace like this:
Tracer tracer  = ZipkinTracer.mk(flumeIp, port,sr,Float.valueOf(sampleRate));

set the  samplerate  = 0 . The Tracer record the data again? why?

**Comment by 3thinkthendoit** [comment]
hi rtyler, sampleRate on http trace is a bug?

**Comment by rtyler** [comment]
@3thinkthendoit is this not a bug? I labelled it as such because the original title says that the sampleRote doesn't work

**Comment by 3thinkthendoit** [comment]
here is my java Code.

Tracer tracer = new SamplingTracer(new RawZipkinTracer(flumeIp, port, sr), Float.valueOf(sampleRate));

When i record the data with http filter:

```
    HttpServletRequest request = (HttpServletRequest) req;      
    HttpServletResponseWrapper response = new HttpServletResponseWrapper((HttpServletResponse) res);
    //logger.info("ContentType:"+request.getContentType());
    long parent = System.currentTimeMillis();
    SpanId spanId = SpanId.apply(System.nanoTime());
    TraceId traceId = TraceId.apply(Option.<SpanId> apply(spanId), Option.<SpanId> empty(), SpanId.apply(parent), Option.<Object>apply(Boolean.TRUE));
    Trace.pushTracerAndSetNextId(tracer, false);
    //Trace.pushTracerAndSetNextId(tracer,true);
    Trace.setId(traceId, false);
    Trace.record(new Annotation.ServerRecv());
    Trace.recordBinary("http.uri", request.getRequestURI());
    Trace.recordBinary("http.port", ""+request.getLocalPort());
    //记录参数
    for (String param : params)
    {
        if (request.getParameter(param) != null)
            Trace.recordBinary("param."+param, request.getParameter(param));
    }
    //Trace.recordBinaries(arg0);
    Trace.recordServiceName(("http-"+module).toLowerCase());
    Trace.recordRpc(request.getMethod());       
    Trace.recordClientAddr(new InetSocketAddress(request.getRemoteAddr(), request.getRemotePort()));
    Trace.recordServerAddr(new InetSocketAddress(NetUtil.getLocalHost(), request.getLocalPort()));
    try {
        chain.doFilter(request, response);
    } catch (Throwable t) {
        Trace.recordBinary("http.hasError", "true");
        Trace.recordBinary("http.error", t.getStackTrace());
        try
        {
            throw t;
        }
        catch (Throwable e)
        {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }               
    }
    //chain.doFilter(request, response);
    //Trace.setId(traceId, false);
    Trace.recordBinary("http.status",""+response.getStatus());
    Trace.record(new Annotation.ServerSend());
```

set the samplerate = 0.0f  the Treace should not record the span . But this recorded .why?

in the RPC finagle trace  set samplerate = 0.0f ,the record  is closed.

**Comment by codefromthecrypt** [comment]
Thanks for the code. I will try to convert this into a test case.

**Comment by codefromthecrypt** [comment]
Hi, @3thinkthendoit so I don't know how to move this to finagle.. if I could I would.

If I understand the issue correctly, you are suggesting that eventhough the finagle sampler is set to zero, it still sinks the trace.

There are tests that cover dropping traces when the sample rate is zero
https://github.com/twitter/finagle/blob/develop/finagle-zipkin/src/test/scala/com/twitter/finagle/zipkin/thrift/SamplerTest.scala#L37

For this reason, I suspect it may be a config issue. I'd have a look at this
https://github.com/twitter/finagle/tree/develop/finagle-zipkin

If you use the `ServerBuilder` or `ClientBuilder`, and assign a tracer there, it seems the case that you would be able to use it implicitly via `Trace.record` etc.

If you still have issues, I'd direct you to finaglers, as not only are there relevant topics there, but in the case you have found a bug, it would be addressable there.

https://groups.google.com/forum/#!searchin/finaglers/ZipkinTracer

Hope this helps
