### ISSUE TITLE
Replace Cassie with Datastax native driver

### ISSUE THREAD

**Issue by rtyler** [openzipkin/zipkin#458]
Currently Zipkin is using a [thrift-based means of talking with Cassandra](https://github.com/openzipkin/zipkin/tree/master/zipkin-cassandra/src/main/scala/com/twitter/cassie). Support for this [Thrift interface](https://wiki.apache.org/cassandra/ThriftInterface) will be removed in future versions of Cassandra.

@michaelsembwever has mentioned the desire to introduce support for the datastax-driver into `zipkin-cassandra`. This ticket is to capture that work

**Comment by abesto** [comment]
Can this be closed?

**Comment by eirslett** [comment]
+1
