### ISSUE TITLE
Programmatic Cassandra schema migration

### ISSUE THREAD

**Issue by rtyler** [openzipkin/zipkin#459]
Creating and updating the database schema (cassandra) manually is onerous and error prone. Creating a programmatic method for schema migration would help significantly in reducing human error and improve interaction with continuous build and delivery systems.

**Comment by michaelsembwever** [comment]
This can be done with the Repository.java class now.

Schema creation is automatic and tested.

I'm thinking with migration it's just about versioning the keyspace name and creating a new keyspace whenever there's an incompatible change.

Simple migrations for compatible changes can also be achieved (eg "ALTER TABLE...")
