### ISSUE TITLE
Add statsd instrumentation into Zipkin core services

### ISSUE THREAD

**Issue by rtyler** [openzipkin/zipkin#460]
I order to be have visibility into the health of the application it would be great to be able to record stats based on various metrics from within the applications (collector, query, web) 

This issue needs more thought in terms of:
- which stats need to be collected
- method of actual implementation
- configuration methods

Will add more info later.

**Comment by yurishkuro** [comment]
Given that existing implementation is based on Finagle, there are a lot of stats already being reported. However, they are not being emitted to any backend in the default configuration, and in fact there seems to be no external configuration mechanism aside from putting a text file in META-INF specifying the class name of the metrics backend.

**Comment by petemounce** [comment]
+1, would find it very useful if Zipkin emitted metrics to allow it to be monitored and alerted on.

**Comment by codefromthecrypt** [comment]
@petemounce have you seen this about metrics? https://github.com/openzipkin/zipkin/tree/master/zipkin-server#metrics

**Comment by jorgheymans** [comment]
Zipkin exposes its metrics via `/prometheus` endpoint now.
