### ISSUE TITLE
Documentation Improvement for Zipkin

### ISSUE THREAD

**Issue by rtyler** [openzipkin/zipkin#461]
(manually copied for @rAun007)

I have been using zipkin for almost like 2-3 months and I feel that the biggest hurdle in adoption is that documentation is missing and github pages doesn't have much as well.

Can somebody who knows in and out of the zipkin, can write documentation on the usage and the internals of the zipkin with the control levers that the user has along with recommended practices etc.

**Comment by jorgheymans** [comment]
While documentation improvement is always ongoing, we should use more specific issues to track those places where improvement is needed.
