### ISSUE TITLE
cassandra cluster for store. zipkin query throw exception!

### ISSUE THREAD

**Issue by 3thinkthendoit** [openzipkin/zipkin#465]
I have 3 cassandar(cluster)  nodes :
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens  Owns   Host ID                               Rack
UN  192.168.115.105  416.67 KB  256     30.6%  aa9265fb-b72d-46d5-a25a-42358c58e26b  rack1
UN  192.168.115.106  110.46 KB  256     36.5%  d3201d31-368a-4a80-9da8-51fce16a43ea  rack1
UN  192.168.115.102  110.54 KB  256     32.9%  639844e2-4300-416d-a25f-f0d3b164b381  rack1

and zipkin-query(query-cassandra.scala) config :  
// development mode.
val keyspaceBuilder = cassandra.Keyspace.static(nodes = Set("192.168.115.106"))
// val keyspaceBuilder = cassandra.Keyspace.static()
val storeBuilder = Store.Builder(
  cassandra.StorageBuilder(keyspaceBuilder),
  cassandra.IndexBuilder(keyspaceBuilder),
  cassandra.AggregatesBuilder(keyspaceBuilder))
QueryServiceBuilder(storeBuilder)

the zipkin-query work OK!
zipkin-web: http://192.168.115.106:9090/

when i kill the node(19.168.115.102)  like this 

UN  192.168.115.105  518.14 KB  256     30.6%  aa9265fb-b72d-46d5-a25a-42358c58e26b  rack1
UN  192.168.115.106  110.46 KB  256     36.5%  d3201d31-368a-4a80-9da8-51fce16a43ea  rack1
DN  192.168.115.102  110.54 KB  256     32.9%  639844e2-4300-416d-a25f-f0d3b164b381  rack1

visit the zipkin-web  throws exception like this:

UnavailableException()

com.twitter.zipkin.gen.QueryException$.decode(QueryException.scala:97)
com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$.readQeValue(ZipkinQuery.scala:5528)
com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$.decode(ZipkinQuery.scala:5449)
com.twitter.zipkin.gen.ZipkinQuery$getServiceNames$result$.decode(ZipkinQuery.scala:5368)
com.twitter.zipkin.gen.ZipkinQuery$FinagleClient.decodeResponse(ZipkinQuery$FinagleClient.scala:56)
com.twitter.zipkin.gen.ZipkinQuery$FinagleClient$$anonfun$getServiceNames$1.apply(ZipkinQuery$FinagleClient.scala:440)
com.twitter.zipkin.gen.ZipkinQuery$FinagleClient$$anonfun$getServiceNames$1.apply(ZipkinQuery$FinagleClient.scala:439)
com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:781)
com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:780)
com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:93)
com.twitter.util.Promise$Transformer.k(Promise.scala:93)
com.twitter.util.Promise$Transformer.apply(Promise.scala:102)
com.twitter.util.Promise$Transformer.apply(Promise.scala:84)
com.twitter.util.Promise$$anon$2.run(Promise.scala:324)
com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:129)
com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:107)
com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:150)
com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:59)
com.twitter.util.Promise.runq(Promise.scala:310)
com.twitter.util.Promise.updateIfEmpty(Promise.scala:605)
com.twitter.util.Promise.update(Promise.scala:583)
com.twitter.util.Promise.setValue(Promise.scala:559)
com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:71)
com.twitter.finagle.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:41)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
com.twitter.finagle.thrift.ThriftFrameCodec.handleUpstream(ThriftFrameCodec.scala:17)
org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
com.twitter.finagle.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:81)
org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)

when i start the node the  zipkin-query  is work!

**Comment by codefromthecrypt** [comment]
Sounds not great, but thanks for reporting.

What build of zipkin are you running? (Ex are you building off a fork? If
so, which commit?)
