### ISSUE TITLE
Migrate to newer, faster Travis CI infra

### ISSUE THREAD

**Issue by rtyler** [openzipkin/zipkin#468]
Looks like we're not using their newer builders, will send a PR imminently to switch us over

**Comment by codefromthecrypt** [comment]
I tried this and it glitched out for reasons I don't recall. Glad you are
giving it another go!

**Comment by rtyler** [comment]
@adriancole how did you discern between builder issues and #440? :)

**Comment by codefromthecrypt** [comment]
umm.. basically there's flakey tests (ones that require services that flake
out), and massive (and conflicting) dep trees. This is independent of
builders, but makes builders easier?
