### ISSUE TITLE
Remove build dependency on source force repositories

### ISSUE THREAD

**Issue by rtyler** [openzipkin/zipkin#469]
Seeing a lot of these in recent builds:

```
[error] SERVER ERROR: Service Unavailable url=http://freemarker.sourceforge.net/maven2/org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.jar
[error] SERVER ERROR: Service Unavailable url=http://freemarker.sourceforge.net/maven2/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.jar
[error] SERVER ERROR: Service Unavailable url=http://freemarker.sourceforge.net/maven2/org/eclipse/jetty/jetty-parent/18/jetty-parent-18.jar
[error] SERVER ERROR: Service Unavailable url=http://freemarker.sourceforge.net/maven2/org/eclipse/jetty/orbit/jetty-orbit/1/jetty-orbit-1.jar
```

Connectivity issues aside, Source forge distributes [malware](http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/) and is a pretty crap player nowadays.

**Comment by codefromthecrypt** [comment]
yanked for no good reason except yeah I can do this now.

**Comment by codefromthecrypt** [comment]
so.. I am trying to just remove the repository references for started. Running what I think is clean process locally.

``` bash
# supernuke to redownload all the things
$ rm -rf ~/.sbt/staging/  ~/.ivy2/cache/ ~/.m2/repository
$ sbt clean test
```

**Comment by codefromthecrypt** [comment]
that worked.. will raise a PR

**Comment by codefromthecrypt** [comment]
actually hold on.. testing that a related example still builds

**Comment by codefromthecrypt** [comment]
k https://github.com/openzipkin/zipkin/pull/471
