### ISSUE TITLE
Minimum viable Zipkin

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#486]
In attempts to keep the core codebase maintained, it seems we could do well to identify the minimum things that should stay in a monorepo, release those, then spin all else out.

Speaking from twitter's POV, the core components are easily identified by having pants files.

zipkin-collector
zipkin-common
zipkin-query
zipkin-scrooge
zipkin-thrift
zipkin-web
zipkin-cassandra // we don't use this any more, but many do
// the below are used for our internal deployments, particularly our custom collector, index and span store
zipkin-sampler
zipkin-receiver-scribe
zipkin-zookeeper

If we do a test deploy of the above components (perhaps as 1.2.0-alpha1 or something), I can verify that Twitter can work off openzipkin directly. Even if zipkin-receiver-scribe and zipkin-zookeeper were spun out, that would still be ok as long as they get released.

**Comment by rtyler** [comment]
Ah yes, MVZ

![mvz](https://pbs.twimg.com/media/B62lW6SIIAA8W_-.png)

Anyways, I think this is a reasonable step. What I would suggest also thinking about is what the criteria should be for something to be "core" versus not core. Cassandra/scribe are core more because of momentum it seems, should that always be the case? Is this the Zipkin Top Ten Most Wanted modules?

**Comment by codefromthecrypt** [comment]
About cassandra/scribe. I think it paints an accurate picture that at least zipkin 1.x has these as constants. Ex. if you look at projects like htrace, they write to scribe for zipkin interop.

When we move forward, especially when we prove we can do quick releases, I think it becomes less important, and spinning out scribe and/or cassandra could happen later. FWIW, internally, we are discussing alternatives to scribe.

**Comment by eirslett** [comment]
Is it possible to render a graph of the dependencies between the projects?

**Comment by jamescway** [comment]
+1 to this.  This would solve a lot of the monolithic problems that we've been facing with the build and simplify things.

**Comment by codefromthecrypt** [comment]
Discussion in gitter == this is something we can do after cutting 1.2

**Comment by abesto** [comment]
@eirslett Sure. Using a small snippet in the top of the top-level `build.gradle` (HAH!), this is what I get when processed through `dot` (from Graphviz):

![project-dependencies dot](https://cloud.githubusercontent.com/assets/59982/8876105/d859a15a-321d-11e5-804e-8230b6459643.jpg)

Snippet used to generate the dotfile: https://gist.github.com/abesto/cdcdd38263eacf1cbb51
The dotfile, if you want to play around with the visualization: https://gist.github.com/abesto/949730fb42a7b974a630

**Comment by eirslett** [comment]
Thanks a lot for the graph! It's quite connected...

**Comment by codefromthecrypt** [comment]
Note: mongo and hbase are currently spun-out as separate repos

**Comment by rtyler** [comment]
Should we close this ticket?

**Comment by codefromthecrypt** [comment]
+1

**Comment by eirslett** [comment]
There was a +1 on closing this ticket, so I'll do it!
