### ISSUE TITLE
Unable to fetch `sbt-launch.jar` properly

### ISSUE THREAD

**Issue by wjam** [openzipkin/zipkin#490]
Running `bin/sbt` without any `sbt-launch.jar` in the directory prints the following message:

```
downloading sbt-launch.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    221      0 --:--:-- --:--:-- --:--:--   222
bad sbtjar!: 70461da8b94c6ca5d2fda3260c5a8c3b
```

I believe the URL in `bin/sbt` should be changed to `https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/$sbtjar`, note the domain name. Correct URL found in SBT documentation (http://www.scala-sbt.org/0.13/tutorial/Manual-Installation.html)

**Comment by codefromthecrypt** [comment]
Just ran into this myself. Thx for the report.
