### ISSUE TITLE
zipkin-kafka indirectly depends on dead libraries

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#492]
zipkin-kafka has a complex build in part due to dependency on dead libraries via tormenta-kafka. This results in us having special resolvers like so. I wonder if we can integrate with kafka without pulling in a dependency tree like this.

```
// for storm-kafka
resolvers += "clojars" at "https://clojars.org/repo"
// com.twitter:kafka
resolvers += "conjars" at "http://conjars.org/repo"
```

**Comment by jamescway** [comment]
I took another look at zipkin-kafka and I realized that we don't actually use it.  It seems like this is an "experimental" library as the readme says, where zipkin-receiver-kafka is the module that we use.  I wonder if anybody really uses zipkin-kafka.

**Comment by codefromthecrypt** [comment]
This was added by twitter folks, and I know for a fact we don't use it. Since it is marked experimental and is causing grief, I suggest we either spin it out, and remove it, or just remove it.

@rtyler wdyt?

**Comment by eirslett** [comment]
I was thinking the same... why do we have both zipkin-kafka and zipkin-receiver-kafka... I think we should dump it.
