### ISSUE TITLE
refactor mocking approach

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#493]
Our mocking approach is fragile due to jmock class mocks. I attempted to increase the version and failed. It would be nice to be able to have a less complex build, and looks like a large part of that is reducing class mocks.

ex. here's what we need in order to have the build work at all

```
    "org.jmock"               %  "jmock"        % "2.4.0" % "test",
        // jmock tests mock classes and require additional dependencies.
        "cglib"                   %  "cglib"        % "2.2.2" % "test",
        "asm"                     %  "asm"          % "1.5.3" % "test",
        "org.objenesis"           %  "objenesis"    % "1.1"   % "test"
```

**Comment by codefromthecrypt** [comment]
First step is to consolidate. Currently, we have mockito used in cassandra for similar purposes. I'll take a stab at consolidating on mockito vs a mix of jmock and mockito.

**Comment by eirslett** [comment]
+1 for mockito :-)
