### ISSUE TITLE
Problem starting zipkin's docker

### ISSUE THREAD

**Issue by htaunay** [openzipkin/zipkin#517]
I have already added to my micro-services collectors and tested them through logging, and now I would like to actually send my trace data to a zipkin server.

Unfortunately following the default tutorial on the README doesn't seem to work as expected. I'm running **Yosemite**, installed **VirtualBox** (5.0.0) through its default dmg, installed **docker** (1.7.1), **boot2docker** (1.7.1) and **docker-compose** (1.3.3) through **brew**.

After running the suggested steps

``` bash
$ git clone https://github.com/openzipkin/docker-zipkin
$ cd docker-zipkin/deploy
$ docker-compose up
```

I get a series of ERROR logs in the **web**, **collector** and **query** processes (**cassandra** seems fine) that look more than INFO logs, and therefore I can't make much of them, hence this ticket. Here is an example of such output:

https://drive.google.com/file/d/0B60GjmIt4IMiazI4LUprVUZoQm8/view?usp=sharing

Any idea of what I may be doing wrong?

Obs: I saved the output with special escaped characters, in order to ease the reading. So I recommend reading the file with something like:

`less -R output.log`

**Comment by codefromthecrypt** [comment]
Mind opening this against the docker-zipkin repo?

**Comment by htaunay** [comment]
No problem
