### ISSUE TITLE
Migrate docs to asciidoc

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#518]
The [zipkin website](http://openzipkin.github.io/zipkin/) is running off the [gh-pages](https://github.com/openzipkin/zipkin/tree/gh-pages) branch of the zipkin repository.

The content is built using sphinx, from source in the doc folder. This process relies on python etc, which isn't a big deal in and of itself. More importantly, the content isn't using code that's already tested.

Let's consider asciidoc as an alternative. Something like https://github.com/jruby-gradle/jruby-gradle-plugin/tree/master/docs

**Comment by eirslett** [comment]
zipkin.io was recently fixed, thanks @abesto ! I'll close this issue, I don't think it's relevant any longer.
