### ISSUE TITLE
./gradlew idea mistakes zipkin-(query|collector)-service/config as a source folder

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#543]
A project imported from `./gradlew idea` incorrectly has `zipkin-(query|collector)-service/config` set as a source folder, not a resources folder. This means you have to manually correct it before the project will compile or run. 

Click File, Project Structure, zipkin-collector-service or zipkin-query-service, config, Resources

This is a bad experience and should be fixable.

**Comment by abesto** [comment]
This is because of https://github.com/openzipkin/zipkin/blob/master/zipkin-query-service/build.gradle#L26-L28 and friends. It's just a word-for-word translation of the relevant part of the old SBT build. I don't see the way forward at the moment, but I feel it shouldn't be too hard to fix.

**Comment by codefromthecrypt** [comment]
well.. we do need these in "resources", just not in a way that ends up
being mistaken as source files, if this makes any sense at all.

**Comment by abesto** [comment]
Alright, then a quick fix might be just moving the config dirs into `resources/main`. Will play around with this later this week.

**Comment by codefromthecrypt** [comment]
to warn you, I think other things expect a configs directory.. probably the
dist.

Thanks for having a look!

**Comment by abesto** [comment]
Just managed to load the whole context back from swap. The `config` dirs are used for two things:
- example configuration for distributed stuff, like you mentioned
- tests called `ConfigSpec`

They were included in the source set to let the `ConfigSpec` tests find them, but I should be able to work around that without adding the `config` dir to the source sets. In the long run, this of course ties into the whole "configuration done right" topic (#466)

**Comment by codefromthecrypt** [comment]
Yeap. As long as fat jars still work (ie they are packaged in them), dist
still works (config dir is present), and something tests they compile.. All
good!

Hopefully as you say.. They will have a short life :)
