### ISSUE TITLE
Update gradle-bintray-plugin to 1.3 when its released

### ISSUE THREAD

**Issue by jamescway** [openzipkin/zipkin#559]
See https://github.com/bintray/gradle-bintray-plugin/issues/68

We need update the plugin when it is released.

This should solve the problem, when jars are bintrayUpload'ed they are not published and you need to bintray.com to click the publish link.

**Comment by codefromthecrypt** [comment]
This should hopefully result in publication of the fat jars cc @dsyer

**Comment by abesto** [comment]
Fat jars not being published was a different issue, fixed in https://github.com/openzipkin/zipkin/pull/561

**Comment by abesto** [comment]
According to https://bintray.com/jfrog/jfrog-jars/gradle-bintray-plugin/view 1.3 has been out for a couple of days (just the readme is not updated; but the badge in the readme is). Is there anything holding us back from upgrading?

**Comment by codefromthecrypt** [comment]
Dooo iittt ;)
