### ISSUE TITLE
Retain SpanStore, delete Index, Storage

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#567]
Per https://groups.google.com/d/msg/zipkin-dev/GY_jEI5pQY8/MAfOukbGBgAJ we will remove the com.twitter.zipkin.storage.Index/Storage types for SpanStore asap. The duplicate hierarchies cause confusion and maintenance burdens we can't afford.

**Comment by codefromthecrypt** [comment]
The entrypoint for query is `ThriftQueryService` not `QueryService`

**Comment by eirslett** [comment]
@adriancole was this fixed?

**Comment by codefromthecrypt** [comment]
irrelevant now, mountains have moved since :)
