### ISSUE TITLE
Move to SpanStore normal java.io.Closeable

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#584]
As mentioned in #451, some types are not instantiatable due to how they mix in Closable.

There's a pattern of use like this..

``` scala
  with com.twitter.util.Closable
  with com.twitter.util.CloseAwaitably
```

I suggest that we use `java.io.Closeable` instead. Eventhough it is a synchronous call, many of our implementations perform synchronous state cleanup. It is also extremely common practice for `close()` to be synchronous, including being built-into the java language (try-with-resources).

If we decide that asynchronous `.close` is required, we could experiment with how bad it is by adding a `src/test/java` tree and putting an example impl there. Even then, we may want to still support synchronous close, similar to how rxnetty has both `closeNow()` and `close()`.

**Comment by codefromthecrypt** [comment]
folks who might care to weigh in: @eirslett @jpinner @niteshkant @dsyer @spencergibb

**Comment by eirslett** [comment]
I have no strong opinions. Scala traits (e.g. SpanStore) aren't instantiatable from Java anyways, you'll need to make an abstract class that mixes in the trait, and then in Java extend from that class. Will moving to j.u.Closeable solve that?

**Comment by codefromthecrypt** [comment]
It gets us closer, I think. It seems SpanStore could transition to an
interface if it wasn't being mixed in with traits itself.

**Comment by codefromthecrypt** [comment]
I think this should wait until we can build Java 8 bytecode. As @eirslett says.. there's a lot of other things that limit work, and Closeable is just part of it. interfaces with default methods are the bridge point, but unfortunately there's a lot in our dep chain that isn't java 8 ready.

**Comment by NiteshKant** [comment]
I think the `try-with-resources` is a good case for using `java.io.Closeable` which makes the code terse so +1 for that! In RxNetty, the primary usage of close is async, so, I couldn't use `Closeable`.

**Comment by codefromthecrypt** [comment]
so does that put you in the "both" camp? :)

**Comment by NiteshKant** [comment]
:) I think they both have their uses. I would use async `close()` for something like a channel, request, response, etc which will be called inline with request processing. For infrequent tasks, a synchronous close is appropriate/sufficient. I do not have insight into zipkin code to have an opinion about specific `close()` uses.

**Comment by codefromthecrypt** [comment]
SpanStore is the storage behind collectors or query services. In current implementations, it is application scoped, and close is invoked as a shutdown hook. I will switch the title to SpanStore uses Closeable :)

**Comment by codefromthecrypt** [comment]
Thought a lot about this recently.. I think it is best to just leave off Closeable from the interfaces completely. This defers how to express close-ability to the implementing types, which might choose to be java closeable or twitter closeable or something else. Didn't really consider the option to just "punt" before!
