### ISSUE TITLE
New Cassandra schema may create hot spots

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#623]
Hi, I just pulled the recent code, and while it's great to see an upgrade from thrift-based schema in Cassandra to proper CQL, wouldn't the new schema create hot spots by not using the previous bucketing technique?  For example, the new schema for indexing spans by service name

```
CREATE TABLE zipkin.service_name_index (
    service_name text,
    ts timestamp,
    trace_id bigint,
    PRIMARY KEY (service_name, ts)
```

The `service_name` here serves as the row key, so for a heavily loaded service ALL spans will be hitting a single partition. The previous implementation was adding a random bucket number 1-10 to the service name, so that the inserts were uniformly distributed across 10 nodes, at the cost of having to do 10 queries when reading by service name. The previous bucketing would be roughly equivalent to this new schema:

```
CREATE TABLE zipkin.service_name_index (
    service_name text,
    bucket tinyint,
    ts timestamp,
    trace_id bigint,
    PRIMARY KEY ((service_name, bucket), ts)
```

**Comment by yurishkuro** [comment]
Another observation - before the upgrade the Zipkin code had a -D switch to control the number of buckets, such that setting that param to 1 bucket would've been equivalent to the current/new schema. If we extend the schema as suggested above, people will have an option to use or not use the bucketing, with little overhead if they don't want to use it.

**Comment by michaelsembwever** [comment]
Indeed there will be hot spots on the `service_name` in this table.
That there was bucketing happening before I definitely missed.

**Comment by michaelsembwever** [comment]
bucketCount and "zipkin.store.cassie.indexBuckets", as you mention defaulted to ten previously.

**Comment by yurishkuro** [comment]
it's pretty much in all tables, e.g. annotations_index for standard annotations like cs/cr/ss/sr will be always hitting row key `"${serviceName}:${annotation}"`. The old code was using BucketedColumnFamily for most of the tables.

**Comment by michaelsembwever** [comment]
yes. thanks for spotting this. i'll have a fix out in the next hour or so.

**Comment by yurishkuro** [comment]
also, if we go for a dedicated bucket column included in the composite row key, I would suggest changing the schema for annotations_index. Right now it is stored as a composite string `${serviceName}:${annotation} [:$annotationValue]`. I would suggest the following schema instead:

```
CREATE TABLE IF NOT EXISTS zipkin.annotations_index (
    service_name      string,
    annotation_name   string,
    annotation_value  blob, -- optional for non-binary annotations.
    bucket_no      tinyint,
    ts             timestamp,
    trace_id       bigint,
    PRIMARY KEY ((service_name, annotation_name, annotation_value, bucket_no), ts)
)
```

**Comment by michaelsembwever** [comment]
that would be a separate ticket @yurishkuro 
i looked into that while doing the related pull request, but because there's a blob there i left it for now. in a later pull request i'd like to remove all the blobs so we have a completely transparent schema.

**Comment by yurishkuro** [comment]
at least keeping the bucket number as a separate column would be useful to start with.

**Comment by michaelsembwever** [comment]
@yurishkuro you want to take a look at that pull request for us?

**Comment by yurishkuro** [comment]
Looks good, just missing the schema change for `service_name` table.

**Comment by michaelsembwever** [comment]
i really don't think bucketing will help for service_name.

and while we get hot partitions there, beyond "tombstones" (old writes), each partition only ever has one column. it might be smarter to change the compaction to LeveledCompactionStrategy rather than bucketing. i also added a comment in the code regarding caching writes, since this table is going to see basically just duplicated writes going to it.

**Comment by yurishkuro** [comment]
I agree, bucketing doesn't seem particularly helpful for service names. But the pull request does contain code to use buckets for this table, so I was pointing out to mismatch with the schema. Maybe undo the code change for this table?

**Comment by michaelsembwever** [comment]
noooooo, where? :-) 

(might be easier to write those comments against the code lines in the PR)

**Comment by yurishkuro** [comment]
sorry. my bad, got tripped by the column name. Good to go!

**Comment by yurishkuro** [comment]
@michaelsembwever when do you plan to merge this? 

I've tested with my collector (written in Go), the new schema works well.

**Comment by michaelsembwever** [comment]
it's merged
