### ISSUE TITLE
hang at bintrayUpload

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#644]
so at the binTray upload step, the build times out like this.

```
:zipkin-aggregate:bintrayUpload
:zipkin-anormdb:bintrayUpload
:zipkin-cassandra:bintrayUpload
:zipkin-cassandra-core:bintrayUpload
:zipkin-collector:bintrayUpload
:zipkin-collector-scribe:bintrayUpload
:zipkin-collector-service:bintrayUpload
:zipkin-common:bintrayUpload
:zipkin-example:bintrayUpload
:zipkin-query:bintrayUpload
:zipkin-query-service:bintrayUpload
:zipkin-receiver-kafka:bintrayUpload
:zipkin-receiver-scribe:bintrayUpload
:zipkin-redis:bintrayUpload
:zipkin-redis-example:bintrayUpload
:zipkin-sampler:bintrayUpload
:zipkin-scrooge:bintrayUpload
:zipkin-thrift:bintrayUpload
:zipkin-tracegen:bintrayUpload
:zipkin-web:bintrayUpload
:bintrayUpload
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

https://travis-ci.org/openzipkin/zipkin/jobs/76552907

When you browse to https://bintray.com/openzipkin/zipkin/zipkin/view, you file it waiting for you to click publish. Once you do.. you can actually successfully click sync to maven https://bintray.com/openzipkin/zipkin/zipkin/1.2.1-rc24/view#central

So, what's up with the hang at bintrayUpload?

**Comment by codefromthecrypt** [comment]
similar status

```
Found 1 configuration(s) to publish.
Uploading to https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25.jar...
Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25.jar'.
Uploading to https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25-javadoc.jar...
Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25-javadoc.jar'.
Uploading to https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25-sources.jar...
Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25-sources.jar'.
Uploading to https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25-all.jar...
Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25-all.jar'.
Uploading to https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25.pom...
Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-rc25/io/zipkin/zipkin-web/1.2.1-rc25/zipkin-web-1.2.1-rc25.pom'.
:zipkin-web:bintrayUpload (Thread[Daemon worker,5,main]) completed. Took 34.463 secs.
:bintrayUpload (Thread[Daemon worker,5,main]) started.
:bintrayUpload
Executing task ':bintrayUpload' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
Found 0 configuration(s) to publish.
```

**Comment by abesto** [comment]
Went on after a couple of minutes (https://travis-ci.org/openzipkin/zipkin/jobs/76685357). The first line was that signing the version was completed. It continued at around the time @adriancole manually pushed the publish button on the UI; may or may not be related.

**Comment by rtyler** [comment]
Is signing happening on bintray's side or in Travis?

**Comment by abesto** [comment]
Bintray. That line is logged at https://github.com/bintray/gradle-bintray-plugin/blob/adb397a261b87e9baff9c264bd1347e61290a3fb/src/main/groovy/com/jfrog/bintray/gradle/BintrayUploadTask.groovy#L301 when https://bintray.com/docs/api/#_gpg_sign_a_version finishes

**Comment by abesto** [comment]
Cloud be useful to try to get HTTP request logs, maybe `--debug` would do it, or some other workaround

**Comment by codefromthecrypt** [comment]
I'll tag again and just wait longer.. Not clicking anywhere. Let's see if
it just finishes.

**Comment by codefromthecrypt** [comment]
Actually, could someone else tag? 1.2.1-rc26

Takes a while to finish and I'm afk

**Comment by rtyler** [comment]
@abesto is there a downside to disabling signing in general?

**Comment by abesto** [comment]
Maven central requires artifacts to be signed.

**Comment by abesto** [comment]
Probably something about security as well :-)

**Comment by codefromthecrypt** [comment]
maybe we can add logging to the signing routine? (if they accept pull requests). perhaps our huge jars take a while to sign.

**Comment by codefromthecrypt** [comment]
calling this done. 2 successful deploys in a row. Key is to _wait_. Also wait at least 5 minutes before clicking on maven sync button in bintray.

**Comment by codefromthecrypt** [comment]
This is timing out again.. when it does, here's the command to sign manually. Then, go to bintray and publish the artifacts.

``` bash
# substitute whatever version instead of 1.8.1
$ curl https://$USER:$BINTRAY_API_KEY@api.bintray.com/gpg/openzipkin/maven/zipkin/versions/1.8.1 -XPOST
```
