### ISSUE TITLE
Set redis socket with environment variable

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#655]
Similar to how we work with cassandra, we should be able to set the redis socket using an environment variable.
https://github.com/openzipkin/zipkin/blob/master/zipkin-collector-service/config/collector-cassandra.scala#L26

This would allow us to make docker files similarly to how we do with cassandra.
https://github.com/openzipkin/docker-zipkin/blob/master/collector/run.sh#L8

Cassandra naturally supports multiple endpoints, hence the name `CASSANDRA_CONTACT_POINTS`. Redis clients typically only connect to a single endpoint. Looking at redis-cli and hiredis, there's no interesting name for this. Perhaps we just choose `REDIS_SOCKET`?

**Comment by codefromthecrypt** [comment]
@dsyer @spencergibb any good choices of env variable name?

**Comment by dsyer** [comment]
Not that I know of. But maybe a `REDIS_[HOST,PORT,PASSWORD]`?

**Comment by codefromthecrypt** [comment]
done
