### ISSUE TITLE
Cannot change port of the query service

### ISSUE THREAD

**Issue by wadey** [openzipkin/zipkin#659]
After this commit, it is no longer possible to change the port of the query service:
- https://github.com/openzipkin/zipkin/commit/35a3891e664ceb4d7584a6a808a110299876016b#diff-5e7107cba5b23b0e69b1ae6e8cff978fR60

Previously, you could do this to change the port:

```
val serverBuilder = ZipkinServerBuilder(9416, 9906)
QueryServiceBuilder(storeBuilder, serverBuilder)
```

But this no longer works. From reading the source, it looks like this should work now but it doesn't work either:

```
java -jar … -D zipkin.queryService.port=127.0.0.1:9416
```

**Comment by codefromthecrypt** [comment]
sorry it is a bit of a mess.. I'll look at this after catching up on change like https://github.com/openzipkin/zipkin/commit/c69db3bfffb855f766ba1754cfe35e7bcc12fce5

**Comment by codefromthecrypt** [comment]
completely knackered, but agree this is really bad. please nag on https://gitter.im/openzipkin/zipkin if this becomes critical and still left undone.

**Comment by wadey** [comment]
I'm using the following workaround to make this work on my fork:
- https://github.com/betable/zipkin/commit/4bd522fc7d81d8c30877b3817c9e1095874743f9

It goes back to using the value set in the ZipkinServerBuilder.

**Comment by codefromthecrypt** [comment]
Looks like this was partially implemented as environment variables in collector like so

``` scala
val serverPort = sys.env.get("COLLECTOR_PORT").getOrElse("9410").toInt
val adminPort = sys.env.get("COLLECTOR_ADMIN_PORT").getOrElse("9900").toInt
```

Mind if I just implement that convention with COLLECTOR, QUERY, WEB?

**Comment by wadey** [comment]
Yeah I like that idea, that is how I am configuring our collector service. I have the following in my query.scala config (which works with the above patch):

``` scala
val serverPort = sys.env.get("QUERY_PORT").getOrElse("9411").toInt
val adminPort = sys.env.get("QUERY_ADMIN_PORT").getOrElse("9901").toInt

…

QueryServiceBuilder(
  storeBuilder,
  serverBuilder = ZipkinServerBuilder(serverPort, adminPort).loggers(List(loggerFactory))
)
```

I basically copied what collector was doing in its config.

**Comment by wadey** [comment]
Thanks @adriancole!

But your patch is actually incomplete and doesn't change the query port (try to change QUERY_PORT and see what happens). You need something like the changes I have for QueryServiceBuilder and ZipkinQueryServerFactory here:
- https://github.com/betable/zipkin/commit/4bd522fc7d81d8c30877b3817c9e1095874743f9

**Comment by codefromthecrypt** [comment]
Yep you're right! https://github.com/openzipkin/zipkin/pull/714/files

**Comment by codefromthecrypt** [comment]
should be good, now
