### ISSUE TITLE
End-to-End example of HTrace-Zipkin (via Kafka)

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#682]
@clehene noted that the architecture diagram doesn't explain kafka well. Regardless of implementation, we should make it clear, what's going on. Maybe by switching to @abesto's dot approach to diagramming.

Here's what we're looking for

```
htrace instrumentation -> kafka <- zipkin-kafka-receiver -> SpanStore <- zipkin-query <- zipkin-web
```

Also.. we actually want this to work.

**Comment by codefromthecrypt** [comment]
For those watching at home.. the collector can now have kafka enabled. There's configuration options here: https://github.com/openzipkin/zipkin/tree/master/zipkin-receiver-kafka

can't wait to see @clehene's end-to-end

**Comment by clehene** [comment]
https://issues.apache.org/jira/browse/HTRACE-235

**Comment by codefromthecrypt** [comment]
PS besides htrace, I think we should inventory other kafka instrumentation. For example, Brave, Ruby and Finagle. At some point, we should be able to trace zipkin itself without scribe, too.

**Comment by eirslett** [comment]
HTrace support is dropped (or at least moved to a separate repository) so I'll close this issue.

**Comment by codefromthecrypt** [comment]
htrace, not hbase :) Anyway, e2e tests aren't likely to happen in this repo.

**Comment by eirslett** [comment]
Ooos, sorry :-P
