### ISSUE TITLE
Documentation mentions zipkin-example which doesn't exist 

### ISSUE THREAD

**Issue by clehene** [openzipkin/zipkin#683]
e.g. https://github.com/openzipkin/zipkin/blob/master/doc/src/sphinx/Quickstart.rst

**Comment by adarshaj** [comment]
I am stuck because of this! Where should I start?

**Comment by codefromthecrypt** [comment]
I'll delete it now. should unblock you

**Comment by codefromthecrypt** [comment]
The problem is that we are publishing examples that are neither valid nor exist.

**Comment by adarshaj** [comment]
:+1:
