### ISSUE TITLE
Much confusion about storage

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [openzipkin/zipkin#686]
Hi,

The [documentation says](http://zipkin.io/Architecture.html)

> We originally built Zipkin on Cassandra for storage. It’s scalable, has a flexible schema, and is heavily used within Twitter. However, we made this component pluggable, and we now have support for Redis, MySQL, PostgreSQL, SQLite, and H2.

But nowhere is it documented how to achieve this, or at least I couldn't find it.

The [gradle.properties file refers to backend switching](https://github.com/openzipkin/zipkin/blob/master/gradle.properties#L17-L34) but the naming is confusing. 
"configKey=dev" stands for using AnormDB, and if I read that correctly it needs to be set when switching to a different backend. 
Are we to infer from this name that backends other than cassandra or redis are not production-ready?
Are there known caveats associated with using RDBMS backends?

To give some context we are evaluating Zipkin and being able to do without Cassandra would be a big plus. We have lots of MySQL instances around with qualified people to oversee them, we'd rather not introduce yet another storage solution in the mix.

**Comment by codefromthecrypt** [comment]
This is a documentation bug. Twitter doesn't use cassandra anymore, and regardless, we should bring this up to speed.

configKey=dev is a specific anormdb setup that uses file sharing. We could quite easily add a mysql config based on a jdbc connect string. I've wondered myself why we haven't (that or postgres). I can help fix the doc bug, but can you share a little more about how you'd be deploying this? docker?

**Comment by jfeltesse-mdsol** [comment]
All deployment options are on the table at this stage, docker could be it as well as building & deploying on AWS instances manually.

Your reply leads me to ask another question, if Cassandra is being phased out why is the docker-zipkin project relying on it? What is the recommended storage backend these days? (I guess the answer is "it depends", I'm just trying to find out which option is going to be the best supported).

**Comment by eirslett** [comment]
Twitter the company isn't using Cassandra anymore, but Zipkin the open source software is using Cassandra a lot (I think Cassandra is regarded as the main storage backend)
Zipkin was originally written at Twitter, but now, the project has been moved out into its own organisation.

**Comment by codefromthecrypt** [comment]
cassandra remains the most supported, as it is used in docker, etc. as
Eirik mentioned zipkin is its own thing. Feel free to join us!
https://gitter.im/openzipkin/zipkin

**Comment by codefromthecrypt** [comment]
ps #853 trims SQL databases to a more relevant list, namely drivers you can configure OOB
