### ISSUE TITLE
Scripts not working per README

### ISSUE THREAD

**Issue by dsyer** [openzipkin/zipkin#697]
If I run `./bin/collector` it seemed to work OK the first time. Now I get this:

```
...
FAILURE: Build failed with an exception.

* Where:
Build file '/home/dsyer/dev/cloud/zipkin/build.gradle' line: 10

* What went wrong:
Error resolving plugin [id: 'com.jfrog.bintray', version: '1.3.1']
> Timeout waiting to lock Plugin Resolution Cache (/home/dsyer/.gradle/caches/2.6/plugin-resolution). It is currently in use by another Gradle instance.
  Owner PID: 7222
  Our PID: 7302
  Owner Operation: queryPluginMetadata - read
  Our operation: queryPluginMetadata - read
  Lock file: /home/dsyer/.gradle/caches/2.6/plugin-resolution/cache.properties.lock

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleException: Error resolving plugin [id: 'com.jfrog.bintray', version: '1.3.1']
...
```

I deleted the lock file and the same thing happened again.

IMO, using gradle to run these processes is a bad idea anyway (who is going to do that in a real environment?). I don't mind building the jars and running those, and I have a feeling it would be quicker (the gradle startup is very slow)
.

**Comment by codefromthecrypt** [comment]
you're right.. it can get flakey. should we change the scripts to package (not via clean so it is faster) and launch the jar directly?

**Comment by codefromthecrypt** [comment]
fwiw.. if ever I run into a problem, I repeat after a `./gradlew clean`

**Comment by codefromthecrypt** [comment]
I don't think we are going to change the dev instructions right now, as they work for most people
