### ISSUE TITLE
Allow caching of getServices in the UI

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#718]
From @yurishkuro 

> the query to get all service names in Cassandra needs to hit every node in the cluster. We've been seeing strange huge latencies with it recently, still investigating. To mitigate the impact, I've added a cache of service names in Cassandra span storage, which periodically refreshes itself.

I think we should solve this at the HTTP abstraction, ex. sending cache headers back, so that the client doesn't call so much.

There are two endpoints on zipkin-web that call `getServices`
- `/` - part of a massive thing that includes enumerating all services, to pass to `index.mustache`
- `/api/services` - possibly unused json string list

I see two things to do:
- change `index.mustache` to use javascript to GET /api/services and fill the `Service Name` selector by itself
- change `handleServices` to return cache headers

**Comment by codefromthecrypt** [comment]
@mzagar @eirslett either of you have some cycles to help with this by chance?

**Comment by mzagar** [comment]
I believe I can take a look at this one.

**Comment by codefromthecrypt** [comment]
Great. I suspect this won't impact you if you are only working in
JavaScript layer. But just in case:
https://github.com/openzipkin/zipkin/pull/728

**Comment by michaelsembwever** [comment]
> the query to get all service names in Cassandra needs to hit every node in the cluster. 

best to increase RF of the zipkin keyspace.
(answers more to the availability than performance)

> I think we should solve this at the HTTP abstraction, ex. sending cache headers back, so that the client doesn't call so much.

:+1:

**Comment by codefromthecrypt** [comment]
so realizing that the getServices isn't actually called by the javascript yet. Also, I noticed a special case. WDYT about this?

if services.size < 3 don't cache
otherwise set TTL on the http response to 30 seconds?

**Comment by mzagar** [comment]
Isn't 30 seconds a bit low - are new services created that often? I was thinking about adding a property allowing to set this timeout to a custom value at web startup and setting the default to 5 minutes, is that too long?

Optimization when not to cache sounds good.

I'll make a PR fpr the js side later today. I noticed /api/services was removed from available endpoints... should I put that back in?

**Comment by codefromthecrypt** [comment]
Honestly I don't know what's the right value.. there's a special case of
bootstrapping, which I think the minimum count would cover.. Perhaps 5m
after that is a decent value. Probably only way to find out is to spike it!

Thanks for the offer for the javascript change! Note that ideally we'd
remove the call from Handlers.scala while at it.

**Comment by codefromthecrypt** [comment]
@mzagar "/api/services" can be put back in.. sure. We just want to remove the call in the Handlers.scala side once that's done.

PS we had a chat on https://gitter.im/openzipkin/zipkin about wanting to do caching at the http-level, addressed by the browser. Browsers know how to deal with cache headers w/o creating special-caches in scala :) Best way forward is to do as much as possible to get the UI javascript-only. Put another way, a tactical scala cache just for services would probably end up as tech debt.

**Comment by codefromthecrypt** [comment]
@yurishkuro @eirslett let's continue the chat from https://github.com/openzipkin/zipkin/pull/983#discussion_r53009101 here, as the history is here

**Comment by codefromthecrypt** [comment]
To summarize status quo, the query server sends back a cache header when there are more than 3 services present:

``` scala
assert(response.headerMap.get("Cache-Control") == Some("max-age=300, must-revalidate"))
```

https://github.com/openzipkin/zipkin/blob/master/zipkin-query/src/test/scala/com/twitter/zipkin/query/ZipkinQueryServerFeatureTest.scala#L167

The actual age is assigned via the flag "zipkin.queryService.servicesMaxAge", which is incidentally not currently mapped as an environment variable.

The zipkin-web server _should_ forward this header all the way to javascript (or any other caller). I suspect if it wasn't, @mzagar would have complained :P However, we have no test on zipkin-web to verify forwarding doesn't lose the header. The main reason is that zipkin-web is an older framework than finatra, and doesn't support feature tests.

**Comment by codefromthecrypt** [comment]
PS something Eirik mentioned was interesting.

If 100s of service names strings are that slow, and for some reason HTTP cache headers aren't an option, a decorating SpanStore which caches in memory would be something those doing custom builds could add, if the middleware itself doesn't have a caching feature.

**Comment by eirslett** [comment]
We could add a cache layer with an environment variable to set TTL (default to 0 seconds, which disables the cache?)
Ideally, people shouldn't have to do custom builds, if we can avoid it?

**Comment by eirslett** [comment]
Another option is to deploy varnish as middleware on top of zipkin-query, to handle the caching. Then we only need cache headers, but the deployment becomes much more complex.

**Comment by codefromthecrypt** [comment]
> We could add a cache layer with an environment variable to set TTL
> (default to 0 seconds, which disables the cache?)
> Ideally, people shouldn't have to do custom builds, if we can avoid it?
> 
> I don't really want to do anything on this :) but the practical issue on
> cassandra remains, so happy to discuss.

I really think we should get most mileage out of the other cache setting we
have now (cache-control). If we find this is a fools errand, I'd prefer we
remove it and make a different parameter that works. one in-one out.

In general I don't like the idea of doing in-memory caching in the query
server. Guava and similar caches add more edge cases to the code, and in
this case, it is one api that sends very little data. What happens if
somehow spanNames degrades in performance.. do we need another env property?

**Comment by yurishkuro** [comment]
> a decorating SpanStore which caches in memory would be something those doing custom builds could add, if the middleware itself doesn't have a caching feature

We already did that a few months ago, and I am still occasionally seeing the dropdown staying blank for a second or more after page loading. I feel it's a combination of transferring large JSON (via two hops due to query service running separately) and DOM creation altogether result in this visible latency. It just seems like the wrong design that the UI needs to keep re-loading this large list. Soon our list of services will be approaching a 1000.

**Comment by eirslett** [comment]
I haven't tested the UI with 1000 service names yet. Might be worthwhile to stub the JSON API calls, and measure the impact on DOM rendering time in isolation?

**Comment by codefromthecrypt** [comment]
> We already did that a few months ago, and I am still occasionally seeing
> the dropdown staying blank for a second or more after page loading. I feel
> it's a combination of transferring large JSON (via two hops due to query
> service running separately) and DOM creation altogether result in this
> visible latency. It just seems like the wrong design that the UI needs to
> keep re-loading this large list. Soon our list of services will be
> approaching a 1000.
> 
> Thanks for the updating us on things tried so far, @yurishkuro!

So, there are plenty of control and monitoring UIs with relatively stable things like buckets, application lists or tenants. I doubt that the supporting UIs require modification to the services they serve. Ex I doubt someone changed S3 bucket api to cache in support of AWS console, although S3 bucket list is quite a fast api anyway! I tend to see refresh buttons on UIs.. but I'm sure there are other ways, too (ex buddy servers etc)

Is there a way we can solve this lag problem without affecting the query server directly? I'd prefer us to not have the maintenance of special-casing certain endpoints due to rendering delays, if at all possible.

**Comment by eirslett** [comment]
I tried creating 1000 service names in the UI to measure the impact on rendering time:

``` diff
diff --git a/zipkin-web/src/main/resources/app/js/component_ui/serviceName.js b/zipkin-web/src/main/resources/app/js/component_ui/serviceName.js
index f5b4cc6..55fb66e 100644
--- a/zipkin-web/src/main/resources/app/js/component_ui/serviceName.js
+++ b/zipkin-web/src/main/resources/app/js/component_ui/serviceName.js
@@ -23,6 +23,11 @@ define(

       this.updateServiceNameDropdown = function(ev, data) {
         $('#serviceName').empty()
+        data.serviceNames = [];
+        for (let i = 0; i < 1000; i++) {
+          data.serviceNames.push('service'+i);
+        }
+
         $.each(data.serviceNames, function(i, item) {
             $('<option>').val(item).text(item).appendTo('#serviceName');
         });
```

This basically replaces the API response with a list of service names, service0, service1, service2 ... service999.
The impact on rendering time was minimal, there was no visual cue showing that the latency was higher than when rendering 15-20 service names.

**Comment by mansu** [comment]
We have hundreds of services here at pinterest and we see the lag in the UI dropdown being populated. So my experience is same as @yurishkuro's. Can we add an environment variable to set the zipkin.queryService.servicesMaxAge?

**Comment by codefromthecrypt** [comment]
@mansu are you saying that your browsers aren't honoring the cache-control headers? or that you feel the timeout is too short?

Bear in mind that the UI is pure javascript and hits a normal http api. In other words, cache headers can also be affected by nginx or similar normal web tier tech.

https://github.com/openzipkin/docker-zipkin/blob/master/zipkin-ui/nginx.conf

ex. here's a caching option https://www.nginx.com/resources/wiki/start/topics/examples/reverseproxycachingexample/

**Comment by codefromthecrypt** [comment]
@mansu lol it is already configurable, just not documented

Here's the default, which is in seconds.

zipkin.query.names-max-age:300

This value can be overridden by system properties or any other [alternative supported by Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html). For example, you can upper-case it as an ENV variable. `ZIPKIN_QUERY_NAMES_MAX_AGE=10000000`

**Comment by mansu** [comment]
@adriancole ah, that works also. Looked around for setting values via command line but couldn't find anything right away. Thanks!

**Comment by jcchavezs** [comment]
I don't know the status of this issue but given that we have a new UI and @tacigar, does it make sense to cache some information in localStorage? For example the service names or span per service? Any concerns more than having the posibility for a service to not to come up? we could set an expiracy at server level or even better have a config page where, in case of doubt, one could clear the storage manually. What do you think @apache/zipkin-committers ?
