### ISSUE TITLE
UI query does not work if `=` is present in the value of a binary annotation

### ISSUE THREAD

**Issue by prat0318** [openzipkin/zipkin#719]
The current [split logic](https://github.com/openzipkin/zipkin/blob/716467aa52b7f6cb9de7a242b3b5eabdb8920b11/zipkin-web/src/main/scala/com/twitter/zipkin/web/QueryExtractor.scala#L76) blindly splits whole of the query by `=` and does not care if that might be present in the value. Hence, this binnary annotation query fails : `http.uri=/foo?bar=3`. i.e. Having another `=` in the value (`/foo?bar=2`).

**Comment by eirslett** [comment]
Aah, we need to encodeURIComponent() it in the JavaScript layer, I guess,

**Comment by prat0318** [comment]
I don't think that is the problem. When we are splitting, it should split only by the first `=` and the rest of them should stay as in, in the value. The limitation of this is `=` should not be in the key, but that is not a deal breaker.
