### ISSUE TITLE
Service Dependencies UI enhancements

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#727]
Each item might need to be split into separate issue, but I want to just list them all in one place. Without some of these features the dependency graph is practically unusable for large systems (e.g. 500+ services)
1. There should be a combobox with service names, and selecting a service should act similar to what happens when you mouse-over the service in the graph, i.e. highlight connected services, dim the rest. 
2. There should be a way (button, checkbox?) to trim the graph to only the services connected to a selected service. It can actually be a dropdown with "distance", i.e. trimming the graph to services that are within specified number of hops from the selected service (currently highlighting is only one hop).
3. The edges are currently highlighted on mouse-over, but not clickable - clicking an edge should bring the same second-level popup as when you click on a service first and then on one of its up/downstream friends

**Comment by codefromthecrypt** [comment]
the dependency graph has been rewritten completely in lens so closing out issues in the classic ui
