### ISSUE TITLE
New Cassandra store stores invalid timestamps

### ISSUE THREAD

**Issue by danchia** [openzipkin/zipkin#737]
Zipkin uses microsecond resolution timestamps.

However, we attempt to store these microsecond timestamps directly into a `timestamp` column in C*, which assumes millsecond resolution. In my opinion this is misleading to people.
Additionally, in the newer cassandra `cqlsh` shell, this breaks the ability the query the column.

Suggested solution is to use `long` type for the `ts` column in C*.

Unfortunately, this is not a compatible change - tables would have to be dropped and re-created.

**Comment by danchia** [comment]
The fix would look something like https://github.com/coursera/zipkin/commit/807e48d2c627c14438acc5e53dd2795bc6378639

however because of the breaking nature, not sure how we should proceed with this.

**Comment by codefromthecrypt** [comment]
your fix is correct. I'll bump the version and cherry-pick it in. thanks!

**Comment by michaelsembwever** [comment]
:+1:
