### ISSUE TITLE
Get rid of anorm

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#747]
anormdb is a mess, and has weird workarounds around extracting byte arrays. It is worse, as we are rev-locked on an old version of anorm. On average I lose more time here than other parts of zipkin. Others may feel differently, but I think this really has to go.

I'm using JOOQ in the java project, and it is more type-safe, works normally with byte arrays, and is overall less magical/implicit. I recommend we switch over to it.

**Comment by codefromthecrypt** [comment]
ps the java project is now in sync with the schema used by anorm

**Comment by jorgheymans** [comment]
The switch to JOOQ has since long happened.
