### ISSUE TITLE
Javascript library updates

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#760]
It would be great if someone can update our javascript libraries. They are all pretty old.

**Comment by codefromthecrypt** [comment]
I hate to say it, but I think we are nearly a point where recreating a UI would be less work than maintaining it.

Good news: It is possible to update all libraries with the exception of dagre-d3.

Bad news: there's custom trimming involved, and this isn't represented in the bower file. This means I can't update it easily unless we want to check in a lot of junk.

Ugly news:  dagre-d3 is very tangled. If you try to update it, you'll get in a mess between versions of dagre and d3. After a few hours, I was unable to sort problems such as undefined references to functions with requirejs shims. See #772, which says all that work is wasted as we need another means to create sankey or similar diagram.

Next step:

If we don't want to throw away the UI, we need to maintain it far better than we are now. We probably want to stop checking in assets into src/main/resources and using something like [bower-installer](https://github.com/craigburke/bower-installer-gradle) to install them at build time like other deps.

cc @abesto @eirslett

**Comment by codefromthecrypt** [comment]
in case anyone wants to pick this up, here's the diff that works as long as you don't touch anything related to d3.

``` diff
diff --git a/zipkin-web/src/main/resources/bower.json b/zipkin-web/src/main/resources/bower.json
index acdf7cf..9595949 100644
--- a/zipkin-web/src/main/resources/bower.json
+++ b/zipkin-web/src/main/resources/bower.json
@@ -2,14 +2,14 @@
   "name": "zipkin",
   "version": "0.0.0",
   "dependencies": {
-    "flight": "~1.1.0",
-    "requirejs": "~2.1.5",
-    "bootstrap": "~3.1.1",
-    "bootstrap-datepicker": "~1.3.0",
-    "jquery-timeago": "~1.3.1",
-    "chosen": "https://github.com/harvesthq/chosen/releases/download/v1.1.0/chosen_v1.1.0.zip",
-    "jquery-cookie": "~1.4.0",
-    "momentjs": "~2.5.1",
+    "flight": "~1.5.1",
+    "requirejs": "~2.1.20",
+    "bootstrap": "~3.3.5",
+    "bootstrap-datepicker": "~1.4.1",
+    "jquery-timeago": "~1.4.3",
+    "chosen": "~1.4.2",
+    "jquery-cookie": "~1.4.1",
+    "momentjs": "~2.10.6",
     "dagre-d3": "~0.2.9"
   }
 }
```

**Comment by eirslett** [comment]
Yup, it would be nice to use something else than dagre!
One option we could do in the meantime is to bundle dagre-d3 with its version of d3 in a self-contained, isolated module. Then, the rest of the UI could be developed independently, and draw the graph by using the graph's public API. jQuery and D3 would be hidden inside the private scope and not pollute the global namespace.

**Comment by codefromthecrypt** [comment]
That sounds like a good way to progress. I don't know how that maps into
steps to do.. for copy/paste grunts like me.. can you say how to do that
ex. take this part out of bower and move this directory here, change
main.js, etc? (or even better PR) :)

**Comment by eirslett** [comment]
The half-dirty version (because it could be dirtier) would be to commit d3 and dagre-d3 (the current versions) into version control, rename them to "d3-legacy" and "dagre-d3-legacy", and import them in require.js with these names.

**Comment by abesto** [comment]
And I guess the non-dirty way would be to have a separate bower config that installs stuff to a separate directory.

**Comment by codefromthecrypt** [comment]
well one thing we'd have to consider is that currently, there's a hook in zipkin-web that allows you to monkey with src/main/resources. If we remove that, then we could indeed merge in the assets from 'wherever', defaulting to bower config except the pinned d3 stuff.

**Comment by abesto** [comment]
Oh, didn't know there's deep bower integration. In that case it's probably not worth playing around with multiple bower configs, especially as this is not a situation we want to maintain in the long term (I guess).

**Comment by codefromthecrypt** [comment]
It isn't so much about bower, as an assumption you can write to the path
assets are at... and libs are under there.

**Comment by eirslett** [comment]
Which hook?

**Comment by codefromthecrypt** [comment]
@eirslett well, I'm just thinking that these flags lift expectations of where assets are stored etc into public api. If we re-organize into pulling bower deps as opposed to storing them in the source tree, we'd break below's contract (maybe for the best).

```
  val webCacheResources = flag("zipkin.web.cacheResources", false, "cache static resources and mustache templates")
  val webResourcesRoot = flag("zipkin.web.resourcesRoot", "zipkin-web/src/main/resources", "on-disk location of resources")
```

**Comment by eirslett** [comment]
Off with their heads!

**Comment by adriancole** [comment]
picking this up again

**Comment by codefromthecrypt** [comment]
first step: https://github.com/openzipkin/zipkin/pull/890/files

once in, we can give a go at bower (except for the dagre-d3-legacy thing)
