### ISSUE TITLE
'spanName' filter should consider character case in zipkin web UI

### ISSUE THREAD

**Issue by zfy0701** [openzipkin/zipkin#767]
I'm using finagle which might record it's rpc method as span name, e.g. "getResult",

in the zipkin UI, there will be a lower case "getresult" show in the dropdown, when I select it I'll find nothing, but if I manually change the url from like:

http://localhost/?serviceName=x&spanName=getresult ....
to 

http://localhost/?serviceName=x&spanName=getResult ....

I could get the right answer.

it looks like we should not transform the span name into lower case in UI for selection

**Comment by codefromthecrypt** [comment]
I think the bug/key insight is that we are inconsistent. Many parts of the
code treat span name case insensitively, but some don't. I'm not sure we
should be case sensitive, and I don't mind us enforcing lowercase on the
wire (just as http2 does). However, we should be consistent with the answer
of if we are case sensitive or not. If we are, that only works for certain
character sets, so might imply a constraint on the character set of span
name.

**Comment by zfy0701** [comment]
both solutions sounds file, from user point of view, it's nice to have them display with cases such as the service name (but you still query using lower case"

**Comment by srijs** [comment]
I'm not sure case insensitivity is a good idea with regards to being able to offer different storage backends, which might _or might not_ offer the ability to query the span name that way, and I don't think  schema-on-write is a thing that should be done for user-provided strings like this.

**Comment by codefromthecrypt** [comment]
My 2p is either we do lowercase on store (which implies searches also
lowercase on the way in), or we leave it case sensitive (and be consistent
about it :P)
