### ISSUE TITLE
Find an alternative to dagre-d3 (for dependency view)

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#772]
According to its homepage, dagre-d3 is no longer maintained. Let's figure out what we should use instead.

https://github.com/cpettitt/dagre-d3

cc @eirslett

**Comment by shakuzen** [comment]
Looks like it redirects to https://github.com/dagrejs/dagre-d3 now and it has some activity. Not that there isn't necessarily something better to use still, but I just wanted to point that out.

**Comment by codefromthecrypt** [comment]
lens uses a different library for the service graph and we aren't investing any more effort in classic UI
