### ISSUE TITLE
Doesn't work with Amazon RDS?

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [openzipkin/zipkin#773]
We've been trying to get the MySQL storage to work on Amazon RDS with little success.

Using docker-zipkin we manage to use the MySQL storage and it works fine.
Changing the `MYSQL_HOST` to an RDS instance, send dummy traces and try to see them in the web UI (by submitting the search form) ends up in errors such as:

```
query_1     | java.lang.RuntimeException: UnexpectedNullableFound(ColumnName(zipkin_annotations.end_ts,Some(end_ts)))
query_1     |   at scala.sys.package$.error(package.scala:27) ~[zipkin-query.jar:na]
query_1     |   at anorm.Sql$.anorm$Sql$$as(Anorm.scala:472) ~[zipkin-query.jar:na]
query_1     |   at anorm.Sql$class.as(Anorm.scala:292) ~[zipkin-query.jar:na]
query_1     |   at anorm.SimpleSql.as(Anorm.scala:190) ~[zipkin-query.jar:na]
query_1     |   at com.twitter.zipkin.storage.anormdb.AnormSpanStore$$anonfun$getTraceIdsByName$1.apply(AnormSpanStore.scala:204) ~[zipkin-query.jar:na]
query_1     |   at com.twitter.zipkin.storage.anormdb.AnormSpanStore$$anonfun$getTraceIdsByName$1.apply(AnormSpanStore.scala:180) ~[zipkin-query.jar:na]
query_1     |   at com.twitter.zipkin.storage.anormdb.DB.withRecoverableRetry(DB.scala:120) ~[zipkin-query.jar:na]
query_1     |   at com.twitter.zipkin.storage.anormdb.DB$$anonfun$inNewThreadWithRecoverableRetry$1.apply(DB.scala:147) ~[zipkin-query.jar:na]
query_1     |   at com.twitter.util.Try$.apply(Try.scala:13) ~[zipkin-query.jar:na]
query_1     |   at com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:115) [zipkin-query.jar:na]
query_1     |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
query_1     |   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
query_1     |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
query_1     |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
query_1     |   at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

in the console while the web UI itself is a white unstyled screen stating:

```
{"errors":["internal server error"]}
com.twitter.finagle.NoStacktrace(Unknown Source)
```

We've been trying both MySQL 5.6 and 5.5, no change.
The only difference between works/doesn't work really is the DB, everything else is the same. The schema etc are also the same.

@adriancole any pointer would be highly appreciated, this is hopefully the last blocker before we put zipkin to good use here.
cc @jcarres-mdsol

**Comment by codefromthecrypt** [comment]
hmm "MAX(a_timestamp) as end_ts" is called by getTraceIdsByName. I'll
add a test to see what happens if you call that and there's no
endpoint with the corresponding service name..

**Comment by codefromthecrypt** [comment]
So empty data test passed. only guess is that there's an annotation
missing data in the a_timestamp field. Can you do a select null or
empty on that? Should be impossible, but worth a try.

**Comment by jcarres-mdsol** [comment]
a_timestamp is never null.

One more thing we have just realized.
When we run it locally with 3 test apps, we create 16 annotations. When executing this against RDS, we create 8 annotations.
Checking the differences, we have seen that the "sr", "ss" and related binary annotations were all in RDS. And the "cs" "cr" annotations and related binary annotations were none of them in RDS.

**Comment by codefromthecrypt** [comment]
Is this reproducible without the test apps? Ex. By just clicking refresh on
zipkin, are you also missing cs annotations? This should be testable I
think.. Maybe by curl and then curl against the api's trace endpoint to
verify.
