### ISSUE TITLE
Move minimum JRE to 8

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#777]
The main zipkin project's artifacts are services, particularly a collector, query and web process. We have done a lot of work to update things to scala 2.11, which is why all major adopters can run on JRE 8. This includes Twitter as I personally moved internal zipkin onto JRE 8 earlier this year.

We wanted to update to JDK 8, as there are a lot of libraries that no longer compile to JRE 7 bytecode. We decided against, as Twitter's internal software still compiled with JDK 7. We can no longer justify holding the project back for a single user. There are many problems in anorm we can't fix as they don't release new versions that work with JRE 7. We need to start thinking about scala 2.12.. we can't freeze forever.

Let's make the call, accept the collateral damage, and update to producing Java 8 bytecode. The primary impact is those still compiling with javac 7 can no longer patch zipkin servers.

Those using zipkin instrumentation are unaffected as this is decoupled completely. For example, both brave and finagle target minimum Java 1.7. This means web apps that generate traces, running on JRE 7 aren't affected at all. It is only the servers that are updated.

**Comment by jamescway** [comment]
We're still on jdk7 but that doesn't need to stop us.  What would be some alternatives for those that are stuck for the time being?

**Comment by codefromthecrypt** [comment]
Ship libraries? Ex. if there's no custom code, then there's no reason to javac. Maybe upstream or find some internal build pipeline that permits use of javac 8. Often there's at least an experimental build for a JDK as old as 8 is.

**Comment by codefromthecrypt** [comment]
For example, I think you guys needed kafka, and the upstream collector now supports it. Is there anything else needed to flip over? once there's nothing left, then there's no code you'd need to run javac 8 against.

unless.. you are saying your servers actually can't run jre 8, either, which makes the solution unfortunately simpler, which is use a version before the flip and lean elbows on whatever's blocking the ability to coexist with JRE 8.

**Comment by yurishkuro** [comment]
+1 to move to 8

**Comment by codefromthecrypt** [comment]
starting this now
