### ISSUE TITLE
Annotation query search doesn't work if end timestamp given of future.

### ISSUE THREAD

**Issue by prat0318** [openzipkin/zipkin#783]
Whenever i play with zipkin to track queries realtime, i change the end timestamp to `tomorrow` so that i need not update the timestamp every minute. This works fine except for annotation query search.

Steps to reproduce.
1) Find an annotation query which gives non-zero results.
2) Change end timestamp to tomorrow.
3) Search with the same annotation query. It returns zero results.

**Comment by yurishkuro** [comment]
@prat0318  Which storage backend were you running?

**Comment by prat0318** [comment]
cassandra

**Comment by eirslett** [comment]
Is this still a problem?

**Comment by prat0318** [comment]
it got fixed in one of the recent ui versions. good to close.

On Wednesday, March 16, 2016, Eirik Sletteberg notifications@github.com
wrote:

> Is this still a problem?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/openzipkin/zipkin/issues/783#issuecomment-197418806

## 

Prateek Agarwal
