### ISSUE TITLE
zipkin-web end time set

### ISSUE THREAD

**Issue by rjbhewei** [openzipkin/zipkin#786]
![image](https://cloud.githubusercontent.com/assets/8099839/10629906/697c1c1c-7805-11e5-8a6e-25fe132ac44c.png)

I find i can not select end time (zipkin version is 1.17.2) 

url send end time is not my select time ，but the OS current time

**Comment by rjbhewei** [comment]
url send end time is not my select time ，but the OS current time

**Comment by codefromthecrypt** [comment]
maybe related to #783

**Comment by lycplus** [comment]
We also encounter this in 1.25.1.

Another problem, when I select span name, and send the request, the page returns, with span name reset to all, which is unexpected. I expect the span name remains to be what I select.

**Comment by codefromthecrypt** [comment]
thanks for reporting! sounds like a valid problem. personally, I'm offline
for a week or so. If anyone else can help with this, please do!

**Comment by lycplus** [comment]
Any update? another problem, why the graph initially collapsed ?  It makes me click the `expand all` all the time.

**Comment by codefromthecrypt** [comment]
@liyichao If you'd like to have a stab at resolving your issue, this is open source: we'd welcome the hand.

**Comment by codefromthecrypt** [comment]
@liyichao wrt "why the graph initially collapsed" the collapsed-ness has to do with the serviceName query. For example, if the serviceName parameter corresponds to the root span, it will show up collapsed. If it doesn't it will expand to the child that contains it. Feel free to spin off another issue on this if you feel that behavior isn't ideal cc @yurishkuro

**Comment by codefromthecrypt** [comment]
wrt your original concern (about end time resetting) I see that this is certainly the case.

For example, if you start from scratch, ex. where there's no query params in the URL, you can select any time, and the page will return with the correct endTs query parameter.

If you already have an endTs query parameter, changing the endtime date or time fields has no effect.

The work around is to clear the URL when you want to change. I agree this is a bug.

**Comment by prat0318** [comment]
@adriancole i checked even with no query params in the URL and i select a previous date from the dropdown, the timestamp added in the query is still the current one (ignoring the selected endTs).
