### ISSUE TITLE
Allow viewing of older dependencies

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#791]
While the dependencies api accepts a stop-point, `?endTs=1445470517980000`, the UI doesn't expose this. This means people making demos with canned data will see nada, and have no means to.

In the mean time, folks using spigo need to re-run their simulations before posting to zipkin. If you see nothing, maybe it is just old data. cc @adrianco

**Comment by eirslett** [comment]
I think #921 fixed this.
