### ISSUE TITLE
Twitter documentation is out of date?

### ISSUE THREAD

**Issue by MatMoore** [openzipkin/zipkin#792]
Hi,

I notice openzipkin still links to the twitter documentation at http://twitter.github.com/zipkin as the "full documentation", and there doesn't seem to be any replacement for this. All I can find is issue #461, which hasn't been worked on since it was opened a few months ago.

I was able to follow twitter's guide a couple of months ago, but it doesn't seem like this has been updated since then. For example, they provide examples of building/packaging zipkin using sbt, but looking through the commit log I saw that sbt has been completely dropped in favour of gradle.

As someone who has never used gradle before, I would really appreciate some details of how I can package and configure Zipkin for production use.

I think if the twitter documentation is not going to maintained as the project evolves then it should be removed as it will mislead new users.

I would be happy to help out with the documentation process if somebody could give me some direction (I am familiar with the concepts behind zipkin but am not currently a heavy user or contributor).

**Comment by codefromthecrypt** [comment]
Hi, there.

We've added substantial documentation updates, far more than existed
before. Don't read too much into what's logged in old issues, but I will
have a look at it.

We now have verbose README files, detailing the minimum variables you need
to set, and doc folders on both zipkin and also the docker-zipkin projects.
Users no longer have to build the project as we took great effort to
publish binaries and also docker images.

The binaries are on bintray and docker images are on both quay and also
dockerhub.

Maybe if you can mention your specific use-case, we can update zipkin.io to
be more obvious.

I know there's still work to do, but you are far better off as you don't
have to run sbt or gradle ;) Regardless, we are on gitter.im on
openzipkin/zipkin and folks deploy in many ways. Many use docker, which we
support best. Some use chef or other tools.

Hope this helps and thanks for keeping us honest!

**Comment by MatMoore** [comment]
Ah... I hadn't checked zipkin.io... I followed the link from README.md to http://twitter.github.com/zipkin instead. Can we just change that?

I should clarify that I'm not using docker, so it looks like I should just grab a jar from bintray for each of the individual services I plan to use?

I know there has been a lot of work to separate out non-essential components but I hadn't thought to look in the subdirectories for readmes. It would be great if we could integrate that information into the zipkin.io docs as well.

**Comment by codefromthecrypt** [comment]
So we do have folks using non-docker, like Cloud Foundry and chef. It makes
sense to make a "recipe" page or something, aggregating the content.

I can try to contact Twitter to redirect the old site to the new one.
Should be possible.

Any particular config mgmt approach you are looking for? Or will basic
collection of where to get artifacts and how to start them work?

**Comment by MatMoore** [comment]
I think just what goes where and how to start is enough for me, but I'm sure recipes would be helpful. I'm personally using ansible and could maybe contribute a sample playbook. If I have time this weekend I'll try running the latest artifacts.

**Comment by codefromthecrypt** [comment]
Great. which backend storage are you planning on? mysql is the simplest,
but cassandra is also well supported.

**Comment by MatMoore** [comment]
Just to update - I did eventually manage to get it working using the fat jars from bintray.

This is just a small development deployment and last time I checked the mysql storage wasn't able to expire old data, so I went with redis instead. I also used scribe rather than kafka to keep things simple.

I am running everything like this:

```
java  -jar zipkin-collector-service-1.25.1-all.jar  -f /collector-redis.scala
java  -jar zipkin-query-service-1.25.1-all.jar  -f /query-redis.scala
java -cp 'libs/' -jar zipkin-web-1.25.1-all.jar -zipkin.web.cacheResources=true
```

**Comment by codefromthecrypt** [comment]
as this topic isn't concise enough to know when it is complete, I took what I could and made https://github.com/openzipkin/zipkin-redis/issues/2 out of it.
