### ISSUE TITLE
Problematic cassandra schema initialization on startup

### ISSUE THREAD

**Issue by pbetkier** [openzipkin/zipkin#793]
The current startup logic of always ensuring that schema exists when using Cassandra repository may be problematic in some cases, e.g. when Cassandra user doesn't have permissions for all the the operations defined in the schema cql script.

In our shared Cassandra cluster for example, users don't have permission to create keyspaces (they are created for them beforehand), so the `/cassandra-schema-cql3.txt` script (always called on startup) fails on  `CREATE KEYSPACE IF NOT EXISTS (...)`. Currently we have our own zipkin fork with this single line removed from the script, but would prefer to use official releases.

Perhaps we could make the schema initialization on startup optional? Or provide a way to configure an alternative schema cql script path with a parameter? What do you think?

**Comment by jamescway** [comment]
The schema functions better as an example to follow at the moment.  For individual cassandra clusters there are enough differences (i.e. datacenter, keyspace, users, etc) that make a generalized setup not a good idea.  In the future we could consider creating database migrations at which point we could think about using config variables.  Not sure when the road map for that would be, but would welcome any assistance :smile:  Another alternative could be a better readme outlining what variables could be changed and what some example fields might be.

**Comment by codefromthecrypt** [comment]
Good points, James. Teasing things out, though.. Having our collectors n
query processes not attempt to do DDL is probably a low hanging fruit, even
if there be dragons like things you mentioned.

**Comment by jamescway** [comment]
Sorry my tech-ese is not too good here.  What do u mean by collector/query doing DDL?  I would have guessed that creating a config would be more of a DDL

**Comment by pbetkier** [comment]
@jamescway I'm referring to `zipkin-cassandra-core/src/main/resources/cassandra-schema-cql3.txt` DDL script that is executed during startup of cassandra-based collector and query service. It's called in the constructor of `org.twitter.zipkin.storage.cassandra.Repository` and as far as I can see there is currently no way of disabling it. I need control over what's being executed :) Ideally make zipkin not execute anything during startup and let me handle the database schema by myself.

**Comment by jamescway** [comment]
@pbetkier ah sorry I didn't realize it was hard coded, that does sound like a problem.  Disabling sounds like a good idea!
