### ISSUE TITLE
[web] Can't direct link to the traces page

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [openzipkin/zipkin#800]
We'd like to be able to link to the "traces" page of a given service which would translate to a URL like
`http://zipkin.example.com/?serviceName=someService&spanName=all&endTs=1446011753772000&limit=10&annotationQuery=` 
but unfortunately nothing happens when accessing such an URL directly.
That's pretty sad given that the form is sending a GET.

Looking at the code makes me wonder why is JS needed at all, wouldn't a simple `<form action=".." method="GET">` do the trick?

**Comment by codefromthecrypt** [comment]
Maybe you're right! Wanna give it a try?

-A

**Comment by jfeltesse-mdsol** [comment]
Never used Mustache for real but could it be the front end side expects all requests to stem from the root page and that all page transitions to be handled by itself, confusing it when someone bypasses that?
Sounds like it's not going to be implemented so easily if from the start the web component has not been designed to handle those cases (which is wrong but what's done is done).

**Comment by codefromthecrypt** [comment]
taking a look now

**Comment by codefromthecrypt** [comment]
If I access this via curl directly on localhost, there's no problem. Trying a public host..

**Comment by codefromthecrypt** [comment]
Similarly, I can use a url directly against a public host. Ex. if you do a `curl` you'll see data in the response, like `<span class="label label-default service-filter-label" data-service-name="zipkin-jdbc">zipkin-jdbc x1 8ms</span>`

Can you use chrome debugger and see what's actually being sent and received? Maybe paste the http envelopes (without the payload) here?

**Comment by jfeltesse-mdsol** [comment]
Strange, I'll try to investigate more this week and report back here.

Thanks for having a look!

**Comment by jfeltesse-mdsol** [comment]
Sorry for the delay. After some more testing it seems to work alright now.

Thanks for having a look nevertheless! :+1:
