### ISSUE TITLE
Cant see latest traces when many in the DB

### ISSUE THREAD

**Issue by jcarres-mdsol** [openzipkin/zipkin#826]
How the UI works now seems to work:
Stage 1: Search
Here you specify the service name, endtime and limit

Stage 2: Ordering of results
Once there are results there is an ordering dropdown to order these results.

I have ~30.000 traces for a given service. These traces have been sent the last 1 month or so.
I want to see the latest traces, the ones send the last couple of days or so, but it is impossible.

If I try to get more than 1.000 traces in the UI the connection will timeout.
If I get 1000 traces then those seems to be the oldest so I can not see anything that has happen recently.
Looking at the UI in fact, I can not even know if Zipkin keeps receiving traces or no.

And Also I do not want to see 1000 traces in the UI.

Possible solutions:
- Add a start date to the UI
  or
- The ordering dropdown is there before clicking find and the ordering happens before the call to the DB

Or both.

**Comment by codefromthecrypt** [comment]
We literally introduced a "lookback" query flag for this https://github.com/openzipkin/zipkin/pull/825

It defaults to 7 days, and overridable via `QUERY_LOOKBACK` (in microseconds). I think @yurishkuro said he'd probably set this to 2 days. In docker, this would be `QUERY_LOOKBACK=172800000000`

This basically changes the default from looking back forever until a pre-canned value. For customizable values, I agree the UI needs to be changed. One question would be whether to specify start_date or lookback directly as the UI element. Thoughts?

PS  I'll cut an interim release today so you can set  `QUERY_LOOKBACK`

**Comment by yurishkuro** [comment]
@jcarres-mdsol This sounds like a bug somewhere in the specific storage implementation. With Cassandra storage the LIMIT applies to the most recent traces, i.e. out of the box you get the most recent trace at the top of search results (unless UI re-sorts by duration).

**Comment by codefromthecrypt** [comment]
The sort happens before the javascript processes the spans for all span
stores. Then, there's a javascript element to sort differently. I think the
key concern is that very old spans show up.. Easiest way out is to cut the
QUERY_LOOKBACK change, as that will magically eliminate the month-old
problem.

**Comment by jcarres-mdsol** [comment]
I think QUERY_LOOKBACK will be confusing. We will have a default start_ts in the search that is invisible to the user. I do not think it will be obvious why most of the data is invisible in searches (i.e. can't search for anything before the QUERY_LOOKBACK which users do not know how was setup as is invisible to them.

Also is inflexible, if I deployed 3 days ago and would like to see data from the last 4 days to compare before and after, I can not if QUERY_LOOKBACK is set to 2 days. I can set it to 5days but then high-volume services will still have the original problem, etc.

**Comment by codefromthecrypt** [comment]
default QUERY_LOOKBACK is an environment variable, so it isn't visible to
users anyway. This is similar to TTL, as most sites don't retain more than
3-7 days trace data. You can feel free to set it to a year, for example.

Let's separate the issue of the environment variable from how a UI presents
the query. Do you have a specific change in mind, even better a pull
request for it? It is trivial to convert startTs into lookback as endTs is
a required parameter anyway.

**Comment by codefromthecrypt** [comment]
Here's a summary from a gitter chat.

Users expect to see most relevant results by default.

Here are some UI options I thought about:
1. Add Lookback to the UI. User clicks or allows the date to be set how it is, then they choose 5minutes lookback.
2. change the UI from basing on endTs (looking backwards) to being based on startTs (looking forwards)
For example, we choose a point in time, and we look for results newer than that.
3. change the UI from basing on endTs (which is almost always current time) to being based on timestamp. Add a +- option. For example, user enters 9:55 +- 5minutes. This is easy to convert to endTs, lookback.

Regardless, there's a different aspect, which is the order of trace results. If limit was subject to descending order of timestamp, they'd always get freshest by default, regardless of UI.

**Comment by yurishkuro** [comment]
I think keeping UI restricted to endTs + duration is fine. Having those controls accept free-form time and interval is a great bonus.
