### ISSUE TITLE
Add a license scan?

### ISSUE THREAD

**Issue by mstine** [openzipkin/zipkin#843]
Looking ahead to potentially packaging the code into Spring Cloud Services at Pivotal, I'm wondering if we could add the Gradle License Plugin (https://github.com/hierynomus/license-gradle-plugin) to determine if there are any poteintal poisonous dependencies in Zipkin. @adriancole

**Comment by codefromthecrypt** [comment]
SGTM

**Comment by codefromthecrypt** [comment]
@abesto if you're interested in this, lemme know.

**Comment by abesto** [comment]
Totally. Licensing is something I'm recently very interested in; if no-one picks it up, I'll have a look this weekend.

**Comment by abesto** [comment]
Wow, rebasing is noisy.
