### ISSUE TITLE
Investigate impact of relaxing root span id=traceid

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#849]
At least finagle, ruby tracer, and brave set span.id=traceid on the root span. We've not audited or formally tested relaxing this to just parent id. Before a change is attempted, it might be nice to understand what people know is relying on this, or if span.id=traceid is just a way to save a random number generator.

If we support root span is just absence of parent_id, we would want to add tests to ensure that works in spanstore, aggregators, and anything that generates a tree.

**Comment by codefromthecrypt** [comment]
@theatrus @eirslett @kristofa anybody have any insight (or memory) about this?

**Comment by codefromthecrypt** [comment]
Food for thought: [dapper](http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/36356.pdf) doesn't seem to imply a span.id=traceid restriction:

> Spans created without a parent id are known as root spans. All spans associated with a specific trace also share a common trace id.

**Comment by codefromthecrypt** [comment]
A bit of a guess, but the traceid=spanid may have nothing to do with dapper, and more about the predecessor to the predecessor of zipkin: https://github.com/twitter/finagle/commit/e00c91709c1be6710d4aee102139b12cb1f837d2#diff-50e70bbc12edca0f2c7be3f34b53d88aR32

**Comment by codefromthecrypt** [comment]
Also, seems htrace already have to set traceid differently, as their ids are 128bit! https://github.com/apache/incubator-htrace/blob/master/htrace-zipkin/src/main/java/org/apache/htrace/zipkin/HTraceToZipkinConverter.java#L112

**Comment by codefromthecrypt** [comment]
I did a quick look through zipkin's scala code the only thing that seems impacted by this might be smoked out via DependencyStoreSpec. For instrumentation, probably just want to make sure none of core tracers indicate root span via parent_id=0 (vs null) or parent_id=trace_id

**Comment by codefromthecrypt** [comment]
NEXT STEP: let others speak up about this

**Comment by eirslett** [comment]
+1 for removing this restriction! That also lets us encode information in the span IDs (like where in the call tree the span originates from)

**Comment by codefromthecrypt** [comment]
I'm +1 on this, too. I'll raise a PR with some test clarifications to support this

**Comment by codefromthecrypt** [comment]
c\* dependency tests weren't actually running. fixed that and backfilled tests to ensure we don't rely on this convention. https://github.com/openzipkin/zipkin/pull/851
