### ISSUE TITLE
Cassandra does not support microsecond precision for timestamp fields

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#857]
I think we need to revert the "setunsafe" code to use native timestamp methods. We should only use millisecond timestamps for the directly exposed timestamp fields, as those should only be used for time window lookups and sorting, where microseconds are not that critical. The timestamps in the thrift blobs will remain at microsecond precision,

**Comment by codefromthecrypt** [comment]
Sounds fine to me, as long as we make it obvious in the code and DDL that these are millisecond granularity as opposed to micros.

**Comment by codefromthecrypt** [comment]
I think we should apply this globally. ex change QueryRequest and the HTTP api to millis, so it is consistent. The logic is sound, and a change like this is better to do before we document the HTTP api.

**Comment by yurishkuro** [comment]
sgtm

**Comment by michaelsembwever** [comment]
for the tracing within cassandra having microsecond accuracy is important.

**Comment by yurishkuro** [comment]
Should we close this as fixed by my PR?

**Comment by michaelsembwever** [comment]
+1
