### ISSUE TITLE
Fix: verifyLicenses thinks subprojects don't have a license

### ISSUE THREAD

**Issue by abesto** [openzipkin/zipkin#858]
The dependency license verification introduced in https://github.com/openzipkin/zipkin/pull/852 fails to recognize that the subprojects (like `zipkin-common`) have a license. Not surprising, since there's no POM file accompanying the jars. I see three options for attacking this:
- Generating a POM file and making sure the license plugin reads it
- Add metadata to the jars that the plugin reads
- Hard-code (or generate with gradle) the license for each subproject into the configuration for the plugin via `downloadLicenses.licenses` (https://github.com/hierynomus/license-gradle-plugin#license-reporting)

**Comment by eirslett** [comment]
Is this fixed?

**Comment by abesto** [comment]
Negative. 11 subproject dependencies are affected.
