### ISSUE TITLE
Hunt down licenses for dependencies

### ISSUE THREAD

**Issue by abesto** [openzipkin/zipkin#859]
The license verification introduced in https://github.com/openzipkin/zipkin/pull/852 highlights that some of the dependencies we use don't specify their license in their POM file. The license plugin can be explicitly told the license of each dependency via `downloadLicenses.licenses` (https://github.com/hierynomus/license-gradle-plugin#license-reporting)

**Comment by eirslett** [comment]
Is this fixed?

**Comment by abesto** [comment]
Negative. ATM there are 35 dependencies with no license, 11 of which are other subprojects of `openzipkin/zipkin`.

**Comment by abesto** [comment]
Closed via #1048
