### ISSUE TITLE
Enhance duration UX by accepting formatted strings

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#864]
zipkin-web accepts raw microseconds in the search form for minimum duration. Eventhough the HTTP api should accept this (as there's no standard URI encoding of duration, especially microseconds), we should make the user experience better.
#863 was raised against this, but approached this by changing the query api to parse scala types. A better solution would be to address this in javascript, similarly to how we address `endTs`

Ex. the hidden [endTs](https://github.com/openzipkin/zipkin/blob/master/zipkin-web/src/main/resources/templates/v2/index.mustache#L25) parameter is assembled by a flightjs component named [timeStamp](https://github.com/openzipkin/zipkin/blob/master/zipkin-web/src/main/resources/app/js/component_ui/timeStamp.js), using momentjs.  Since momentjs supports [duration strings](http://momentjs.com/docs/#/durations/), we should be able to use this as well. By using momentjs, we can allow validation and coersion to happen in the browser, where other similar aspects are addressed.

As a first step, we can create a text component which attempts to use momentjs if the contents are non-numeric. Ex. if the contents are purely numeric, we could assume it is microseconds, a granularity very untypical in javascript. Ex. `2 hours` would use momentjs, whereas `140` is missing a unit and be passed raw as microseconds. Alternatively, we could special case some unit for micros and default purely numeric strings to millis.

The normal flow in flight seems to be to define an inputfield, hidden outputfield, and a javascript component to plumb them together.

**Comment by codefromthecrypt** [comment]
@danchia @yurishkuro @eirslett @nikhil2406 @gneokleo @synk Fishing for those who've touched flight components before :) Do any of you have some cycles to try this?

**Comment by adriancole** [comment]
@jcarres-mdsol I suspect your answer is "scala...", but just in case you can help :P

**Comment by adriancole** [comment]
@dev-priya really really really fishing :) I remember you saved me back in the day on twitter UI stuff.. if this looks like something you could help with, you'd win the adoration of millions (of lines of code?! :))

**Comment by danchia** [comment]
@adriancole let me give this a stab.

**Comment by danchia** [comment]
So I took a quick stab at this, and it turns out it's not that easy.

momentjs supports ASP style durations (H:m:s), but not human readable ones like "1 second".

Even worse is that their human readable forms of durations, e.g. `moment.duration("0:00::00:1").humanize()` gives you `a few seconds` which is not parsable back into a duration.

Any ideas?

**Comment by codefromthecrypt** [comment]
might not work, but I was thinking the 2 arg methods, which look like they
accept a number and a unit? (ex  'm' or 'minutes')

http://momentjs.com/docs/#/manipulating/add/
http://momentjs.com/docs/#/utilities/

**Comment by danchia** [comment]
Hm.. interesting. Still have to solve the bijection problem, but I have an idea..

**Comment by codefromthecrypt** [comment]
@danchia I hope this task didn't scare you from zipkin forever :P

**Comment by danchia** [comment]
Nah, really busy at work :(

Zipkin is definitely one of my favorite projects to watch :)

**Comment by jorgheymans** [comment]
This issue refers to zipkin-classic which is no longer maintained and replaced by Lens. If the duration search component is not satisfactory there please open a new issue.
