### ISSUE TITLE
DependencyLink is not serializable

### ISSUE THREAD

**Issue by chemicL** [openzipkin/zipkin#867]
The change of DependencyLink from case class to standard class (from version 1.21.0) made the class not serializable, which causes issues in the dependencies project (zipkin-dependencies-spark) and probably in the query service too.

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 1.0 in stage 3.0 (TID 19) had a not serializable result: com.twitter.zipkin.common.DependencyLink
```

**Comment by yurishkuro** [comment]
Considering that the `DependencyLink` is used almost in the final stage of the Spark job:

```
    val dependencies: Dependencies = aggregates
      .map { case ((parent: String, child: String), callCount: Long) =>
        Dependencies(0, 0, Seq(DependencyLink(parent = parent, child = child, callCount = callCount)))
      }
      .reduce(_ + _) // merge DLs under one Dependencies object, which overrides +

    saveToCassandra(sc, dependencies)
```

A simple work around could be to define a local version of it as a normal, serializable `case class`. This should allow the  final `.reduce(_ + _)` step to succeed and produce a single in-memory object. Then in `saveToCassandra` method we can re-map it to the thrift-compatible class.

**Comment by chemicL** [comment]
I'll code a work around for now, but I suppose it would make sense to make the DependencyLink a serializable class, as it forms an interface for various uses.

**Comment by codefromthecrypt** [comment]
So, the canonical serialization of zipkin objects are json or thrift, not java serialization. We have tests for the serialized for of json (used in query), for example, but that's also largely because case classes in scala are so hard to deal with.

Scrooge thrifts are marked as Serializable.. what would happen if you stored scrooge thrifts instead?
https://github.com/openzipkin/zipkin/blob/master/zipkin-scrooge/src/main/scala/com/twitter/zipkin/conversions/thrift.scala#L156

**Comment by chemicL** [comment]
Thanks for the clarification, I suppose for Spark it makes sense to use the thrift wrappers. I noticed @yurishkuro faced the same problem with other classes and defined his own case classes, which seems more readable. I'll leave the implementation with his approach, but this can be revisited in the future.

**Comment by yurishkuro** [comment]
I suggest closing this issue.
