### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zhy4606** [openzipkin/zipkin#870]
[ant:scalac] error: missing or invalid dependency detected while loading class file 'JavaTimeToStatement.class'.
[ant:scalac] Could not access type ZonedDateTime in value java.time,
[ant:scalac] because it (or its dependencies) are missing. Check your build definition for
[ant:scalac] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[ant:scalac] A full rebuild may help if 'JavaTimeToStatement.class' was compiled against an incompatible version of java.time.

**Comment by codefromthecrypt** [comment]
are you failing to compile? or are you referring to the warning output.

**Comment by zhy4606** [comment]
sorry my jdk version is 1.7  change 1.8 it's ok

**Comment by sreeram-dev** [comment]
I faced this issue too. Can you check for it before?

**Comment by codefromthecrypt** [comment]
Worthwhile

**Comment by eirslett** [comment]
If anybody wants to take on this:
http://mrhaki.blogspot.no/2010/11/gradle-goodness-set-java-version.html
@zhy4606 @sreeram-boyapati do you have time to submit a PR for something like this?

**Comment by shakuzen** [comment]
We enforce the acceptable JDK version range in the build now.
