### ISSUE TITLE
openzipkin.github.io displays the default page

### ISSUE THREAD

**Issue by vprithvi** [openzipkin/zipkin#871]
I somehow ended up on http://openzipkin.github.io/ and found it to be the default page. Maybe we should redirect it to http://twitter.github.io/zipkin/ or delete it entirely

**Comment by codefromthecrypt** [comment]
interesting. agreed.

though http://openzipkin.github.io/zipkin/ or better zipkin.io

**Comment by eirslett** [comment]
![zipkin-great-again](https://cloud.githubusercontent.com/assets/1872593/13821145/aa32af14-eba0-11e5-8f9b-6bf0748e7583.jpg)
