### ISSUE TITLE
PRs changing Travis config cause confusion

### ISSUE THREAD

**Issue by abesto** [openzipkin/zipkin#878]
In the eternal words of @adriancole:

whoah.. just learned something!
so we have 2 travis checkers on the pull request
the one ending in "pr" uses the travis config from that pull request
the one ending in "push" uses the previous travis config
so .. if you raise a pull request, which affects travis config, you might end up with a christmas status
the "pr" passes", but the "push" fails

**Comment by eirslett** [comment]
Maybe rename them to something more descriptive?
Or should we close this issue? (due to lack of activity)

**Comment by abesto** [comment]
Methinks the name describes what the job does pretty well (-pr tests with a merge into `master`, -push tests on the branch). The issue here seems to be that one of the jobs (push) works incorrectly. I'm not sure how to approach fixing this without digging into Travis documentation.

Depending on how you think about GitHub Issues (todo list vs. issue tracker), it may make sense to close this (no-one's been working on this) or keeping it around (let's not forget it's an issue). Personally I'm in the "issue tracker" camp and would keep this open.

**Comment by jorgheymans** [comment]
issue was discussed, became inactive, was added to todo list then 2 years later removed from todo list ... So I'll close this one if anyone objects feel free to reopen.
