### ISSUE TITLE
Making SSL connection configurable in Mysql

### ISSUE THREAD

**Issue by sharpcoder77** [openzipkin/zipkin#885]
Ability to connect to Mysql over SSL should be configurable. I was not able to find any documentation related to this.

From first impression, it looks like it is hard-coded in `DBConfig.scala`. 

One possible solution can be getting it from environment variable and setting it when initializing `DBParams`

**Comment by codefromthecrypt** [comment]
I'm thinking add: `MYSQL_USE_SSL` as this is easy enough to make portable and is sensible as a top-level concern. This would add `useSSL=true` to the query line. sg?

**Comment by sharpcoder77** [comment]
Yes, that will do it

**Comment by codefromthecrypt** [comment]
started looking into this, but it seems awkward to test as most of the time you need to setup custom certs. Ex. if using RDS, you need to download a pem file, etc. 

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MariaDB.html#MariaDB.Concepts.SSLSupport

In other words there's more config than just the flag I think, and if we don't test this, then... well feels debty. Any thoughts on how to "finish the job" ex. patterns to stuff certs on disk in docker + self-signing one for mariadb? Or should we just open the flag and leave it to manual testing?

**Comment by sharpcoder77** [comment]
All parameters required for MySQL SSL can be passed as system properties to the JVM trying to use Mysql over SSL.

We can accept JAVA_OPTS for collector/query via environment variable, in which user can configure these parameters as:

```
-Djavax.net.ssl.keyStore=path_to_keystore_file
-Djavax.net.ssl.keyStorePassword=password
-Djavax.net.ssl.trustStore=path_to_truststore_file
-Djavax.net.ssl.trustStorePassword=password
```

Path to keystores can be mounted as a volume in container.

**Comment by codefromthecrypt** [comment]
good point! I think this can work.

**Comment by codefromthecrypt** [comment]
update: I've found what's needed to accomplish this, using spring-boot example for now. I've verified you only need 3 things:
- append `&useSSL=true` to the mysql url
- set `javax.net.ssl.trustStore` and `javax.net.ssl.trustStorePassword` JVM arguments

I used Amazon RDS and zipkin-java to verify. I'll raise a pull request both here and there to make this possible.

``` bash
# download the region-specific cert in PEM format, and install it (default is $HOME/.keystore)
# http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
$ keytool -import -alias mysqlServerCACertOR  -trustcacerts -file ~/Downloads/rds-ca-2015-us-west-2.pem

# Tell the JVM you trust the cert, by specifying your trustStore and password.
$ STORAGE_TYPE=mysql MYSQL_HOST=zipkin.abcdefg.us-west-2.rds.amazonaws.com MYSQL_USER=zipkin MYSQL_PASS=notetelling ./mvnw -pl zipkin-java-server spring-boot:run -Drun.jvmArguments="-Djavax.net.ssl.trustStore=/Users/acole/.keystore -Djavax.net.ssl.trustStorePassword=FOOBAR"

# check to make sure you are actually able to get data
$ curl http://localhost:9411/api/v1/services|jq .
```
