### ISSUE TITLE
zipkin-thrift jar does not include thrift generated code

### ISSUE THREAD

**Issue by vprithvi** [openzipkin/zipkin#892]
The `zipkin-thrift` jar (until at least version 1.28.0) only contains the thrift IDL files and none of the thrift generated java code. 

```
jar -tf /Users/prithvi/Downloads/zipkin-thrift-1.28.0.jar
META-INF/
META-INF/MANIFEST.MF
com/
com/twitter/
com/twitter/zipkin/
com/twitter/zipkin/zipkinDependencies.thrift
com/twitter/zipkin/zipkinCore.thrift
```

**Comment by eirslett** [comment]
That's the way it is supposed to be. Then, you can generate thrift files yourself. I think zipkin-scrooge is a package that contains auto-generated code.
