### ISSUE TITLE
Aggregates tab not visible and how to show dependencies graph

### ISSUE THREAD

**Issue by gauravrmazra** [openzipkin/zipkin#893]
Hi,

I am unable to see Aggregates tab in Zipkin UI. Is it some sort of configuration or it is removed?

**Comment by codefromthecrypt** [comment]
The tab is called dependencies and there will only be data if you are
running MySQL or Cassandra with the zipkin-dependencies-spark job.

**Comment by gamefundas** [comment]
I followed the example at DZone (https://dzone.com/articles/knowing-how-all-your) and ended up with a UI thats very different than the screenshots posted on the blog. 

For me, no Timeline tab, Dependencies appearing on the top menu, no service summary, stats box, favorites etc. Sort of limited UI functionality overall. Not sure if I am running a different version of zipkin-web.

Tried the tracegen to generate some data but still nothing to the effect. Does it mean that DB backend is required for the UI to be fully featured?

**Comment by codefromthecrypt** [comment]
That dzone article is almost 2 years old and doesn't serve as
documentation. The project has been rehosted to OpenZipkin and the UI
changed before that happened. The hadoop code to produce an aggregate view
was not merged when that article was written either. Long story short: we
can't change the past, so if your goal is to get started, why no engage
with us in the present?

As mentioned in the last thread, the MySQL storage type does query-time
aggregating, which isn't that scalable, but does work for small data sets.

I have no idea which data store you are using, but assuming it is
Cassandra, you can use the spark job (as we no longer support hadoop)

https://github.com/openzipkin/zipkin-dependencies-spark

If you'd like to discuss more, you can join
https://gitter.im/openzipkin/zipkin

**Comment by gamefundas** [comment]
Thanks for the clarification. We plan to use MySQL. Will try it out. Appreciate your help on this.

**Comment by codefromthecrypt** [comment]
anytime!

**Comment by gauravrmazra** [comment]
Thanks for clarifying @adriancole

**Comment by codefromthecrypt** [comment]
No problemo
