### ISSUE TITLE
UI should not prefer empty service name in annotations over non-empty ones

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#896]
When instrumenting outgoing HTTP calls, the target service name is not always known, so the client can emit ServerAddress annotation with the correct host:port, but empty service name. This results in the spans displayed in the UI with service name of "unknown", even though when the server is instrumented it emits a valid service name in sr/sr annotations.

Proposed fix:
- do not replace empty service names with "unknown" string, as it makes further processing/filtering difficult
- make sure the empty service name does not take precedence if the spans contains annotations with valid service names.

**Comment by codefromthecrypt** [comment]
Good idea. I suppose  this is the difference  between unknown  and not know
yet. Make sure the update also updates the thrift which says empty string
is not allowed.
