### ISSUE TITLE
Kafka with multiple partitions

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#903]
right now, the ruby and brave tracers produce messages w/o a partition set. We have tests to cover that this operates. Some tracers, such as the one @prat0318 is using in-house, produce spans to different partitions in the zipkin topic. We need to cover this use case with tests.

**Comment by codefromthecrypt** [comment]
cc kafka peeps @clehene @kristofa @espenkm @eirslett @jamescway

**Comment by jorgheymans** [comment]
As can be seen in the [Kafka Collector](https://github.com/openzipkin/zipkin/tree/master/zipkin-collector/kafka/src/main/java/zipkin2/collector/kafka), there is no manual partition assignment happening. Therefor a span reporter using multiple partitions is not an issue, in fact it's the standard Kafka Consumer working.
