### ISSUE TITLE
POMs in Maven Central have unresolvable versions for some dependencies

### ISSUE THREAD

**Issue by dsyer** [openzipkin/zipkin#910]
I assume this is a bug in the gradle configuration. For example from http://repo1.maven.org/maven2/io/zipkin/zipkin-web/1.30.0/zipkin-web-1.30.0.pom:

```
    <dependency>
      <groupId>com.github.spullara.mustache.java</groupId>
      <artifactId>compiler</artifactId>
      <version>${commonVersions.mustache}</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by codefromthecrypt** [comment]
Appears to be, yeah.. Those variables should never reach the repository!

@abesto if no other reasons than timezone and I'm headed out of country
tomorrow.. Mind having a look?

**Comment by abesto** [comment]
Sure thing. I'll have time on Saturday in the worst case.

**Comment by abesto** [comment]
The issue was introduced in 2412c4b8, Groovy doesn't interpolate on `'`, only on `"`. PR coming up.

**Comment by codefromthecrypt** [comment]
Awesome turnaround! Will cut a new release shortly
