### ISSUE TITLE
Overly sensitive test in DependencyStoreSpec

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#912]
@adriancole I noticed in zipkin-dependency-spark, the test `getDependenciesAllInstrumented` is disabled because it fails. I think it fails because it's the only one that calls `store.getDependencies` with a specific timestamp, while others call it with `today`. Cassandra job saves the DepLinks record with `Time.now` floored to a day, so while it produces the correct results, they cannot be retrieved by `store.getDependencies`. 

Would it make sense to redefine this test to use timestamps like `(today + 250) * 1000`, and then query at `today + 1000` like all other tests do?

**Comment by codefromthecrypt** [comment]
I didn't look deeply at why the job fails. If you can find a way for the
test to pass meaningfully for the 2 dep stores and spark, please do!

Thanks for having a look.

**Comment by yurishkuro** [comment]
@adriancole I will do a PR.

May also add more tests, per https://github.com/openzipkin/zipkin/issues/914

**Comment by codefromthecrypt** [comment]
thanks

**Comment by codefromthecrypt** [comment]
made a comment in the PR. I think the flooring concern shouldn't be conflated with the "today" one.

cassandra's impl will take an input date and floor it to a day. So, they can be retrieved, subject to the window which is a documented aspect of the dependency api. If the tests don't show that working, we can adjust them.

What I'm concerned about is losing a test that shows we can process data older than a day. For example, if _all_ of our tests look at _today_, we can easily make an impl that cannot process, for example, the data from 2 days ago. After looking at the test in question, I can tell that this aspect is non-obvious.

The test data should be explicitly a relative date such as 2 or 3 days ago (which avoids problems around any lookback defaults), as opposed to constants (which it has now). Also, we can rename the test to something like lookback3days which is doubley calls out the nature of the concern.

**Comment by yurishkuro** [comment]
sorry, replied on PR before seeing this. If the primary concern was "test that shows we can process data older than a day", then the fix is simple - I can probably leave the trace timestamps the same, but only change the query time to "today", because it's how Cassandra job always stores the result.
