### ISSUE TITLE
Single-sided RPC spans are not recognized for dependency diagram

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#914]
Specifically, in Cassandra implementation in zipkin-dependencies-spark, not sure about other stores.

There are situations where only the server or the client is instrumented, yet it is able to identify the peer and emit a ClientAddress or ServerAddress annotation within the single-sided span.  I want to add a test to the DependecyStoreSpec that will expect the store to return a parent-child link even for this span.

I also want to extend the DependencyLink model to include a boolean flag `singleSided` that will indicate that even though this link has been detected from the span, the instrumentation is not actually complete, which is useful for adoption tracking stats. Such link can be displayed in the UI as a dashed line. At minimum I would like to have this flag in the thrift class.

fyi, the change is meant to pass these two tests:

``` scala
  /**
   * In some cases an RPC call is made where one of the two services is not instrumented.
   * However, if the other service is able to emit "sa" or "ca" annotation with a service
   * name, the link can still be constructed.
   */
  @Test def getDependenciesOnlyServerInstrumented() = {
    val client = Endpoint(127 << 24 | 1, 9410, "not-instrumented-client")
    val server = Endpoint(127 << 24 | 2, 9410, "instrumented-server")

    val trace = ApplyTimestampAndDuration(List(
      Span(10L, "get", 10L, annotations = List(
        Annotation((today + 100) * 1000, Constants.ServerRecv, Some(server)),
        Annotation((today + 350) * 1000, Constants.ServerSend, Some(server))),
        binaryAnnotations = List(
          BinaryAnnotation(Constants.ClientAddr, true, Some(client))))
    ))
    processDependencies(trace)

    val traceDuration = Trace.duration(trace).get
    result(store.getDependencies(today + 1000)).sortBy(_.parent) should be(
      List(
        new DependencyLink("not-instrumented-client", "instrumented-server", 1)
      )
    )
  }

  /**
   * In some cases an RPC call is made where one of the two services is not instrumented.
   * However, if the other service is able to emit "sa" or "ca" annotation with a service
   * name, the link can still be constructed.
   */
  @Test def getDependenciesOnlyClientInstrumented() = {
    val client = Endpoint(127 << 24 | 1, 9410, "instrumented-client")
    val server = Endpoint(127 << 24 | 2, 9410, "not-instrumented-server")

    val trace = ApplyTimestampAndDuration(List(
      Span(10L, "get", 10L, annotations = List(
        Annotation((today + 100) * 1000, Constants.ClientSend, Some(client)),
        Annotation((today + 350) * 1000, Constants.ClientRecv, Some(client))),
        binaryAnnotations = List(
          BinaryAnnotation(Constants.ServerAddr, true, Some(server))))
    ))
    processDependencies(trace)

    val traceDuration = Trace.duration(trace).get
    result(store.getDependencies(today + 1000)).sortBy(_.parent) should be(
      List(
        new DependencyLink("instrumented-client", "not-instrumented-server", 1)
      )
    )
  }
```

As I am not familiar with other span store implementations, the new test will be disabled there, for now.

Any objections / suggestions?

**Comment by yurishkuro** [comment]
Actually, it might be better to use an enum `{ParentAndChild, ParentOnly, ChildOnly}` instead of a boolean flag.

**Comment by adriancole** [comment]
this looks sensible. I'd just name the endpoints "client" "server" so it is easier to understand (than the prior test)

**Comment by adriancole** [comment]
>
> Actually, it might be better to use an enum {ParentAndChild, ParentOnly,
> ChildOnly} instead of a boolean flag.
>
So the crux of this is the single-side span. Ex where these annotations are
logged into separate span ids vs the norm in zipkin where the same span
includes both client and server sides of the operation.

This would impact users who do this intentionally in zipkin, and also those
who use HTrace, which only supports single-size spans.

One key question here is whether or not this aspect should be the job of
the aggregator vs the job of the data format.

For example, can you raise visibility of the impacts of having the
aggregation job address this case? Ex. leave the result alone, and just
address the collapsing etc before the links are created, or by an
intermediate step?

**Comment by adriancole** [comment]
@eirslett there are two issues in this issue maybe you can help us think through.

one is supporting the parent/child case with the dependency link format as exists today, particularly when someone doesn't do the zipkin norm, which is to log client and server events in the same span.

the second issue is a proposal to add flags to the link data type itself. I'm usually sensitive to adding things that look complex, so probably more balanced for someone else to comment besides me.

**Comment by codefromthecrypt** [comment]
ps deleted my above note, which worried about the `{ParentAndChild, ParentOnly, ChildOnly}`. I don't want to cause FUD. I think this is actually not risking the dependency link itself, and the use case of tracking sounds quite interesting.

It might make the aggregation work more complex (ex more in a SQL query, or another intermediate state), but as far as I can tell doesn't change the cardinality of dependencyLinks (which was my first concern).

@yurishkuro mind bumping this into its own issue? I think I'm on board

**Comment by jcarres-mdsol** [comment]
I do not think it is necessary.
You can get all unique services by sr/ss from the store compare them with unique by ca and there you have your stats.

**Comment by codefromthecrypt** [comment]
@jcarres-mdsol to be clear, you are suggesting that the concern of reporting uninstrumented edges can be addressed in a different manner. Ex that the dependency graph doesn't need to hold this concern?

**Comment by yurishkuro** [comment]
Just to clarify what I want to do. I think of Dependency Graph as representing the architecture of the system, showing which services talk to each other. That function should be independent of how different tracers report data on RPC spans - one span or two spans. But at least in the Cassandra Spark job it is implemented to only build a link between two services if their names come from _two distinct spans_. I want to change that, and allow the job to consider, for example, standalone spans where the other service is still known (from SA or CA), as that still represents a valid architectural link.

As an illustration, look at the issue https://github.com/openzipkin/zipkin/issues/917. For a human it is obvious that there are 3 services involved in that "headless" trace, but the test expects only one link in the output.

So that's the primary objective of this ticket. The enum field is just a bit of extra data to record in each link, since the job now knows which of the two services was actually sending spans that were responsible for the link.

@jcarres-mdsol I am not quite following your suggestion. There is no way to query Cassandra in bulk, a M/R job is the only way to process all the data.  Per above, all the information is already present during the main Spark job, so the recording that information in the link seems like the best approach.

**Comment by yurishkuro** [comment]
@adriancole @jcarres-mdsol I've updated the description with the actual two new tests I am using to test the behavior. So far they only account for the shape of the graph, not for the extra enum describing the edge origin.

**Comment by kristofa** [comment]
@yurishkuro We have services (api gateway services) and databases which only are instrumented at either server or client side and they appear in the dependency overview when using `zipkin-dependencies-spark`.

**Comment by yurishkuro** [comment]
@kristofa it does work if the client is instrumented and emits ServerAddress. It does not work if only the server is instrumented, see https://github.com/openzipkin/zipkin/issues/917

**Comment by michaelsembwever** [comment]
Seems to make sense to add support for one-sided spans (where client is instrumented and emits ServerAddress).

I'm hesitant to adding an enum though. I get the impression it's just added schema when it's otherwise implied when reading the dependency graph.

**Comment by yurishkuro** [comment]
@michaelsembwever the graph only says a->b, it doesn't say if a and b have been instrumented, and that info is critical in driving the adoption efforts in the company.

**Comment by michaelsembwever** [comment]
@yurishkuro 

>  that info is critical in driving the adoption efforts in the company.

that type of rationale bears no weight in any open source project.
and i think you know that. 

either promote the idea for what it's worth, or fork the project.

Forking the project isn't a negative thing always. If you've got a company that requires a faster cadence that it can rationalise and get patches accepted then it's perfectly normal that the company keeps a fork so it gets what it wants and can take patience in arguing for and moving ideas back into the main repository. Maintaining a forked repository so it stays close to the original involves a little effort, but a rather trivial amount if you ask me.

In this manner, a company fork that's kept close to the original, is a Capabilities Interface, without weighing the community with the effort of the API part of it.

**Comment by jorgheymans** [comment]
It's nearing on 5 years since this idea was floated. Apart from that, the idea of using the dependency diagram to track adoption stats has never really caught on.

Other than that, this issue is notable as we see @michaelsembwever [foretell](https://github.com/openzipkin/zipkin/issues/914#issuecomment-177108525) the Forking of Zipkin.
