### ISSUE TITLE
Improve UI control behaviour before JS has loaded

### ISSUE THREAD

**Issue by jdb8** [openzipkin/zipkin#916]
I find often that before the js has fully loaded/executed on the query results page, I'll mistakenly click on a UI control (such as the sort order dropdown) and find that it does nothing. IMO it would feel much nicer to do one of the following:
- make it clear to the user that any interactions with the page before js has loaded will not work (disable the UI controls)
- handle any changes to the UI at the point when the js is loaded (probably more complex, but would arguably be the best solution). I suppose this could be implemented by checking if any UI control values are different from those provided in the query params, and performing the appropriate action if any differences are found?

**Comment by eirslett** [comment]
The UI has been rewritten, currently it shows a blank page until the js is loaded, which is somewhat ugly, but can be improved later on - in any case, since it's a pure javascript UI this won't be a problem in the future.
