### ISSUE TITLE
Test dependencies_headlessTrace is incorrect

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#917]
This test runs against this trace:

``` scala
  val trace = ApplyTimestampAndDuration(List(
    Span(1L, "get", 2L, Some(1L),
      annotations = List(
        Annotation((today + 50) * 1000, Constants.ClientSend, Some(zipkinWeb)),
        Annotation((today + 100) * 1000, Constants.ServerRecv, Some(zipkinQuery.copy(port = 0))),
        Annotation((today + 250) * 1000, Constants.ServerSend, Some(zipkinQuery.copy(port = 0))),
        Annotation((today + 300) * 1000, Constants.ClientRecv, Some(zipkinWeb))),
      binaryAnnotations = List(
        BinaryAnnotation(Constants.ClientAddr, true, Some(zipkinWeb)),
        BinaryAnnotation(Constants.ServerAddr, true, Some(zipkinQuery)))),
    Span(1L, "query", 3L, Some(2L),
      annotations = List(
        Annotation((today + 150) * 1000, Constants.ClientSend, Some(zipkinQuery)),
        Annotation((today + 200) * 1000, Constants.ClientRecv, Some(zipkinQuery))),
      binaryAnnotations = List(
        BinaryAnnotation(Constants.ClientAddr, true, Some(zipkinQuery)),
        BinaryAnnotation(Constants.ServerAddr, true, Some(zipkinJdbc))))
  ))
```

and it expects the output `List(zipkin-query->zipkin-jdbc(1))`.

I think the expected output is wrong, as from the first span it is clear (to a human) that there should be `zipkinWeb -> zipkinQuery`.

After my change (WIP) to https://github.com/openzipkin/zipkin/issues/914, the actual output from Cassandra store in this test is `List(zipkin-web->zipkin-query(1), zipkin-query->zipkin-jdbc(1))`.

Thoughts?  It's easy to change the test condition, but I am not sure if it's going to be very difficult to support spans like this in other stores.

**Comment by t-yuki** [comment]
I think AnormDB implementation also have same problem and I'm working on to fix it with the other problem.

**Comment by codefromthecrypt** [comment]
Thanks for keeping an eye, out, yuki. Whatever you find in anorm will
likely need to be repeated in zipkin-java (which I can do, if you aren't
into java)

I can't comment too much on this today, but glad the both of you are
looking at it.

**Comment by yurishkuro** [comment]
There's another option. From the description of this test, it's main goal is to check if the store can deal with traces where root span has `traceID != spanID`. To make this test forward-compatible with #914, we can change the assertion to expect _at least_ `List(zipkin-query->zipkin-jdbc(1))`, but not break if there are other edges. My PR https://github.com/openzipkin/zipkin-dependencies-spark/pull/18 contains two more tests that specifically test the addition of edges for single-sided spans, so when they make it to core they will test the extra conditions. And once other stores implement support single-sided spans, this "headless" test can be changed back to "should equal".

**Comment by yurishkuro** [comment]
An even better option - Capabilities API, #931

**Comment by jorgheymans** [comment]
The [test](https://github.com/openzipkin/zipkin/blob/946b96ce18e9b5cdc31bb447bcf09dc1df383f0f/zipkin-tests/src/main/java/zipkin2/storage/ITDependencies.java#L230) has evolved long since and works correctly.
