### ISSUE TITLE
Why does Span.serviceName give priority to ServerAddress?

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#919]
I agree that server-side should take precedence over client-side, but it seems the CoreServer annotations should be the top priority, not ServerAddress binary annotation. In the current form, if 10 clients call the same service, but all decide to call it differently in ServerAddress, it will appear under 10 different names. And if the service owners wants to find traces in their service, they need to search under 10 names.

But if the CoreServer annotation is the first priority, it will always have the same name.

**Comment by codefromthecrypt** [comment]
serveraddress was added to allow far-right resources to show up, for example, uninstrumented mysql servers, S3, etc.

clientaddress was not as it explodes the far left

**Comment by yurishkuro** [comment]
@adriancole by far-right do you mean those that will not log their own annotations? In that case the span will have Client Send/Recv and a ServerAddress, and the latter will win. I am not proposing to change that, only to let Server Send/Recv win over ServerAddress.

**Comment by codefromthecrypt** [comment]
I don't have a strong opinion about who should win "sa" vs "sr", as long as
"sr" isn't required.

Would be nicer if we could resolve at collection time, but anyway..

I don't have a problem with changing the precedence, I would just make a
comment in the test with your rationale.

Seems this is an assumption that clients are more likely to make mistakes
naming the destination than servers naming themselves.. I buy that.

**Comment by codefromthecrypt** [comment]
Yeah I think you understand my concern, which was about a potential
explosion on the left side if we named nodes based on clients (fear which
might not be substantiated).

Regardless, you've clarified to me this isn't impacted at all.

**Comment by michaelsembwever** [comment]
@eirslett have you any opinion on this?

We faced the problem that @yurishkuro mentions with clients calling servers different things and we have to address it by making the clients use our discovery-service so service name was always correct. (I think we had to do the same with the CoreAnnotation as well anyway).

**Comment by eirslett** [comment]
The logic for this is ported to JavaScript. There are karma tests, so it should be easy enough to add a test that verifies the wanted behavior, and then changes the order of precedence.

**Comment by jorgheymans** [comment]
The question was answered, has not received any further comments in a while so closing.
