### ISSUE TITLE
Dependency Store API defines time range as closed interval

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#924]
`getDependencies` doc says:

```
   * @param endTs only return links from spans where [[com.twitter.zipkin.common.Span.timestamp]]
   *              are at or before this time in epoch milliseconds.
   * @param lookback only return links from spans where [[com.twitter.zipkin.common.Span.timestamp]]
   *                 are at or after (endTs - lookback) in milliseconds. Defaults to endTs.
```

That means the interval is closed on both ends, which is unusual pattern for time range query API, since running a query for sequential intervals can produce duplicates. Usually query APIs are defined as open-closed interval `(start, end]`, not `[start, end]`.

I was running into subtle edge cases in the Spark job because of this. Incidentally, if we do change the API to use open-close interval, the tests in DependencyStoreSpec would need to be adjusted such that `endTs` and `endTs - lookback` timestamps land on the opposite sides of `floorToDay(endTs)` (or whichever window is used).

**Comment by jorgheymans** [comment]
Even though the concerns raised here probably are relevant, I am closing this issue as it's approaching its 5 year anniversary and nobody else has been bothered by this. As always, feel free to raise a PR if you feel strongly about this, make sure to hop on our gitter channel https://gitter.im/openzipkin/zipkin beforehand to discuss the proposed design changes. Thanks !
