### ISSUE TITLE
We might be logging invalid span timestamps

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#926]
from @jcarres-mdsol

I've noticed now the "start_ts" in the zipkin_spans have changed the format to look like "20151013064708" .. from http and zipkin-web

^^ is certainly not epoch micros even if it is a number

this could be related to the code that adds a default span timestamp, as I don't think finagle tracers actually include span.timestamp

**Comment by jorgheymans** [comment]
I'll wager that if span timestamps had been incorrect back then, it would have been fixed long since.
