### ISSUE TITLE
Additional span stores for ElasticSearch and possibly DynamoDB?

### ISSUE THREAD

**Issue by sidneyshek** [openzipkin/zipkin#928]
We currently have a ElasticSearch span store in-house that allows us to query for traces in ES indices, and we would like to contribute this upstream as we hope it would be useful for others. What's the appetite for this and maintaining it as part of this project?

We are also investigating the possibility of writing a DynamoDB span store (we would prefer not to manage a Cassandra cluster if possible). Thoughts?

**Comment by yurishkuro** [comment]
@sidneyshek we're very interested in ES backend!!! Would love to see a working impl. Cassandra is good at throughput, but the querying capabilities are exceptionally poor in the current Zipkin implementation.

**Comment by codefromthecrypt** [comment]
Hi!

Thanks for thinking about this! Our new data stores are in separate github
repositories. If it becomes very popular and well maintained, we could
consider promoting it into the main repo, but certainly best to at least
incubate it outside.

If you get to a point where you are closer.. Maybe suggest a name!

Ps Are you planning to write this in scala or java?

**Comment by karlunho** [comment]
I'd love to see an ES backend, because then it would in theory give the ability to do faceted searches.

Btw - I'm self promoting here, but if you might be interested in Apache usergrid (http://usergrid.apache.org ). It's a Backend as a Service that uses ES for indexing but C\* for the the storage. It was originally designed for mobile app back ends , but we've built in graph query capabilities on top of C_, and added all sorts of neat features that might be applicable such as C_ counter abstractions, which might be useful for doing aggregations. 

This is similar to the idea of how AWS recommends using ES in conjunction with DynamoDB (except that Usergrid can run in a docker container ;-)

Ok - this is the 2nd self promo of usergrid today since Parse shut down today too ;-) 

Let me know if anyone is interested ....

Regards,
Alan Ho

**Comment by sidneyshek** [comment]
@adriancole It's currently in Scala, we've got some tests to write before releasing. Having it under OpenZipkin as a separate incubator repo makes sense to me. My biggest concern is how API changes in core zipkin flow down to these other backends. What's the (proposed?) process for that? We've been bitten by recent changes which aren't reflected in type signatures like span sort ordering and enforced lower case for span and service names. Wonder if we can do some contract-style testing (so some base integration spec that all backend repos need to implement)?

**Comment by codefromthecrypt** [comment]
Hi, there.

We have 2 storage test cases, which if run will break when upstream changes
clarify something.

https://github.com/openzipkin/zipkin/tree/master/zipkin-cassandra/src/test/scala/com/twitter/zipkin/storage/cassandra

Luckily, the rate of change is far less. Plus I can help with the repo
setup (and watching the tests). If you are interested in collaborating, we
should pick a name and work together to make sure the burden is least.

maybe zipkin-scala-elasticsearch or something?

ps the actual repo will be similar to
https://github.com/openzipkin/zipkin-dependencies-spark or
https://github.com/openzipkin/zipkin-mongodb

**Comment by sidneyshek** [comment]
`zipkin-scala-elasticsearch` sounds great! I'll start pulling our code apart to match one of the existing repos over the next few days.

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin-scala-elasticsearch

**Comment by eirslett** [comment]
I'll close this issue - elasticsearch issues should go here: https://github.com/openzipkin/zipkin-scala-elasticsearch

**Comment by codefromthecrypt** [comment]
elasticsearch is being very quickly implemented here. It may move to the above repo at some point, probably with a different name as no scala is involved https://github.com/openzipkin/zipkin-java/pull/107

**Comment by sidneyshek** [comment]
I feel embarrassed we haven't had the time to push up our ES implementation yet. If you guys are close then it might be worth closing off the scala repo.

**Comment by codefromthecrypt** [comment]
good idea.. just nuked it, as agreed it would be confusing to others.
