### ISSUE TITLE
Relationship between CLIENT_SEND and SERVER_RECV annotations of spans

### ISSUE THREAD

**Issue by t-yuki** [openzipkin/zipkin#929]
I'm working on AnormDependencyStore to fix some missing dependencies which have intermediate spans between RPC.
For more details, see wip test https://github.com/t-yuki/zipkin/commit/6bd69e365be4a4bf6a260c4935ad1af3d105f5a5#diff-206cff9258cbda55156ecb3e85c2862dR191

Now, I wonder the relationship between CLIENT_SEND and SERVER_RECV annotations of spans.
I surveyed several implementation and test spec but they varies.

DependencyStoreSpec says cross service requests share a span.
~~However, zipkin-tracer (Ruby) seems to be created new span on SERVER_RECV that is a child of CLIENT_SEND.~~
And annotations reported by zipkin-web/query itself are no way.

How should I handle implementation varieties? or Have I misinterpreted?
Or it is not specified so should DependencyStore handle all possible patterns?
### DependencyStoreSpec

```
[service1] Span0: SR
[service1]   Span1: CS-SA[service2]
[service2]   Span1: SR-CA[service1]
```

It  says cross service requests share a span.
### zipkin-web/query

 Finagle?: https://github.com/twitter/finagle/blob/150bbf14ccff580bf156e6ef185f54fd4fc75e76/finagle-core/src/main/scala/com/twitter/finagle/tracing/Trace.scala#L238

```
[service1] Span0: SR-SA[service1]-CA[service1]
[service2]   Span1: CS-SA[service1]-CA[service1]
```

Unless I'm mistaken, it seems to be corrupted.
### zipkin-tracer (Ruby)

 SR: https://github.com/openzipkin/zipkin-tracer/blob/master/lib/zipkin-tracer/rack/zipkin-tracer.rb#L41
 CS: https://github.com/openzipkin/zipkin-tracer/blob/master/lib/zipkin-tracer/faraday/zipkin-tracer.rb#L52

```
[service1] Span0: SR
[service1]   Span1: CS-SA[service2]
[service2]     Span2: SR
```

~~It creates new span on Server Receive.~~

**Actually it has the same output to test spec, OK.**
### Go

 SR: https://github.com/spacemonkeygo/monitor/blob/master/trace/manager.go#L106
 CS: https://github.com/spacemonkeygo/monitor/blob/master/trace/http.go#L37

[service1] Span0: SR
[service1]   Span1: CS
[service2]   Span1: SR

It is the same to TestSpec.

**Comment by codefromthecrypt** [comment]
This topic comes up a lot.

In zipkin, canonical spans come in two forms ["sr", "ss"] and ["cs", "sr", "ss", "cr"], depending on whether the client is instrumented or not.

For example, zipkin (and dapper) examples usually do not have client-originated traces. So, the root span usually looks like  ["sr", "ss"]. If there's an outgoing call, it would look like this  ["cs", "sr", "ss", "cr"]. The latter "sr", "ss" annotations are contributed by the downstream services into the same span.

We did throughly review the intent of the address annotations, which are documented here https://github.com/openzipkin/zipkin/blob/master/zipkin-thrift/src/main/thrift/com/twitter/zipkin/zipkinCore.thrift

If you haven't seen this, have a look and let me know if there's any questions. No doubt that implementations (and spec data) have been out-of-sync. PS don't forget one primary trace instrumentation is openzipkin/brave.

**Comment by codefromthecrypt** [comment]
cc @jcarres-mdsol

**Comment by t-yuki** [comment]
Thanks, I read thrift file firstly but I'm not sure the server should start new span or use provided span id by Request Header, for SERVER_RECV annotation as the spec.
Anyway implementations are varied...

**Comment by codefromthecrypt** [comment]
Long story on that one ;)

If the server has no propagated context Headers, it usually starts a new
span. If the headers are present, those ids are used. If a header says "not
sampled" then no trace is created.

Happy to chat more about this, too. Are you free to join the tracing
workshop Monday, Tuesday? We can review some of these things in a Tokyo
friendly time.

https://docs.google.com/document/d/1CWiSc2PaKh9YAg5P5zE7S2q-RkpRv1kqQh_z-HefLng/edit?usp=sharing_eid&ts=563bfa38

**Comment by jcarres-mdsol** [comment]
The method in ruby is named terribly, it does create a new Span object in Ruby but it does not find a new ID for this span, so if your trace_id had the ids from the http request, the SR will send to zipkin a span with the same IDs than the CS which I think will work as per the spec

**Comment by t-yuki** [comment]
Oh I see. You are right, I didn't checked `tracer.with_new_span` method carefully.
So as far as I know. the remaining problem is that default zipkin-web, zipkin-query and tracegen create obscurity annotations.

OK, tracegen maybe misused CLIENT_SEND and CLIENT_RECV because they annotates it with `nextEp`, not current `ep`: https://github.com/openzipkin/zipkin/blob/master/zipkin-tracegen/src/main/scala/com/twitter/zipkin/tracegen/TraceGen.scala#L127
Should I open a pull request to fix?

Also zipkin-web, zipkin-query may have another problem as explained above but it is not examined yet.

**Comment by t-yuki** [comment]
Thanks, the workshop is interesting. Maybe I have no time to join actively but I'll watch gitter.

**Comment by yurishkuro** [comment]
> OK, tracegen maybe misused CLIENT_SEND and CLIENT_RECV because they annotates it with nextEp

the endpoint in the annotation is supposed to refer to the service that is emitting the annotation. Since `ep` is the current server acting as client, the code seems correct.
