### ISSUE TITLE
RFC: extend DependencyLink data model to include inferred instrumentation

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#930]
## Background

 Adoption is one of the biggest challenges to successful deployment of distributed tracing in an organization. Developers often need to upgrade dependencies of their services and change configuration (in the best case), or even change the application code (in the worst case). Therefore, automatic tracking of adoption stats is very important for distributed tracing teams. The Dependencies graph partially provides these stats, however the edges in the graph sometimes represent a link between two services where only one of the services is fully instrumented for tracing, and the other service name is simply inferred from RPC fields (cf. #914). This is useful information to track in the Dependencies data model, since that information is explicitly available in the traces that are aggregated into dependency graph. 
## Proposal

Add an optional `instrumentation` field to `DependencyLink`.
### Thrift

``` thrift
struct DependencyLink {
  /** parent service name (caller) */
  1: string parent
  /** child service name (callee) */
  2: string child
  #3: Moments OBSOLETE_duration_moments
  /** calls made during the duration of this link */
  4: i64 callCount
  # histogram?
  /** which service(s) actually submitted span data that resulted in this link */
  5: optional Instrumentation instrumentation
}

/** 
 * Describes which service(s) submitted span data that resulted in a DependencyLink. 
 */
enum Instrumentation {
    /** Both parent and child services submitted span data */
    PARENT_AND_CHILD,

    /** Only the parent service submitted span data; the child service name was inferred from it */
    PARENT_ONLY,

    /** Only the child service submitted span data; the parent service name was inferred from it */
    CHILD_ONLY
}
```
### Scala model

In the object model we need a way to "merge" two links with the same `(parent, child)` pair, e.g. when merging Dependency sets from several days. The proposal is to give `ParentAndChild` a priority over the other two values.

``` scala
  sealed trait Instrumentation {
    def +(other: Instrumentation): Instrumentation
  }
  case object ParentAndChild extends Instrumentation {
    override def +(other: Instrumentation): Instrumentation = this
  }
  case object ParentOnly extends Instrumentation {
    override def +(other: Instrumentation): Instrumentation = other match {
      case ParentAndChild => other
      case ChildOnly => ParentAndChild
      case _ => this
    }
  }
  case object ChildOnly extends Instrumentation {
    override def +(other: Instrumentation): Instrumentation = other match {
      case ParentAndChild => other
      case ParentOnly => ParentAndChild
      case _ => this
    }
  }
```

**Comment by codefromthecrypt** [comment]
I mentioned my opinion on another issue.

Here's it again, I don't believe dependency links should be carrying information like this. It complicates the model for a niche, and introduces questions, like.. what if some links from service A->B are instrumented differently than others? Do we now have 2 links for the same path?

Zipkin primarily serves latency analysis, not software management. The fact that links don't have latency data on them is merely unfinished work. The more responsibilities and other ancillary work we add to the project, the less chance we have for finishing highly sought after, unfinished work.

I don't think that dependency link is the only reporting structure, and I would love to hear why we assume it must be? The type of change we add to the project must represent highest need, if we aren't to make it a complicated mess again.

**Comment by codefromthecrypt** [comment]
Here's an alternative: This report could be made in a separate repo and stored in a different table. Probably the UI could be written far cleaner than our current one. An advantage is that the next field of interest about tracers has a far more coherent place to go. The other advantage mentioned is that this leaves the current dependency model clear to actually complete! ie adding latency data, something mentioned multiple times.

http://blog.codinghorror.com/rule-of-three/

If a reporting project is made, and no-one besides you use it, we'll know that it shouldn't have gone upstream anyway. We wouldn't have displaced effort from people who aren't interested. If on the other hand, it becomes popular, we've a new microservice of value in zipkin as opposed to an increasingly hard to maintain monolith. IOTW, interested people have a more nimble way to contribute to tracer inventory/adoption projects.

Regardless, I'd encourage you to brief others, for example at our workshop next week. Maybe you've already met rule of three? Maybe lyft or coursera or someone else also wants this, and would feel stifled if this didn't happen immediately in the existing data structures? Worth finding out, imho

https://docs.google.com/document/d/1CWiSc2PaKh9YAg5P5zE7S2q-RkpRv1kqQh_z-HefLng/edit#

**Comment by michaelsembwever** [comment]
> If a reporting project is made, and no-one besides you use it, we'll know that it shouldn't have gone upstream anyway. We wouldn't have displaced effort from people who aren't interested. If on the other hand, it becomes popular, we've a new microservice of value in zipkin as opposed to an increasingly hard to maintain monolith.

agreed on this notion.
sometimes more complicated proposals need to be handled this way.
more damage can come than good by adding too much too early.

**Comment by yurishkuro** [comment]
not much interest in this, so closing
