### ISSUE TITLE
RFC: Introduce backend store Capabilities API

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#931]
It seems #914 is highlighting the need to introduce some sort of Capabilities API for zipkin backend stores so that people who need new features can progress independently without waiting for every single backend store implementation to support a new feature before the feature can be moved into core.

This is especially evident in tests, e.g. #917, where a new feature cannot proceed without upgrading the tests, and the tests cannot be upgraded easily because other backends would not support that.

Proposal: extend SpanStore and DependencyStore API with `getCapabilities()` method returning something like this:

``` scala
trait DependencyStoreCapabilities {
    def canBuildEdgeForSingleSidedSpan: Boolean
    def canInferInstrumentationForEdge: Boolean
}

object DefaultDependencyStoreCapabilities extends DependencyStoreCapabilities {
    val canBuildEdgeForSingleSidedSpan = false
    val canInferInstrumentationForEdge = false
}
```

**Comment by codefromthecrypt** [comment]
is there anyone besides @yurishkuro interested in this?

**Comment by michaelsembwever** [comment]
:-1: 
Until more interest is seen on this I'd rather promote kept-close forks for this type of "additions".

Forking the project isn't a negative thing always. If you've got a company that requires a faster cadence that it can rationalise and get patches accepted then it's perfectly normal that the company keeps a fork so it gets what it wants and can take patience in arguing for and moving ideas back into the main repository. The cadence of open source projects and companies internal development simply don't match, and we can't force that. Maintaining a forked repository so it stays close to the original involves a little effort, but a rather trivial amount if you ask me.

In this manner, a company fork that's kept close to the original, is a Capabilities Interface, without weighing the community with the effort of the API part of it.

It also means that proposals into the main repository have well implemented and tested solutions. The success of implementations eases many of the concerns as to whether the added complexity will pay off.

**Comment by eirslett** [comment]
I'll close this due to lack of activity and disagreement on whether this is the right direction for upstream Zipkin or not.
