### ISSUE TITLE
Have a way to pass `KAFKA_CONSUMER_GROUP_ID` as env variable

### ISSUE THREAD

**Issue by prat0318** [openzipkin/zipkin#933]
similar to `KAFKA_STREAMS` and `KAFKA_TOPIC` there should be a way to pass another consumer group name, so that two collectors can read and ingest from a same topic. Right now, if one is registered another one is denied any partition ownership.

**Comment by codefromthecrypt** [comment]
OK, so to test this, we could publish 2 spans make two collectors consume
one each

**Comment by prat0318** [comment]
that will happen only if the first collector updates the lowmark. I am fine even if the second group also starts reading from the first message

**Comment by codefromthecrypt** [comment]
Is updating the low mark something obvious in the api? (ex pastable). I've
not done this before. Regardless, good point.. we can have the test pass if
the second reads at least one span

**Comment by prat0318** [comment]
i dont think there is such an api. i think the way kafka works, if multiple consumer groups are reading from a topic both will receive the same message independant of each other. I think that is fine. so we can work out the example even with a single span.

**Comment by codefromthecrypt** [comment]
sorry .. is this literally "group.id" in kafka?
