### ISSUE TITLE
Collection-tier service naming practice

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#935]
If there was a documented practice for naming services, implicitly traced spans could have more relevant names.

@karlunho and @dankosaur mentioned the same solution to this, which is a stage in collection that resolves names.

**Comment by codefromthecrypt** [comment]
This could be a google doc in the features folder, if interested enough: https://drive.google.com/drive/u/1/folders/0B0tSnQT3uGdAfmZaVzZfOXJRRzZPUmRDRFVGRUFHVm1fX2ZXenM1VGN3RElTQzc3azI3X1k

**Comment by codefromthecrypt** [comment]
Lacking this, there's a fallback order at query time, but this code has proven itself high maintenance. If there was a way to hard-set a service name correctly before storage, this problem space could become smaller.

ex. https://github.com/openzipkin/zipkin/blob/master/zipkin-common/src/main/scala/com/twitter/zipkin/common/Span.scala#L76

``` scala
  /**
   * Tries to extract the best name of the service in this span. This depends on annotations
   * logged and prioritized names logged by the server over those logged by the client.
   */
  lazy val serviceName: Option[String] = {
    // Most authoritative is the label of the server's endpoint
    binaryAnnotations.find(_.key == Constants.ServerAddr).map(_.serviceName).filterNot(_.isEmpty) orElse
      // Next, the label of any server annotation, logged by an instrumented server
      serverSideAnnotations.headOption.map(_.serviceName).filterNot(_.isEmpty) orElse
      // Next is the label of the client's endpoint
      binaryAnnotations.find(_.key == Constants.ClientAddr).map(_.serviceName).filterNot(_.isEmpty) orElse
      // Next is the label of any client annotation, logged by an instrumented client
      clientSideAnnotations.headOption.map(_.serviceName).filterNot(_.isEmpty) orElse
      // Finally is the label of the local component's endpoint
      binaryAnnotations.find(_.key == Constants.LocalComponent).map(_.serviceName).filterNot(_.isEmpty)
  }
```

**Comment by jorgheymans** [comment]
@adriancole is this thought still valid or can we close ?

**Comment by codefromthecrypt** [comment]
v2 format made this far less hairy than before. in v1 you could have like 4 different names in the same span!
