### ISSUE TITLE
Spans with same service_name, and name getting squashed

### ISSUE THREAD

**Issue by prat0318** [openzipkin/zipkin#941]
![](http://i.imgur.com/7C9s7G2.png)

This shows even if service_name (`example_happyhour`) and span_name (`query`) are same, still different spans get logged. I believe this behaviour was fine in v1.23.0.

But now (1.31.0), only the last `query` is shown. On looking at the insert logs as well, it looks like only unique insert statements are executed. So, it is somewhere in collector (CassandraStore) where the change has gone.

As, there can be spans with same service_name and names, this is a **bug**.

@adriancole i could not run an old version collector because of #933 issue present on old version (so i can't run multiple instance with same consumer group), so filing up the ticket here.

**Comment by yurishkuro** [comment]
@prat0318 just to make sure, did you click on Expand All?

**Comment by prat0318** [comment]
@yurishkuro yeah that didn't work. In fact, adding random suffices after `query` for each span, indeed showed up different spans.

**Comment by prat0318** [comment]
My bad. It was a subtle bug in `pyramid_zipkin`. Closing it up
