### ISSUE TITLE
zipkin-web-all.jar isn't getting javascript assets

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#953]
This might be a travis or release related config. The zipkin-web all jar is missing javascript assets. We can't release another version until this is fixed.

ex. download a recent jar here, and java -jar it (or jar -tf it) http://oss.jfrog.org/artifactory/oss-snapshot-local/io/zipkin/zipkin-web/1.32.4-SNAPSHOT/

**Comment by codefromthecrypt** [comment]
@abesto @eirslett can either of you have a look?

**Comment by abesto** [comment]
Will take a look tonight (~4 hours from now)

**Comment by abesto** [comment]
Learning nr. 1: `zipkin-web/src/main/resources/dist` is not removed by `zipkin-web:clean`. It's also ignored by `git clean`, because `.gitignore`. Now that I've removed it manually, I can reproduce the issue locally.

**Comment by codefromthecrypt** [comment]
verified by running the snapshot jar
