### ISSUE TITLE
[ui] Frozen highlighting in the navigation bar

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#960]
Maybe someone knows how to quickly fix it in mustache.

https://github.com/openzipkin/zipkin/blob/master/zipkin-web/src/main/resources/templates/v2/layout.mustache#L23

``` html
        <div class="navbar-left">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Find a trace</a></li>
            <li><a href="/dependency">Dependencies</a></li>
          </ul>
        </div>
```

The `class="active"` is always hardcoded on the Find a Trace menu item, even if the page is showing Dependencies.

**Comment by eirslett** [comment]
We could set it to

``` mustache
<li {{#isTracePage}}class="active"{{/isTracePage}}>...</li>
```

And then, in zipkin-web/scala, add "isTracePage" to true to the data that is sent to MustacheRenderer.
(Same with isDependencyPage)

**Comment by yurishkuro** [comment]
ok, that worked, I can submit a pr, but first need to fix the build issue I posted in gitter
