### ISSUE TITLE
[ui] Service name not present for some spans

### ISSUE THREAD

**Issue by marcingrzejszczak** [openzipkin/zipkin#962]
Hello,

in our e2e test project (https://github.com/spring-cloud-samples/brewery) we're testing integration with Zipkin. For some of the created spans the UI is not presenting the service name. 

![zipkin](https://cloud.githubusercontent.com/assets/3297437/12975398/929ef1c8-d0bb-11e5-9636-69b0d4deee26.png)

I've done an analysis of the JSON from Zipkin and it seems to be valid. Most likely there is a bug in the UI
## How to reproduce?
- Either see the attached JSON.

[zipkin_json.txt](https://github.com/openzipkin/zipkin/files/126243/zipkin_json.txt)
- Or execute this (for linux):

```
git clone https://github.com/spring-cloud-samples/brewery.git
cd brewery
bash runAcceptanceTests.sh -t SLEUTH -k
```

and then check `localhost:8080` for Zipkin UI

**Comment by codefromthecrypt** [comment]
spot checked one with a missing span name.. and it was a local span.

``` json
  {
    "traceId": "1a6f929826b14a57",
    "name": "async:ingredientsfetchcontroller#method=ingredients",
    "id": "3dbcebf1dfa30d29",
    "parentId": "f88ee39a5700b1db",
    "timestamp": 1.455188843323e+15,
    "duration": 1000,
    "annotations": [

    ],
    "binaryAnnotations": [
      {
        "key": "lc",
        "value": "unknown",
        "endpoint": {
          "serviceName": "brewing",
          "ipv4": "127.0.0.1",
          "port": 9992
        }
      }
    ]
  }
```

**Comment by codefromthecrypt** [comment]
can't look deeper now, but next step is to pare down the data to include spans whose service name are not on the left. Then analyze them.

Ex. is there a common trait among these (or common traits?)
like.. spans missing core annotations? ("cs" "sr" "ss" "sr")? spans that are local? Is there something about the json itself that looks different than ones that display serviceNames? Does api/v1/services include the missing service name? Does api/v1/spans?serviceName=missing_name work?

I _think_ the rendering code is this, but we could probably narrow down a bit more, as it makes testing easier
https://github.com/openzipkin/zipkin/blob/master/zipkin-web/src/main/resources/app/js/component_ui/trace.js

**Comment by virtuald** [comment]
I've ran into this too -- and the common thread for mine seems to be that they are missing the core annotations (cs, sr, et al).

**Comment by codefromthecrypt** [comment]
The zipkin ui is tuned for zipkin annotations, so if you aren't logging any zipkin annotations, they won't show up. We have tests to show that if zipkin annotations are logged, a service name will be chosen. 

https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/test/component_ui/traceSummary.test.js

First thing is to correct your instrumentation to log a zipkin annotation (like "sr"), or a [special zipkin binary annotation](https://github.com/openzipkin/zipkin/blob/master/zipkin-thrift/src/main/thrift/com/twitter/zipkin/zipkinCore.thrift#L199) ("ca", "sa" or "lc").

You can validate your data by changing the url into an api call. ex. http://host:9411/api/v1/trace/hex-encoded-id returns the json
