### ISSUE TITLE
How should we handle single-host RPC spans in the UI?

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#963]
At least htrace, opentracing, google cloud trace and sleuth use single-host spans. For example, client send and server receive are in different spans, based on the client or the server tracer.

Zipkin's v1 model was designed to have client and server in the same span, hence the need for the annotations "cs" "sr" "ss" "sr".  Zipkin v2 will probably move to single-host (per #939)

Zipkin's UI was designed for when a single span contained both client and server sides. Ex. there's a single bar for a client+server span, and there are dots for each of the major client or server events (such as client receive or server send). This cuts the visual depth of a trace quite a bit.

Conversely, single-host spans have a separate span for a client or a server. This means that a server span is visually below its client counterpart. For the same amount of RPCs, this is double the "bars" vs client+server spans.

Do we need any UI work wrt single-tracer RPC spans, or is status quo ok?

**Comment by codefromthecrypt** [comment]
cc'ing some who might have an opinion: @marcingrzejszczak @yurishkuro @clehene

**Comment by yurishkuro** [comment]
@adriancole the examples you asked for. Looks fairly normal, the one weird thing is the query service adds server annotations to the middle span `client.post`. Also, the server span is centered, even though the IP is the same (though I haven't used the latest code).

[3b47c02255029f91.json.txt](https://github.com/openzipkin/zipkin/files/127472/3b47c02255029f91.json.txt)

<img width="1363" alt="screen shot 2016-02-11 at 9 00 38 pm" src="https://cloud.githubusercontent.com/assets/3523016/12998568/537836c8-d113-11e5-8ddf-d145fe44a4ef.png">

<img width="981" alt="screen shot 2016-02-11 at 9 01 45 pm" src="https://cloud.githubusercontent.com/assets/3523016/12998559/32c72c22-d113-11e5-8104-7e7300b1e512.png">

<img width="982" alt="screen shot 2016-02-11 at 9 01 55 pm" src="https://cloud.githubusercontent.com/assets/3523016/12998560/32c8651a-d113-11e5-8ad6-07739465a37e.png">

<img width="977" alt="screen shot 2016-02-11 at 9 02 06 pm" src="https://cloud.githubusercontent.com/assets/3523016/12998561/32caad16-d113-11e5-8b0c-27d38977be41.png">

**Comment by codefromthecrypt** [comment]
closed in favor of #1799
