### ISSUE TITLE
Change cassandra to use latency-aware load balancing

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#967]
Per https://github.com/openzipkin/zipkin/pull/958/files#r52631161, we should consider changing the load balancing policy to be latency aware. Perhaps @yurishkuro or @danchia could shed light on how this is impactful.

The change to CassandraSpanStoreFactory would look like this:

``` scala
new TokenAwarePolicy(new LatencyAwarePolicy.Builder(new DCAwareRoundRobinPolicy(dc)).build())
```

One thing to consider is what to default `dc` to? I suppose this will end up another flag, like `CASSANDRA_LOCAL_DC`

**Comment by yurishkuro** [comment]
The default Cassandra installation uses dc=`datacenter1`. The real one should come from env, as you said.

**Comment by yurishkuro** [comment]
As for impact, it depends how the prod cluster is configured. We had one cluster name spanning 2 DCs, with distinct keyspaces per DC, yet the plain round robin policy would periodically pick a host from the other DC as coordinating node, causing latency up to 60sec.
