### ISSUE TITLE
webpack not getting installed

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#970]
@eirslett another build issue, this time from our deployment pipeline that builds zipkin-web in a docker image.  After finishing downloading npm modules, it's unable to find `webpack.js`. Any suggestions?

```
WARN In npm@3.6.0 replacing bundled version of path-array with path-array@1.0.1
npm WARN In npm@3.6.0 replacing bundled version of node-gyp with node-gyp@3.2.1
[0m:zipkin-web:webpack
2016-02-12 23:18:50Z    
> zipkin-web@0.0.0 build /home/udocker/zipkin/zipkin-web
> node node_modules/webpack/bin/webpack.js --bail

2016-02-12 23:18:51Z    module.js:341
    throw err;
    ^

Error: Cannot find module '/home/udocker/zipkin/zipkin-web/node_modules/webpack/bin/webpack.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

npm ERR! Linux 3.18.24
npm ERR! argv "/home/udocker/zipkin/zipkin-web/build/nodejs/node-v5.5.0-linux-x64/bin/node" "/home/udocker/zipkin/zipkin-web/node_modules/npm/bin/npm-cli.js" "run-script" "build"
npm ERR! node v5.5.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! zipkin-web@0.0.0 build: `node node_modules/webpack/bin/webpack.js --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zipkin-web@0.0.0 build script 'node node_modules/webpack/bin/webpack.js --bail'.
```

**Comment by eirslett** [comment]
Try running npm install manually inside the docker container? (If you can install npm there)
And see if the file exists?

**Comment by yurishkuro** [comment]
@eirslett how is the webpack being installed now?  I don't see it mentioned in the `npm install` logs.

**Comment by eirslett** [comment]
It's in devDependencies in package.json. When you run npm install, it should install every dependency. (When you run npm install --production, it skips the devDependencies)

**Comment by eirslett** [comment]
Try checking if there's an environment variable in the build, `NODE_ENV=production`. (Which npm could in theory pick up, and then skip installing the devDependencies).

**Comment by yurishkuro** [comment]
Setting `NODE_ENV=development` fixed the build. Is that how it's supposed to be during the build?

**Comment by eirslett** [comment]
It's not supposed to be set to any particular value, but it should not be set to "production" (since it's a build). That is for all node/npm projects in general.

**Comment by codefromthecrypt** [comment]
Yuri, you mind adding/creating README on zipkin-web with this build note?

**Comment by yurishkuro** [comment]
https://github.com/openzipkin/zipkin/pull/975

**Comment by RobertTassy** [comment]
Running npm installed resolved my issue of missing webpack merge - I guess I must've deleted something while I was playing around..
