### ISSUE TITLE
UI refactoring

### ISSUE THREAD

**Issue by eirslett** [openzipkin/zipkin#974]
My plan is to refactor zipkin-web to that the web GUI for Zipkin becomes a pure HTML/JavaScript/CSS frontend on top of zipkin-query's REST API.
A lot of work has already been done:
- introduce webpack as a build system for the frontend
- move bits and pieces of logic from server to client
  Some more to be done:
- render all the mustache templates client-side, but let some business logic happen on the server

The reason there will temporarily be some stuff being done server-side, is that there's a lot of complexity and it would be very risky to rewrite it all in one go. Most of that remaining server-side stuff will be JSON from query-server transformed into other JSON that can be consumed by mustache templates.

Webpack has also introduced babel, a JavaScript cross-compiler that will let us use new ES2015 syntax/features, and it compiles it back to ES5 JavaScript that all browsers support. We should migrate the code base gradually towards ES2015 in the places it makes sense.

The end result of the refactoring would be to move all remaining business logic from zipkin-web into the browser bundle, rewriting it from Scala to JavaScript in the process. Then, we can get rid of zipkin-web entirely and serve the static assets directly from zipkin-query. (Or apache httpd, or nginx...)

**Comment by codefromthecrypt** [comment]
@eirslett so we had some caching issues come up again recently (#718). One thing we've not done is tested things like caching headers from zipkin-web. (ex they are tested on zipkin-query as finatra is a testable framework). Note I'm not trying to discuss cache specifically here, just calling out that zipkin-web is hard to test.

I'm wondering if UI refactoring could get us to a place where we could mount static assets on top of zipkin-query itself? Ex. zipkin-web is simply zipkin-query + static assets. That would allow us to not have to do any routing, which should help performance, and also allow us to inherit any tested configuration, such as cache headers on the api.

**Comment by eirslett** [comment]
Yes, I imagine that zipkin-web (the scala backend) would disappear, and zipkin-query could host the assets directly. The only thing that really remains in that scala backend now, is the logic for transforming trace JSON to mustache JSON.
Caching of API calls might be even better to do in zipkin-query, using Guava cache or something like that. Caching static assets is maybe better to do with ETags. But the impact of loading javascript and css is much lower when they're bundled, since HTTP over TCP gives a per-connection overhead.

**Comment by yurishkuro** [comment]
@eirslett in `zipkin-web/src/main/resources/templates/v2/layout.mustache` I had this diff below to fix nav bar highlighting. The variables isIndexPage/isDependenciesPage were set somewhere in Scala. Where is the best place to set them now?

``` diff
 -            <li class="active"><a href="/">Find a trace</a></li>
 -            <li><a href="/dependency">Dependencies</a></li>
 +            <li {{#isIndexPage}}class="active"{{/isIndexPage}}><a href="/">Find a trace</a></li>
 +            <li {{#isDependenciesPage}}class="active"{{/isDependenciesPage}}><a href="/dependency">Dependencies</a></li>
 +            <li><a href="http://t.uber.com/jaeger">Wiki / Help</a></li>
```

**Comment by yurishkuro** [comment]
@eirslett another question, in `zipkin-web/src/main/resources/templates/v2/index.mustache` we used to have a section that was displayed on the home page (before query was executed), for example:

``` html
{{^queryResults}}
  <div class="alert alert-info" id="help-msg">
    <p>Please select the criteria for your trace lookup.</p>
  </div>
  <div id="logo"></div>
{{/queryResults}}
```

How this section never shows. Is it because the syntax `{{^queryResults}}` is no longer recognized?

**Comment by eirslett** [comment]
Here's a potential solution to nr. 1:
Create a new flight component, (component_ui/navbar.js) and in CommonUI (page/common.js), attach it to the menu element the same way EnvironmentUI is attached. Then, it should listen on an event which, when triggered, should mark the correct menu element as active.
Inside page/default, page/trace and page/dependencies, the event should be fired immediately as the page loads.
Personally I would prefer this solution, but it's a bit more work to implement.

Here's another possible solution to nr. 1:
Use your mustache diff as-is.
In page/common.js, we call `tmpl()` directly without any arguments, but we could have called it like this:

``` javascript
tmpl({
  isIndexPage: true,
  isDependenciesPage: false
})
```

the challenge then is to figure out which menu item should be active. You could do that with something like `const isDependenciesPage = window.location.pathname.indexOf('/dependencies') === 0`
and later on, we can integrate it properly with the frontend router.

**Comment by eirslett** [comment]
Regarding nr 2 - that sounds like a bug that I'll have to investigate. queryResults should be recognized...

**Comment by codefromthecrypt** [comment]
opened a sub-topic on configuration defaults https://github.com/openzipkin/zipkin/issues/993
