### ISSUE TITLE
Importing into (or linking as a) Intellij IDEA Gradle project fails

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#977]
Currently, we have to use offline `./gradlew cleanIdea idea` then File, Open vs Intellij's Gradle integration. 

For example, if using File, New Project from existing sources.. choosing Gradle, you will likely get errors about classes in the `com.twitter.zipkin.thriftscala` package not being found.

**Comment by jorgheymans** [comment]
Gradle huh ?
