### ISSUE TITLE
IDEA build failures until config files are removed from being considered "source"

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#978]
reported by @yurishkuro 

> not sure if other people get that, but when I import the project on a clean repo, IntelliJ cannot build it because of configuration files in zipkin-collector-service/config and zipkin-query-service/config. These dirs are somehow added as both test resource and some other type, and I have to open project settings and unselect them to make sure they are only included as test resource (so that IntelliJ doesn't try to compile them).
#544 attempted to solve this issue

**Comment by codefromthecrypt** [comment]
In my environment, `gradle/idea-mark-config-dir-as-resource.gradle` seems to have worked, as I don't have to do anything to have the resulting idea files correct.

``` bash
$ ./gradlew cleanIdea idea
--snip--
$ grep 'file://\$MODULE_DIR\$/config' */*.iml
zipkin-collector-service/zipkin-collector-service.iml:      <sourceFolder url="file://$MODULE_DIR$/config" isTestSource="false" type="java-resource"/>
zipkin-query-service/zipkin-query-service.iml:      <sourceFolder url="file://$MODULE_DIR$/config" isTestSource="false" type="java-resource"/>
```

**Comment by codefromthecrypt** [comment]
@yurishkuro do you mind checking to see what your local environment generates? (ex the same grep before you open the project in intellij?)

**Comment by yurishkuro** [comment]
I get the same:

```
$ grep 'file://\$MODULE_DIR\$/config' */*.iml
zipkin-collector-service/zipkin-collector-service.iml:      <sourceFolder url="file://$MODULE_DIR$/config" isTestSource="false" type="java-resource"/>
zipkin-query-service/zipkin-query-service.iml:      <sourceFolder url="file://$MODULE_DIR$/config" isTestSource="false" type="java-resource"/>
```

Actually just tried clean import from clean zipkin repo and didn't get compile errors. Maybe it's something about our fork, even though #544 is present.

**Comment by eirslett** [comment]
Can we rename them from .scala to .scalaconf? Maybe the IDE doesn't detect them as source code then.

**Comment by jorgheymans** [comment]
Both scala and gradle are no longer used in zipkin, Intellij imports the maven project just fine now.
