### ISSUE TITLE
minimum propagated state for zipkin

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#987]
I had a chat with @dsyer and a question came up about if parent_id is actually something that's required to be propagated. Local to the process, it isn't needed, as a child would take the current id. This comes up when reporting spans to the collector.

If a patch to a span includes only the trace id and span id, then some storage implementations would need to be revised to conditionally update parent_id. (ex don't overwrite parent_id with null).

The above storage issue aside, I'm wondering if there are other reasons why parent_id is propagated?

**Comment by codefromthecrypt** [comment]
Finagle seems to think only trace id and span id are required, for example, but that makes sense as the root span won't have a parent. The interesting part is whether it should be ok for an update to an existing child span to omit the parent_id..

``` scala
    val All = Seq(TraceId, SpanId, ParentSpanId, Sampled, Flags)
    val Required = Seq(TraceId, SpanId)
```

https://github.com/twitter/finagle/blob/master/finagle-http/src/main/scala/com/twitter/finagle/http/Codec.scala#L261

**Comment by jcarres-mdsol** [comment]
if we have:
A calls B calls C
and in the same request
A calls B calls D

You would disambiguate the tree by looking at timestamps and Endpoint's IPs?

**Comment by codefromthecrypt** [comment]
the tree is still created by trace id, span id, parent id.

The scenario in question is..
I start a span on A for A calls B. Instrumentation sends out-of band, to
the collector,  (trace id, span id, parent id, name) + client annotations.

A propagates in-band (trace id, span id) to B.

Can instrumentation on B get away with just sending (trace id, span id) +
server annotations the collector? Right now, we also send parent id in-band.

**Comment by jcarres-mdsol** [comment]
I see. 
Because ServiceA will already create a spanID before calling ServiceB. 
Then ServiceB just uses that spanID on SR/SS , creates a new spanID on CS/CR to next service and that one has a parentID which is sent to zipkin but it is **not** sent to the next service. The only thing serviceC needs to know is the current spanID and then it can create children from that.
It will also work for localspans on serviceB as they will be all children from the spanID created by serviceA

Seems that should work

**Comment by jorgheymans** [comment]
Closing this what seems to be a food-for-thought issue. AFAICT `parentSpanId` is always propagated unless root-span. See https://github.com/openzipkin/b3-propagation#parentspanid. Feel free to correct me if i'm out in the wrong here or if it's more nuanced.
