### ISSUE TITLE
Configuration for zipkin-web

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#993]
As zipkin-web decouples from the scala backend, the issue of javascript configuration (particularly defaults) become foreground. Particularly, query limit, query lookback, and dependencies lookback are all inherited from scala processes at the moment.

What's the cleanest way to attack this problem? We've discussed a config endpoint.. are there any other ways, or is this the best?

https://github.com/openzipkin/zipkin/commit/088580067517601a7b2ee07ca37f964e2da32e9f#commitcomment-16230719

**Comment by eirslett** [comment]
The current implementation uses a `/config.json` endpoint, which will suffice until it doesn't.
