### ISSUE TITLE
support /heath endpoint

### ISSUE THREAD

**Issue by jcarres-mdsol** [openzipkin/zipkin#994]
In our testing tools we are checking that the zipkin query server is running but doing a HEAD request to the API.
This will return 404
But if we do a GET request it will respond normally with 200.
That's an extra burden (to be sending data when it does need to) and the API should be responding to HEAD also.

Optionally or in addition the zipkin query server could have some /status or similar endpoint to check its health.

**Comment by yurishkuro** [comment]
@jcarres-mdsol do you have suggestion on what the health endpoint should be checking?  I often see those implemented as `return OK`, which only tells the server is running, not that it's healthy. If we decide, for example, to include some db query in the health check, then it may require extending span storage api.

**Comment by eirslett** [comment]
It would be nice for the frontend UI to poll on a health endpoint as well. I think it sould be sufficient to return OK, to verify that the server is running and reachable. We could then show a simple "query server unreachable" message, which is more helpful than a UI that doesn't work.

**Comment by codefromthecrypt** [comment]
My guess is the most important  state is if the spanstore connection is
OK.  I made a interface like this at Netflix and then exported it to the
health check handler. It is better than just http and simpler than checking
many things.

Basically we add a method span stores need to implement that returns true
if OK.  Span stores use the cheapest valid way to do that. We can export
that to an http call (which load balancers etc can check)

Ex from a DNS project

https://github.com/Netflix/denominator/blob/master/route53/src/main/java/denominator/route53/HostedZonesReadable.java

**Comment by jcarres-mdsol** [comment]
Yes, usually is either "OK"  or a DB check. 
We can add the route now with a simple "OK" and later as the check in the spanstores are implemented upgrade it to check these.

**Comment by codefromthecrypt** [comment]
looks like there's an OK in the query server already:

https://github.com/twitter/finatra/blob/master/inject/inject-server/src/main/scala/com/twitter/inject/server/TwitterServer.scala#L112

$ curl localhost:9901/health

OK
Do we want to map health onto the main port? (9411)

**Comment by jcarres-mdsol** [comment]
It will be useful, else you need to open firewall ports just because of that

**Comment by codefromthecrypt** [comment]
ok, so localhost:9411/health?

**Comment by jcarres-mdsol** [comment]
Sounds good!

On Tue, Feb 23, 2016 at 10:39 AM, Adrian Cole notifications@github.com
wrote:

> ok, so localhost:9411/health?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openzipkin/zipkin/issues/994#issuecomment-187624982.

## 

_Jordi Polo Carres_ | Software Architect  | Medidata Solutions Worldwide
http://www.mdsol.com/

**Comment by eirslett** [comment]
This was fixed in #997.
