### ISSUE TITLE
The total time of each span seems incorrect

### ISSUE THREAD

**Issue by lycplus** [openzipkin/zipkin#998]
In the summary page (home page)，zipkin will show a summary time of each span below each trace. We have many redis spans each costs 300us+, but in the summary page, it shows `redis * 232 5ms`,`5ms/232=21.5us`, so, I think, may be the summary data is incorrect.

**Comment by shakuzen** [comment]
As far as I can tell from spot checking with the latest version of Zipkin, it appears the time shown on the traces view for each service name is the **longest** span duration for that service name, which perhaps isn't apparent.

**Comment by codefromthecrypt** [comment]
@liyichao check this out.. it is confirmed (even if not necessarily the right thing to do) #2234

**Comment by lycplus** [comment]
Then I misunderstand the meaning, which is not that straightforward. Close the issue if you think it is not a problem.

**Comment by codefromthecrypt** [comment]
there was a bug actually.. https://github.com/openzipkin/zipkin/pull/2235

**Comment by codefromthecrypt** [comment]
#2488 will add some clarifications also
