### ISSUE TITLE
[1.33.2] Collapse + button in Trace detail page not working

### ISSUE THREAD

**Issue by lycplus** [openzipkin/zipkin#999]
Using the data in tracegen, when clicking the + button at the left of  service `natoque`, the service does not expand.

Before clicking +:

<img width="1400" alt="2016-02-24 14 40 52" src="https://cloud.githubusercontent.com/assets/2576762/13277566/afeab0ca-db04-11e5-878e-14232d738967.png">

After clicking +:

<img width="1411" alt="2016-02-24 14 42 56" src="https://cloud.githubusercontent.com/assets/2576762/13277612/030cc004-db05-11e5-9f50-1eff630475cb.png">

**Comment by codefromthecrypt** [comment]
tracegen doesn't return the same data twice. to look into this, we'd need the data that you are seeing. you can grab it via http://your_host:9411/api/v1/trace/trace-id

**Comment by lycplus** [comment]
When I click expand all, it expands as expected.

**Comment by lycplus** [comment]
[trace.txt](https://github.com/openzipkin/zipkin/files/144128/trace.txt)

**Comment by eirslett** [comment]
The +/- buttons haven't worked for some time now. Maybe the best way to find the problem is to do a git bisect? We'd need to go 6 months back in time, I guess.

**Comment by codefromthecrypt** [comment]
fyi on this and other ui issues, I'd suggest holding off until zipkin-web is javascript only. There's a number of small issues, but sands are shifting. Once the big refactor is over, things will be easier. https://github.com/openzipkin/zipkin/pull/1004
